// @ts-nocheck
export interface CustomerType {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  longDescription: string;
  services: string[]; // top service slugs for this customer type
  painPoints: string[];
  creditHighlights: string[];
}

export const CUSTOMER_TYPES: CustomerType[] = [
  {
    slug: "homeowners",
    name: "Homeowners",
    shortName: "Homeowners",
    description: "Every home service you need, from one reliable company. HVAC, plumbing, electrical, painting, cleaning, handyman, and 34 more trades — starting at $99/hour.",
    longDescription: "As a homeowner, you accumulate home projects the way other people accumulate emails — faster than you can clear them. The faucet that drips, the light fixture you keep meaning to swap, the exterior that needs paint, the HVAC tune-up you forgot about, the drywall patch from last year's accident. Home Services Co handles all of it under one phone number, one account, and one standard — starting at $99/hour with upfront pricing on every job.",
    services: ["hvac-services", "plumbing", "electrical", "handyman-services", "house-cleaning", "painting"],
    painPoints: ["Too many vendors for too many small jobs", "Never knowing if a quote is fair", "Vendors who ghost or no-show", "No time to chase three different contractors", "Surprise fees on the final invoice"],
    creditHighlights: ["Starting at $99/hour across 40 services", "Upfront pricing — the invoice matches the estimate", "Same-day availability in most markets", "Licensed, insured, background-checked technicians"],
  },
  {
    slug: "renters-movers",
    name: "Renters & Movers",
    shortName: "Renters",
    description: "Moving, cleaning, handyman repairs, and move-in/out services. One company handles everything — starting at $99/hour.",
    longDescription: "Moving involves a dozen small home services — cleaning the old place, repairing the drywall damage from a misplaced nail, assembling the furniture you just unboxed at the new place, hanging curtain rods, installing the smart lock. Home Services Co consolidates every one of those jobs into a single vendor relationship. One phone call handles the move-out clean, the handyman punch list, and the setup at the new place.",
    services: ["moving-services", "house-cleaning", "handyman-services", "furniture-assembly", "locksmith-services"],
    painPoints: ["Coordinating too many vendors during a move", "Move-out cleaning deadlines", "Furniture assembly backlog at the new place", "Handyman repairs needed before deposit return", "Rekeying a new home safely"],
    creditHighlights: ["One vendor for every moving-related service", "Move-out clean, handyman, assembly, locks — all at $99/hour", "Same-day availability for tight move-in/out timelines", "Licensed and insured — matters if anything breaks"],
  },
  {
    slug: "property-managers",
    name: "Property Managers & Landlords",
    shortName: "Property Mgrs",
    description: "One vendor for 40 trades across every unit in your portfolio. Dedicated accounts, consolidated invoicing, priority scheduling.",
    longDescription: "Every day a unit sits vacant is lost rent. Property managers juggle dozens of vendors — an HVAC company for one set of repairs, a plumber for another, a cleaner, a handyman, a painter. Home Services Co consolidates all of it into a single vendor relationship with a dedicated account, priority scheduling, consistent technicians, and one monthly invoice across every trade and every property.",
    services: ["house-cleaning", "handyman-services", "plumbing", "electrical", "painting", "appliance-repair"],
    painPoints: ["Too many vendors across the portfolio", "Inconsistent quality between units", "Every vacant day is lost rent", "Reconciling multiple invoices each month", "Finding a vendor who will actually return calls"],
    creditHighlights: ["One vendor, 40 services, every unit", "Dedicated account manager and priority scheduling", "Consolidated monthly invoicing", "Starting at $99/hour across every trade"],
  },
  {
    slug: "realtors",
    name: "Realtors & Real Estate Agents",
    shortName: "Realtors",
    description: "Pre-listing prep, inspection repairs, and post-close punch lists. One vendor, 40 services, fast turnaround.",
    longDescription: "Getting a home market-ready touches a dozen trades — cleaning, painting, handyman repairs, landscaping, pressure washing, minor plumbing and electrical. Home Services Co is the single vendor who handles all of it. Realtors use us for pre-listing prep, inspection repair items, and buyer/seller requested work. Starting at $99/hour with upfront pricing — which makes the conversation with sellers easier because you can give them a real number instead of a range.",
    services: ["painting", "house-cleaning", "handyman-services", "pressure-washing", "landscaping", "carpet-cleaning"],
    painPoints: ["Pre-listing prep needed fast", "Inspection repair items from multiple trades", "Sellers resist spending on cosmetic work", "Coordinating multiple vendors against a closing date", "Needing one trusted point of contact for every service"],
    creditHighlights: ["Pre-listing packages starting at $99/hour", "Fast turnaround for inspection repair items", "One vendor across cleaning, painting, handyman, landscaping", "Honest upfront pricing for seller conversations"],
  },
  {
    slug: "businesses",
    name: "Businesses & Offices",
    shortName: "Businesses",
    description: "Commercial cleaning, HVAC, electrical, handyman, and facility services. One vendor for every building service you need.",
    longDescription: "Small businesses and offices need the same services as homes — HVAC, electrical, plumbing, cleaning, handyman, painting, flooring — just more of them, on more predictable schedules. Home Services Co offers commercial accounts with dedicated scheduling, consistent technicians, and one consolidated invoice across every service. After-hours and weekend work available at the same starting rate.",
    services: ["hvac-services", "electrical", "house-cleaning", "handyman-services", "painting", "carpet-cleaning"],
    painPoints: ["Too many vendors for facility maintenance", "Scheduling around business hours", "Inconsistent service across locations", "Managing multiple commercial accounts", "Needing certificates of insurance on file"],
    creditHighlights: ["One vendor for every commercial facility service", "After-hours service at the same starting rate", "Certificates of insurance within 24 hours", "Starting at $99/hour across 40 services"],
  },
  {
    slug: "estate-managers",
    name: "Estate Managers & Families",
    shortName: "Estates",
    description: "Estate prep, deep cleaning, junk removal, painting, and handyman punch lists. One vendor for the whole property.",
    longDescription: "Clearing and preparing an estate touches every home service there is — cleaning, junk removal, handyman repairs, painting, carpet cleaning, landscaping, and sometimes HVAC, plumbing, and electrical work. Home Services Co consolidates all of it. One project manager coordinates the full scope, with upfront pricing on every piece so families and executors know exactly what they're spending before work starts.",
    services: ["house-cleaning", "junk-removal", "painting", "handyman-services", "carpet-cleaning", "landscaping"],
    painPoints: ["Emotionally overwhelming volume of work", "Time pressure from property sales or leases", "Too many vendors to coordinate remotely", "Need clear pricing up front for estate accounting", "Need respectful, patient crews"],
    creditHighlights: ["One project manager for the full estate scope", "Upfront pricing for estate accounting", "Respectful, patient technicians across every trade", "Starting at $99/hour with consolidated invoicing"],
  },
  {
    slug: "contractors",
    name: "Contractors & Builders",
    shortName: "Contractors",
    description: "Subcontracting, punch-list work, specialty trades, and cleanup. Licensed trades on-call when your crew is booked.",
    longDescription: "Contractors and builders use Home Services Co for specialty trades, punch-list work, and overflow when their own crews are booked. Licensed HVAC, plumbing, electrical, flooring, drywall, painting, and more — available at $99/hour with upfront pricing and same-day scheduling. Recurring accounts available for ongoing project needs across multiple job sites.",
    services: ["drywall-repair", "painting", "flooring-installation", "junk-removal", "carpentry", "electrical"],
    painPoints: ["Specialty trades booked out for weeks", "Punch-list work delaying project completion", "Need licensed subs who show up when promised", "Overflow when own crews are booked", "Job site cleanup between phases"],
    creditHighlights: ["Licensed specialty trades on-call", "Same-day availability for urgent punch-list items", "Starting at $99/hour across 40 trades", "Recurring accounts for ongoing project needs"],
  },
  {
    slug: "churches-nonprofits",
    name: "Churches & Nonprofits",
    shortName: "Nonprofits",
    description: "Facility maintenance, cleaning, handyman, and specialty services for houses of worship and nonprofits.",
    longDescription: "Churches, nonprofits, and community organizations typically operate on tight budgets with volunteer-led facilities committees. Home Services Co offers straightforward pricing (starting at $99/hour) across every facility service — cleaning, HVAC, electrical, plumbing, painting, handyman, landscaping. One vendor, one invoice, one account manager. Transparent pricing so your board and facilities committee can plan.",
    services: ["house-cleaning", "hvac-services", "handyman-services", "electrical", "painting", "landscaping"],
    painPoints: ["Tight facilities budgets", "Volunteer-led committees lack vendor relationships", "Need transparent pricing for board approval", "Decades of deferred maintenance", "Need respectful handling of sacred spaces"],
    creditHighlights: ["Transparent pricing for board planning", "One vendor across every facility service", "Starting at $99/hour for straightforward budgeting", "Respectful technicians for sacred and community spaces"],
  },
  {
    slug: "schools-universities",
    name: "Schools & Universities",
    shortName: "Schools",
    description: "Facility services, end-of-semester cleanouts, and recurring maintenance across campus.",
    longDescription: "Schools and universities have complex facility service needs — end-of-semester cleanouts, dorm turnover, classroom refreshes, lab equipment moves, HVAC maintenance, electrical work, and general handyman service. Home Services Co handles all of it with dedicated account management, consolidated invoicing, and scheduling coordinated around the academic calendar.",
    services: ["house-cleaning", "handyman-services", "junk-removal", "hvac-services", "painting", "electrical"],
    painPoints: ["Massive facility volume during academic transitions", "Must work around academic calendar", "Multiple buildings, one vendor relationship", "Budget restrictions demand predictable pricing", "Need coordinated service across campus"],
    creditHighlights: ["One vendor across every facility service", "Academic-calendar-aware scheduling", "Starting at $99/hour with predictable budgeting", "Consolidated campus-wide invoicing"],
  },
  {
    slug: "hotels-hospitality",
    name: "Hotels & Hospitality",
    shortName: "Hotels",
    description: "FF&E refreshes, renovation work, cleaning, HVAC, and facility services for hospitality properties.",
    longDescription: "Hotels, motels, and vacation rentals need ongoing facility services — HVAC maintenance (critical for guest comfort), room-level cleaning and refreshes, handyman repairs, painting, flooring, and full renovation coordination. Home Services Co offers discreet off-hours service to minimize guest disruption, dedicated account management, and consolidated invoicing across the property or portfolio.",
    services: ["hvac-services", "house-cleaning", "handyman-services", "painting", "flooring-installation", "carpet-cleaning"],
    painPoints: ["Must minimize guest disruption", "Brand standards require consistent quality", "Multiple properties in a portfolio", "Tight turnaround between bookings", "Need reliable HVAC response for guest comfort"],
    creditHighlights: ["Discreet off-hours service across every trade", "Dedicated account management across portfolio", "Consolidated invoicing for multi-property operators", "Starting at $99/hour with same-day availability"],
  },
  {
    slug: "warehouses",
    name: "Warehouses & Industrial",
    shortName: "Warehouses",
    description: "Commercial HVAC, electrical, plumbing, and facility services for warehouses and industrial properties.",
    longDescription: "Warehouses and industrial properties need scaled-up versions of the same home services — HVAC (often commercial-grade), electrical (often three-phase), plumbing, facility cleaning, concrete, and more. Home Services Co handles light-to-medium commercial work with licensed trades and dedicated account management.",
    services: ["hvac-services", "electrical", "plumbing", "concrete-services", "handyman-services"],
    painPoints: ["Commercial facility needs at scale", "Heavy industrial equipment access", "Lease deadlines for build-out and clear-out", "Need licensed, insured commercial trades", "Consolidated invoicing across multiple services"],
    creditHighlights: ["Licensed commercial trades across every service", "Dedicated account management", "Starting at $99/hour with itemized commercial materials", "Consolidated monthly invoicing"],
  },
  {
    slug: "retail",
    name: "Retail & Stores",
    shortName: "Retail",
    description: "Store build-outs, remodels, cleaning, handyman, and facility services for retail locations.",
    longDescription: "Retail closures, remodels, and tenant build-outs involve painting, flooring, electrical, handyman work, cleaning, and specialty trades. Home Services Co handles all of it with dedicated project coordination and the ability to work around store hours. Retail chains with multiple locations get consolidated account management across the portfolio.",
    services: ["painting", "flooring-installation", "electrical", "handyman-services", "house-cleaning", "carpet-cleaning"],
    painPoints: ["Build-out and remodel deadlines", "Must work around store hours", "Multi-location consistency requirements", "Landlord build-out requirements", "Need one vendor for every trade"],
    creditHighlights: ["After-hours service at the same starting rate", "Multi-location account management", "Starting at $99/hour across every trade", "Consolidated invoicing for retail chains"],
  },
  {
    slug: "seniors-downsizers",
    name: "Seniors & Downsizers",
    shortName: "Seniors",
    description: "Compassionate, patient service for older adults transitioning to smaller homes or assisted living.",
    longDescription: "Downsizing touches every home service — cleaning, junk removal, handyman repairs, painting, carpet cleaning, and sometimes HVAC, plumbing, and electrical. Home Services Co approaches senior transitions with patience and respect. Our technicians work at the pace of the person, not the clock. Family members coordinating from out of town get a single point of contact and consolidated invoicing instead of juggling a dozen vendors remotely.",
    services: ["house-cleaning", "junk-removal", "handyman-services", "painting", "carpet-cleaning", "moving-services"],
    painPoints: ["Emotionally overwhelming transition", "Family members coordinating from out of town", "Physical limitations prevent DIY", "Need patient, respectful crews", "Too many vendors to juggle remotely"],
    creditHighlights: ["Single point of contact for every service", "Patient, respectful technicians", "Consolidated invoicing for remote family coordination", "Starting at $99/hour across 40 services"],
  },
];
