// @ts-nocheck
import type { Roadway } from "./roadways";

/**
 * NYC bridges. Covers East River, Hudson, Harlem River, Bronx-Whitestone-Throgs Neck
 * crossings, the Outer Harbor crossings, and the smaller MTA/DOT spans that
 * generate roadside calls.
 */
export const BRIDGES: Roadway[] = [
  // ── EAST RIVER ─────────────────────────────────────────────────────────────
  {
    slug: "brooklyn-bridge",
    name: "Brooklyn Bridge",
    kind: "bridge",
    subType: "Suspension Bridge (East River)",
    boroughs: ["manhattan", "brooklyn"],
    segment: "Connects Manhattan's City Hall area to Cadman Plaza in Brooklyn Heights. Cars only — no commercial trucks over 3 tons or vehicles taller than 11 feet.",
    hazards: [
      "Strict 3-ton commercial vehicle weight limit — box trucks regularly get caught and need recovery off the bridge.",
      "11-foot height limit catches U-Haul trucks every weekend.",
      "Pedestrian and cyclist promenade above means no shoulder relief for a roadside call.",
      "Approach incidents on the Manhattan side at Frankfort and Park Row are routine.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "winch-out-recovery", "flat-tire-change"],
    lanes: "3 lanes each direction",
    length: "5,989 ft",
    relatedNeighborhoods: [
      { state: "manhattan", city: "financial-district" },
      { state: "manhattan", city: "two-bridges" },
      { state: "brooklyn", city: "brooklyn-heights" },
      { state: "brooklyn", city: "dumbo" },
    ],
    geo: { lat: 40.7061, lon: -73.9969 },
  },
  {
    slug: "manhattan-bridge",
    name: "Manhattan Bridge",
    kind: "bridge",
    subType: "Suspension Bridge (East River)",
    boroughs: ["manhattan", "brooklyn"],
    segment: "Connects Canal Street/Bowery in Manhattan to Flatbush Avenue Extension in Downtown Brooklyn. Carries cars, trucks, BMT subway lines, pedestrians, and cyclists.",
    hazards: [
      "Heavy commercial truck volume produces frequent tire damage from debris.",
      "Subway-train vibration on the lower deck startles new drivers into sudden lane changes.",
      "Canal Street approach stacks daily.",
      "Wind events on the upper deck create control issues for high-sided trucks.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "jump-start"],
    lanes: "7 lanes total (3 upper + 4 lower)",
    length: "6,855 ft",
    relatedNeighborhoods: [
      { state: "manhattan", city: "chinatown" },
      { state: "manhattan", city: "two-bridges" },
      { state: "brooklyn", city: "dumbo" },
      { state: "brooklyn", city: "downtown-brooklyn" },
    ],
    geo: { lat: 40.7075, lon: -73.9903 },
  },
  {
    slug: "williamsburg-bridge",
    name: "Williamsburg Bridge",
    kind: "bridge",
    subType: "Suspension Bridge (East River)",
    boroughs: ["manhattan", "brooklyn"],
    segment: "Connects Delancey Street in Manhattan's Lower East Side to Bedford Avenue / Roebling Street in Williamsburg. Carries cars, trucks, the J/M/Z subway lines, pedestrians, and cyclists.",
    hazards: [
      "Heavy commercial truck volume produces frequent tire damage.",
      "Delancey approach stacks daily.",
      "Bicycle path heavy use means roadway-side door-strike risk on the Brooklyn side.",
      "Wind events on the open deck create control issues for high-sided trucks.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "jump-start"],
    lanes: "8 lanes total",
    length: "7,308 ft",
    relatedNeighborhoods: [
      { state: "manhattan", city: "lower-east-side" },
      { state: "manhattan", city: "two-bridges" },
      { state: "brooklyn", city: "williamsburg" },
    ],
    geo: { lat: 40.7137, lon: -73.9722 },
  },
  {
    slug: "ed-koch-queensboro-bridge",
    name: "Ed Koch Queensboro Bridge (59th Street Bridge)",
    shortName: "Queensboro Bridge",
    kind: "bridge",
    subType: "Cantilever Bridge (East River)",
    boroughs: ["manhattan", "queens"],
    segment: "Connects the Upper East Side at 59th and 2nd Avenue to Long Island City at Queens Plaza. Carries cars, trucks, pedestrians, and cyclists. Free crossing.",
    hazards: [
      "Heavy free-crossing volume backs up daily — multi-hour delays during rush.",
      "Upper-deck Manhattan-bound traffic stacks in the morning.",
      "59th Street outer-roadway exits (to Sutton Place) generate constant fender-benders.",
      "Wind events on the upper deck create control issues for high-sided trucks.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "jump-start"],
    lanes: "9 lanes total (upper + lower)",
    length: "7,449 ft",
    relatedNeighborhoods: [
      { state: "manhattan", city: "midtown-east" },
      { state: "manhattan", city: "upper-east-side" },
      { state: "queens", city: "long-island-city" },
    ],
    geo: { lat: 40.7565, lon: -73.9551 },
  },
  {
    slug: "rfk-triboro-bridge",
    name: "Robert F. Kennedy (Triboro) Bridge",
    shortName: "RFK / Triboro",
    kind: "bridge",
    subType: "Three-Way Span (East / Harlem Rivers)",
    boroughs: ["manhattan", "queens", "bronx"],
    segment: "Three-borough span connecting Manhattan (East Harlem at 125th), Queens (Astoria), and the Bronx (Randalls Island and Mott Haven via Bruckner). MTA-tolled.",
    hazards: [
      "Toll plaza approach generates rear-ends in heavy rain.",
      "Cross-borough merges produce constant lane-change incidents.",
      "Heavy commercial truck volume from Bronx Bruckner traffic.",
      "Pothole runs on the Randalls Island connector tear sidewalls.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "winch-out-recovery", "commercial-towing"],
    lanes: "Variable by leg",
    length: "12,300 ft total",
    relatedNeighborhoods: [
      { state: "manhattan", city: "east-harlem" },
      { state: "queens", city: "astoria" },
      { state: "bronx", city: "mott-haven" },
    ],
    geo: { lat: 40.7896, lon: -73.9251 },
  },

  // ── HUDSON RIVER ───────────────────────────────────────────────────────────
  {
    slug: "george-washington-bridge",
    name: "George Washington Bridge",
    shortName: "GWB",
    kind: "bridge",
    subType: "Suspension Bridge (Hudson River)",
    boroughs: ["manhattan"],
    segment: "Connects Washington Heights in Manhattan to Fort Lee, NJ. Upper deck (8 lanes) and lower deck (6 lanes) carry I-95, US-1, US-9, and US-46. World's busiest motor-vehicle bridge.",
    hazards: [
      "Routinely ranked America's busiest motor-vehicle bridge — multi-hour delays daily.",
      "Heavy commercial truck volume produces constant tire damage from debris.",
      "Wind events on the upper deck create control issues for high-sided trucks.",
      "Approach incidents on the Manhattan side at the Cross Bronx / Trans-Manhattan are routine.",
      "Lower-deck breakdowns block live lanes with no relief.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "winch-out-recovery", "commercial-towing"],
    lanes: "14 lanes total (8 upper + 6 lower)",
    length: "4,760 ft",
    relatedNeighborhoods: [
      { state: "manhattan", city: "washington-heights" },
      { state: "manhattan", city: "fort-george" },
    ],
    geo: { lat: 40.8517, lon: -73.9527 },
  },

  // ── BRONX / QUEENS ────────────────────────────────────────────────────────
  {
    slug: "throgs-neck-bridge",
    name: "Throgs Neck Bridge",
    kind: "bridge",
    subType: "Suspension Bridge (East River)",
    boroughs: ["queens", "bronx"],
    segment: "Connects Bay Terrace in Queens (via the Clearview Expressway) to Throgs Neck in the Bronx (via the Cross Bronx Expressway). MTA-tolled.",
    hazards: [
      "Toll plaza approach generates rear-ends in heavy rain.",
      "Wind events on the open span create control issues for high-sided trucks.",
      "Heavy commercial truck volume from the I-95 connection.",
      "No-shoulder design means breakdowns block live lanes.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "winch-out-recovery"],
    lanes: "6 lanes total",
    length: "2,910 ft",
    relatedNeighborhoods: [
      { state: "queens", city: "bay-terrace" },
      { state: "queens", city: "douglaston" },
      { state: "bronx", city: "throgs-neck" },
    ],
    geo: { lat: 40.8024, lon: -73.7942 },
  },
  {
    slug: "bronx-whitestone-bridge",
    name: "Bronx-Whitestone Bridge",
    shortName: "Whitestone Bridge",
    kind: "bridge",
    subType: "Suspension Bridge (East River)",
    boroughs: ["queens", "bronx"],
    segment: "Connects Whitestone in Queens (via the Whitestone Expressway) to the Hutchinson River Parkway in the Bronx. MTA-tolled.",
    hazards: [
      "Toll plaza approach generates rear-ends in heavy rain.",
      "Wind events on the open span create control issues for high-sided trucks.",
      "Tight on/off ramps on both sides generate merge incidents.",
      "Whitestone Expressway approach stacks daily.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "winch-out-recovery"],
    lanes: "6 lanes total",
    length: "2,300 ft",
    relatedNeighborhoods: [
      { state: "queens", city: "whitestone" },
      { state: "queens", city: "college-point" },
      { state: "bronx", city: "pelham-bay" },
    ],
    geo: { lat: 40.8062, lon: -73.8347 },
  },
  {
    slug: "henry-hudson-bridge",
    name: "Henry Hudson Bridge",
    kind: "bridge",
    subType: "Arch Bridge (Harlem River Ship Canal)",
    boroughs: ["manhattan", "bronx"],
    segment: "Connects Inwood in Manhattan to Spuyten Duyvil and Riverdale in the Bronx via the Henry Hudson Parkway. MTA-tolled, no-cash (E-ZPass and pay-by-mail only).",
    hazards: [
      "Commercial vehicles banned on the parkway — box trucks regularly need recovery off the bridge.",
      "Toll plaza approach generates rear-ends in heavy rain.",
      "Wind events on the open span.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "winch-out-recovery", "flat-tire-change"],
    lanes: "7 lanes total (upper + lower)",
    length: "2,000 ft",
    relatedNeighborhoods: [
      { state: "manhattan", city: "inwood" },
      { state: "bronx", city: "riverdale" },
    ],
    geo: { lat: 40.8782, lon: -73.9242 },
  },

  // ── HARLEM RIVER (Manhattan-Bronx) — small spans ─────────────────────────
  {
    slug: "willis-avenue-bridge",
    name: "Willis Avenue Bridge",
    kind: "bridge",
    subType: "Swing Bridge (Harlem River)",
    boroughs: ["manhattan", "bronx"],
    segment: "Connects East Harlem (1st Ave at 125th) to Mott Haven in the Bronx. Northbound traffic from Manhattan.",
    hazards: [
      "Heavy commercial truck volume from the Bruckner connection.",
      "Approach incidents at the 125th and 1st intersection.",
      "Pothole runs on the bridge deck tear sidewalls.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "flat-tire-change", "jump-start"],
    lanes: "4 lanes northbound",
    length: "3,212 ft",
    relatedNeighborhoods: [
      { state: "manhattan", city: "east-harlem" },
      { state: "bronx", city: "mott-haven" },
    ],
    geo: { lat: 40.8024, lon: -73.9285 },
  },
  {
    slug: "3rd-avenue-bridge",
    name: "Third Avenue Bridge",
    kind: "bridge",
    subType: "Swing Bridge (Harlem River)",
    boroughs: ["manhattan", "bronx"],
    segment: "Connects East Harlem (3rd Ave at 129th) to Mott Haven in the Bronx. Southbound traffic into Manhattan.",
    hazards: [
      "Heavy commercial truck volume from the Bronx Bruckner approach.",
      "Approach incidents at the 129th and 3rd intersection.",
      "Pothole runs on the bridge deck tear sidewalls.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "flat-tire-change", "jump-start"],
    lanes: "5 lanes southbound",
    length: "2,800 ft",
    relatedNeighborhoods: [
      { state: "manhattan", city: "east-harlem" },
      { state: "bronx", city: "mott-haven" },
    ],
    geo: { lat: 40.8050, lon: -73.9301 },
  },
  {
    slug: "madison-avenue-bridge",
    name: "Madison Avenue Bridge",
    kind: "bridge",
    subType: "Swing Bridge (Harlem River)",
    boroughs: ["manhattan", "bronx"],
    segment: "Connects Madison Avenue at 138th in Harlem to East 138th Street in Mott Haven.",
    hazards: [
      "Approach incidents at 138th and Madison.",
      "Heavy daytime livery and rideshare cut-through.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "jump-start", "lockout-service"],
    lanes: "4 lanes total",
    length: "1,892 ft",
    relatedNeighborhoods: [
      { state: "manhattan", city: "harlem" },
      { state: "bronx", city: "mott-haven" },
    ],
    geo: { lat: 40.8132, lon: -73.9337 },
  },
  {
    slug: "macombs-dam-bridge",
    name: "Macombs Dam Bridge",
    kind: "bridge",
    subType: "Swing Bridge (Harlem River)",
    boroughs: ["manhattan", "bronx"],
    segment: "Connects 155th Street in Manhattan (Polo Grounds / Washington Heights edge) to the Bronx near Yankee Stadium and the Major Deegan.",
    hazards: [
      "Yankee Stadium event traffic generates extreme delays game days.",
      "Heavy commercial truck volume from the Deegan connection.",
      "Pothole runs on the bridge deck tear sidewalls.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "flat-tire-change", "jump-start"],
    lanes: "4 lanes total",
    length: "2,540 ft",
    relatedNeighborhoods: [
      { state: "manhattan", city: "washington-heights" },
      { state: "manhattan", city: "harlem" },
      { state: "bronx", city: "concourse" },
    ],
    geo: { lat: 40.8275, lon: -73.9320 },
  },
  {
    slug: "washington-bridge",
    name: "Washington Bridge",
    kind: "bridge",
    subType: "Arch Bridge (Harlem River)",
    boroughs: ["manhattan", "bronx"],
    segment: "Connects 181st Street in Washington Heights to University Avenue in the Bronx, carrying westbound Cross Bronx Expressway traffic toward the GWB.",
    hazards: [
      "GWB-bound traffic stacks every weekday afternoon.",
      "Heavy commercial truck volume from the Cross Bronx connection.",
      "No-shoulder design means breakdowns block live lanes.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "commercial-towing"],
    lanes: "8 lanes total",
    length: "2,375 ft",
    relatedNeighborhoods: [
      { state: "manhattan", city: "washington-heights" },
      { state: "bronx", city: "university-heights" },
    ],
    geo: { lat: 40.8475, lon: -73.9211 },
  },
  {
    slug: "university-heights-bridge",
    name: "University Heights Bridge",
    kind: "bridge",
    subType: "Swing Bridge (Harlem River Ship Canal)",
    boroughs: ["manhattan", "bronx"],
    segment: "Connects 207th Street in Inwood to the University Heights section of the Bronx via West Fordham Road.",
    hazards: [
      "Approach incidents at 207th and 10th Avenue.",
      "Heavy bus volume narrows curb access on both approaches.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "jump-start", "lockout-service"],
    lanes: "4 lanes total",
    length: "1,500 ft",
    relatedNeighborhoods: [
      { state: "manhattan", city: "inwood" },
      { state: "bronx", city: "university-heights" },
    ],
    geo: { lat: 40.8657, lon: -73.9181 },
  },
  {
    slug: "broadway-bridge",
    name: "Broadway Bridge",
    kind: "bridge",
    subType: "Vertical-Lift Bridge (Harlem River Ship Canal)",
    boroughs: ["manhattan", "bronx"],
    segment: "Connects Inwood to Marble Hill and Kingsbridge in the Bronx via Broadway.",
    hazards: [
      "Approach incidents at 225th and Broadway.",
      "Heavy bus volume narrows curb access on both approaches.",
      "Vertical-lift schedule for marine traffic creates occasional unexpected stops.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "jump-start", "lockout-service"],
    lanes: "4 lanes total",
    length: "558 ft",
    relatedNeighborhoods: [
      { state: "manhattan", city: "inwood" },
      { state: "bronx", city: "kingsbridge" },
    ],
    geo: { lat: 40.8744, lon: -73.9117 },
  },

  // ── BROOKLYN / QUEENS ─────────────────────────────────────────────────────
  {
    slug: "pulaski-bridge",
    name: "Pulaski Bridge",
    kind: "bridge",
    subType: "Bascule Bridge (Newtown Creek)",
    boroughs: ["brooklyn", "queens"],
    segment: "Connects McGuinness Boulevard in Greenpoint, Brooklyn, to 11th Street in Long Island City, Queens.",
    hazards: [
      "Heavy truck volume from the McGuinness / LIC industrial corridor.",
      "Bascule lift schedule for marine traffic creates occasional unexpected stops.",
      "Approach incidents at McGuinness and Greenpoint Ave.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "jump-start", "flatbed-towing"],
    lanes: "4 lanes total",
    length: "2,800 ft",
    relatedNeighborhoods: [
      { state: "brooklyn", city: "greenpoint" },
      { state: "queens", city: "long-island-city" },
    ],
    geo: { lat: 40.7395, lon: -73.9523 },
  },
  {
    slug: "kosciuszko-bridge",
    name: "Kosciuszko Bridge",
    shortName: "K-Bridge",
    kind: "bridge",
    subType: "Cable-Stayed Bridge (Newtown Creek)",
    boroughs: ["brooklyn", "queens"],
    segment: "Carries the BQE (I-278) over Newtown Creek between Greenpoint, Brooklyn, and Maspeth, Queens.",
    hazards: [
      "Heavy commercial truck volume produces frequent tire damage from debris.",
      "BQE merge stacks every weekday afternoon.",
      "Wind events on the open span create control issues for high-sided trucks.",
      "Pothole runs on the bridge deck tear sidewalls.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "commercial-towing", "winch-out-recovery"],
    lanes: "9 lanes total (4 + 5)",
    length: "5,100 ft",
    relatedNeighborhoods: [
      { state: "brooklyn", city: "greenpoint" },
      { state: "queens", city: "maspeth" },
    ],
    geo: { lat: 40.7311, lon: -73.9259 },
  },
  {
    slug: "marine-parkway-bridge",
    name: "Marine Parkway-Gil Hodges Memorial Bridge",
    shortName: "Marine Parkway Bridge",
    kind: "bridge",
    subType: "Vertical-Lift Bridge (Rockaway Inlet)",
    boroughs: ["brooklyn", "queens"],
    segment: "Connects Flatbush Avenue in Marine Park, Brooklyn, to the Rockaway Peninsula in Queens. MTA-tolled.",
    hazards: [
      "Heavy beach traffic every summer weekend.",
      "Vertical-lift schedule for marine traffic creates occasional unexpected stops.",
      "Crosswind incidents on the open span.",
      "Salt-air corrosion on the Rockaway side generates frequent battery failures.",
    ],
    commonCalls: ["jump-start", "battery-replacement", "accident-recovery", "flatbed-towing", "flat-tire-change"],
    lanes: "4 lanes total",
    length: "4,022 ft",
    relatedNeighborhoods: [
      { state: "brooklyn", city: "marine-park" },
      { state: "queens", city: "rockaway-beach" },
    ],
    geo: { lat: 40.5733, lon: -73.8849 },
  },
  {
    slug: "cross-bay-veterans-bridge",
    name: "Cross Bay Veterans Memorial Bridge",
    kind: "bridge",
    subType: "Box-Girder Bridge (Jamaica Bay)",
    boroughs: ["queens"],
    segment: "Connects Howard Beach to Broad Channel along Cross Bay Boulevard. MTA-tolled.",
    hazards: [
      "Heavy beach and JFK traffic.",
      "Crosswind incidents on the open span.",
      "Salt-air corrosion produces frequent battery failures.",
    ],
    commonCalls: ["jump-start", "battery-replacement", "accident-recovery", "flat-tire-change", "flatbed-towing"],
    lanes: "4 lanes total",
    length: "2,768 ft",
    relatedNeighborhoods: [
      { state: "queens", city: "howard-beach" },
      { state: "queens", city: "broad-channel" },
    ],
    geo: { lat: 40.6322, lon: -73.8211 },
  },

  // ── STATEN ISLAND ──────────────────────────────────────────────────────────
  {
    slug: "verrazzano-narrows-bridge",
    name: "Verrazzano-Narrows Bridge",
    kind: "bridge",
    subType: "Suspension Bridge (Narrows)",
    boroughs: ["brooklyn", "staten-island"],
    segment: "Connects Bay Ridge in Brooklyn to Fort Wadsworth in Staten Island. Longest suspension span in the Americas. MTA-tolled (Staten Island-bound free for SI residents with E-ZPass).",
    hazards: [
      "Routinely backed up during rush hour and event traffic.",
      "Heavy commercial truck volume from the I-278 connection.",
      "Wind events on the open span create control issues for high-sided trucks.",
      "No-shoulder design means breakdowns block live lanes.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "winch-out-recovery", "commercial-towing"],
    lanes: "13 lanes total (7 upper + 6 lower)",
    length: "4,260 ft (main span)",
    relatedNeighborhoods: [
      { state: "brooklyn", city: "bay-ridge" },
      { state: "staten-island", city: "rosebank" },
    ],
    geo: { lat: 40.6066, lon: -74.0447 },
  },
  {
    slug: "goethals-bridge",
    name: "Goethals Bridge",
    kind: "bridge",
    subType: "Cable-Stayed Bridge (Arthur Kill)",
    boroughs: ["staten-island"],
    segment: "Connects Howland Hook, Staten Island, to Elizabeth, NJ. Carries the Staten Island Expressway / I-278. Port Authority-tolled.",
    hazards: [
      "Heavy commercial truck volume from the New Jersey port traffic.",
      "Toll plaza approach generates rear-ends in heavy rain.",
      "Wind events on the open span.",
      "Salt-air corrosion in the channel creates frequent battery failures.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "commercial-towing"],
    lanes: "6 lanes total",
    length: "1,151 ft (main span)",
    relatedNeighborhoods: [
      { state: "staten-island", city: "mariners-harbor" },
    ],
    geo: { lat: 40.6385, lon: -74.1923 },
  },
  {
    slug: "bayonne-bridge",
    name: "Bayonne Bridge",
    kind: "bridge",
    subType: "Arch Bridge (Kill Van Kull)",
    boroughs: ["staten-island"],
    segment: "Connects Port Richmond, Staten Island, to Bayonne, NJ. Port Authority-tolled.",
    hazards: [
      "Crosswind incidents on the high-arch open deck.",
      "Heavy commercial truck volume from the port traffic.",
      "Toll plaza approach generates rear-ends in heavy rain.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change"],
    lanes: "4 lanes total",
    length: "1,675 ft (main span)",
    relatedNeighborhoods: [
      { state: "staten-island", city: "port-richmond" },
      { state: "staten-island", city: "elm-park" },
    ],
    geo: { lat: 40.6395, lon: -74.1422 },
  },
  {
    slug: "outerbridge-crossing",
    name: "Outerbridge Crossing",
    kind: "bridge",
    subType: "Cantilever Bridge (Arthur Kill)",
    boroughs: ["staten-island"],
    segment: "Connects Tottenville, Staten Island, to Perth Amboy, NJ. Carries NY-440 / NJ-440. Port Authority-tolled.",
    hazards: [
      "Heavy commercial truck volume from the New Jersey port traffic.",
      "Toll plaza approach generates rear-ends in heavy rain.",
      "Crosswind incidents on the open span.",
      "No-shoulder design means breakdowns block live lanes.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "commercial-towing"],
    lanes: "4 lanes total",
    length: "1,638 ft (main span)",
    relatedNeighborhoods: [
      { state: "staten-island", city: "tottenville" },
    ],
    geo: { lat: 40.5246, lon: -74.2459 },
  },
];