import type { Roadway } from "./roadways";

/**
 * NYC highways, parkways, expressways, and grade-separated drives.
 * Every entry generates a /highways/[slug] page. Curated to cover every
 * limited-access corridor inside the five boroughs where stranded drivers
 * actually call from.
 */
export const HIGHWAYS: Roadway[] = [
  // ── MANHATTAN ──────────────────────────────────────────────────────────────
  {
    slug: "fdr-drive",
    name: "FDR Drive",
    shortName: "FDR",
    kind: "highway",
    subType: "Drive",
    boroughs: ["manhattan"],
    segment: "Limited-access drive along the East River from the Battery north to the Triboro/RFK Bridge at 125th Street.",
    hazards: [
      "No-shoulder design from 14th to 96th means a flat tire or breakdown blocks a live lane immediately.",
      "Low-clearance underpasses at the UN tunnel disqualify high flatbeds — we route around via 1st Avenue.",
      "Salt-water flooding at the 23rd, 34th, and 96th street exits during nor'easters strands cars.",
      "Heavy debris on the inside lane between 60th and 79th tears tires.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "flat-tire-change", "jump-start", "winch-out-recovery"],
    nearestExits: ["Battery", "Houston St", "23rd St", "34th St", "63rd St", "79th St", "96th St", "116th St", "Triboro"],
    speedLimit: "40 mph",
    lanes: "3 lanes each direction (mostly)",
    relatedNeighborhoods: [
      { state: "manhattan", city: "financial-district" },
      { state: "manhattan", city: "lower-east-side" },
      { state: "manhattan", city: "stuyvesant-town" },
      { state: "manhattan", city: "midtown-east" },
      { state: "manhattan", city: "upper-east-side" },
      { state: "manhattan", city: "east-harlem" },
    ],
    geo: { lat: 40.7458, lon: -73.9719 },
  },
  {
    slug: "west-side-highway",
    name: "West Side Highway",
    shortName: "West Side Hwy",
    kind: "highway",
    subType: "Highway (Route 9A)",
    boroughs: ["manhattan"],
    segment: "Surface-level highway along the Hudson from the Battery north to 72nd Street, where it becomes the Henry Hudson Parkway.",
    hazards: [
      "Pedestrian and cyclist crossings at every cross-street generate sudden stops.",
      "Heavy weekend cyclist volume on the adjacent greenway creates door-strike risk.",
      "Pothole runs between Houston and 14th tear sidewalls.",
      "Cruise-terminal truck traffic at 12th and 55th creates congestion bursts.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "jump-start", "flatbed-towing"],
    nearestExits: ["Battery", "Chambers St", "Canal St", "Houston St", "23rd St", "42nd St", "57th St", "72nd St"],
    speedLimit: "35 mph",
    lanes: "3 lanes each direction",
    relatedNeighborhoods: [
      { state: "manhattan", city: "battery-park-city" },
      { state: "manhattan", city: "tribeca" },
      { state: "manhattan", city: "west-village" },
      { state: "manhattan", city: "chelsea" },
      { state: "manhattan", city: "hells-kitchen" },
    ],
    geo: { lat: 40.7367, lon: -74.0083 },
  },
  {
    slug: "henry-hudson-parkway",
    name: "Henry Hudson Parkway",
    shortName: "Henry Hudson Pkwy",
    kind: "highway",
    subType: "Parkway",
    boroughs: ["manhattan", "bronx"],
    segment: "Continues the West Side Highway from 72nd Street north through Riverside Park, across the Henry Hudson Bridge, and through Riverdale to the Bronx-Westchester line.",
    hazards: [
      "Commercial vehicles are banned — drivers in box trucks get caught and need recovery off the parkway.",
      "Tight on/off ramps at 96th, 125th, and 158th generate merge incidents.",
      "Henry Hudson Bridge toll plaza generates rear-ends in heavy rain.",
      "Pothole runs through Inwood tear tires.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "flat-tire-change", "jump-start"],
    nearestExits: ["79th St", "96th St", "125th St", "158th St", "Dyckman", "Inwood", "Henry Hudson Bridge"],
    speedLimit: "45-50 mph",
    lanes: "3 lanes each direction",
    relatedNeighborhoods: [
      { state: "manhattan", city: "upper-west-side" },
      { state: "manhattan", city: "morningside-heights" },
      { state: "manhattan", city: "washington-heights" },
      { state: "manhattan", city: "inwood" },
      { state: "bronx", city: "riverdale" },
    ],
    geo: { lat: 40.8514, lon: -73.9329 },
  },
  {
    slug: "harlem-river-drive",
    name: "Harlem River Drive",
    kind: "highway",
    subType: "Drive",
    boroughs: ["manhattan"],
    segment: "Connects the FDR at 125th Street north along the Harlem River to the Cross Bronx Expressway approach at the GWB.",
    hazards: [
      "No-shoulder design across most of the corridor means breakdowns block live lanes.",
      "Macombs Dam Bridge merge generates lane-change incidents.",
      "GWB approach stack-up backs traffic south every weekday afternoon.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "flat-tire-change", "winch-out-recovery"],
    nearestExits: ["125th St", "Madison Ave Br", "145th St", "Macombs Dam Br", "GWB"],
    speedLimit: "40 mph",
    lanes: "3 lanes each direction",
    relatedNeighborhoods: [
      { state: "manhattan", city: "east-harlem" },
      { state: "manhattan", city: "harlem" },
      { state: "manhattan", city: "washington-heights" },
    ],
    geo: { lat: 40.8281, lon: -73.9337 },
  },

  // ── BROOKLYN / QUEENS ──────────────────────────────────────────────────────
  {
    slug: "brooklyn-queens-expressway",
    name: "Brooklyn-Queens Expressway",
    shortName: "BQE",
    kind: "highway",
    subType: "Expressway (I-278)",
    boroughs: ["brooklyn", "queens"],
    segment: "Runs from the Verrazzano-Narrows Bridge in Bay Ridge north through Sunset Park, Carroll Gardens, Brooklyn Heights, Williamsburg, Greenpoint, and across the Kosciuszko Bridge into Queens, continuing past LaGuardia to the Triboro/RFK Bridge.",
    hazards: [
      "Triple-cantilever in Brooklyn Heights restricts weight and has been load-rated down — heavy box trucks and tractors get diverted.",
      "Sharp curves at Atlantic Ave and Kent Ave generate constant fender-benders.",
      "Pothole runs through Sunset Park and Greenpoint tear sidewalls every winter.",
      "Kosciuszko Bridge crosswinds in winter cause control issues for high-sided trucks.",
      "No-shoulder design through Williamsburg means breakdowns block live lanes.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "winch-out-recovery"],
    nearestExits: ["Hamilton Ave", "Atlantic Ave", "Tillary St", "Manhattan Br", "Kent Ave", "McGuinness", "Kosciuszko Br", "Maurice Ave", "LIE", "Astoria Blvd", "Triboro"],
    speedLimit: "50 mph",
    lanes: "3 lanes each direction (mostly)",
    relatedNeighborhoods: [
      { state: "brooklyn", city: "bay-ridge" },
      { state: "brooklyn", city: "sunset-park" },
      { state: "brooklyn", city: "carroll-gardens" },
      { state: "brooklyn", city: "brooklyn-heights" },
      { state: "brooklyn", city: "williamsburg" },
      { state: "brooklyn", city: "greenpoint" },
      { state: "queens", city: "long-island-city" },
      { state: "queens", city: "astoria" },
    ],
    geo: { lat: 40.6975, lon: -73.9716 },
  },
  {
    slug: "belt-parkway",
    name: "Belt Parkway",
    kind: "highway",
    subType: "Parkway",
    boroughs: ["brooklyn", "queens"],
    segment: "Loops along southern Brooklyn and Queens, from the Verrazzano in Bay Ridge through Bensonhurst, Gravesend, Sheepshead Bay, Canarsie, East New York, Howard Beach, and JFK to the Cross Island Parkway.",
    hazards: [
      "Commercial vehicles banned — box trucks and box vans regularly get caught and need recovery off the parkway.",
      "Tight on/off ramps at Pennsylvania, Cropsey, and Knapp generate merge incidents.",
      "Salt-water flooding at the Plumb Beach and Mill Basin sections during nor'easters strands cars.",
      "Verrazzano-bound traffic stacks every weekday afternoon.",
      "Crosswind incidents on the bridges over Mill Basin and Paerdegat.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "flat-tire-change", "winch-out-recovery", "jump-start"],
    nearestExits: ["Verrazzano", "Bay Pkwy", "Cropsey", "Ocean Pkwy", "Knapp St", "Flatbush Ave", "Pennsylvania", "Cross Bay Blvd", "JFK", "Cross Island"],
    speedLimit: "50 mph",
    lanes: "3 lanes each direction",
    relatedNeighborhoods: [
      { state: "brooklyn", city: "bay-ridge" },
      { state: "brooklyn", city: "bensonhurst" },
      { state: "brooklyn", city: "sheepshead-bay" },
      { state: "brooklyn", city: "canarsie" },
      { state: "queens", city: "howard-beach" },
    ],
    geo: { lat: 40.5934, lon: -73.9265 },
  },
  {
    slug: "prospect-expressway",
    name: "Prospect Expressway",
    kind: "highway",
    subType: "Expressway (NY-27)",
    boroughs: ["brooklyn"],
    segment: "Short connector from the BQE/Gowanus Expressway to Ocean Parkway in Windsor Terrace.",
    hazards: [
      "Tight merge from the Gowanus Expressway generates lane-change incidents.",
      "Right-side exit-only lanes at Church Avenue confuse out-of-borough drivers.",
      "Pothole runs near the Hamilton entrance tear sidewalls.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "flat-tire-change", "winch-out-recovery"],
    nearestExits: ["Hamilton Ave", "Church Ave", "Ocean Pkwy"],
    speedLimit: "45 mph",
    lanes: "3 lanes each direction",
    relatedNeighborhoods: [
      { state: "brooklyn", city: "windsor-terrace" },
      { state: "brooklyn", city: "park-slope" },
    ],
    geo: { lat: 40.6582, lon: -73.9836 },
  },
  {
    slug: "gowanus-expressway",
    name: "Gowanus Expressway",
    kind: "highway",
    subType: "Expressway (I-278)",
    boroughs: ["brooklyn"],
    segment: "Elevated section of I-278 from the Battery Tunnel through Red Hook, Sunset Park, and Bay Ridge to the Verrazzano-Narrows Bridge.",
    hazards: [
      "Aging elevated structure with multiple lane-width restrictions during ongoing rehab.",
      "Verrazzano-bound traffic stacks every weekday afternoon.",
      "Battery Tunnel exit weave generates accidents.",
      "Heavy truck volume produces frequent tire damage from debris.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "winch-out-recovery"],
    nearestExits: ["Battery Tunnel", "Hamilton Ave", "39th St", "65th St", "92nd St", "Verrazzano"],
    speedLimit: "50 mph",
    lanes: "3 lanes each direction",
    relatedNeighborhoods: [
      { state: "brooklyn", city: "red-hook" },
      { state: "brooklyn", city: "sunset-park" },
      { state: "brooklyn", city: "bay-ridge" },
    ],
    geo: { lat: 40.6478, lon: -74.0125 },
  },
  {
    slug: "jackie-robinson-parkway",
    name: "Jackie Robinson Parkway",
    shortName: "Jackie Robinson Pkwy",
    kind: "highway",
    subType: "Parkway",
    boroughs: ["brooklyn", "queens"],
    segment: "Winding parkway from Bushwick east through Cypress Hills, Highland Park, Forest Park, and into Kew Gardens, connecting to the Grand Central and Van Wyck.",
    hazards: [
      "Tightest curves of any NYC parkway — frequent guard-rail incidents.",
      "Commercial vehicles banned — box trucks regularly need recovery off the parkway.",
      "Heavy deer activity through Forest Park after dusk.",
      "Limited shoulder space means breakdowns require quick recovery.",
    ],
    commonCalls: ["accident-recovery", "winch-out-recovery", "flatbed-towing", "flat-tire-change"],
    nearestExits: ["Bushwick Ave", "Pennsylvania Ave", "Cypress Hills", "Forest Park", "Metropolitan Ave", "Grand Central"],
    speedLimit: "35-40 mph",
    lanes: "2 lanes each direction",
    relatedNeighborhoods: [
      { state: "brooklyn", city: "bushwick" },
      { state: "brooklyn", city: "cypress-hills" },
      { state: "brooklyn", city: "east-new-york" },
      { state: "queens", city: "richmond-hill" },
      { state: "queens", city: "kew-gardens" },
    ],
    geo: { lat: 40.6885, lon: -73.8743 },
  },

  // ── QUEENS ─────────────────────────────────────────────────────────────────
  {
    slug: "long-island-expressway",
    name: "Long Island Expressway",
    shortName: "LIE",
    kind: "highway",
    subType: "Expressway (I-495)",
    boroughs: ["queens"],
    segment: "Major east-west spine from the Queens-Midtown Tunnel in Long Island City east through Sunnyside, Maspeth, Elmhurst, Rego Park, Forest Hills, Kew Gardens Hills, Fresh Meadows, Bayside, and Douglaston to the Nassau line.",
    hazards: [
      "Queens-Midtown Tunnel-bound traffic stacks every weekday — multi-hour delays during rush.",
      "Heavy truck volume in the right two lanes tears tires from debris.",
      "Tight on/off ramps at Maurice, Long Island Expressway service road, Junction, and Utopia generate merge incidents.",
      "Cross Island Parkway interchange routinely stacks evening rush.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "winch-out-recovery"],
    nearestExits: ["Tunnel", "Greenpoint Ave", "Maurice Ave", "Queens Blvd", "Woodhaven Blvd", "Grand Central Pkwy", "Junction Blvd", "Main St", "Utopia Pkwy", "Cross Island Pkwy", "Little Neck"],
    speedLimit: "50 mph",
    lanes: "3-4 lanes each direction",
    relatedNeighborhoods: [
      { state: "queens", city: "long-island-city" },
      { state: "queens", city: "sunnyside" },
      { state: "queens", city: "maspeth" },
      { state: "queens", city: "elmhurst" },
      { state: "queens", city: "rego-park" },
      { state: "queens", city: "forest-hills" },
      { state: "queens", city: "fresh-meadows" },
      { state: "queens", city: "bayside" },
      { state: "queens", city: "douglaston" },
    ],
    geo: { lat: 40.7430, lon: -73.8556 },
  },
  {
    slug: "grand-central-parkway",
    name: "Grand Central Parkway",
    shortName: "Grand Central Pkwy",
    kind: "highway",
    subType: "Parkway",
    boroughs: ["queens"],
    segment: "Runs from the Triboro/RFK Bridge east through Astoria, past LaGuardia Airport, through Flushing Meadows, and into Forest Hills and Kew Gardens, where it splits to the Van Wyck and Interboro.",
    hazards: [
      "Commercial vehicles banned — box trucks regularly need recovery off the parkway.",
      "LaGuardia airport feed traffic generates constant lane changes.",
      "Citi Field and US Open event traffic compresses the central blocks.",
      "Pothole runs near the Whitestone interchange tear sidewalls.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "flat-tire-change", "winch-out-recovery", "jump-start"],
    nearestExits: ["Triboro", "31st St", "94th St (LaGuardia)", "Northern Blvd", "Whitestone Expwy", "Van Wyck", "Interboro/Jackie Robinson"],
    speedLimit: "50 mph",
    lanes: "3 lanes each direction",
    relatedNeighborhoods: [
      { state: "queens", city: "astoria" },
      { state: "queens", city: "east-elmhurst" },
      { state: "queens", city: "corona" },
      { state: "queens", city: "flushing" },
      { state: "queens", city: "forest-hills" },
      { state: "queens", city: "kew-gardens" },
    ],
    geo: { lat: 40.7588, lon: -73.8516 },
  },
  {
    slug: "van-wyck-expressway",
    name: "Van Wyck Expressway",
    shortName: "Van Wyck",
    kind: "highway",
    subType: "Expressway (I-678)",
    boroughs: ["queens"],
    segment: "Connects the Whitestone Bridge south through Flushing, Briarwood, and Jamaica to JFK Airport.",
    hazards: [
      "JFK-bound rideshare and limo traffic generates constant lane changes.",
      "Notoriously congested at all hours — rush hour means multi-hour delays.",
      "Tight on/off ramps at Main Street, Hillside, and Liberty generate merge incidents.",
      "Pothole runs near the Jamaica Avenue overpass tear tires.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "jump-start"],
    nearestExits: ["Whitestone Br", "Main St", "Jewel Ave", "Briarwood", "Hillside Ave", "Liberty Ave", "Belt Pkwy", "JFK"],
    speedLimit: "50 mph",
    lanes: "3 lanes each direction",
    relatedNeighborhoods: [
      { state: "queens", city: "flushing" },
      { state: "queens", city: "briarwood" },
      { state: "queens", city: "jamaica" },
      { state: "queens", city: "south-jamaica" },
    ],
    geo: { lat: 40.6928, lon: -73.8084 },
  },
  {
    slug: "whitestone-expressway",
    name: "Whitestone Expressway",
    kind: "highway",
    subType: "Expressway (I-678)",
    boroughs: ["queens"],
    segment: "Connects the Bronx-Whitestone Bridge south through Whitestone, College Point, and Flushing to the Van Wyck.",
    hazards: [
      "Toll plaza approach at the Bronx-Whitestone Bridge generates rear-ends in heavy rain.",
      "College Point industrial truck volume produces frequent tire damage.",
      "Tight on/off ramps generate merge incidents.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "flat-tire-change", "jump-start"],
    nearestExits: ["Bronx-Whitestone Br", "20th Ave (College Point)", "Northern Blvd", "Van Wyck"],
    speedLimit: "50 mph",
    lanes: "3 lanes each direction",
    relatedNeighborhoods: [
      { state: "queens", city: "whitestone" },
      { state: "queens", city: "college-point" },
      { state: "queens", city: "flushing" },
    ],
    geo: { lat: 40.7857, lon: -73.8341 },
  },
  {
    slug: "cross-island-parkway",
    name: "Cross Island Parkway",
    shortName: "Cross Island Pkwy",
    kind: "highway",
    subType: "Parkway",
    boroughs: ["queens"],
    segment: "Runs from the Whitestone Bridge south and east along the eastern edge of Queens through Bayside, Douglaston, Little Neck, and into the Belt Parkway.",
    hazards: [
      "Commercial vehicles banned — box trucks regularly need recovery off the parkway.",
      "Sharp curves through Bayside and Douglaston generate guard-rail incidents.",
      "Crosswind incidents on the elevated sections near the Throgs Neck approach.",
      "Pothole runs near the Northern Boulevard interchange tear tires.",
    ],
    commonCalls: ["accident-recovery", "winch-out-recovery", "flatbed-towing", "flat-tire-change"],
    nearestExits: ["Whitestone Br", "Northern Blvd", "Bell Blvd", "Long Island Expwy", "Grand Central Pkwy", "Throgs Neck Br", "Belt Pkwy"],
    speedLimit: "50 mph",
    lanes: "3 lanes each direction",
    relatedNeighborhoods: [
      { state: "queens", city: "bayside" },
      { state: "queens", city: "douglaston" },
      { state: "queens", city: "little-neck" },
    ],
    geo: { lat: 40.7666, lon: -73.7681 },
  },
  {
    slug: "clearview-expressway",
    name: "Clearview Expressway",
    kind: "highway",
    subType: "Expressway (I-295)",
    boroughs: ["queens"],
    segment: "Connects the LIE in Bayside south through Hollis Hills and Queens Village to the Belt Parkway via the Throgs Neck Bridge approach.",
    hazards: [
      "Throgs Neck Bridge approach toll plaza generates rear-ends in heavy rain.",
      "Tight on/off ramps at the LIE interchange generate merge incidents.",
      "Pothole runs through Hollis Hills tear sidewalls.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "flat-tire-change", "jump-start"],
    nearestExits: ["Throgs Neck Br", "Northern Blvd", "LIE", "Union Tpke", "Hillside Ave"],
    speedLimit: "50 mph",
    lanes: "3 lanes each direction",
    relatedNeighborhoods: [
      { state: "queens", city: "bayside" },
      { state: "queens", city: "hollis-hills" },
      { state: "queens", city: "queens-village" },
    ],
    geo: { lat: 40.7522, lon: -73.7700 },
  },

  // ── BRONX ──────────────────────────────────────────────────────────────────
  {
    slug: "cross-bronx-expressway",
    name: "Cross Bronx Expressway",
    shortName: "Cross Bronx",
    kind: "highway",
    subType: "Expressway (I-95)",
    boroughs: ["bronx"],
    segment: "Runs from the George Washington Bridge east across the Bronx through Tremont, Crotona, and West Farms, joining the Bruckner at the Bronx River and continuing to the Throgs Neck.",
    hazards: [
      "Routinely ranked the most congested freeway segment in America — multi-hour delays daily.",
      "Heavy commercial truck volume produces constant tire damage from debris.",
      "Tight on/off ramps at Webster, 3rd Ave, and White Plains generate merge incidents.",
      "GWB-bound traffic stacks every weekday afternoon.",
      "No-shoulder design across most of the corridor means breakdowns block live lanes immediately.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "winch-out-recovery", "commercial-towing"],
    nearestExits: ["GWB", "Univ Heights Br", "Webster Ave", "3rd Ave", "Boston Rd", "White Plains Rd", "Castle Hill Ave", "Bruckner", "Throgs Neck Br"],
    speedLimit: "50 mph",
    lanes: "3 lanes each direction",
    relatedNeighborhoods: [
      { state: "bronx", city: "tremont" },
      { state: "bronx", city: "west-farms" },
      { state: "bronx", city: "morrisania" },
      { state: "bronx", city: "throgs-neck" },
    ],
    geo: { lat: 40.8444, lon: -73.8957 },
  },
  {
    slug: "major-deegan-expressway",
    name: "Major Deegan Expressway",
    shortName: "Major Deegan",
    kind: "highway",
    subType: "Expressway (I-87)",
    boroughs: ["bronx"],
    segment: "Runs from the Triboro/RFK Bridge north through Mott Haven, Highbridge, University Heights, Kingsbridge, and Riverdale to the Westchester line as the New York State Thruway.",
    hazards: [
      "Yankee Stadium event traffic compresses the southern stretches.",
      "Heavy commercial truck volume produces constant tire damage.",
      "Tight on/off ramps at 138th, 145th, Fordham, and 233rd generate merge incidents.",
      "Cross Bronx interchange routinely stacks afternoon rush.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "commercial-towing"],
    nearestExits: ["Triboro", "138th St", "Yankee Stadium", "Cross Bronx", "Fordham Rd", "230th St", "Van Cortlandt", "233rd St"],
    speedLimit: "50 mph",
    lanes: "3-4 lanes each direction",
    relatedNeighborhoods: [
      { state: "bronx", city: "mott-haven" },
      { state: "bronx", city: "highbridge" },
      { state: "bronx", city: "university-heights" },
      { state: "bronx", city: "kingsbridge" },
      { state: "bronx", city: "riverdale" },
    ],
    geo: { lat: 40.8525, lon: -73.9168 },
  },
  {
    slug: "bruckner-expressway",
    name: "Bruckner Expressway",
    shortName: "Bruckner",
    kind: "highway",
    subType: "Expressway (I-278 / I-95)",
    boroughs: ["bronx"],
    segment: "Runs from the Triboro/RFK Bridge through Mott Haven, Hunts Point, Soundview, Castle Hill, and Throgs Neck, splitting east into the Throgs Neck Bridge approach and continuing as I-95 to the New England Thruway.",
    hazards: [
      "Hunts Point Market truck volume produces constant tire damage and broadside risk at the produce-market exits.",
      "Cross Bronx interchange routinely stacks rush hour.",
      "Tight on/off ramps at Hunts Point, Castle Hill, and East 177th generate merge incidents.",
      "Pothole runs near the East River bridge approaches tear sidewalls.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "commercial-towing"],
    nearestExits: ["Triboro", "138th St", "Hunts Point", "Cross Bronx", "Castle Hill Ave", "Throgs Neck Br", "Pelham Bay"],
    speedLimit: "50 mph",
    lanes: "3 lanes each direction",
    relatedNeighborhoods: [
      { state: "bronx", city: "mott-haven" },
      { state: "bronx", city: "hunts-point" },
      { state: "bronx", city: "soundview" },
      { state: "bronx", city: "castle-hill" },
      { state: "bronx", city: "throgs-neck" },
    ],
    geo: { lat: 40.8232, lon: -73.8645 },
  },
  {
    slug: "hutchinson-river-parkway",
    name: "Hutchinson River Parkway",
    shortName: "Hutch",
    kind: "highway",
    subType: "Parkway",
    boroughs: ["bronx"],
    segment: "Runs from the Whitestone Bridge approach north through Pelham Bay, Co-op City, and into Westchester.",
    hazards: [
      "Commercial vehicles banned — box trucks regularly need recovery off the parkway.",
      "Tight curves through Pelham Bay generate guard-rail incidents.",
      "Pothole runs near Co-op City tear sidewalls.",
    ],
    commonCalls: ["accident-recovery", "winch-out-recovery", "flatbed-towing", "flat-tire-change"],
    nearestExits: ["Bruckner", "Pelham Pkwy", "Co-op City Blvd", "Boston Rd", "Westchester"],
    speedLimit: "50 mph",
    lanes: "3 lanes each direction",
    relatedNeighborhoods: [
      { state: "bronx", city: "pelham-bay" },
      { state: "bronx", city: "co-op-city" },
    ],
    geo: { lat: 40.8717, lon: -73.8298 },
  },
  {
    slug: "sheridan-expressway",
    name: "Sheridan Expressway",
    kind: "highway",
    subType: "Boulevard (former I-895)",
    boroughs: ["bronx"],
    segment: "Short connector between the Cross Bronx and the Bruckner, recently converted from limited-access to surface boulevard.",
    hazards: [
      "Conversion to surface signals confuses drivers expecting expressway speeds.",
      "Cross Bronx and Bruckner merges still stack rush hour.",
      "Pothole runs at the south end tear tires.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "flatbed-towing", "jump-start"],
    nearestExits: ["Cross Bronx", "Hunts Point", "Bruckner"],
    speedLimit: "30 mph",
    lanes: "2 lanes each direction",
    relatedNeighborhoods: [
      { state: "bronx", city: "west-farms" },
      { state: "bronx", city: "hunts-point" },
    ],
    geo: { lat: 40.8311, lon: -73.8842 },
  },
  {
    slug: "mosholu-parkway",
    name: "Mosholu Parkway",
    kind: "highway",
    subType: "Parkway",
    boroughs: ["bronx"],
    segment: "Short connector parkway from the Grand Concourse to the Bronx River Parkway, running through Norwood and Bedford Park.",
    hazards: [
      "Commercial vehicles banned — box trucks regularly need recovery off the parkway.",
      "Sharp curves generate guard-rail incidents.",
      "Pothole runs through Norwood tear tires.",
    ],
    commonCalls: ["accident-recovery", "winch-out-recovery", "flatbed-towing", "flat-tire-change"],
    nearestExits: ["Grand Concourse", "Bronx River Pkwy"],
    speedLimit: "40 mph",
    lanes: "2 lanes each direction",
    relatedNeighborhoods: [
      { state: "bronx", city: "norwood" },
      { state: "bronx", city: "bedford-park" },
    ],
    geo: { lat: 40.8754, lon: -73.8854 },
  },

  // ── STATEN ISLAND ──────────────────────────────────────────────────────────
  {
    slug: "staten-island-expressway",
    name: "Staten Island Expressway",
    shortName: "SIE",
    kind: "highway",
    subType: "Expressway (I-278)",
    boroughs: ["staten-island"],
    segment: "Connects the Verrazzano-Narrows Bridge east through Grasmere, Concord, Sunnyside, and across the Goethals Bridge to New Jersey.",
    hazards: [
      "Goethals and Verrazzano toll plaza approaches generate rear-ends in heavy rain.",
      "Heavy commercial truck volume from the New Jersey port traffic.",
      "Tight on/off ramps at Bradley, Victory, and Slosson generate merge incidents.",
      "Construction zones from the long-running rehab project create lane-shift hazards.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "winch-out-recovery", "commercial-towing"],
    nearestExits: ["Verrazzano", "Bay St", "Hylan Blvd", "Bradley", "Victory Blvd", "Slosson Ave", "Goethals Br"],
    speedLimit: "50 mph",
    lanes: "3 lanes each direction",
    relatedNeighborhoods: [
      { state: "staten-island", city: "rosebank" },
      { state: "staten-island", city: "grasmere" },
      { state: "staten-island", city: "sunnyside" },
    ],
    geo: { lat: 40.6098, lon: -74.1145 },
  },
  {
    slug: "west-shore-expressway",
    name: "West Shore Expressway",
    kind: "highway",
    subType: "Expressway (NY-440)",
    boroughs: ["staten-island"],
    segment: "Runs along Staten Island's western edge from the Outerbridge Crossing north to the Goethals Bridge and the Bayonne Bridge approach.",
    hazards: [
      "Heavy commercial truck volume from the Travis industrial corridor.",
      "Crosswind incidents on the elevated sections.",
      "Tight on/off ramps at Arthur Kill, Bloomfield, and Forest Hill generate merge incidents.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "commercial-towing"],
    nearestExits: ["Outerbridge", "Arthur Kill Rd", "Bloomfield", "Forest Hill Rd", "Goethals", "Bayonne Br"],
    speedLimit: "55 mph",
    lanes: "3 lanes each direction",
    relatedNeighborhoods: [
      { state: "staten-island", city: "tottenville" },
      { state: "staten-island", city: "rossville" },
      { state: "staten-island", city: "travis" },
    ],
    geo: { lat: 40.5707, lon: -74.2069 },
  },
  {
    slug: "korean-war-veterans-parkway",
    name: "Korean War Veterans Parkway",
    kind: "highway",
    subType: "Parkway",
    boroughs: ["staten-island"],
    segment: "Connects the Outerbridge Crossing in Tottenville east to the West Shore Expressway, running through Eltingville and Richmond Valley.",
    hazards: [
      "Commercial vehicles banned — box trucks regularly need recovery off the parkway.",
      "Heavy deer activity through Richmond Valley after dusk.",
      "Crosswind incidents at the wetland crossings.",
    ],
    commonCalls: ["accident-recovery", "winch-out-recovery", "flatbed-towing", "flat-tire-change"],
    nearestExits: ["Outerbridge", "Richmond Ave", "Arthur Kill Rd", "West Shore Expwy"],
    speedLimit: "50 mph",
    lanes: "2 lanes each direction",
    relatedNeighborhoods: [
      { state: "staten-island", city: "tottenville" },
      { state: "staten-island", city: "eltingville" },
      { state: "staten-island", city: "richmond-valley" },
    ],
    geo: { lat: 40.5390, lon: -74.2160 },
  },
];