import type { Roadway } from "./roadways";

/**
 * Major NYC arterial streets, avenues, and boulevards where stranded drivers call us.
 * Curated to cover every borough with the corridors that actually generate roadside calls —
 * commercial spines, crosstown arteries, neighborhood-defining boulevards, and the few
 * truck-restricted streets where drivers get caught up before realizing the rules.
 */
export const STREETS: Roadway[] = [
  // ── MANHATTAN ──────────────────────────────────────────────────────────────
  {
    slug: "broadway",
    name: "Broadway",
    kind: "street",
    subType: "Avenue",
    boroughs: ["manhattan", "bronx"],
    segment: "Runs the full diagonal of Manhattan from Bowling Green to Inwood and continues north through the Bronx as US-9. Crosses every avenue grid in Manhattan and stitches together the Financial District, SoHo, NoHo, Union Square, Times Square, Lincoln Square, the Upper West Side, Morningside Heights, Harlem, Washington Heights, and Inwood.",
    hazards: [
      "Heavy taxi and rideshare traffic from Times Square through the Theater District generates sudden stops and rear-end incidents.",
      "Bus lanes and pedestrian plazas constrain how trucks can get to the curb, especially around Herald Square, Times Square, and Madison Square.",
      "Older curb-cut driveways through SoHo and the Upper West Side leave low-clearance EVs stranded after a hard scrape.",
      "Steam-grate clusters between 23rd and 57th eat tires on a regular basis.",
    ],
    commonCalls: ["flat-tire-change", "jump-start", "lockout-service", "accident-recovery", "flatbed-towing"],
    relatedNeighborhoods: [
      { state: "manhattan", city: "soho" },
      { state: "manhattan", city: "times-square" },
      { state: "manhattan", city: "upper-west-side" },
      { state: "manhattan", city: "harlem" },
      { state: "manhattan", city: "inwood" },
    ],
    geo: { lat: 40.7589, lon: -73.9851 },
  },
  {
    slug: "5th-avenue",
    name: "5th Avenue",
    shortName: "5th Ave",
    kind: "street",
    subType: "Avenue",
    boroughs: ["manhattan"],
    segment: "Runs south-to-north from Washington Square Park to 142nd Street, dividing Manhattan into East and West. Anchors Museum Mile, the Plaza District, the Flatiron, and the southern edge of Harlem.",
    hazards: [
      "Holiday-season foot traffic between 49th and 59th makes curb access nearly impossible without staging from a side street.",
      "School pickup zones along the UES and Carnegie Hill block driver access in long stretches.",
      "Tourist double-parking around Rockefeller Center generates fender-benders that need quick photos and a clean tow.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "luxury-exotic-towing", "lockout-service", "jump-start"],
    relatedNeighborhoods: [
      { state: "manhattan", city: "flatiron" },
      { state: "manhattan", city: "midtown" },
      { state: "manhattan", city: "upper-east-side" },
      { state: "manhattan", city: "harlem" },
    ],
    geo: { lat: 40.7736, lon: -73.9665 },
  },
  {
    slug: "park-avenue",
    name: "Park Avenue",
    shortName: "Park Ave",
    kind: "street",
    subType: "Avenue",
    boroughs: ["manhattan"],
    segment: "Runs from Union Square north through Murray Hill, Midtown East, the Upper East Side, Carnegie Hill, East Harlem, and across the Park Avenue Bridge into the Bronx as a wide median boulevard.",
    hazards: [
      "Center-median construction zones north of 96th Street force lane shifts that catch out unfamiliar drivers.",
      "Tunnel into Grand Central at 40th is low-clearance and disqualifies most flatbeds — we route around via Lexington.",
      "Cobblestone strips between 50th and 59th destroy low-profile tire sidewalls.",
    ],
    commonCalls: ["flatbed-towing", "flat-tire-change", "luxury-exotic-towing", "ev-tesla-towing", "lockout-service"],
    relatedNeighborhoods: [
      { state: "manhattan", city: "murray-hill" },
      { state: "manhattan", city: "midtown-east" },
      { state: "manhattan", city: "upper-east-side" },
      { state: "manhattan", city: "east-harlem" },
    ],
    geo: { lat: 40.7549, lon: -73.9786 },
  },
  {
    slug: "madison-avenue",
    name: "Madison Avenue",
    shortName: "Madison Ave",
    kind: "street",
    subType: "Avenue",
    boroughs: ["manhattan"],
    segment: "One-way northbound spine from 23rd Street to 138th Street, parallel one block east of 5th. Anchors the Madison Avenue retail corridor on the Upper East Side and runs straight up to the Madison Avenue Bridge into the Bronx.",
    hazards: [
      "Tight UPS/FedEx commercial delivery double-parking blocks the right lane all morning between Midtown and 96th.",
      "Hospital traffic around Mount Sinai and Lenox Hill generates sudden ambulance lane clears.",
      "Northbound merge to the Madison Avenue Bridge sees rear-ends in heavy rain.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "jump-start", "flat-tire-change"],
    relatedNeighborhoods: [
      { state: "manhattan", city: "midtown-east" },
      { state: "manhattan", city: "upper-east-side" },
      { state: "manhattan", city: "carnegie-hill" },
      { state: "manhattan", city: "east-harlem" },
    ],
    geo: { lat: 40.7654, lon: -73.9692 },
  },
  {
    slug: "lexington-avenue",
    name: "Lexington Avenue",
    shortName: "Lex",
    kind: "street",
    subType: "Avenue",
    boroughs: ["manhattan"],
    segment: "One-way southbound spine from East Harlem to Gramercy. Carries heavy commuter, taxi, and bus traffic and serves Hunter College, the 59th-Lex hub, and Grand Central.",
    hazards: [
      "M101/M102/M103 bus lanes restrict curb access during peak hours.",
      "Subway grate clusters around 86th and 96th catch low-profile tires.",
      "Heavy crosstown taxi cuts at 59th, 86th, and 125th cause clipped mirrors and door damage.",
    ],
    commonCalls: ["flat-tire-change", "accident-recovery", "lockout-service", "jump-start", "flatbed-towing"],
    relatedNeighborhoods: [
      { state: "manhattan", city: "gramercy" },
      { state: "manhattan", city: "murray-hill" },
      { state: "manhattan", city: "midtown-east" },
      { state: "manhattan", city: "upper-east-side" },
      { state: "manhattan", city: "east-harlem" },
    ],
    geo: { lat: 40.7677, lon: -73.9628 },
  },
  {
    slug: "houston-street",
    name: "Houston Street",
    shortName: "Houston",
    kind: "street",
    subType: "Crosstown Street",
    boroughs: ["manhattan"],
    segment: "Major Manhattan crosstown from FDR Drive at the East River to West Street at the Hudson, dividing SoHo from Greenwich Village and Lower East Side from East Village.",
    hazards: [
      "Westbound bottleneck at Lafayette generates rear-ends every weekday rush.",
      "Pothole and patchwork between Bowery and 6th Ave tears up tires.",
      "Wide cross-streets confuse left-turn rules — taxis cut across lanes and clip mirrors.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "flatbed-towing", "jump-start"],
    relatedNeighborhoods: [
      { state: "manhattan", city: "soho" },
      { state: "manhattan", city: "noho" },
      { state: "manhattan", city: "east-village" },
      { state: "manhattan", city: "lower-east-side" },
    ],
    geo: { lat: 40.7237, lon: -73.9974 },
  },
  {
    slug: "canal-street",
    name: "Canal Street",
    shortName: "Canal",
    kind: "street",
    subType: "Crosstown Street",
    boroughs: ["manhattan"],
    segment: "Crosses lower Manhattan from the Manhattan Bridge approach on the east to the Holland Tunnel entrance on the west. The single most congested NYC commercial truck corridor.",
    hazards: [
      "Box trucks and tractor-trailers heading for the Holland Tunnel back up to Lafayette every weekday.",
      "Manhattan Bridge feeder lanes generate constant lane-change incidents.",
      "Heavy potholes between Mott and Allen punish low-clearance sedans and EVs.",
      "Cyclist deliveries cutting through tunnel traffic cause door-strike incidents.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "heavy-duty-towing", "flat-tire-change"],
    relatedNeighborhoods: [
      { state: "manhattan", city: "chinatown" },
      { state: "manhattan", city: "tribeca" },
      { state: "manhattan", city: "soho" },
      { state: "manhattan", city: "two-bridges" },
    ],
    geo: { lat: 40.7193, lon: -74.0027 },
  },
  {
    slug: "delancey-street",
    name: "Delancey Street",
    shortName: "Delancey",
    kind: "street",
    subType: "Crosstown Street",
    boroughs: ["manhattan"],
    segment: "Major east-west connector feeding the Williamsburg Bridge from the Bowery. Carries heavy truck and rideshare volume in both directions.",
    hazards: [
      "Williamsburg Bridge approach generates constant cut-and-merge incidents.",
      "Pothole runs near Norfolk and Essex tear sidewalls.",
      "Eastbound bus lane and turn-only lane confusion near Allen catches out new drivers.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "flat-tire-change", "lockout-service"],
    relatedNeighborhoods: [
      { state: "manhattan", city: "lower-east-side" },
      { state: "manhattan", city: "two-bridges" },
    ],
    geo: { lat: 40.7181, lon: -73.9881 },
  },
  {
    slug: "bowery",
    name: "Bowery",
    kind: "street",
    subType: "Avenue",
    boroughs: ["manhattan"],
    segment: "Lower Manhattan north-south spine from Chatham Square to Cooper Square, connecting Chinatown, Lower East Side, NoLita, NoHo, and East Village.",
    hazards: [
      "Heavy delivery truck volume to Chinatown markets blocks the curb most mornings.",
      "Manhattan Bridge approach traffic backs up across Delancey.",
      "Older asphalt patches near Grand and Hester punish low-profile tires.",
    ],
    commonCalls: ["flat-tire-change", "lockout-service", "jump-start", "accident-recovery", "flatbed-towing"],
    relatedNeighborhoods: [
      { state: "manhattan", city: "chinatown" },
      { state: "manhattan", city: "nolita" },
      { state: "manhattan", city: "noho" },
      { state: "manhattan", city: "east-village" },
    ],
    geo: { lat: 40.7237, lon: -73.9925 },
  },
  {
    slug: "14th-street",
    name: "14th Street",
    kind: "street",
    subType: "Crosstown Street",
    boroughs: ["manhattan"],
    segment: "Major crosstown from the East River to the Hudson, with a busway between 3rd and 9th Avenues that restricts non-bus traffic during peak hours.",
    hazards: [
      "Busway restrictions mean private cars get rerouted and confused, generating impromptu turns.",
      "PATH and L train hubs (8th, 6th, Union Square) generate heavy taxi/rideshare drop-and-go.",
      "Pothole patches around 1st Ave and Avenue A take out tires.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "jump-start", "flatbed-towing"],
    relatedNeighborhoods: [
      { state: "manhattan", city: "union-square" },
      { state: "manhattan", city: "chelsea" },
      { state: "manhattan", city: "stuyvesant-town" },
    ],
    geo: { lat: 40.7370, lon: -73.9931 },
  },
  {
    slug: "34th-street",
    name: "34th Street",
    kind: "street",
    subType: "Crosstown Street",
    boroughs: ["manhattan"],
    segment: "Penn Station and Herald Square cross-spine, busiest mid-Manhattan crosstown for cars and buses.",
    hazards: [
      "Penn Station drop-off chaos generates constant fender-benders between Madison and 9th Avenue.",
      "Macy's loading-zone congestion blocks the right lane all day.",
      "Lincoln Tunnel feeder backups push west of 8th Avenue mid-afternoon.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "lockout-service", "flatbed-towing"],
    relatedNeighborhoods: [
      { state: "manhattan", city: "midtown" },
      { state: "manhattan", city: "hudson-yards" },
      { state: "manhattan", city: "murray-hill" },
    ],
    geo: { lat: 40.7488, lon: -73.9876 },
  },
  {
    slug: "42nd-street",
    name: "42nd Street",
    kind: "street",
    subType: "Crosstown Street",
    boroughs: ["manhattan"],
    segment: "Times Square / Grand Central / UN crosstown spine. Heavy tourist, theater, and commuter volume around the clock.",
    hazards: [
      "Times Square pedestrian plazas channel traffic into narrow lanes that pile up at the lights.",
      "Lincoln Tunnel approach backups extend across 10th and 11th avenues most afternoons.",
      "Tour bus loading at 8th and 42nd routinely blocks the curb.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "jump-start", "lockout-service"],
    relatedNeighborhoods: [
      { state: "manhattan", city: "times-square" },
      { state: "manhattan", city: "midtown" },
      { state: "manhattan", city: "hells-kitchen" },
      { state: "manhattan", city: "midtown-east" },
    ],
    geo: { lat: 40.7559, lon: -73.9866 },
  },
  {
    slug: "125th-street",
    name: "125th Street",
    kind: "street",
    subType: "Crosstown Street",
    boroughs: ["manhattan"],
    segment: "Harlem's main crosstown spine from the Hudson River to the Triboro/RFK Bridge approach.",
    hazards: [
      "Triboro approach backups generate rear-ends east of 2nd Avenue.",
      "Apollo Theater and Magic Johnson Theater event traffic clogs the central blocks.",
      "Heavy bus volume on the M60 SBS to LaGuardia narrows the usable curb.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "jump-start", "flatbed-towing"],
    relatedNeighborhoods: [
      { state: "manhattan", city: "harlem" },
      { state: "manhattan", city: "east-harlem" },
      { state: "manhattan", city: "morningside-heights" },
    ],
    geo: { lat: 40.8095, lon: -73.9457 },
  },

  // ── BROOKLYN ───────────────────────────────────────────────────────────────
  {
    slug: "atlantic-avenue",
    name: "Atlantic Avenue",
    kind: "street",
    subType: "Avenue",
    boroughs: ["brooklyn", "queens"],
    segment: "Runs from the Brooklyn waterfront at Furman Street east through Brooklyn Heights, Cobble Hill, Boerum Hill, Bed-Stuy, Crown Heights, East New York, and across the Queens line to JFK.",
    hazards: [
      "Heavy bus volume and the LIRR Atlantic Branch overpass at Flatbush generate squeeze points.",
      "Wide intersections with Flatbush, Nostrand, and Utica produce broadside collisions.",
      "Truck-heavy stretches through East New York generate frequent tire damage from debris.",
    ],
    commonCalls: ["accident-recovery", "heavy-duty-towing", "flatbed-towing", "flat-tire-change", "jump-start"],
    relatedNeighborhoods: [
      { state: "brooklyn", city: "brooklyn-heights" },
      { state: "brooklyn", city: "cobble-hill" },
      { state: "brooklyn", city: "boerum-hill" },
      { state: "brooklyn", city: "bed-stuy" },
      { state: "brooklyn", city: "crown-heights" },
    ],
    geo: { lat: 40.6837, lon: -73.9482 },
  },
  {
    slug: "flatbush-avenue",
    name: "Flatbush Avenue",
    kind: "street",
    subType: "Avenue",
    boroughs: ["brooklyn"],
    segment: "Brooklyn's longest commercial spine, running from the Manhattan Bridge approach south through Downtown Brooklyn, Prospect Heights, Flatbush, Midwood, and Marine Park to the Marine Parkway-Gil Hodges Bridge to the Rockaways.",
    hazards: [
      "Barclays Center event traffic generates surge collisions around Atlantic Avenue.",
      "Prospect Park southbound merge bottlenecks rear-end every weekday afternoon.",
      "Pothole runs through Flatbush proper and Marine Park tear sidewalls.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "flatbed-towing", "jump-start", "lockout-service"],
    relatedNeighborhoods: [
      { state: "brooklyn", city: "downtown-brooklyn" },
      { state: "brooklyn", city: "prospect-heights" },
      { state: "brooklyn", city: "flatbush" },
      { state: "brooklyn", city: "midwood" },
      { state: "brooklyn", city: "marine-park" },
    ],
    geo: { lat: 40.6489, lon: -73.9569 },
  },
  {
    slug: "bedford-avenue",
    name: "Bedford Avenue",
    shortName: "Bedford",
    kind: "street",
    subType: "Avenue",
    boroughs: ["brooklyn"],
    segment: "Brooklyn's longest avenue, running north-south from Greenpoint through Williamsburg, Bed-Stuy, Crown Heights, Flatbush, and down to Sheepshead Bay.",
    hazards: [
      "Williamsburg bar-and-restaurant strip generates constant double-park and door-strike incidents.",
      "Bike lane confusion in Williamsburg and Bed-Stuy creates car-cyclist incidents needing scene photos.",
      "Crown Heights truck routes generate tire damage from broken glass and curb edges.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "lockout-service", "jump-start", "flatbed-towing"],
    relatedNeighborhoods: [
      { state: "brooklyn", city: "williamsburg" },
      { state: "brooklyn", city: "bed-stuy" },
      { state: "brooklyn", city: "crown-heights" },
    ],
    geo: { lat: 40.7081, lon: -73.9571 },
  },
  {
    slug: "ocean-parkway",
    name: "Ocean Parkway",
    kind: "street",
    subType: "Parkway (surface)",
    boroughs: ["brooklyn"],
    segment: "Tree-lined parkway running from Prospect Park south to Brighton Beach and Coney Island. Service lanes flank a central through-roadway.",
    hazards: [
      "Light cycle confusion at the service/through-road merges generates clipped fender incidents.",
      "Wide unprotected left turns at Avenue P, Avenue U, and Kings Highway produce broadside collisions.",
      "Pothole runs near Avenue M and Avenue X chew tires every winter.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "jump-start", "flatbed-towing"],
    relatedNeighborhoods: [
      { state: "brooklyn", city: "kensington" },
      { state: "brooklyn", city: "midwood" },
      { state: "brooklyn", city: "gravesend" },
      { state: "brooklyn", city: "brighton-beach" },
    ],
    geo: { lat: 40.6090, lon: -73.9684 },
  },
  {
    slug: "eastern-parkway",
    name: "Eastern Parkway",
    kind: "street",
    subType: "Parkway (surface)",
    boroughs: ["brooklyn"],
    segment: "Olmsted-designed boulevard from Grand Army Plaza east through Crown Heights and Brownsville to Ralph Avenue.",
    hazards: [
      "West Indian Day Parade and event closures redirect traffic onto unfamiliar side streets.",
      "Service-road turn cuts confuse drivers unfamiliar with the parkway pattern.",
      "Heavy Hasidic school-pickup traffic on weekday afternoons through Crown Heights.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "jump-start", "lockout-service"],
    relatedNeighborhoods: [
      { state: "brooklyn", city: "crown-heights" },
      { state: "brooklyn", city: "prospect-heights" },
      { state: "brooklyn", city: "brownsville" },
    ],
    geo: { lat: 40.6709, lon: -73.9442 },
  },
  {
    slug: "4th-avenue-brooklyn",
    name: "4th Avenue (Brooklyn)",
    shortName: "4th Ave",
    kind: "street",
    subType: "Avenue",
    boroughs: ["brooklyn"],
    segment: "North-south spine from Atlantic Avenue south through Park Slope, Gowanus, Sunset Park, and Bay Ridge to the Verrazzano on-ramp at the Belt Parkway.",
    hazards: [
      "BQE on/off ramp incidents at 3rd Street and 38th Street routinely.",
      "Heavy Sunset Park commercial truck volume generates wide-turn incidents.",
      "Verrazzano-bound traffic stacks every weekday afternoon south of 65th Street.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "heavy-duty-towing", "flat-tire-change"],
    relatedNeighborhoods: [
      { state: "brooklyn", city: "park-slope" },
      { state: "brooklyn", city: "gowanus" },
      { state: "brooklyn", city: "sunset-park" },
      { state: "brooklyn", city: "bay-ridge" },
    ],
    geo: { lat: 40.6602, lon: -73.9923 },
  },
  {
    slug: "kings-highway",
    name: "Kings Highway",
    kind: "street",
    subType: "Boulevard",
    boroughs: ["brooklyn"],
    segment: "Major southern Brooklyn east-west spine from Bay Parkway east through Midwood, Flatlands, and Canarsie to the Belt Parkway.",
    hazards: [
      "Heavy commercial truck volume east of Coney Island Ave generates curbside incidents.",
      "Belt Parkway on-ramp at Pennsylvania generates rear-ends in heavy rain.",
      "Pothole runs near Ocean Ave and Nostrand consistently tear tires.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "jump-start", "flatbed-towing"],
    relatedNeighborhoods: [
      { state: "brooklyn", city: "midwood" },
      { state: "brooklyn", city: "flatbush" },
      { state: "brooklyn", city: "flatlands" },
      { state: "brooklyn", city: "canarsie" },
    ],
    geo: { lat: 40.6191, lon: -73.9579 },
  },
  {
    slug: "nostrand-avenue",
    name: "Nostrand Avenue",
    kind: "street",
    subType: "Avenue",
    boroughs: ["brooklyn"],
    segment: "Runs from Williamsburg south through Bed-Stuy, Crown Heights, Flatbush, Midwood, Sheepshead Bay, and the foot of the Marine Parkway Bridge to the Rockaways.",
    hazards: [
      "Heavy bus volume on the B44 SBS narrows curb access most of the day.",
      "Sheepshead Bay congestion around Emmons backs up flooding the southern end.",
      "Crosstown traffic at Eastern Parkway and Empire Boulevard generates broadside incidents.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "jump-start", "lockout-service"],
    relatedNeighborhoods: [
      { state: "brooklyn", city: "bed-stuy" },
      { state: "brooklyn", city: "crown-heights" },
      { state: "brooklyn", city: "flatbush" },
      { state: "brooklyn", city: "midwood" },
      { state: "brooklyn", city: "sheepshead-bay" },
    ],
    geo: { lat: 40.6473, lon: -73.9485 },
  },
  {
    slug: "myrtle-avenue",
    name: "Myrtle Avenue",
    kind: "street",
    subType: "Avenue",
    boroughs: ["brooklyn", "queens"],
    segment: "Runs from Downtown Brooklyn east through Fort Greene, Clinton Hill, Bed-Stuy, Bushwick, and across the Queens line into Ridgewood and Glendale.",
    hazards: [
      "BQE Brooklyn-bound off-ramp at Myrtle backs up afternoon rush.",
      "Bushwick warehouse truck traffic generates broken-glass tire incidents.",
      "Pratt Institute event drop-off blocks the curb seasonally.",
    ],
    commonCalls: ["flat-tire-change", "accident-recovery", "jump-start", "flatbed-towing"],
    relatedNeighborhoods: [
      { state: "brooklyn", city: "fort-greene" },
      { state: "brooklyn", city: "clinton-hill" },
      { state: "brooklyn", city: "bed-stuy" },
      { state: "brooklyn", city: "bushwick" },
    ],
    geo: { lat: 40.6970, lon: -73.9301 },
  },
  {
    slug: "fulton-street-brooklyn",
    name: "Fulton Street (Brooklyn)",
    kind: "street",
    subType: "Avenue",
    boroughs: ["brooklyn"],
    segment: "Major commercial spine from Downtown Brooklyn east through Fort Greene, Clinton Hill, Bed-Stuy, and East New York to the Queens line.",
    hazards: [
      "B25 and B26 bus volume narrows curb access from Fort Greene through Bed-Stuy.",
      "Heavy taxi rideshare drop-off around the Atlantic Terminal anchor point.",
      "Truck-route stretches east of Bed-Stuy generate frequent tire damage.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "lockout-service", "jump-start"],
    relatedNeighborhoods: [
      { state: "brooklyn", city: "downtown-brooklyn" },
      { state: "brooklyn", city: "fort-greene" },
      { state: "brooklyn", city: "bed-stuy" },
      { state: "brooklyn", city: "east-new-york" },
    ],
    geo: { lat: 40.6818, lon: -73.9456 },
  },
  {
    slug: "coney-island-avenue",
    name: "Coney Island Avenue",
    kind: "street",
    subType: "Avenue",
    boroughs: ["brooklyn"],
    segment: "Runs straight south from Prospect Park through Kensington, Midwood, and Gravesend to Coney Island.",
    hazards: [
      "Heavy black-car and livery volume generates rear-end incidents at Avenue J and Kings Highway.",
      "Pothole runs near Cortelyou and Avenue P chew tires.",
      "Coney Island event traffic compresses southern blocks every summer weekend.",
    ],
    commonCalls: ["flat-tire-change", "jump-start", "accident-recovery", "flatbed-towing"],
    relatedNeighborhoods: [
      { state: "brooklyn", city: "kensington" },
      { state: "brooklyn", city: "midwood" },
      { state: "brooklyn", city: "gravesend" },
      { state: "brooklyn", city: "coney-island" },
    ],
    geo: { lat: 40.6191, lon: -73.9714 },
  },
  {
    slug: "linden-boulevard",
    name: "Linden Boulevard",
    kind: "street",
    subType: "Boulevard",
    boroughs: ["brooklyn", "queens"],
    segment: "Runs from East Flatbush across East New York, Brownsville, and into Queens through Jamaica.",
    hazards: [
      "Wide intersections at Pennsylvania, Schenck, and Conduit produce broadside collisions.",
      "Heavy commercial truck volume east of Pennsylvania tears tires on debris.",
      "Belt Parkway entrance at Pennsylvania creates evening rush bottleneck.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "heavy-duty-towing", "flat-tire-change"],
    relatedNeighborhoods: [
      { state: "brooklyn", city: "east-flatbush" },
      { state: "brooklyn", city: "east-new-york" },
      { state: "queens", city: "jamaica" },
    ],
    geo: { lat: 40.6611, lon: -73.9118 },
  },

  // ── QUEENS ─────────────────────────────────────────────────────────────────
  {
    slug: "queens-boulevard",
    name: "Queens Boulevard",
    shortName: "Queens Blvd",
    kind: "street",
    subType: "Boulevard",
    boroughs: ["queens"],
    segment: "Wide multi-lane boulevard running from the Queensboro Bridge east through Long Island City, Sunnyside, Woodside, Elmhurst, Rego Park, Forest Hills, Kew Gardens, and Briarwood to Jamaica.",
    hazards: [
      "Historic 'Boulevard of Death' nickname earned through wide unprotected pedestrian crossings — incidents still common near Woodside and Elmhurst.",
      "Service-road / through-road weaves confuse out-of-borough drivers.",
      "Heavy bus volume on the Q60 narrows the right lane through the corridor.",
      "Pothole runs near Junction Boulevard tear sidewalls.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "flatbed-towing", "jump-start", "lockout-service"],
    relatedNeighborhoods: [
      { state: "queens", city: "long-island-city" },
      { state: "queens", city: "sunnyside" },
      { state: "queens", city: "woodside" },
      { state: "queens", city: "elmhurst" },
      { state: "queens", city: "rego-park" },
      { state: "queens", city: "forest-hills" },
      { state: "queens", city: "kew-gardens" },
    ],
    geo: { lat: 40.7363, lon: -73.8830 },
  },
  {
    slug: "northern-boulevard",
    name: "Northern Boulevard",
    shortName: "Northern Blvd",
    kind: "street",
    subType: "Boulevard",
    boroughs: ["queens"],
    segment: "Runs from the Queensboro Bridge east through Long Island City, Astoria, Jackson Heights, Corona, Flushing, Bayside, Douglaston, and across the Nassau line as Route 25A.",
    hazards: [
      "Citi Field event traffic compresses the corridor around 114th Street.",
      "LaGuardia airport feed traffic generates constant lane changes near 82nd through 94th.",
      "Pothole runs near the Roosevelt Avenue overpass cluster damage tires.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "flat-tire-change", "jump-start", "lockout-service"],
    relatedNeighborhoods: [
      { state: "queens", city: "long-island-city" },
      { state: "queens", city: "astoria" },
      { state: "queens", city: "jackson-heights" },
      { state: "queens", city: "corona" },
      { state: "queens", city: "flushing" },
      { state: "queens", city: "bayside" },
    ],
    geo: { lat: 40.7644, lon: -73.8617 },
  },
  {
    slug: "roosevelt-avenue",
    name: "Roosevelt Avenue",
    kind: "street",
    subType: "Avenue",
    boroughs: ["queens"],
    segment: "Runs from Long Island City east through Sunnyside, Woodside, Jackson Heights, Corona, and Flushing under the elevated 7 train.",
    hazards: [
      "Heavy elevated train infrastructure restricts overhead clearance for high flatbeds — we route taller jobs via Northern.",
      "Heavy pedestrian, bus, and double-park volume narrows lanes.",
      "Corona and Flushing market congestion generates daily fender-benders.",
    ],
    commonCalls: ["flat-tire-change", "jump-start", "accident-recovery", "lockout-service"],
    relatedNeighborhoods: [
      { state: "queens", city: "sunnyside" },
      { state: "queens", city: "woodside" },
      { state: "queens", city: "jackson-heights" },
      { state: "queens", city: "corona" },
      { state: "queens", city: "flushing" },
    ],
    geo: { lat: 40.7457, lon: -73.8909 },
  },
  {
    slug: "astoria-boulevard",
    name: "Astoria Boulevard",
    kind: "street",
    subType: "Boulevard",
    boroughs: ["queens"],
    segment: "Western Queens spine running parallel to the Grand Central Parkway from the Triboro/RFK Bridge east toward LaGuardia.",
    hazards: [
      "GCP on/off ramps at 31st Street and Hoyt Avenue generate merge incidents.",
      "Triboro toll plaza approach backups generate rear-ends.",
      "LaGuardia-bound rideshare drop-and-go at 94th creates constant curb chaos.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "flat-tire-change", "jump-start"],
    relatedNeighborhoods: [
      { state: "queens", city: "astoria" },
      { state: "queens", city: "east-elmhurst" },
    ],
    geo: { lat: 40.7758, lon: -73.9176 },
  },
  {
    slug: "woodhaven-boulevard",
    name: "Woodhaven Boulevard",
    kind: "street",
    subType: "Boulevard",
    boroughs: ["queens"],
    segment: "Major north-south spine connecting the LIE in Elmhurst south through Rego Park, Forest Hills, Richmond Hill, and Woodhaven, eventually continuing as Cross Bay Boulevard.",
    hazards: [
      "Heavy commercial truck volume generates broadside collisions at Metropolitan and Atlantic.",
      "Costco and Rego Park Mall traffic compresses the northern end on weekends.",
      "Pothole runs near Atlantic Avenue overpass tear tires.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "flatbed-towing", "jump-start"],
    relatedNeighborhoods: [
      { state: "queens", city: "rego-park" },
      { state: "queens", city: "forest-hills" },
      { state: "queens", city: "richmond-hill" },
      { state: "queens", city: "woodhaven" },
    ],
    geo: { lat: 40.7077, lon: -73.8593 },
  },
  {
    slug: "cross-bay-boulevard",
    name: "Cross Bay Boulevard",
    kind: "street",
    subType: "Boulevard",
    boroughs: ["queens"],
    segment: "Continuation of Woodhaven south across Jamaica Bay via the Cross Bay Veterans Memorial Bridge to Broad Channel and the Rockaways.",
    hazards: [
      "Crosswind incidents on the bridge stretches in winter.",
      "Beach traffic congestion every summer weekend.",
      "Salt-air corrosion produces frequent battery and electrical failures from Broad Channel south.",
    ],
    commonCalls: ["jump-start", "battery-replacement", "accident-recovery", "flat-tire-change", "flatbed-towing"],
    relatedNeighborhoods: [
      { state: "queens", city: "howard-beach" },
      { state: "queens", city: "broad-channel" },
      { state: "queens", city: "rockaway-beach" },
    ],
    geo: { lat: 40.6308, lon: -73.8243 },
  },
  {
    slug: "rockaway-boulevard",
    name: "Rockaway Boulevard",
    kind: "street",
    subType: "Boulevard",
    boroughs: ["queens"],
    segment: "Major southern Queens spine from East New York east through Ozone Park, Howard Beach, JFK Airport, and Springfield Gardens.",
    hazards: [
      "Heavy JFK cargo truck volume generates broadside incidents at the Aqueduct turn.",
      "Belt Parkway service-road weave east of Lefferts produces lane-change clips.",
      "Pothole runs near the Aqueduct and Resorts World tear tires.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "heavy-duty-towing", "flat-tire-change", "jump-start"],
    relatedNeighborhoods: [
      { state: "queens", city: "ozone-park" },
      { state: "queens", city: "howard-beach" },
      { state: "queens", city: "south-ozone-park" },
      { state: "queens", city: "springfield-gardens" },
    ],
    geo: { lat: 40.6772, lon: -73.8082 },
  },
  {
    slug: "hillside-avenue",
    name: "Hillside Avenue",
    kind: "street",
    subType: "Avenue",
    boroughs: ["queens"],
    segment: "Major southeast Queens commercial spine running from Kew Gardens through Jamaica, Hollis, Queens Village, and Bellerose to the Nassau line as Route 25.",
    hazards: [
      "Heavy bus volume on the Q43 narrows lanes.",
      "Jamaica Center commercial drop-off blocks curb access most of the day.",
      "Pothole runs through Hollis tear sidewalls.",
    ],
    commonCalls: ["flat-tire-change", "jump-start", "accident-recovery", "lockout-service"],
    relatedNeighborhoods: [
      { state: "queens", city: "jamaica" },
      { state: "queens", city: "hollis" },
      { state: "queens", city: "queens-village" },
      { state: "queens", city: "bellerose" },
    ],
    geo: { lat: 40.7140, lon: -73.7920 },
  },
  {
    slug: "jamaica-avenue",
    name: "Jamaica Avenue",
    kind: "street",
    subType: "Avenue",
    boroughs: ["queens"],
    segment: "Runs from the Brooklyn line at Cypress Hills east through Woodhaven, Richmond Hill, Jamaica, and Queens Village.",
    hazards: [
      "J train elevated structure restricts overhead clearance through Richmond Hill.",
      "Jamaica Center congestion produces constant fender-benders at 165th Street.",
      "Pothole runs west of Sutphin tear tires.",
    ],
    commonCalls: ["flat-tire-change", "accident-recovery", "jump-start", "lockout-service"],
    relatedNeighborhoods: [
      { state: "queens", city: "woodhaven" },
      { state: "queens", city: "richmond-hill" },
      { state: "queens", city: "jamaica" },
    ],
    geo: { lat: 40.6928, lon: -73.8003 },
  },
  {
    slug: "main-street-flushing",
    name: "Main Street (Flushing)",
    kind: "street",
    subType: "Avenue",
    boroughs: ["queens"],
    segment: "Flushing's central commercial spine from Northern Boulevard south to the Long Island Expressway and beyond into Kew Gardens Hills.",
    hazards: [
      "Densest pedestrian congestion in Queens — frequent door strikes and curb fender-benders.",
      "Bus-stop double-park stacking blocks the right lane constantly.",
      "Heavy commercial delivery weaving narrows the through-lane.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "lockout-service", "jump-start", "flatbed-towing"],
    relatedNeighborhoods: [
      { state: "queens", city: "flushing" },
    ],
    geo: { lat: 40.7649, lon: -73.8311 },
  },
  {
    slug: "union-turnpike",
    name: "Union Turnpike",
    kind: "street",
    subType: "Turnpike",
    boroughs: ["queens"],
    segment: "Runs from Kew Gardens east through Briarwood, Fresh Meadows, and Glen Oaks to the Nassau line.",
    hazards: [
      "Grand Central Parkway service-road merge near Park Lane South generates lane-change incidents.",
      "Heavy hospital traffic at Long Island Jewish narrows lanes.",
      "Pothole runs east of Utopia Parkway tear tires.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "jump-start", "flatbed-towing"],
    relatedNeighborhoods: [
      { state: "queens", city: "kew-gardens" },
      { state: "queens", city: "briarwood" },
      { state: "queens", city: "fresh-meadows" },
      { state: "queens", city: "glen-oaks" },
    ],
    geo: { lat: 40.7188, lon: -73.7849 },
  },
  {
    slug: "francis-lewis-boulevard",
    name: "Francis Lewis Boulevard",
    kind: "street",
    subType: "Boulevard",
    boroughs: ["queens"],
    segment: "Major north-south spine in eastern Queens, from Whitestone south through Bayside, Queens Village, Cambria Heights, and Laurelton to the Belt Parkway.",
    hazards: [
      "Wide unprotected left turns at Hillside Ave and Linden Blvd produce broadside collisions.",
      "Heavy school-pickup volume through Bayside in the afternoon.",
      "Pothole runs near the Cross Island Parkway interchange tear tires.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "jump-start", "lockout-service"],
    relatedNeighborhoods: [
      { state: "queens", city: "bayside" },
      { state: "queens", city: "queens-village" },
      { state: "queens", city: "cambria-heights" },
      { state: "queens", city: "laurelton" },
    ],
    geo: { lat: 40.7461, lon: -73.7691 },
  },

  // ── BRONX ──────────────────────────────────────────────────────────────────
  {
    slug: "grand-concourse",
    name: "Grand Concourse",
    kind: "street",
    subType: "Boulevard",
    boroughs: ["bronx"],
    segment: "Bronx's signature tree-lined boulevard running from Mott Haven north through Concourse, Highbridge, Mount Eden, Tremont, Fordham, and Bedford Park to Mosholu Parkway.",
    hazards: [
      "Yankee Stadium event traffic compresses the southern stretches.",
      "Wide intersections at 161st, 167th, Tremont, and Fordham produce broadside collisions.",
      "Pothole runs near 138th and 149th tear sidewalls.",
      "Service-road / through-road weaves catch out unfamiliar drivers.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "flatbed-towing", "jump-start", "lockout-service"],
    relatedNeighborhoods: [
      { state: "bronx", city: "mott-haven" },
      { state: "bronx", city: "concourse" },
      { state: "bronx", city: "highbridge" },
      { state: "bronx", city: "tremont" },
      { state: "bronx", city: "fordham" },
      { state: "bronx", city: "bedford-park" },
    ],
    geo: { lat: 40.8407, lon: -73.9034 },
  },
  {
    slug: "fordham-road",
    name: "Fordham Road",
    kind: "street",
    subType: "Crosstown",
    boroughs: ["bronx"],
    segment: "Major Bronx crosstown spine from the Henry Hudson Bridge through Kingsbridge, University Heights, Fordham, Belmont, and Bronx Park East.",
    hazards: [
      "Heaviest bus volume in the Bronx on the Bx12 SBS — narrow curb access.",
      "Fordham University event traffic compresses the central blocks.",
      "Wide intersections at Webster, Third, and Southern Boulevard generate broadside collisions.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "jump-start", "lockout-service"],
    relatedNeighborhoods: [
      { state: "bronx", city: "kingsbridge" },
      { state: "bronx", city: "university-heights" },
      { state: "bronx", city: "fordham" },
      { state: "bronx", city: "belmont" },
    ],
    geo: { lat: 40.8615, lon: -73.8975 },
  },
  {
    slug: "bruckner-boulevard",
    name: "Bruckner Boulevard",
    kind: "street",
    subType: "Boulevard",
    boroughs: ["bronx"],
    segment: "Service-road equivalent of the Bruckner Expressway, running from Mott Haven east through Hunts Point, Soundview, and Throgs Neck.",
    hazards: [
      "Hunts Point Market truck volume produces constant tire damage and broadside risk.",
      "Bruckner Expressway on/off ramp incidents at every interchange.",
      "Pothole runs near Castle Hill consistently tear sidewalls.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "heavy-duty-towing", "flat-tire-change"],
    relatedNeighborhoods: [
      { state: "bronx", city: "mott-haven" },
      { state: "bronx", city: "hunts-point" },
      { state: "bronx", city: "soundview" },
      { state: "bronx", city: "throgs-neck" },
    ],
    geo: { lat: 40.8190, lon: -73.8616 },
  },
  {
    slug: "white-plains-road",
    name: "White Plains Road",
    kind: "street",
    subType: "Avenue",
    boroughs: ["bronx"],
    segment: "Major Bronx north-south spine under the 2 train elevated, running from Soundview through Williamsbridge, Wakefield, and into Mount Vernon.",
    hazards: [
      "Heavy elevated infrastructure restricts overhead clearance.",
      "Heavy bus volume narrows lanes through the corridor.",
      "Pothole runs through Williamsbridge tear tires.",
    ],
    commonCalls: ["flat-tire-change", "jump-start", "accident-recovery", "lockout-service"],
    relatedNeighborhoods: [
      { state: "bronx", city: "soundview" },
      { state: "bronx", city: "williamsbridge" },
      { state: "bronx", city: "wakefield" },
    ],
    geo: { lat: 40.8714, lon: -73.8625 },
  },
  {
    slug: "jerome-avenue",
    name: "Jerome Avenue",
    kind: "street",
    subType: "Avenue",
    boroughs: ["bronx"],
    segment: "Runs from Yankee Stadium north under the 4 train elevated through Highbridge, Mount Eden, Mount Hope, Fordham, and Bedford Park.",
    hazards: [
      "Heavy auto-body shop concentration generates frequent recovery-tow drop-offs.",
      "Yankee Stadium event traffic stacks southbound at 161st.",
      "Pothole runs north of 184th tear tires.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "auto-body-collision-delivery", "flat-tire-change", "jump-start"],
    relatedNeighborhoods: [
      { state: "bronx", city: "highbridge" },
      { state: "bronx", city: "mount-eden" },
      { state: "bronx", city: "fordham" },
      { state: "bronx", city: "bedford-park" },
    ],
    geo: { lat: 40.8473, lon: -73.9001 },
  },
  {
    slug: "tremont-avenue",
    name: "Tremont Avenue (East & West)",
    kind: "street",
    subType: "Crosstown",
    boroughs: ["bronx"],
    segment: "Crosses the Bronx from the Hudson at University Heights east through Tremont, Belmont, West Farms, and across the Whitestone Expressway to Throgs Neck.",
    hazards: [
      "Cross Bronx Expressway service-road weaves generate constant lane-change incidents.",
      "Heavy truck volume east of Webster tears tires from debris.",
      "Major school-pickup volume at Christopher Columbus High narrows the central blocks.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "flat-tire-change", "jump-start", "heavy-duty-towing"],
    relatedNeighborhoods: [
      { state: "bronx", city: "tremont" },
      { state: "bronx", city: "belmont" },
      { state: "bronx", city: "west-farms" },
      { state: "bronx", city: "throgs-neck" },
    ],
    geo: { lat: 40.8488, lon: -73.8775 },
  },
  {
    slug: "pelham-parkway",
    name: "Pelham Parkway",
    kind: "street",
    subType: "Parkway (surface)",
    boroughs: ["bronx"],
    segment: "Tree-lined parkway running from the Bronx River Parkway east through Pelham Parkway South / North to the Hutchinson River Parkway.",
    hazards: [
      "Wide unprotected left turns at White Plains Road generate broadside incidents.",
      "Hutch on-ramp backups stack eastbound.",
      "Heavy hospital traffic at Jacobi narrows lanes.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "jump-start", "flatbed-towing"],
    relatedNeighborhoods: [
      { state: "bronx", city: "pelham-parkway" },
      { state: "bronx", city: "morris-park" },
    ],
    geo: { lat: 40.8567, lon: -73.8516 },
  },

  // ── STATEN ISLAND ──────────────────────────────────────────────────────────
  {
    slug: "hylan-boulevard",
    name: "Hylan Boulevard",
    kind: "street",
    subType: "Boulevard",
    boroughs: ["staten-island"],
    segment: "Staten Island's signature commercial spine, running 14 miles from Rosebank through Grasmere, Dongan Hills, New Dorp, Great Kills, Eltingville, Annadale, Huguenot, and Tottenville.",
    hazards: [
      "Wide unprotected left turns at New Dorp Lane, Tysens Lane, and Richmond Avenue produce frequent broadside collisions.",
      "Deer strikes after dusk south of Annadale are routine — collision tows generated nightly.",
      "Snow-buildup along the wide curb makes winter recovery work common.",
      "Pothole runs near Grasmere and Dongan Hills tear sidewalls.",
    ],
    commonCalls: ["accident-recovery", "flatbed-towing", "flat-tire-change", "jump-start", "lockout-service"],
    relatedNeighborhoods: [
      { state: "staten-island", city: "rosebank" },
      { state: "staten-island", city: "dongan-hills" },
      { state: "staten-island", city: "new-dorp" },
      { state: "staten-island", city: "great-kills" },
      { state: "staten-island", city: "annadale" },
      { state: "staten-island", city: "tottenville" },
    ],
    geo: { lat: 40.5742, lon: -74.1175 },
  },
  {
    slug: "richmond-avenue",
    name: "Richmond Avenue",
    kind: "street",
    subType: "Avenue",
    boroughs: ["staten-island"],
    segment: "Mid-Island north-south spine connecting the Staten Island Mall area to Eltingville and Annadale.",
    hazards: [
      "Heavy weekend mall traffic at the Korean War Veterans Pkwy interchange stacks.",
      "Wide intersections at Forest Hill Road and Drumgoole produce broadside incidents.",
      "Pothole runs near the SI Mall lots tear sidewalls.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "jump-start", "lockout-service", "flatbed-towing"],
    relatedNeighborhoods: [
      { state: "staten-island", city: "new-springville" },
      { state: "staten-island", city: "bulls-head" },
      { state: "staten-island", city: "eltingville" },
    ],
    geo: { lat: 40.5856, lon: -74.1593 },
  },
  {
    slug: "victory-boulevard",
    name: "Victory Boulevard",
    kind: "street",
    subType: "Boulevard",
    boroughs: ["staten-island"],
    segment: "Runs from the ferry terminal at St. George west through Tompkinsville, Silver Lake, Sunnyside, Travis, and into Bloomfield.",
    hazards: [
      "Steep grades through Silver Lake produce brake-fade incidents in older cars.",
      "Wide unprotected left turns at Bay Street and Forest Avenue generate broadside collisions.",
      "Pothole runs near Clove Road tear tires.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "jump-start", "flatbed-towing"],
    relatedNeighborhoods: [
      { state: "staten-island", city: "st-george" },
      { state: "staten-island", city: "tompkinsville" },
      { state: "staten-island", city: "silver-lake" },
      { state: "staten-island", city: "sunnyside" },
    ],
    geo: { lat: 40.6157, lon: -74.1018 },
  },
  {
    slug: "forest-avenue",
    name: "Forest Avenue",
    kind: "street",
    subType: "Avenue",
    boroughs: ["staten-island"],
    segment: "Northern Staten Island east-west spine from West Brighton through Port Richmond and into Mariner's Harbor.",
    hazards: [
      "Heavy commercial truck volume west of Manor Road tears tires from broken glass.",
      "Wide intersections at Jewett and Bement generate broadside collisions.",
      "Pothole runs through Port Richmond consistently tear sidewalls.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "flatbed-towing", "jump-start"],
    relatedNeighborhoods: [
      { state: "staten-island", city: "west-brighton" },
      { state: "staten-island", city: "port-richmond" },
      { state: "staten-island", city: "mariners-harbor" },
    ],
    geo: { lat: 40.6311, lon: -74.1372 },
  },
  {
    slug: "amboy-road",
    name: "Amboy Road",
    kind: "street",
    subType: "Road",
    boroughs: ["staten-island"],
    segment: "Runs parallel south of Hylan through Great Kills, Eltingville, Annadale, Huguenot, Prince's Bay, and Tottenville.",
    hazards: [
      "Deer-strike incidents after dusk south of Huguenot are common.",
      "Wide unprotected lefts at Page Avenue and Bloomingdale generate broadside collisions.",
      "Pothole runs in winter tear sidewalls.",
    ],
    commonCalls: ["accident-recovery", "flat-tire-change", "jump-start", "lockout-service"],
    relatedNeighborhoods: [
      { state: "staten-island", city: "great-kills" },
      { state: "staten-island", city: "annadale" },
      { state: "staten-island", city: "huguenot" },
      { state: "staten-island", city: "princes-bay" },
      { state: "staten-island", city: "tottenville" },
    ],
    geo: { lat: 40.5400, lon: -74.1885 },
  },
];