// @ts-nocheck
// Auto-generated: 100 NYC Towing & Roadside Tips series.
// Generator: scripts/generate-tips-100.py
// Note: shape defined locally (matches BlogPost in blog-posts.ts) to avoid a circular import.
interface TipPost {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  content: string[];
}

export const TIPS_100: TipPost[] = [
  {
    slug: "tip-001-winter-cold-cranks-battery",
    title: "Tip #1: Cold Cranks Kill Marginal Batteries First",
    excerpt: "NYC overnight lows in the teens between January and March kill any battery that's already weak. Cold thickens the electrolyte, the alternator hasn't had time to…",
    category: "Winter",
    date: "May 19, 2026",
    content: [
      "NYC overnight lows in the teens between January and March kill any battery that's already weak. Cold thickens the electrolyte, the alternator hasn't had time to top it back up since last night's drive, and the starter draws more amps than usual to crank a cold engine.",
      "If your battery is more than 3 years old and you've had even one slow-crank morning this winter, replace it before it strands you. Standard group sizes run $150–$250; we stock the most common ones on every truck and can swap on the curb.",
      "If you're stranded, we run battery service at the same $149 / hour rate (1-hour minimum, $124 first hour when you book online). Driver brings a real load tester — not a $20 voltmeter — and tells you whether you need a jump or a replacement before doing anything.",
    ],
  },
  {
    slug: "tip-002-winter-tire-pressure-drop",
    title: "Tip #2: Tire Pressure Drops 1 PSI for Every 10°F",
    excerpt: "When the temperature swings from a 50°F afternoon to a 10°F overnight low, your tire pressure drops about 4 PSI from where you set it. If you started near the l…",
    category: "Winter",
    date: "May 19, 2026",
    content: [
      "When the temperature swings from a 50°F afternoon to a 10°F overnight low, your tire pressure drops about 4 PSI from where you set it. If you started near the lower end of the recommended range, you're now riding on under-inflated tires.",
      "Under-inflated tires generate more heat at highway speed, wear unevenly, hurt fuel economy, and increase the chance of a sidewall failure on a pothole strike. The TPMS light will warn you on most modern cars, but the light triggers around 25% under-pressure — by then you've been driving on soft tires for a while.",
      "Check pressure on a cold morning every two weeks in winter. Use a real gauge, not the one at the gas station that reads 'EEEEE'. If you catch a flat or a pothole strike on the BQE or Cross Bronx, we run tire service at our standard hourly rate.",
    ],
  },
  {
    slug: "tip-003-winter-block-heater-extreme-cold",
    title: "Tip #3: Block Heater Is Worth It Below 10°F",
    excerpt: "Most NYC commuters don't run a block heater because we don't think of ourselves as a 'cold' city. But a Polar Vortex morning at -5°F is rough on any engine — an…",
    category: "Winter",
    date: "May 19, 2026",
    content: [
      "Most NYC commuters don't run a block heater because we don't think of ourselves as a 'cold' city. But a Polar Vortex morning at -5°F is rough on any engine — and brutal on diesels. A block heater plugged in for 2–4 hours pre-startup saves the battery, the starter, and the engine.",
      "Outdoor outlets are common in private driveways in the outer boroughs and Staten Island. Manhattan curb-parkers can't realistically run one. If you're a curb-parker in the cold and your car won't start, a block heater isn't an option — battery replacement and a fresh thermostat are.",
      "If your car won't crank below freezing, call us. We diagnose on scene at $149 / hour (book online for $124 first hour) and replace the battery on the curb if that's the fix.",
    ],
  },
  {
    slug: "tip-004-winter-snow-stuck-what-not-to-do",
    title: "Tip #4: Stuck in Snow: What NOT to Do",
    excerpt: "Don't keep flooring it. Spinning tires in snow polishes the surface beneath them into ice, glazes the rubber, and digs you in deeper. After two failed rocks, st…",
    category: "Winter",
    date: "May 19, 2026",
    content: [
      "Don't keep flooring it. Spinning tires in snow polishes the surface beneath them into ice, glazes the rubber, and digs you in deeper. After two failed rocks, stop. Each subsequent attempt makes the recovery harder.",
      "Don't dig with anything sharp near the tire. A bent tire iron, a thin shovel edge, even a key — anything that punctures a sidewall converts a stuck-car problem into a stuck-car-with-flat-tire problem.",
      "Do call winch-out recovery. We arrive with proper winch capacity, snatch blocks for awkward angles, and we know which corner of the vehicle is the right pull point for your year/make/model. Standard $149 / hour rate, 1-hour minimum, $124 first hour online.",
    ],
  },
  {
    slug: "tip-005-winter-alt-side-parking-snow-rules",
    title: "Tip #5: Alt-Side Parking Changes During Snow Emergencies",
    excerpt: "NYC suspends alt-side parking during declared snow emergencies, but the suspension dates change every season. Check 311 or the NYC ASP app before you skip a swe…",
    category: "Winter",
    date: "May 19, 2026",
    content: [
      "NYC suspends alt-side parking during declared snow emergencies, but the suspension dates change every season. Check 311 or the NYC ASP app before you skip a sweeper. Skipping when ASP is in effect = $65 ticket plus tow risk on accumulation days.",
      "The 'snow gentleman's rule' for shoveled-out spots has no legal weight. Reclaiming a spot with a folding chair won't stop NYPD from ticketing the next driver. It also won't stop a Sanitation tow if the street is being plowed.",
      "If your car gets towed during snow conditions, recovery is more involved than a normal pound visit — Pier 76 and the borough pounds are extra-busy. We run impound recovery service so you don't lose a full day in line. Standard $149 / hour rate.",
    ],
  },
  {
    slug: "tip-006-winter-frozen-door-lock",
    title: "Tip #6: Frozen Door Lock — Don't Force the Key",
    excerpt: "Forcing a key into a frozen lock cylinder bends pins inside. Once they're bent, no amount of de-icer fixes it — you need the cylinder rebuilt or replaced. The f…",
    category: "Winter",
    date: "May 19, 2026",
    content: [
      "Forcing a key into a frozen lock cylinder bends pins inside. Once they're bent, no amount of de-icer fixes it — you need the cylinder rebuilt or replaced. The fix is patience: warm the key, not the lock, then insert.",
      "Hand-warm the key in your pocket for a minute. Slide it in slowly. If it stops, withdraw, warm again, retry. De-icer (CRC, WD-40 specialist) sprayed sparingly into the keyhole helps once the key will go halfway in.",
      "If you're locked out entirely and the fob has died, we run lockout service at our standard $149 / hour rate. Most calls finish inside 10 minutes — well inside the 1-hour minimum. Book online for $124 first hour.",
    ],
  },
  {
    slug: "tip-007-winter-ice-covered-car-strategy",
    title: "Tip #7: Ice-Covered Car: Strategy Matters",
    excerpt: "Don't pour hot water on a windshield. The temperature shock cracks glass — and an already-stressed older windshield will go from chip to full crack in seconds.",
    category: "Winter",
    date: "May 19, 2026",
    content: [
      "Don't pour hot water on a windshield. The temperature shock cracks glass — and an already-stressed older windshield will go from chip to full crack in seconds.",
      "Run the defroster on max for 5 minutes with the engine running before scraping. The cabin warms the inside surface of the glass, the ice softens its grip, and scraping becomes 5x easier. Use a real scraper — credit cards bend and snap.",
      "If the car won't start because the battery is cold-weak and you've been idling to defrost too long, that's our $149 / hour roadside rate, 1-hour minimum, $124 online. Jump plus load test on the spot.",
    ],
  },
  {
    slug: "tip-008-winter-salt-damage-brakes",
    title: "Tip #8: Road Salt Eats Brake Lines",
    excerpt: "NYC and the surrounding region salt heavily. By late February, the underside of any vehicle that's been driven on highways is coated in brine. The corrosion att…",
    category: "Winter",
    date: "May 19, 2026",
    content: [
      "NYC and the surrounding region salt heavily. By late February, the underside of any vehicle that's been driven on highways is coated in brine. The corrosion attacks brake lines, fuel lines, and rear suspension components.",
      "Spray the underside with a high-pressure hose at a coin wash twice a winter — at minimum after every storm cycle. Pay attention to wheel wells and behind the bumper covers where salt accumulates.",
      "If a brake line bursts (telltale: pedal sinks to the floor, fluid puddle under the rear wheel), stop driving and call for a flatbed tow. We tow to your shop at $149 / hour, same hourly rate as every other service.",
    ],
  },
  {
    slug: "tip-009-winter-wipers-washer-fluid",
    title: "Tip #9: Winter Wiper Blades and Fluid Matter",
    excerpt: "Standard wiper blades freeze, the rubber gets brittle, and they smear instead of clear after one storm. Winter blades (Rain-X Latitude, Bosch ICON in winter com…",
    category: "Winter",
    date: "May 19, 2026",
    content: [
      "Standard wiper blades freeze, the rubber gets brittle, and they smear instead of clear after one storm. Winter blades (Rain-X Latitude, Bosch ICON in winter compound) shed ice and don't freeze stuck to the glass.",
      "Use winter-rated washer fluid (-20°F or colder). Summer washer fluid freezes in the reservoir, the lines, and the nozzles. A burst washer pump from frozen fluid is a $200+ repair.",
      "When the windshield is iced and visibility is zero, don't drive. Defrost first. If the car won't start, that's a separate roadside call — same $149 / hour rate, $124 first hour online.",
    ],
  },
  {
    slug: "tip-010-winter-coolant-concentration",
    title: "Tip #10: Check Coolant Concentration Before December",
    excerpt: "A 50/50 coolant mix protects to about -34°F, which covers NYC easily. But coolant degrades, and a topped-up cooling system that's been bled with plain water can…",
    category: "Winter",
    date: "May 19, 2026",
    content: [
      "A 50/50 coolant mix protects to about -34°F, which covers NYC easily. But coolant degrades, and a topped-up cooling system that's been bled with plain water can drop the freeze point to dangerous levels by year three.",
      "A cheap antifreeze tester (under $5 at any auto parts store) tells you the actual concentration in 30 seconds. If you're at 60/40 or better, you're fine. If you're at 30/70 (water-heavy), drain a quart and replace with concentrate.",
      "Frozen coolant cracks engine blocks. If you've been driving with low or weak coolant and the engine starts running hot, stop and call. We tow flatbed to your shop at our $149 / hour rate — same as every service.",
    ],
  },
  {
    slug: "tip-011-jump-start-procedure-step-by-step",
    title: "Tip #11: Jump-Start a Car the Right Way",
    excerpt: "Position the working car nose-to-nose with the dead one, engines off. Red clamp on dead positive (+), other red on live positive. Black on live negative, last b…",
    category: "Roadside",
    date: "May 19, 2026",
    content: [
      "Position the working car nose-to-nose with the dead one, engines off. Red clamp on dead positive (+), other red on live positive. Black on live negative, last black clamp on a clean unpainted metal point on the dead car's engine block — not the dead battery's negative terminal. The order matters.",
      "Start the working car, let it run 2–3 minutes. Then start the dead car. If it cranks slowly or not at all after 5–10 seconds, stop — you have a deeper problem than a low charge. Don't keep grinding the starter; you'll burn it out.",
      "Disconnect in reverse order: dead-side black first, then live-side black, live-side red, dead-side red. If you're unsure or the car still won't start, call us — same $149 / hour rate as every roadside service, $124 first hour when you book online.",
    ],
  },
  {
    slug: "tip-012-dont-jump-swollen-battery",
    title: "Tip #12: Never Jump a Swollen or Leaking Battery",
    excerpt: "A swollen battery case (bulging sides, distortion, visible deformation) means internal pressure has built up from a thermal runaway event or extreme overcharge.…",
    category: "Roadside",
    date: "May 19, 2026",
    content: [
      "A swollen battery case (bulging sides, distortion, visible deformation) means internal pressure has built up from a thermal runaway event or extreme overcharge. Jumping it can rupture the case and spray sulfuric acid.",
      "Same for any battery with visible electrolyte leak, white powdery corrosion crusting the terminals, or a strong rotten-egg sulfur smell. Replace, don't jump.",
      "We replace on the curb at $149 / hour service rate plus battery at retail. Old battery goes with us for proper recycling. Most calls finish inside the 1-hour minimum.",
    ],
  },
  {
    slug: "tip-013-dont-drive-on-flat-tire",
    title: "Tip #13: Why Driving on a Flat Costs You 10x More",
    excerpt: "A flat tire driven for even a few hundred feet at low speed will come apart and damage the wheel itself. A $200 tire turns into a $200 tire plus a $400 wheel pl…",
    category: "Roadside",
    date: "May 19, 2026",
    content: [
      "A flat tire driven for even a few hundred feet at low speed will come apart and damage the wheel itself. A $200 tire turns into a $200 tire plus a $400 wheel plus possible suspension damage from running the rim on pavement.",
      "If you must move the car a few feet to safety, drive slow and straight, no more than the length of one parking spot. Then stop and either change the tire or call for service.",
      "Tire change is $149 / hour, 1-hour minimum (most finish in 25 minutes). Book online for $124 first hour. If you have no spare or the damage is sidewall/rim, we flatbed to a tire shop at the same hourly rate.",
    ],
  },
  {
    slug: "tip-014-find-your-spare-and-jack",
    title: "Tip #14: Know Where Your Spare and Jack Are Before You Need Them",
    excerpt: "Many new cars no longer carry a spare — they ship with a mobile-inflator kit instead, or with run-flats. Check now, in your driveway, with the manual handy. Kno…",
    category: "Roadside",
    date: "May 19, 2026",
    content: [
      "Many new cars no longer carry a spare — they ship with a mobile-inflator kit instead, or with run-flats. Check now, in your driveway, with the manual handy. Knowing what you have before a 2 AM curbside emergency saves an hour.",
      "If you have a spare, locate the jack and tire iron. Common spots: under the trunk floor (most sedans), behind a panel in the rear cargo area (SUVs), or mounted under the rear bumper (most pickups and a few SUVs).",
      "If your car has the inflator kit, it works for small punctures. For sidewall damage or anything bigger than a finger's width, the kit won't seal it — call us at $149 / hour, 1-hour minimum, $124 first hour online.",
    ],
  },
  {
    slug: "tip-015-lockout-never-break-window",
    title: "Tip #15: Lockout: Never Break the Window Yourself",
    excerpt: "A side window replacement runs $200–$800 depending on vehicle and glass type, and the replacement takes a day (the shop has to order the right glass). A profess…",
    category: "Roadside",
    date: "May 19, 2026",
    content: [
      "A side window replacement runs $200–$800 depending on vehicle and glass type, and the replacement takes a day (the shop has to order the right glass). A professional lockout is faster and cheaper — air wedges and long-reach tools, no damage.",
      "Don't use a wire coat hanger. Modern airbag-equipped cars route the side-curtain airbag wiring along the door interior. A coat hanger that catches that wiring can trigger the airbag, which is a $1,500–$3,000 repair.",
      "Standard $149 / hour service rate, 1-hour minimum (most lockouts finish in under 10 minutes), $124 first hour when you book online.",
    ],
  },
  {
    slug: "tip-016-gas-delivery-vs-walking",
    title: "Tip #16: Gas Delivery vs. Walking to a Station",
    excerpt: "If you're on a highway or in a tunnel, do not walk. Pedestrians on active travel lanes get hit. Call for gas delivery. We bring up to 5 gallons in approved cont…",
    category: "Roadside",
    date: "May 19, 2026",
    content: [
      "If you're on a highway or in a tunnel, do not walk. Pedestrians on active travel lanes get hit. Call for gas delivery. We bring up to 5 gallons in approved containers and pour them into your tank in under 10 minutes.",
      "If you're parked on a residential street and the nearest gas station is a few blocks away, walking is reasonable if you have an approved jerry can and a way to carry it. Don't use a plastic milk jug — illegal and dangerous.",
      "Gas delivery runs our $149 / hour rate, 1-hour minimum, $124 first hour online. Plus fuel at cost plus a small handling fee. Up to 5 gallons standard.",
    ],
  },
  {
    slug: "tip-017-run-flat-tires-not-invincible",
    title: "Tip #17: Run-Flat Tires Aren't Invincible",
    excerpt: "Run-flats are designed to give you 50 miles at 50 mph after total air loss — enough to reach a tire shop. They are not a permanent fix and they cannot be patche…",
    category: "Roadside",
    date: "May 19, 2026",
    content: [
      "Run-flats are designed to give you 50 miles at 50 mph after total air loss — enough to reach a tire shop. They are not a permanent fix and they cannot be patched. Once you've driven on one flat, it needs replacement, not repair.",
      "Driving past the run-flat distance limit destroys the tire's sidewall structure and damages the wheel. Many BMW and Mercedes owners learn this the expensive way.",
      "Most run-flat-equipped cars do not carry a spare. If you're past the 50-mile/50-mph limit, call us for a flatbed to a tire shop. Same $149 / hour rate as every service, $124 first hour online.",
    ],
  },
  {
    slug: "tip-018-battery-age-proactive-replace",
    title: "Tip #18: Replace Your Battery at Year 4, Not Year 6",
    excerpt: "Battery life in NYC averages 3–5 years. By year 4 most batteries are losing capacity even if they still start the car. By year 5–6 you're rolling the dice every…",
    category: "Roadside",
    date: "May 19, 2026",
    content: [
      "Battery life in NYC averages 3–5 years. By year 4 most batteries are losing capacity even if they still start the car. By year 5–6 you're rolling the dice every cold morning.",
      "A load test (which any auto parts store does free) tells you exactly how much capacity is left. If you're below 75% rated CCA, replace before winter.",
      "We do on-curb battery replacement at $149 / hour service rate plus the battery at retail. Most common group sizes in stock on every truck.",
    ],
  },
  {
    slug: "tip-019-alternator-vs-battery-diagnosis",
    title: "Tip #19: Alternator vs. Battery — How to Tell",
    excerpt: "Battery problem: car won't start with a click-click-click, lights are dim or out, jump works and car drives normally afterward.",
    category: "Roadside",
    date: "May 19, 2026",
    content: [
      "Battery problem: car won't start with a click-click-click, lights are dim or out, jump works and car drives normally afterward.",
      "Alternator problem: car ran fine, then started losing electrical (dim lights, dying radio, dash gauges going wonky), then died. A jump might start it but it dies again within a few miles because the alternator isn't recharging.",
      "Our roadside driver brings a real alternator load tester. If your alternator is bad, we tell you and tow flatbed to a shop instead of leaving you with a jump that will fail in 10 miles. Same $149 / hour rate.",
    ],
  },
  {
    slug: "tip-020-parasitic-draw-overnight-dead",
    title: "Tip #20: Battery Dies Overnight? Parasitic Draw",
    excerpt: "If your car is fine all day but dead in the morning, something is drawing current with the key off. Common culprits: a glove box light stuck on, a dome light no…",
    category: "Roadside",
    date: "May 19, 2026",
    content: [
      "If your car is fine all day but dead in the morning, something is drawing current with the key off. Common culprits: a glove box light stuck on, a dome light not switching off, an aftermarket alarm or stereo wired wrong, a phone charger left in a 12V port.",
      "Quick test: pull the battery negative cable for a night. If the battery is full the next morning, you have a parasitic draw. If it's still flat, the battery itself is shot.",
      "We diagnose parasitic draws on scene at our $149 / hour rate — multimeter on the negative cable to isolate the circuit pulling current. Most diagnostics finish inside the 1-hour minimum.",
    ],
  },
  {
    slug: "tip-021-key-fob-battery-replacement",
    title: "Tip #21: Key Fob Battery — 2-Minute Fix You Can Do Yourself",
    excerpt: "If your remote won't lock/unlock from a distance but still works when held against the door handle, it's a low fob battery. Most fobs use a CR2032 coin cell — u…",
    category: "Roadside",
    date: "May 19, 2026",
    content: [
      "If your remote won't lock/unlock from a distance but still works when held against the door handle, it's a low fob battery. Most fobs use a CR2032 coin cell — under $3 at any drugstore.",
      "Pry the fob open at the seam with a small flat screwdriver, swap the coin cell (note polarity), snap it back together. Most modern fobs do not require re-programming after a battery change.",
      "If the fob is dead and you're locked out completely, call us. Lockout service is our standard $149 / hour rate, 1-hour minimum, $124 first hour online.",
    ],
  },
  {
    slug: "tip-022-tpms-light-vs-actual-flat",
    title: "Tip #22: TPMS Light Isn't Always a Flat",
    excerpt: "TPMS (tire pressure monitoring) triggers at about 25% below the recommended cold pressure. A cold-weather pressure drop, a slow leak, or a tire that's actually…",
    category: "Roadside",
    date: "May 19, 2026",
    content: [
      "TPMS (tire pressure monitoring) triggers at about 25% below the recommended cold pressure. A cold-weather pressure drop, a slow leak, or a tire that's actually flat all light the same indicator.",
      "First, look at the tires before driving. A visibly flat tire is a flat tire — don't drive on it. If all four look normal, check pressures cold. Top up to spec at the next gas station with a working air pump.",
      "If you have a flat or a slow-leak puncture, we run tire service at $149 / hour, 1-hour min. Plug-and-patch is included when the damage is in the tread. Sidewall damage = flatbed to a shop.",
    ],
  },
  {
    slug: "tip-023-kids-in-the-car-during-breakdown",
    title: "Tip #23: Kids in the Car During a Breakdown",
    excerpt: "Keep them in the car with seatbelts on, unless the car is in an unsafe position (active travel lane, on a bridge deck). Being inside a buckled vehicle is far sa…",
    category: "Roadside",
    date: "May 19, 2026",
    content: [
      "Keep them in the car with seatbelts on, unless the car is in an unsafe position (active travel lane, on a bridge deck). Being inside a buckled vehicle is far safer than standing on a shoulder.",
      "Tell dispatch you have kids when you call. We prioritize and ETA accordingly. The driver will identify himself by name on arrival and won't ask you or the kids to exit until the vehicle is loaded.",
      "Standard $149 / hour rate, 1-hour minimum, $124 first hour online. Same trucks online or by phone.",
    ],
  },
  {
    slug: "tip-024-pet-inside-vehicle-during-tow",
    title: "Tip #24: Bringing a Pet on a Tow",
    excerpt: "Pets ride in the cab with you, not in the towed vehicle. The cab of a wheel-lift or flatbed has bench seats with seatbelts; bring a leash. Most carriers prefer…",
    category: "Roadside",
    date: "May 19, 2026",
    content: [
      "Pets ride in the cab with you, not in the towed vehicle. The cab of a wheel-lift or flatbed has bench seats with seatbelts; bring a leash. Most carriers prefer animals are secured for the cab ride.",
      "If you have a service animal or special-needs pet, tell dispatch ahead of time so the driver expects to coordinate. Aggressive dogs need a muzzle for safety.",
      "Same $149 / hour rate. The vehicle on the deck stays empty — animals never ride in the towed car.",
    ],
  },
  {
    slug: "tip-025-empty-fuel-warning-how-far",
    title: "Tip #25: Empty Fuel Warning — How Far Can You Really Go?",
    excerpt: "Most modern cars hit the warning at about 1/16th of a tank — typically 30–50 miles of remaining range. But that estimate depends on driving style; if you've bee…",
    category: "Roadside",
    date: "May 19, 2026",
    content: [
      "Most modern cars hit the warning at about 1/16th of a tank — typically 30–50 miles of remaining range. But that estimate depends on driving style; if you've been climbing hills or running A/C hard, it's less.",
      "Don't run the tank below E. Repeatedly running dry can damage the fuel pump (which is cooled by the gasoline surrounding it). A new fuel pump runs $400–$900 installed.",
      "If you actually run out, we deliver gas at $149 / hour service rate plus fuel at cost. Most deliveries finish inside the 1-hour minimum. Book online for $124 first hour.",
    ],
  },
  {
    slug: "tip-026-awd-4wd-always-flatbed",
    title: "Tip #26: AWD and 4WD: Always Flatbed",
    excerpt: "All-wheel-drive and four-wheel-drive vehicles have center differentials that require all four wheels to rotate at the same speed. Wheel-lift towing lifts two wh…",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "All-wheel-drive and four-wheel-drive vehicles have center differentials that require all four wheels to rotate at the same speed. Wheel-lift towing lifts two wheels off the ground and drags the other two — the speed differential destroys the transfer case.",
      "Repairs run $3,000–$8,000 depending on vehicle. Some manufacturers (Audi, Subaru) explicitly void warranty coverage on transfer cases that show tow damage.",
      "If you're not sure whether your car is AWD, tell dispatch the year/make/model. We default to flatbed when in doubt. Same $149 / hour rate either way, $124 first hour online.",
    ],
  },
  {
    slug: "tip-027-ev-motor-lockup-risk",
    title: "Tip #27: EVs Cannot Be Dragged — Motor Lock-Up Risk",
    excerpt: "Electric drivetrains often can't freewheel without power, especially on Teslas (in-wheel motors), Rivians (lock when battery is depleted), and most newer EVs. D…",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "Electric drivetrains often can't freewheel without power, especially on Teslas (in-wheel motors), Rivians (lock when battery is depleted), and most newer EVs. Dragging a non-freewheel EV destroys the motor.",
      "Tesla specifically has a 'tow mode' that has to be enabled from the touchscreen before loading. A trained operator knows how to do this; a generic tow driver may not.",
      "All EV transport is flatbed at our $149 / hour rate. Authorized service center drop is the standard destination — Tesla Service, Rivian Service, Lucid Service. Manufacturer roadside coverage reimburses most tows.",
    ],
  },
  {
    slug: "tip-028-low-clearance-sports-car",
    title: "Tip #28: Low-Clearance Sports Cars Need Corner Protection",
    excerpt: "Cars like the Corvette Z06, 911 GT3, AMG GTR, Huracan, and most other low-clearance performance vehicles scrape on standard flatbed ramps. The front bumper and…",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "Cars like the Corvette Z06, 911 GT3, AMG GTR, Huracan, and most other low-clearance performance vehicles scrape on standard flatbed ramps. The front bumper and underbody aero hit the ramp transition.",
      "Proper procedure: low-angle ramps, optional ramp extensions, corner protection (rubber pads or wood blocks at the contact points). If your operator doesn't bring this gear, find one who does.",
      "We have the right equipment for low-clearance and exotic vehicles. Same $149 / hour rate, $124 first hour online. For six-figure cars, elevated cargo insurance is available — see /services/luxury-exotic-towing.",
    ],
  },
  {
    slug: "tip-029-motorcycle-strap-points",
    title: "Tip #29: Motorcycle Tow: Strap Points Matter",
    excerpt: "Soft straps go around the handlebar pinch bolts or the lower triple clamp — never around brake reservoirs, fairings, or fragile trim. Improper strap points crac…",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "Soft straps go around the handlebar pinch bolts or the lower triple clamp — never around brake reservoirs, fairings, or fragile trim. Improper strap points crack plastic and bend metal.",
      "The bike sits on its wheels (not on its side) with a front-wheel chock locking it in place. Soft straps pull it down into the chock so it can't shift. Two straps front, optional rear stabilizer.",
      "Motorcycle transport runs the same $149 / hour rate as every other service. Book online for $124 first hour. Scooters are the same rate. Heavy touring bikes may need a heavy-duty flatbed.",
    ],
  },
  {
    slug: "tip-030-awd-that-looks-like-fwd",
    title: "Tip #30: Some AWDs Don't Look Like AWDs (CR-V, RAV4)",
    excerpt: "Many crossovers ship in both FWD and AWD trims that look identical from the outside. Honda CR-V, Toyota RAV4, Mazda CX-5, Subaru Forester (always AWD), Nissan R…",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "Many crossovers ship in both FWD and AWD trims that look identical from the outside. Honda CR-V, Toyota RAV4, Mazda CX-5, Subaru Forester (always AWD), Nissan Rogue — same body, different drivetrain.",
      "If you call for a tow and describe your CR-V as 'just a car,' you may get a wheel-lift truck dispatched. If yours is the AWD version, that's a transfer case disaster waiting.",
      "Look at the door jamb sticker or the VIN decode. When in doubt, tell dispatch 'I'm not sure' — we default to flatbed and confirm on scene. Same $149 / hour rate either way.",
    ],
  },
  {
    slug: "tip-031-convertible-top-latched-before-tow",
    title: "Tip #31: Latch the Convertible Top Before a Tow",
    excerpt: "Convertible tops left unlatched flap during transport, even on a flatbed strapped down. The wind on I-95 will rip a soft top off its bows.",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "Convertible tops left unlatched flap during transport, even on a flatbed strapped down. The wind on I-95 will rip a soft top off its bows.",
      "If the top mechanism is broken and won't latch, tape it down with painter's tape (won't damage paint) along the seal lines. Tell dispatch — we can also wrap with shrink to keep it pinned.",
      "Same $149 / hour rate for any tow. Book online for $124 first hour.",
    ],
  },
  {
    slug: "tip-032-close-trunk-before-driver-leaves",
    title: "Tip #32: Close the Trunk and Doors Before You Hand Over the Keys",
    excerpt: "Open trunks lock up against tow chains and cables; open doors swing during loading and can damage hinges. Walk around the vehicle with the driver before loading…",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "Open trunks lock up against tow chains and cables; open doors swing during loading and can damage hinges. Walk around the vehicle with the driver before loading — confirm all closures.",
      "If a door or trunk lid is damaged and won't close fully, tell dispatch in advance. We can use ratchet straps to secure the lid for transport.",
      "Standard $149 / hour rate. Driver does a photo walkaround before loading — protects both sides.",
    ],
  },
  {
    slug: "tip-033-lock-visible-items-in-trunk",
    title: "Tip #33: Lock Personal Items in the Trunk Before You Leave",
    excerpt: "If you're leaving the vehicle at a tow company yard or at a body shop, lock anything you don't want to lose in the trunk. Visible items on seats and dashes attr…",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "If you're leaving the vehicle at a tow company yard or at a body shop, lock anything you don't want to lose in the trunk. Visible items on seats and dashes attract break-ins regardless of where the car is stored.",
      "Glove box: don't leave registration, insurance cards, garage door remotes, or anything with your home address.",
      "We don't go into your trunk or glove box — but you can't control everyone who handles the vehicle next. Better to remove temptation.",
    ],
  },
  {
    slug: "tip-034-tow-to-home-vs-shop-vs-dealer",
    title: "Tip #34: Tow to Home vs. Shop vs. Dealer",
    excerpt: "Home: best when the vehicle needs to sit while you figure out a plan, or when the repair will be DIY. Make sure you have legal parking.",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "Home: best when the vehicle needs to sit while you figure out a plan, or when the repair will be DIY. Make sure you have legal parking.",
      "Shop: best when you already know what's wrong and have a trusted mechanic. Most shops accept after-hours drops — confirm with the shop first.",
      "Dealer: required for warranty work, factory recalls, EV battery service, and anything that needs proprietary diagnostic tools. Same $149 / hour rate to any destination, hours quoted based on route.",
    ],
  },
  {
    slug: "tip-035-same-day-vs-overnight-storage",
    title: "Tip #35: Same-Day Drop Avoids Storage Fees",
    excerpt: "Storage fees apply when a vehicle sits in a tow operator's yard overnight or longer. Same-day pickup-to-drop with no yard stop = zero storage fee. Our default f…",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "Storage fees apply when a vehicle sits in a tow operator's yard overnight or longer. Same-day pickup-to-drop with no yard stop = zero storage fee. Our default flow is same-day.",
      "If a shop is closed when we arrive (common after-hours), we coordinate with you on the destination — your home, a 24-hour shop, or our yard with storage fee starting the next day.",
      "Storage fees are NEVER charged on same-day drops at our company. If a tow operator surprises you with one, dispute it and file a 311 complaint with DCWP.",
    ],
  },
  {
    slug: "tip-036-multi-vehicle-accident-scene",
    title: "Tip #36: Multi-Vehicle Accident: One Tow Per Vehicle",
    excerpt: "At a multi-vehicle accident, each driveable vehicle gets its own tow if it can't move under its own power. Don't try to combine — the insurance claim, the photo…",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "At a multi-vehicle accident, each driveable vehicle gets its own tow if it can't move under its own power. Don't try to combine — the insurance claim, the photos, and the destination are vehicle-specific.",
      "If NYPD calls rotation tow, you may have no choice in operator for the vehicle in the travel lane. But you can call us afterward to retrieve from the rotation operator's yard.",
      "Our accident recovery rate is the same $149 / hour rate, with hours quoted based on scene complexity. Most insurance carriers direct-bill us.",
    ],
  },
  {
    slug: "tip-037-documentation-timestamped-photos",
    title: "Tip #37: Demand Timestamped Photos at Load and Drop",
    excerpt: "Photos at load (4 sides of the vehicle, plus close-ups of existing damage) and at drop (same vehicle, intact and in the new location) protect both you and the o…",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "Photos at load (4 sides of the vehicle, plus close-ups of existing damage) and at drop (same vehicle, intact and in the new location) protect both you and the operator. Insurance disputes and damage claims become impossible without them.",
      "If a tow operator refuses or 'forgets' to take photos, that's a red flag. Find another operator.",
      "Every load and drop we run includes timestamped photos. Emailed with the receipt. Standard $149 / hour rate.",
    ],
  },
  {
    slug: "tip-038-itemized-receipt-required",
    title: "Tip #38: What Should Be on Your Itemized Receipt",
    excerpt: "Required line items: service description (tow type), pickup address, drop address, start time, end time, rate ($149/hr), hours billed (and any half-hour increme…",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "Required line items: service description (tow type), pickup address, drop address, start time, end time, rate ($149/hr), hours billed (and any half-hour increments), discount applied (if any), total. Plus operator name, license number, and DCWP credentials.",
      "Optional but useful: truck number, driver name, payment method, tip if any. Photos can be embedded or linked.",
      "If a receipt is missing any of the required items, request a corrected one. NYC DCWP requires itemization on every tow invoice.",
    ],
  },
  {
    slug: "tip-039-scope-change-on-scene",
    title: "Tip #39: When the Diagnosis Changes on Scene",
    excerpt: "Sometimes what sounds like a dead battery on the phone turns out to be a bad alternator on scene — meaning a jump won't hold, and you actually need a tow. Or a…",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "Sometimes what sounds like a dead battery on the phone turns out to be a bad alternator on scene — meaning a jump won't hold, and you actually need a tow. Or a 'flat tire' is actually a sidewall blowout that needs a flatbed.",
      "When scope changes, we stop, walk through the new diagnosis with you, and quote the revised estimated hours before we proceed. You decide whether to continue.",
      "Same $149 / hour rate regardless of what the work turns into. Book online for $124 first hour.",
    ],
  },
  {
    slug: "tip-040-garage-clearance-before-truck",
    title: "Tip #40: Verify Garage Clearance Before You Call",
    excerpt: "Most NYC residential garages cap at 6'6\" or 7'. A standard flatbed truck is too tall to enter. Our wheel-lift trucks clear most of those garages, but the dispat…",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "Most NYC residential garages cap at 6'6\" or 7'. A standard flatbed truck is too tall to enter. Our wheel-lift trucks clear most of those garages, but the dispatcher will confirm before sending.",
      "Know your building's posted height limit (usually on a sign at the entrance). If you don't know, walk down and check before calling. A truck that arrives and can't enter still bills the dispatch time.",
      "Same $149 / hour rate. If the dispatcher knows the height up front, we send the right truck and avoid the wasted trip.",
    ],
  },
  {
    slug: "tip-041-bqe-shoulder-breakdown",
    title: "Tip #41: BQE Shoulder Breakdown — Stay With Vehicle",
    excerpt: "The BQE between the Brooklyn Bridge and the Verrazzano has some of the narrowest shoulders in the city. Pulling onto one is uncomfortable but possible; getting…",
    category: "NYC",
    date: "May 19, 2026",
    content: [
      "The BQE between the Brooklyn Bridge and the Verrazzano has some of the narrowest shoulders in the city. Pulling onto one is uncomfortable but possible; getting out and walking around your vehicle is dangerous.",
      "Stay in the car with seatbelts on. Hazards on. If you have a passenger, exit on the non-traffic side. Tell dispatch where you are by exit number — that's faster than cross-streets.",
      "Standard $149 / hour rate. We stage trucks at multiple points along the BQE, typical arrival 15–30 minutes.",
    ],
  },
  {
    slug: "tip-042-cross-bronx-worst-spots",
    title: "Tip #42: Cross Bronx: The Worst Breakdown Spots",
    excerpt: "Between the Major Deegan and Throgs Neck Bridge, the Cross Bronx has no real shoulders and constant traffic. The roughest break-down spots are the Webster Ave t…",
    category: "NYC",
    date: "May 19, 2026",
    content: [
      "Between the Major Deegan and Throgs Neck Bridge, the Cross Bronx has no real shoulders and constant traffic. The roughest break-down spots are the Webster Ave to White Plains Rd stretch, and the approach to the Throgs Neck.",
      "If you break down here, call 911 first if you're in an active lane. NYPD coordinates lane closure for the tow truck to safely access.",
      "Our dispatcher knows the Cross Bronx — we route around the worst traffic by approaching from side streets. $149 / hour rate.",
    ],
  },
  {
    slug: "tip-043-tunnel-breakdown-call-911",
    title: "Tip #43: Tunnel Breakdown: 911 First, Always",
    excerpt: "Holland, Lincoln, Brooklyn-Battery (Hugh Carey), Queens-Midtown, and Lincoln tunnels all have no shoulders. A vehicle stopped in a tunnel is a critical life-saf…",
    category: "NYC",
    date: "May 19, 2026",
    content: [
      "Holland, Lincoln, Brooklyn-Battery (Hugh Carey), Queens-Midtown, and Lincoln tunnels all have no shoulders. A vehicle stopped in a tunnel is a critical life-safety hazard.",
      "Call 911 immediately. Port Authority (Holland, Lincoln) or NYPD (Queens-Midtown, BBT) responds first to manage the scene. Tow operators cannot legally enter a tunnel without coordination — the tunnel authority pre-arranges access.",
      "Once you're cleared from the tunnel (usually pushed to a turnaround), we handle the recovery at our standard $149 / hour rate.",
    ],
  },
  {
    slug: "tip-044-port-authority-crossings",
    title: "Tip #44: Port Authority Crossings: Different Rules",
    excerpt: "The Holland Tunnel, Lincoln Tunnel, GWB, Bayonne Bridge, Goethals Bridge, and Outerbridge Crossing are Port Authority of NY/NJ jurisdiction. Their rotation tow…",
    category: "NYC",
    date: "May 19, 2026",
    content: [
      "The Holland Tunnel, Lincoln Tunnel, GWB, Bayonne Bridge, Goethals Bridge, and Outerbridge Crossing are Port Authority of NY/NJ jurisdiction. Their rotation tow contract is separate from NYC's rotation.",
      "If you break down inside a PA crossing and they call rotation, you may end up with a NJ-side operator regardless of where you're going. You can still call us to retrieve your car from their yard afterward.",
      "Our $149 / hour rate applies to any pickup, including yard retrievals from rotation operators.",
    ],
  },
  {
    slug: "tip-045-bridge-deck-breakdown",
    title: "Tip #45: Bridge Deck Breakdown — Stay In Car",
    excerpt: "The major bridges (Verrazzano, Triborough, RFK, Whitestone, Throgs Neck, Henry Hudson, GWB) have either no shoulder or a very narrow one. Wind on bridge decks i…",
    category: "NYC",
    date: "May 19, 2026",
    content: [
      "The major bridges (Verrazzano, Triborough, RFK, Whitestone, Throgs Neck, Henry Hudson, GWB) have either no shoulder or a very narrow one. Wind on bridge decks is dangerous, especially in winter.",
      "Stay inside with seatbelts on. Hazards on. Bridge authority will dispatch their own response — let them coordinate the tow access.",
      "We handle bridge calls in coordination with the bridge authority. Standard $149 / hour rate.",
    ],
  },
  {
    slug: "tip-046-alt-side-plus-breakdown-double-penalty",
    title: "Tip #46: Alt-Side Day + Breakdown = Double Penalty",
    excerpt: "If your car breaks down at the curb on an alt-side day and you can't move it before the sweeper window, you get a $65 ticket on top of the tow fee. The ticket i…",
    category: "NYC",
    date: "May 19, 2026",
    content: [
      "If your car breaks down at the curb on an alt-side day and you can't move it before the sweeper window, you get a $65 ticket on top of the tow fee. The ticket isn't waivable just because the car was dead.",
      "Tell dispatch the alt-side window — we prioritize curb pickups to avoid the ticket where possible.",
      "Same $149 / hour rate. The $65 ticket goes to NYC DOF, not to us.",
    ],
  },
  {
    slug: "tip-047-garage-clearance-restrictions",
    title: "Tip #47: Garage Clearance Restrictions in Manhattan",
    excerpt: "Manhattan condo and co-op garages overwhelmingly cap at 6'6\" or 7'. A standard flatbed is 9–10 feet tall and physically cannot enter. Our wheel-lift trucks (8 f…",
    category: "NYC",
    date: "May 19, 2026",
    content: [
      "Manhattan condo and co-op garages overwhelmingly cap at 6'6\" or 7'. A standard flatbed is 9–10 feet tall and physically cannot enter. Our wheel-lift trucks (8 feet tall) clear most.",
      "Before calling, look for the height sign at the entrance. If your car is AWD and your garage is sub-flatbed-height, the truck stages outside, the driver retrieves manually, and we flatbed from the street.",
      "Same $149 / hour rate. Dispatch will tell you the truck type before sending.",
    ],
  },
  {
    slug: "tip-048-one-way-streets-u-turn-restrictions",
    title: "Tip #48: One-Way Streets and Tow Staging",
    excerpt: "Many NYC blocks are one-way with no place to U-turn. Our driver may need to stage on a cross-street and walk to your vehicle to assess. Tell dispatch the block…",
    category: "NYC",
    date: "May 19, 2026",
    content: [
      "Many NYC blocks are one-way with no place to U-turn. Our driver may need to stage on a cross-street and walk to your vehicle to assess. Tell dispatch the block direction so we approach the right way.",
      "Most NYC parking enforcement allows tow trucks to double-park briefly during a hookup. We don't get to use a hydrant or a bus stop, though — please don't direct us to one.",
      "Standard $149 / hour rate, same for every borough.",
    ],
  },
  {
    slug: "tip-049-manhattan-loading-zone-staging",
    title: "Tip #49: Manhattan Loading Zones: Truck Staging",
    excerpt: "Commercial vehicle loading zones in Midtown and Lower Manhattan are limited to specific hours and operators. Tow trucks generally have brief stop privileges dur…",
    category: "NYC",
    date: "May 19, 2026",
    content: [
      "Commercial vehicle loading zones in Midtown and Lower Manhattan are limited to specific hours and operators. Tow trucks generally have brief stop privileges during active loading, but we can't camp in them.",
      "Dispatch may stage the truck on a side street while the driver assesses on foot. This is faster than circling for parking.",
      "Same $149 / hour rate. Time spent staging is part of dispatch — clock starts when work begins.",
    ],
  },
  {
    slug: "tip-050-311-vs-911-which-to-call",
    title: "Tip #50: 311 vs. 911 — Which Number for a Breakdown",
    excerpt: "911: active emergency — vehicle in a travel lane, on a bridge deck, in a tunnel, blocking a fire lane, injury or accident scene, or active medical emergency. Po…",
    category: "NYC",
    date: "May 19, 2026",
    content: [
      "911: active emergency — vehicle in a travel lane, on a bridge deck, in a tunnel, blocking a fire lane, injury or accident scene, or active medical emergency. Police and EMS handle.",
      "311: non-emergency — illegal parking, dead vehicle on a residential street, abandoned vehicle, noise, complaint about a tow operator, file DCWP violation. Routing only — no on-scene response.",
      "If you're not sure, call 911. They route you down to 311 if it's not an emergency. Then call us at the standard $149 / hour rate for the actual recovery.",
    ],
  },
  {
    slug: "tip-051-dcwp-tow-license-verification",
    title: "Tip #51: Verify a Tow Operator's DCWP License",
    excerpt: "Every legitimate NYC tow operator has a NYC DCWP (Department of Consumer and Worker Protection) license. Number should appear on the truck door, the invoice, an…",
    category: "NYC",
    date: "May 19, 2026",
    content: [
      "Every legitimate NYC tow operator has a NYC DCWP (Department of Consumer and Worker Protection) license. Number should appear on the truck door, the invoice, and the website.",
      "Look up the operator at nyc.gov/dcwp. An expired or missing license is a major red flag — illegal operators have no insurance, no rate caps, and no oversight.",
      "We're DCWP licensed. License number on every invoice, truck, and receipt.",
    ],
  },
  {
    slug: "tip-052-private-property-vs-nypd-tow",
    title: "Tip #52: Private-Property Tow vs. NYPD Tow",
    excerpt: "Private-property tow: triggered by a private lot operator or property manager when you parked without authorization. Goes to a private yard. NYC caps redemption…",
    category: "NYC",
    date: "May 19, 2026",
    content: [
      "Private-property tow: triggered by a private lot operator or property manager when you parked without authorization. Goes to a private yard. NYC caps redemption at $125 for the hookup + $25/day storage after day one.",
      "NYPD tow: triggered by NYPD for violations (no parking, scofflaw, fire lane, etc.). Goes to a borough pound. Standard fees plus any outstanding violation balances.",
      "If you were towed and don't know which, check the signage at the lot you parked in. If it lists a private operator, that's where your car is. If no signage, NYPD.",
    ],
  },
  {
    slug: "tip-053-nyc-fuel-surcharge-doesnt-exist",
    title: "Tip #53: NYC 'Fuel Surcharge' Doesn't Exist",
    excerpt: "Some predatory operators add a 'fuel surcharge' line item to invoices. There is no NYC-mandated fuel surcharge for tow operators. It's pure padding.",
    category: "NYC",
    date: "May 19, 2026",
    content: [
      "Some predatory operators add a 'fuel surcharge' line item to invoices. There is no NYC-mandated fuel surcharge for tow operators. It's pure padding.",
      "If you see one on a tow invoice, dispute it. File a 311 complaint with DCWP. Most operators back down when challenged.",
      "Our invoice has no surcharge of any kind. One rate: $149 / hour, $124 first hour online.",
    ],
  },
  {
    slug: "tip-054-after-hours-markup-doesnt-exist",
    title: "Tip #54: There Is No After-Hours Markup in NYC Towing",
    excerpt: "Overnight, weekend, and holiday tow rates are the same as daytime rates in NYC. Any operator quoting an 'after-hours surcharge' is padding. The DCWP rate caps f…",
    category: "NYC",
    date: "May 19, 2026",
    content: [
      "Overnight, weekend, and holiday tow rates are the same as daytime rates in NYC. Any operator quoting an 'after-hours surcharge' is padding. The DCWP rate caps for private-property tows don't change by time of day.",
      "We charge the same $149 / hour rate at 3 AM Sunday as 3 PM Wednesday. Book online for $124 first hour either way.",
      "If you've been hit with an after-hours surcharge, dispute it and file a 311 complaint.",
    ],
  },
  {
    slug: "tip-055-storage-fees-same-day-illegal",
    title: "Tip #55: Same-Day Storage Fees Are Illegal",
    excerpt: "Storage fees only apply when a vehicle sits in a tow yard overnight or longer. A same-day pickup-to-drop with no yard stop should never have a storage fee. NYC…",
    category: "NYC",
    date: "May 19, 2026",
    content: [
      "Storage fees only apply when a vehicle sits in a tow yard overnight or longer. A same-day pickup-to-drop with no yard stop should never have a storage fee. NYC DCWP rules cap storage at $25/day, starting day 2.",
      "If you see a storage fee on a same-day drop invoice, dispute it. It's a 311 complaint to DCWP.",
      "We never charge storage on same-day drops. Standard $149 / hour rate, no add-ons.",
    ],
  },
  {
    slug: "tip-056-nypd-tow-pound-process",
    title: "Tip #56: NYPD Tow Pound: The Full Process",
    excerpt: "Confirm your car was towed (not stolen) via 311 or the NYC Finest Parking app. Note the pound location — Pier 76 (Manhattan), Brooklyn Navy Yard, College Point…",
    category: "Legal",
    date: "May 19, 2026",
    content: [
      "Confirm your car was towed (not stolen) via 311 or the NYC Finest Parking app. Note the pound location — Pier 76 (Manhattan), Brooklyn Navy Yard, College Point (Queens), Zerega (Bronx), Western Ave (Staten Island).",
      "Bring: valid ID, registration (paper original), proof of insurance, payment for tow fee + storage + any outstanding violations. Missing any = sent home to come back.",
      "Total time: 2–4 hours. We run an impound recovery service if you can't lose half a day. Standard $149 / hour rate plus pound fees passed through with no markup.",
    ],
  },
  {
    slug: "tip-057-pier-76-brooklyn-navy-yard-pounds",
    title: "Tip #57: Borough Tow Pound Locations and Hours",
    excerpt: "Pier 76 — W 36th St & 12th Ave, Manhattan. Mon-Sun, 7am-11pm. Brooklyn Navy Yard — 63 Flushing Ave. Mon-Sun, 7am-11pm.",
    category: "Legal",
    date: "May 19, 2026",
    content: [
      "Pier 76 — W 36th St & 12th Ave, Manhattan. Mon-Sun, 7am-11pm. Brooklyn Navy Yard — 63 Flushing Ave. Mon-Sun, 7am-11pm.",
      "College Point — 31-04 College Point Blvd, Queens. Mon-Sun. Zerega — 745 Zerega Ave, Bronx. Mon-Sun. Western Ave — 21 Western Ave, Staten Island. Mon-Sun.",
      "All hours subject to change — verify at nyc.gov/sheriff before going. We run impound recovery as a service at $149 / hour, $124 first hour online.",
    ],
  },
  {
    slug: "tip-058-documents-needed-at-pound",
    title: "Tip #58: Documents You MUST Bring to the Pound",
    excerpt: "Government-issued photo ID (driver's license, state ID). Vehicle registration (paper original, not a photo). Proof of current NY auto insurance (paper card or a…",
    category: "Legal",
    date: "May 19, 2026",
    content: [
      "Government-issued photo ID (driver's license, state ID). Vehicle registration (paper original, not a photo). Proof of current NY auto insurance (paper card or app screenshot acceptable at most pounds). Payment for fees + violations.",
      "If the vehicle isn't registered in your name, you'll need a notarized authorization from the registered owner. Out-of-state plates need the out-of-state registration.",
      "Missing any item and you're sent home. Make a checklist before you go. Or hire us to handle it — standard $149 / hour rate.",
    ],
  },
  {
    slug: "tip-059-outstanding-tickets-must-be-paid",
    title: "Tip #59: Outstanding Tickets Must Be Paid at the Pound",
    excerpt: "Some categories of NYC parking tickets (scofflaw, judgment, default convictions) require full payment before the vehicle is released. The total can run into tho…",
    category: "Legal",
    date: "May 19, 2026",
    content: [
      "Some categories of NYC parking tickets (scofflaw, judgment, default convictions) require full payment before the vehicle is released. The total can run into thousands if you've accumulated a backlog.",
      "Check your NYC Open Parking and Camera Violations balance at nyc.gov/finance BEFORE going to the pound. Saves a trip if you'll need to come back with payment.",
      "Tickets are paid to NYC DOF, not to the tow operator. Our impound recovery service includes navigating the payment desk for you.",
    ],
  },
  {
    slug: "tip-060-carrier-direct-billing-accident-tow",
    title: "Tip #60: Insurance Direct-Bill on Accident Tows",
    excerpt: "For accident and collision tows, your insurance usually covers the tow fee (under collision or comprehensive coverage). We bill the carrier directly in most cas…",
    category: "Legal",
    date: "May 19, 2026",
    content: [
      "For accident and collision tows, your insurance usually covers the tow fee (under collision or comprehensive coverage). We bill the carrier directly in most cases — you give us the carrier name and claim number, we handle the paperwork.",
      "If the claim is denied (no coverage, at-fault dispute), you pay the quoted rate and submit the itemized receipt for reimbursement consideration.",
      "Same $149 / hour rate either way. The vehicle gets to the body shop the same day in most cases.",
    ],
  },
  {
    slug: "tip-061-nyc-pip-coverage-explained",
    title: "Tip #61: New York No-Fault (PIP) Coverage Basics",
    excerpt: "NY is a no-fault state. PIP (Personal Injury Protection) on your auto policy pays medical expenses regardless of fault, up to $50,000. Most policies also includ…",
    category: "Legal",
    date: "May 19, 2026",
    content: [
      "NY is a no-fault state. PIP (Personal Injury Protection) on your auto policy pays medical expenses regardless of fault, up to $50,000. Most policies also include short-distance accident tow coverage regardless of fault.",
      "If you're in an accident with injuries, your own PIP coverage pays first — don't wait on the other driver's carrier for medical bills.",
      "Tow coverage varies by policy. Read your declarations page. We handle direct-bill for any carrier in NY.",
    ],
  },
  {
    slug: "tip-062-311-complaint-predatory-tow",
    title: "Tip #62: Filing a 311 Complaint Against a Tow Operator",
    excerpt: "If an operator overcharged, refused photos, padded mileage, charged an after-hours surcharge, or otherwise violated DCWP rules: document everything (photos of t…",
    category: "Legal",
    date: "May 19, 2026",
    content: [
      "If an operator overcharged, refused photos, padded mileage, charged an after-hours surcharge, or otherwise violated DCWP rules: document everything (photos of the invoice, the truck, the signage if a private-property tow), then file a 311 complaint and route to DCWP.",
      "DCWP investigates complaints and can fine operators or revoke licenses. Recovery of overcharges is possible but takes weeks to months.",
      "We're DCWP licensed and follow every rule. License number on every invoice.",
    ],
  },
  {
    slug: "tip-063-dcwp-rate-caps-private-property",
    title: "Tip #63: DCWP Rate Caps for Private-Property Tows",
    excerpt: "NYC DCWP caps private-property tow hookup fees at $125 and storage at $25 per day starting day 2. Total redemption for a same-day pickup at a private lot should…",
    category: "Legal",
    date: "May 19, 2026",
    content: [
      "NYC DCWP caps private-property tow hookup fees at $125 and storage at $25 per day starting day 2. Total redemption for a same-day pickup at a private lot should never exceed $125.",
      "If you're charged above the cap, document and dispute. File 311 / DCWP complaint. Pay under protest, get the itemized receipt, then go after recovery.",
      "These caps apply only to private-property tows (you parked in an unauthorized lot). Customer-requested tows (you called for service) are different — our $149 / hour rate is for customer-initiated work.",
    ],
  },
  {
    slug: "tip-064-signage-requirements-private-lots",
    title: "Tip #64: Signage Requirements at Private Lots",
    excerpt: "Private lots must post signs at every entrance: tow operator name, phone, license number, and the rate. Signs must be visible and legible at night.",
    category: "Legal",
    date: "May 19, 2026",
    content: [
      "Private lots must post signs at every entrance: tow operator name, phone, license number, and the rate. Signs must be visible and legible at night.",
      "If you were towed from a lot with missing, illegible, or non-compliant signage, the tow may be illegal. Photograph the lack of signage at the time of pickup if possible.",
      "Document everything. File a 311 / DCWP complaint. The fine and operator-level enforcement is real.",
    ],
  },
  {
    slug: "tip-065-claim-number-what-insurance-needs",
    title: "Tip #65: What Your Insurance Needs for a Tow Claim",
    excerpt: "Carrier name, policy number, claim number (issued when you opened the claim — call the carrier from the scene if you haven't yet), accident report number if NYP…",
    category: "Legal",
    date: "May 19, 2026",
    content: [
      "Carrier name, policy number, claim number (issued when you opened the claim — call the carrier from the scene if you haven't yet), accident report number if NYPD was on scene, the other party's information if at-fault.",
      "Photos of the scene, the damage, and the position of vehicles. Driver's name, the tow operator's name and license number.",
      "We email the carrier-formatted receipt within hours of completion. Standard $149 / hour rate.",
    ],
  },
  {
    slug: "tip-066-our-rate-249-explained",
    title: "Tip #66: Our Rate: $149 / Hour, No Catches",
    excerpt: "One rate for every service we run: $149 per hour, 1-hour minimum, billed in half-hour increments after that. Book online and save $25 — your first hour is $124…",
    category: "Pricing",
    date: "May 19, 2026",
    content: [
      "One rate for every service we run: $149 per hour, 1-hour minimum, billed in half-hour increments after that. Book online and save $25 — your first hour is $124 instead of $149.",
      "Same rate for towing, flatbed, roadside, lockout, jump, gas, winch-out, recovery, mobile mechanic. Same rate at 3 AM as 3 PM. Same rate every day of the year, including holidays.",
      "No NYC surcharge, no after-hours markup, no storage fees on same-day drops, no fuel surcharge. The number you hear or see is the number you pay.",
    ],
  },
  {
    slug: "tip-067-cash-only-is-red-flag",
    title: "Tip #67: Cash-Only Demands Are a Red Flag",
    excerpt: "Legitimate NYC tow operators accept all major cards, Apple Pay, Google Pay, and cash. An operator who demands cash-only — especially for a higher-than-quoted am…",
    category: "Pricing",
    date: "May 19, 2026",
    content: [
      "Legitimate NYC tow operators accept all major cards, Apple Pay, Google Pay, and cash. An operator who demands cash-only — especially for a higher-than-quoted amount — is almost always a scam.",
      "If you're cornered with a cash-only demand at the curb, photograph the truck, the driver, the invoice, and any signage. Pay under protest. File a 311 / DCWP complaint immediately.",
      "We accept every payment method. Receipt emailed instantly.",
    ],
  },
  {
    slug: "tip-068-itemized-receipt-mandatory",
    title: "Tip #68: Itemized Receipts Are Mandatory by Law",
    excerpt: "NYC DCWP requires an itemized invoice on every tow. Required: service type, pickup, drop, start time, end time, rate, hours, any line items, total. Plus operato…",
    category: "Pricing",
    date: "May 19, 2026",
    content: [
      "NYC DCWP requires an itemized invoice on every tow. Required: service type, pickup, drop, start time, end time, rate, hours, any line items, total. Plus operator name and DCWP license number.",
      "A handwritten invoice on a blank receipt with just a dollar amount = illegal. Demand a proper itemization. If refused, photograph everything and dispute via 311.",
      "Our receipts are auto-generated with every required item and emailed within minutes. Standard $149 / hour rate.",
    ],
  },
  {
    slug: "tip-069-hidden-surcharges-to-watch-for",
    title: "Tip #69: Hidden Surcharges to Watch For",
    excerpt: "Bait-and-switch surcharges to dispute: 'NYC surcharge' (doesn't exist), 'fuel surcharge' (doesn't exist), 'after-hours surcharge' (illegal), 'environmental fee'…",
    category: "Pricing",
    date: "May 19, 2026",
    content: [
      "Bait-and-switch surcharges to dispute: 'NYC surcharge' (doesn't exist), 'fuel surcharge' (doesn't exist), 'after-hours surcharge' (illegal), 'environmental fee' (vague pretext), 'gate fee' (often padded), 'admin fee' (padded).",
      "If any of these appear on an invoice, dispute on the spot. Get an itemized invoice without them or refuse to pay.",
      "Our invoice has none of these. Just hours × $149, with the online discount if applicable.",
    ],
  },
  {
    slug: "tip-070-padded-mileage",
    title: "Tip #70: Padded Mileage Is Theft",
    excerpt: "Some operators bill 'mileage' from where the truck supposedly came from (their yard, 20 miles away). This is illegal — mileage is supposed to be from your picku…",
    category: "Pricing",
    date: "May 19, 2026",
    content: [
      "Some operators bill 'mileage' from where the truck supposedly came from (their yard, 20 miles away). This is illegal — mileage is supposed to be from your pickup point to your drop point on the efficient route.",
      "Question any mileage figure above the efficient driving distance from pickup to drop. Google Maps the route to verify.",
      "Our $149 / hour rate has no mileage component. Distance just means more time on the clock — same rate per hour. Estimated total hours quoted before dispatch.",
    ],
  },
  {
    slug: "tip-071-rotation-tow-vs-operator-of-choice",
    title: "Tip #71: Rotation Tow vs. Operator of Choice",
    excerpt: "When NYPD responds to an accident or breakdown in an active travel lane, they may call 'rotation tow' — the next operator on a rotation list, regardless of your…",
    category: "Pricing",
    date: "May 19, 2026",
    content: [
      "When NYPD responds to an accident or breakdown in an active travel lane, they may call 'rotation tow' — the next operator on a rotation list, regardless of your preference. You don't get to pick.",
      "If your car is movable, you can refuse rotation and call your operator. If it's blocking the lane or unsafe, rotation handles it and you can retrieve from their yard afterward.",
      "We accept yard retrievals from rotation operators at our standard $149 / hour rate.",
    ],
  },
  {
    slug: "tip-072-fleet-account-vs-retail",
    title: "Tip #72: Fleet Account vs. Retail",
    excerpt: "If you run 5+ tows per month (commercial fleet, body shop, property manager, dealer), a fleet account beats retail pricing on volume. Net-30 billing, priority d…",
    category: "Pricing",
    date: "May 19, 2026",
    content: [
      "If you run 5+ tows per month (commercial fleet, body shop, property manager, dealer), a fleet account beats retail pricing on volume. Net-30 billing, priority dispatch, consistent drivers, COI on file.",
      "Retail rate: $149 / hour, 1-hour minimum, $124 first hour online. Fleet rates negotiated based on volume.",
      "Set up a fleet account at /commercial. No subscription, no monthly minimum.",
    ],
  },
  {
    slug: "tip-073-aaa-vs-local-operator",
    title: "Tip #73: AAA vs. Local Operator",
    excerpt: "AAA covers basic roadside — jump, tire, lockout, gas, short tows. Tow distance is capped (often 3–5 miles from breakdown). Past that, AAA charges retail on the…",
    category: "Pricing",
    date: "May 19, 2026",
    content: [
      "AAA covers basic roadside — jump, tire, lockout, gas, short tows. Tow distance is capped (often 3–5 miles from breakdown). Past that, AAA charges retail on the overage.",
      "AAA's national dispatch routes through a call center that has no idea where you are in NYC. ETA is often 60–120 minutes because they're calling around to local operators looking for one who'll take the job at AAA's reimbursement rate.",
      "Our direct service is 20–40 minutes in most cases. Standard $149 / hour rate, $124 first hour online. If you call AAA and wait an hour, then call us at hour-zero, we'll usually beat their truck.",
    ],
  },
  {
    slug: "tip-074-payment-method-comparison",
    title: "Tip #74: Card vs. Apple Pay vs. Cash",
    excerpt: "Credit card: standard, builds dispute-protection if anything goes wrong with the service. Most operators accept Visa/MC/Amex/Discover.",
    category: "Pricing",
    date: "May 19, 2026",
    content: [
      "Credit card: standard, builds dispute-protection if anything goes wrong with the service. Most operators accept Visa/MC/Amex/Discover.",
      "Apple Pay / Google Pay: same protection as the underlying card, plus contactless. Best for safety-conscious customers who don't want to hand over a physical card.",
      "Cash: fine if you have it. We accept all three. Receipt is identical regardless of payment method.",
    ],
  },
  {
    slug: "tip-075-insurance-reimbursement-workflow",
    title: "Tip #75: Insurance Reimbursement Workflow",
    excerpt: "For at-fault accidents or routine tows where you're paying up front: get the itemized receipt at completion, scan/photograph it, submit to your insurance with t…",
    category: "Pricing",
    date: "May 19, 2026",
    content: [
      "For at-fault accidents or routine tows where you're paying up front: get the itemized receipt at completion, scan/photograph it, submit to your insurance with the claim number.",
      "Most carriers process tow reimbursements in 2–4 weeks. Some require a separate claim form (Liberty Mutual, Allstate). Some pay direct to the operator if you set it up at intake (Geico, Progressive).",
      "Our receipts are formatted for any major NY carrier. Standard $149 / hour rate, $124 first hour online.",
    ],
  },
  {
    slug: "tip-076-tesla-tow-mode-procedure",
    title: "Tip #76: Tesla 'Tow Mode' Procedure",
    excerpt: "Teslas need to be in 'tow mode' before loading. From the touchscreen: Controls → Service → Towing → enable Transport Mode. The car must have at least some batte…",
    category: "EV",
    date: "May 19, 2026",
    content: [
      "Teslas need to be in 'tow mode' before loading. From the touchscreen: Controls → Service → Towing → enable Transport Mode. The car must have at least some battery for the screen to respond. If the battery is dead, the front trunk has a manual jump terminal.",
      "Transport Mode releases the parking brake and prevents the motor from re-engaging on the deck. Without it, the wheels lock and dragging causes drivetrain damage.",
      "We flatbed all EVs at $149 / hour rate. Drivers trained on Tesla, Rivian, Lucid, Polestar.",
    ],
  },
  {
    slug: "tip-077-rivian-neutral-release",
    title: "Tip #77: Rivian Neutral Release",
    excerpt: "Rivians have a manual neutral release on the brake-pedal side dash if the 12V battery is dead and the main pack is depleted. The procedure is in the owner's man…",
    category: "EV",
    date: "May 19, 2026",
    content: [
      "Rivians have a manual neutral release on the brake-pedal side dash if the 12V battery is dead and the main pack is depleted. The procedure is in the owner's manual; trained operators carry the reference.",
      "Without releasing properly, the drivetrain locks and dragging damages the in-wheel motors. Repair cost: drivetrain replacement.",
      "We flatbed every Rivian at our standard $149 / hour rate. Authorized service center drop is standard.",
    ],
  },
  {
    slug: "tip-078-lucid-towing-constraints",
    title: "Tip #78: Lucid Air Towing Constraints",
    excerpt: "Lucid Air requires flatbed with all four wheels off the ground. The drivetrain does not freewheel safely. Tesla-style 'tow mode' procedures don't apply to Lucid…",
    category: "EV",
    date: "May 19, 2026",
    content: [
      "Lucid Air requires flatbed with all four wheels off the ground. The drivetrain does not freewheel safely. Tesla-style 'tow mode' procedures don't apply to Lucid — different system.",
      "Battery service for the Lucid Air is dealer-only. We tow to Lucid Studio NJ or Lucid Service NYC depending on the issue.",
      "Standard $149 / hour rate, $124 first hour online.",
    ],
  },
  {
    slug: "tip-079-bmw-xdrive-flatbed-only",
    title: "Tip #79: BMW xDrive: Always Flatbed",
    excerpt: "Every BMW xDrive (all-wheel-drive) model requires flatbed. The transfer case can't handle wheel-lift. Models: most 3-series xDrive, 5-series xDrive, X1, X3, X5,…",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "Every BMW xDrive (all-wheel-drive) model requires flatbed. The transfer case can't handle wheel-lift. Models: most 3-series xDrive, 5-series xDrive, X1, X3, X5, X7, M-models with AWD.",
      "BMW warranty explicitly voids transfer case repairs that show tow damage. The transfer case alone runs $3,000–$5,000 plus labor.",
      "We flatbed every xDrive at $149 / hour. Book online for $124 first hour.",
    ],
  },
  {
    slug: "tip-080-porsche-911-corner-protection",
    title: "Tip #80: Porsche 911: Corner Protection on Load",
    excerpt: "Porsche 911 front bumpers, especially GT3 and Turbo trims, scrape on standard flatbed ramps. Load procedure: low-angle ramps, ramp extensions, corner blocks at…",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "Porsche 911 front bumpers, especially GT3 and Turbo trims, scrape on standard flatbed ramps. Load procedure: low-angle ramps, ramp extensions, corner blocks at the front contact points.",
      "GT3 RS and Turbo S have active aero that lowers further when stopped — even more clearance loss. Trained operators bring the right gear.",
      "We have the equipment for low-clearance exotics. Same $149 / hour rate, elevated cargo insurance available for six-figure vehicles.",
    ],
  },
  {
    slug: "tip-081-mercedes-amg-low-clearance",
    title: "Tip #81: Mercedes AMG: Low Clearance Procedure",
    excerpt: "AMG GT, AMG GTR, S65 Coupe, and SL63 are all low enough to scrape on standard ramps. Same procedure as low-clearance Porsches: low-angle ramps, corner protectio…",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "AMG GT, AMG GTR, S65 Coupe, and SL63 are all low enough to scrape on standard ramps. Same procedure as low-clearance Porsches: low-angle ramps, corner protection, slow load.",
      "AMG GT in particular has an active aero front splitter that drops 1.5 inches when the car is stopped. Lift it manually before loading or wait for the system to retract on key-off.",
      "Standard $149 / hour rate. Trained operators on AMG specifically.",
    ],
  },
  {
    slug: "tip-082-audi-quattro-center-diff",
    title: "Tip #82: Audi Quattro: Center Diff Damage Is Permanent",
    excerpt: "Audi Quattro is full-time AWD with a center differential. Any wheel-lift towing destroys the center diff. Repairs run $3,500–$6,000 plus labor.",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "Audi Quattro is full-time AWD with a center differential. Any wheel-lift towing destroys the center diff. Repairs run $3,500–$6,000 plus labor.",
      "Audi explicitly voids Quattro drivetrain warranty for tow damage. Documentation requirement: photos showing the vehicle was flatbedded, not wheel-lifted.",
      "We flatbed every Quattro at $149 / hour. Standard receipt includes photos.",
    ],
  },
  {
    slug: "tip-083-mustang-mach-e-towing",
    title: "Tip #83: Mustang Mach-E EV Towing Notes",
    excerpt: "Mach-E is full-time AWD on the GT trim (RWD on Select/Premium). Either way, flatbed only. The drivetrain does not freewheel when the 12V is dead.",
    category: "EV",
    date: "May 19, 2026",
    content: [
      "Mach-E is full-time AWD on the GT trim (RWD on Select/Premium). Either way, flatbed only. The drivetrain does not freewheel when the 12V is dead.",
      "Ford specifically requires flatbed in the Mach-E owner's manual. Wheel-lift towing voids the drivetrain warranty.",
      "Standard $149 / hour rate, $124 first hour online. Authorized Ford EV service centers in NY/NJ.",
    ],
  },
  {
    slug: "tip-084-ioniq-ev6-towing",
    title: "Tip #84: Hyundai Ioniq / Kia EV6 Towing",
    excerpt: "Both vehicles share an E-GMP platform. AWD versions require flatbed; RWD versions can be flatbedded too (recommended for safety even when not required).",
    category: "EV",
    date: "May 19, 2026",
    content: [
      "Both vehicles share an E-GMP platform. AWD versions require flatbed; RWD versions can be flatbedded too (recommended for safety even when not required).",
      "12V battery dead = main pack disconnected = no neutral release through normal procedures. There's a manual jump procedure for the 12V documented in the owner's manual.",
      "We tow to Hyundai EV Service or Kia EV Service. Standard $149 / hour rate.",
    ],
  },
  {
    slug: "tip-085-subaru-outback-always-awd",
    title: "Tip #85: Subaru Outback / Crosstrek: Always AWD",
    excerpt: "Every modern Subaru passenger vehicle (Outback, Forester, Crosstrek, Impreza, Legacy, Ascent, WRX) is AWD. There is no FWD trim. Always flatbed.",
    category: "Towing",
    date: "May 19, 2026",
    content: [
      "Every modern Subaru passenger vehicle (Outback, Forester, Crosstrek, Impreza, Legacy, Ascent, WRX) is AWD. There is no FWD trim. Always flatbed.",
      "Subaru's symmetrical AWD is permanently engaged. Wheel-lifting destroys the rear differential and transfer case. Repair cost: $3,000–$6,000.",
      "We default to flatbed on every Subaru. $149 / hour rate.",
    ],
  },
  {
    slug: "tip-086-battery-test-every-3-years",
    title: "Tip #86: Battery Test Every 3 Years",
    excerpt: "Most batteries hit end-of-life between year 3 and year 5 in NYC. Year 3 is the smart time to start load-testing annually. Year 4 is the smart time to budget a r…",
    category: "Maintenance",
    date: "May 19, 2026",
    content: [
      "Most batteries hit end-of-life between year 3 and year 5 in NYC. Year 3 is the smart time to start load-testing annually. Year 4 is the smart time to budget a replacement.",
      "Any auto parts store (AutoZone, Advance, O'Reilly) tests batteries free in 5 minutes. Bring the receipt — they'll write the CCA rating on it for comparison next year.",
      "When it's time, we replace on the curb at $149 / hour service rate plus battery at retail. Old battery recycled.",
    ],
  },
  {
    slug: "tip-087-tire-rotation-interval",
    title: "Tip #87: Tire Rotation Interval — 5,000–7,500 Miles",
    excerpt: "Front and rear tires wear at different rates. Without rotation, the fronts (or rears, depending on drivetrain) wear out twice as fast. Rotation extends tire lif…",
    category: "Maintenance",
    date: "May 19, 2026",
    content: [
      "Front and rear tires wear at different rates. Without rotation, the fronts (or rears, depending on drivetrain) wear out twice as fast. Rotation extends tire life ~30%.",
      "Most shops rotate every 5,000–7,500 miles. Schedule with your oil change to make it easy.",
      "If you hit a pothole and have rim damage or sidewall damage, we run flatbed to the shop at our $149 / hour rate.",
    ],
  },
  {
    slug: "tip-088-alternator-load-test",
    title: "Tip #88: Alternator Load Test — Not Just a Voltmeter",
    excerpt: "A multimeter on a battery at idle gives you a static voltage reading — not whether the alternator can carry electrical load. A real alternator load test runs th…",
    category: "Maintenance",
    date: "May 19, 2026",
    content: [
      "A multimeter on a battery at idle gives you a static voltage reading — not whether the alternator can carry electrical load. A real alternator load test runs the headlights, A/C, and accessories while measuring voltage drop.",
      "If voltage drops below 13.5V under load, the alternator is failing. Replace before it strands you.",
      "Our drivers carry real load testers. Standard $149 / hour rate, $124 first hour online.",
    ],
  },
  {
    slug: "tip-089-brake-pad-warning-sound",
    title: "Tip #89: Brake Pad Warning Sound: Replace Now",
    excerpt: "Most cars have a small metal tab on the brake pad backing that drags on the rotor when the pad is worn out. The sound is a high-pitched squeal at low speed, esp…",
    category: "Maintenance",
    date: "May 19, 2026",
    content: [
      "Most cars have a small metal tab on the brake pad backing that drags on the rotor when the pad is worn out. The sound is a high-pitched squeal at low speed, especially when braking lightly.",
      "Ignore it and the pad wears through to the rotor, scoring it. A $200 pad job becomes a $500–$800 pad-and-rotor job.",
      "If brakes fail entirely (pedal sinks, fluid leak), stop driving immediately. We tow flatbed at $149 / hour to your shop.",
    ],
  },
  {
    slug: "tip-090-cooling-system-check-summer",
    title: "Tip #90: Check Cooling System Before Summer",
    excerpt: "NYC summer highs hit 95°F+ with humidity in the 80%+ range. The cooling system that 'works' in spring may not hold up in August traffic. A radiator that's losin…",
    category: "Maintenance",
    date: "May 19, 2026",
    content: [
      "NYC summer highs hit 95°F+ with humidity in the 80%+ range. The cooling system that 'works' in spring may not hold up in August traffic. A radiator that's losing pressure or a thermostat stuck partially open will overheat.",
      "Cheap pressure test ($30 at any shop) confirms the system holds pressure. Coolant flush every 5 years or 50k miles.",
      "If you overheat on the BQE in August, stop. Don't keep driving. We tow flatbed to your shop at $149 / hour.",
    ],
  },
  {
    slug: "tip-091-wiper-blade-replacement",
    title: "Tip #91: Wiper Blades — Replace Annually",
    excerpt: "Wiper rubber dries out, cracks, and loses its edge in 12–18 months. NYC sun, road grit, and salt accelerate the wear. Smearing instead of clearing = time for ne…",
    category: "Maintenance",
    date: "May 19, 2026",
    content: [
      "Wiper rubber dries out, cracks, and loses its edge in 12–18 months. NYC sun, road grit, and salt accelerate the wear. Smearing instead of clearing = time for new blades.",
      "Standard sizes $15–$25 per blade. Winter-specific blades (Rain-X Latitude in winter compound, Bosch ICON) shed ice and don't freeze stuck.",
      "If your windshield is iced and you can't drive, that's a separate roadside call. Standard $149 / hour rate.",
    ],
  },
  {
    slug: "tip-092-cabin-air-filter",
    title: "Tip #92: Cabin Air Filter — Replace Annually",
    excerpt: "Most cars have a cabin air filter behind the glovebox. NYC air loads it up fast — pollution, brake dust, pollen. A clogged filter cuts A/C efficiency and create…",
    category: "Maintenance",
    date: "May 19, 2026",
    content: [
      "Most cars have a cabin air filter behind the glovebox. NYC air loads it up fast — pollution, brake dust, pollen. A clogged filter cuts A/C efficiency and creates a musty smell.",
      "Replacement is $15–$30 for the filter, 10 minutes of DIY for most cars. YouTube your specific year/make/model for the procedure.",
      "Not a tow scenario, but worth doing once a year for the people who breathe in the car.",
    ],
  },
  {
    slug: "tip-093-headlight-haze-fix",
    title: "Tip #93: Headlight Haze — DIY Fix Saves $600",
    excerpt: "Yellowed, hazy headlights cut night-time vision by up to 70%. The cause: UV degradation of the plastic lens. A new headlight assembly is $300–$800 per side.",
    category: "Maintenance",
    date: "May 19, 2026",
    content: [
      "Yellowed, hazy headlights cut night-time vision by up to 70%. The cause: UV degradation of the plastic lens. A new headlight assembly is $300–$800 per side.",
      "A $20 headlight restoration kit (Sylvania, 3M) sands, polishes, and re-coats the lens in an hour of DIY work. Results last 2–3 years.",
      "If you can't see at night because of haze, you're a hazard. Fix this weekend.",
    ],
  },
  {
    slug: "tip-094-spare-tire-pressure-check",
    title: "Tip #94: Check the Spare Tire's Pressure",
    excerpt: "Spares lose air sitting unused, just like regular tires. Most temporary spares need 60 PSI (much higher than a regular tire). A flat spare is useless when you n…",
    category: "Maintenance",
    date: "May 19, 2026",
    content: [
      "Spares lose air sitting unused, just like regular tires. Most temporary spares need 60 PSI (much higher than a regular tire). A flat spare is useless when you need it most.",
      "Check spare pressure every 6 months. Top up with a gas station compressor or a small 12V inflator.",
      "If your spare is flat or non-existent, we flatbed to a tire shop at $149 / hour rate.",
    ],
  },
  {
    slug: "tip-095-phantom-12v-drain",
    title: "Tip #95: Phantom 12V Drain From Charging Ports",
    excerpt: "Many older cars have 12V outlets that stay live with the key off. A phone charger, dashcam, or aftermarket accessory plugged in will slowly drain the battery.",
    category: "Maintenance",
    date: "May 19, 2026",
    content: [
      "Many older cars have 12V outlets that stay live with the key off. A phone charger, dashcam, or aftermarket accessory plugged in will slowly drain the battery.",
      "Check whether your 12V outlet is switched (keyed) or constant. Manuals usually specify. If constant, unplug accessories overnight.",
      "If you wake up to a dead battery despite no obvious cause, we run parasitic-draw diagnostic on scene at our $149 / hour rate.",
    ],
  },
  {
    slug: "tip-096-dsp-fleet-priority-dispatch",
    title: "Tip #96: DSP Fleets: Priority Dispatch Matters",
    excerpt: "Amazon DSPs and similar last-mile delivery fleets run tight routes with no slack. A van down for 90 minutes waiting on retail roadside is a $200–$500 revenue hi…",
    category: "Fleet",
    date: "May 19, 2026",
    content: [
      "Amazon DSPs and similar last-mile delivery fleets run tight routes with no slack. A van down for 90 minutes waiting on retail roadside is a $200–$500 revenue hit per vehicle.",
      "Fleet accounts get priority dispatch — your call jumps the retail queue. We coordinate with your dispatcher on shop drops and re-routes.",
      "Fleet rates negotiated based on volume. Standard retail rate is $149 / hour. Set up at /commercial.",
    ],
  },
  {
    slug: "tip-097-rideshare-tlc-friendly-shops",
    title: "Tip #97: Rideshare: TLC-Friendly Shops Matter",
    excerpt: "TLC-licensed vehicles need TLC-inspected shops for major repairs. Not every shop is on the list. Sending a TLC vehicle to a non-approved shop means re-inspectio…",
    category: "Fleet",
    date: "May 19, 2026",
    content: [
      "TLC-licensed vehicles need TLC-inspected shops for major repairs. Not every shop is on the list. Sending a TLC vehicle to a non-approved shop means re-inspection delays.",
      "Our dispatch maintains the current list of TLC-approved shops in each borough. Tell us you're TLC and we route accordingly.",
      "Standard $149 / hour rate. Fleet accounts available for high-volume operators.",
    ],
  },
  {
    slug: "tip-098-body-shop-direct-delivery",
    title: "Tip #98: Body Shop Direct-Delivery Accounts",
    excerpt: "Body shops with consistent insurance-vendor relationships get a dedicated tow operator that delivers cars from accident scenes directly to the shop. Faster cycl…",
    category: "Fleet",
    date: "May 19, 2026",
    content: [
      "Body shops with consistent insurance-vendor relationships get a dedicated tow operator that delivers cars from accident scenes directly to the shop. Faster cycle time, fewer intermediate stops.",
      "We run body shop accounts with consolidated monthly billing, COI on file for the shop, and drivers who know the receiving procedures (where to drop, who signs).",
      "Set up an account at /commercial. Volume-based pricing under retail $149 / hour.",
    ],
  },
  {
    slug: "tip-099-property-manager-dcwp-compliance",
    title: "Tip #99: Property Managers: DCWP Compliance Matters",
    excerpt: "Private-property tow operators must comply with DCWP rules — proper signage at every entrance, rate caps at $125 hookup, $25/day storage starting day 2, photos…",
    category: "Fleet",
    date: "May 19, 2026",
    content: [
      "Private-property tow operators must comply with DCWP rules — proper signage at every entrance, rate caps at $125 hookup, $25/day storage starting day 2, photos at pickup, proper redemption procedure.",
      "Non-compliant signage exposes property managers to 311 complaints, fines, and even forced removal of the tow contract. We handle compliance for our property manager accounts.",
      "Set up at /commercial. Same $149 / hour rate for customer-initiated work; capped rates for enforcement tows.",
    ],
  },
  {
    slug: "tip-100-master-index-100-nyc-tow-tips",
    title: "Tip #100: The Complete Index — 99 NYC Towing & Roadside Tips In One Place",
    excerpt: "The master index of our 99-tip series. Every tip in one place, grouped by category, every entry linked. Bookmark this one.",
    category: "Tips",
    date: "May 19, 2026",
    content: [
      "Welcome to the complete index of our 99-part NYC towing and roadside tips series. Every tip is a self-contained guide on a specific scenario — what to do, what to avoid, and how it ties into our flat hourly rate.",
      "One rate runs across every service we provide: $149 per hour, 1-hour minimum, billed in half-hour increments after that. Book online and your first hour is $124 — a $25 discount on the fastest booking channel. No NYC surcharge, no after-hours markup, no storage fees on same-day drops. The same rate at 3 AM as at 3 PM.",
      "### Winter — Cold-weather tips for NYC drivers — battery, tires, ice, snow.",
      "#1: {link:/blog/tip-001-winter-cold-cranks-battery|Cold Cranks Kill Marginal Batteries First} · #2: {link:/blog/tip-002-winter-tire-pressure-drop|Tire Pressure Drops 1 PSI for Every 10°F} · #3: {link:/blog/tip-003-winter-block-heater-extreme-cold|Block Heater Is Worth It Below 10°F} · #4: {link:/blog/tip-004-winter-snow-stuck-what-not-to-do|Stuck in Snow: What NOT to Do} · #5: {link:/blog/tip-005-winter-alt-side-parking-snow-rules|Alt-Side Parking Changes During Snow Emergencies} · #6: {link:/blog/tip-006-winter-frozen-door-lock|Frozen Door Lock — Don't Force the Key} · #7: {link:/blog/tip-007-winter-ice-covered-car-strategy|Ice-Covered Car: Strategy Matters} · #8: {link:/blog/tip-008-winter-salt-damage-brakes|Road Salt Eats Brake Lines} · #9: {link:/blog/tip-009-winter-wipers-washer-fluid|Winter Wiper Blades and Fluid Matter} · #10: {link:/blog/tip-010-winter-coolant-concentration|Check Coolant Concentration Before December}",
      "### Roadside — Jump-start, tire, lockout, gas, dead key fob — the everyday calls.",
      "#11: {link:/blog/tip-011-jump-start-procedure-step-by-step|Jump-Start a Car the Right Way} · #12: {link:/blog/tip-012-dont-jump-swollen-battery|Never Jump a Swollen or Leaking Battery} · #13: {link:/blog/tip-013-dont-drive-on-flat-tire|Why Driving on a Flat Costs You 10x More} · #14: {link:/blog/tip-014-find-your-spare-and-jack|Know Where Your Spare and Jack Are Before You Need Them} · #15: {link:/blog/tip-015-lockout-never-break-window|Lockout: Never Break the Window Yourself} · #16: {link:/blog/tip-016-gas-delivery-vs-walking|Gas Delivery vs. Walking to a Station} · #17: {link:/blog/tip-017-run-flat-tires-not-invincible|Run-Flat Tires Aren't Invincible} · #18: {link:/blog/tip-018-battery-age-proactive-replace|Replace Your Battery at Year 4, Not Year 6} · #19: {link:/blog/tip-019-alternator-vs-battery-diagnosis|Alternator vs. Battery — How to Tell} · #20: {link:/blog/tip-020-parasitic-draw-overnight-dead|Battery Dies Overnight? Parasitic Draw} · #21: {link:/blog/tip-021-key-fob-battery-replacement|Key Fob Battery — 2-Minute Fix You Can Do Yourself} · #22: {link:/blog/tip-022-tpms-light-vs-actual-flat|TPMS Light Isn't Always a Flat} · #23: {link:/blog/tip-023-kids-in-the-car-during-breakdown|Kids in the Car During a Breakdown} · #24: {link:/blog/tip-024-pet-inside-vehicle-during-tow|Bringing a Pet on a Tow} · #25: {link:/blog/tip-025-empty-fuel-warning-how-far|Empty Fuel Warning — How Far Can You Really Go?}",
      "### Towing — Flatbed vs wheel-lift, AWD/EV, motorcycles, exotic cars, garage clearance.",
      "#26: {link:/blog/tip-026-awd-4wd-always-flatbed|AWD and 4WD: Always Flatbed} · #27: {link:/blog/tip-027-ev-motor-lockup-risk|EVs Cannot Be Dragged — Motor Lock-Up Risk} · #28: {link:/blog/tip-028-low-clearance-sports-car|Low-Clearance Sports Cars Need Corner Protection} · #29: {link:/blog/tip-029-motorcycle-strap-points|Motorcycle Tow: Strap Points Matter} · #30: {link:/blog/tip-030-awd-that-looks-like-fwd|Some AWDs Don't Look Like AWDs (CR-V, RAV4)} · #31: {link:/blog/tip-031-convertible-top-latched-before-tow|Latch the Convertible Top Before a Tow} · #32: {link:/blog/tip-032-close-trunk-before-driver-leaves|Close the Trunk and Doors Before You Hand Over the Keys} · #33: {link:/blog/tip-033-lock-visible-items-in-trunk|Lock Personal Items in the Trunk Before You Leave} · #34: {link:/blog/tip-034-tow-to-home-vs-shop-vs-dealer|Tow to Home vs. Shop vs. Dealer} · #35: {link:/blog/tip-035-same-day-vs-overnight-storage|Same-Day Drop Avoids Storage Fees} · #36: {link:/blog/tip-036-multi-vehicle-accident-scene|Multi-Vehicle Accident: One Tow Per Vehicle} · #37: {link:/blog/tip-037-documentation-timestamped-photos|Demand Timestamped Photos at Load and Drop} · #38: {link:/blog/tip-038-itemized-receipt-required|What Should Be on Your Itemized Receipt} · #39: {link:/blog/tip-039-scope-change-on-scene|When the Diagnosis Changes on Scene} · #40: {link:/blog/tip-040-garage-clearance-before-truck|Verify Garage Clearance Before You Call} · #79: {link:/blog/tip-079-bmw-xdrive-flatbed-only|BMW xDrive: Always Flatbed} · #80: {link:/blog/tip-080-porsche-911-corner-protection|Porsche 911: Corner Protection on Load} · #81: {link:/blog/tip-081-mercedes-amg-low-clearance|Mercedes AMG: Low Clearance Procedure} · #82: {link:/blog/tip-082-audi-quattro-center-diff|Audi Quattro: Center Diff Damage Is Permanent} · #85: {link:/blog/tip-085-subaru-outback-always-awd|Subaru Outback / Crosstrek: Always AWD}",
      "### NYC — Borough-specific hazards — BQE, Cross Bronx, bridges, tunnels, alt-side parking.",
      "#41: {link:/blog/tip-041-bqe-shoulder-breakdown|BQE Shoulder Breakdown — Stay With Vehicle} · #42: {link:/blog/tip-042-cross-bronx-worst-spots|Cross Bronx: The Worst Breakdown Spots} · #43: {link:/blog/tip-043-tunnel-breakdown-call-911|Tunnel Breakdown: 911 First, Always} · #44: {link:/blog/tip-044-port-authority-crossings|Port Authority Crossings: Different Rules} · #45: {link:/blog/tip-045-bridge-deck-breakdown|Bridge Deck Breakdown — Stay In Car} · #46: {link:/blog/tip-046-alt-side-plus-breakdown-double-penalty|Alt-Side Day + Breakdown = Double Penalty} · #47: {link:/blog/tip-047-garage-clearance-restrictions|Garage Clearance Restrictions in Manhattan} · #48: {link:/blog/tip-048-one-way-streets-u-turn-restrictions|One-Way Streets and Tow Staging} · #49: {link:/blog/tip-049-manhattan-loading-zone-staging|Manhattan Loading Zones: Truck Staging} · #50: {link:/blog/tip-050-311-vs-911-which-to-call|311 vs. 911 — Which Number for a Breakdown} · #51: {link:/blog/tip-051-dcwp-tow-license-verification|Verify a Tow Operator's DCWP License} · #52: {link:/blog/tip-052-private-property-vs-nypd-tow|Private-Property Tow vs. NYPD Tow} · #53: {link:/blog/tip-053-nyc-fuel-surcharge-doesnt-exist|NYC 'Fuel Surcharge' Doesn't Exist} · #54: {link:/blog/tip-054-after-hours-markup-doesnt-exist|There Is No After-Hours Markup in NYC Towing} · #55: {link:/blog/tip-055-storage-fees-same-day-illegal|Same-Day Storage Fees Are Illegal}",
      "### Legal — Tow pound process, insurance billing, DCWP rules, 311 complaints.",
      "#56: {link:/blog/tip-056-nypd-tow-pound-process|NYPD Tow Pound: The Full Process} · #57: {link:/blog/tip-057-pier-76-brooklyn-navy-yard-pounds|Borough Tow Pound Locations and Hours} · #58: {link:/blog/tip-058-documents-needed-at-pound|Documents You MUST Bring to the Pound} · #59: {link:/blog/tip-059-outstanding-tickets-must-be-paid|Outstanding Tickets Must Be Paid at the Pound} · #60: {link:/blog/tip-060-carrier-direct-billing-accident-tow|Insurance Direct-Bill on Accident Tows} · #61: {link:/blog/tip-061-nyc-pip-coverage-explained|New York No-Fault (PIP) Coverage Basics} · #62: {link:/blog/tip-062-311-complaint-predatory-tow|Filing a 311 Complaint Against a Tow Operator} · #63: {link:/blog/tip-063-dcwp-rate-caps-private-property|DCWP Rate Caps for Private-Property Tows} · #64: {link:/blog/tip-064-signage-requirements-private-lots|Signage Requirements at Private Lots} · #65: {link:/blog/tip-065-claim-number-what-insurance-needs|What Your Insurance Needs for a Tow Claim}",
      "### Pricing — Our $149/hr rate, scams to avoid, fleet vs retail, payment methods.",
      "#66: {link:/blog/tip-066-our-rate-249-explained|Our Rate: $149 / Hour, No Catches} · #67: {link:/blog/tip-067-cash-only-is-red-flag|Cash-Only Demands Are a Red Flag} · #68: {link:/blog/tip-068-itemized-receipt-mandatory|Itemized Receipts Are Mandatory by Law} · #69: {link:/blog/tip-069-hidden-surcharges-to-watch-for|Hidden Surcharges to Watch For} · #70: {link:/blog/tip-070-padded-mileage|Padded Mileage Is Theft} · #71: {link:/blog/tip-071-rotation-tow-vs-operator-of-choice|Rotation Tow vs. Operator of Choice} · #72: {link:/blog/tip-072-fleet-account-vs-retail|Fleet Account vs. Retail} · #73: {link:/blog/tip-073-aaa-vs-local-operator|AAA vs. Local Operator} · #74: {link:/blog/tip-074-payment-method-comparison|Card vs. Apple Pay vs. Cash} · #75: {link:/blog/tip-075-insurance-reimbursement-workflow|Insurance Reimbursement Workflow}",
      "### EV — Tesla, Rivian, Lucid, Ioniq, Mach-E — EV-specific towing procedures.",
      "#76: {link:/blog/tip-076-tesla-tow-mode-procedure|Tesla 'Tow Mode' Procedure} · #77: {link:/blog/tip-077-rivian-neutral-release|Rivian Neutral Release} · #78: {link:/blog/tip-078-lucid-towing-constraints|Lucid Air Towing Constraints} · #83: {link:/blog/tip-083-mustang-mach-e-towing|Mustang Mach-E EV Towing Notes} · #84: {link:/blog/tip-084-ioniq-ev6-towing|Hyundai Ioniq / Kia EV6 Towing}",
      "### Maintenance — Battery, tires, alternator, cooling system — preventive care.",
      "#86: {link:/blog/tip-086-battery-test-every-3-years|Battery Test Every 3 Years} · #87: {link:/blog/tip-087-tire-rotation-interval|Tire Rotation Interval — 5,000–7,500 Miles} · #88: {link:/blog/tip-088-alternator-load-test|Alternator Load Test — Not Just a Voltmeter} · #89: {link:/blog/tip-089-brake-pad-warning-sound|Brake Pad Warning Sound: Replace Now} · #90: {link:/blog/tip-090-cooling-system-check-summer|Check Cooling System Before Summer} · #91: {link:/blog/tip-091-wiper-blade-replacement|Wiper Blades — Replace Annually} · #92: {link:/blog/tip-092-cabin-air-filter|Cabin Air Filter — Replace Annually} · #93: {link:/blog/tip-093-headlight-haze-fix|Headlight Haze — DIY Fix Saves $600} · #94: {link:/blog/tip-094-spare-tire-pressure-check|Check the Spare Tire's Pressure} · #95: {link:/blog/tip-095-phantom-12v-drain|Phantom 12V Drain From Charging Ports}",
      "### Fleet — DSP, rideshare, body shop, property manager, heavy-duty accounts.",
      "#96: {link:/blog/tip-096-dsp-fleet-priority-dispatch|DSP Fleets: Priority Dispatch Matters} · #97: {link:/blog/tip-097-rideshare-tlc-friendly-shops|Rideshare: TLC-Friendly Shops Matter} · #98: {link:/blog/tip-098-body-shop-direct-delivery|Body Shop Direct-Delivery Accounts} · #99: {link:/blog/tip-099-property-manager-dcwp-compliance|Property Managers: DCWP Compliance Matters}",
      "Need a tow or roadside service right now? {link:/book-towing-service-today|Book online} to save $25 — your first hour is $124 instead of $149. Or call (212) 470-4068 at the standard $149 / hour rate. 24/7 dispatch, all 5 NYC boroughs, no NYC surcharge, no after-hours markup.",
    ],
  }
];