// @ts-nocheck
export interface CustomerType {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  longDescription: string;
  services: string[]; // top service slugs for this customer type
  painPoints: string[];
  creditHighlights: string[]; // preserved field name; used as "value highlights" / program benefits
}

export const CUSTOMER_TYPES: CustomerType[] = [
  {
    slug: "drivers",
    name: "Everyday Drivers",
    shortName: "Drivers",
    description: "Broke down on the shoulder, dead battery in the lot, locked out at the grocery store. 24/7 dispatch, flat upfront pricing, 30-minute arrival option.",
    longDescription: "Most tow calls come from drivers having the worst moment of their week. Our job is to make it the least bad moment possible. You call a live dispatcher (never an IVR), we quote the exact price before any truck rolls, we text you the driver's name and ETA, and we arrive with the right equipment the first time — flatbed for AWD, wheel-lift for the parking deck, motorcycle-rated for the bike. Emergency Priority guarantees 30-minute arrival or $50 off. Standard service is under 60 minutes. No predatory storage yards — we tow to the shop YOU choose.",
    services: ["emergency-towing", "flatbed-towing", "accident-recovery", "jump-start-service", "flat-tire-change", "lockout-service"],
    painPoints: ["Stranded on the shoulder of a live freeway", "Dead battery in a crowded lot", "Locked keys in the car with kids or a dog inside", "Flat tire and no spare", "Broke down after business hours"],
    creditHighlights: ["30-minute arrival guarantee or $50 off", "Flat upfront pricing — no phone-game surcharges", "Your shop, your choice — never a predatory tow-yard"],
  },
  {
    slug: "fleet-managers",
    name: "Fleet Managers & Commercial Fleets",
    shortName: "Fleets",
    description: "Delivery, service, last-mile, and rental fleets. Dedicated dispatch line, net-30 billing, per-vehicle documentation for every call.",
    longDescription: "Fleet managers juggle dozens or hundreds of vehicles that each generate an average of 0.8 breakdowns per year. At 100 vans, that's 80 tow calls annually. We set up commercial accounts with a dedicated dispatch number, authorized caller list, and net-30 consolidated billing. Every tow produces a per-vehicle invoice with VIN, odometer, photos, and destination — the exact fields your fleet management software expects. Preferred rates for contracted volume, custom SLAs, and direct integration with Element, Holman, ARI, and Wheels.",
    services: ["fleet-vehicle-towing", "medium-duty-towing", "flatbed-towing", "emergency-towing", "jump-start-service"],
    painPoints: ["Dozens of vehicles breaking down across a wide service area", "Drivers expensing tows with inconsistent documentation", "Fleet-management-software integration for clean reporting", "Need direct billing so drivers never handle payment"],
    creditHighlights: ["Net-30 consolidated billing with per-VIN line items", "Dedicated dispatch number and authorized caller list", "Preferred rates for contracted volume"],
  },
  {
    slug: "rental-car-branches",
    name: "Rental Car Companies",
    shortName: "Rental Cars",
    description: "Customer breakdowns, exchanges, impound returns, and fleet shuffling. Branded-experience-preserving service with contactless handoffs.",
    longDescription: "Rental car breakdowns are a brand experience problem as much as a logistics problem — your customer is already frustrated, and the tow truck is the third-party you're trusting to not make it worse. Our drivers follow your customer-service protocols: uniform, introduction script, vehicle inspection, customer belongings confirmation, and coordination with the branch for a replacement vehicle meeting point. Contactless key handoffs are standard. Available at every major US airport and most mid-size urban markets.",
    services: ["emergency-towing", "flatbed-towing", "fleet-vehicle-towing", "dealership-transport", "jump-start-service"],
    painPoints: ["Customer stranded with rental breakdown", "Brand experience suffers if tow driver is unprofessional", "Need coordination with branch for replacement vehicle", "Airport pickups and drop-offs in controlled-access areas"],
    creditHighlights: ["Branded-experience-matched service protocols", "Airport access credentials in every major market", "Contactless key handoff standard"],
  },
  {
    slug: "insurance-carriers",
    name: "Insurance Carriers & Auto Clubs",
    shortName: "Insurance",
    description: "AAA, Geico, State Farm, Progressive, Allstate, USAA. Direct-bill service with carrier-compliant documentation on every call.",
    longDescription: "Insurance carriers and auto clubs need tow operators who speak their language: ACORD-compatible invoicing, carrier-specific dispatch protocols, IVR integration with ISP networks, and clean documentation for every call — time-on-scene, miles towed, destination, driver notes, and photographs where applicable. We're set up for direct-bill with every major carrier and most auto clubs, plus most third-party networks (Agero, Allied, Road America, Urgently, Nation Safe Drivers).",
    services: ["emergency-towing", "flatbed-towing", "accident-recovery", "jump-start-service", "flat-tire-change", "fuel-delivery", "lockout-service"],
    painPoints: ["Member stranded, expecting fast fulfillment", "Third-party network dispatch often sends the wrong equipment", "Paperwork compliance for reimbursement", "Fulfillment SLAs vary by carrier"],
    creditHighlights: ["Direct-bill with every major carrier", "ACORD-compatible invoicing and documentation", "Third-party network certified (Agero, Allied, Urgently, etc.)"],
  },
  {
    slug: "law-enforcement",
    name: "Law Enforcement & Public Safety",
    shortName: "Law Enforcement",
    description: "Police, sheriff, state patrol, highway patrol. Rotation-list participation with rapid lane-clearance response and chain-of-custody documentation.",
    longDescription: "Law enforcement agencies need tow operators they can trust on the worst calls — fatal accidents, drug seizures, pursuit terminations, abandoned vehicle recoveries, and rotation-list non-emergency holds. We participate in rotation lists in every jurisdiction where local ordinance allows, maintain evidence-grade chain-of-custody documentation, and train drivers in traffic incident management for rapid lane-clearance. Our storage yards meet DOJ impound-standard fencing, lighting, and camera requirements.",
    services: ["accident-recovery", "emergency-towing", "heavy-duty-towing", "rollover-recovery", "impound-towing"],
    painPoints: ["Live travel lanes need clearance fast", "Chain-of-custody required for evidence vehicles", "Rotation-list compliance with state and local rules", "24/7 response needed for overnight accidents"],
    creditHighlights: ["Rotation-list participation in every jurisdiction we can", "DOJ-standard storage yards with camera monitoring", "Certified TIM operators for lane-clearance work"],
  },
  {
    slug: "dealerships",
    name: "Auto Dealerships",
    shortName: "Dealerships",
    description: "Inventory moves, trade-in transport, auction pickups, loaner swaps, customer breakdowns. Enclosed transport available for exotic inventory.",
    longDescription: "Dealerships have daily vehicle-movement needs — rooftop-to-rooftop inventory swaps, trade-in transport from remote appraisals, auction buy pickup and delivery, loaner car ferrying, and service drop-off/pickup for high-value customers. Enclosed transport available for pre-owned exotic inventory. We set up dedicated dispatch with a single point of contact, consolidated monthly billing, and per-stock-number documentation matched to your DMS.",
    services: ["dealership-transport", "auction-transport", "flatbed-towing", "luxury-exotic-towing", "fleet-vehicle-towing"],
    painPoints: ["Daily inventory shuffle between rooftops", "Trade-in transport from remote appraisals", "Auction buy pickup within yard deadlines", "Service customer loaner swaps"],
    creditHighlights: ["Single-point-of-contact dispatch", "Enclosed transport available for exotic inventory", "Stock-number-matched documentation for DMS"],
  },
  {
    slug: "body-shops",
    name: "Body Shops & Collision Centers",
    shortName: "Body Shops",
    description: "Insurance-authorized pickups, total-loss tows, urgent parts runs. Direct-billing with major carriers and salvage yard coordination.",
    longDescription: "Body shops and collision centers need a tow operator who understands their workflow. We pick up insurance-authorized vehicles straight from the accident scene, tow total-loss vehicles to insurer-designated salvage yards with proper paperwork, and handle inter-shop parts runs for urgent repairs. Our drivers know how to read a POE form, handle a title-of-salvage transfer, and work with the BAR inspection process in California and similar regulated states.",
    services: ["accident-recovery", "flatbed-towing", "body-shop-transport", "emergency-towing"],
    painPoints: ["Insurance-authorized pickups need fast response", "Total-loss tows require specific destination and paperwork", "Parts runs between shops on tight repair deadlines", "Customer cars need to arrive without additional damage"],
    creditHighlights: ["Direct-bill relationships with major insurance carriers", "POE-familiar drivers", "Fast insurance-authorized pickup"],
  },
  {
    slug: "property-managers",
    name: "Property Managers & HOAs",
    shortName: "Property Mgrs",
    description: "Trespassing vehicles, fire-lane violators, reserved-space abusers. Compliant private-property towing with full documentation.",
    longDescription: "Property managers and HOAs use private-property towing to enforce parking rules: trespassing vehicles, fire-lane violators, reserved-space abusers, unauthorized long-term parkers. Every state has different notification, signage, and documentation requirements, and we comply with all of them. Photographs, timestamped records, and required signage consultation are standard. Dedicated dispatch line and net-30 billing for multi-property managers.",
    services: ["impound-towing", "parking-lot-assistance", "fleet-vehicle-towing"],
    painPoints: ["Trespassing vehicles blocking residents", "Fire-lane violations creating liability", "Reserved-space abuse by non-residents", "Multi-property portfolio with recurring needs"],
    creditHighlights: ["Full state-law compliance with photo documentation", "Required-signage consultation included", "Net-30 billing across entire portfolio"],
  },
  {
    slug: "truck-drivers",
    name: "Truck Drivers & Trucking Companies",
    shortName: "Truckers",
    description: "Broken-down semis, blown tires on trailers, DOT inspection failures, rollover recoveries. Class 7/8 heavy-duty fleet available 24/7.",
    longDescription: "Professional drivers and trucking companies break down big and break down expensive. Every hour a truck is off the road is lost revenue plus driver HOS complications. Our heavy-duty fleet covers Class 7 and 8 — 50-ton and 75-ton wreckers, rotators for load-shift recovery, air-cushion systems for rollover recovery. Drivers hold WreckMaster or TRAA certifications. 24/7 availability on every interstate we cover, with coordination for state DOT lane closures when needed.",
    services: ["semi-truck-towing", "heavy-duty-towing", "rollover-recovery", "medium-duty-towing", "emergency-towing"],
    painPoints: ["Breakdowns create HOS complications and lost revenue", "Rollover recoveries require specialized equipment", "Loaded trailer recoveries need load-shift planning", "DOT inspection failures need fast resolution"],
    creditHighlights: ["WreckMaster-certified heavy operators", "50-ton and 75-ton wreckers with rotators", "Air-cushion rollover recovery"],
  },
  {
    slug: "motorcyclists",
    name: "Motorcyclists & Riders",
    shortName: "Motorcyclists",
    description: "Sport bikes, cruisers, touring, adventure, dirt. Dedicated motorcycle-rated flatbeds, soft-strap tie-downs, ride-along when possible.",
    longDescription: "Motorcycle towing done wrong is expensive — a bike strapped through the bars or chained to the frame can damage thousands of dollars of fairings, triple clamps, or handlebar controls. We use dedicated motorcycle-rated flatbeds with proper wheel chocks and soft canyon straps that tie to the frame at designated points. Every major bike type handled correctly: sportbikes, cruisers, baggers, adventure bikes, dirt bikes, scooters. Ride-along space usually available so you aren't stranded.",
    services: ["motorcycle-towing", "emergency-towing", "flatbed-towing", "accident-recovery"],
    painPoints: ["Most tow companies don't know how to strap a bike correctly", "No ride-along means you're stranded", "Sport bikes have low clearance that standard flatbeds damage", "Bike shops often can't recommend a good tow operator"],
    creditHighlights: ["Motorcycle-rated flatbeds with wheel chocks", "Soft-strap (never chain-hook) tie-down protocol", "Ride-along space usually available"],
  },
  {
    slug: "rv-owners",
    name: "RV & Motorhome Owners",
    shortName: "RV Owners",
    description: "Class A, B, and C motorhomes, fifth-wheels, travel trailers. Heavy-duty equipment with RV-familiar drivers.",
    longDescription: "RV breakdowns are one of the most stressful scenarios on the road — often on a trip, often far from home, often with family aboard. Our heavy-duty fleet covers Class A motorhomes (which need a 35-50 ton wrecker), Class B and C units (medium-duty), plus fifth-wheel and travel trailer towing with proper hitch matching. Our drivers know RV slide-outs, awnings, and the specific loading considerations for recreational vehicles.",
    services: ["rv-motorhome-towing", "heavy-duty-towing", "medium-duty-towing", "emergency-towing"],
    painPoints: ["Breakdown on a trip far from home", "Family aboard making the situation stressful", "Most tow operators aren't familiar with RV systems", "Finding an RV-competent service shop at the destination"],
    creditHighlights: ["Class A, B, C, fifth-wheel, and travel trailer experience", "Heavy-duty fleet in every major market", "RV-familiar drivers"],
  },
  {
    slug: "classic-car-owners",
    name: "Classic & Exotic Car Owners",
    shortName: "Classics",
    description: "Ferraris, Porsches, pre-war vintage, muscle cars, restorations. Soft-strap flatbeds or enclosed transport with experienced drivers.",
    longDescription: "Classic and exotic owners learn early that most tow operators don't understand their cars. A pre-war vintage with drum brakes and a non-synchro transmission needs a very different loading approach than a McLaren with adaptive ride height. We use dedicated soft-strap flatbeds, enclosed transport on request, drivers who know what a launch-assist button is and what a non-starting vintage needs to load safely. Insured to $500,000 per load without rider policies.",
    services: ["luxury-exotic-towing", "classic-car-transport", "long-distance-towing", "flatbed-towing"],
    painPoints: ["Most tow trucks can't safely load low-clearance cars", "Chain-and-hook tow operators damage body panels", "Non-running classics need special loading techniques", "Enclosed transport availability varies by market"],
    creditHighlights: ["Dedicated low-approach-angle flatbeds", "Enclosed transport available on request", "Insured up to $500,000 per load"],
  },
  {
    slug: "auto-lenders",
    name: "Auto Lenders & Repossession Clients",
    shortName: "Lenders",
    description: "Credit unions, banks, buy-here-pay-here lots. Licensed recovery agents, DMV-compliant paperwork, secure storage.",
    longDescription: "Repossession is a licensed discipline separate from general towing. Our repo operators hold state-required recovery agent licenses, carry dedicated repo insurance, follow breach-of-peace protocols, and maintain full chain-of-custody documentation. We recover from driveways, workplaces, and public lots; deliver to secure fenced storage with camera monitoring; and follow lender-specified retrieval and redemption protocols for each account.",
    services: ["repossession-towing", "impound-towing", "fleet-vehicle-towing"],
    painPoints: ["Recovery-agent licensing varies by state", "Breach-of-peace compliance required", "Secure storage with chain-of-custody", "Lender-specific paperwork and protocols"],
    creditHighlights: ["Licensed recovery agents in every state", "Secure camera-monitored storage", "Lender-specific protocol compliance"],
  },
  {
    slug: "emergency-services",
    name: "Municipal & Emergency Services",
    shortName: "Municipal",
    description: "City fleets, fire, EMS, public works. Vehicle recovery, evidence tows, and heavy equipment transport with government-contract compliance.",
    longDescription: "Municipal and emergency services customers — city fleets, fire, EMS, public works — need tow operators who can work within government contracting requirements: MWBE certifications where applicable, prevailing-wage compliance on public work, detailed documentation for audit trails, and dedicated points of contact for bulk dispatch. Also handles post-incident recovery for emergency-services vehicles after crashes.",
    services: ["fleet-vehicle-towing", "heavy-duty-towing", "accident-recovery", "equipment-transport"],
    painPoints: ["Government contracting compliance overhead", "Emergency-services vehicle recovery requires coordination", "Bulk dispatch needs dedicated account management", "Audit-trail documentation for taxpayer dollars"],
    creditHighlights: ["Government-contract compliance available", "Dedicated municipal account management", "Audit-ready documentation on every call"],
  },
];
