// AUTO-GENERATED by scripts/pexels-download.ts — do not edit by hand.
// Curated pool of Pexels cleaning photography, mapped to SEO filenames + alt text.
// All photos by Tima Miroshnichenko (https://www.pexels.com/@tima-miroshnichenko).
// Pexels license: free to use commercially, no attribution required, but we include it anyway.

export type PhotoPool = 'lifestyle' | 'team'
export type PhotoCategory = 'mop' | 'dust' | 'kitchen' | 'bathroom' | 'window' | 'bed' | 'vacuum' | 'team' | 'interior'

export interface SitePhoto {
  id: number
  src: string
  alt: string
  caption: string
  pool: PhotoPool
  category: PhotoCategory
  width: number
  height: number
  photographer: string
  photographerUrl: string
  sourceUrl: string
}

export const PHOTOS: SitePhoto[] = [
  {
    "id": 6196567,
    "src": "/photos/nyc-cleaner-mopping-modern-living-room.jpg",
    "alt": "Professional NYC cleaner mopping the floor in a modern apartment living room",
    "caption": "Mopping a modern NYC apartment",
    "pool": "lifestyle",
    "category": "mop",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/a-grayscale-photo-of-a-person-mopping-the-floor-6196567/"
  },
  {
    "id": 6196575,
    "src": "/photos/nyc-maid-mopping-tiled-apartment-floor.jpg",
    "alt": "A maid from The NYC Maid mopping a tiled floor in a cozy New York City apartment",
    "caption": "Tile floor cleaning in a New York apartment",
    "pool": "lifestyle",
    "category": "mop",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/woman-in-gray-sweater-mopping-a-tiled-floor-6196575/"
  },
  {
    "id": 6196568,
    "src": "/photos/nyc-house-cleaner-mopping-cozy-living-room.jpg",
    "alt": "A professional house cleaner mopping the floor of a cozy New York City living room",
    "caption": "Floor mopping, NYC living room",
    "pool": "lifestyle",
    "category": "mop",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/a-woman-mopping-the-floor-6196568/"
  },
  {
    "id": 6196582,
    "src": "/photos/nyc-cleaner-mopping-bright-modern-apartment.jpg",
    "alt": "House cleaner mopping a bright, modern NYC apartment with large windows",
    "caption": "Bright NYC apartment mop session",
    "pool": "lifestyle",
    "category": "mop",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/a-woman-cleaning-the-floor-6196582/"
  },
  {
    "id": 6196573,
    "src": "/photos/nyc-home-cleaning-service-mopping-floor.jpg",
    "alt": "Home cleaning service in New York City mopping a tile floor",
    "caption": "NYC home cleaning service at work",
    "pool": "lifestyle",
    "category": "mop",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/grayscale-photo-of-a-woman-on-a-video-call-while-holding-a-mop-6196573/"
  },
  {
    "id": 6195198,
    "src": "/photos/nyc-maid-wiping-table-modern-living-room.jpg",
    "alt": "A NYC maid wearing gloves wiping a coffee table in a modern Manhattan living room",
    "caption": "Detail dusting, NYC living room",
    "pool": "lifestyle",
    "category": "dust",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/woman-cleaning-the-house-6195198/"
  },
  {
    "id": 6195199,
    "src": "/photos/nyc-house-cleaning-wiping-table-gloves.jpg",
    "alt": "Professional house cleaner wiping a table in a contemporary New York apartment",
    "caption": "Surface wipe down in an NYC home",
    "pool": "lifestyle",
    "category": "dust",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/woman-in-gray-sweater-standing-near-table-6195199/"
  },
  {
    "id": 6195194,
    "src": "/photos/nyc-maid-service-table-cleaning.jpg",
    "alt": "The NYC Maid cleaner wiping a table in a New York City apartment",
    "caption": "NYC table cleaning detail",
    "pool": "lifestyle",
    "category": "dust",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/a-woman-in-gray-sweater-standing-by-the-table-6195194/"
  },
  {
    "id": 6195212,
    "src": "/photos/nyc-maid-making-bed-bright-bedroom.jpg",
    "alt": "NYC maid service making the bed in a bright, monochrome bedroom",
    "caption": "Bedroom turndown, NYC apartment",
    "pool": "lifestyle",
    "category": "bed",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/grayscale-photo-of-a-woman-fixing-the-bed-6195212/"
  },
  {
    "id": 6195289,
    "src": "/photos/nyc-window-cleaning-apartment-cloth-bucket.jpg",
    "alt": "Professional window cleaning in a New York City apartment using cloth and bucket",
    "caption": "NYC apartment window cleaning",
    "pool": "lifestyle",
    "category": "window",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/grayscale-photo-of-woman-wiping-the-window-6195289/"
  },
  {
    "id": 6195207,
    "src": "/photos/nyc-maid-washing-dishes-modern-kitchen.jpg",
    "alt": "NYC maid wearing rubber gloves washing dishes in a modern Manhattan kitchen",
    "caption": "Dish cleaning in a NYC kitchen",
    "pool": "lifestyle",
    "category": "kitchen",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/woman-in-black-long-sleeve-shirt-washing-dishes-6195207/"
  },
  {
    "id": 6195203,
    "src": "/photos/nyc-kitchen-cleaning-washing-dishes-sink.jpg",
    "alt": "NYC kitchen cleaning service washing dishes under running water at the sink",
    "caption": "Kitchen sink detail, NYC",
    "pool": "lifestyle",
    "category": "kitchen",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/grayscale-photo-of-a-person-washing-a-glass-in-the-kitchen-sink-6195203/"
  },
  {
    "id": 6195118,
    "src": "/photos/nyc-maid-professional-cleaner-red-uniform.jpg",
    "alt": "Professional cleaner from The NYC Maid in red uniform cleaning an NYC apartment with a bucket",
    "caption": "NYC Maid team member at work",
    "pool": "team",
    "category": "team",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/woman-in-gray-shirt-and-orange-jumpsuit-6195118/"
  },
  {
    "id": 6195125,
    "src": "/photos/nyc-cleaning-team-red-uniforms-living-room.jpg",
    "alt": "The NYC Maid cleaning team in red uniforms ready to sanitize a modern Manhattan living room",
    "caption": "NYC Maid cleaning crew",
    "pool": "team",
    "category": "team",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/cleaners-in-orange-uniform-6195125/"
  },
  {
    "id": 6195120,
    "src": "/photos/nyc-maid-professional-cleaning-team-equipment.jpg",
    "alt": "Three professional NYC Maid cleaners in uniform with equipment, ready for a job",
    "caption": "NYC Maid team with equipment",
    "pool": "team",
    "category": "team",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/man-and-woman-standing-while-holding-vacuum-cleaner-6195120/"
  },
  {
    "id": 6195122,
    "src": "/photos/nyc-cleaning-team-vacuuming-red-uniforms.jpg",
    "alt": "A team of professional NYC Maid cleaners in red uniforms using a vacuum in a New York home",
    "caption": "NYC Maid team vacuuming",
    "pool": "team",
    "category": "vacuum",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/people-wearing-sneakers-6195122/"
  },
  {
    "id": 6195277,
    "src": "/photos/nyc-maid-crew-sweeping-mopping-red-overalls.jpg",
    "alt": "Two NYC Maid cleaners in red overalls vacuuming and sweeping a modern NYC living room",
    "caption": "NYC Maid crew mid-service",
    "pool": "team",
    "category": "team",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/women-in-orange-uniform-cleaning-the-floor-6195277/"
  },
  {
    "id": 6195276,
    "src": "/photos/nyc-cleaner-ladder-mopping-high-wall.jpg",
    "alt": "NYC Maid cleaner in red overalls on a ladder cleaning a high wall in a Manhattan apartment",
    "caption": "Above-eye-level cleaning, NYC Maid",
    "pool": "team",
    "category": "team",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/woman-in-orange-jumpsuit-standing-on-gray-ladder-6195276/"
  },
  {
    "id": 6197108,
    "src": "/photos/nyc-cleaning-crew-mopping-dining-room.jpg",
    "alt": "The NYC Maid cleaning crew in red uniforms mopping and wiping glass in a New York dining room",
    "caption": "Dining room detail, NYC Maid",
    "pool": "team",
    "category": "team",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/group-of-people-cleaning-a-dining-room-6197108/"
  },
  {
    "id": 6196682,
    "src": "/photos/nyc-maid-team-professional-dining-room.jpg",
    "alt": "Professional NYC Maid team working in a modern dining room in New York City",
    "caption": "Team service, NYC Maid",
    "pool": "team",
    "category": "team",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/people-cleaning-a-dining-room-6196682/"
  },
  {
    "id": 6195274,
    "src": "/photos/nyc-cleaners-vacuum-mop-modern-living-room.jpg",
    "alt": "Two NYC Maid cleaners in work uniforms using a vacuum and mop in a modern Manhattan living room",
    "caption": "NYC Maid vacuum and mop combo",
    "pool": "team",
    "category": "team",
    "width": 1880,
    "height": 1253,
    "photographer": "Tima Miroshnichenko",
    "photographerUrl": "https://www.pexels.com/@tima-miroshnichenko",
    "sourceUrl": "https://www.pexels.com/photo/women-cleaning-inside-of-a-house-6195274/"
  }
]

export const LIFESTYLE_PHOTOS = PHOTOS.filter(p => p.pool === 'lifestyle')
export const TEAM_PHOTOS = PHOTOS.filter(p => p.pool === 'team')

// Deterministic pick from pool based on a seed string (neighborhood slug).
function hash(seed: string): number {
  let h = 2166136261
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i)
    h = Math.imul(h, 16777619)
  }
  return Math.abs(h)
}

export function pickLifestylePhoto(seed: string): SitePhoto {
  return LIFESTYLE_PHOTOS[hash(seed) % LIFESTYLE_PHOTOS.length]
}

export function pickTeamPhoto(seed: string): SitePhoto {
  return TEAM_PHOTOS[hash(seed + 'team') % TEAM_PHOTOS.length]
}

export function pickPhotoByCategory(category: PhotoCategory, seed: string): SitePhoto {
  const matches = PHOTOS.filter(p => p.category === category)
  if (matches.length === 0) return pickLifestylePhoto(seed)
  return matches[hash(seed + category) % matches.length]
}
