import type { ResourceCategory } from './types'

export const resourcesIntro =
  'The following one hundred sites span the companies, publications, standards bodies, research institutions, and tools that are actively shaping AI search, agentic AI, and the answer-engine landscape described throughout this guide. They are organized by category rather than ranked. This list points to root domains and primary destinations rather than specific articles, since specific URLs move and expire — the organizations themselves are the stable reference point. As with anything on the fast-moving edge of this industry, verify current relevance before relying on any single one.'

export const resources: ResourceCategory[] = [
  {
    category: 'AI Labs & Foundation Model Companies',
    intro: 'The companies actually building the foundation models behind every answer engine and agent discussed throughout this guide. Their individual research and product blogs are the most direct, primary-source way to track how the retrieval and synthesis mechanics described in Part Two and Part Three are actually evolving.',
    items: [
      { name: 'OpenAI', url: 'https://openai.com', description: 'Creator of GPT models and ChatGPT, including ChatGPT Search.' },
      { name: 'Anthropic', url: 'https://anthropic.com', description: 'Creator of Claude and the Model Context Protocol standard for AI agents.' },
      { name: 'Google DeepMind', url: 'https://deepmind.google', description: 'Google\'s AI research lab, behind Gemini and much of the modeling powering AI Overviews.' },
      { name: 'Meta AI', url: 'https://ai.meta.com', description: 'Meta\'s AI research division, developer of the open-weight Llama model family.' },
      { name: 'Microsoft AI', url: 'https://microsoft.ai', description: 'Microsoft\'s AI initiatives, including Copilot across Bing and Microsoft 365.' },
      { name: 'Mistral AI', url: 'https://mistral.ai', description: 'European AI lab known for efficient, openly released language models.' },
      { name: 'Cohere', url: 'https://cohere.com', description: 'Enterprise-focused AI company specializing in retrieval, embeddings, and search infrastructure.' },
      { name: 'xAI', url: 'https://x.ai', description: 'Elon Musk\'s AI lab, developer of the Grok model family.' },
      { name: 'Together AI', url: 'https://www.together.ai', description: 'Cloud infrastructure and hosting platform for open-weight foundation models, widely used to run and fine-tune them at scale.' },
      { name: 'Hugging Face', url: 'https://huggingface.co', description: 'The largest open hub for sharing AI models, datasets, and tools.' },
    ],
  },
  {
    category: 'Search Engines & Answer Engines',
    intro: 'The actual products people type or speak questions into today. Some are classic search engines with a generative layer bolted on top; others, like Perplexity, were built answer-first from the ground up. Watching how each one presents citations is a fast, free way to study AEO mechanics firsthand.',
    items: [
      { name: 'Google Search', url: 'https://google.com', description: 'The dominant search engine, now serving AI Overviews above traditional results.' },
      { name: 'Bing', url: 'https://bing.com', description: 'Microsoft\'s search engine, deeply integrated with Copilot.' },
      { name: 'ChatGPT', url: 'https://chatgpt.com', description: 'OpenAI\'s assistant, with built-in live web search and citation.' },
      { name: 'Claude', url: 'https://claude.ai', description: 'Anthropic\'s assistant, with web search and source citation capability.' },
      { name: 'Perplexity', url: 'https://perplexity.ai', description: 'Cited-answer search engine built specifically around synthesis rather than ranked links.' },
      { name: 'DuckDuckGo', url: 'https://duckduckgo.com', description: 'Privacy-focused search engine with its own AI-assisted answer features.' },
      { name: 'Brave Search', url: 'https://search.brave.com', description: 'An independent search index with its own AI summary feature, not reliant on Google or Bing data.' },
      { name: 'You.com', url: 'https://you.com', description: 'An early entrant in AI-native, customizable search and answer experiences.' },
      { name: 'Kagi', url: 'https://kagi.com', description: 'A paid, ad-free search engine with integrated AI answer features.' },
      { name: 'Google AI Overviews Info', url: 'https://blog.google/products/search', description: 'Google\'s official blog for search product updates, including AI Overviews.' },
    ],
  },
  {
    category: 'SEO & AEO Industry Publications',
    intro: 'The trade press that tracks algorithm changes, AI-search rollouts, and practitioner strategy on a near-daily basis. The fastest way to stay current on a subject this guide has been clear will keep moving well past the day it was written.',
    items: [
      { name: 'Search Engine Land', url: 'https://searchengineland.com', description: 'One of the longest-running and most widely read SEO and search-marketing news publications.' },
      { name: 'Search Engine Journal', url: 'https://searchenginejournal.com', description: 'A major SEO and digital-marketing publication covering algorithm changes and AI search.' },
      { name: 'Search Engine Roundtable', url: 'https://seroundtable.com', description: 'Daily coverage of search-engine algorithm changes, forum discussion, and industry chatter.' },
      { name: 'Moz Blog', url: 'https://moz.com/blog', description: 'Long-standing SEO education resource from the makers of the Moz toolset.' },
      { name: 'Ahrefs Blog', url: 'https://ahrefs.com/blog', description: 'Data-driven SEO research and guides from the Ahrefs tool team.' },
      { name: 'Semrush Blog', url: 'https://semrush.com/blog', description: 'SEO, content, and AI-search strategy content from the Semrush platform.' },
      { name: 'Backlinko', url: 'https://backlinko.com', description: 'Brian Dean\'s widely cited SEO strategy and case-study blog.' },
      { name: 'Google Search Central Blog', url: 'https://developers.google.com/search/blog', description: 'Google\'s own official blog for webmasters and SEO practitioners.' },
      { name: 'Bing Webmaster Blog', url: 'https://blogs.bing.com/webmaster', description: 'Microsoft\'s official blog for site owners optimizing for Bing and Copilot.' },
      { name: 'Growth Memo', url: 'https://growthmemo.com', description: 'Kevin Indig\'s widely read newsletter on SEO strategy and AI search shifts.' },
    ],
  },
  {
    category: 'Standards, Protocols & Technical References',
    intro: 'The actual specifications behind the structured-data, crawling, and agent-communication concepts explained throughout this guide\'s glossary. Where to go when you need the precise technical definition rather than the plain-language explanation given here.',
    items: [
      { name: 'Schema.org', url: 'https://schema.org', description: 'The shared structured-data vocabulary used across the web for machine-readable markup.' },
      { name: 'W3C', url: 'https://w3.org', description: 'The World Wide Web Consortium, steward of core web standards.' },
      { name: 'WHATWG', url: 'https://whatwg.org', description: 'The standards body maintaining the HTML living standard used by every browser and crawler.' },
      { name: 'Google Search Central Documentation', url: 'https://developers.google.com/search/docs', description: 'Google\'s official technical documentation for how search crawling and indexing work.' },
      { name: 'llms.txt Specification', url: 'https://llmstxt.org', description: 'The proposal and specification site for the llms.txt standard described in this guide\'s glossary.' },
      { name: 'Model Context Protocol', url: 'https://modelcontextprotocol.io', description: 'Anthropic\'s open standard for connecting AI models and agents to real tools and data.' },
      { name: 'OpenAPI Initiative', url: 'https://openapis.org', description: 'The standards body behind the OpenAPI specification, widely used for describing machine-readable APIs.' },
      { name: 'IETF', url: 'https://ietf.org', description: 'The Internet Engineering Task Force, which standardizes many of the underlying internet protocols AI crawlers rely on.' },
      { name: 'Robots Exclusion Protocol (Google)', url: 'https://developers.google.com/search/docs/crawling-indexing/robots/intro', description: 'Google\'s documentation on the robots.txt standard governing crawler access.' },
      { name: 'JSON-LD', url: 'https://json-ld.org', description: 'The official site for the JSON-LD structured-data format used to implement Schema.org markup.' },
    ],
  },
  {
    category: 'Academic & Research Institutions',
    intro: 'The primary research literature underneath every product and news headline in this list. If you want to understand transformers, RAG, or agent architecture at the source rather than through a marketing summary, this is where the original papers live.',
    items: [
      { name: 'arXiv', url: 'https://arxiv.org', description: 'The primary open repository where most cutting-edge AI and machine learning research is first published.' },
      { name: 'Papers With Code', url: 'https://paperswithcode.com', description: 'A resource pairing AI research papers with their open-source implementations.' },
      { name: 'Stanford HAI', url: 'https://hai.stanford.edu', description: 'Stanford\'s Human-Centered Artificial Intelligence institute, publisher of the widely cited annual AI Index report.' },
      { name: 'MIT CSAIL', url: 'https://csail.mit.edu', description: 'MIT\'s Computer Science and Artificial Intelligence Laboratory, a leading source of foundational AI research.' },
      { name: 'Google Research', url: 'https://research.google', description: 'Google\'s public research publications, including work underlying BERT, MUM, and search ranking.' },
      { name: 'OpenAI Research', url: 'https://openai.com/research', description: 'OpenAI\'s published research papers and technical reports.' },
      { name: 'Anthropic Research', url: 'https://anthropic.com/research', description: 'Anthropic\'s published research on model capability, safety, and interpretability.' },
      { name: 'ACL Anthology', url: 'https://aclanthology.org', description: 'The full archive of published research from the Association for Computational Linguistics.' },
      { name: 'NeurIPS', url: 'https://neurips.cc', description: 'One of the largest annual machine learning research conferences.' },
      { name: 'Allen Institute for AI (AI2)', url: 'https://allenai.org', description: 'A nonprofit AI research institute known for open models and NLP research.' },
    ],
  },
  {
    category: 'Agentic AI & Commerce Infrastructure',
    intro: 'The frameworks, platforms, and infrastructure companies actively building the agentic and agent-to-agent commerce layer described in Part Four — the closest thing available today to watching the next five years get built in real time.',
    items: [
      { name: 'LangChain', url: 'https://langchain.com', description: 'A widely used open-source framework for building applications on top of language models, including AI agents.' },
      { name: 'LlamaIndex', url: 'https://llamaindex.ai', description: 'A data-framework for connecting language models to external data via retrieval, core to RAG applications.' },
      { name: 'CrewAI', url: 'https://crewai.com', description: 'A framework for orchestrating multiple collaborating AI agents on complex tasks.' },
      { name: 'AutoGPT (GitHub)', url: 'https://github.com/Significant-Gravitas/AutoGPT', description: 'One of the earliest widely known autonomous AI agent projects.' },
      { name: 'Zapier', url: 'https://zapier.com', description: 'Automation platform increasingly building AI-agent-driven workflows connecting business tools.' },
      { name: 'Stripe', url: 'https://stripe.com', description: 'Payments infrastructure company building toward AI-agent-initiated commerce and checkout flows.' },
      { name: 'Shopify', url: 'https://shopify.com', description: 'E-commerce platform investing in AI-agent and AI-shopping-assistant compatibility for merchants.' },
      { name: 'Model Context Protocol Servers (GitHub)', url: 'https://github.com/modelcontextprotocol', description: 'The official repository of reference implementations for the Model Context Protocol.' },
      { name: 'Salesforce Agentforce', url: 'https://salesforce.com/agentforce', description: 'Salesforce\'s platform for building autonomous AI agents inside business workflows.' },
      { name: 'UiPath', url: 'https://www.uipath.com', description: 'Enterprise automation platform building agentic AI orchestration into business process workflows.' },
    ],
  },
  {
    category: 'AEO / AI-Visibility Tools & Analytics',
    intro: 'The practical toolset for actually running the Part Five playbook — measuring technical crawlability, content quality, and the emerging "share of answer" metric described in Part Two, rather than just reading about the theory.',
    items: [
      { name: 'Google Search Console', url: 'https://search.google.com/search-console', description: 'Google\'s free tool for monitoring a site\'s search performance, indexing status, and technical issues.' },
      { name: 'Google Analytics', url: 'https://analytics.google.com', description: 'The standard web analytics platform for measuring traffic, including what remains after AI-answer zero-click behavior.' },
      { name: 'Bing Webmaster Tools', url: 'https://bing.com/webmasters', description: 'Microsoft\'s equivalent monitoring tool for Bing and Copilot search performance.' },
      { name: 'Ahrefs', url: 'https://ahrefs.com', description: 'A major SEO tool suite for backlink analysis, keyword research, and site auditing.' },
      { name: 'Semrush', url: 'https://semrush.com', description: 'A comprehensive SEO and content marketing platform, increasingly adding AI-search-visibility tracking.' },
      { name: 'Moz', url: 'https://moz.com', description: 'A long-standing SEO tool suite and the originator of the Domain Authority metric.' },
      { name: 'Clearscope', url: 'https://clearscope.io', description: 'A content-optimization tool focused on topical depth and semantic relevance.' },
      { name: 'MarketMuse', url: 'https://marketmuse.com', description: 'An AI-assisted content planning and topical-authority research platform.' },
      { name: 'Surfer SEO', url: 'https://surferseo.com', description: 'A content-optimization tool that analyzes top-ranking pages to guide on-page structure.' },
      { name: 'Screaming Frog SEO Spider', url: 'https://screamingfrog.co.uk/seo-spider', description: 'A widely used technical site-crawling and auditing tool for diagnosing indexing issues.' },
    ],
  },
  {
    category: 'General AI & Technology News',
    intro: 'Broader technology journalism covering AI\'s business, cultural, and competitive impact — useful context beyond the narrower SEO trade press for understanding where the industry as a whole believes this is headed.',
    items: [
      { name: 'TechCrunch', url: 'https://techcrunch.com', description: 'Technology news outlet with dedicated, extensive AI industry coverage.' },
      { name: 'The Verge', url: 'https://theverge.com', description: 'Technology and culture publication covering AI products and platform shifts.' },
      { name: 'Wired', url: 'https://wired.com', description: 'Long-running technology publication with in-depth AI and search-industry reporting.' },
      { name: 'MIT Technology Review', url: 'https://technologyreview.com', description: 'A research-grounded technology publication with rigorous AI coverage.' },
      { name: 'Ars Technica', url: 'https://arstechnica.com', description: 'Technical, detail-oriented technology news, including deep AI and infrastructure coverage.' },
      { name: 'Stratechery', url: 'https://stratechery.com', description: 'Ben Thompson\'s widely read strategic analysis of technology and platform economics, including AI\'s effect on search.' },
      { name: 'Import AI', url: 'https://jack-clark.net', description: 'Jack Clark\'s widely followed weekly newsletter on AI research and policy developments.' },
      { name: 'Axios AI+', url: 'https://axios.com/ai', description: 'Axios\'s dedicated AI industry news vertical.' },
      { name: 'VentureBeat AI', url: 'https://venturebeat.com/category/ai', description: 'Business-and-industry-focused AI news coverage.' },
      { name: 'The Information', url: 'https://theinformation.com', description: 'Subscription tech-industry publication known for deep AI-company reporting.' },
    ],
  },
  {
    category: 'Venture Capital & Industry Analysis',
    intro: 'The investors and research firms placing large financial bets on where this all goes next. Their public analysis is a useful, if never neutral, signal of where serious capital expects agentic AI and answer engines to head over the next five years.',
    items: [
      { name: 'a16z (Andreessen Horowitz)', url: 'https://a16z.com', description: 'Venture capital firm publishing extensive analysis on AI, agents, and the future of search.' },
      { name: 'Sequoia Capital', url: 'https://sequoiacap.com', description: 'Venture capital firm with widely circulated essays on AI industry trends.' },
      { name: 'Bessemer Venture Partners', url: 'https://bvp.com', description: 'Venture firm publishing regular research on AI and SaaS market trends.' },
      { name: 'CB Insights', url: 'https://cbinsights.com', description: 'Market intelligence platform tracking AI industry funding, trends, and competitive landscapes.' },
      { name: 'Gartner', url: 'https://gartner.com', description: 'Research and advisory firm publishing widely cited technology and AI adoption forecasts.' },
      { name: 'Forrester', url: 'https://forrester.com', description: 'Research firm covering enterprise technology trends, including AI search and agentic commerce.' },
      { name: 'Boston Consulting Group', url: 'https://www.bcg.com', description: 'Consulting firm publishing widely cited research on AI\'s business and organizational impact.' },
      { name: 'PwC AI', url: 'https://pwc.com/gx/en/issues/artificial-intelligence.html', description: 'Consulting firm research on enterprise AI adoption and economic impact.' },
      { name: 'World Economic Forum AI', url: 'https://www.weforum.org', description: 'Global policy forum\'s coverage of AI\'s economic and societal impact.' },
      { name: 'OECD.AI', url: 'https://oecd.ai', description: 'The OECD\'s policy observatory tracking global AI governance and regulation.' },
    ],
  },
  {
    category: 'Reference, Community & Discussion',
    intro: 'Where the actual, unfiltered practitioner conversation happens — including, not incidentally, some of the exact corroborating platforms discussed in Part Two and Part Three that AI systems themselves increasingly draw on for real-world corroboration.',
    items: [
      { name: 'Wikipedia', url: 'https://wikipedia.org', description: 'The open encyclopedia frequently used by AI systems as a high-trust corroborating source.' },
      { name: 'Hacker News', url: 'https://news.ycombinator.com', description: 'A technology-focused discussion community where AI search and agent developments are debated in depth.' },
      { name: 'Reddit r/SEO', url: 'https://reddit.com/r/SEO', description: 'An active community of SEO practitioners discussing tactics, algorithm changes, and AI-search shifts.' },
      { name: 'Reddit r/artificial', url: 'https://reddit.com/r/artificial', description: 'A general-audience community discussion forum for AI news and developments.' },
      { name: 'Reddit r/LocalLLaMA', url: 'https://reddit.com/r/LocalLLaMA', description: 'A technically detailed community focused on open-source and self-hosted language models.' },
      { name: 'Product Hunt', url: 'https://producthunt.com', description: 'A launch platform where new AI search, AEO, and agent tools are frequently first announced.' },
      { name: 'GitHub', url: 'https://github.com', description: 'The primary hub for open-source AI, RAG, and agent-framework code referenced throughout this guide.' },
      { name: 'Stack Overflow', url: 'https://stackoverflow.com', description: 'The long-standing developer Q&A community, itself a heavily cited source in AI coding-assistant answers.' },
      { name: 'Indie Hackers', url: 'https://indiehackers.com', description: 'A community of independent founders discussing organic growth strategy in the AI-search era.' },
      { name: 'Search Engine Roundtable Forum Digest', url: 'https://seroundtable.com/category/google', description: 'Ongoing coverage specifically tracking Google\'s algorithm and AI-search changes.' },
    ],
  },
]
