// @ts-nocheck
/* State-specific data for DSCR loan content */

export interface StateInfo {
  propertyTaxRate: string;
  incomeTax: string;
  landlordFriendly: "Very" | "Moderate" | "Tenant-Friendly";
  foreclosureType: "Non-Judicial" | "Judicial" | "Both";
  insuranceNote: string;
  strClimate: string;
  dscrNote: string;
  tip: string;
}

const stateData: Record<string, StateInfo> = {
  AL: { propertyTaxRate: "0.40%", incomeTax: "2–5%", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "Affordable. Gulf Coast properties need wind/hail coverage.", strClimate: "Growing in Gulf Shores and Birmingham. Few restrictions.", dscrNote: "Low property taxes and affordable prices create strong DSCR ratios. Great for cash-flow investors.", tip: "Alabama's low property taxes are a DSCR cheat code. A $200K rental here might have $67/month in taxes vs. $417 in Texas. That's a 0.15+ DSCR boost." },
  AK: { propertyTaxRate: "1.07%", incomeTax: "None", landlordFriendly: "Moderate", foreclosureType: "Non-Judicial", insuranceNote: "Higher due to remote location and weather.", strClimate: "Limited market. Seasonal tourism in some areas.", dscrNote: "No state income tax is a plus. Limited rental market makes DSCR qualification harder in most areas.", tip: "Alaska's no income tax is great for investors, but the rental market is thin outside Anchorage. Make sure rent comps are solid before committing." },
  AZ: { propertyTaxRate: "0.62%", incomeTax: "2.5% flat", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "Low premiums. No hurricane or flood risk in most areas.", strClimate: "Phoenix and Scottsdale have strong STR markets. Some HOAs restrict.", dscrNote: "Low taxes, low insurance, and strong rents make Arizona one of the best DSCR states. Phoenix metro is a top-5 DSCR market.", tip: "Scottsdale vacation rentals can hit 1.5+ DSCR with STR income. But verify HOA rules — many Scottsdale HOAs ban short-term rentals entirely." },
  AR: { propertyTaxRate: "0.63%", incomeTax: "2–4.7%", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "Affordable. Tornado coverage recommended.", strClimate: "Growing slowly. Few restrictions.", dscrNote: "Very affordable market with strong rent-to-price ratios. Under-the-radar DSCR state.", tip: "Northwest Arkansas (Fayetteville, Bentonville) is booming thanks to Walmart HQ and University of Arkansas. Look there first for DSCR deals." },
  CA: { propertyTaxRate: "0.75%", incomeTax: "1–13.3%", landlordFriendly: "Tenant-Friendly", foreclosureType: "Non-Judicial", insuranceNote: "High. Wildfire zones can be extremely expensive. Some areas uninsurable.", strClimate: "Heavily regulated. Many cities ban or cap STRs. Check local ordinances.", dscrNote: "High home prices make DSCR qualification difficult. Most properties come in below 1.0 DSCR. Investors often need 30%+ down to make numbers work.", tip: "California is tough for DSCR — $800K homes renting for $3,500 won't hit 1.0 DSCR. If you're investing here, target inland markets (Riverside, Fresno, Bakersfield) where rent-to-price ratios are better." },
  CO: { propertyTaxRate: "0.51%", incomeTax: "4.4% flat", landlordFriendly: "Moderate", foreclosureType: "Both", insuranceNote: "Moderate. Hail and wildfire coverage important in some areas.", strClimate: "Strong in mountain/ski towns. Denver regulates STRs.", dscrNote: "Denver metro prices have risen faster than rents, making DSCR tighter. Mountain towns with STR income can hit excellent ratios.", tip: "Colorado mountain towns (Breckenridge, Steamboat) can generate $5K+/month in STR income. That's where the DSCR ratios shine — not in Denver's high-priced SFR market." },
  CT: { propertyTaxRate: "2.15%", incomeTax: "3–6.99%", landlordFriendly: "Tenant-Friendly", foreclosureType: "Judicial", insuranceNote: "Moderate to high. Coastal flood zones add cost.", strClimate: "Limited. Some demand near NYC commuter areas.", dscrNote: "Very high property taxes crush DSCR ratios. Investors need strong rents to overcome the tax burden. Multi-family in cities like Hartford and New Haven can work.", tip: "Connecticut's 2%+ property tax rate is a DSCR killer. On a $300K property, that's $500/month in taxes alone. Focus on multi-family where combined rents offset the tax hit." },
  DE: { propertyTaxRate: "0.57%", incomeTax: "2.2–6.6%", landlordFriendly: "Moderate", foreclosureType: "Judicial", insuranceNote: "Moderate. Coastal properties need flood insurance.", strClimate: "Beach areas (Rehoboth, Lewes) have STR demand.", dscrNote: "Small market but low property taxes help DSCR. Beach town STRs can be profitable.", tip: "Delaware beach towns are an under-the-radar STR play. Lower prices than Jersey Shore or Hamptons, good seasonal demand, and no sales tax attracts visitors." },
  FL: { propertyTaxRate: "0.89%", incomeTax: "None", landlordFriendly: "Very", foreclosureType: "Judicial", insuranceNote: "HIGH. Hurricane and flood insurance can be $300–$800/month. Factor this into DSCR carefully.", strClimate: "Massive STR market. Orlando, Miami, Tampa, Keys are top markets. Some cities regulate.", dscrNote: "No state income tax and strong rents make Florida a top DSCR state — BUT insurance costs are the wildcard. Always get an insurance quote before running your DSCR.", tip: "Florida's insurance crisis is real. We've seen $400K homes with $6,000+/year insurance bills — that's $500/month eating into your DSCR. Get an insurance quote BEFORE you make an offer, not after." },
  GA: { propertyTaxRate: "0.92%", incomeTax: "1–5.49%", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "Affordable in metro Atlanta. Coastal areas need wind coverage.", strClimate: "Atlanta is mostly long-term. Savannah has strong STR demand.", dscrNote: "Atlanta metro is one of the best DSCR markets in the country. Affordable homes, strong rents, landlord-friendly laws, and non-judicial foreclosure.", tip: "Atlanta's south side and east side suburbs (College Park, East Point, Decatur) offer $200K–$300K homes renting for $1,800–$2,200. Easy 1.25+ DSCR territory." },
  HI: { propertyTaxRate: "0.29%", incomeTax: "1.4–11%", landlordFriendly: "Tenant-Friendly", foreclosureType: "Both", insuranceNote: "High. Hurricane and lava zone coverage needed in some areas.", strClimate: "Strong vacation rental demand. Heavily regulated on some islands.", dscrNote: "Lowest property taxes in the US but extremely high home prices. STR income can offset, but long-term rental DSCR is very challenging.", tip: "Hawaii's 0.29% property tax rate is the lowest in America — but when homes cost $800K+, it doesn't matter much. STR income is the only way to make DSCR work here." },
  ID: { propertyTaxRate: "0.63%", incomeTax: "5.8% flat", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "Low premiums. Minimal natural disaster risk.", strClimate: "Boise metro growing. Sun Valley/McCall have STR demand.", dscrNote: "Boise home prices have risen significantly, but rents have kept pace. Still a workable DSCR market with decent fundamentals.", tip: "Boise's growth has pushed prices up, but Meridian and Nampa still offer sub-$350K homes with good rental demand. That's where the DSCR sweet spot is." },
  IL: { propertyTaxRate: "2.23%", incomeTax: "4.95% flat", landlordFriendly: "Tenant-Friendly", foreclosureType: "Judicial", insuranceNote: "Moderate. Chicago requires specific landlord insurance.", strClimate: "Chicago regulates STRs. Downstate has fewer restrictions.", dscrNote: "Illinois has the second-highest property taxes in the US. This is a significant DSCR headwind. Chicago multi-family can still work thanks to strong rents.", tip: "Illinois' 2.2% property taxes mean a $250K home costs $458/month in taxes. That's brutal for DSCR. The move here is multi-family in Chicago where combined unit rents overcome the tax burden." },
  IN: { propertyTaxRate: "0.84%", incomeTax: "3.05% flat", landlordFriendly: "Very", foreclosureType: "Judicial", insuranceNote: "Low premiums. Tornado coverage recommended.", strClimate: "Indianapolis has growing STR market. Few state-level restrictions.", dscrNote: "Indianapolis is a DSCR goldmine. Low prices, strong rents, low taxes, and landlord-friendly laws. One of the easiest markets to hit 1.25+ DSCR.", tip: "Indianapolis is arguably the #1 DSCR market in America for cash-flow investors. $150K–$250K homes renting for $1,400–$1,900. Do the math — those are easy 1.3+ DSCRs all day." },
  NV: { propertyTaxRate: "0.55%", incomeTax: "None", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "Low premiums. No hurricane, earthquake, or flood risk.", strClimate: "Las Vegas and Henderson have massive STR markets. Licensed and regulated.", dscrNote: "No income tax, low property taxes, low insurance, and strong STR income make Nevada excellent for DSCR. Las Vegas is a top-10 DSCR market.", tip: "Las Vegas vacation rentals near the Strip can generate $4K–$6K/month. Even with a $400K purchase, that's a 1.4+ DSCR. Just make sure the property is in an STR-licensed zone." },
  NJ: { propertyTaxRate: "2.47%", incomeTax: "1.4–10.75%", landlordFriendly: "Tenant-Friendly", foreclosureType: "Judicial", insuranceNote: "High. Flood insurance required in many areas.", strClimate: "Shore towns have strong summer STR. Otherwise limited.", dscrNote: "Highest property taxes in the US are a massive DSCR obstacle. Multi-family in cities like Newark and Jersey City can work if rents are high enough.", tip: "New Jersey's 2.5% property tax rate is the highest in America. On a $400K property, that's $833/month in taxes. You need very strong rents to overcome that and hit 1.0 DSCR." },
  NY: { propertyTaxRate: "1.72%", incomeTax: "4–10.9%", landlordFriendly: "Tenant-Friendly", foreclosureType: "Judicial", insuranceNote: "Moderate to high. NYC requires specific coverage.", strClimate: "NYC essentially bans STRs under 30 days. Upstate is more open.", dscrNote: "NYC is extremely difficult for DSCR due to high prices and rent control. Upstate markets (Buffalo, Rochester, Syracuse) offer much better DSCR potential.", tip: "Forget NYC for DSCR — the prices are insane and rent control caps your upside. Look upstate: Buffalo and Rochester have $100K–$200K homes renting for $1,200–$1,600. Those DSCRs crush anything in Manhattan." },
  TX: { propertyTaxRate: "1.80%", incomeTax: "None", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "Moderate. Hail, wind, and flood coverage important in some areas.", strClimate: "Strong in Austin, San Antonio, and Gulf Coast. Most cities allow STRs.", dscrNote: "No income tax and massive rental demand make Texas a DSCR powerhouse — but 1.8% property taxes are the tradeoff. Houston and San Antonio offer the best rent-to-price ratios.", tip: "Texas has no income tax but high property taxes (1.8%). The hack? Buy in areas with lower tax rates within the state — some Houston suburbs are at 1.5% while Austin can hit 2.2%. That difference is $100+/month on a typical rental." },
  TN: { propertyTaxRate: "0.66%", incomeTax: "None", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "Affordable. Standard coverage is sufficient.", strClimate: "Nashville and Gatlinburg/Pigeon Forge are top STR markets. Nashville regulates permits.", dscrNote: "No income tax, low property taxes, landlord-friendly — Tennessee checks every box for DSCR investors. Nashville and Memphis are both excellent markets.", tip: "Gatlinburg/Pigeon Forge vacation rentals are some of the highest-performing STR DSCR deals in the country. $350K cabins generating $4K–$5K/month in STR income. That's a 1.5+ DSCR easy." },
  DC: { propertyTaxRate: "0.56%", incomeTax: "4–10.75%", landlordFriendly: "Tenant-Friendly", foreclosureType: "Non-Judicial", insuranceNote: "Moderate. Standard urban coverage.", strClimate: "Heavily regulated. 90-day annual cap on STRs. License required.", dscrNote: "Extremely high home prices relative to rents make DSCR challenging. Multi-family can work in emerging neighborhoods. STR restrictions limit Airbnb strategy.", tip: "DC is a tough DSCR market — $600K condos renting for $2,800 won't hit 1.0. If you invest here, look at multi-family in NE and SE neighborhoods where price-to-rent ratios are more favorable." },
  IA: { propertyTaxRate: "1.57%", incomeTax: "4.4–6%", landlordFriendly: "Moderate", foreclosureType: "Both", insuranceNote: "Affordable. Tornado and hail coverage recommended.", strClimate: "Limited demand outside college towns. Few restrictions.", dscrNote: "Affordable prices and decent rents but higher property taxes eat into DSCR. Des Moines and Cedar Rapids offer the best rent-to-price ratios.", tip: "Iowa's college towns (Iowa City, Ames) have consistent rental demand from students. But watch the property taxes — at 1.6%, they add $200+/month on a typical rental." },
  KS: { propertyTaxRate: "1.41%", incomeTax: "3.1–5.7%", landlordFriendly: "Very", foreclosureType: "Judicial", insuranceNote: "Moderate. Tornado coverage essential in western Kansas.", strClimate: "Limited STR market. No major restrictions.", dscrNote: "Affordable market with decent rents. Kansas City metro (KS side) offers the strongest DSCR opportunities. Wichita is also investable.", tip: "The Kansas side of KC metro (Overland Park, Olathe) offers similar rents to the Missouri side but different tax structures. Compare both before choosing." },
  KY: { propertyTaxRate: "0.86%", incomeTax: "4% flat", landlordFriendly: "Moderate", foreclosureType: "Judicial", insuranceNote: "Affordable. Standard coverage sufficient.", strClimate: "Louisville has growing STR market. Bourbon trail tourism helps.", dscrNote: "Louisville and Lexington are the main DSCR markets. Affordable prices with decent rents create workable ratios. Judicial foreclosure is the main drawback.", tip: "Louisville's Germantown and Highlands neighborhoods have strong rental demand and affordable entry points. The bourbon tourism angle is growing for STR investors too." },
  LA: { propertyTaxRate: "0.55%", incomeTax: "1.85–4.25%", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "HIGH. Hurricane, flood, and wind insurance in coastal areas can be very expensive. New Orleans flood zones are especially costly.", strClimate: "New Orleans has massive STR demand but heavily regulated. License required, some zones banned.", dscrNote: "Very low property taxes are a DSCR advantage, but insurance costs in coastal areas can wipe it out. Inland markets like Baton Rouge and Shreveport have much lower insurance.", tip: "New Orleans STR income can hit $4K–$6K/month on a $300K property — incredible DSCR. But insurance can be $400+/month and STR regulations are strict. Get licensed first, get insurance quotes second, THEN run your DSCR." },
  ME: { propertyTaxRate: "1.36%", incomeTax: "5.8–7.15%", landlordFriendly: "Moderate", foreclosureType: "Judicial", insuranceNote: "Moderate. Coastal properties need flood coverage.", strClimate: "Strong vacation rental demand in coastal towns (Portland, Bar Harbor, Kennebunkport). Growing year-round.", dscrNote: "High property taxes and high income tax are headwinds. But Maine's coastal STR market generates strong seasonal income that can offset the costs.", tip: "Maine coastal STRs (Old Orchard Beach, Kennebunkport) command $300–$500/night in summer. If your property does well June–September, the annual DSCR can still be strong despite the off-season." },
  MD: { propertyTaxRate: "1.07%", incomeTax: "2–5.75%", landlordFriendly: "Tenant-Friendly", foreclosureType: "Both", insuranceNote: "Moderate. Baltimore and coastal areas need flood coverage.", strClimate: "Baltimore has some STR demand. Ocean City is a strong vacation market.", dscrNote: "Maryland has moderate property taxes but tenant-friendly laws. Baltimore multi-family offers the best DSCR potential. Ocean City STRs can be very profitable.", tip: "Baltimore row houses in the $100K–$200K range renting for $1,200–$1,500 deliver strong DSCR ratios. The entry point is low but do your due diligence on neighborhood quality." },
  MA: { propertyTaxRate: "1.23%", incomeTax: "5% flat", landlordFriendly: "Tenant-Friendly", foreclosureType: "Non-Judicial", insuranceNote: "Moderate to high. Coastal flood coverage needed.", strClimate: "Boston heavily regulates STRs. Cape Cod and island markets have strong seasonal demand.", dscrNote: "High home prices and tenant-friendly laws make Massachusetts challenging for DSCR. Worcester and Springfield offer better price-to-rent ratios than Boston metro.", tip: "Don't try to DSCR a $700K Boston condo. Look at Worcester, Springfield, or Lowell — $200K–$350K multi-family with combined rents that actually hit 1.25+ DSCR." },
  MI: { propertyTaxRate: "1.54%", incomeTax: "4.25% flat", landlordFriendly: "Moderate", foreclosureType: "Non-Judicial", insuranceNote: "Affordable in most areas. Detroit has higher rates.", strClimate: "Northern Michigan and lake areas have strong STR demand. Detroit is long-term rental.", dscrNote: "Detroit and Grand Rapids are the main DSCR markets. Very affordable entry points in Detroit but high property taxes offset some of the benefit.", tip: "Detroit's $80K–$150K homes renting for $900–$1,300 look great on paper, but factor in the 1.5% property tax AND higher insurance. Run every deal through the calculator — some pencil out, many don't." },
  MN: { propertyTaxRate: "1.12%", incomeTax: "5.35–9.85%", landlordFriendly: "Moderate", foreclosureType: "Non-Judicial", insuranceNote: "Moderate. Standard coverage sufficient.", strClimate: "Minneapolis–St. Paul has moderate STR demand. Lake country has seasonal rentals.", dscrNote: "Moderate property taxes and high income tax. Minneapolis-St. Paul has stable rental demand but prices have risen. Rochester (Mayo Clinic) is an overlooked gem.", tip: "Rochester, MN has unusually stable rental demand thanks to the Mayo Clinic — medical professionals always need housing. It's one of the most recession-proof rental markets in the Midwest." },
  MS: { propertyTaxRate: "0.81%", incomeTax: "0–5%", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "Moderate. Gulf Coast needs hurricane and flood coverage.", strClimate: "Gulf Coast (Biloxi, Gulfport) has some STR demand. Otherwise limited.", dscrNote: "Very affordable market with low taxes and landlord-friendly laws. DSCR ratios can be excellent on paper, but rental demand is thin outside major cities.", tip: "Mississippi is ultra-affordable but make sure rental demand exists in your specific area. Jackson and the Gulf Coast have demand. Rural areas may not — verify rent comps carefully." },
  MO: { propertyTaxRate: "0.97%", incomeTax: "2–4.95%", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "Moderate. Tornado coverage recommended.", strClimate: "Branson has strong STR tourism. Kansas City and St. Louis are long-term rental markets.", dscrNote: "Kansas City and St. Louis offer strong DSCR fundamentals — affordable prices, decent rents, and landlord-friendly laws. Both cities have active investor communities.", tip: "Kansas City's Midtown and Westport areas have excellent rent-to-price ratios for DSCR. St. Louis is even cheaper entry but do your homework on neighborhood quality — it matters more here than most cities." },
  MT: { propertyTaxRate: "0.83%", incomeTax: "4.7–6.75%", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "Low premiums in most areas. Wildfire coverage needed near forests.", strClimate: "Strong STR market near Glacier and Yellowstone. Big Sky and Whitefish are premium.", dscrNote: "Montana's tourism-driven STR market can produce excellent DSCR ratios. Long-term rental DSCR is harder due to limited urban rental demand.", tip: "A cabin near Glacier National Park can gross $50K–$80K/year in STR income. On a $400K property, that's a potential 1.5+ DSCR. Montana STR is one of the best-kept secrets in the DSCR world." },
  NE: { propertyTaxRate: "1.73%", incomeTax: "2.46–6.64%", landlordFriendly: "Very", foreclosureType: "Judicial", insuranceNote: "Affordable. Tornado coverage recommended.", strClimate: "Limited STR demand. Omaha is a long-term rental market.", dscrNote: "Omaha is the primary DSCR market. Affordable prices and strong rents, but high property taxes (1.7%) offset some of the benefit.", tip: "Omaha has Warren Buffett and a surprisingly strong rental market. The Berkshire Hathaway effect keeps the economy stable. Just watch those property taxes — they're higher than you'd expect for the Midwest." },
  NH: { propertyTaxRate: "2.18%", incomeTax: "None", landlordFriendly: "Moderate", foreclosureType: "Non-Judicial", insuranceNote: "Moderate. Standard coverage.", strClimate: "White Mountains and Lakes Region have strong seasonal STR demand.", dscrNote: "No income tax is great but the second-highest property taxes in the US are a serious DSCR headwind. STR in tourist areas may be the best play.", tip: "New Hampshire's 2.2% property tax is brutal for DSCR — but there's no income tax and no sales tax. The STR play in the White Mountains or Lakes Region can work because seasonal tourism income is strong." },
  NM: { propertyTaxRate: "0.80%", incomeTax: "1.7–5.9%", landlordFriendly: "Moderate", foreclosureType: "Judicial", insuranceNote: "Low premiums. Minimal natural disaster risk.", strClimate: "Santa Fe and Albuquerque have moderate STR demand.", dscrNote: "Affordable market with low property taxes. Albuquerque offers the best DSCR potential. Santa Fe is a premium STR market.", tip: "Albuquerque is one of the most underrated DSCR markets — sub-$250K homes renting for $1,400–$1,700 with very low property taxes. Easy 1.25+ DSCRs." },
  NC: { propertyTaxRate: "0.84%", incomeTax: "4.5% flat", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "Moderate. Coastal areas need hurricane and flood coverage.", strClimate: "Strong STR market in Outer Banks, Asheville, and mountain towns. Charlotte and Raleigh are long-term.", dscrNote: "Charlotte and Raleigh are top-tier DSCR markets — strong population growth, landlord-friendly laws, moderate taxes, and rising rents. Asheville STRs also perform well.", tip: "Charlotte's suburbs (Gastonia, Concord, Kannapolis) are the DSCR sweet spot — $200K–$300K homes with $1,600–$2,000 rents. Lower prices than Charlotte proper, same rental demand." },
  ND: { propertyTaxRate: "0.98%", incomeTax: "0–2.5%", landlordFriendly: "Very", foreclosureType: "Judicial", insuranceNote: "Affordable. Standard coverage.", strClimate: "Very limited STR market.", dscrNote: "Small rental market centered on Fargo. Very affordable but limited demand outside the main cities.", tip: "Fargo is the only real DSCR play in North Dakota. The oil boom brought people, but the market is small. Stick to Fargo and verify rent demand." },
  OH: { propertyTaxRate: "1.56%", incomeTax: "0–3.75%", landlordFriendly: "Moderate", foreclosureType: "Judicial", insuranceNote: "Affordable. Standard coverage.", strClimate: "Limited STR outside tourist areas. Cleveland and Columbus are long-term rental markets.", dscrNote: "Ohio has high property taxes but very affordable home prices. Columbus is the strongest DSCR market — growing city with strong employer base. Cleveland and Cincinnati are cash-flow plays.", tip: "Columbus is Ohio's growth engine — Ohio State, tech jobs, healthcare. It's the only Ohio city with both population growth AND rising rents. Cleveland is cheaper entry but flat growth." },
  OK: { propertyTaxRate: "0.90%", incomeTax: "0.25–4.75%", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "Moderate. Tornado and hail coverage essential.", strClimate: "Limited STR demand. Long-term rental focused.", dscrNote: "Very affordable market with low taxes and landlord-friendly laws. Oklahoma City and Tulsa both offer strong DSCR fundamentals.", tip: "Oklahoma City and Tulsa are sleeper DSCR markets. $150K–$200K homes renting for $1,200–$1,500. The math is simple and the laws are on your side." },
  OR: { propertyTaxRate: "0.97%", incomeTax: "4.75–9.9%", landlordFriendly: "Tenant-Friendly", foreclosureType: "Both", insuranceNote: "Moderate. Earthquake coverage recommended in some areas.", strClimate: "Portland regulates STRs. Coastal and mountain areas have seasonal demand.", dscrNote: "Oregon's high income tax and tenant-friendly laws (statewide rent control) make it challenging. Portland prices have softened, which may create DSCR opportunities.", tip: "Oregon has statewide rent control — rents can only increase 7% + CPI per year. This caps your upside. Factor that into your long-term DSCR projections." },
  PA: { propertyTaxRate: "1.58%", incomeTax: "3.07% flat", landlordFriendly: "Moderate", foreclosureType: "Judicial", insuranceNote: "Moderate. Pittsburgh and Philadelphia have standard rates.", strClimate: "Philadelphia and Pocono Mountains have STR demand. Pittsburgh is long-term.", dscrNote: "High property taxes are the main DSCR obstacle. Philadelphia multi-family and Pittsburgh SFR offer the best rent-to-price ratios.", tip: "Pittsburgh is one of the most affordable big cities in America. $150K–$250K homes with $1,200–$1,600 rents. The property taxes hurt but the entry point is so low that the DSCR still works." },
  RI: { propertyTaxRate: "1.63%", incomeTax: "3.75–5.99%", landlordFriendly: "Tenant-Friendly", foreclosureType: "Non-Judicial", insuranceNote: "Moderate. Coastal flood coverage needed.", strClimate: "Newport and coastal areas have STR demand.", dscrNote: "Small state with high taxes and tenant-friendly laws. Providence offers the best DSCR potential. Newport STRs can work seasonally.", tip: "Rhode Island is small but Providence has an underrated rental market — Brown University and RISD keep demand steady. Just watch the 1.6% property tax." },
  SC: { propertyTaxRate: "0.57%", incomeTax: "0–6.5%", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "Moderate. Coastal areas need hurricane and flood coverage.", strClimate: "Strong STR market in Charleston, Myrtle Beach, and Hilton Head.", dscrNote: "Low property taxes, landlord-friendly laws, and strong tourism make South Carolina excellent for DSCR. Charleston and Myrtle Beach are top-tier markets for both LTR and STR.", tip: "South Carolina's 0.57% property tax rate is one of the lowest in the country. Combined with Myrtle Beach STR income, you can hit 1.5+ DSCRs that most states can't touch." },
  SD: { propertyTaxRate: "1.22%", incomeTax: "None", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "Affordable. Standard coverage.", strClimate: "Black Hills (Rapid City, Deadwood) have some STR demand.", dscrNote: "No income tax and landlord-friendly. Sioux Falls is the main rental market with steady growth.", tip: "Sioux Falls is growing fast and has no state income tax. It's a small market but the fundamentals are solid for DSCR — just make sure you verify rent comps in your specific area." },
  UT: { propertyTaxRate: "0.58%", incomeTax: "4.65% flat", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "Low premiums. Minimal natural disaster risk.", strClimate: "Park City and ski areas have strong STR demand. Salt Lake regulates.", dscrNote: "Low property taxes and strong population growth. Salt Lake City prices have risen significantly but suburbs still offer workable DSCR ratios.", tip: "Salt Lake City proper is getting expensive, but Ogden, West Valley City, and West Jordan still have $300K–$400K homes with good rent demand. That's where the DSCR math works." },
  VT: { propertyTaxRate: "1.90%", incomeTax: "3.35–8.75%", landlordFriendly: "Tenant-Friendly", foreclosureType: "Judicial", insuranceNote: "Moderate. Standard coverage.", strClimate: "Ski areas (Stowe, Killington) have strong seasonal STR demand.", dscrNote: "High taxes, tenant-friendly laws, and a small rental market make Vermont challenging for DSCR. Ski-town STRs are the exception — strong seasonal income.", tip: "Vermont is basically a no-go for DSCR except ski-town vacation rentals. A $400K cabin near Stowe grossing $50K+/year in STR income can absolutely work. Everything else is tough." },
  VA: { propertyTaxRate: "0.82%", incomeTax: "2–5.75%", landlordFriendly: "Moderate", foreclosureType: "Non-Judicial", insuranceNote: "Moderate. Hampton Roads and coastal areas need flood coverage.", strClimate: "Virginia Beach and Shenandoah have STR demand. NoVA is long-term rental.", dscrNote: "Northern Virginia (NoVA) prices are very high relative to rents. Hampton Roads, Richmond, and Roanoke offer much better DSCR ratios.", tip: "Skip Northern Virginia for DSCR — $500K+ homes and moderate rents don't pencil. Richmond and Hampton Roads are where the DSCR ratios work: $200K–$350K with $1,500–$2,000 rents." },
  WA: { propertyTaxRate: "0.98%", incomeTax: "None", landlordFriendly: "Tenant-Friendly", foreclosureType: "Non-Judicial", insuranceNote: "Moderate. Earthquake coverage recommended in western WA.", strClimate: "Seattle regulates heavily. Eastern WA and San Juan Islands have STR demand.", dscrNote: "No income tax is a big advantage, but Seattle prices make DSCR very difficult. Spokane, Tacoma, and suburbs offer much better price-to-rent ratios.", tip: "Seattle proper is nearly impossible for DSCR — $700K homes renting for $2,800. But Spokane ($250K–$350K, rents $1,600–$2,000) is a completely different market with actual DSCR-friendly numbers." },
  WV: { propertyTaxRate: "0.58%", incomeTax: "3–6.5%", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "Low premiums. Affordable coverage.", strClimate: "Limited. New River Gorge area has growing adventure tourism.", dscrNote: "Very affordable market with low taxes. Charleston is the primary rental market. Limited overall demand but excellent price points for investors who verify rent comps.", tip: "West Virginia is the cheapest state in the country to buy rental property. $80K–$150K homes exist. But make sure someone actually wants to rent in your specific area — demand is spotty." },
  WI: { propertyTaxRate: "1.76%", incomeTax: "3.54–7.65%", landlordFriendly: "Moderate", foreclosureType: "Judicial", insuranceNote: "Moderate. Standard coverage.", strClimate: "Door County and lake areas have seasonal STR demand. Milwaukee is long-term.", dscrNote: "High property taxes are the main DSCR headwind. Milwaukee offers the best price-to-rent ratio but 1.8% taxes add $250+/month on a typical rental.", tip: "Milwaukee has some of the cheapest homes in any major US city — $100K–$200K range. But the 1.8% property tax means a $150K home costs $225/month in taxes alone. Always calculator-check these deals." },
  WY: { propertyTaxRate: "0.61%", incomeTax: "None", landlordFriendly: "Very", foreclosureType: "Non-Judicial", insuranceNote: "Low premiums. Minimal risk.", strClimate: "Jackson Hole has premium STR demand. Limited elsewhere.", dscrNote: "No income tax, low property taxes, and landlord-friendly. The market is tiny but Jackson Hole STRs are some of the highest-grossing in the country.", tip: "Jackson Hole is one of the most expensive STR markets in America — $1M+ homes but $100K+/year in rental income. The DSCR math works at the high end if you can handle the entry price." },
};

// Fallback for states without specific data
const defaultStateInfo: StateInfo = {
  propertyTaxRate: "Varies",
  incomeTax: "Varies",
  landlordFriendly: "Moderate",
  foreclosureType: "Both",
  insuranceNote: "Standard homeowner's insurance required. Rates vary by location and property type.",
  strClimate: "Check local regulations. Short-term rental rules vary by city and county.",
  dscrNote: "DSCR loan availability and market conditions vary. Use our calculator to run the numbers for your specific property.",
  tip: "Every state has DSCR-friendly pockets. Focus on cities with strong rent-to-price ratios and use our calculator to verify before making offers.",
};

export function getStateInfo(stateAbbr: string): StateInfo {
  return stateData[stateAbbr] || defaultStateInfo;
}
