import type { Metadata } from 'next'
import Link from 'next/link'
import { organizationSchema, webSiteSchema, webPageSchema, breadcrumbSchema, faqSchema } from '@/app/site/nycmaid/_lib/seo/schema'
import JsonLd from '@/app/site/nycmaid/_components/JsonLd'
import Breadcrumbs from '@/app/site/nycmaid/_components/Breadcrumbs'
import { jobDates } from '@/app/site/nycmaid/_lib/seo/job-dates'

export const revalidate = 259200 // 3 days — must be a literal for Next segment config

const pageUrl = 'https://www.thenycmaid.com/careers/commission-sales-partner'
const pageTitle = 'Sales Jobs NYC — Commission / 1099 Sales Rep, Paid Daily'
const pageDescription = 'Commission sales jobs in NYC. 1099 sales rep role at one of NYC\'s fastest-growing cleaning services — sign clients or referrers, earn 10% recurring on every cleaning, paid daily via Stripe Connect. Uncapped, override tier as your network grows. Apply now.'

export const metadata: Metadata = {
  title: pageTitle,
  description: pageDescription,
  alternates: { canonical: pageUrl },
  robots: { index: true, follow: true, 'max-snippet': -1, 'max-image-preview': 'large' as const, 'max-video-preview': -1 },
  openGraph: {
    title: pageTitle,
    description: pageDescription,
    url: pageUrl,
    type: 'article',
    siteName: 'The NYC Maid',
    locale: 'en_US',
    images: [{ url: 'https://www.thenycmaid.com/icon-512.png', width: 512, height: 512, alt: 'Commission Sales Partner — The NYC Maid — Now Hiring' }],
    modifiedTime: new Date().toISOString(),
  },
  twitter: { card: 'summary_large_image', title: pageTitle, description: pageDescription, images: ['https://www.thenycmaid.com/icon-512.png'] },
  keywords: 'sales jobs nyc, commission sales jobs nyc, 1099 sales jobs nyc, sales rep jobs nyc, commission only sales jobs, paid daily sales job, uncapped commission jobs nyc, referral partner program, real estate referral income, doorman side income, side hustle nyc, independent sales rep nyc',
  other: {
    'geo.region': 'US-NY',
    'geo.placename': 'New York City',
    'geo.position': '40.7589;-73.9851',
    'ICBM': '40.7589, -73.9851',
    'format-detection': 'telephone=yes',
  },
}

function salesJobPostingSchema() {
  const { datePosted, validThrough } = jobDates()
  return {
    '@context': 'https://schema.org/',
    '@type': 'JobPosting',
    title: 'Commission Sales Representative (1099) — NYC',
    datePosted,
    validThrough,
    description: `<h2>Commission Sales Partner — The NYC Maid — NYC</h2>
<p>First sales role at one of NYC's fastest-growing cleaning services. Earn <strong>10% recurring commission</strong> on every completed cleaning — from direct clients you sign OR from referrers you recruit. Paid daily via Stripe Connect. 1099 independent contractor, no cap, override tier as your network grows.</p>
<h3>Two ways to earn — both pay 10% recurring, both pay forever</h3>
<ul><li><strong>Sign clients directly</strong> — homeowners, commercial accounts, property managers, Airbnb hosts. 10% recurring on every cleaning they book.</li>
<li><strong>Sign referrers</strong> — doormen, real estate agents, concierges, movers. You earn 10% on every cleaning generated by your referrer network.</li></ul>
<h3>How the money works</h3>
<p>10% recurring on every completed cleaning. Paid daily via Stripe Connect direct deposit. 1099 — no ceiling. Book compounds every month. Tier upgrades: 12% at 50 clients, 15% at 100. Override commission on cleanings generated by partners you've brought into the network.</p>
<h3>How to apply</h3>
<p>Apply at <a href="https://www.thenycmaid.com/apply/commission-sales-partner">thenycmaid.com/apply/commission-sales-partner</a> — include a 60-second selfie video.</p>`,
    hiringOrganization: {
      '@type': 'Organization',
      name: 'The NYC Maid',
      sameAs: 'https://www.thenycmaid.com',
      url: 'https://www.thenycmaid.com',
      logo: { '@type': 'ImageObject', url: 'https://www.thenycmaid.com/icon-512.png', width: 512, height: 512 },
      telephone: '+1-212-202-8400',
      email: 'hi@thenycmaid.com',
      foundingDate: '2018',
      numberOfEmployees: { '@type': 'QuantitativeValue', minValue: 10, maxValue: 50 },
    },
    image: 'https://www.thenycmaid.com/icon-512.png',
    identifier: { '@type': 'PropertyValue', name: 'The NYC Maid', value: 'nycmaid-sales-nyc' },
    jobLocation: {
      '@type': 'Place',
      address: { '@type': 'PostalAddress', addressLocality: 'New York', addressRegion: 'NY', postalCode: '10036', addressCountry: 'US' },
    },
    applicantLocationRequirements: { '@type': 'Country', name: 'US' },
    employmentType: ['CONTRACTOR'],
    jobImmediateStart: true,
    totalJobOpenings: 5,
    directApply: true,
    url: pageUrl,
    industry: 'Cleaning Services',
    occupationalCategory: '41-3091.00',
    qualifications: 'NYC-area network access. Relationship builder. Sales background helpful, not required. English required, English/Spanish a plus.',
    responsibilities: 'Sign cleaning clients and referral partners across NYC. Build and maintain a recurring book of business.',
    skills: 'Relationship building, prospecting, referral network development, communication, follow-through',
    incentiveCompensation: '10% recurring commission on every completed cleaning, from direct clients and referrer networks. Paid daily via Stripe Connect. Tier upgrades at 50 and 100 clients. Override commission on partners brought into the network. 1099 independent contractor, uncapped.',
    jobBenefits: 'Recurring commission that compounds. Paid daily via Stripe Connect. No cap. Override income as your network of partners grows. Multi-brand portfolio expansion. 1099 — be your own boss, your own hours.',
    educationRequirements: { '@type': 'EducationalOccupationalCredential', credentialCategory: 'high school' },
    experienceRequirements: { '@type': 'OccupationalExperienceRequirements', monthsOfExperience: 0 },
    experienceInPlaceOfEducation: true,
    applicationContact: { '@type': 'ContactPoint', telephone: '+1-212-202-8400', email: 'hi@thenycmaid.com', contactType: 'Recruiting' },
  }
}

const faqs = [
  { question: 'How do I get paid?', answer: 'Daily, via Stripe Connect direct deposit — automated the moment a completed job closes. No invoicing, no chasing, no monthly wait.' },
  { question: 'What exactly earns me commission?', answer: 'Every completed cleaning tied to you — whether it came from a client you signed directly or from anyone in your referrer network. 10% recurring, for as long as they stay a customer.' },
  { question: 'Is there a cap?', answer: 'No. 1099 independent contractor, no ceiling. Tier upgrades take you to 12% at 50 clients and 15% at 100. Bring other partners into the network and you also earn an override on the cleanings they generate.' },
  { question: 'Do I need prior sales experience?', answer: 'Helpful but not required. Real estate, insurance, financial advising, hospitality, personal trainers, event planners, ex-doormen, ex-concierges — all encouraged. What matters is your network and your hustle.' },
  { question: 'What\'s the commitment?', answer: 'This is a build. Early months are the foundation; real income comes from compounding. No fixed quota or set hours — partners who sign 3 direct clients or 3 active referrers in their first 90 days tend to be the ones who build a real book.' },
  { question: 'What do I get to work with?', answer: 'A unique tracking link and code (permanent attribution), a real-time commission dashboard, auto Stripe Connect payouts, and optional branded marketing materials if you want them. The whole payout system is already live for existing referrers today.' },
]

const Check = () => <span className="text-[#A8F0DC] mt-0.5 flex-shrink-0">&#10003;</span>

export default function CommissionSalesPartnerPage() {
  return (
    <>
      <JsonLd data={[
        organizationSchema(),
        webSiteSchema(),
        webPageSchema({
          url: pageUrl,
          name: pageTitle,
          description: pageDescription,
          type: 'WebPage',
          speakable: ['h1', 'h2', '.hero-description'],
          breadcrumb: [
            { name: 'Home', url: 'https://www.thenycmaid.com' },
            { name: 'Careers', url: 'https://www.thenycmaid.com/available-nyc-maid-jobs' },
            { name: 'Commission Sales Partner', url: pageUrl },
          ],
        }),
        breadcrumbSchema([
          { name: 'Home', url: 'https://www.thenycmaid.com' },
          { name: 'Careers', url: 'https://www.thenycmaid.com/available-nyc-maid-jobs' },
          { name: 'Commission Sales Partner', url: pageUrl },
        ]),
        salesJobPostingSchema(),
        faqSchema(faqs),
      ]} />

      {/* Hero */}
      <section className="bg-gradient-to-b from-[#1E2A4A] to-[#243352] py-20 md:py-28">
        <div className="max-w-5xl mx-auto px-4">
          <div className="flex items-center gap-3 mb-4 flex-wrap">
            <p className="text-[#A8F0DC] text-sm font-semibold tracking-[0.2em] uppercase">Now Hiring</p>
            <span className="text-white/30">&middot;</span>
            <p className="text-white/60 text-sm">First Sales Role</p>
            <span className="text-white/30">&middot;</span>
            <p className="text-white/60 text-sm">1099 &middot; Uncapped</p>
            <span className="text-white/30">&middot;</span>
            <p className="text-white/60 text-sm">Paid Daily</p>
          </div>
          <h1 className="font-[family-name:var(--font-bebas)] text-4xl md:text-6xl lg:text-7xl text-white tracking-wide leading-[0.95] mb-6">
            Sales Jobs in NYC — Commission, 1099, Paid Daily
          </h1>
          <p className="hero-description text-blue-200/80 text-lg max-w-3xl leading-relaxed mb-4">
            First sales role at one of NYC&apos;s fastest-growing cleaning services. Build a book that compounds forever. Get paid daily.
          </p>
          <p className="text-blue-200/60 max-w-3xl leading-relaxed mb-3">
            155 jobs/month and growing month-over-month &mdash; on $0 spent on ads. Ranked #1 on Google Maps for &ldquo;nyc maid&rdquo; and &ldquo;nyc cleaning service.&rdquo; Featured in Pioneer Woman and AOL. Everything so far has been organic, referrals, and word of mouth. This is the first sales position we&apos;ve ever opened.
          </p>
          <p className="text-blue-200/60 max-w-3xl leading-relaxed mb-6">
            Two ways to earn &mdash; both pay <strong className="text-white">10% recurring</strong>, both pay forever. Sign clients directly, sign referrers who bring us clients, or stack both.
          </p>
          <div className="flex flex-wrap items-center gap-3 mb-10">
            <span className="bg-[#A8F0DC]/20 text-[#A8F0DC] text-xs font-semibold px-4 py-2 rounded-full">10% Recurring &mdash; Forever</span>
            <span className="bg-[#A8F0DC]/20 text-[#A8F0DC] text-xs font-semibold px-4 py-2 rounded-full">Paid Daily via Stripe Connect</span>
            <span className="bg-[#A8F0DC]/20 text-[#A8F0DC] text-xs font-semibold px-4 py-2 rounded-full">1099 &middot; No Cap</span>
            <span className="bg-[#A8F0DC]/20 text-[#A8F0DC] text-xs font-semibold px-4 py-2 rounded-full">Override Tier as You Grow</span>
          </div>
          <div className="flex flex-col sm:flex-row items-start gap-5">
            <Link href="/apply/commission-sales-partner" target="_blank" rel="noopener noreferrer" className="bg-[#A8F0DC] text-[#1E2A4A] px-10 py-4 rounded-lg font-bold text-sm tracking-widest uppercase hover:bg-[#8DE8CC] transition-colors">
              Apply Now
            </Link>
            <a href="sms:2122028400" className="text-blue-200/70 font-medium text-lg py-4 hover:text-white transition-colors underline underline-offset-4">
              or Text (212) 202-8400
            </a>
          </div>
        </div>
      </section>

      {/* Numbers Bar */}
      <section className="bg-[#A8F0DC] py-12">
        <div className="max-w-5xl mx-auto px-4">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-6 text-center">
            <div>
              <p className="font-[family-name:var(--font-bebas)] text-4xl text-[#1E2A4A] tracking-wide">10%</p>
              <p className="text-[#1E2A4A]/60 text-sm font-medium">Recurring, Forever</p>
            </div>
            <div>
              <p className="font-[family-name:var(--font-bebas)] text-4xl text-[#1E2A4A] tracking-wide">155/mo</p>
              <p className="text-[#1E2A4A]/60 text-sm font-medium">Jobs &amp; Growing</p>
            </div>
            <div>
              <p className="font-[family-name:var(--font-bebas)] text-4xl text-[#1E2A4A] tracking-wide">#1</p>
              <p className="text-[#1E2A4A]/60 text-sm font-medium">Google Maps &mdash; NYC Maid</p>
            </div>
            <div>
              <p className="font-[family-name:var(--font-bebas)] text-4xl text-[#1E2A4A] tracking-wide">Daily</p>
              <p className="text-[#1E2A4A]/60 text-sm font-medium">Stripe Connect Payouts</p>
            </div>
          </div>
        </div>
      </section>

      <div className="max-w-5xl mx-auto px-4 py-12">
        <Breadcrumbs items={[
          { name: 'Careers', href: '/available-nyc-maid-jobs' },
          { name: 'Commission Sales Partner', href: '/careers/commission-sales-partner' },
        ]} />

        {/* Two ways to earn */}
        <section className="mb-20">
          <p className="text-xs font-semibold text-[#A8F0DC] tracking-[0.2em] uppercase mb-2">How You Earn</p>
          <h2 className="font-[family-name:var(--font-bebas)] text-3xl md:text-4xl text-[#1E2A4A] tracking-wide mb-3">Two Ways to Earn. Both Pay 10% Recurring. Both Pay Forever.</h2>
          <p className="text-gray-500 max-w-3xl mb-10">Direct clients pay you fast. Referrer networks compound long-term. Together = a real passive income book that grows every month. The best salespeople do both.</p>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <div className="border border-gray-200 rounded-2xl overflow-hidden">
              <div className="bg-gradient-to-b from-[#1E2A4A] to-[#243352] p-6">
                <p className="font-[family-name:var(--font-bebas)] text-5xl text-[#A8F0DC] tracking-wide mb-1">1</p>
                <h3 className="font-[family-name:var(--font-bebas)] text-xl text-white tracking-wide">Sign Clients Directly</h3>
              </div>
              <div className="p-6">
                <p className="text-gray-600 text-sm leading-relaxed">Close a homeowner, a commercial account, a property manager, or an Airbnb host — you earn <strong>10% recurring on every cleaning they book</strong>. As long as they&apos;re a client, you&apos;re paid.</p>
              </div>
            </div>
            <div className="border border-gray-200 rounded-2xl overflow-hidden">
              <div className="bg-gradient-to-b from-[#1E2A4A] to-[#243352] p-6">
                <p className="font-[family-name:var(--font-bebas)] text-5xl text-[#A8F0DC] tracking-wide mb-1">2</p>
                <h3 className="font-[family-name:var(--font-bebas)] text-xl text-white tracking-wide">Sign Referrers</h3>
              </div>
              <div className="p-6">
                <p className="text-gray-600 text-sm leading-relaxed">Sign a doorman, a real estate agent, a concierge, a moving company — they refer clients, and <strong>you earn 10% on every cleaning generated by your referrer network</strong>. Sign the referrer once, earn on everything they send us for years.</p>
              </div>
            </div>
          </div>
        </section>

        {/* How the money works + math */}
        <section className="bg-gradient-to-b from-[#1E2A4A] to-[#243352] rounded-2xl p-8 md:p-14 mb-20">
          <p className="text-[#A8F0DC] text-xs font-semibold tracking-[0.2em] uppercase mb-2">The Math</p>
          <h2 className="font-[family-name:var(--font-bebas)] text-3xl text-white tracking-wide mb-3">Every Relationship Pays You Every Month It Stays Active</h2>
          <p className="text-blue-200/60 max-w-3xl mb-10">10% recurring on every completed cleaning. Paid daily via Stripe Connect. 1099, no cap. Your book compounds every month — every client and referrer you sign stays productive for years.</p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {[
              ['1 weekly recurring direct client', '$27.60/mo passive — forever'],
              ['1 doorman refers 10 clients', '$275/mo passive from one relationship'],
              ['1 property manager, 100 units', 'up to $2,200/mo passive'],
              ['1 commercial account (office/gym/medical)', '$500–2,000/mo passive from a single deal'],
            ].map(([a, b]) => (
              <div key={a} className="border border-white/10 rounded-2xl p-6">
                <p className="text-white font-semibold mb-1">{a}</p>
                <p className="text-[#A8F0DC] text-sm">{b}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Override tier */}
        <section className="mb-20">
          <p className="text-xs font-semibold text-[#A8F0DC] tracking-[0.2em] uppercase mb-2">Your Upside</p>
          <h2 className="font-[family-name:var(--font-bebas)] text-3xl md:text-4xl text-[#1E2A4A] tracking-wide mb-3">Override Tier — Grow Your Network, Grow Your Income</h2>
          <p className="text-gray-500 max-w-3xl mb-6">This is the first sales partner role at The NYC Maid. For the right person, it&apos;s the foundation of a growing partner network — and the first person in the door is positioned to benefit most as it compounds.</p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {[
              ['Hit milestones, unlock override tier', 'Earned through performance — a higher commission tier as your network compounds, not a title or new role.'],
              ['Override on partners you bring in', 'Earn an override commission on every completed cleaning generated by partners you’ve brought into the network — on top of your personal book.'],
              ['Three layers of income', 'Personal book + override book + multi-brand portfolio expansion, all compounding together.'],
            ].map(([t, d]) => (
              <div key={t} className="border border-gray-200 rounded-2xl p-6">
                <h3 className="font-semibold text-[#1E2A4A] mb-2">{t}</h3>
                <p className="text-gray-500 text-sm leading-relaxed">{d}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Infrastructure */}
        <section className="mb-20">
          <p className="text-xs font-semibold text-gray-400 tracking-[0.2em] uppercase mb-2">Already Built</p>
          <h2 className="font-[family-name:var(--font-bebas)] text-3xl md:text-4xl text-[#1E2A4A] tracking-wide mb-3">The Infrastructure Is Built. You Just Plug In.</h2>
          <p className="text-gray-500 max-w-3xl mb-10">Every part of the payout system is already live and running for existing referrers today. No manual reporting. No &ldquo;we&apos;ll get back to you on the commission math.&rdquo; Every dollar is transparent, automated, and yours the moment it&apos;s earned.</p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {[
              'Unique tracking URL and code — permanent attribution locked to you',
              'Auto-applied at booking — commission calculated the moment the booking is created',
              'Real-time commission dashboard — every lead, booking, and dollar as it happens',
              'Auto Stripe Connect payouts — daily deposits, no invoicing, no chasing',
              'Full audit trail — every commission timestamped and traceable to the source booking',
              'Multi-channel tracking — web, SMS, phone, or QR, your attribution follows the client',
              'Recurring commissions auto-apply — every future cleaning fires another commission',
              'Optional branded materials available if useful — one-pagers, business cards, digital pitch deck',
            ].map((item) => (
              <div key={item} className="flex gap-2 border border-gray-200 rounded-xl p-4">
                <Check />
                <p className="text-gray-600 text-sm leading-relaxed">{item}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Target list */}
        <section className="mb-20">
          <p className="text-xs font-semibold text-[#A8F0DC] tracking-[0.2em] uppercase mb-2">Your Target List</p>
          <h2 className="font-[family-name:var(--font-bebas)] text-3xl md:text-4xl text-[#1E2A4A] tracking-wide mb-8">Two Lanes</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="border border-gray-200 rounded-2xl p-6">
              <h3 className="font-semibold text-[#1E2A4A] mb-3">Direct clients (10% on their cleanings)</h3>
              <div className="space-y-2">
                {['Homeowners in your network', 'Commercial accounts — offices, gyms, medical, retail, restaurants, coworking', 'Property management contracts', 'Airbnb hosts and superhosts', 'Move-in/move-out packages', 'Post-construction cleanings'].map((i) => (
                  <div key={i} className="flex gap-2"><Check /><p className="text-gray-600 text-sm">{i}</p></div>
                ))}
              </div>
            </div>
            <div className="border border-gray-200 rounded-2xl p-6">
              <h3 className="font-semibold text-[#1E2A4A] mb-3">Referrers (10% on all their referrals)</h3>
              <div className="space-y-2">
                {['Luxury building doormen (300+ unit buildings)', 'Real estate agents', 'Corporate concierges (WeWork, Industrious, luxury offices)', 'Moving companies', 'Interior designers', 'Wedding + event planners', 'Renovation contractors', 'Home organizers'].map((i) => (
                  <div key={i} className="flex gap-2"><Check /><p className="text-gray-600 text-sm">{i}</p></div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* What we look for + the catch */}
        <section className="mb-20 grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="border border-gray-200 rounded-2xl p-6">
            <h3 className="font-semibold text-[#1E2A4A] mb-3">What We&apos;re Looking For</h3>
            <div className="space-y-2">
              {['Relationship builder — you know everyone in your neighborhood, building, or industry', 'Sales background helpful, not required', 'Strong communication (English required, English/Spanish a plus)', 'NYC-based with real network access', 'Hungry for passive income and willing to build a book over time', 'Comfortable working as a 1099'].map((i) => (
                <div key={i} className="flex gap-2"><Check /><p className="text-gray-600 text-sm">{i}</p></div>
              ))}
            </div>
          </div>
          <div className="border border-gray-200 rounded-2xl p-6">
            <h3 className="font-semibold text-[#1E2A4A] mb-3">The Catch</h3>
            <p className="text-gray-500 text-sm leading-relaxed mb-3">There isn&apos;t one. But be honest with yourself before applying:</p>
            <div className="space-y-2">
              {['This is a build. Early months are the foundation — real income comes from compounding.', 'You bring the network and do the outreach — your own hours, your own way. No schedule, no set hours, no one telling you when or how to work.', 'No fixed quota — but partners who sign 3 direct clients or 3 active referrers in their first 90 days are the ones who build a real book.'].map((i) => (
                <div key={i} className="flex gap-2"><span className="text-[#1E2A4A] mt-0.5">&bull;</span><p className="text-gray-600 text-sm">{i}</p></div>
              ))}
            </div>
          </div>
        </section>

        {/* FAQ */}
        <section className="mb-20">
          <p className="text-xs font-semibold text-[#A8F0DC] tracking-[0.2em] uppercase mb-2">Questions</p>
          <h2 className="font-[family-name:var(--font-bebas)] text-3xl md:text-4xl text-[#1E2A4A] tracking-wide mb-8">Frequently Asked Questions</h2>
          <div className="space-y-3">
            {faqs.map((faq) => (
              <details key={faq.question} className="group border border-gray-200 rounded-xl overflow-hidden hover:border-[#A8F0DC] transition-colors">
                <summary className="cursor-pointer px-5 py-4 flex items-center justify-between gap-4">
                  <span className="font-medium text-[#1E2A4A] text-sm">{faq.question}</span>
                  <span className="text-[#A8F0DC] text-lg flex-shrink-0 group-open:rotate-45 transition-transform">+</span>
                </summary>
                <div className="px-5 pb-5"><p className="text-gray-600 text-sm leading-relaxed">{faq.answer}</p></div>
              </details>
            ))}
          </div>
        </section>

        {/* Apply CTA */}
        <section className="bg-[#A8F0DC] rounded-2xl p-8 md:p-12 text-center mb-16">
          <p className="font-[family-name:var(--font-bebas)] text-3xl md:text-4xl text-[#1E2A4A] tracking-wide mb-2">First Sales Role. 10% Recurring. Paid Daily. No Ceiling.</p>
          <p className="text-[#1E2A4A]/60 max-w-xl mx-auto mb-6">Apply in a few minutes — include a 60-second selfie video. We respond within 48 hours.</p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link href="/apply/commission-sales-partner" target="_blank" rel="noopener noreferrer" className="bg-[#1E2A4A] text-white px-10 py-4 rounded-lg font-bold text-sm tracking-widest uppercase hover:bg-[#1E2A4A]/90 transition-colors">
              Apply Now
            </Link>
            <a href="sms:2122028400" className="text-[#1E2A4A]/60 font-medium text-sm hover:text-[#1E2A4A] transition-colors underline underline-offset-4">
              or Text (212) 202-8400
            </a>
          </div>
        </section>
      </div>
    </>
  )
}
