import type { EmdMicrositeConfig } from './types'

export const celebrationMaidConfig: EmdMicrositeConfig = {
  domain: 'celebrationmaid.com',
  brandName: 'Celebration Maid',
  city: 'Celebration',
  regionLabel: 'Celebration, FL',
  metaTitle: 'Celebration Maid and Cleaning Service',
  metaDescription: 'Celebration Maid — house cleaning across Downtown Celebration, Artisan Park & Lake Evalyn from $49/hr. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '28.3197', lng: '-81.5326' },
  introParagraphs: [
    "Celebration Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across one of Florida's most distinctive planned communities — a New Urbanist town built around walkable streets, front porches, and picture-perfect architecture just south of Walt Disney World. If you live in Celebration, you know how much this community's picket-fence presentation matters to residents. We built Celebration Maid to answer exactly that problem: a local cleaning service that understands this community's standards and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Celebration Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Celebration.",
    "Whether you need a one-time deep clean before hosting guests near Downtown Celebration, a recurring weekly service for a busy Artisan Park household, or a fast turnover clean for a Lake Evalyn rental between guests, Celebration Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from classic front-porch cottages to newer builds in North Village, and that range of experience shapes how we train every cleaner. Celebration Maid was built around the reality that this community's architectural standards demand real attention to detail.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Celebration Maid exists because this master-planned town's walkable streets, HOA architectural standards, and mix of full-time residents and vacation-home owners make it its own world. So rather than force Celebration into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this community.",
    "Every cleaner who works under the Celebration Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Celebration, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Celebration as in Minneapolis. Celebration Maid does not. We built our service around this community's architectural presentation standards and mix of full-time and vacation homes.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Celebration Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Celebration home on recurring visits.",
  ],
  challenges: [
    { title: 'HOA Presentation Standards', body: "Celebration's strict architectural and community standards mean homes are expected to look their best inside and out. We clean with those expectations in mind." },
    { title: 'Vacation Home Turnover', body: "Many Celebration homes near the Disney corridor serve as vacation properties. We offer fast turnover cleaning between guest stays." },
    { title: 'Front-Porch Home Care', body: "Celebration's signature front-porch cottages and Southern-style homes often have detailed millwork and trim that need careful attention. We adjust our approach accordingly." },
    { title: 'Humidity & Mold Prevention', body: "Central Florida humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit." },
    { title: 'Walkable-Town Foot Traffic', body: "Homes near Downtown Celebration see more foot traffic and visiting family than typical suburban homes. We build extra attention to entryways into our routine." },
    { title: 'Hurricane Season Readiness', body: "Storm season means shutter dust and post-storm cleanup. We offer flexible scheduling around storm prep and recovery." },
  ],
  neighborhoods: [
    { name: 'Downtown Celebration', blurb: "Close to the lake and Market Street, our downtown clients rely on us for consistent, detail-first cleaning." },
    { name: 'Artisan Park', blurb: "This newer village within Celebration is home to many of our longest-running recurring clients." },
    { name: 'Lake Evalyn', blurb: "This waterfront section trusts Celebration Maid for everything from routine upkeep to deep cleans before family visits." },
    { name: 'Golfpark', blurb: "This golf-course-adjacent neighborhood is a favorite for our weekly and bi-weekly recurring clients." },
    { name: 'North Village', blurb: "This newer section of Celebration calls for a first-clean approach tuned to newer construction." },
    { name: 'Aquila Reserve', blurb: "This established residential section is a regular stop for our bi-weekly and monthly cleaning plans." },
  ],
  pricingExplainer: [
    "Celebration Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy downtown cottage might only need the 2-hour minimum, while an Artisan Park home getting its first deep clean could run 5 hours or more.",
    "Recurring service is where Celebration Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Celebration.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Celebration full-time families. Weekly service keeps clutter and dust from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes or vacation properties. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, guest turnover, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "Our HOA has real standards and Celebration Maid always leaves the place looking exactly the way it should.", name: 'Rebecca N.', neighborhood: 'Downtown Celebration' },
    { text: "We rent our home out to vacationers and needed fast turnovers. They've never made us miss a check-in.", name: 'Trevor L.', neighborhood: 'North Village' },
    { text: "They've handled our Artisan Park home weekly for over a year — always the same reliable cleaner.", name: 'Julia B.', neighborhood: 'Artisan Park' },
    { text: "Our front-porch cottage has a lot of trim detail and they treated it with real care.", name: 'Adam K.', neighborhood: 'Lake Evalyn' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Celebration?', answer: 'Celebration Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Celebration?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Celebration Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, vacation home turnovers, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Do you clean vacation homes near the Disney corridor?', answer: "Yes, with fast turnaround between guests — this is one of our most requested services in Celebration." },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for closing on a new home or ending a lease." },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or lockbox code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Celebration Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of Celebration do you serve?', answer: 'Downtown Celebration, Artisan Park, Lake Evalyn, Golfpark, North Village, Aquila Reserve, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Celebration.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Celebration Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Celebration Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a smaller cottage or condo?', answer: 'Yes, our 2-hour minimum is usually perfect for a smaller unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Celebration Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'Do you manage cleanings for a vacation rental management company?', answer: 'Yes, we regularly work with property managers overseeing multiple Celebration vacation homes.' },
    { question: 'What if my community requires vendor registration?', answer: 'Send us your requirements ahead of time and we\'ll get registered.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Is Celebration Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Celebration Maid serve both cottages and larger homes?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Celebration Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
