import type { EmdMicrositeConfig } from './types'

export const cocoaBeachMaidConfig: EmdMicrositeConfig = {
  domain: 'cocoabeachmaid.com',
  brandName: 'Cocoa Beach Maid',
  city: 'Cocoa Beach',
  regionLabel: 'Cocoa Beach, FL',
  metaTitle: 'Cocoa Beach Maid and Cleaning Service',
  metaDescription: 'Cocoa Beach Maid — house cleaning across Cocoa Isles, South Patrick Shores & Banana River Estates starting at $49 per hour. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '28.3200', lng: '-80.6076' },
  introParagraphs: [
    "Cocoa Beach Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across the Space Coast's most famous barrier island — a surf town where salt air, sand, and rocket launches are just part of daily life. If you live in Cocoa Beach, you know how quickly beach sand and ocean humidity can wear down a home. We built Cocoa Beach Maid to answer exactly that problem: a local cleaning service that understands barrier-island living and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Cocoa Beach Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Cocoa Beach.",
    "Whether you need a one-time deep clean before hosting guests near the pier, a recurring weekly service for a busy Cocoa Isles household, or a fast turnover clean for a South Patrick Shores vacation rental between guests, Cocoa Beach Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from canal-front homes on the Banana River to beachfront condos steps from the surf, and that range of experience shapes how we train every cleaner. Cocoa Beach Maid was built around the reality that a barrier-island surf town demands a different approach than inland cleaning routines.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Cocoa Beach Maid exists because this barrier island's mix of surf culture, Space Coast workforce housing, and vacation rentals make it its own world. So rather than force Cocoa Beach into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this city.",
    "Every cleaner who works under the Cocoa Beach Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Cocoa Beach, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Cocoa Beach as in Minneapolis. Cocoa Beach Maid does not. We built our service around this barrier island's beach sand, ocean humidity, and heavy tourist turnover.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Cocoa Beach Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Cocoa Beach home on recurring visits.",
  ],
  challenges: [
    { title: 'Beach Sand Everywhere', body: "Living steps from the surf means sand tracks in constantly, working into carpets, grout lines, and furniture. We use techniques built for lifting sand without grinding it deeper in." },
    { title: 'Salt Air & Corrosion', body: "Cocoa Beach's ocean air carries fine salt particulate that settles on chrome fixtures, appliances, and window tracks. We use products chosen to cut salt residue without damaging finishes." },
    { title: 'Rocket Launch Scheduling', body: "Launch days from nearby Cape Canaveral can bring road closures and traffic surges. We build launch-day awareness into our scheduling so appointments aren't disrupted." },
    { title: 'Vacation Rental Turnover', body: "As one of Florida's most visited surf towns, Cocoa Beach condos and homes turn over fast between guests. Our scheduling supports same-day and next-day turnovers." },
    { title: 'Humidity & Mold Prevention', body: "Barrier-island humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit." },
    { title: 'Hurricane Season Readiness', body: "Storm season means shutter dust and post-storm cleanup on a barrier island that takes weather seriously. We offer flexible scheduling around storm prep and recovery." },
  ],
  neighborhoods: [
    { name: 'Cocoa Isles', blurb: "This canal-laced residential neighborhood is home to many of our longest-running recurring clients, who value a consistent cleaner they can trust." },
    { name: 'South Patrick Shores', blurb: "Just south of the city, this waterfront community's homes call for extended deep-cleaning sessions and careful attention to salt residue." },
    { name: 'Banana River Estates', blurb: "Riverfront living here means boat access and Banana River breezes — we adjust our routine for homes with direct water exposure." },
    { name: 'Downtown Cocoa Beach', blurb: "Close to the pier and Minutemen Causeway, our downtown condo clients rely on us for fast, reliable turnover cleaning between stays." },
    { name: 'Cape Canaveral', blurb: "Just north of Cocoa Beach, our Cape Canaveral clients include both full-time residents and short-term rental owners near Port Canaveral." },
    { name: 'Cocoa Beach Country Club Area', blurb: "This golf-adjacent neighborhood trusts Cocoa Beach Maid for everything from routine upkeep to deep cleans before family visits." },
  ],
  pricingExplainer: [
    "Cocoa Beach Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy downtown condo might only need the 2-hour minimum, while a South Patrick Shores home getting its first deep clean could run 5 hours or more.",
    "Recurring service is where Cocoa Beach Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Cocoa Beach.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Cocoa Beach families and full-time residents. Weekly service keeps sand and salt buildup from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes or seasonal residences. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "We're steps from the beach and sand gets everywhere. Cocoa Beach Maid actually gets it out of the grout, not just the surface.", name: 'Kelly A.', neighborhood: 'Downtown Cocoa Beach' },
    { text: "We live on a canal in Cocoa Isles and the salt air is brutal on our fixtures. They know exactly how to handle it.", name: 'Doug R.', neighborhood: 'Cocoa Isles' },
    { text: "They've handled our South Patrick Shores home weekly for over a year — always the same reliable cleaner.", name: 'Nancy V.', neighborhood: 'South Patrick Shores' },
    { text: "We rent our condo out near the pier and needed fast turnovers. They've never made us miss a check-in, even around launch weekends.", name: 'Pete C.', neighborhood: 'Cape Canaveral' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Cocoa Beach?', answer: 'Cocoa Beach Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Cocoa Beach?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Cocoa Beach Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, Airbnb turnovers, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for closing on a canal-front home or ending a lease near the beach." },
    { question: 'Can you get beach sand out of carpets and grout?', answer: "Yes, this is one of our specialties on a barrier island — we use techniques built specifically for lifting sand without grinding it in further." },
    { question: 'Do you clean Airbnb and short-term rentals?', answer: 'Yes, with fast turnaround between guests, including around busy launch weekends.' },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or lockbox code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Cocoa Beach Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of Cocoa Beach do you serve?', answer: 'Cocoa Isles, South Patrick Shores, Banana River Estates, downtown Cocoa Beach, Cape Canaveral, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Cocoa Beach.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Cocoa Beach Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Cocoa Beach Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a studio or small condo?', answer: 'Yes, our 2-hour minimum is usually perfect for a small unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Cocoa Beach Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'Do you clean canal-front and waterfront homes?', answer: 'Yes, we regularly service waterfront properties across Cocoa Isles and Banana River Estates.' },
    { question: 'What if my building requires vendor registration?', answer: 'Send us your requirements ahead of time and we\'ll get registered.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Do you clean vacation homes that sit empty?', answer: 'Yes, with arrival-prep cleanings before you visit.' },
    { question: 'Is Cocoa Beach Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty — barrier-island storms move fast.' },
    { question: 'Does Cocoa Beach Maid serve both condos and houses?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Cocoa Beach Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
    { question: 'Do rocket launches ever affect scheduling?', answer: "Occasionally — launch-day traffic and road closures near Cape Canaveral can shift arrival windows. We'll text you proactively if a launch affects your appointment." },
  ],
}
