import type { EmdMicrositeConfig } from './types'

export const cordovaParkMaidConfig: EmdMicrositeConfig = {
  domain: 'cordovaparkmaid.com',
  brandName: 'Cordova Park Maid',
  city: 'Pensacola',
  regionLabel: 'Cordova Park, Pensacola, FL',
  metaTitle: 'Cordova Park Maid and Cleaning Service',
  metaDescription: 'Cordova Park Maid — house cleaning near Cordova Mall & Bayou Blvd, Pensacola, FL starting at $49 per hour. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '30.4674', lng: '-87.2114' },
  introParagraphs: [
    "Cordova Park Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning for the Cordova Park neighborhood and the surrounding Pensacola area — an established, centrally-located residential pocket near Cordova Mall and Bayou Boulevard. If you live in Cordova Park, you know how quickly Gulf Coast humidity and everyday life can get ahead of a busy household. We built Cordova Park Maid to answer exactly that problem: a local cleaning service that understands Pensacola living and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Cordova Park Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Cordova Park and the rest of Pensacola.",
    "Whether you need a one-time deep clean before hosting company, a recurring weekly service for a busy household near Bayou Blvd, or a fast turnover clean for a nearby rental, Cordova Park Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from classic Cordova Park ranch homes to condos closer to downtown Pensacola, and that range of experience shapes how we train every cleaner. Cordova Park Maid was built around the reality that this centrally-located part of Pensacola sees a real mix of housing styles and demands real range.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Cordova Park Maid exists because this established, centrally-located Pensacola neighborhood deserves a cleaning brand tuned to it specifically. So rather than treat Cordova Park as an afterthought, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this part of Pensacola.",
    "Every cleaner who works under the Cordova Park Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Cordova Park and greater Pensacola, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Cordova Park as in Minneapolis. Cordova Park Maid does not. We built our service around this part of Pensacola's mid-century homes, mature yards, and everyday Gulf humidity.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Cordova Park Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Cordova Park-area home on recurring visits.",
  ],
  challenges: [
    { title: 'Mid-Century Homes', body: "Cordova Park's housing stock skews established, with original tile, cabinetry, and fixtures that need a gentler touch than newer construction. We adjust our approach accordingly." },
    { title: 'Humidity & Mold Prevention', body: "Pensacola's Gulf Coast humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit." },
    { title: 'Mall-Area Traffic Dust', body: "Homes near the Cordova Mall/Bayou Blvd corridor see more everyday traffic and dust tracked in than quieter residential pockets. We factor that into every visit." },
    { title: 'Pine & Oak Debris', body: "Mature tree cover throughout Cordova Park means pine needles and leaf debris get tracked indoors regularly. We use techniques suited to lifting fine particulate without smearing it." },
    { title: 'Hurricane Season Readiness', body: "Panhandle storm season means shutter dust and post-storm cleanup for inland Pensacola just as much as the coast. We offer flexible scheduling around storm prep and recovery." },
  ],
  neighborhoods: [
    { name: 'Cordova Park', blurb: "Centered around Bayou Blvd and Cordova Mall, this established neighborhood is where Cordova Park Maid focuses most of its weekly and bi-weekly recurring service." },
    { name: 'East Hill', blurb: "Closer to downtown, East Hill's historic bungalows call for the same care and attention we bring to every Pensacola-area home." },
    { name: 'North Hill', blurb: "This historic preservation district's Victorian-era homes get the extra care their original woodwork and fixtures deserve." },
    { name: 'Brent', blurb: "Just north along N Davis Highway, Brent's established homes trust us for consistent, reliable service." },
    { name: 'Downtown Pensacola', blurb: "Close to Palafox Street, our downtown condo and loft clients rely on us for reliable, consistent cleaning." },
    { name: 'Ferry Pass', blurb: "Further north near I-10, Ferry Pass's mix of subdivisions is a regular stop for our recurring cleaning plans." },
  ],
  pricingExplainer: [
    "Cordova Park Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy Cordova Park condo might only need the 2-hour minimum, while a larger home getting its first deep clean could run 5 hours or more.",
    "Recurring service is where Cordova Park Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Cordova Park and greater Pensacola.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Cordova Park families with kids or pets. Weekly service keeps clutter and dust from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "Our home near Cordova Mall is older and needed real care, not a rushed once-over. They got it.", name: 'Renee B.', neighborhood: 'Cordova Park' },
    { text: "They've cleaned our place weekly for months now — always the same reliable cleaner.", name: 'Todd M.', neighborhood: 'Cordova Park' },
    { text: "We manage a rental near Bayou Blvd and needed fast turnaround between tenants. They delivered.", name: 'Angela F.', neighborhood: 'East Hill' },
    { text: "Booked a deep clean before hosting family and they went above and beyond.", name: 'Steven R.', neighborhood: 'North Hill' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Cordova Park?', answer: 'Cordova Park Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Cordova Park?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Cordova Park Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, rental turnovers, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for a rental turnover or closing on a new home." },
    { question: 'Can you clean older, established homes?', answer: "Absolutely. Many Cordova Park homes are decades old and we adjust our products and technique accordingly." },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or door code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Cordova Park Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas near Cordova Park do you serve?', answer: 'Cordova Park, East Hill, North Hill, Brent, downtown Pensacola, Ferry Pass, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Cordova Park or greater Pensacola.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Cordova Park Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Cordova Park Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a smaller home or condo?', answer: 'Yes, our 2-hour minimum is usually perfect for a smaller unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Cordova Park Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'Do you manage cleanings for landlords with multiple rentals?', answer: 'Yes, we regularly work with landlords managing several properties around Cordova Park and Pensacola.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Is Cordova Park Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Cordova Park Maid serve both houses and condos?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Cordova Park Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
