import type { EmdMicrositeConfig } from './types'

export const daytonaBeachMaidConfig: EmdMicrositeConfig = {
  domain: 'daytonabeachmaid.com',
  brandName: 'Daytona Beach Maid',
  city: 'Daytona Beach',
  regionLabel: 'Daytona Beach, FL',
  metaTitle: 'Daytona Beach Maid and Cleaning Service',
  metaDescription: 'Daytona Beach Maid — house cleaning across Seabreeze, Wilbur-by-the-Sea & Daytona Beach Shores starting at $49 per hour. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '29.2108', lng: '-81.0228' },
  introParagraphs: [
    "Daytona Beach Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across the 'World's Most Famous Beach' — a city known for the Daytona 500, Bike Week, and a beachfront that draws visitors year-round. If you live in Daytona Beach, you know how quickly ocean salt air and event-driven crowds can wear down a home. We built Daytona Beach Maid to answer exactly that problem: a local cleaning service that understands this city's rhythm and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Daytona Beach Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Daytona Beach.",
    "Whether you need a one-time deep clean before hosting guests for race week, a recurring weekly service for a busy Wilbur-by-the-Sea household, or a fast turnover clean for a beachfront condo between guests, Daytona Beach Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from Halifax River bungalows to oceanfront high-rises, and that range of experience shapes how we train every cleaner. Daytona Beach Maid was built around the reality that this city's tourism-driven calendar demands a different approach than a typical residential town.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Daytona Beach Maid exists because this motorsports-and-beach city's event calendar, oceanfront condos, and riverside neighborhoods make it its own world. So rather than force Daytona Beach into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this city.",
    "Every cleaner who works under the Daytona Beach Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Daytona Beach, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Daytona Beach as in Minneapolis. Daytona Beach Maid does not. We built our service around this city's event-driven tourism, salt-air beachfront, and riverside neighborhoods.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Daytona Beach Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Daytona Beach home on recurring visits.",
  ],
  challenges: [
    { title: 'Event-Week Turnover', body: "Daytona 500, Bike Week, and Spring Break bring surges of visitors and fast turnovers for beachfront rentals. Our scheduling flexes to meet event-week demand." },
    { title: 'Salt Air & Corrosion', body: "Daytona's oceanfront air carries fine salt particulate that settles on chrome fixtures, appliances, and window tracks. We use products chosen to cut salt residue without damaging finishes." },
    { title: 'Older Beachfront Buildings', body: "Many oceanfront condo buildings here are older properties that need extra attention to keep up appearances. We adjust our approach for aging fixtures and finishes." },
    { title: 'Humidity & Mold Prevention', body: "Central Florida coastal humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit." },
    { title: 'Vacation Rental Turnover', body: "As a major tourist destination, Daytona Beach homes and condos turn over fast between guests. Our scheduling supports same-day and next-day turnovers." },
    { title: 'Hurricane Season Readiness', body: "Storm season means shutter dust and post-storm cleanup. We offer flexible scheduling around storm prep and recovery." },
  ],
  neighborhoods: [
    { name: 'Seabreeze', blurb: "This historic neighborhood near the beach is a favorite for our weekly and bi-weekly recurring clients." },
    { name: 'Wilbur-by-the-Sea', blurb: "This quiet coastal community south of the main beach is home to many of our longest-running recurring clients." },
    { name: 'Beach Street / Riverfront', blurb: "Along the Halifax River, our riverfront clients trust Daytona Beach Maid for consistent, detail-first cleaning." },
    { name: 'Daytona Beach Shores', blurb: "Our oceanfront condo clients here rely on us for fast, reliable turnover cleaning between stays and event weeks." },
    { name: 'Halifax Harbor Area', blurb: "This established area near the marina is a regular stop for our bi-weekly and monthly cleaning plans." },
    { name: 'South Daytona Border', blurb: "This residential area trusts Daytona Beach Maid for everything from routine upkeep to deep cleans before family visits." },
  ],
  pricingExplainer: [
    "Daytona Beach Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy condo might only need the 2-hour minimum, while a riverfront home getting its first deep clean could run 5 hours or more.",
    "Recurring service is where Daytona Beach Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Daytona Beach.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Daytona Beach full-time residents and rental owners. Weekly service keeps salt and humidity buildup from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes or seasonal residences. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or event-week reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "We rent our condo out during race week and needed fast turnovers. Daytona Beach Maid has never made us miss a check-in.", name: 'Cynthia W.', neighborhood: 'Daytona Beach Shores' },
    { text: "We live in Wilbur-by-the-Sea and the salt air is brutal on our fixtures. They know exactly how to handle it.", name: 'Roy F.', neighborhood: 'Wilbur-by-the-Sea' },
    { text: "They've handled our Seabreeze home weekly for over a year — always the same reliable cleaner.", name: 'Angela C.', neighborhood: 'Seabreeze' },
    { text: "Our riverfront home needed a deep clean before hosting family for the race and they went above and beyond.", name: 'Kevin P.', neighborhood: 'Beach Street / Riverfront' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Daytona Beach?', answer: 'Daytona Beach Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Daytona Beach?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Daytona Beach Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, vacation rental turnovers, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Do you offer fast turnovers during Daytona 500 or Bike Week?', answer: "Yes — this is one of our specialties. We scale up crews around event weeks to keep rental turnovers on schedule." },
    { question: 'Do you clean vacation rentals near the beach?', answer: "Yes, with fast turnaround between guests." },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for closing on a riverfront home or ending a lease near the beach." },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or lockbox code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings, and earlier around major race and event weeks.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Daytona Beach Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of Daytona Beach do you serve?', answer: 'Seabreeze, Wilbur-by-the-Sea, Beach Street/Riverfront, Daytona Beach Shores, the Halifax Harbor area, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Daytona Beach.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Daytona Beach Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Daytona Beach Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a studio or small condo?', answer: 'Yes, our 2-hour minimum is usually perfect for a small unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Daytona Beach Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'Do you manage cleanings for a property management company?', answer: 'Yes, we regularly work with rental managers who oversee multiple Daytona Beach properties.' },
    { question: 'What if my condo building requires vendor registration?', answer: 'Send us your requirements ahead of time and we\'ll get registered.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Do you clean seasonal homes that sit empty for months?', answer: 'Yes, with arrival-prep cleanings timed to when you return for the season.' },
    { question: 'Is Daytona Beach Maid available on holidays?', answer: 'Text us to check holiday availability — this is a busy season for visitors.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Daytona Beach Maid serve both condos and houses?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Daytona Beach Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
