import type { EmdMicrositeConfig } from './types'

export const delandMaidConfig: EmdMicrositeConfig = {
  domain: 'delandmaid.com',
  brandName: 'DeLand Maid',
  city: 'DeLand',
  regionLabel: 'DeLand, FL',
  metaTitle: 'DeLand Maid and Cleaning Service',
  metaDescription: 'DeLand Maid — house cleaning across Historic Downtown DeLand, Victoria Park & Glenwood starting at $49 per hour. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '29.0283', lng: '-81.3031' },
  introParagraphs: [
    "DeLand Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across the 'Athens of Florida' — a Volusia County city known for its historic brick-lined downtown, Stetson University, and oak-canopied neighborhoods. If you live in DeLand, you know how quickly humidity and mature tree canopy can wear down a home. We built DeLand Maid to answer exactly that problem: a local cleaning service that understands this community and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. DeLand Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around DeLand.",
    "Whether you need a one-time deep clean before hosting family for a Stetson event, a recurring weekly service for a busy Victoria Park household, or a fast turnover clean for a rental near campus between leases, DeLand Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from historic downtown homes to newer construction in Victoria Park, and that range of experience shapes how we train every cleaner. DeLand Maid was built around the reality that this college town's mix of historic character and planned growth demands real range.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "DeLand Maid exists because this historic university town's brick-lined downtown, oak canopy, and mix of student rentals and family neighborhoods make it its own world. So rather than force DeLand into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this city.",
    "Every cleaner who works under the DeLand Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in DeLand, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in DeLand as in Minneapolis. DeLand Maid does not. We built our service around this college town's academic calendar, historic homes, and planned-community growth.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' DeLand Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your DeLand home on recurring visits.",
  ],
  challenges: [
    { title: 'University Turnover Season', body: "May move-outs and August move-ins around Stetson University create a crunch for landlords who need a rental cleaned fast between tenants. We scale up crews for turnover season." },
    { title: 'Historic Home Care', body: "Downtown DeLand's historic homes often have original hardwood floors and older fixtures that need gentler products than a newer build. We adjust our approach accordingly." },
    { title: 'Oak Canopy Debris', body: "DeLand's mature oak canopy drops leaves and debris year-round, tracking indoors constantly. We use techniques suited to lifting this kind of organic debris without smearing it." },
    { title: 'Humidity & Mildew', body: "Central Florida humidity creates mildew risk in bathrooms and closets. We pay close attention to these zones on every visit." },
    { title: 'Planned Community Standards', body: "Victoria Park and similar communities often have HOA expectations around presentation. We clean with those standards in mind." },
    { title: 'Hurricane Season Readiness', body: "Storm season means shutter dust and post-storm cleanup. We offer flexible scheduling around storm prep and recovery." },
  ],
  neighborhoods: [
    { name: 'Historic Downtown DeLand', blurb: "Brick-lined streets and historic homes make downtown DeLand one of the city's most requested areas for our weekly and bi-weekly recurring clients." },
    { name: 'Victoria Park', blurb: "This large planned community is home to many of our longest-running recurring clients, who value a consistent cleaner they can trust." },
    { name: 'Glenwood', blurb: "This established residential area trusts DeLand Maid for everything from routine upkeep to deep cleans." },
    { name: 'Near Stetson University', blurb: "Student rentals and faculty housing close to campus are where our turnover cleaning gets the most use, especially around semester transitions." },
    { name: 'Lake Winnemissett Area', blurb: "This lakefront neighborhood's homes call for extra attention to humidity and mold-prone zones." },
    { name: 'Spring Garden Ranch Area', blurb: "This established rural-residential area is a regular stop for our bi-weekly and monthly cleaning plans." },
  ],
  pricingExplainer: [
    "DeLand Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy near-campus rental might only need the 2-hour minimum, while a Victoria Park family home getting its first deep clean could run 5 hours or more.",
    "Recurring service is where DeLand Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of DeLand.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among DeLand families with kids or pets. Weekly service keeps clutter and dust from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households or grad students. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes or landlords managing a rental between tenants. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "We manage a few rentals near campus and needed a fast turnaround between leases. DeLand Maid has never made us miss a move-in date.", name: 'Patricia H.', neighborhood: 'Near Stetson University' },
    { text: "Our downtown home has original wood floors and they treated them with real care.", name: 'Nathan G.', neighborhood: 'Historic Downtown DeLand' },
    { text: "They've cleaned our Victoria Park home biweekly for months now — always the same reliable cleaner.", name: 'Amanda W.', neighborhood: 'Victoria Park' },
    { text: "Booked a deep clean before a family event and the house looked spotless when they got here.", name: 'Ricky B.', neighborhood: 'Glenwood' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in DeLand?', answer: 'DeLand Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in DeLand?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does DeLand Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, student rental turnovers, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Do you clean student rentals between leases?', answer: "Yes — this is one of our specialties around May move-outs and August move-ins near Stetson. Book early since turnover season fills up fast." },
    { question: 'Can you clean historic homes in downtown DeLand?', answer: "Absolutely. We use gentler products suited to original hardwood floors and vintage fixtures." },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for a landlord turning over a rental or a family relocating to Victoria Park." },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or door code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings, and earlier during May and August turnover season.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is DeLand Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of DeLand do you serve?', answer: 'Historic Downtown DeLand, Victoria Park, Glenwood, near Stetson University, the Lake Winnemissett area, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in DeLand.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, DeLand Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has DeLand Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a studio apartment or small rental?', answer: 'Yes, our 2-hour minimum is usually perfect for a small unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact DeLand Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'Do you clean rental properties for landlords with multiple units?', answer: 'Yes, we regularly work with landlords managing several near-campus rentals.' },
    { question: 'What if my community requires vendor registration?', answer: 'Send us your requirements ahead of time and we\'ll get registered.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Is DeLand Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does DeLand Maid serve both houses and apartments?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does DeLand Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
