import type { EmdMicrositeConfig } from './types'

export const destinMaidConfig: EmdMicrositeConfig = {
  domain: 'destinmaid.com',
  brandName: 'Destin Maid',
  city: 'Destin',
  regionLabel: 'Destin, FL',
  metaTitle: 'Destin Maid and Cleaning Service',
  metaDescription: 'Destin Maid — house cleaning across Crystal Beach, Kelly Plantation & Holiday Isle from $49/hr. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '30.3935', lng: '-86.4958' },
  introParagraphs: [
    "Destin Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across the 'World's Luckiest Fishing Village' — a Panhandle beach town known for sugar-white sand, emerald water, and one of the busiest vacation-rental markets in the state. If you live in Destin, you know how quickly that famous sand and salt air can wear down a home. We built Destin Maid to answer exactly that problem: a local cleaning service that understands Panhandle beach living and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Destin Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Destin.",
    "Whether you need a one-time deep clean before hosting guests near Destin Harbor, a recurring weekly service for a busy Kelly Plantation household, or a fast turnover clean for a Holiday Isle vacation rental between guests, Destin Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from harborfront condos to golf-course estates, and that range of experience shapes how we train every cleaner. Destin Maid was built around the reality that this town's tourism-driven rental market demands a different approach than a typical residential city.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Destin Maid exists because this Panhandle beach town's sugar-white sand, harbor culture, and vacation-rental economy make it its own world. So rather than force Destin into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this city.",
    "Every cleaner who works under the Destin Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Destin, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Destin as in Minneapolis. Destin Maid does not. We built our service around this town's sugar-sand beaches, harbor traffic, and one of the busiest short-term rental markets on the Gulf.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Destin Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Destin home on recurring visits.",
  ],
  challenges: [
    { title: 'Sugar Sand Everywhere', body: "Destin's famously fine, powdery sand tracks indoors more than typical beach sand and works into carpets and grout lines. We use techniques built for lifting fine sand without grinding it deeper in." },
    { title: 'Peak-Season Rental Turnover', body: "As one of the busiest vacation-rental markets on the Gulf, Destin condos and homes flip fast between summer guests. Our scheduling supports same-day and next-day turnovers." },
    { title: 'Salt Air & Corrosion', body: "Gulf-front air carries fine salt particulate that settles on chrome fixtures, appliances, and window tracks. We use products chosen to cut salt residue without damaging finishes." },
    { title: 'Harbor & Boat Traffic', body: "Homes near Destin Harbor track in more dirt and debris from dock access and boat traffic. We adjust our routine for homes with direct water access." },
    { title: 'Humidity & Mold Prevention', body: "Panhandle Gulf humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit." },
    { title: 'Hurricane Season Readiness', body: "Panhandle storm season means shutter dust and post-storm cleanup. We offer flexible scheduling around storm prep and recovery." },
  ],
  neighborhoods: [
    { name: 'Crystal Beach', blurb: "This laid-back beachfront neighborhood west of the harbor is a favorite for our weekly and bi-weekly recurring clients." },
    { name: 'Kelly Plantation', blurb: "This golf-course community is home to many of our longest-running recurring clients, who value a consistent cleaner they can trust." },
    { name: 'Regatta Bay', blurb: "Another established golf community, Regatta Bay's homes trust Destin Maid for everything from routine upkeep to deep cleans." },
    { name: 'Holiday Isle', blurb: "Sitting between the Gulf and the harbor, Holiday Isle's condos are where much of our vacation-rental turnover work happens." },
    { name: 'Destin Harbor', blurb: "Our harborfront clients rely on us for fast, reliable cleaning between charter-fishing seasons and boat-traffic dust." },
    { name: 'Destiny East', blurb: "This gated community's homes call for a first-clean approach tuned to newer construction and larger square footage." },
  ],
  pricingExplainer: [
    "Destin Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy Holiday Isle condo might only need the 2-hour minimum, while a Kelly Plantation estate getting its first deep clean could run 5 hours or more.",
    "Recurring service is where Destin Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Destin.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Destin full-time residents and rental owners. Weekly service keeps sand and salt buildup from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes or seasonal residences. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "Our sand is finer than most beach towns and it gets everywhere. Destin Maid is the first cleaner who's actually gotten it out of our grout.", name: 'Wendy F.', neighborhood: 'Holiday Isle' },
    { text: "We rent our condo out all summer and needed fast turnovers between guests. They've never made us miss a check-in.", name: 'Chris O.', neighborhood: 'Crystal Beach' },
    { text: "They've handled our Kelly Plantation home biweekly for over a year — always the same reliable cleaner.", name: 'Laura M.', neighborhood: 'Kelly Plantation' },
    { text: "We live near the harbor and the boat traffic tracks in a lot of dirt. Destin Maid keeps up with it easily.", name: 'Sam T.', neighborhood: 'Destin Harbor' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Destin?', answer: 'Destin Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Destin?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Destin Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, vacation rental turnovers, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Can you get Destin\'s sugar-white sand out of carpets and grout?', answer: "Yes — this is one of our specialties. Destin's fine sand needs a different technique than typical beach sand, and we use it on every visit." },
    { question: 'Do you clean vacation rentals near the beach?', answer: "Yes, with fast turnaround between guests — this is one of our most requested services during peak season." },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for closing on a harborfront condo or ending a lease near the beach." },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or lockbox code, especially for rental turnovers." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings, and earlier during peak summer season.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Destin Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of Destin do you serve?', answer: 'Crystal Beach, Kelly Plantation, Regatta Bay, Holiday Isle, Destin Harbor, Destiny East, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Destin.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Destin Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Destin Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a studio or small condo?', answer: 'Yes, our 2-hour minimum is usually perfect for a small unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Destin Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'Do you manage cleanings for a property management company?', answer: 'Yes, we regularly work with rental managers who oversee multiple Destin properties.' },
    { question: 'What if my condo building requires vendor registration?', answer: 'Send us your requirements ahead of time and we\'ll get registered.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Do you clean seasonal homes that sit empty for months?', answer: 'Yes, with arrival-prep cleanings timed to when you return for the season.' },
    { question: 'Is Destin Maid available on holidays?', answer: 'Text us to check holiday availability — this is a busy season for visitors.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger estates?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Destin Maid serve both condos and houses?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Destin Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
