import type { EmdMicrositeConfig } from './types'

export const downtownStPeteMaidConfig: EmdMicrositeConfig = {
  domain: 'downtownstpetemaid.com',
  brandName: 'Downtown St. Petersburg Maid',
  city: 'Downtown St. Petersburg',
  regionLabel: 'Downtown St. Petersburg, St. Petersburg, FL',
  metaTitle: 'Downtown St. Petersburg Maid — House Cleaning Service',
  metaDescription: 'Downtown St. Petersburg Maid — house cleaning near Beach Drive & the St. Pete Pier starting at $49 per hour. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '27.7730', lng: '-82.6360' },
  introParagraphs: [
    'Downtown St. Petersburg Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning for Downtown St. Petersburg and the surrounding St. Petersburg area, in Pinellas County. If you live near Beach Drive or the St. Pete Pier, you know what it takes to keep a home clean in this part of the Tampa Bay region — real Gulf Coast humidity, real wear, and a housing stock with real character. We built Downtown St. Petersburg Maid to answer exactly that: a local cleaning service that understands Downtown St. Petersburg living and shows up on time, every time.',
    'We\'re not a national franchise cold-calling from a call center in another state. Downtown St. Petersburg Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Downtown St. Petersburg.',
    'Whether you need a one-time deep clean before hosting family, a recurring weekly service for a busy household, or a fast turnover clean for a downtown condo lease turnover or a new owner\'s move-in clean, Downtown St. Petersburg Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.',
    'Our team has cleaned everything from historic Downtown St. Petersburg homes to newer builds elsewhere in St. Petersburg, and that range of experience shapes how we train every cleaner. Downtown St. Petersburg Maid was built around the reality that St. Petersburg\'s mix of established neighborhoods and coastal humidity demands real range.',
  ],
  ourStory: [
    'The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.',
    'Downtown St. Petersburg Maid exists because Downtown St. Petersburg — anchored by Beach Drive and the St. Pete Pier — deserves a cleaning brand tuned to it specifically, not folded anonymously into a citywide service. So rather than treat Downtown St. Petersburg as an afterthought, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this part of St. Petersburg.',
    'Every cleaner who works under the Downtown St. Petersburg Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.',
    'We\'re proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Downtown St. Petersburg, one cleaning at a time.',
  ],
  differentiation: [
    'National cleaning franchises operate the same playbook everywhere — the same checklist in Downtown St. Petersburg as in Minneapolis. Downtown St. Petersburg Maid does not. We built our service around St. Petersburg\'s housing stock, humidity, and the specific character of Downtown St. Petersburg.',
    'Franchise pricing also tends to hide the real cost behind a \'custom quote.\' Downtown St. Petersburg Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.',
    'And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Downtown St. Petersburg home on recurring visits.',
  ],
  challenges: [
    { title: 'Urban High-Rise Living', body: 'Downtown St. Petersburg\'s condo towers along Beach Drive and the waterfront have grown fast in the last decade — smaller square footage than a suburban home, but building access, elevators, and guest-parking logistics all matter more.' },
    { title: 'A Mix of Young Professionals & Retirees', body: 'Our downtown St. Pete clients split between young professionals working nearby and retirees who moved downtown for the walkability of Beach Drive and the Pier — both value flexible, reliable scheduling.' },
    { title: 'Humidity & Mold Prevention', body: 'St. Petersburg\'s Gulf Coast humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit in Downtown St. Petersburg.' },
    { title: 'Hurricane Season Readiness', body: 'Tampa Bay\'s storm season means shutter dust and post-storm cleanup for Downtown St. Petersburg just as much as anywhere else in St. Petersburg. We offer flexible scheduling around storm prep and recovery.' },
    { title: 'Tree & Landscaping Debris', body: 'Mature landscaping around Downtown St. Petersburg means pollen and leaf debris get tracked indoors more than in newer, less-landscaped subdivisions. We use techniques suited to lifting fine particulate without smearing it.' },
  ],
  neighborhoods: [
    { name: 'Old Northeast', blurb: 'St. Petersburg\'s flagship historic bungalow district, just north.' },
    { name: 'Snell Isle', blurb: 'The man-made luxury island north of downtown.' },
    { name: 'Historic Kenwood', blurb: 'A bungalow-heavy arts district west of downtown.' },
    { name: 'Grand Central District', blurb: 'The Central Avenue corridor just west, known for its shops and restaurants.' },
    { name: 'Old Southeast', blurb: 'A historic neighborhood just south of downtown.' },
  ],
  pricingExplainer: [
    'Downtown St. Petersburg Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.',
    'What determines how many hours your home needs? Mainly size and condition. A tidy Downtown St. Petersburg-area home might only need the 2-hour minimum, while a larger property getting its first deep clean could run 5 hours or more.',
    'Recurring service is where Downtown St. Petersburg Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.',
    'One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Downtown St. Petersburg and greater St. Petersburg.',
  ],
  firstVisitSteps: [
    'Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.',
    'We confirm your appointment window by text, usually within 15 minutes.',
    'Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.',
    'We do a final walkthrough before wrapping up. If anything doesn\'t meet your expectations, tell us within 24 hours and we\'ll send someone back at no extra charge.',
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: 'The most popular plan among Downtown St. Petersburg-area families with kids or pets. Weekly service keeps clutter and dust from getting ahead of you, earning 20% off.' },
    { frequency: 'Bi-Weekly', body: 'A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%.' },
    { frequency: 'Monthly', body: 'Best suited to light-use homes. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount.' },
    { frequency: 'One-Time', body: 'Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge.' },
  ],
  testimonials: [
    { text: 'Our home near Beach Drive needed real care, not a rushed once-over. They got it.', name: 'Diane H.', neighborhood: 'Downtown St. Petersburg' },
    { text: 'They\'ve cleaned our place weekly for months now — always the same reliable cleaner.', name: 'Walter E.', neighborhood: 'Historic Kenwood' },
    { text: 'We needed a fast turnaround and they delivered, no excuses.', name: 'Cynthia O.', neighborhood: 'Grand Central District' },
    { text: 'Booked a deep clean before hosting family and they went above and beyond.', name: 'Roger P.', neighborhood: 'Old Southeast' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Downtown St. Petersburg?', answer: 'Downtown St. Petersburg Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'How do I book a cleaning in Downtown St. Petersburg?', answer: 'Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning.' },
    { question: 'Do you offer move-in/move-out cleaning in Downtown St. Petersburg?', answer: 'Yes — perfect for a downtown condo lease turnover or a new owner\'s move-in clean.' },
    { question: 'What areas near Downtown St. Petersburg do you serve?', answer: 'Downtown St. Petersburg, Old Northeast, Snell Isle, Historic Kenwood, Grand Central District, Old Southeast, and surrounding St. Petersburg neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Downtown St. Petersburg or greater St. Petersburg.' },
    { question: 'Can you handle homes with urban high-rise living?', answer: 'Downtown St. Petersburg\'s condo towers along Beach Drive and the waterfront have grown fast in the last decade — smaller square footage than a suburban home, but building access, elevators, and guest-parking logistics all matter more.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: 'We charge by the hour, not a flat rate, so pricing stays fair for every home size.' },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Can I customize what gets cleaned?', answer: 'Of course — just tell us your priorities when booking.' },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: 'Yes, we prioritize consistency for recurring clients.' },
    { question: 'Will I need to be home during the cleaning?', answer: 'It\'s up to you — many clients leave a key or door code.' },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'Do you have reviews I can read?', answer: 'Yes, Downtown St. Petersburg Maid carries The Florida Maid\'s 5.0-star Google rating.' },
    { question: 'How long has Downtown St. Petersburg Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a smaller home or apartment?', answer: 'Yes, our 2-hour minimum is usually perfect for a smaller unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Downtown St. Petersburg Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'Do you manage cleanings for landlords with multiple rentals?', answer: 'Yes, we regularly work with landlords managing several properties around Downtown St. Petersburg and St. Petersburg.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Is Downtown St. Petersburg Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Downtown St. Petersburg Maid serve both houses and apartments?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Downtown St. Petersburg Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
