import type { EmdMicrositeConfig } from './types'

export const ferryPassMaidConfig: EmdMicrositeConfig = {
  domain: 'ferrypassmaid.com',
  brandName: 'Ferry Pass Maid',
  city: 'Pensacola',
  regionLabel: 'Ferry Pass, Pensacola, FL',
  metaTitle: 'Ferry Pass Maid and Cleaning Service',
  metaDescription: 'Ferry Pass Maid — house cleaning near Nine Mile Rd, UWF & I-10, Pensacola, FL from $49/hr. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '30.5192', lng: '-87.2251' },
  introParagraphs: [
    "Ferry Pass Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning for Ferry Pass and the surrounding Pensacola area — a fast-growing suburban stretch near I-10, Nine Mile Road, and the University of West Florida. If you live in Ferry Pass, you know how quickly a busy household with student housing or growing subdivisions nearby can get ahead of your cleaning schedule. We built Ferry Pass Maid to answer exactly that problem: a local cleaning service that understands Pensacola living and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Ferry Pass Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Ferry Pass and the rest of Pensacola.",
    "Whether you need a one-time deep clean before hosting family, a recurring weekly service for a busy household near UWF, or a fast turnover clean for a student rental between semesters, Ferry Pass Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from newer Ferry Pass subdivisions to homes elsewhere in Pensacola, and that range of experience shapes how we train every cleaner. Ferry Pass Maid was built around the reality that this growing, well-connected part of Pensacola demands real range.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Ferry Pass Maid exists because this fast-growing pocket of Pensacola near I-10 and UWF deserves a cleaning brand tuned to it specifically. So rather than treat Ferry Pass as an afterthought, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this part of Pensacola.",
    "Every cleaner who works under the Ferry Pass Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Ferry Pass and greater Pensacola, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Ferry Pass as in Minneapolis. Ferry Pass Maid does not. We built our service around this fast-growing part of Pensacola's newer subdivisions, student housing turnover, and everyday Gulf humidity.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Ferry Pass Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Ferry Pass-area home on recurring visits.",
  ],
  challenges: [
    { title: 'New-Construction Turnover', body: "Newer Ferry Pass subdivisions mean frequent move-ins with drywall dust and construction debris still lingering. We handle first-clean move-in service regularly." },
    { title: 'Humidity & Mold Prevention', body: "Pensacola's Gulf Coast humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit." },
    { title: 'Student Rental Turnover', body: "With UWF nearby, some Ferry Pass rentals see semester-based tenant turnover. We offer fast move-in/move-out cleaning to keep properties ready." },
    { title: 'Pine & Oak Debris', body: "Wooded lots throughout Ferry Pass mean pine needles and leaf debris get tracked indoors regularly. We use techniques suited to lifting fine particulate without smearing it." },
    { title: 'Hurricane Season Readiness', body: "Panhandle storm season means shutter dust and post-storm cleanup. We offer flexible scheduling around storm prep and recovery." },
  ],
  neighborhoods: [
    { name: 'Ferry Pass', blurb: "Anchored by Nine Mile Road and the I-10 corridor, this growing suburban area is where Ferry Pass Maid focuses most of its weekly and bi-weekly recurring service." },
    { name: 'University Area', blurb: "Near UWF, our clients rely on us for reliable scheduling around academic-year turnover." },
    { name: 'Cordova Park', blurb: "South near Bayou Blvd, Cordova Park's established homes are a regular stop for our recurring cleaning plans." },
    { name: 'Brent', blurb: "Just south along N Davis Highway, Brent's established homes trust us for consistent, reliable service." },
    { name: 'East Hill', blurb: "Closer to downtown, East Hill's historic bungalows call for the same care and attention we bring to every Pensacola-area home." },
    { name: 'Gonzalez', blurb: "This neighboring community shares much of the same suburban housing stock and gets the same careful attention." },
  ],
  pricingExplainer: [
    "Ferry Pass Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy Ferry Pass townhome might only need the 2-hour minimum, while a larger subdivision home getting its first deep clean could run 5 hours or more.",
    "Recurring service is where Ferry Pass Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Ferry Pass and greater Pensacola.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Ferry Pass families with kids or pets. Weekly service keeps clutter and dust from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "We just closed on a new build in Ferry Pass and they cleared out all the construction dust before move-in.", name: 'Alicia R.', neighborhood: 'Ferry Pass' },
    { text: "They've cleaned our place near UWF weekly for months now — always the same reliable cleaner.", name: 'Brian H.', neighborhood: 'Ferry Pass' },
    { text: "We manage a rental near campus and needed fast turnaround between tenants. They delivered.", name: 'Sandra L.', neighborhood: 'University Area' },
    { text: "Booked a deep clean before hosting family and they went above and beyond.", name: 'Derek W.', neighborhood: 'Cordova Park' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Ferry Pass?', answer: 'Ferry Pass Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Ferry Pass?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Ferry Pass Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, rental turnovers, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Do you clean new-construction homes?', answer: 'Yes, with a first-clean approach tuned to clearing out drywall dust and construction debris.' },
    { question: 'Do you offer move-in/move-out cleaning for student rentals near UWF?', answer: "Yes — we regularly work around semester-based turnover for landlords and students near campus." },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or door code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Ferry Pass Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas near Ferry Pass do you serve?', answer: 'Ferry Pass, the UWF/university area, Cordova Park, Brent, East Hill, Gonzalez, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Ferry Pass or greater Pensacola.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Ferry Pass Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Ferry Pass Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a townhome or smaller unit?', answer: 'Yes, our 2-hour minimum is usually perfect for a smaller unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Ferry Pass Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'Do you manage cleanings for landlords with multiple rentals?', answer: 'Yes, we regularly work with landlords managing several Ferry Pass-area properties.' },
    { question: 'What if my community has a gate or HOA check-in?', answer: 'Just let us know your community\'s procedures when booking and we\'ll build in the extra time.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Is Ferry Pass Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents or builders?', answer: 'Yes, we regularly clean staged listings and model homes in new communities.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Ferry Pass Maid serve both houses and townhomes?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Ferry Pass Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
