import type { EmdMicrositeConfig } from './types'

export const fortMyersMaidConfig: EmdMicrositeConfig = {
  domain: 'fortmyersmaid.com',
  brandName: 'Fort Myers Maid',
  city: 'Fort Myers',
  regionLabel: 'Fort Myers, FL',
  metaTitle: 'Fort Myers Maid and Cleaning Service',
  metaDescription: 'Fort Myers Maid — house cleaning across McGregor Boulevard, the River District & Gateway starting at $49 per hour. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '26.6406', lng: '-81.8723' },
  introParagraphs: [
    "Fort Myers Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across a city defined by royal palm-lined boulevards, a revitalized historic downtown, and a canal network that laces through nearly every neighborhood. If you live in Fort Myers, you know how quickly Southwest Florida humidity and canal-front living can wear down a home. We built Fort Myers Maid to answer exactly that problem: a local cleaning service that understands this region and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Fort Myers Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Fort Myers.",
    "Whether you need a one-time deep clean before hosting guests along McGregor Boulevard, a recurring weekly service for a busy Iona household, or a fast turnover clean for a River District condo between guests, Fort Myers Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from historic downtown lofts to newer construction in Gateway, and that range of experience shapes how we train every cleaner. Fort Myers Maid was built around the reality that Southwest Florida's mix of historic character and rapid growth demands real flexibility.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Fort Myers Maid exists because this Southwest Florida city's canal network, historic River District, and rapidly growing suburbs make it its own world. So rather than force Fort Myers into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this city.",
    "Every cleaner who works under the Fort Myers Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Fort Myers, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Fort Myers as in Minneapolis. Fort Myers Maid does not. We built our service around this city's canal-front homes, historic downtown, and hurricane-aware maintenance needs.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Fort Myers Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Fort Myers home on recurring visits.",
  ],
  challenges: [
    { title: 'Canal & Waterfront Homes', body: "Fort Myers' extensive canal network means many homes track in more dirt and debris from dock access and boat traffic. We adjust our routine for homes with direct water access." },
    { title: 'Humidity & Mold Prevention', body: "Southwest Florida humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit." },
    { title: 'Hurricane Season Readiness', body: "Southwest Florida takes storm season seriously. We offer flexible scheduling around storm prep and post-storm cleanup, and understand the extra care hurricane-resilient homes need." },
    { title: 'Historic Home Care', body: "River District and McGregor Boulevard homes often have original details that need gentler products than a newer build. We adjust our approach accordingly." },
    { title: 'New-Construction Dust', body: "Fast-growing communities like Gateway mean many clients move into homes still shedding drywall dust and construction debris. We adjust our first-clean approach for newly built homes." },
    { title: 'Snowbird Turnover', body: "Many Fort Myers condos and homes sit empty for months at a time during off-season. We offer arrival-prep cleanings timed to when owners return." },
  ],
  neighborhoods: [
    { name: 'McGregor Boulevard', blurb: "This iconic royal palm-lined corridor is home to many of our longest-running recurring clients in some of Fort Myers' most historic homes." },
    { name: 'River District (Downtown)', blurb: "Fort Myers' revitalized historic downtown along the Caloosahatchee is where much of our condo and loft turnover cleaning happens." },
    { name: 'Iona', blurb: "This established residential area between Fort Myers and Sanibel is a favorite for our weekly and bi-weekly recurring clients." },
    { name: 'Whiskey Creek', blurb: "This golf-course community trusts Fort Myers Maid for everything from routine upkeep to deep cleans before family visits." },
    { name: 'Gateway', blurb: "This master-planned community on the east side calls for a first-clean approach tuned to newer construction and larger square footage." },
    { name: 'Town and River', blurb: "This canal-laced waterfront neighborhood's homes call for extended deep-cleaning sessions and careful attention to boat-traffic debris." },
  ],
  pricingExplainer: [
    "Fort Myers Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy River District condo might only need the 2-hour minimum, while a McGregor Boulevard estate getting its first deep clean could run 5 hours or more.",
    "Recurring service is where Fort Myers Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Fort Myers.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Fort Myers families with kids or pets. Weekly service keeps humidity and clutter buildup from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes or seasonal residences. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "We live on a canal in Town and River and the boat traffic tracks in a lot of dirt. Fort Myers Maid keeps up with it easily.", name: 'Julie R.', neighborhood: 'Town and River' },
    { text: "We moved into a new build in Gateway and they cleared out every bit of construction dust before we unpacked.", name: 'Aaron K.', neighborhood: 'Gateway' },
    { text: "They've handled our McGregor Boulevard home weekly for over a year — always the same reliable cleaner.", name: 'Dorothy L.', neighborhood: 'McGregor Boulevard' },
    { text: "We come down seasonally and they get our Iona condo ready before every arrival. Never a hitch.", name: 'Frank D.', neighborhood: 'Iona' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Fort Myers?', answer: 'Fort Myers Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Fort Myers?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Fort Myers Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, Airbnb turnovers, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for closing on a canal-front home or ending a lease downtown." },
    { question: 'Do you clean new-construction homes?', answer: 'Yes, with a first-clean approach tuned to clearing out drywall dust and construction debris in communities like Gateway.' },
    { question: 'Do you clean Airbnb and short-term rentals?', answer: 'Yes, with fast turnaround between guests.' },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or gate code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Fort Myers Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of Fort Myers do you serve?', answer: 'McGregor Boulevard, the River District, Iona, Whiskey Creek, Gateway, Town and River, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Fort Myers.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Fort Myers Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Fort Myers Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a condo or smaller unit?', answer: 'Yes, our 2-hour minimum is usually perfect for a smaller unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Fort Myers Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'Do you clean canal-front and waterfront homes?', answer: 'Yes, we regularly service waterfront properties across Town and River and Iona.' },
    { question: 'What if my community requires vendor registration?', answer: 'Send us your requirements ahead of time and we\'ll get registered.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Do you clean seasonal homes that sit empty for months?', answer: 'Yes, with arrival-prep cleanings timed to when you return for the season.' },
    { question: 'Is Fort Myers Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Fort Myers Maid serve both condos and houses?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Fort Myers Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
