import type { EmdMicrositeConfig } from './types'

export const gainesvilleMaidConfig: EmdMicrositeConfig = {
  domain: 'gainesvillemaid.com',
  brandName: 'Gainesville Maid',
  city: 'Gainesville',
  regionLabel: 'Gainesville, FL',
  metaTitle: 'Gainesville Maid and Cleaning Service',
  metaDescription: 'Gainesville Maid — house cleaning across Haile Plantation, the Duckpond & Turkey Creek from $49/hr. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '29.6516', lng: '-82.3248' },
  introParagraphs: [
    "Gainesville Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across a city that runs on a college-town calendar — families in Haile Plantation, historic homes in the Duckpond, and a rotating population of students, faculty, and renters near the University of Florida. If you live in Gainesville, you know the rhythm: move-in surges in August, move-out chaos in May, and everything in between. We built Gainesville Maid to answer exactly that problem: a local cleaning service that understands the town-and-gown calendar and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Gainesville Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Gainesville.",
    "Whether you need a one-time deep clean before hosting family for a Gators game weekend, a recurring weekly service for a busy Haile Plantation household, or a fast turnover clean for a student rental near campus between leases, Gainesville Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from historic Duckpond bungalows to newer construction in Kanapaha, and that range of experience shapes how we train every cleaner. Gainesville Maid was built around the reality that a college town's housing stock is more varied — and turns over faster — than almost anywhere else in Florida.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Gainesville Maid exists because this city's mix of historic neighborhoods, family suburbs, and a massive student rental market make it its own world. So rather than force Gainesville into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this city.",
    "Every cleaner who works under the Gainesville Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Gainesville, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Gainesville as in Minneapolis. Gainesville Maid does not. We built our service around this city's academic calendar, its mix of historic and new construction, and its high volume of rental turnovers.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Gainesville Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Gainesville home on recurring visits.",
  ],
  challenges: [
    { title: 'Student Turnover Season', body: "May move-outs and August move-ins create a crunch for landlords and parents who need a rental cleaned fast between tenants. We scale up crews for turnover season so timelines don't slip." },
    { title: 'Red Clay & Pollen', body: "North Central Florida's red clay soil and heavy spring pollen track into entryways and settle on windowsills. We use products and techniques suited to lifting fine particulate without smearing it." },
    { title: 'Historic Home Care', body: "Duckpond and other historic-district homes often have original hardwood floors, plaster walls, and older fixtures that need gentler products than a newer build. We adjust our approach accordingly." },
    { title: 'Humidity & Mildew', body: "North Florida humidity still creates mildew risk in bathrooms and closets, even without coastal salt air. We pay close attention to these zones on every visit." },
    { title: 'Game Day Scheduling', body: "Home football weekends bring a surge of house guests and tailgate cleanup. We offer flexible pre- and post-game scheduling for hosts." },
    { title: 'Large Lot & Rural-Adjacent Homes', body: "Many Gainesville homes sit on larger wooded lots that track in more leaves, sand, and debris than a typical suburban lot. We adjust cleaning time estimates for these properties." },
  ],
  neighborhoods: [
    { name: 'Haile Plantation', blurb: "This large planned community on the southwest side is one of Gainesville's most established family neighborhoods, and a favorite for our weekly and bi-weekly recurring clients." },
    { name: 'The Duckpond', blurb: "Gainesville's historic district is full of century-old homes with original details. We clean here with extra care for original wood floors and vintage fixtures." },
    { name: 'Turkey Creek', blurb: "This golf-course community in southwest Gainesville is home to many of our longest-running recurring clients, who value a consistent cleaner they can trust." },
    { name: 'Kanapaha', blurb: "Newer construction near Kanapaha Botanical Gardens means larger square footage and more surfaces to cover — we regularly staff two-person teams for these homes." },
    { name: 'Millhopper', blurb: "This established neighborhood in northwest Gainesville trusts Gainesville Maid for everything from routine upkeep to deep cleans before family visits." },
    { name: 'Near UF / Midtown', blurb: "Student rentals and faculty housing close to campus are where our turnover cleaning gets the most use, especially around semester transitions." },
  ],
  pricingExplainer: [
    "Gainesville Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy near-campus rental might only need the 2-hour minimum, while a Haile Plantation family home getting its first deep clean could run 5 hours or more.",
    "Recurring service is where Gainesville Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Gainesville.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Gainesville families with kids or pets. Weekly service keeps clutter and dust from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households or grad students. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes or landlords managing a rental between tenants. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "We manage a few rentals near campus and needed a fast turnaround between leases. Gainesville Maid has never made us miss a move-in date.", name: 'Carla D.', neighborhood: 'Near UF' },
    { text: "Our Duckpond bungalow has original wood floors and they treated them with real care. Not every cleaning company would bother.", name: 'James P.', neighborhood: 'Duckpond' },
    { text: "They've cleaned our Haile Plantation home biweekly for months now — always the same reliable cleaner.", name: 'Melissa T.', neighborhood: 'Haile Plantation' },
    { text: "Booked a deep clean before a Gators game weekend with family in town. House looked spotless when they got here.", name: 'Ryan K.', neighborhood: 'Turkey Creek' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Gainesville?', answer: 'Gainesville Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Gainesville?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Gainesville Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, student rental turnovers, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Do you clean student rentals between leases?', answer: "Yes — this is one of our specialties around May move-outs and August move-ins. Book early since turnover season fills up fast." },
    { question: 'Can you clean historic homes in the Duckpond?', answer: "Absolutely. We use gentler products suited to original hardwood floors, plaster walls, and vintage fixtures." },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for a landlord turning over a rental or a family relocating for a UF faculty position." },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or door code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings, and earlier during May and August turnover season.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Gainesville Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of Gainesville do you serve?', answer: 'Haile Plantation, the Duckpond, Turkey Creek, Kanapaha, Millhopper, near-campus rentals, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Gainesville.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Gainesville Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Gainesville Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a studio apartment or small rental?', answer: 'Yes, our 2-hour minimum is usually perfect for a small unit.' },
    { question: 'Do you clean for parties or events, like game day tailgates?', answer: 'Yes, pre- and post-event cleaning available, including game-day turnarounds.' },
    { question: 'How do I contact Gainesville Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'Do you clean rental properties for landlords with multiple units?', answer: 'Yes, we regularly work with landlords managing several student rentals near campus.' },
    { question: 'What if my rental has strict lease-turnover deadlines?', answer: 'Tell us your deadline when booking — turnover cleanings are one of our specialties and we plan crew size around your timeline.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Do you clean vacation or seasonal homes that sit empty?', answer: 'Yes, with arrival-prep cleanings before you visit.' },
    { question: 'Is Gainesville Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Gainesville Maid serve both houses and apartments?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Gainesville Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
    { question: 'Do you clean during finals week or move-out crunch?', answer: 'Yes — book as early as possible since this is our busiest stretch of the year.' },
  ],
}
