import type { EmdMicrositeConfig } from './types'

export const gulfBreezeMaidConfig: EmdMicrositeConfig = {
  domain: 'gulfbreezemaid.com',
  brandName: 'Gulf Breeze Maid',
  city: 'Pensacola',
  regionLabel: 'Gulf Breeze, Santa Rosa County, Pensacola, FL',
  metaTitle: 'Gulf Breeze Maid and Cleaning Service',
  metaDescription: 'Gulf Breeze Maid — house cleaning across Tiger Point & Shoreline Park, greater Pensacola, FL from $49/hr. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '30.3585', lng: '-87.1636' },
  introParagraphs: [
    "Gulf Breeze Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning for Gulf Breeze and the greater Pensacola area — a quiet peninsula town across the bay from downtown Pensacola, tucked between Pensacola Bay and Santa Rosa Sound. If you live in Gulf Breeze, you know how quickly salt air and coastal humidity can wear down a home. We built Gulf Breeze Maid to answer exactly that problem: a local cleaning service that understands life across the bay from Pensacola and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Gulf Breeze Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Gulf Breeze and the rest of the greater Pensacola area.",
    "Whether you need a one-time deep clean before hosting family, a recurring weekly service for a busy Tiger Point household, or a fast turnover clean for a waterfront rental between guests, Gulf Breeze Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from quiet Gulf Breeze family homes to waterfront properties along Santa Rosa Sound, and that range of experience shapes how we train every cleaner. Gulf Breeze Maid was built around the reality that this peninsula town's mix of coastal exposure and quiet residential streets demands real range.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Gulf Breeze Maid exists because this quiet peninsula town across the bay from Pensacola deserves a cleaning brand tuned to it specifically. So rather than treat Gulf Breeze as an afterthought, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this part of the greater Pensacola area.",
    "Every cleaner who works under the Gulf Breeze Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Gulf Breeze and greater Pensacola, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Gulf Breeze as in Minneapolis. Gulf Breeze Maid does not. We built our service around this peninsula town's waterfront properties, quiet residential streets, and everyday Gulf humidity.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Gulf Breeze Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Gulf Breeze home on recurring visits.",
  ],
  challenges: [
    { title: 'Salt Air & Corrosion', body: "Gulf Breeze sits between Pensacola Bay and Santa Rosa Sound, where fine salt particulate settles on chrome fixtures, appliances, and window tracks. We use products chosen to cut salt residue without damaging finishes." },
    { title: 'Humidity & Mold Prevention', body: "Coastal Gulf humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit." },
    { title: 'Waterfront & Dock Debris', body: "Homes near Santa Rosa Sound track in more sand, dock debris, and boat traffic dirt than inland properties. We adjust our routine for homes with direct water access." },
    { title: 'Vacation & Second-Home Upkeep', body: "Some Gulf Breeze properties sit empty for stretches between visits. We offer arrival-prep cleanings so a second home or vacation property is ready the moment you walk in." },
    { title: 'Hurricane Season Readiness', body: "Panhandle storm season means shutter dust and post-storm cleanup for a bayside town like Gulf Breeze. We offer flexible scheduling around storm prep and recovery." },
  ],
  neighborhoods: [
    { name: 'Tiger Point', blurb: "This established golf-course community is home to many of our longest-running recurring clients, who value a consistent cleaner they can trust." },
    { name: 'Shoreline Park Area', blurb: "Close to Santa Rosa Sound, our waterfront clients here rely on us for careful attention to salt residue and dock-tracked debris." },
    { name: 'Gulf Breeze Proper', blurb: "Anchored around Highway 98, this quiet peninsula community is where Gulf Breeze Maid focuses most of its weekly and bi-weekly recurring service." },
    { name: 'Pensacola Beach', blurb: "Just south across the Bob Sikes Bridge, our Pensacola Beach clients trust us for fast, reliable turnover cleaning between summer stays." },
    { name: 'Navarre', blurb: "East along Highway 98, this neighboring coastal community shares much of the same salt-air maintenance needs." },
    { name: 'Downtown Pensacola', blurb: "Across the 3 Mile Bridge, our downtown Pensacola clients rely on us for reliable, consistent cleaning." },
  ],
  pricingExplainer: [
    "Gulf Breeze Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy Gulf Breeze condo might only need the 2-hour minimum, while a Tiger Point estate getting its first deep clean could run 5 hours or more.",
    "Recurring service is where Gulf Breeze Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Gulf Breeze and the greater Pensacola area.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Gulf Breeze families with kids or pets. Weekly service keeps clutter and dust from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes or seasonal residences. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "Our Tiger Point home overlooks the golf course and they always leave it spotless.", name: 'Karen L.', neighborhood: 'Tiger Point' },
    { text: "We keep a second home in Gulf Breeze and they have it ready every time we arrive.", name: 'Robert F.', neighborhood: 'Gulf Breeze' },
    { text: "Salt air was destroying our fixtures until they started coming regularly.", name: 'Patricia N.', neighborhood: 'Shoreline Park Area' },
    { text: "Booked a deep clean before hosting family and they went above and beyond.", name: 'Michael D.', neighborhood: 'Gulf Breeze' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Gulf Breeze?', answer: 'Gulf Breeze Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Gulf Breeze?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Gulf Breeze Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, vacation rental turnovers, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Do you clean waterfront and Santa Rosa Sound-front homes?', answer: 'Yes, we regularly service waterfront properties along Santa Rosa Sound and Pensacola Bay.' },
    { question: 'Do you clean vacation homes that sit empty?', answer: 'Yes, with arrival-prep cleanings before you visit.' },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or door code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Gulf Breeze Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas near Gulf Breeze do you serve?', answer: 'Gulf Breeze, Tiger Point, the Shoreline Park area, Pensacola Beach, Navarre, downtown Pensacola, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Gulf Breeze or the greater Pensacola area.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Gulf Breeze Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Gulf Breeze Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a condo or smaller unit?', answer: 'Yes, our 2-hour minimum is usually perfect for a smaller unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Gulf Breeze Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'What if my condo building requires vendor registration?', answer: 'Send us your requirements ahead of time and we\'ll get registered.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Is Gulf Breeze Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Gulf Breeze Maid serve both houses and condos?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Gulf Breeze Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
