import type { EmdMicrositeConfig } from './types'

export const longwoodMaidConfig: EmdMicrositeConfig = {
  domain: 'longwoodmaid.com',
  brandName: 'Longwood Maid',
  city: 'Longwood',
  regionLabel: 'Longwood, FL',
  metaTitle: 'Longwood Maid and Cleaning Service',
  metaDescription: 'Longwood Maid — house cleaning across Sabal Point, The Woodlands & Sweetwater Oaks starting at $49 per hour. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '28.7031', lng: '-81.3384' },
  introParagraphs: [
    "Longwood Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across one of Seminole County's most historic small towns — a community of oak-canopied streets, lakefront neighborhoods near the Wekiva River, and a preserved Victorian-era downtown. If you live in Longwood, you know how quickly mature tree canopy and Florida humidity can wear down a home. We built Longwood Maid to answer exactly that problem: a local cleaning service that understands this community and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Longwood Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Longwood.",
    "Whether you need a one-time deep clean before hosting guests, a recurring weekly service for a busy Sabal Point household, or a fast turnover clean for a rental between tenants, Longwood Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from historic downtown cottages to lakefront estates near Wekiva Cove, and that range of experience shapes how we train every cleaner. Longwood Maid was built around the reality that this community's mix of historic character and lakefront living demands real range.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Longwood Maid exists because this historic Seminole County town's oak canopy, lakefront neighborhoods, and preserved downtown make it its own world. So rather than force Longwood into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this city.",
    "Every cleaner who works under the Longwood Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Longwood, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Longwood as in Minneapolis. Longwood Maid does not. We built our service around this town's historic homes, lakefront neighborhoods, and mature tree canopy.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Longwood Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Longwood home on recurring visits.",
  ],
  challenges: [
    { title: 'Oak Canopy Debris', body: "Longwood's mature oak canopy drops leaves and debris year-round, tracking indoors constantly. We use techniques suited to lifting this kind of organic debris without smearing it." },
    { title: 'Historic Home Care', body: "Historic Longwood's Victorian-era homes often have original hardwood floors and older fixtures that need gentler products than a newer build. We adjust our approach accordingly." },
    { title: 'Lakefront Humidity & Mold Prevention', body: "Longwood's many lakes and proximity to the Wekiva River mean humidity stays high near the water. We pay close attention to bathrooms and closets, the highest-risk zones for mildew." },
    { title: 'Gated Community Standards', body: "Sabal Point and Alaqua often have HOA expectations around presentation and consistency. We clean with those standards in mind." },
    { title: 'Large Lot Homes', body: "Many Longwood homes sit on larger wooded lots that track in more leaves, sand, and debris than a typical suburban lot. We adjust cleaning time estimates for these properties." },
    { title: 'Hurricane Season Readiness', body: "Storm season means shutter dust and post-storm cleanup. We offer flexible scheduling around storm prep and recovery." },
  ],
  neighborhoods: [
    { name: 'Historic Longwood', blurb: "Oak-lined streets and Victorian-era homes make historic Longwood one of the city's most requested areas for our weekly and bi-weekly recurring clients." },
    { name: 'Sabal Point', blurb: "This gated community is home to many of our longest-running recurring clients, who value a consistent cleaner they can trust." },
    { name: 'The Woodlands', blurb: "This established residential area trusts Longwood Maid for everything from routine upkeep to deep cleans." },
    { name: 'Alaqua', blurb: "This upscale gated golf community's homes call for cleaning with real attention to presentation standards." },
    { name: 'Sweetwater Oaks', blurb: "This lakefront neighborhood's homes call for extra attention to humidity and mold-prone zones." },
    { name: 'Wekiva Cove', blurb: "Close to the Wekiva River, our Wekiva Cove clients trust us for consistent, detail-first cleaning." },
  ],
  pricingExplainer: [
    "Longwood Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy historic cottage might only need the 2-hour minimum, while a Sabal Point estate getting its first deep clean could run 5 hours or more.",
    "Recurring service is where Longwood Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Longwood.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Longwood families with kids or pets. Weekly service keeps clutter and dust from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "Our historic cottage has original wood floors and they treated them with real care.", name: 'Eleanor P.', neighborhood: 'Historic Longwood' },
    { text: "Our Sabal Point home has real HOA standards and Longwood Maid always meets them.", name: 'Todd W.', neighborhood: 'Sabal Point' },
    { text: "They've handled our Sweetwater Oaks home weekly for over a year — always the same reliable cleaner.", name: 'Melinda S.', neighborhood: 'Sweetwater Oaks' },
    { text: "Booked a deep clean before hosting family and they went above and beyond.", name: 'Ray D.', neighborhood: 'The Woodlands' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Longwood?', answer: 'Longwood Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Longwood?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Longwood Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Can you clean historic homes in downtown Longwood?', answer: "Absolutely. We use gentler products suited to original hardwood floors and vintage fixtures." },
    { question: 'Can you clean homes in gated communities like Sabal Point or Alaqua?', answer: "Absolutely. We're familiar with the presentation standards these communities expect." },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for closing on a new home or moving out of a rental." },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or gate code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Longwood Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of Longwood do you serve?', answer: 'Historic Longwood, Sabal Point, The Woodlands, Alaqua, Sweetwater Oaks, Wekiva Cove, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Longwood.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Longwood Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Longwood Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a townhome or smaller unit?', answer: 'Yes, our 2-hour minimum is usually perfect for a smaller unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Longwood Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'What if my community has a gate or HOA check-in?', answer: 'Just let us know your community\'s procedures when booking and we\'ll build in the extra time.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Is Longwood Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Longwood Maid serve both houses and townhomes?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Longwood Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
