import type { EmdMicrositeConfig } from './types'

export const orlandoMaidConfig: EmdMicrositeConfig = {
  domain: 'orlandoflmaid.com',
  brandName: 'Orlando Maid',
  city: 'Orlando',
  regionLabel: 'Orlando, FL',
  metaTitle: 'Orlando Maid and Cleaning Service',
  metaDescription: 'Orlando Maid — house cleaning across Winter Park, Baldwin Park & Lake Nona starting at $49 per hour. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '28.5383', lng: '-81.3792' },
  introParagraphs: [
    "Orlando Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across Central Florida's biggest, fastest-growing metro — from lakefront bungalows near Winter Park to new-construction communities pushing out toward Lake Nona. If you live in Orlando, you know the pace: new neighborhoods breaking ground every year, theme-park tourism flooding the area with short-term rentals, and a housing stock that ranges from 1920s Colonial charm to brand-new smart homes. We built Orlando Maid to answer exactly that problem: a local cleaning service that understands the full range of Orlando living and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Orlando Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Orlando.",
    "Whether you need a one-time deep clean before hosting family visiting the parks, a recurring weekly service for a busy Baldwin Park household, or a fast turnover clean for a Dr. Phillips vacation rental between guests, Orlando Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from historic College Park cottages to brand-new Lake Nona builds, and that range of experience shapes how we train every cleaner. Orlando Maid was built around the reality that this metro's sheer size and variety demand a service that can flex to any home type.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Orlando Maid exists because Central Florida's tourism economy, sprawling new-construction communities, and mature in-town neighborhoods make it its own world. So rather than force Orlando into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this city.",
    "Every cleaner who works under the Orlando Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Orlando, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Orlando as in Minneapolis. Orlando Maid does not. We built our service around this metro's mix of historic in-town neighborhoods, sprawling new-construction suburbs, and a massive short-term rental market.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Orlando Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Orlando home on recurring visits.",
  ],
  challenges: [
    { title: 'Vacation Rental Turnover', body: "With one of the country's largest short-term rental markets, Orlando homes near the parks turn over fast between guests. Our scheduling supports same-day and next-day turnovers." },
    { title: 'New-Construction Dust', body: "Fast-growing communities like Lake Nona mean many clients move into homes still shedding drywall dust and construction debris. We adjust our first-clean approach for newly built homes." },
    { title: 'Humidity & Mold Prevention', body: "Central Florida's inland humidity still creates mildew risk in bathrooms and closets. We pay close attention to these high-risk zones on every visit." },
    { title: 'Lawn Debris & Central Florida Storms', body: "Frequent summer thunderstorms track grass, mulch, and lawn debris indoors. We adjust entryway and floor cleaning routines during rainy season." },
    { title: 'Large Metro Scheduling', body: "Orlando's sprawl means travel time varies a lot by neighborhood. We build routes by area so your appointment window stays reliable." },
    { title: 'Historic Home Care', body: "College Park and other older in-town neighborhoods have original hardwood floors and vintage fixtures that need gentler products than a new build. We adjust accordingly." },
  ],
  neighborhoods: [
    { name: 'Winter Park', blurb: "Brick-lined streets and lakefront estates make Winter Park one of Central Florida's most established neighborhoods, and a favorite for our weekly and bi-weekly recurring clients." },
    { name: 'Baldwin Park', blurb: "This master-planned, walkable community near Orlando's urban core is home to many of our recurring clients who value consistency and quick response." },
    { name: 'College Park', blurb: "Tree-lined streets and 1920s-40s bungalows give College Park real character — we clean here with extra care for original hardwood floors and vintage details." },
    { name: 'Thornton Park', blurb: "Just east of downtown, Thornton Park's condos and historic homes are a regular stop for our weekly and bi-weekly cleaning plans." },
    { name: 'Lake Nona', blurb: "One of the fastest-growing parts of Orlando, Lake Nona's new-construction homes call for a first-clean approach tuned to newly built properties." },
    { name: 'Dr. Phillips', blurb: "Close to the theme-park corridor, Dr. Phillips is where much of our vacation-rental turnover work happens, alongside full-time family homes." },
  ],
  pricingExplainer: [
    "Orlando Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy Baldwin Park condo might only need the 2-hour minimum, while a Winter Park estate getting its first deep clean could run 5 hours or more.",
    "Recurring service is where Orlando Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Orlando.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Orlando families with kids or pets. Weekly service keeps clutter and dust from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes or seasonal residences near the parks. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "We run a short-term rental near the parks and needed reliable turnovers. Orlando Maid has never made us miss a check-in.", name: 'Brian S.', neighborhood: 'Dr. Phillips' },
    { text: "Our College Park bungalow has original wood floors and they treated them with real care.", name: 'Diane W.', neighborhood: 'College Park' },
    { text: "They've cleaned our Baldwin Park home weekly for over a year — always the same reliable cleaner.", name: 'Marcus L.', neighborhood: 'Baldwin Park' },
    { text: "Just moved into a new build in Lake Nona and they got all the construction dust out before we unpacked.", name: 'Priya N.', neighborhood: 'Lake Nona' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Orlando?', answer: 'Orlando Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Orlando?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Orlando Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, vacation rental turnovers, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for closing on a Lake Nona new build or ending a lease near downtown." },
    { question: 'Do you clean vacation rentals near the theme parks?', answer: "Yes, with fast turnaround between guests — this is one of our most requested services in the Dr. Phillips and International Drive corridors." },
    { question: 'Can you clean historic homes in College Park?', answer: "Absolutely. We use gentler products suited to original hardwood floors and vintage details." },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or door code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Orlando Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of Orlando do you serve?', answer: 'Winter Park, Baldwin Park, College Park, Thornton Park, Lake Nona, Dr. Phillips, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in the Orlando metro we serve.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Orlando Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Orlando Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a studio or small condo?', answer: 'Yes, our 2-hour minimum is usually perfect for a small unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Orlando Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'Do you clean new-construction homes?', answer: 'Yes, with a first-clean approach tuned to clearing out drywall dust and construction debris.' },
    { question: 'What if my community has a gate or HOA check-in?', answer: 'Just let us know your community\'s procedures when booking and we\'ll build in the extra time.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Do you clean vacation homes that sit empty most of the year?', answer: 'Yes, with arrival-prep cleanings before you visit.' },
    { question: 'Is Orlando Maid available on holidays?', answer: 'Text us to check holiday availability — this is a busy season for park visitors.' },
    { question: 'Do you clean model units for real estate agents or builders?', answer: 'Yes, we regularly clean staged listings and model homes in new communities.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Orlando Maid serve both houses and condos?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Orlando Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
    { question: 'How far out does Orlando Maid travel from downtown?', answer: 'We cover the greater Orlando metro — ask when booking if you\'re unsure whether your area is included.' },
  ],
}
