import type { EmdMicrositeConfig } from './types'

export const oviedoMaidConfig: EmdMicrositeConfig = {
  domain: 'oviedomaid.com',
  brandName: 'Oviedo Maid',
  city: 'Oviedo',
  regionLabel: 'Oviedo, FL',
  metaTitle: 'Oviedo Maid and Cleaning Service',
  metaDescription: 'Oviedo Maid — house cleaning across Historic Downtown Oviedo, Twin Rivers & Live Oak Reserve starting at $49 per hour. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '28.6700', lng: '-81.2081' },
  introParagraphs: [
    "Oviedo Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across one of Seminole County's top family-oriented suburbs — a community known for excellent schools, well-kept planned neighborhoods, and easy access to UCF. If you live in Oviedo, you know the pace: busy family schedules, active HOA communities, and homes that need real upkeep between school runs and after-school activities. We built Oviedo Maid to answer exactly that problem: a local cleaning service that understands this community and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Oviedo Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Oviedo.",
    "Whether you need a one-time deep clean before hosting family, a recurring weekly service for a busy Twin Rivers household, or a fast turnover clean for a Live Oak Reserve rental between tenants, Oviedo Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from historic downtown cottages to newer planned-community homes, and that range of experience shapes how we train every cleaner. Oviedo Maid was built around the reality that this community's high standards and busy families demand real reliability.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Oviedo Maid exists because this top-rated Seminole County suburb's planned communities, busy family schedules, and high presentation standards make it its own world. So rather than force Oviedo into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this city.",
    "Every cleaner who works under the Oviedo Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Oviedo, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Oviedo as in Minneapolis. Oviedo Maid does not. We built our service around this community's busy family schedules and well-maintained planned communities.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Oviedo Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Oviedo home on recurring visits.",
  ],
  challenges: [
    { title: 'Busy Family Schedules', body: "Many Oviedo households juggle school schedules, sports, and two working parents. We offer flexible booking windows so cleaning fits your life." },
    { title: 'HOA Presentation Standards', body: "Twin Rivers and Live Oak Reserve often have HOA expectations around presentation and consistency. We clean with those standards in mind." },
    { title: 'Humidity & Mold Prevention', body: "Central Florida humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit." },
    { title: 'New-Construction Dust', body: "Growing sections of Oviedo mean many clients move into homes still shedding drywall dust and construction debris. We adjust our first-clean approach for newly built homes." },
    { title: 'Large Family Homes', body: "Many Oviedo homes are larger family properties that take longer to clean thoroughly. We adjust cleaning time estimates for these homes." },
    { title: 'Hurricane Season Readiness', body: "Storm season means shutter dust and post-storm cleanup. We offer flexible scheduling around storm prep and recovery." },
  ],
  neighborhoods: [
    { name: 'Historic Downtown Oviedo', blurb: "This charming small-town core is a favorite for our weekly and bi-weekly recurring clients." },
    { name: 'Twin Rivers', blurb: "This large planned community is home to many of our longest-running recurring clients, who value a consistent cleaner they can trust." },
    { name: 'Live Oak Reserve', blurb: "This established residential area trusts Oviedo Maid for everything from routine upkeep to deep cleans." },
    { name: 'Alafaya Woods', blurb: "This family-friendly neighborhood is a regular stop for our bi-weekly and monthly cleaning plans." },
    { name: 'Kingsbridge West', blurb: "This planned community calls for a first-clean approach tuned to newer construction." },
    { name: 'Stonewyck', blurb: "This residential section trusts us for consistent, detail-first cleaning for busy households." },
  ],
  pricingExplainer: [
    "Oviedo Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy townhome might only need the 2-hour minimum, while a Twin Rivers family home getting its first deep clean could run 5 hours or more.",
    "Recurring service is where Oviedo Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Oviedo.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Oviedo families with kids or pets. Weekly service keeps clutter and dust from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "Between two jobs and three kids we never had time to keep up. Oviedo Maid gave us our weekends back.", name: 'Jennifer L.', neighborhood: 'Twin Rivers' },
    { text: "They've handled our Live Oak Reserve home weekly for over a year — always the same reliable cleaner.", name: 'Peter K.', neighborhood: 'Live Oak Reserve' },
    { text: "Our Twin Rivers home has real HOA standards and Oviedo Maid always meets them.", name: 'Michelle A.', neighborhood: 'Twin Rivers' },
    { text: "Booked a deep clean before hosting family and they went above and beyond.", name: 'Samuel R.', neighborhood: 'Alafaya Woods' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Oviedo?', answer: 'Oviedo Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Oviedo?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Oviedo Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Can you clean homes in HOA communities like Twin Rivers?', answer: "Absolutely. We're familiar with the presentation standards these communities expect." },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for closing on a new home or moving out of a rental." },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or gate code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Oviedo Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of Oviedo do you serve?', answer: 'Historic Downtown Oviedo, Twin Rivers, Live Oak Reserve, Alafaya Woods, Kingsbridge West, Stonewyck, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Oviedo.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Oviedo Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Oviedo Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a townhome or smaller unit?', answer: 'Yes, our 2-hour minimum is usually perfect for a smaller unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Oviedo Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'What if my community has a gate or HOA check-in?', answer: 'Just let us know your community\'s procedures when booking and we\'ll build in the extra time.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Is Oviedo Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Oviedo Maid serve both houses and townhomes?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Oviedo Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
