import type { EmdMicrositeConfig } from './types'

export const panamaCityMaidConfig: EmdMicrositeConfig = {
  domain: 'panamacitymaid.com',
  brandName: 'Panama City Maid',
  city: 'Panama City',
  regionLabel: 'Panama City, FL',
  metaTitle: 'Panama City Maid and Cleaning Service',
  metaDescription: 'Panama City Maid — house cleaning across St. Andrews, the Cove & North Bay from $49/hr. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '30.1588', lng: '-85.6602' },
  introParagraphs: [
    "Panama City Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across a Panhandle city built around St. Andrews Bay — a community of historic waterfront neighborhoods, a rebuilt downtown, and a strong Tyndall Air Force Base presence. If you live in Panama City, you know how quickly bay-front humidity and salt air can wear down a home. We built Panama City Maid to answer exactly that problem: a local cleaning service that understands this community and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Panama City Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Panama City.",
    "Whether you need a one-time deep clean before hosting family in from out of town, a recurring weekly service for a busy North Bay household, or a fast turnover clean tied to a Tyndall PCS move, Panama City Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from historic St. Andrews cottages to newer rebuilds across the city, and that range of experience shapes how we train every cleaner. Panama City Maid was built around the reality that this resilient community deserves a cleaning service that shows up reliably, every time.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Panama City Maid exists because this Panhandle bay community's mix of historic neighborhoods, military families, and rebuilt housing stock make it its own world. So rather than force Panama City into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this city.",
    "Every cleaner who works under the Panama City Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Panama City, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Panama City as in Minneapolis. Panama City Maid does not. We built our service around this bay community's historic neighborhoods, military-family relocations, and coastal exposure.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Panama City Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Panama City home on recurring visits.",
  ],
  challenges: [
    { title: 'Military Family Relocations', body: "As the home of Tyndall Air Force Base, Panama City sees families move in and out on tight PCS timelines. We offer flexible move-in/move-out scheduling built around military relocation dates." },
    { title: 'Historic Waterfront Home Care', body: "St. Andrews and other historic districts have older homes with original details that need gentler products than a newer build. We adjust our approach accordingly." },
    { title: 'Salt Air & Bay Humidity', body: "Homes near St. Andrews Bay carry fine salt particulate that settles on chrome fixtures, appliances, and window tracks. We use products chosen to cut salt residue without damaging finishes." },
    { title: 'Humidity & Mold Prevention', body: "Panhandle Gulf Coast humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit." },
    { title: 'Newer Rebuilt Construction', body: "Many Panama City homes have been rebuilt or renovated in recent years and can still carry construction dust. We adjust our first-clean approach for these properties." },
    { title: 'Hurricane Season Readiness', body: "This community takes storm season seriously. We offer flexible scheduling around storm prep and post-storm cleanup." },
  ],
  neighborhoods: [
    { name: 'St. Andrews', blurb: "This historic waterfront district is home to many of our longest-running recurring clients, who value a consistent cleaner they can trust." },
    { name: 'The Cove', blurb: "This established residential neighborhood near the bay is a favorite for our weekly and bi-weekly recurring clients." },
    { name: 'North Bay', blurb: "This bay-front area calls for careful attention to salt residue and humidity on every visit." },
    { name: 'Millville', blurb: "This working-class historic neighborhood trusts Panama City Maid for everything from routine upkeep to deep cleans." },
    { name: 'DeLeon Avenue Area', blurb: "This residential corridor is a regular stop for our bi-weekly and monthly cleaning plans." },
    { name: 'Historic Downtown', blurb: "Our downtown clients near St. Andrews Bay rely on us for consistent, detail-first cleaning." },
  ],
  pricingExplainer: [
    "Panama City Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy Cove condo might only need the 2-hour minimum, while a St. Andrews home getting its first deep clean could run 5 hours or more.",
    "Recurring service is where Panama City Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Panama City.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Panama City families with kids or pets. Weekly service keeps humidity and dust from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes or seasonal residences. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "We PCS'd in with only two weeks notice and they got the new house move-in ready right on schedule.", name: 'A1C Ramirez', neighborhood: 'North Bay' },
    { text: "Our St. Andrews home has original details and they treated everything with real care.", name: 'Betty J.', neighborhood: 'St. Andrews' },
    { text: "They've cleaned our Cove home weekly for months now — always the same reliable cleaner.", name: 'Walter H.', neighborhood: 'The Cove' },
    { text: "Booked a deep clean before hosting family in from out of town and they went above and beyond.", name: 'Michelle D.', neighborhood: 'Millville' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Panama City?', answer: 'Panama City Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Panama City?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Panama City Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, military PCS turnovers, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Do you offer move-in/move-out cleaning tied to Tyndall PCS moves?', answer: "Yes — we regularly work with Tyndall Air Force Base families on tight relocation timelines and can turn around a move-in or move-out clean fast." },
    { question: 'Can you clean historic homes in St. Andrews?', answer: "Absolutely. We use gentler products suited to original details and older fixtures." },
    { question: 'Do you clean newer or rebuilt homes?', answer: 'Yes, with a first-clean approach tuned to clearing out any remaining construction dust.' },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or door code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Panama City Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of Panama City do you serve?', answer: 'St. Andrews, the Cove, North Bay, Millville, the DeLeon Avenue area, historic downtown, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Panama City.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Panama City Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Panama City Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a condo or smaller unit?', answer: 'Yes, our 2-hour minimum is usually perfect for a smaller unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Panama City Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'Do you clean waterfront homes near St. Andrews Bay?', answer: 'Yes, we regularly service properties across St. Andrews and North Bay.' },
    { question: 'What if my building requires vendor registration?', answer: 'Send us your requirements ahead of time and we\'ll get registered.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Do you clean vacation homes that sit empty?', answer: 'Yes, with arrival-prep cleanings before you visit.' },
    { question: 'Is Panama City Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Panama City Maid serve both houses and condos?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Panama City Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
