import type { EmdMicrositeConfig } from './types'

export const parklandMaidConfig: EmdMicrositeConfig = {
  domain: 'parklandmaid.com',
  brandName: 'Parkland Maid',
  city: 'Parkland',
  regionLabel: 'Parkland, FL',
  metaTitle: 'Parkland Maid and Cleaning Service',
  metaDescription: 'Parkland Maid — house cleaning across Heron Bay, Parkland Golf & Country Club & Terramar starting at $49 per hour. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '26.3103', lng: '-80.2378' },
  introParagraphs: [
    "Parkland Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across one of Broward County's most affluent, family-focused communities — a city known for equestrian trails, gated golf estates, and some of the top-rated schools in South Florida. If you live in Parkland, you know how much this community's presentation standards matter to residents. We built Parkland Maid to answer exactly that problem: a local cleaning service that understands this community's expectations and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Parkland Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Parkland.",
    "Whether you need a one-time deep clean before hosting guests near Heron Bay, a recurring weekly service for a busy Parkland Golf & Country Club household, or a fast turnover clean for a Terramar rental between tenants, Parkland Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from gated golf estates to family townhomes, and that range of experience shapes how we train every cleaner. Parkland Maid was built around the reality that this community's high standards demand real attention to detail.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Parkland Maid exists because this affluent, family-focused city's gated golf estates, equestrian trails, and high presentation standards make it its own world. So rather than force Parkland into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this city.",
    "Every cleaner who works under the Parkland Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Parkland, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Parkland as in Minneapolis. Parkland Maid does not. We built our service around this community's gated golf estates, busy family schedules, and high presentation expectations.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Parkland Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Parkland home on recurring visits.",
  ],
  challenges: [
    { title: 'Gated Community Standards', body: "Heron Bay and Parkland Golf & Country Club often have HOA expectations around presentation and consistency. We clean with those standards in mind." },
    { title: 'Busy Family Schedules', body: "Many Parkland households juggle school schedules, sports, and two working parents. We offer flexible booking windows so cleaning fits your life." },
    { title: 'Humidity & Mold Prevention', body: "South Florida humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit." },
    { title: 'Large Estate Homes', body: "Many Parkland properties are large estate homes that take longer to clean thoroughly. We staff multi-person teams for these properties as needed." },
    { title: 'Equestrian & Rural-Adjacent Homes', body: "Parkland's western reaches include equestrian properties with more open land, tracking in more dirt and organic debris. We adjust our routine for these homes." },
    { title: 'Hurricane Season Readiness', body: "Storm season means shutter dust and post-storm cleanup. We offer flexible scheduling around storm prep and recovery." },
  ],
  neighborhoods: [
    { name: 'Heron Bay', blurb: "This large gated golf community is home to many of our longest-running recurring clients, who value a consistent cleaner they can trust." },
    { name: 'Parkland Golf & Country Club', blurb: "This exclusive gated community's estates call for cleaning with real attention to presentation standards." },
    { name: 'Terramar', blurb: "This established residential area trusts Parkland Maid for everything from routine upkeep to deep cleans." },
    { name: 'Pine Tree Estates', blurb: "This equestrian-adjacent neighborhood is a favorite for our weekly and bi-weekly recurring clients." },
    { name: 'Meadow Run', blurb: "This family-friendly neighborhood is a regular stop for our bi-weekly and monthly cleaning plans." },
    { name: 'Parkland Bay', blurb: "This newer community calls for a first-clean approach tuned to newer construction." },
  ],
  pricingExplainer: [
    "Parkland Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy townhome might only need the 2-hour minimum, while a Heron Bay estate getting its first deep clean could run 5 hours or more.",
    "Recurring service is where Parkland Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Parkland.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Parkland families with kids or pets. Weekly service keeps clutter and dust from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "Our Heron Bay home has real HOA standards and Parkland Maid always meets them.", name: 'Samantha K.', neighborhood: 'Heron Bay' },
    { text: "Between school runs and work we never had time to keep up. They gave us our weekends back.", name: 'Brian L.', neighborhood: 'Terramar' },
    { text: "They've handled our Parkland Golf & Country Club home weekly for over a year — always the same reliable cleaner.", name: 'Rachel M.', neighborhood: 'Parkland Golf & Country Club' },
    { text: "We have horses and the extra dirt they track in is no match for Parkland Maid.", name: 'Katherine J.', neighborhood: 'Pine Tree Estates' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Parkland?', answer: 'Parkland Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Parkland?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Parkland Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Can you clean homes in gated communities like Heron Bay?', answer: "Absolutely. We're familiar with the presentation standards these communities expect and can handle gate check-in procedures." },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for closing on a new home or moving out of a rental." },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or gate code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Parkland Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of Parkland do you serve?', answer: 'Heron Bay, Parkland Golf & Country Club, Terramar, Pine Tree Estates, Meadow Run, Parkland Bay, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Parkland.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Parkland Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Parkland Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets or horses on the property?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a townhome or smaller unit?', answer: 'Yes, our 2-hour minimum is usually perfect for a smaller unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Parkland Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'What if my community has a gate or HOA check-in?', answer: 'Just let us know your community\'s procedures when booking and we\'ll build in the extra time.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Is Parkland Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger estates?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Parkland Maid serve both townhomes and estate homes?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Parkland Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
