import type { EmdMicrositeConfig } from './types'

export const perdidoKeyMaidConfig: EmdMicrositeConfig = {
  domain: 'perdidokeymaid.com',
  brandName: 'Perdido Key Maid',
  city: 'Pensacola',
  regionLabel: 'Perdido Key, Pensacola, FL',
  metaTitle: 'Perdido Key Maid and Cleaning Service',
  metaDescription: 'Perdido Key Maid — house cleaning across Perdido Key & Johnson Beach, greater Pensacola, FL starting at $49 per hour. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '30.3113', lng: '-87.4468' },
  introParagraphs: [
    "Perdido Key Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across Perdido Key and the greater Pensacola area — a narrow barrier island stretching along the Florida-Alabama line, home to one of the region's busiest vacation-rental markets. If you own or manage property on Perdido Key, you know how quickly salt air, beach sand, and back-to-back guest turnovers can wear down a home. We built Perdido Key Maid to answer exactly that problem: a local cleaning service that understands barrier-island living and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Perdido Key Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Perdido Key and the rest of the greater Pensacola area.",
    "Whether you need a one-time deep clean before hosting family, a recurring service for a full-time Perdido Key residence, or a fast turnover clean for a beachfront condo between guests, Perdido Key Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from high-rise beachfront condos to Old Florida cottages tucked along the Intracoastal side of the Key, and that range of experience shapes how we train every cleaner. Perdido Key Maid was built around the reality that this barrier island's tourism-driven rental market demands fast, reliable, no-excuses turnover.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Perdido Key Maid exists because this barrier island community west of Pensacola runs on a completely different rhythm than an ordinary residential neighborhood — guest turnovers, condo association rules, and salt-heavy Gulf air all demand a specialized approach. So rather than force Perdido Key into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this part of the greater Pensacola area.",
    "Every cleaner who works under the Perdido Key Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust on Perdido Key and greater Pensacola, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist on Perdido Key as in Minneapolis. Perdido Key Maid does not. We built our service around this barrier island's beachfront condos, guest-turnover pace, and one of the busiest short-term rental markets on the Gulf.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Perdido Key Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Perdido Key property on recurring visits.",
  ],
  challenges: [
    { title: 'Beach Sand Everywhere', body: "Perdido Key's fine white sand tracks indoors more than typical beach sand and works into carpets and grout lines. We use techniques built for lifting fine sand without grinding it deeper in." },
    { title: 'Peak-Season Rental Turnover', body: "As one of the busiest vacation-rental markets on the Gulf, Perdido Key condos flip fast between guests. Our scheduling supports same-day and next-day turnovers." },
    { title: 'Salt Air & Corrosion', body: "Gulf-front air carries fine salt particulate that settles on chrome fixtures, appliances, and window tracks. We use products chosen to cut salt residue without damaging finishes." },
    { title: 'Condo Association Access Rules', body: "Many Perdido Key high-rises require vendor registration and elevator scheduling for cleaners. We handle the paperwork so your turnover stays on time." },
    { title: 'Hurricane Season Readiness', body: "Panhandle storm season means shutter dust and post-storm cleanup, especially on a barrier island. We offer flexible scheduling around storm prep and recovery." },
  ],
  neighborhoods: [
    { name: 'Perdido Key', blurb: "One of the region's premier beachfront destinations, Perdido Key's condos and homes are where most of our vacation-rental turnover work happens." },
    { name: 'Johnson Beach Area', blurb: "Near the National Seashore, our clients here rely on us for careful attention to salt residue and fine beach sand." },
    { name: 'Innerarity Point', blurb: "This quieter Intracoastal-side community trusts us for consistent, reliable residential service." },
    { name: 'Ono Island (FL side)', blurb: "Near the Alabama state line, our clients here rely on the same standard of care as the rest of the Key." },
    { name: 'Pensacola Beach', blurb: "East along the coast, our Pensacola Beach clients trust us for fast, reliable turnover cleaning between summer stays." },
    { name: 'Warrington', blurb: "Toward the mainland near NAS Pensacola, Warrington's households get the same careful attention." },
  ],
  pricingExplainer: [
    "Perdido Key Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your property needs? Mainly size and condition. A tidy Perdido Key condo might only need the 2-hour minimum, while a beachfront home getting its first deep clean could run 5 hours or more.",
    "Recurring service is where Perdido Key Maid saves you the most, especially for full-time residents. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Perdido Key and the greater Pensacola area.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among full-time Perdido Key residents. Weekly service keeps sand and salt residue from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households or lighter-use condos. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to seasonal or lightly-used properties. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, guest turnover, or pre-listing reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "We rent our Perdido Key condo out most of the year and they've never made us miss a check-in.", name: 'Todd W.', neighborhood: 'Perdido Key' },
    { text: "Salt air was destroying our fixtures until they started coming regularly.", name: 'Lauren B.', neighborhood: 'Johnson Beach Area' },
    { text: "They handle the elevator scheduling and vendor sign-in at our building without us having to lift a finger.", name: 'Frank D.', neighborhood: 'Perdido Key' },
    { text: "Same-day turnaround between guests, every time, no exceptions.", name: 'Christine A.', neighborhood: 'Innerarity Point' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost on Perdido Key?', answer: 'Perdido Key Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning on Perdido Key?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Perdido Key Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, vacation rental turnovers, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Do you clean vacation rentals near the beach?', answer: "Yes, with fast turnaround between guests, including same-day and next-day turnovers." },
    { question: 'What if my condo building requires vendor registration?', answer: 'Send us your requirements ahead of time and we\'ll get registered and handle elevator scheduling.' },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key, lockbox code, or door code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings; same-day turnovers can often be arranged with less notice.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Perdido Key Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of Perdido Key do you serve?', answer: 'Perdido Key, the Johnson Beach area, Innerarity Point, the Florida side of Ono Island, Pensacola Beach, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere on Perdido Key or the greater Pensacola area.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Perdido Key Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Perdido Key Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a studio or small condo?', answer: 'Yes, our 2-hour minimum is usually perfect for a small unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Perdido Key Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your unit size and needs for a straightforward estimate.' },
    { question: 'Do you manage cleanings for property managers with multiple units?', answer: 'Yes, we regularly work with property managers and short-term rental owners across Perdido Key.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Is Perdido Key Maid available on holidays?', answer: 'Text us to check holiday availability — this is often our busiest turnover season.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Perdido Key Maid serve both houses and condos?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Perdido Key Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
