// Auto-generated 2026-08-05 via Pexels API — each entry verified against Pexels' own alt-text
// containing both the city name AND "Florida"/"FL" before being accepted as a real match for
// that city. An initial looser pass matched Port St. Lucie to a photo of Saint Kitts, and
// Weston/Windermere to UK locations, on nothing but a loose name substring — this stricter
// check is why. Cities with no confidently-verified Pexels match use a neutral generic
// clean-home photo instead of a specific-but-wrong city photo — realLocation:false marks these.
export interface EmdCityPhoto {
  src: string
  alt: string
  photographer: string | null
  photographerUrl: string | null
  realLocation: boolean
}

export const EMD_CITY_PHOTOS: Record<string, EmdCityPhoto> = {
  'altamontespringsmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'bocaratonflmaid.com': { src: 'https://images.pexels.com/photos/12239932/pexels-photo-12239932.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'Serene sunset over the ocean at Boca Raton, Florida, with waves and a pastel sky creating a peaceful scene.', photographer: 'Pamela Leggett', photographerUrl: 'https://www.pexels.com/@pamela-leggett-238541939', realLocation: true },
  'brandonmaid.com': { src: 'https://images.pexels.com/photos/38857026/pexels-photo-38857026.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'Aerial shot of a residential community with lush greenery in Brandon, Florida, USA.', photographer: 'Chris  The Island', photographerUrl: 'https://www.pexels.com/@chris-the-island-3570397', realLocation: true },
  'celebrationmaid.com': { src: 'https://images.pexels.com/photos/8987704/pexels-photo-8987704.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A peaceful wooden footbridge over a reflective lake in a lush park setting in Celebration, Florida.', photographer: 'Lily Astacio', photographerUrl: 'https://www.pexels.com/@lily-astacio-86001559', realLocation: true },
  'clermontmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'cocoabeachmaid.com': { src: 'https://images.pexels.com/photos/2524166/pexels-photo-2524166.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'Stunning sunset view of Cocoa Beach Pier, Florida, with a vibrant sky and calm ocean.', photographer: 'James Cheney', photographerUrl: 'https://www.pexels.com/@cheneymediaproductions', realLocation: true },
  'coralgablesmaid.com': { src: 'https://images.pexels.com/photos/31098243/pexels-photo-31098243.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'Tranquil university campus view with palm trees and water in Coral Gables, Florida.', photographer: 'DΛVΞ GΛRCIΛ', photographerUrl: 'https://www.pexels.com/@davegarcia', realLocation: true },
  'coralspringsmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'daytonabeachmaid.com': { src: 'https://images.pexels.com/photos/14784193/pexels-photo-14784193.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A flock of seagulls gathered on the sandy shore of Daytona Beach, Florida.', photographer: 'Erick  Martinez-Velasco', photographerUrl: 'https://www.pexels.com/@erick-martinez-velasco-247863608', realLocation: true },
  'delandmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'destinmaid.com': { src: 'https://images.pexels.com/photos/18518616/pexels-photo-18518616.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'Sunset view of Destin, FL beachfront with modern architecture and serene ocean.', photographer: 'Drew Burks', photographerUrl: 'https://www.pexels.com/@drew-burks-651927257', realLocation: true },
  'fortlauderdalemaid.com': { src: 'https://images.pexels.com/photos/15334541/pexels-photo-15334541.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'Elegant waterfront mansion with palm trees in Fort Lauderdale, Florida under a clear blue sky.', photographer: 'Eric Prouzet', photographerUrl: 'https://www.pexels.com/@eric-prouzet-225470', realLocation: true },
  'fortmyersmaid.com': { src: 'https://images.pexels.com/photos/12569260/pexels-photo-12569260.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'Aerial photo showcasing a suburban neighborhood in Fort Myers, Florida, with clear skies and organized streets.', photographer: 'Nick Adams', photographerUrl: 'https://www.pexels.com/@nick-adams-256425755', realLocation: true },
  'gainesvillemaid.com': { src: 'https://images.pexels.com/photos/35527303/pexels-photo-35527303.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'People hiking through a forest in Gainesville, Florida, exploring nature and scenery.', photographer: 'Larry Hyler', photographerUrl: 'https://www.pexels.com/@heiler', realLocation: true },
  'lakemarymaid.com': { src: 'https://images.pexels.com/photos/13304180/pexels-photo-13304180.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'Beautiful aerial view of a park with a pond in Lake Mary, Florida, showcasing autumn foliage.', photographer: 'Thomas Haney', photographerUrl: 'https://www.pexels.com/@thomas-haney-175964438', realLocation: true },
  'longwoodmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'miamibeachmaid.com': { src: 'https://images.pexels.com/photos/33462250/pexels-photo-33462250.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A vibrant beach scene in Miami Beach, Florida, showcasing kite surfers and beachgoers under a bright sky.', photographer: 'mysurrogateband', photographerUrl: 'https://www.pexels.com/@mysurrogateband-1076071941', realLocation: true },
  'naplesflmaid.com': { src: 'https://images.pexels.com/photos/3731068/pexels-photo-3731068.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'Captivating sunset view from Naples Pier, Florida; a serene ocean landscape.', photographer: 'Waldo', photographerUrl: 'https://www.pexels.com/@waldomalan', realLocation: true },
  'orlandoflmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'oviedomaid.com': { src: 'https://images.pexels.com/photos/14458516/pexels-photo-14458516.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'Aerial view of a resort nestled in a lush forest landscape under a clear blue sky in Oviedo, FL.', photographer: 'Thomas Haney', photographerUrl: 'https://www.pexels.com/@thomas-haney-175964438', realLocation: true },
  'palmbeachgardensflmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'panamacitymaid.com': { src: 'https://images.pexels.com/photos/18145153/pexels-photo-18145153.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'Stunning aerial shot of a beachfront resort in Panama City Beach, FL with pools and coastline.', photographer: 'Ryan Beirne', photographerUrl: 'https://www.pexels.com/@peepsbeirne', realLocation: true },
  'parklandmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'pensacolamaid.com': { src: 'https://images.pexels.com/photos/12382675/pexels-photo-12382675.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'Aerial photograph showcasing the pristine blue waves and white sand of Pensacola Beach, Florida.', photographer: 'Viktoria B.', photographerUrl: 'https://www.pexels.com/@viktoriab', realLocation: true },
  'pompanobeachmaid.com': { src: 'https://images.pexels.com/photos/33664883/pexels-photo-33664883.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A vibrant lifeguard tower on Pompano Beach, Florida with a clear view of the ocean and nearby buildings in the background.', photographer: 'Stanley  Louigene', photographerUrl: 'https://www.pexels.com/@stanley-louigene-262756857', realLocation: true },
  'portstluciemaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'riverviewmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'sanfordmaid.com': { src: 'https://images.pexels.com/photos/11983160/pexels-photo-11983160.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'Elegant bridge spanning over a serene river in Sanford, FL, highlighting stunning architectural details.', photographer: 'Connor Scott McManus', photographerUrl: 'https://www.pexels.com/@connorscottmcmanus', realLocation: true },
  'sarasotaflmaid.com': { src: 'https://images.pexels.com/photos/31848418/pexels-photo-31848418.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'Panoramic view of Sarasota, Florida skyline against a blue sky, featuring modern architecture and waterfront.', photographer: 'Jeffrey Eisen', photographerUrl: 'https://www.pexels.com/@jeffrey-eisen-1257101', realLocation: true },
  'stpetemaid.com': { src: 'https://images.pexels.com/photos/10634719/pexels-photo-10634719.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'Scenic view of St. Petersburg, FL marina at dusk, featuring skyline and reflections in water.', photographer: 'Neil Cabacang', photographerUrl: 'https://www.pexels.com/@neil-cabacang-33524025', realLocation: true },
  'tallahasseeflmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'thevillagesmaid.com': { src: 'https://images.pexels.com/photos/27289601/pexels-photo-27289601.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'Two rowboats floating peacefully on a lake, showcasing tranquility in The Villages, FL.', photographer: 'Michael Hamments', photographerUrl: 'https://www.pexels.com/@michael-hamments-736237287', realLocation: true },
  'verobeachmaid.com': { src: 'https://images.pexels.com/photos/8752296/pexels-photo-8752296.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'Capture of a colorful sunrise reflecting off the water at Vero Beach, Florida\'s serene coastline.', photographer: 'John Biondo', photographerUrl: 'https://www.pexels.com/@jlbdigital', realLocation: true },
  'wellingtonmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'wesleychapelmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'westonflmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'westpalmbeachmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'windermeremaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'wintergardenmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'winterparkmaid.com': { src: 'https://images.pexels.com/photos/11969611/pexels-photo-11969611.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'Peaceful scene of a lake with Spanish moss hanging from trees, captured at dusk in Winter Park, Florida.', photographer: 'Madison Santangelo', photographerUrl: 'https://www.pexels.com/@madison-santangelo-223565943', realLocation: true },
  // Pensacola-area neighborhood microsites (2026-08-18) — no confidently-verified
  // Pexels match for these hyper-local names, so all 10 use the generic fallback.
  'brentmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'cordovaparkmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'easthillmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'ensleymaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'ferrypassmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'northhillmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'pacemaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'gulfbreezemaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'perdidokeymaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
  'warringtonmaid.com': { src: 'https://images.pexels.com/photos/28586197/pexels-photo-28586197.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200', alt: 'A bright, professionally cleaned modern living room.', photographer: null, photographerUrl: null, realLocation: false },
}

// Generic professional-cleaning photo — same image used site-wide in the differentiation
// section. Depicts a real cleaner performing a real cleaning task; not presented as a photo
// of this specific company's specific staff.
export const EMD_GENERIC_CLEANING_PHOTO = {
  src: 'https://images.pexels.com/photos/6195949/pexels-photo-6195949.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200',
  alt: 'A professional house cleaner vacuuming a living room.',
  photographer: 'RDNE Stock project',
}
