import type { EmdMicrositeConfig } from './types'

export const portStLucieMaidConfig: EmdMicrositeConfig = {
  domain: 'portstluciemaid.com',
  brandName: 'Port St. Lucie Maid',
  city: 'Port St. Lucie',
  regionLabel: 'Port St. Lucie, FL',
  metaTitle: 'Port St. Lucie Maid and Cleaning Service',
  metaDescription: 'Port St. Lucie Maid — house cleaning across Tradition, St. Lucie West & PGA Village Verano starting at $49 per hour. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '27.2730', lng: '-80.3582' },
  introParagraphs: [
    "Port St. Lucie Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across one of Florida's fastest-growing cities — from brand-new construction in Tradition to established retiree communities near St. Lucie West. If you live in Port St. Lucie, you know the pace: new neighborhoods breaking ground constantly, a large active-adult population, and a sprawling footprint that stretches across the Treasure Coast. We built Port St. Lucie Maid to answer exactly that problem: a local cleaning service that understands this city's rapid growth and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Port St. Lucie Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Port St. Lucie.",
    "Whether you need a one-time deep clean after moving into a new build in Tradition, a recurring weekly service for a busy St. Lucie West household, or a fast turnover clean for a PGA Village Verano rental between guests, Port St. Lucie Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from brand-new builds to established active-adult communities, and that range of experience shapes how we train every cleaner. Port St. Lucie Maid was built around the reality that this city's rapid growth demands a service that scales with it.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Port St. Lucie Maid exists because this fast-growing Treasure Coast city's mix of new construction, planned communities, and active-adult neighborhoods make it its own world. So rather than force Port St. Lucie into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this city.",
    "Every cleaner who works under the Port St. Lucie Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Port St. Lucie, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Port St. Lucie as in Minneapolis. Port St. Lucie Maid does not. We built our service around this city's new-construction surge, active-adult communities, and sprawling footprint.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Port St. Lucie Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Port St. Lucie home on recurring visits.",
  ],
  challenges: [
    { title: 'New-Construction Dust', body: "As one of Florida's fastest-growing cities, many clients move into homes in Tradition and nearby communities still shedding drywall dust and construction debris. We adjust our first-clean approach for newly built homes." },
    { title: 'Active-Adult Community Standards', body: "Communities like PGA Village Verano often have HOA expectations around presentation and consistency. We clean with those standards in mind." },
    { title: 'Humidity & Mold Prevention', body: "Treasure Coast humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit." },
    { title: 'Sprawling City Scheduling', body: "Port St. Lucie's rapid growth means travel time varies a lot by neighborhood. We build routes by area so your appointment window stays reliable." },
    { title: 'Seasonal Resident Turnover', body: "Many Port St. Lucie homes belong to part-time and seasonal residents. We offer arrival-prep cleanings timed to when owners return for the season." },
    { title: 'Hurricane Season Readiness', body: "Storm season means shutter dust and post-storm cleanup. We offer flexible scheduling around storm prep and recovery." },
  ],
  neighborhoods: [
    { name: 'Tradition', blurb: "This large master-planned community is one of Port St. Lucie's fastest-growing areas, and where much of our new-construction first-clean work happens." },
    { name: 'St. Lucie West', blurb: "This established mixed-use community is home to many of our longest-running recurring clients, who value a consistent cleaner they can trust." },
    { name: 'PGA Village Verano', blurb: "This golf-course active-adult community trusts Port St. Lucie Maid for everything from routine upkeep to deep cleans, cleaned with HOA presentation standards in mind." },
    { name: 'Lakewood Park', blurb: "This established residential area is a regular stop for our bi-weekly and monthly cleaning plans." },
    { name: 'The Cascades', blurb: "This 55-and-over active-adult community is where many of our seasonal and part-time residents rely on us for arrival-prep cleanings." },
    { name: 'Sandpiper Bay', blurb: "Close to the St. Lucie River, our Sandpiper Bay clients trust us for reliable, consistent cleaning of both full-time and seasonal homes." },
  ],
  pricingExplainer: [
    "Port St. Lucie Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy Lakewood Park home might only need the 2-hour minimum, while a new Tradition build getting its first post-construction clean could run 5 hours or more.",
    "Recurring service is where Port St. Lucie Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Port St. Lucie.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Port St. Lucie families with kids or pets. Weekly service keeps clutter and dust from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households or active-adult residents. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes or seasonal residences. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, post-construction job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "We moved into a new build in Tradition and they cleared out every bit of construction dust before we unpacked.", name: 'Karen D.', neighborhood: 'Tradition' },
    { text: "They've handled our PGA Village Verano villa weekly for over a year — always the same reliable cleaner, and they know our HOA standards.", name: 'Walt R.', neighborhood: 'PGA Village Verano' },
    { text: "We come down for the season and they get our Cascades home ready before every arrival. Never a hitch.", name: 'Barbara N.', neighborhood: 'The Cascades' },
    { text: "Booked a deep clean before hosting family in St. Lucie West and they went above and beyond.", name: 'Miguel A.', neighborhood: 'St. Lucie West' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Port St. Lucie?', answer: 'Port St. Lucie Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Port St. Lucie?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Port St. Lucie Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, seasonal-home turnovers, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Do you clean brand-new construction homes?', answer: "Yes — this is one of our specialties in fast-growing communities like Tradition. We clear out drywall dust and construction debris before you move in." },
    { question: 'Can you clean homes in active-adult and 55-and-over communities?', answer: "Absolutely. We're familiar with HOA presentation standards in communities like PGA Village Verano and The Cascades." },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for closing on a new build or moving out of a rental." },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or gate code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Port St. Lucie Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of Port St. Lucie do you serve?', answer: 'Tradition, St. Lucie West, PGA Village Verano, Lakewood Park, The Cascades, Sandpiper Bay, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Port St. Lucie.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Port St. Lucie Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Port St. Lucie Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a small condo or villa?', answer: 'Yes, our 2-hour minimum is usually perfect for a smaller unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Port St. Lucie Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'Do you clean seasonal homes that sit empty for months?', answer: 'Yes, with arrival-prep cleanings timed to when you return for the season.' },
    { question: 'What if my community has a gate or check-in?', answer: 'Just let us know your community\'s procedures when booking and we\'ll build in the extra time.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Is Port St. Lucie Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents or builders?', answer: 'Yes, we regularly clean staged listings and model homes in new communities.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Port St. Lucie Maid serve both houses and villas?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Port St. Lucie Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
    { question: 'How far out does Port St. Lucie Maid travel?', answer: 'We cover the greater Port St. Lucie area — ask when booking if you\'re unsure whether your community is included.' },
  ],
}
