import type { EmdMicrositeConfig } from './types'

export const riverviewMaidConfig: EmdMicrositeConfig = {
  domain: 'riverviewmaid.com',
  brandName: 'Riverview Maid',
  city: 'Riverview',
  regionLabel: 'Riverview, FL',
  metaTitle: 'Riverview Maid and Cleaning Service',
  metaDescription: 'Riverview Maid — house cleaning across Panther Trace, Summerfield & South Fork starting at $49 per hour. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '27.8661', lng: '-82.3254' },
  introParagraphs: [
    "Riverview Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across one of the Tampa Bay area's fastest-growing suburbs — a Hillsborough County community of sprawling master-planned neighborhoods, new construction, and young families moving in every month. If you live in Riverview, you know the pace: new subdivisions filling in constantly and homes that need real upkeep between school runs and work schedules. We built Riverview Maid to answer exactly that problem: a local cleaning service that understands this community and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Riverview Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Riverview.",
    "Whether you need a one-time deep clean before hosting family, a recurring weekly service for a busy Summerfield household, or a fast turnover clean for a South Fork rental between tenants, Riverview Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from brand-new builds to established Panther Trace homes, and that range of experience shapes how we train every cleaner. Riverview Maid was built around the reality that this fast-growing suburb demands a service that scales with it.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Riverview Maid exists because this rapidly growing Hillsborough County suburb's master-planned communities and young family population make it its own world. So rather than force Riverview into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this city.",
    "Every cleaner who works under the Riverview Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Riverview, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Riverview as in Minneapolis. Riverview Maid does not. We built our service around this suburb's rapid new growth, young families, and master-planned communities.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Riverview Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Riverview home on recurring visits.",
  ],
  challenges: [
    { title: 'New-Construction Dust', body: "As one of Tampa Bay's fastest-growing suburbs, many clients move into homes in South Fork and nearby communities still shedding drywall dust and construction debris. We adjust our first-clean approach for newly built homes." },
    { title: 'Busy Young-Family Schedules', body: "Many Riverview households juggle school schedules, sports, and two working parents. We offer flexible booking windows so cleaning fits your life." },
    { title: 'HOA Presentation Standards', body: "Panther Trace and Summerfield often have HOA expectations around presentation and consistency. We clean with those standards in mind." },
    { title: 'Humidity & Mold Prevention', body: "Tampa Bay humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit." },
    { title: 'Large Family Homes', body: "Many Riverview homes are larger family properties that take longer to clean thoroughly. We adjust cleaning time estimates for these homes." },
    { title: 'Hurricane Season Readiness', body: "Storm season means shutter dust and post-storm cleanup. We offer flexible scheduling around storm prep and recovery." },
  ],
  neighborhoods: [
    { name: 'Panther Trace', blurb: "This large, established community is home to many of our longest-running recurring clients, who value a consistent cleaner they can trust." },
    { name: 'Summerfield', blurb: "This family-friendly neighborhood is a favorite for our weekly and bi-weekly recurring clients." },
    { name: 'South Fork', blurb: "This newer planned community calls for a first-clean approach tuned to newer construction." },
    { name: 'Rivercrest', blurb: "This established community trusts Riverview Maid for everything from routine upkeep to deep cleans." },
    { name: 'Boyette Springs', blurb: "This residential area is a regular stop for our bi-weekly and monthly cleaning plans." },
    { name: 'Bell Creek', blurb: "This growing area's homes call for consistent, detail-first cleaning for busy households." },
  ],
  pricingExplainer: [
    "Riverview Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy Panther Trace home might only need the 2-hour minimum, while a South Fork family home getting its first post-construction clean could run 5 hours or more.",
    "Recurring service is where Riverview Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Riverview.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Riverview families with kids or pets. Weekly service keeps clutter and dust from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "We moved into a new build in South Fork and they cleared out every bit of construction dust before we unpacked.", name: 'Ashley T.', neighborhood: 'South Fork' },
    { text: "Between school runs and two jobs we never had time to keep up. Riverview Maid gave us our weekends back.", name: 'Marcus B.', neighborhood: 'Summerfield' },
    { text: "They've handled our Panther Trace home weekly for over a year — always the same reliable cleaner.", name: 'Tamara G.', neighborhood: 'Panther Trace' },
    { text: "Booked a deep clean before hosting family and they went above and beyond.", name: 'Derek W.', neighborhood: 'Rivercrest' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Riverview?', answer: 'Riverview Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Riverview?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Riverview Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Do you clean brand-new construction homes?', answer: "Yes — this is one of our specialties in fast-growing communities like South Fork. We clear out drywall dust and construction debris before you move in." },
    { question: 'Can you clean homes in HOA communities like Panther Trace?', answer: "Absolutely. We're familiar with the presentation standards these communities expect." },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for closing on a new build or moving out of a rental." },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or gate code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Riverview Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of Riverview do you serve?', answer: 'Panther Trace, Summerfield, South Fork, Rivercrest, Boyette Springs, Bell Creek, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Riverview.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Riverview Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Riverview Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a townhome or smaller unit?', answer: 'Yes, our 2-hour minimum is usually perfect for a smaller unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Riverview Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'What if my community has a gate or HOA check-in?', answer: 'Just let us know your community\'s procedures when booking and we\'ll build in the extra time.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Is Riverview Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents or builders?', answer: 'Yes, we regularly clean staged listings and model homes in new communities.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Riverview Maid serve both houses and townhomes?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Riverview Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
