import type { EmdMicrositeConfig } from './types'

export const sarasotaMaidConfig: EmdMicrositeConfig = {
  domain: 'sarasotaflmaid.com',
  brandName: 'Sarasota Maid',
  city: 'Sarasota',
  regionLabel: 'Sarasota, FL',
  metaTitle: 'Sarasota Maid and Cleaning Service',
  metaDescription: 'Sarasota Maid — house cleaning across Siesta Key, Downtown Sarasota & Laurel Park starting at $49 per hour. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '27.3364', lng: '-82.5307' },
  introParagraphs: [
    "Sarasota Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across a city known for its arts scene, its downtown high-rises, and Siesta Key's famous powder-quartz sand. If you live in Sarasota, you know how quickly barrier-island sand and Gulf humidity can wear down a home. We built Sarasota Maid to answer exactly that problem: a local cleaning service that understands this community and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Sarasota Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Sarasota.",
    "Whether you need a one-time deep clean before hosting guests on Siesta Key, a recurring weekly service for a busy Laurel Park household, or a fast turnover clean for a downtown Sarasota condo between guests, Sarasota Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from historic Southside Village bungalows to high-rise condos on Lido Key, and that range of experience shapes how we train every cleaner. Sarasota Maid was built around the reality that this city's mix of arts-district character and barrier-island living demands real range.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Sarasota Maid exists because this Gulf Coast arts community's barrier-island beaches, downtown condo towers, and historic neighborhoods make it its own world. So rather than force Sarasota into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this city.",
    "Every cleaner who works under the Sarasota Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Sarasota, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Sarasota as in Minneapolis. Sarasota Maid does not. We built our service around this city's barrier-island sand, downtown high-rises, and historic in-town neighborhoods.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Sarasota Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Sarasota home on recurring visits.",
  ],
  challenges: [
    { title: 'Siesta Key\'s Famous Sand', body: "Siesta Key's powder-fine quartz sand tracks indoors more than typical beach sand and works into carpets and grout lines. We use techniques built for lifting fine sand without grinding it deeper in." },
    { title: 'Salt Air & Corrosion', body: "Sarasota's Gulf-front properties carry fine salt particulate that settles on chrome fixtures, appliances, and window tracks. We use products chosen to cut salt residue without damaging finishes." },
    { title: 'High-Rise Condo Logistics', body: "Many of our downtown and Lido Key clients live in buildings with front-desk check-in and freight-elevator scheduling. We coordinate arrival windows around your building's rules." },
    { title: 'Humidity & Mold Prevention', body: "Gulf Coast humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit." },
    { title: 'Historic Home Care', body: "Southside Village and Laurel Park homes often have original details that need gentler products than a newer build. We adjust our approach accordingly." },
    { title: 'Snowbird Turnover', body: "Many Sarasota condos and homes sit empty for months at a time during off-season. We offer arrival-prep cleanings timed to when owners return." },
  ],
  neighborhoods: [
    { name: 'Siesta Key', blurb: "Home to some of the world's finest sand, Siesta Key's beach houses and condos are where much of our vacation-rental turnover and sand-cleanup work happens." },
    { name: 'Downtown Sarasota', blurb: "Close to the arts district, our downtown high-rise clients rely on us for fast, reliable turnover cleaning between stays." },
    { name: 'Southside Village', blurb: "This walkable, historic neighborhood is a favorite for our weekly and bi-weekly recurring clients." },
    { name: 'Laurel Park', blurb: "This historic in-town neighborhood's bungalows call for extra care with original details on every visit." },
    { name: 'Rosemary District', blurb: "This up-and-coming neighborhood near downtown trusts Sarasota Maid for everything from routine upkeep to deep cleans." },
    { name: 'Lido Key', blurb: "Our Lido Key condo clients trust us for consistent, detail-first cleaning between beach days." },
  ],
  pricingExplainer: [
    "Sarasota Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy downtown condo might only need the 2-hour minimum, while a Laurel Park bungalow getting its first deep clean could run 5 hours or more.",
    "Recurring service is where Sarasota Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Sarasota.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Sarasota full-time residents and families. Weekly service keeps sand and salt buildup from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes or seasonal residences. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "Siesta Key's sand is so fine it gets everywhere. Sarasota Maid is the first cleaner who's actually gotten it out of our grout.", name: 'Rachel B.', neighborhood: 'Siesta Key' },
    { text: "We live downtown and the building requires check-in coordination. They handle it every time without a hitch.", name: 'George T.', neighborhood: 'Downtown Sarasota' },
    { text: "They've handled our Laurel Park bungalow weekly for over a year — always the same reliable cleaner.", name: 'Nina F.', neighborhood: 'Laurel Park' },
    { text: "Our Lido Key condo needed a deep clean before season and they went above and beyond.", name: 'Howard L.', neighborhood: 'Lido Key' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Sarasota?', answer: 'Sarasota Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Sarasota?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Sarasota Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, Airbnb turnovers, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Can you get Siesta Key\'s fine sand out of carpets and grout?', answer: "Yes — this is one of our specialties. Siesta Key's powder-quartz sand needs a different technique than typical beach sand, and we use it on every visit." },
    { question: 'Can you clean high-rise condos with front-desk security?', answer: "Absolutely. Just let us know your building's procedures when booking." },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for closing on a Lido Key condo or ending a lease downtown." },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or door code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Sarasota Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of Sarasota do you serve?', answer: 'Siesta Key, downtown Sarasota, Southside Village, Laurel Park, the Rosemary District, Lido Key, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Sarasota.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Sarasota Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Sarasota Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a studio or small condo?', answer: 'Yes, our 2-hour minimum is usually perfect for a small unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Sarasota Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'Do you clean Airbnb and short-term rentals on Siesta Key?', answer: 'Yes, with fast turnaround between guests — this is one of our most requested services on the Key.' },
    { question: 'What if my building requires vendor registration?', answer: 'Send us your requirements ahead of time and we\'ll get registered.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Do you clean seasonal homes that sit empty for months?', answer: 'Yes, with arrival-prep cleanings timed to when you return for the season.' },
    { question: 'Is Sarasota Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Sarasota Maid serve both condos and houses?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Sarasota Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
