import type { EmdMicrositeConfig } from './types'

export const snellIsleMaidConfig: EmdMicrositeConfig = {
  domain: 'snellislemaid.com',
  brandName: 'Snell Isle Maid',
  city: 'Snell Isle',
  regionLabel: 'Snell Isle, St. Petersburg, FL',
  metaTitle: 'Snell Isle Maid — House Cleaning Service',
  metaDescription: 'Snell Isle Maid — house cleaning near the Vinoy Golf Club & Coffee Pot Bayou starting at $49 per hour. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '27.7960', lng: '-82.6180' },
  introParagraphs: [
    'Snell Isle Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning for Snell Isle and the surrounding St. Petersburg area, in Pinellas County. If you live near the Vinoy Golf Club or Coffee Pot Bayou, you know what it takes to keep a home clean in this part of the Tampa Bay region — real Gulf Coast humidity, real wear, and a housing stock with real character. We built Snell Isle Maid to answer exactly that: a local cleaning service that understands Snell Isle living and shows up on time, every time.',
    'We\'re not a national franchise cold-calling from a call center in another state. Snell Isle Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Snell Isle.',
    'Whether you need a one-time deep clean before hosting family, a recurring weekly service for a busy household, or a fast turnover clean for an estate-home closing or a seasonal owner\'s return, Snell Isle Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.',
    'Our team has cleaned everything from historic Snell Isle homes to newer builds elsewhere in St. Petersburg, and that range of experience shapes how we train every cleaner. Snell Isle Maid was built around the reality that St. Petersburg\'s mix of established neighborhoods and coastal humidity demands real range.',
  ],
  ourStory: [
    'The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.',
    'Snell Isle Maid exists because Snell Isle — anchored by the Vinoy Golf Club and Coffee Pot Bayou — deserves a cleaning brand tuned to it specifically, not folded anonymously into a citywide service. So rather than treat Snell Isle as an afterthought, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this part of St. Petersburg.',
    'Every cleaner who works under the Snell Isle Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.',
    'We\'re proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Snell Isle, one cleaning at a time.',
  ],
  differentiation: [
    'National cleaning franchises operate the same playbook everywhere — the same checklist in Snell Isle as in Minneapolis. Snell Isle Maid does not. We built our service around St. Petersburg\'s housing stock, humidity, and the specific character of Snell Isle.',
    'Franchise pricing also tends to hide the real cost behind a \'custom quote.\' Snell Isle Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.',
    'And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Snell Isle home on recurring visits.',
  ],
  challenges: [
    { title: 'A Man-Made Luxury Island', body: 'Snell Isle is one of St. Petersburg\'s most exclusive addresses — a man-made island of large waterfront estates around the Vinoy Golf Club, where boat docks, pools, and expansive square footage shape every estimate we give.' },
    { title: 'Estate-Level Detail Work', body: 'Snell Isle homes tend to be larger and more custom-finished than the St. Pete average, and many clients here want the same cleaner returning for consistency on high-value interior finishes.' },
    { title: 'Humidity & Mold Prevention', body: 'St. Petersburg\'s Gulf Coast humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit in Snell Isle.' },
    { title: 'Hurricane Season Readiness', body: 'Tampa Bay\'s storm season means shutter dust and post-storm cleanup for Snell Isle just as much as anywhere else in St. Petersburg. We offer flexible scheduling around storm prep and recovery.' },
    { title: 'Tree & Landscaping Debris', body: 'Mature landscaping around Snell Isle means pollen and leaf debris get tracked indoors more than in newer, less-landscaped subdivisions. We use techniques suited to lifting fine particulate without smearing it.' },
  ],
  neighborhoods: [
    { name: 'Old Northeast', blurb: 'St. Petersburg\'s flagship historic bungalow district, just south of the causeway.' },
    { name: 'Coffee Pot Bayou', blurb: 'The waterfront corridor connecting Snell Isle to Old Northeast.' },
    { name: 'Shore Acres', blurb: 'Another waterfront St. Pete neighborhood northeast of Snell Isle.' },
    { name: 'Downtown St. Petersburg', blurb: 'A short drive south, home to the Vinoy hotel and Beach Drive.' },
    { name: 'Venetian Isles', blurb: 'A canal-front neighborhood further northeast with similar boat-access homes.' },
  ],
  pricingExplainer: [
    'Snell Isle Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.',
    'What determines how many hours your home needs? Mainly size and condition. A tidy Snell Isle-area home might only need the 2-hour minimum, while a larger property getting its first deep clean could run 5 hours or more.',
    'Recurring service is where Snell Isle Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.',
    'One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Snell Isle and greater St. Petersburg.',
  ],
  firstVisitSteps: [
    'Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.',
    'We confirm your appointment window by text, usually within 15 minutes.',
    'Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.',
    'We do a final walkthrough before wrapping up. If anything doesn\'t meet your expectations, tell us within 24 hours and we\'ll send someone back at no extra charge.',
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: 'The most popular plan among Snell Isle-area families with kids or pets. Weekly service keeps clutter and dust from getting ahead of you, earning 20% off.' },
    { frequency: 'Bi-Weekly', body: 'A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%.' },
    { frequency: 'Monthly', body: 'Best suited to light-use homes. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount.' },
    { frequency: 'One-Time', body: 'Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge.' },
  ],
  testimonials: [
    { text: 'Our home near the Vinoy Golf Club needed real care, not a rushed once-over. They got it.', name: 'Victoria S.', neighborhood: 'Snell Isle' },
    { text: 'They\'ve cleaned our place weekly for months now — always the same reliable cleaner.', name: 'Charles B.', neighborhood: 'Shore Acres' },
    { text: 'We needed a fast turnaround and they delivered, no excuses.', name: 'Margaret O.', neighborhood: 'Coffee Pot Bayou' },
    { text: 'Booked a deep clean before hosting family and they went above and beyond.', name: 'Richard N.', neighborhood: 'Venetian Isles' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Snell Isle?', answer: 'Snell Isle Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'How do I book a cleaning in Snell Isle?', answer: 'Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning.' },
    { question: 'Do you offer move-in/move-out cleaning in Snell Isle?', answer: 'Yes — perfect for an estate-home closing or a seasonal owner\'s return.' },
    { question: 'What areas near Snell Isle do you serve?', answer: 'Snell Isle, Old Northeast, Coffee Pot Bayou, Shore Acres, Downtown St. Petersburg, Venetian Isles, and surrounding St. Petersburg neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Snell Isle or greater St. Petersburg.' },
    { question: 'Can you handle homes with a man-made luxury island?', answer: 'Snell Isle is one of St. Petersburg\'s most exclusive addresses — a man-made island of large waterfront estates around the Vinoy Golf Club, where boat docks, pools, and expansive square footage shape every estimate we give.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: 'We charge by the hour, not a flat rate, so pricing stays fair for every home size.' },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Can I customize what gets cleaned?', answer: 'Of course — just tell us your priorities when booking.' },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: 'Yes, we prioritize consistency for recurring clients.' },
    { question: 'Will I need to be home during the cleaning?', answer: 'It\'s up to you — many clients leave a key or door code.' },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'Do you have reviews I can read?', answer: 'Yes, Snell Isle Maid carries The Florida Maid\'s 5.0-star Google rating.' },
    { question: 'How long has Snell Isle Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a smaller home or apartment?', answer: 'Yes, our 2-hour minimum is usually perfect for a smaller unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Snell Isle Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'Do you manage cleanings for landlords with multiple rentals?', answer: 'Yes, we regularly work with landlords managing several properties around Snell Isle and St. Petersburg.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Is Snell Isle Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Snell Isle Maid serve both houses and apartments?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Snell Isle Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
