import type { EmdMicrositeConfig } from './types'

export const stPeteMaidConfig: EmdMicrositeConfig = {
  domain: 'stpetemaid.com',
  brandName: 'St. Pete Maid',
  city: 'St. Petersburg',
  regionLabel: 'St. Petersburg, FL',
  metaTitle: 'St. Pete Maid and Cleaning Service',
  metaDescription: 'St. Pete Maid — house cleaning across Old Northeast, Snell Isle & Downtown St. Pete from $49/hr. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '27.7676', lng: '-82.6403' },
  introParagraphs: [
    "St. Pete Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across a city known for its arts murals, historic Craftsman bungalows, and a rapidly growing downtown skyline on Tampa Bay. If you live in St. Petersburg, you know how quickly Gulf Coast humidity and bay-front salt air can wear down a home. We built St. Pete Maid to answer exactly that problem: a local cleaning service that understands this city's character and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. St. Pete Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around St. Petersburg.",
    "Whether you need a one-time deep clean before hosting guests in Old Northeast, a recurring weekly service for a busy Snell Isle household, or a fast turnover clean for a downtown condo between guests, St. Pete Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from historic Kenwood bungalows to waterfront towers downtown, and that range of experience shapes how we train every cleaner. St. Pete Maid was built around the reality that this city's mix of historic character and rapid downtown growth demands real range.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "St. Pete Maid exists because this Tampa Bay arts city's historic bungalow neighborhoods, waterfront enclaves, and growing downtown make it its own world. So rather than force St. Petersburg into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this city.",
    "Every cleaner who works under the St. Pete Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in St. Petersburg, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in St. Petersburg as in Minneapolis. St. Pete Maid does not. We built our service around this city's historic bungalows, waterfront neighborhoods, and downtown high-rise condos.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' St. Pete Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your St. Petersburg home on recurring visits.",
  ],
  challenges: [
    { title: 'Historic Bungalow Care', body: "Old Northeast, Kenwood, and other historic districts are full of Craftsman-era bungalows with original woodwork and details. We adjust our approach to protect original finishes." },
    { title: 'High-Rise Condo Logistics', body: "Many of our downtown clients live in buildings with front-desk check-in and freight-elevator scheduling. We coordinate arrival windows around your building's rules." },
    { title: 'Waterfront Humidity & Salt Air', body: "Snell Isle and Shore Acres homes sit close to Tampa Bay, where salt air and humidity settle on fixtures and create mildew risk. We pay close attention to these zones." },
    { title: 'Canal & Waterfront Homes', body: "Snell Isle's canal-front homes track in more dirt and debris from dock access and boat traffic. We adjust our routine for homes with direct water access." },
    { title: 'Humidity & Mold Prevention', body: "Tampa Bay humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit." },
    { title: 'Hurricane Season Readiness', body: "Storm season means shutter dust and post-storm cleanup. We offer flexible scheduling around storm prep and recovery." },
  ],
  neighborhoods: [
    { name: 'Old Northeast', blurb: "Brick-lined streets and Craftsman bungalows make Old Northeast one of St. Pete's most requested neighborhoods, and a favorite for our weekly and bi-weekly recurring clients." },
    { name: 'Snell Isle', blurb: "This upscale waterfront neighborhood is home to many of our longest-running recurring clients, who value a consistent cleaner they can trust." },
    { name: 'Downtown / EDGE District', blurb: "Close to the arts murals and waterfront, our downtown condo clients rely on us for fast, reliable turnover cleaning." },
    { name: 'Historic Kenwood', blurb: "This eclectic, artsy neighborhood's bungalows call for extra care with original details on every visit." },
    { name: 'Shore Acres', blurb: "This waterfront neighborhood's canal-front homes call for extended deep-cleaning sessions and careful attention to salt residue." },
    { name: 'Roser Park', blurb: "One of St. Pete's oldest historic districts, Roser Park trusts St. Pete Maid for everything from routine upkeep to deep cleans." },
  ],
  pricingExplainer: [
    "St. Pete Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy downtown condo might only need the 2-hour minimum, while a Snell Isle waterfront home getting its first deep clean could run 5 hours or more.",
    "Recurring service is where St. Pete Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of St. Petersburg.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among St. Pete families with kids or pets. Weekly service keeps humidity and dust from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes or seasonal residences. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "Our Old Northeast bungalow has original woodwork and they treated it with real care. Not every cleaning company would bother.", name: 'Colleen M.', neighborhood: 'Old Northeast' },
    { text: "We live downtown and the building requires check-in coordination. They handle it every time without a hitch.", name: 'Derek A.', neighborhood: 'Downtown / EDGE District' },
    { text: "They've handled our Snell Isle home weekly for over a year — always the same reliable cleaner.", name: 'Sheila R.', neighborhood: 'Snell Isle' },
    { text: "Booked a deep clean before hosting family and they went above and beyond.", name: 'Marcus T.', neighborhood: 'Historic Kenwood' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in St. Petersburg?', answer: 'St. Pete Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in St. Petersburg?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does St. Pete Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, Airbnb turnovers, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Can you clean historic bungalows in Old Northeast or Kenwood?', answer: "Absolutely. We use gentler products suited to original woodwork and vintage details." },
    { question: 'Can you clean high-rise condos with front-desk security?', answer: "Absolutely. Just let us know your building's procedures when booking." },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for closing on a Snell Isle waterfront home or ending a lease downtown." },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or door code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is St. Pete Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of St. Petersburg do you serve?', answer: 'Old Northeast, Snell Isle, downtown/EDGE District, Historic Kenwood, Shore Acres, Roser Park, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in St. Petersburg.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, St. Pete Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has St. Pete Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a studio or small condo?', answer: 'Yes, our 2-hour minimum is usually perfect for a small unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact St. Pete Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'Do you clean canal-front and waterfront homes?', answer: 'Yes, we regularly service waterfront properties across Snell Isle and Shore Acres.' },
    { question: 'What if my building requires vendor registration?', answer: 'Send us your requirements ahead of time and we\'ll get registered.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Do you clean vacation homes that sit empty?', answer: 'Yes, with arrival-prep cleanings before you visit.' },
    { question: 'Is St. Pete Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does St. Pete Maid serve both condos and houses?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does St. Pete Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
