import type { EmdMicrositeConfig } from './types'

export const theVillagesMaidConfig: EmdMicrositeConfig = {
  domain: 'thevillagesmaid.com',
  brandName: 'The Villages Maid',
  city: 'The Villages',
  regionLabel: 'The Villages, FL',
  metaTitle: 'The Villages Maid and Cleaning Service',
  metaDescription: 'The Villages Maid — house cleaning across Spanish Springs, Lake Sumter Landing & Brownwood from $49/hr. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '28.9005', lng: '-81.9401' },
  introParagraphs: [
    "The Villages Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across America's largest active-adult community — a sprawling network of villas and golf-cart-friendly neighborhoods spanning three counties. If you live in The Villages, you know how much this community's presentation standards and golf-cart-paced lifestyle matter to residents. We built The Villages Maid to answer exactly that problem: a local cleaning service that understands this community and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. The Villages Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around The Villages.",
    "Whether you need a one-time deep clean before hosting family, a recurring weekly service for a busy villa near Spanish Springs, or a fast turnover clean for a seasonal home between visits, The Villages Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from cozy courtyard villas to larger designer homes, and that range of experience shapes how we train every cleaner. The Villages Maid was built around the reality that this community's scale and seasonal population demand a service that scales with it.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "The Villages Maid exists because this massive active-adult community's villa-style homes, seasonal residents, and presentation standards make it its own world. So rather than force The Villages into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this community.",
    "Every cleaner who works under The Villages Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in The Villages, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in The Villages as in Minneapolis. The Villages Maid does not. We built our service around this community's villa-style homes, seasonal population, and presentation expectations.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' The Villages Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your home in The Villages on recurring visits.",
  ],
  challenges: [
    { title: 'Seasonal Resident Turnover', body: "The Villages has one of Florida's largest seasonal populations. We offer arrival-prep cleanings timed to when owners return for the season and closing cleans before they head north." },
    { title: 'Villa & Designer Home Standards', body: "Villages homes range from compact courtyard villas to larger designer models, each with its own presentation expectations. We tailor our approach to your home type." },
    { title: 'Golf-Cart Community Logistics', body: "With homes accessible primarily by golf cart paths in many sections, we plan our routes and scheduling around this community's unique layout." },
    { title: 'Humidity & Mold Prevention', body: "Central Florida humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit." },
    { title: 'Large Sprawling Coverage Area', body: "The Villages spans a huge footprint across Sumter, Lake, and Marion counties. We build routes by area so your appointment window stays reliable." },
    { title: 'Hurricane Season Readiness', body: "Storm season means shutter dust and post-storm cleanup. We offer flexible scheduling around storm prep and recovery." },
  ],
  neighborhoods: [
    { name: 'Spanish Springs', blurb: "This original town square area is home to many of our longest-running recurring clients, who value a consistent cleaner they can trust." },
    { name: 'Lake Sumter Landing', blurb: "This waterfront town square area's homes are a favorite for our weekly and bi-weekly recurring clients." },
    { name: 'Brownwood', blurb: "This newer town square area trusts The Villages Maid for everything from routine upkeep to deep cleans." },
    { name: 'Village of Bonita', blurb: "This established residential village is a regular stop for our bi-weekly and monthly cleaning plans." },
    { name: 'Village of Fenney', blurb: "This newer village on the south end calls for a first-clean approach tuned to newer construction." },
    { name: 'Historic Side (Original Villages)', blurb: "Our clients in the historic original section trust us for consistent, detail-first cleaning of established villas." },
  ],
  pricingExplainer: [
    "The Villages Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy courtyard villa might only need the 2-hour minimum, while a larger designer home getting its first deep clean could run 5 hours or more.",
    "Recurring service is where The Villages Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of The Villages.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among full-time Villages residents. Weekly service keeps clutter and dust from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller villas. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes or seasonal residences. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, arrival-prep or closing clean, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "We come down for the season and they get our villa ready before every arrival. Never a hitch.", name: 'Norma K.', neighborhood: 'Spanish Springs' },
    { text: "They've handled our home near Lake Sumter Landing weekly for over a year — always the same reliable cleaner.", name: 'Fred T.', neighborhood: 'Lake Sumter Landing' },
    { text: "Our designer home is larger than most and they always account for that in scheduling.", name: 'Sandra L.', neighborhood: 'Village of Bonita' },
    { text: "Booked a deep clean before hosting family and they went above and beyond.", name: 'Walter B.', neighborhood: 'Brownwood' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in The Villages?', answer: 'The Villages Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in The Villages?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning do you offer in The Villages?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, seasonal arrival-prep and closing cleans, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Do you clean seasonal homes that sit empty for months?', answer: "Yes — this is one of our specialties in The Villages. We time arrival-prep cleanings to when you return for the season and closing cleans before you head north." },
    { question: 'Can you clean smaller courtyard villas?', answer: "Absolutely — our 2-hour minimum is usually a perfect fit for a courtyard villa." },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for closing on a new villa or moving between homes within The Villages." },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or gate code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings, and earlier around the seasonal turnover months.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours are you available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of The Villages do you serve?', answer: 'Spanish Springs, Lake Sumter Landing, Brownwood, the Village of Bonita, the Village of Fenney, and surrounding villages.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere across The Villages.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, The Villages Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has The Villages Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact The Villages Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'What if my village has a gate or check-in?', answer: 'Just let us know your community\'s procedures when booking and we\'ll build in the extra time.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean homes between owners or family members visiting?', answer: 'Yes, that\'s our move-in/move-out and arrival-prep service.' },
    { question: 'Can you clean around a home office or hobby room setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Is The Villages Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger designer homes?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does The Villages Maid serve both villas and larger homes?', answer: 'Yes, both are core to our service area.' },
    { question: 'How do you handle scheduling across such a large community?', answer: 'We build our routes by section, so wherever your villa is located across The Villages, your appointment window stays reliable.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
