import type { EmdMicrositeConfig } from './types'

export const veroBeachMaidConfig: EmdMicrositeConfig = {
  domain: 'verobeachmaid.com',
  brandName: 'Vero Beach Maid',
  city: 'Vero Beach',
  regionLabel: 'Vero Beach, FL',
  metaTitle: 'Vero Beach Maid and Cleaning Service',
  metaDescription: 'Vero Beach Maid — house cleaning across Riomar, Central Beach & Grand Harbor from $49/hr. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '27.6386', lng: '-80.3973' },
  introParagraphs: [
    "Vero Beach Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across one of the Treasure Coast's most refined communities — from barrier-island estates in Riomar to golf-and-marina living in Grand Harbor. If you live in Vero Beach, you know how quickly ocean air and seasonal turnover can wear down a home. We built Vero Beach Maid to answer exactly that problem: a local cleaning service that understands this community's standards and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Vero Beach Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Vero Beach.",
    "Whether you need a one-time deep clean before hosting guests at your Central Beach condo, a recurring weekly service for a busy Riomar household, or a fast turnover clean for a seasonal home in The Moorings between visits, Vero Beach Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from downtown bungalows to barrier-island estates, and that range of experience shapes how we train every cleaner. Vero Beach Maid was built around the reality that this community's mix of full-time residents and seasonal owners demands real flexibility.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Vero Beach Maid exists because this Treasure Coast community's barrier-island estates, golf-and-marina neighborhoods, and seasonal population make it its own world. So rather than force Vero Beach into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this city.",
    "Every cleaner who works under the Vero Beach Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Vero Beach, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Vero Beach as in Minneapolis. Vero Beach Maid does not. We built our service around this community's barrier-island estates, golf-and-marina communities, and large seasonal population.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Vero Beach Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Vero Beach home on recurring visits.",
  ],
  challenges: [
    { title: 'Salt Air & Corrosion', body: "Riomar and Central Beach properties sit right on the barrier island, where fine salt particulate settles on chrome fixtures, appliances, and window tracks. We use products chosen to cut salt residue without damaging finishes." },
    { title: 'Seasonal Resident Turnover', body: "Vero Beach has one of Florida's larger seasonal populations. We offer arrival-prep cleanings timed to when owners return for the season and closing cleans before they head north." },
    { title: 'Golf & Marina Community Standards', body: "Communities like Grand Harbor and The Moorings often have HOA expectations around presentation and consistency. We clean with those standards in mind." },
    { title: 'Humidity & Mold Prevention', body: "Treasure Coast humidity creates ideal conditions for mildew, especially in bathrooms and closets. We pay close attention to these high-risk zones on every visit." },
    { title: 'Large Estate Homes', body: "Many Vero Beach properties are larger estate homes that take longer to clean thoroughly. We staff multi-person teams for these properties as needed." },
    { title: 'Hurricane Season Readiness', body: "Storm season means shutter dust and post-storm cleanup. We offer flexible scheduling around storm prep and recovery." },
  ],
  neighborhoods: [
    { name: 'Riomar', blurb: "This historic barrier-island neighborhood is home to many of our longest-running recurring clients, who value a consistent cleaner they can trust." },
    { name: 'Central Beach', blurb: "Close to the ocean and downtown shopping, Central Beach's condos and cottages are a favorite for our weekly and bi-weekly recurring clients." },
    { name: 'Old Town / Downtown Vero', blurb: "Vero Beach's walkable downtown core trusts us for everything from routine upkeep to deep cleans before family visits." },
    { name: 'Grand Harbor', blurb: "This golf-and-marina community's homes call for cleaning with real attention to presentation standards." },
    { name: 'The Moorings', blurb: "One of Vero Beach's premier golf communities, The Moorings is where much of our seasonal-home arrival-prep work happens." },
    { name: 'Vero Isles', blurb: "This waterfront neighborhood's canal-front homes call for extended deep-cleaning sessions and careful attention to salt residue." },
  ],
  pricingExplainer: [
    "Vero Beach Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy Central Beach condo might only need the 2-hour minimum, while a Riomar estate getting its first deep clean could run 5 hours or more.",
    "Recurring service is where Vero Beach Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Vero Beach.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Vero Beach full-time residents. Weekly service keeps salt and humidity buildup from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes or seasonal residences. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, arrival-prep or closing clean, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "We live on the island in Riomar and the salt air is brutal on our fixtures. Vero Beach Maid knows exactly how to handle it.", name: 'Eleanor W.', neighborhood: 'Riomar' },
    { text: "We come down for the season and they get our Moorings villa ready before every arrival. Never a hitch.", name: 'Harold G.', neighborhood: 'The Moorings' },
    { text: "They've handled our Central Beach condo weekly for over a year — always the same reliable cleaner.", name: 'Patricia J.', neighborhood: 'Central Beach' },
    { text: "Our Grand Harbor home needed a deep clean before a family visit and they went above and beyond.", name: 'Bill S.', neighborhood: 'Grand Harbor' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Vero Beach?', answer: 'Vero Beach Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Vero Beach?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Vero Beach Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, seasonal arrival-prep and closing cleans, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Do you clean seasonal homes that sit empty for months?', answer: "Yes — this is one of our specialties in Vero Beach. We time arrival-prep cleanings to when you return for the season and closing cleans before you head north." },
    { question: 'Can you clean homes in golf and marina communities like Grand Harbor or The Moorings?', answer: "Absolutely. We're familiar with the presentation standards these communities expect." },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for closing on a barrier-island home or ending a lease downtown." },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or gate code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings, and earlier around the seasonal turnover months.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Vero Beach Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of Vero Beach do you serve?', answer: 'Riomar, Central Beach, Old Town / Downtown Vero, Grand Harbor, The Moorings, Vero Isles, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Vero Beach.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Vero Beach Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Vero Beach Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a condo or smaller unit?', answer: 'Yes, our 2-hour minimum is usually perfect for a smaller unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Vero Beach Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'Do you clean barrier-island and waterfront homes?', answer: 'Yes, we regularly service waterfront properties across Riomar and Vero Isles.' },
    { question: 'What if my community requires vendor registration?', answer: 'Send us your requirements ahead of time and we\'ll get registered.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Is Vero Beach Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger estates?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Vero Beach Maid serve both condos and houses?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Vero Beach Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
    { question: 'Can you schedule around when I fly in for the season?', answer: 'Yes — just give us your arrival date and we\'ll have your home ready before you land.' },
  ],
}
