import type { EmdMicrositeConfig } from './types'

export const westPalmBeachMaidConfig: EmdMicrositeConfig = {
  domain: 'westpalmbeachmaid.com',
  brandName: 'West Palm Beach Maid',
  city: 'West Palm Beach',
  regionLabel: 'West Palm Beach, FL',
  metaTitle: 'West Palm Beach Maid and Cleaning Service',
  metaDescription: 'West Palm Beach Maid — house cleaning across Downtown, El Cid & Flamingo Park from $49/hr. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '26.7153', lng: '-80.0534' },
  introParagraphs: [
    "West Palm Beach Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across downtown high-rises, historic bungalow neighborhoods, and the waterfront estates that make West Palm Beach one of Florida's most desirable places to live. If you live in West Palm Beach, you already know how quickly humidity, dust, and the pace of city life can wear down a home. We built West Palm Beach Maid to answer exactly that problem: a local cleaning service that understands the city and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. West Palm Beach Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around West Palm Beach.",
    "Whether you need a one-time deep clean before hosting guests downtown, a recurring weekly service for a busy El Cid household, or a fast turnover clean for a South End rental between guests, West Palm Beach Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from downtown condo towers to historic Flamingo Park bungalows, and that range of experience shapes how we train every cleaner. West Palm Beach Maid was built around the reality that a mainland Florida cleaning routine has to account for both dense urban living and classic Florida homes — often on the very same street.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. Over the years, that idea grew into a company that has now cleaned over 25,000 homes across the state — from Orlando to Tampa, Jacksonville to West Palm Beach.",
    "West Palm Beach Maid exists because this city is its own world — a mix of downtown high-rises, historic districts, and waterfront estates that don't all clean the same way. So rather than force West Palm Beach into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this city.",
    "Every cleaner who works under the West Palm Beach Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews. When you book with us, you're getting a cleaner who has been screened, trained, and held accountable.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in West Palm Beach, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in West Palm Beach as in Minneapolis. West Palm Beach Maid does not. We built our service around this city's real mix of high-rise condos, historic homes, and waterfront estates, training our cleaners on exactly what each type of home needs.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote' that requires an in-home estimate before you even know what you're paying. West Palm Beach Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier — so you know the cost before you ever book.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your West Palm Beach home on recurring visits.",
  ],
  challenges: [
    { title: 'Humidity & Mold Prevention', body: "South Florida humidity creates ideal conditions for mildew and mold, especially in bathrooms, closets, and AC vents. We pay close attention to these high-risk zones on every visit." },
    { title: 'Historic Home Care', body: "West Palm Beach's historic districts like Flamingo Park and El Cid are full of homes with original hardwood floors, older fixtures, and delicate architectural details. We train our cleaners to handle these surfaces with extra care." },
    { title: 'High-Rise & Building Logistics', body: "Many of our downtown clients live in buildings with front-desk check-in and freight-elevator scheduling. Our cleaners arrive prepared and coordinate arrival windows around your building's rules." },
    { title: 'Sun & UV Fading', body: "Constant Florida sun fades fabrics, wood finishes, and flooring faster than in most climates. We use gentle, UV-safe cleaning products on sun-exposed surfaces." },
    { title: 'Hurricane Season Readiness', body: "Storm season means shutter dust and post-storm cleanup on top of your regular routine. We offer flexible scheduling around storm prep and recovery." },
    { title: 'Fast Turnover for Rentals & Guests', body: "Between Airbnb bookings and seasonal residents, West Palm Beach homes turn over fast. Our scheduling supports same-day and next-day turnovers." },
  ],
  neighborhoods: [
    { name: 'Downtown / CityPlace', blurb: "West Palm Beach's downtown core and the CityPlace district are full of high-rise condos and modern apartments. We regularly coordinate with front-desk staff and building management for cleanings here." },
    { name: 'El Cid', blurb: "This historic waterfront neighborhood of Mediterranean Revival homes calls for careful, detail-first cleaning that respects original architectural features while keeping these beautiful homes spotless." },
    { name: 'Flamingo Park', blurb: "One of the city's most beloved historic districts, Flamingo Park's bungalows and cottage-style homes are a regular stop for our recurring weekly and bi-weekly clients." },
    { name: 'Southend / SoSo', blurb: "This walkable, up-and-coming district near the Intracoastal has grown fast with young professionals and new construction, and we've grown our recurring client base right along with it." },
    { name: 'Northwood', blurb: "Northwood's historic shopping village and surrounding residential streets are home to many longtime clients who trust us for consistent, dependable weekly service." },
    { name: 'Prospect Park & Southland Park', blurb: "These quieter residential neighborhoods south of downtown are full of single-family homes where bi-weekly and monthly cleaning plans are especially popular." },
  ],
  pricingExplainer: [
    "West Palm Beach Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own cleaning products and equipment, $59/hour when we bring everything ourselves, or $89/hour for same-day and emergency service.",
    "What determines how many hours your West Palm Beach home needs? Mainly size and condition. A tidy downtown condo getting a routine touch-up might only need the 2-hour minimum, while a multi-bedroom El Cid estate getting its first deep clean could run 5 hours or more.",
    "Recurring service is where West Palm Beach Maid saves you the most. Book weekly and save 20% off your rate; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of West Palm Beach.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off. Tell us your home size, the service you want, and your building's access requirements if applicable.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back to make it right at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among West Palm Beach condo residents and families. Weekly service keeps dust and humidity buildup from ever getting ahead of you, and earns the deepest recurring discount — 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup before it becomes a bigger job, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes or condos that get a mid-month tidy-up from the owner. Monthly service goes deeper than a quick touch-up, and also carries the 10% recurring discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "We live downtown and the front-desk coordination alone can be a headache with other services. West Palm Beach Maid handled our building's check-in process without us lifting a finger.", name: 'Diane K.', neighborhood: 'Downtown' },
    { text: "Booked a deep clean before hosting family and they went above and beyond — every baseboard, every window sill. Our El Cid home hasn't looked this good in years.", name: 'Roberto M.', neighborhood: 'El Cid' },
    { text: "They've handled our Flamingo Park bungalow for over a year now and always treat the original hardwood floors with real care.", name: 'Susan T.', neighborhood: 'Flamingo Park' },
    { text: "We manage a couple of rentals near SoSo and needed a cleaner who could turn units around fast. West Palm Beach Maid has never made us miss a check-in.", name: 'James P.', neighborhood: 'Southend' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in West Palm Beach?', answer: 'West Palm Beach Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day and emergency service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate. That keeps pricing fair for everyone, no matter your home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — West Palm Beach Maid has a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in West Palm Beach?', answer: "Text or call us at (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour, and we dispatch a professional cleaner to your door within hours.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but it is always appreciated.' },
    { question: 'What types of cleaning does West Palm Beach Maid offer?', answer: 'We offer regular home cleaning, deep cleaning, move-in/move-out cleaning, post-construction cleanup, weekly/bi-weekly/monthly recurring service, Airbnb turnover cleaning, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'A regular cleaning covers dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying of every room.' },
    { question: 'What is included in a deep cleaning?', answer: 'Our deep clean covers everything in a regular clean, plus inside your oven and refrigerator, baseboards, light fixtures, window sills and tracks, and detailed scrubbing of every surface.' },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes. Our move-in/move-out service is perfect for closing on a downtown condo or ending a lease. We clean every surface, inside cabinets, appliances, and closets." },
    { question: 'Can you clean high-rise condos with front-desk security?', answer: "Absolutely. Most of our downtown clients live in buildings with front-desk check-in. Just let us know your building's procedures when you book." },
    { question: 'Do you clean Airbnb and short-term rentals?', answer: 'Yes. We provide fast-turnaround cleaning between guests — fresh linens, restocked amenities, and a spotless, photo-ready space.' },
    { question: 'Can I customize what gets cleaned?', answer: "Of course. Just tell us your priorities when you book and we'll tailor the visit accordingly." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'We offer both options. At $49/hour, you provide supplies. At $59/hour, we bring all professional-grade supplies and equipment.' },
    { question: 'What cleaning products do you use?', answer: 'We use professional-grade, effective cleaning products. If you prefer eco-friendly or specific brands, just let us know.' },
    { question: 'Can I request eco-friendly or green products?', answer: 'Yes. We are happy to use eco-friendly, non-toxic, or hypoallergenic products — just mention your preference when booking.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes. Every West Palm Beach Maid cleaner is fully background-checked, licensed, and insured, and we carry general liability insurance up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance for exactly this reason. If anything is ever damaged, contact us immediately and we will make it right.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes. We do our best to match recurring clients with the same cleaner on every visit." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's entirely up to you. Many clients leave a key, share a code, or coordinate through their building's front desk." },
    { question: 'How far in advance should I book?', answer: 'We recommend booking 2-3 days in advance for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'We ask for at least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is West Palm Beach Maid available?', answer: 'Our office is open Monday through Saturday, 7am-7pm. Our booking line is available 24/7 — call or text (954) 710-3636 anytime.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes. We offer weekly, bi-weekly, and monthly recurring cleaning, and recurring clients receive priority scheduling.' },
    { question: 'What areas of West Palm Beach do you serve?', answer: 'West Palm Beach Maid serves the entire city — Downtown, CityPlace, El Cid, Flamingo Park, Southend/SoSo, Northwood, Prospect Park, and Southland Park.' },
    { question: 'Is there a travel fee outside downtown?', answer: 'No travel fees anywhere in West Palm Beach.' },
    { question: 'Do you have reviews I can read?', answer: 'Yes. West Palm Beach Maid carries The Florida Maid\'s 5.0-star Google rating.' },
    { question: 'How long has West Palm Beach Maid been serving the area?', answer: 'West Palm Beach Maid is a dedicated local brand of The Florida Maid, which has been cleaning Florida homes since 2018 and has served over 25,000 homes statewide.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely — we love pets! Just let us know so we can plan accordingly.' },
    { question: 'Can you clean a studio or small condo?', answer: 'Of course. Studios and one-bedroom condos are extremely common downtown, and our 2-hour minimum is usually the perfect fit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes. We offer pre-event and post-event cleaning.' },
    { question: 'How do I contact West Palm Beach Maid?', answer: 'Text or call us at (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do you clean historic homes in El Cid or Flamingo Park?', answer: "Yes. Our cleaners are experienced with the unique features of historic West Palm Beach homes — original hardwood floors, crown molding, and older fixtures." },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes. Many of our West Palm Beach Maid cleaners are bilingual in English and Spanish.' },
    { question: 'Can I get a quote before booking?', answer: "Yes. Text or call (954) 710-3636 with your home size and cleaning needs and we'll give you a straightforward hourly estimate." },
    { question: 'Do you offer discounts for multiple units, like an investor with several rentals?', answer: "Yes. Contact us directly to set up a custom recurring schedule and portfolio pricing." },
    { question: 'What if my building requires vendor registration?', answer: "Send us your building's requirements when you book and we'll get our cleaner properly registered before your appointment." },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'If you are not satisfied with any part of your cleaning, contact us within 24 hours and we will send someone back to fix it at no additional charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes. Just text us with a few days notice and we will do our best to accommodate a new day or time.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes — this is our move-in/move-out service, cleaning the unit top to bottom for the next tenant.' },
    { question: 'Is Downtown West Palm Beach a big part of your service area?', answer: 'Yes, Downtown and CityPlace are among our busiest zones, with many high-rise condo clients on recurring plans.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes. Just flag any sensitive equipment you want left untouched, and we will clean around it carefully.' },
    { question: 'Do you offer post-party or post-event cleanup?', answer: 'Yes, this is one of our most requested one-time services, especially around Flagler Drive events and downtown gatherings.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Standard cleaning does not include exterior window washing, wall washing, or carpet shampooing. These can often be arranged as add-ons.' },
    { question: 'Do you clean vacation homes that sit empty most of the year?', answer: 'Yes. We offer periodic upkeep visits for seasonal residents, with arrival-prep cleanings scheduled before you visit.' },
    { question: 'Is West Palm Beach Maid available on holidays?', answer: 'Regular hours are Monday-Saturday, 7am-7pm. Text (954) 710-3636 to check holiday availability.' },
    { question: 'Can I request a walkthrough before the cleaner starts?', answer: 'For first-time appointments, your cleaner is happy to do a quick walkthrough with you if you are home.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean model units and staged listings for agents ahead of showings.' },
    { question: 'What forms of ID does my cleaner carry?', answer: 'Our cleaners carry government-issued photo ID and can provide identification if your building requires it.' },
    { question: 'Do you offer subscription billing for recurring clients?', answer: 'Yes — recurring clients can set up automatic billing so you never have to manually pay after each visit.' },
    { question: 'Can Weight Palm Beach Maid clean a unit with a lockbox?', answer: 'Yes, lockbox access works well for vacant listings. Just provide the code and any showing-schedule conflicts.' },
    { question: 'Do you offer team cleanings for larger estates?', answer: 'Yes. For larger properties, we can send a multi-person team to complete a thorough deep clean faster.' },
    { question: 'What happens if weather delays my appointment?', answer: 'Severe weather is the one situation where we will proactively reach out to reschedule at no penalty to you.' },
    { question: 'Do you clean homes near the Intracoastal Waterway?', answer: 'Yes. Waterfront homes get the same thorough treatment, with extra attention to humidity-prone areas.' },
    { question: 'Can I leave standing instructions for every visit?', answer: 'Yes. Standing instructions can be saved to your recurring profile so every cleaner follows them automatically.' },
    { question: 'Does West Palm Beach Maid serve both condos and single-family homes?', answer: 'Yes. We regularly clean both downtown condo towers and single-family homes throughout the historic districts.' },
    { question: 'How does West Palm Beach Maid handle multi-story homes?', answer: 'Multi-story homes typically take longer than a single-level unit of the same size. Let us know when booking so we can estimate time accurately.' },
    { question: 'What should I do if I need to cancel a recurring plan?', answer: 'Just text or call us — canceling a recurring plan is simple and penalty-free with the standard 24-hour notice.' },
  ],
}
