import type { EmdMicrositeConfig } from './types'

export const winterParkMaidConfig: EmdMicrositeConfig = {
  domain: 'winterparkmaid.com',
  brandName: 'Winter Park Maid',
  city: 'Winter Park',
  regionLabel: 'Winter Park, FL',
  metaTitle: 'Winter Park Maid and Cleaning Service',
  metaDescription: 'Winter Park Maid — house cleaning across Park Avenue, Interlachen & Comstock Park from $49/hr. Licensed, insured, background-checked. Call/text (954) 710-3636 — 24/7 booking.',
  geo: { lat: '28.5999', lng: '-81.3392' },
  introParagraphs: [
    "Winter Park Maid (A Florida Maid Services Company) is the trusted name in professional house cleaning across one of Central Florida's most polished, historic communities — a lakefront college town built around Rollins College, brick-paved streets, and a chain of spring-fed lakes. If you live in Winter Park, you know how much this community's presentation standards and mature oak canopy shape how a home should look. We built Winter Park Maid to answer exactly that problem: a local cleaning service that understands this community's expectations and shows up on time, every time.",
    "We're not a national franchise cold-calling from a call center in another state. Winter Park Maid is a dedicated local brand of The Florida Maid, a Florida-founded cleaning company that has served over 25,000 homes statewide since 2018. Every cleaner who walks through your door has been background-checked, trained to our standards, and held to the same insurance and accountability requirements as every other Florida Maid technician — but the focus, pricing, and scheduling here are built specifically around Winter Park.",
    "Whether you need a one-time deep clean before hosting guests near Park Avenue, a recurring weekly service for a busy Interlachen household, or a fast turnover clean for a Comstock Park rental between tenants, Winter Park Maid has a plan that fits. No contracts, no hidden fees, no surprises — just flat hourly pricing starting at $49/hr and a satisfaction guarantee on every visit.",
    "Our team has cleaned everything from historic lakefront estates to condos steps from Park Avenue, and that range of experience shapes how we train every cleaner. Winter Park Maid was built around the reality that this community's high standards demand real attention to detail.",
  ],
  ourStory: [
    "The Florida Maid started in 2018 with a simple idea: Florida homes deserve a cleaning company built around Florida conditions, not a national franchise applying the same playbook everywhere. That idea grew into a company that has now cleaned over 25,000 homes across the state.",
    "Winter Park Maid exists because this historic lakefront college town's mature oak canopy, brick-paved streets, and high presentation standards make it its own world. So rather than force Winter Park into a one-size-fits-all mold, we built a dedicated local brand around it — same trusted company, same insurance, same background-checked cleaners, but a focus tuned specifically to this city.",
    "Every cleaner who works under the Winter Park Maid name goes through the same vetting process as every other Florida Maid technician: background checks, in-person training, and ongoing quality reviews.",
    "We're proud of the 5.0-star Google rating that follows The Florida Maid name across every city we serve, and we intend to earn that same trust in Winter Park, one cleaning at a time.",
  ],
  differentiation: [
    "National cleaning franchises operate the same playbook everywhere — the same checklist in Winter Park as in Minneapolis. Winter Park Maid does not. We built our service around this community's historic lakefront estates, mature tree canopy, and refined presentation expectations.",
    "Franchise pricing also tends to hide the real cost behind a 'custom quote.' Winter Park Maid publishes flat hourly pricing up front — $49, $59, or $89 per hour depending on the tier.",
    "And unlike a franchise where you might get a different cleaner from a rotating pool every time, we prioritize sending the same cleaner back to your Winter Park home on recurring visits.",
  ],
  challenges: [
    { title: 'Historic Home Care', body: "Interlachen and other historic Winter Park neighborhoods have original hardwood floors and details that need gentler products than a newer build. We adjust our approach accordingly." },
    { title: 'Oak Canopy Debris', body: "Winter Park's famous mature oak canopy drops leaves and debris year-round, tracking indoors constantly. We use techniques suited to lifting this kind of organic debris without smearing it." },
    { title: 'Lakefront Humidity & Mold Prevention', body: "Winter Park's chain of lakes keeps humidity high near the water. We pay close attention to bathrooms and closets, the highest-risk zones for mildew." },
    { title: 'High Presentation Standards', body: "This community expects a level of presentation that goes beyond a standard clean. We train our cleaners to meet that standard on every visit." },
    { title: 'Large Estate Homes', body: "Many Winter Park properties are large estate homes that take longer to clean thoroughly. We staff multi-person teams for these properties as needed." },
    { title: 'Hurricane Season Readiness', body: "Storm season means shutter dust and post-storm cleanup. We offer flexible scheduling around storm prep and recovery." },
  ],
  neighborhoods: [
    { name: 'Park Avenue', blurb: "Close to Winter Park's iconic shopping and dining corridor, our clients here rely on us for consistent, detail-first cleaning." },
    { name: 'Interlachen', blurb: "This historic lakefront neighborhood is home to many of our longest-running recurring clients, who value a consistent cleaner they can trust." },
    { name: 'Comstock Park', blurb: "This established residential area trusts Winter Park Maid for everything from routine upkeep to deep cleans." },
    { name: 'Lake Sue', blurb: "This lakefront area's homes call for extra attention to humidity and mold-prone zones." },
    { name: 'Windsong', blurb: "This established neighborhood is a favorite for our weekly and bi-weekly recurring clients." },
    { name: 'Virginia Heights', blurb: "This residential section is a regular stop for our bi-weekly and monthly cleaning plans." },
  ],
  pricingExplainer: [
    "Winter Park Maid keeps pricing simple and hourly, not flat-rate. Every visit falls into one of three tiers: $49/hour when you supply your own products, $59/hour when we bring everything, or $89/hour for same-day service.",
    "What determines how many hours your home needs? Mainly size and condition. A tidy Park Avenue condo might only need the 2-hour minimum, while an Interlachen lakefront estate getting its first deep clean could run 5 hours or more.",
    "Recurring service is where Winter Park Maid saves you the most. Book weekly and save 20%; book bi-weekly or monthly and save 10%.",
    "One thing we never do: charge a mandatory travel fee. Your hourly rate is the same across all of Winter Park.",
  ],
  firstVisitSteps: [
    "Book by texting or calling (954) 710-3636, or use our online self-booking form for $20 off.",
    "We confirm your appointment window by text, usually within 15 minutes.",
    "Your cleaner arrives within the scheduled window and gets to work using the checklist for your selected service tier.",
    "We do a final walkthrough before wrapping up. If anything doesn't meet your expectations, tell us within 24 hours and we'll send someone back at no extra charge.",
  ],
  frequencyGuide: [
    { frequency: 'Weekly', body: "The most popular plan among Winter Park full-time residents. Weekly service keeps clutter and dust from getting ahead of you, earning 20% off." },
    { frequency: 'Bi-Weekly', body: "A strong middle ground for smaller households. Bi-weekly visits still catch most buildup, and you save 10%." },
    { frequency: 'Monthly', body: "Best suited to light-use homes. Monthly service goes deeper than a quick touch-up, and also carries the 10% discount." },
    { frequency: 'One-Time', body: "Perfect for a single deep clean, move-in/move-out job, or pre-event reset. No commitment, no recurring charge." },
  ],
  testimonials: [
    { text: "Our Interlachen home has original wood floors and they treated them with real care. Not every cleaning company would bother.", name: 'Margaret S.', neighborhood: 'Interlachen' },
    { text: "We live near Park Avenue and appreciate how consistent and thorough they are every time.", name: 'Nathaniel P.', neighborhood: 'Park Avenue' },
    { text: "They've handled our Comstock Park home weekly for over a year — always the same reliable cleaner.", name: 'Dana W.', neighborhood: 'Comstock Park' },
    { text: "Our lakefront home has humidity issues and they always know exactly how to handle it.", name: 'Robert H.', neighborhood: 'Lake Sue' },
  ],
  faqs: [
    { question: 'How much does house cleaning cost in Winter Park?', answer: 'Winter Park Maid pricing starts at $49/hour when you provide your own supplies, or $59/hour when we bring everything. Same-day service is $89/hour.' },
    { question: 'Do you charge by the hour or a flat rate?', answer: "We charge by the hour, not a flat rate, so pricing stays fair for every home size." },
    { question: 'Is there a minimum number of hours?', answer: 'Yes — a 2-hour minimum on all bookings.' },
    { question: 'How do I book a cleaning in Winter Park?', answer: "Text or call (954) 710-3636, or use our online self-booking form for $20 off your first cleaning." },
    { question: 'Do you offer same-day cleaning?', answer: 'Yes. Same-day and emergency service is available at $89/hour.' },
    { question: 'What payment methods do you accept?', answer: 'We accept credit cards, debit cards, Zelle (hi@thefloridamaid.com), Venmo, Apple Pay, and cash.' },
    { question: 'Do I need to tip my cleaner?', answer: 'Tipping is never required, but always appreciated.' },
    { question: 'What types of cleaning does Winter Park Maid offer?', answer: 'Regular cleaning, deep cleaning, move-in/move-out, post-construction cleanup, weekly/bi-weekly/monthly recurring, same-day cleaning, and office cleaning.' },
    { question: 'What is included in a regular cleaning?', answer: 'Dusting, vacuuming, mopping, full kitchen and bathroom cleaning, bed making, and general tidying.' },
    { question: 'What is included in a deep cleaning?', answer: 'Everything in a regular clean plus inside your oven and fridge, baseboards, light fixtures, window tracks, and detailed scrubbing.' },
    { question: 'Can you clean historic homes in Interlachen?', answer: "Absolutely. We use gentler products suited to original hardwood floors and vintage fixtures." },
    { question: 'Do you offer move-in/move-out cleaning?', answer: "Yes — perfect for closing on a lakefront estate or ending a lease near Park Avenue." },
    { question: 'Can I customize what gets cleaned?', answer: "Of course — just tell us your priorities when booking." },
    { question: 'Do you bring your own cleaning supplies?', answer: 'At $49/hour you provide supplies; at $59/hour we bring everything.' },
    { question: 'What cleaning products do you use?', answer: 'Professional-grade products, with eco-friendly options on request.' },
    { question: 'Are your cleaners background-checked and insured?', answer: 'Yes, fully background-checked, licensed, and insured up to $1,000,000.' },
    { question: 'What if something is damaged during my cleaning?', answer: 'We carry full liability insurance and will make it right immediately.' },
    { question: 'Can I request the same cleaner every time?', answer: "Yes, we prioritize consistency for recurring clients." },
    { question: 'Will I need to be home during the cleaning?', answer: "It's up to you — many clients leave a key or gate code." },
    { question: 'How far in advance should I book?', answer: '2-3 days in advance is recommended for regular cleanings.' },
    { question: 'What is your cancellation policy?', answer: 'At least 24 hours notice for cancellations or rescheduling.' },
    { question: 'What days and hours is Winter Park Maid available?', answer: 'Office hours Monday-Saturday 7am-7pm; booking line available 24/7 at (954) 710-3636.' },
    { question: 'Do you offer recurring cleaning schedules?', answer: 'Yes — weekly, bi-weekly, and monthly, with priority scheduling for recurring clients.' },
    { question: 'What areas of Winter Park do you serve?', answer: 'Park Avenue, Interlachen, Comstock Park, Lake Sue, Windsong, Virginia Heights, and surrounding neighborhoods.' },
    { question: 'Is there a travel fee?', answer: 'No travel fees anywhere in Winter Park.' },
    { question: 'Do you have reviews I can read?', answer: "Yes, Winter Park Maid carries The Florida Maid's 5.0-star Google rating." },
    { question: 'How long has Winter Park Maid been serving the area?', answer: 'As a Florida Maid brand, we\'ve been cleaning Florida homes since 2018.' },
    { question: 'Can you clean if I have pets?', answer: 'Absolutely, just let us know so we can plan accordingly.' },
    { question: 'Can you clean a condo or smaller unit?', answer: 'Yes, our 2-hour minimum is usually perfect for a smaller unit.' },
    { question: 'Do you clean for parties or events?', answer: 'Yes, pre-event and post-event cleaning available.' },
    { question: 'How do I contact Winter Park Maid?', answer: 'Text or call (954) 710-3636, or email hi@thefloridamaid.com.' },
    { question: 'Do your cleaners speak Spanish?', answer: 'Yes, many of our cleaners are bilingual.' },
    { question: 'Can I get a quote before booking?', answer: 'Yes, text us your home size and needs for a straightforward estimate.' },
    { question: 'Do you clean lakefront homes?', answer: 'Yes, we regularly service lakefront properties around Winter Park\'s chain of lakes.' },
    { question: 'What if my building requires vendor registration?', answer: 'Send us your requirements ahead of time and we\'ll get registered.' },
    { question: 'Do you offer a satisfaction guarantee?', answer: 'Yes — contact us within 24 hours and we\'ll make it right at no extra charge.' },
    { question: 'Can I change my recurring cleaning day?', answer: 'Yes, just text us with a few days notice.' },
    { question: 'Do you clean rental properties between tenants?', answer: 'Yes, that\'s our move-in/move-out service.' },
    { question: 'Can you clean around a home office setup?', answer: 'Yes, just flag sensitive equipment to avoid.' },
    { question: 'What is not included in a standard cleaning?', answer: 'Exterior windows, wall washing, and carpet shampooing — available as add-ons.' },
    { question: 'Is Winter Park Maid available on holidays?', answer: 'Text us to check holiday availability.' },
    { question: 'Do you clean model units for real estate agents?', answer: 'Yes, we regularly clean staged listings.' },
    { question: 'Do you offer subscription billing?', answer: 'Yes, recurring clients can set up automatic billing.' },
    { question: 'Do you offer team cleanings for larger estates?', answer: 'Yes, for larger properties we send a multi-person team.' },
    { question: 'What happens if weather delays my appointment?', answer: 'We\'ll proactively reach out to reschedule at no penalty.' },
    { question: 'Does Winter Park Maid serve both condos and estate homes?', answer: 'Yes, both are core to our service area.' },
    { question: 'How does Winter Park Maid handle multi-story homes?', answer: 'Multi-story homes take longer — let us know when booking.' },
    { question: 'What if I need to cancel a recurring plan?', answer: 'Simple and penalty-free with 24-hour notice.' },
  ],
}
