// Programmatic SEO combo data: [industry]-crm-[city]-[state]
// Generates 20,400 unique landing pages (51 industries x 400 metros)

export interface ComboIndustry {
  name: string;
  slug: string;
  description: string;
}

export interface ComboMetro {
  city: string;
  state: string;
  stateAbbr: string;
  slug: string;
  shortSlug: string;
}

export interface Combo {
  industry: ComboIndustry;
  metro: ComboMetro;
  slug: string;
}

export const industries: ComboIndustry[] = [
  { name: "Cleaning Services", slug: "cleaning-services", description: "Full Loop CRM helps cleaning services manage recurring clients, dispatch crews, and fill every open slot with AI-driven lead generation." },
  { name: "Carpet Cleaning", slug: "carpet-cleaning", description: "Full Loop CRM gives carpet cleaning businesses the tools to book more jobs, route technicians efficiently, and automate follow-ups for repeat service." },
  { name: "Window Cleaning", slug: "window-cleaning", description: "Full Loop CRM helps window cleaning companies schedule recurring routes, convert online leads instantly, and manage seasonal demand spikes." },
  { name: "Pressure Washing", slug: "pressure-washing", description: "Full Loop CRM empowers pressure washing operators to fill their calendar, track jobs with GPS, and build a steady pipeline of residential and commercial clients." },
  { name: "Landscaping", slug: "landscaping", description: "Full Loop CRM helps landscaping companies manage seasonal crews, upsell design services, and keep every property on a recurring maintenance schedule." },
  { name: "Lawn Care", slug: "lawn-care", description: "Full Loop CRM automates lawn care route scheduling, client communication, and rebooking so you spend less time in the office and more time on the route." },
  { name: "Tree Service", slug: "tree-service", description: "Full Loop CRM helps tree service companies capture emergency leads 24/7, schedule estimates, and manage crew dispatch across multiple job sites." },
  { name: "Handyman Services", slug: "handyman-services", description: "Full Loop CRM gives handyman businesses a single platform to manage diverse job types, send quotes, and convert one-time callers into repeat clients." },
  { name: "Pest Control", slug: "pest-control", description: "Full Loop CRM helps pest control companies manage recurring treatment schedules, automate renewal reminders, and dominate local search results." },
  { name: "HVAC", slug: "hvac", description: "Full Loop CRM helps HVAC companies capture seasonal demand, manage maintenance agreements, and dispatch technicians with GPS-tracked efficiency." },
  { name: "Plumbing", slug: "plumbing", description: "Full Loop CRM gives plumbing businesses the tools to capture emergency calls, schedule service appointments, and build long-term client relationships." },
  { name: "Electrical", slug: "electrical", description: "Full Loop CRM helps electrical contractors manage leads from homeowners and builders, schedule inspections, and grow through referral automation." },
  { name: "Painting", slug: "painting", description: "Full Loop CRM helps painting companies manage estimate requests, schedule crews across multiple projects, and win more bids with faster follow-up." },
  { name: "Junk Removal", slug: "junk-removal", description: "Full Loop CRM helps junk removal businesses fill trucks daily, optimize routes, and convert website visitors into same-day bookings." },
  { name: "Pool Cleaning", slug: "pool-cleaning", description: "Full Loop CRM helps pool cleaning businesses manage recurring service routes, track chemical logs, and automate seasonal open/close scheduling." },
  { name: "Roofing", slug: "roofing", description: "Full Loop CRM helps roofing companies capture storm-season leads, manage multi-day projects, and automate insurance claim follow-ups." },
  { name: "Garage Door Repair", slug: "garage-door-repair", description: "Full Loop CRM helps garage door repair businesses respond to emergency calls instantly, schedule installations, and drive repeat service revenue." },
  { name: "Appliance Repair", slug: "appliance-repair", description: "Full Loop CRM gives appliance repair technicians a system to manage parts ordering, schedule callbacks, and build a loyal client base." },
  { name: "Locksmith", slug: "locksmith", description: "Full Loop CRM helps locksmith businesses capture emergency lockout calls 24/7, dispatch the nearest technician, and track every job with GPS." },
  { name: "Flooring Installation", slug: "flooring-installation", description: "Full Loop CRM helps flooring installers manage multi-day projects, send automated updates to homeowners, and generate referral business." },
  { name: "Fencing", slug: "fencing", description: "Full Loop CRM helps fencing companies manage estimates, schedule installation crews, and follow up with prospects who requested quotes." },
  { name: "Gutter Cleaning", slug: "gutter-cleaning", description: "Full Loop CRM helps gutter cleaning businesses build recurring seasonal routes, automate reminders, and maximize revenue per stop." },
  { name: "Chimney Sweep", slug: "chimney-sweep", description: "Full Loop CRM helps chimney sweep businesses manage seasonal inspection schedules, automate rebooking, and grow through local search dominance." },
  { name: "Drywall Repair", slug: "drywall-repair", description: "Full Loop CRM helps drywall repair contractors manage estimate requests, schedule patch jobs, and build relationships with property managers and realtors." },
  { name: "Concrete & Masonry", slug: "concrete-masonry", description: "Full Loop CRM helps concrete and masonry contractors track multi-phase projects, manage subcontractor schedules, and win more bids." },
  { name: "Deck Building", slug: "deck-building", description: "Full Loop CRM helps deck builders manage design consultations, schedule multi-day builds, and generate referral leads from completed projects." },
  { name: "Home Inspection", slug: "home-inspection", description: "Full Loop CRM helps home inspectors manage agent relationships, schedule inspections around closings, and automate report delivery." },
  { name: "Mold Remediation", slug: "mold-remediation", description: "Full Loop CRM helps mold remediation companies respond to urgent inquiries, manage testing and remediation schedules, and follow up on insurance claims." },
  { name: "Water Damage Restoration", slug: "water-damage-restoration", description: "Full Loop CRM helps water damage restoration companies capture emergency leads around the clock, dispatch crews fast, and manage insurance documentation." },
  { name: "Fire Damage Restoration", slug: "fire-damage-restoration", description: "Full Loop CRM helps fire damage restoration companies manage complex multi-phase projects, coordinate with adjusters, and keep clients informed." },
  { name: "Septic Services", slug: "septic-services", description: "Full Loop CRM helps septic service companies manage pumping schedules, automate maintenance reminders, and track every tank in their territory." },
  { name: "Irrigation", slug: "irrigation", description: "Full Loop CRM helps irrigation companies manage seasonal startups and winterizations, schedule installations, and automate service reminders." },
  { name: "Snow Removal", slug: "snow-removal", description: "Full Loop CRM helps snow removal companies manage contract clients, dispatch plows based on GPS, and automate storm-triggered scheduling." },
  { name: "Power Washing", slug: "power-washing", description: "Full Loop CRM helps power washing businesses book more residential and commercial jobs, build recurring schedules, and dominate local search." },
  { name: "House Cleaning", slug: "house-cleaning", description: "Full Loop CRM helps house cleaning businesses manage recurring schedules, dispatch teams, and convert every inquiry into a booked appointment." },
  { name: "Move-In/Move-Out Cleaning", slug: "move-in-move-out-cleaning", description: "Full Loop CRM helps move-in/move-out cleaning companies build referral networks with property managers and realtors, and automate turnover scheduling." },
  { name: "Post-Construction Cleaning", slug: "post-construction-cleaning", description: "Full Loop CRM helps post-construction cleaning crews manage builder relationships, schedule final cleans, and track multi-site projects." },
  { name: "Air Duct Cleaning", slug: "air-duct-cleaning", description: "Full Loop CRM helps air duct cleaning businesses generate leads, schedule whole-home services, and automate follow-up for recurring maintenance." },
  { name: "Dryer Vent Cleaning", slug: "dryer-vent-cleaning", description: "Full Loop CRM helps dryer vent cleaning businesses book recurring annual services, automate safety reminders, and grow through local SEO." },
  { name: "Solar Panel Cleaning", slug: "solar-panel-cleaning", description: "Full Loop CRM helps solar panel cleaning companies manage route-based scheduling, automate rebooking, and prove ROI to homeowners." },
  { name: "Upholstery Cleaning", slug: "upholstery-cleaning", description: "Full Loop CRM helps upholstery cleaning businesses manage on-site appointments, upsell additional services, and automate review requests." },
  { name: "Pet Waste Removal", slug: "pet-waste-removal", description: "Full Loop CRM helps pet waste removal businesses manage weekly route schedules, automate billing, and grow through neighborhood referrals." },
  { name: "Mobile Car Detailing", slug: "mobile-car-detailing", description: "Full Loop CRM helps mobile car detailing businesses manage on-location appointments, optimize daily routes, and build a loyal repeat client base." },
  { name: "Mobile Pet Grooming", slug: "mobile-pet-grooming", description: "Full Loop CRM helps mobile pet grooming businesses manage appointment schedules, track pet profiles, and automate rebooking reminders." },
  { name: "Mobile Salon Services", slug: "mobile-salon-services", description: "Full Loop CRM helps mobile salon professionals manage client schedules, optimize travel routes, and build a loyal client book." },
  { name: "Hauling Services", slug: "hauling-services", description: "Full Loop CRM helps hauling companies manage dispatch, fill trucks, and convert one-time jobs into ongoing commercial contracts." },
  { name: "Demolition", slug: "demolition", description: "Full Loop CRM helps demolition contractors manage permits, schedule multi-day teardowns, and build relationships with general contractors." },
  { name: "Paving", slug: "paving", description: "Full Loop CRM helps paving companies manage seasonal project pipelines, schedule crews, and automate follow-up on estimates." },
  { name: "Stucco Repair", slug: "stucco-repair", description: "Full Loop CRM helps stucco repair contractors manage estimate requests, schedule repair crews, and generate repeat business from property managers." },
  { name: "Siding Installation", slug: "siding-installation", description: "Full Loop CRM helps siding installation companies manage project timelines, coordinate material deliveries, and convert storm-damage leads." },
  { name: "Insulation", slug: "insulation", description: "Full Loop CRM helps insulation contractors manage energy audit leads, schedule installation crews, and build referral networks with HVAC companies." },
];

export const metros: ComboMetro[] = [
  { city: "New York", state: "New York", stateAbbr: "NY", slug: "new-york-ny", shortSlug: "nyc" },
  { city: "Los Angeles", state: "California", stateAbbr: "CA", slug: "los-angeles-ca", shortSlug: "la" },
  { city: "Chicago", state: "Illinois", stateAbbr: "IL", slug: "chicago-il", shortSlug: "chicago" },
  { city: "Houston", state: "Texas", stateAbbr: "TX", slug: "houston-tx", shortSlug: "houston" },
  { city: "Phoenix", state: "Arizona", stateAbbr: "AZ", slug: "phoenix-az", shortSlug: "phoenix" },
  { city: "Philadelphia", state: "Pennsylvania", stateAbbr: "PA", slug: "philadelphia-pa", shortSlug: "philly" },
  { city: "San Antonio", state: "Texas", stateAbbr: "TX", slug: "san-antonio-tx", shortSlug: "san-antonio" },
  { city: "San Diego", state: "California", stateAbbr: "CA", slug: "san-diego-ca", shortSlug: "san-diego" },
  { city: "Dallas", state: "Texas", stateAbbr: "TX", slug: "dallas-tx", shortSlug: "dallas" },
  { city: "Austin", state: "Texas", stateAbbr: "TX", slug: "austin-tx", shortSlug: "austin" },
  { city: "Jacksonville", state: "Florida", stateAbbr: "FL", slug: "jacksonville-fl", shortSlug: "jacksonville-fl" },
  { city: "Fort Worth", state: "Texas", stateAbbr: "TX", slug: "fort-worth-tx", shortSlug: "fort-worth" },
  { city: "Columbus", state: "Ohio", stateAbbr: "OH", slug: "columbus-oh", shortSlug: "columbus" },
  { city: "Charlotte", state: "North Carolina", stateAbbr: "NC", slug: "charlotte-nc", shortSlug: "charlotte" },
  { city: "Indianapolis", state: "Indiana", stateAbbr: "IN", slug: "indianapolis-in", shortSlug: "indianapolis" },
  { city: "San Francisco", state: "California", stateAbbr: "CA", slug: "san-francisco-ca", shortSlug: "sf" },
  { city: "Seattle", state: "Washington", stateAbbr: "WA", slug: "seattle-wa", shortSlug: "seattle" },
  { city: "Denver", state: "Colorado", stateAbbr: "CO", slug: "denver-co", shortSlug: "denver" },
  { city: "Nashville", state: "Tennessee", stateAbbr: "TN", slug: "nashville-tn", shortSlug: "nashville" },
  { city: "Oklahoma City", state: "Oklahoma", stateAbbr: "OK", slug: "oklahoma-city-ok", shortSlug: "oklahoma-city" },
  { city: "El Paso", state: "Texas", stateAbbr: "TX", slug: "el-paso-tx", shortSlug: "el-paso" },
  { city: "Washington", state: "District of Columbia", stateAbbr: "DC", slug: "washington-dc", shortSlug: "dc" },
  { city: "Boston", state: "Massachusetts", stateAbbr: "MA", slug: "boston-ma", shortSlug: "boston" },
  { city: "Las Vegas", state: "Nevada", stateAbbr: "NV", slug: "las-vegas-nv", shortSlug: "vegas" },
  { city: "Portland", state: "Oregon", stateAbbr: "OR", slug: "portland-or", shortSlug: "portland" },
  { city: "Memphis", state: "Tennessee", stateAbbr: "TN", slug: "memphis-tn", shortSlug: "memphis" },
  { city: "Louisville", state: "Kentucky", stateAbbr: "KY", slug: "louisville-ky", shortSlug: "louisville" },
  { city: "Baltimore", state: "Maryland", stateAbbr: "MD", slug: "baltimore-md", shortSlug: "baltimore" },
  { city: "Milwaukee", state: "Wisconsin", stateAbbr: "WI", slug: "milwaukee-wi", shortSlug: "milwaukee" },
  { city: "Albuquerque", state: "New Mexico", stateAbbr: "NM", slug: "albuquerque-nm", shortSlug: "albuquerque" },
  { city: "Tucson", state: "Arizona", stateAbbr: "AZ", slug: "tucson-az", shortSlug: "tucson" },
  { city: "Fresno", state: "California", stateAbbr: "CA", slug: "fresno-ca", shortSlug: "fresno" },
  { city: "Mesa", state: "Arizona", stateAbbr: "AZ", slug: "mesa-az", shortSlug: "mesa" },
  { city: "Sacramento", state: "California", stateAbbr: "CA", slug: "sacramento-ca", shortSlug: "sacramento" },
  { city: "Atlanta", state: "Georgia", stateAbbr: "GA", slug: "atlanta-ga", shortSlug: "atl" },
  { city: "Kansas City", state: "Missouri", stateAbbr: "MO", slug: "kansas-city-mo", shortSlug: "kansas-city" },
  { city: "Omaha", state: "Nebraska", stateAbbr: "NE", slug: "omaha-ne", shortSlug: "omaha" },
  { city: "Colorado Springs", state: "Colorado", stateAbbr: "CO", slug: "colorado-springs-co", shortSlug: "colorado-springs" },
  { city: "Raleigh", state: "North Carolina", stateAbbr: "NC", slug: "raleigh-nc", shortSlug: "raleigh" },
  { city: "Virginia Beach", state: "Virginia", stateAbbr: "VA", slug: "virginia-beach-va", shortSlug: "virginia-beach" },
  { city: "Long Beach", state: "California", stateAbbr: "CA", slug: "long-beach-ca", shortSlug: "long-beach" },
  { city: "Miami", state: "Florida", stateAbbr: "FL", slug: "miami-fl", shortSlug: "miami" },
  { city: "Oakland", state: "California", stateAbbr: "CA", slug: "oakland-ca", shortSlug: "oakland" },
  { city: "Minneapolis", state: "Minnesota", stateAbbr: "MN", slug: "minneapolis-mn", shortSlug: "minneapolis" },
  { city: "Tampa", state: "Florida", stateAbbr: "FL", slug: "tampa-fl", shortSlug: "tampa" },
  { city: "Tulsa", state: "Oklahoma", stateAbbr: "OK", slug: "tulsa-ok", shortSlug: "tulsa" },
  { city: "Arlington", state: "Texas", stateAbbr: "TX", slug: "arlington-tx", shortSlug: "arlington" },
  { city: "New Orleans", state: "Louisiana", stateAbbr: "LA", slug: "new-orleans-la", shortSlug: "nola" },
  { city: "Wichita", state: "Kansas", stateAbbr: "KS", slug: "wichita-ks", shortSlug: "wichita" },
  { city: "Cleveland", state: "Ohio", stateAbbr: "OH", slug: "cleveland-oh", shortSlug: "cleveland" },
  { city: "Bakersfield", state: "California", stateAbbr: "CA", slug: "bakersfield-ca", shortSlug: "bakersfield" },
  { city: "Aurora", state: "Colorado", stateAbbr: "CO", slug: "aurora-co", shortSlug: "aurora" },
  { city: "Anaheim", state: "California", stateAbbr: "CA", slug: "anaheim-ca", shortSlug: "anaheim" },
  { city: "Honolulu", state: "Hawaii", stateAbbr: "HI", slug: "honolulu-hi", shortSlug: "honolulu" },
  { city: "Santa Ana", state: "California", stateAbbr: "CA", slug: "santa-ana-ca", shortSlug: "santa-ana" },
  { city: "Riverside", state: "California", stateAbbr: "CA", slug: "riverside-ca", shortSlug: "riverside" },
  { city: "Corpus Christi", state: "Texas", stateAbbr: "TX", slug: "corpus-christi-tx", shortSlug: "corpus-christi" },
  { city: "Lexington", state: "Kentucky", stateAbbr: "KY", slug: "lexington-ky", shortSlug: "lexington" },
  { city: "Pittsburgh", state: "Pennsylvania", stateAbbr: "PA", slug: "pittsburgh-pa", shortSlug: "pittsburgh" },
  { city: "Anchorage", state: "Alaska", stateAbbr: "AK", slug: "anchorage-ak", shortSlug: "anchorage" },
  { city: "Stockton", state: "California", stateAbbr: "CA", slug: "stockton-ca", shortSlug: "stockton" },
  { city: "Cincinnati", state: "Ohio", stateAbbr: "OH", slug: "cincinnati-oh", shortSlug: "cincinnati" },
  { city: "St Paul", state: "Minnesota", stateAbbr: "MN", slug: "st-paul-mn", shortSlug: "st-paul" },
  { city: "Greensboro", state: "North Carolina", stateAbbr: "NC", slug: "greensboro-nc", shortSlug: "greensboro" },
  { city: "Toledo", state: "Ohio", stateAbbr: "OH", slug: "toledo-oh", shortSlug: "toledo" },
  { city: "Newark", state: "New Jersey", stateAbbr: "NJ", slug: "newark-nj", shortSlug: "newark" },
  { city: "Plano", state: "Texas", stateAbbr: "TX", slug: "plano-tx", shortSlug: "plano" },
  { city: "Henderson", state: "Nevada", stateAbbr: "NV", slug: "henderson-nv", shortSlug: "henderson" },
  { city: "Lincoln", state: "Nebraska", stateAbbr: "NE", slug: "lincoln-ne", shortSlug: "lincoln" },
  { city: "Orlando", state: "Florida", stateAbbr: "FL", slug: "orlando-fl", shortSlug: "orlando" },
  { city: "Jersey City", state: "New Jersey", stateAbbr: "NJ", slug: "jersey-city-nj", shortSlug: "jersey-city" },
  { city: "Chandler", state: "Arizona", stateAbbr: "AZ", slug: "chandler-az", shortSlug: "chandler" },
  { city: "St Petersburg", state: "Florida", stateAbbr: "FL", slug: "st-petersburg-fl", shortSlug: "st-pete" },
  { city: "Laredo", state: "Texas", stateAbbr: "TX", slug: "laredo-tx", shortSlug: "laredo" },
  { city: "Norfolk", state: "Virginia", stateAbbr: "VA", slug: "norfolk-va", shortSlug: "norfolk" },
  { city: "Durham", state: "North Carolina", stateAbbr: "NC", slug: "durham-nc", shortSlug: "durham" },
  { city: "Madison", state: "Wisconsin", stateAbbr: "WI", slug: "madison-wi", shortSlug: "madison" },
  { city: "Lubbock", state: "Texas", stateAbbr: "TX", slug: "lubbock-tx", shortSlug: "lubbock" },
  { city: "Winston-Salem", state: "North Carolina", stateAbbr: "NC", slug: "winston-salem-nc", shortSlug: "winston-salem" },
  { city: "Garland", state: "Texas", stateAbbr: "TX", slug: "garland-tx", shortSlug: "garland" },
  { city: "Glendale", state: "Arizona", stateAbbr: "AZ", slug: "glendale-az", shortSlug: "glendale" },
  { city: "Hialeah", state: "Florida", stateAbbr: "FL", slug: "hialeah-fl", shortSlug: "hialeah" },
  { city: "Reno", state: "Nevada", stateAbbr: "NV", slug: "reno-nv", shortSlug: "reno" },
  { city: "Baton Rouge", state: "Louisiana", stateAbbr: "LA", slug: "baton-rouge-la", shortSlug: "baton-rouge" },
  { city: "Irvine", state: "California", stateAbbr: "CA", slug: "irvine-ca", shortSlug: "irvine" },
  { city: "Chesapeake", state: "Virginia", stateAbbr: "VA", slug: "chesapeake-va", shortSlug: "chesapeake" },
  { city: "Irving", state: "Texas", stateAbbr: "TX", slug: "irving-tx", shortSlug: "irving" },
  { city: "Scottsdale", state: "Arizona", stateAbbr: "AZ", slug: "scottsdale-az", shortSlug: "scottsdale" },
  { city: "North Las Vegas", state: "Nevada", stateAbbr: "NV", slug: "north-las-vegas-nv", shortSlug: "north-vegas" },
  { city: "Fremont", state: "California", stateAbbr: "CA", slug: "fremont-ca", shortSlug: "fremont" },
  { city: "Gilbert", state: "Arizona", stateAbbr: "AZ", slug: "gilbert-az", shortSlug: "gilbert" },
  { city: "San Bernardino", state: "California", stateAbbr: "CA", slug: "san-bernardino-ca", shortSlug: "san-bernardino" },
  { city: "Boise", state: "Idaho", stateAbbr: "ID", slug: "boise-id", shortSlug: "boise" },
  { city: "Birmingham", state: "Alabama", stateAbbr: "AL", slug: "birmingham-al", shortSlug: "birmingham" },
  { city: "Rochester", state: "New York", stateAbbr: "NY", slug: "rochester-ny", shortSlug: "rochester" },
  { city: "Richmond", state: "Virginia", stateAbbr: "VA", slug: "richmond-va", shortSlug: "richmond" },
  { city: "Spokane", state: "Washington", stateAbbr: "WA", slug: "spokane-wa", shortSlug: "spokane" },
  { city: "Des Moines", state: "Iowa", stateAbbr: "IA", slug: "des-moines-ia", shortSlug: "des-moines" },
  { city: "Montgomery", state: "Alabama", stateAbbr: "AL", slug: "montgomery-al", shortSlug: "montgomery" },
  { city: "Modesto", state: "California", stateAbbr: "CA", slug: "modesto-ca", shortSlug: "modesto" },
  { city: "Fayetteville", state: "North Carolina", stateAbbr: "NC", slug: "fayetteville-nc", shortSlug: "fayetteville" },
  // --- Added metros (103–400) ---
  { city: "Tacoma", state: "Washington", stateAbbr: "WA", slug: "tacoma-wa", shortSlug: "tacoma" },
  { city: "Oxnard", state: "California", stateAbbr: "CA", slug: "oxnard-ca", shortSlug: "oxnard" },
  { city: "Knoxville", state: "Tennessee", stateAbbr: "TN", slug: "knoxville-tn", shortSlug: "knoxville" },
  { city: "Brownsville", state: "Texas", stateAbbr: "TX", slug: "brownsville-tx", shortSlug: "brownsville" },
  { city: "Salt Lake City", state: "Utah", stateAbbr: "UT", slug: "salt-lake-city-ut", shortSlug: "salt-lake-city" },
  { city: "Tallahassee", state: "Florida", stateAbbr: "FL", slug: "tallahassee-fl", shortSlug: "tallahassee" },
  { city: "Fort Wayne", state: "Indiana", stateAbbr: "IN", slug: "fort-wayne-in", shortSlug: "fort-wayne" },
  { city: "Huntsville", state: "Alabama", stateAbbr: "AL", slug: "huntsville-al", shortSlug: "huntsville" },
  { city: "Providence", state: "Rhode Island", stateAbbr: "RI", slug: "providence-ri", shortSlug: "providence" },
  { city: "Grand Rapids", state: "Michigan", stateAbbr: "MI", slug: "grand-rapids-mi", shortSlug: "grand-rapids" },
  { city: "Overland Park", state: "Kansas", stateAbbr: "KS", slug: "overland-park-ks", shortSlug: "overland-park" },
  { city: "Yonkers", state: "New York", stateAbbr: "NY", slug: "yonkers-ny", shortSlug: "yonkers" },
  { city: "Akron", state: "Ohio", stateAbbr: "OH", slug: "akron-oh", shortSlug: "akron" },
  { city: "Little Rock", state: "Arkansas", stateAbbr: "AR", slug: "little-rock-ar", shortSlug: "little-rock" },
  { city: "Amarillo", state: "Texas", stateAbbr: "TX", slug: "amarillo-tx", shortSlug: "amarillo" },
  { city: "Moreno Valley", state: "California", stateAbbr: "CA", slug: "moreno-valley-ca", shortSlug: "moreno-valley" },
  { city: "Fontana", state: "California", stateAbbr: "CA", slug: "fontana-ca", shortSlug: "fontana" },
  { city: "Grand Prairie", state: "Texas", stateAbbr: "TX", slug: "grand-prairie-tx", shortSlug: "grand-prairie" },
  { city: "Mobile", state: "Alabama", stateAbbr: "AL", slug: "mobile-al", shortSlug: "mobile" },
  { city: "Shreveport", state: "Louisiana", stateAbbr: "LA", slug: "shreveport-la", shortSlug: "shreveport" },
  { city: "Augusta", state: "Georgia", stateAbbr: "GA", slug: "augusta-ga", shortSlug: "augusta" },
  { city: "Frisco", state: "Texas", stateAbbr: "TX", slug: "frisco-tx", shortSlug: "frisco" },
  { city: "Cape Coral", state: "Florida", stateAbbr: "FL", slug: "cape-coral-fl", shortSlug: "cape-coral" },
  { city: "McKinney", state: "Texas", stateAbbr: "TX", slug: "mckinney-tx", shortSlug: "mckinney" },
  { city: "Sioux Falls", state: "South Dakota", stateAbbr: "SD", slug: "sioux-falls-sd", shortSlug: "sioux-falls" },
  { city: "Peoria", state: "Arizona", stateAbbr: "AZ", slug: "peoria-az", shortSlug: "peoria" },
  { city: "Ontario", state: "California", stateAbbr: "CA", slug: "ontario-ca", shortSlug: "ontario" },
  { city: "Vancouver", state: "Washington", stateAbbr: "WA", slug: "vancouver-wa", shortSlug: "vancouver" },
  { city: "Tempe", state: "Arizona", stateAbbr: "AZ", slug: "tempe-az", shortSlug: "tempe" },
  { city: "Springfield", state: "Missouri", stateAbbr: "MO", slug: "springfield-mo", shortSlug: "springfield-mo" },
  { city: "Pembroke Pines", state: "Florida", stateAbbr: "FL", slug: "pembroke-pines-fl", shortSlug: "pembroke-pines" },
  { city: "Salem", state: "Oregon", stateAbbr: "OR", slug: "salem-or", shortSlug: "salem" },
  { city: "Lancaster", state: "California", stateAbbr: "CA", slug: "lancaster-ca", shortSlug: "lancaster-ca" },
  { city: "Elk Grove", state: "California", stateAbbr: "CA", slug: "elk-grove-ca", shortSlug: "elk-grove" },
  { city: "Corona", state: "California", stateAbbr: "CA", slug: "corona-ca", shortSlug: "corona" },
  { city: "Eugene", state: "Oregon", stateAbbr: "OR", slug: "eugene-or", shortSlug: "eugene" },
  { city: "Palmdale", state: "California", stateAbbr: "CA", slug: "palmdale-ca", shortSlug: "palmdale" },
  { city: "Clarksville", state: "Tennessee", stateAbbr: "TN", slug: "clarksville-tn", shortSlug: "clarksville" },
  { city: "Salinas", state: "California", stateAbbr: "CA", slug: "salinas-ca", shortSlug: "salinas" },
  { city: "Murfreesboro", state: "Tennessee", stateAbbr: "TN", slug: "murfreesboro-tn", shortSlug: "murfreesboro" },
  { city: "Roseville", state: "California", stateAbbr: "CA", slug: "roseville-ca", shortSlug: "roseville" },
  { city: "Dayton", state: "Ohio", stateAbbr: "OH", slug: "dayton-oh", shortSlug: "dayton" },
  { city: "Surprise", state: "Arizona", stateAbbr: "AZ", slug: "surprise-az", shortSlug: "surprise" },
  { city: "Macon", state: "Georgia", stateAbbr: "GA", slug: "macon-ga", shortSlug: "macon" },
  { city: "Denton", state: "Texas", stateAbbr: "TX", slug: "denton-tx", shortSlug: "denton" },
  { city: "Waco", state: "Texas", stateAbbr: "TX", slug: "waco-tx", shortSlug: "waco" },
  { city: "McAllen", state: "Texas", stateAbbr: "TX", slug: "mcallen-tx", shortSlug: "mcallen" },
  { city: "Paterson", state: "New Jersey", stateAbbr: "NJ", slug: "paterson-nj", shortSlug: "paterson" },
  { city: "Savannah", state: "Georgia", stateAbbr: "GA", slug: "savannah-ga", shortSlug: "savannah" },
  { city: "Lakewood", state: "Colorado", stateAbbr: "CO", slug: "lakewood-co", shortSlug: "lakewood" },
  { city: "Midland", state: "Texas", stateAbbr: "TX", slug: "midland-tx", shortSlug: "midland" },
  { city: "Killeen", state: "Texas", stateAbbr: "TX", slug: "killeen-tx", shortSlug: "killeen" },
  { city: "Bellevue", state: "Washington", stateAbbr: "WA", slug: "bellevue-wa", shortSlug: "bellevue" },
  { city: "Miramar", state: "Florida", stateAbbr: "FL", slug: "miramar-fl", shortSlug: "miramar" },
  { city: "Mesquite", state: "Texas", stateAbbr: "TX", slug: "mesquite-tx", shortSlug: "mesquite" },
  { city: "Sunnyvale", state: "California", stateAbbr: "CA", slug: "sunnyvale-ca", shortSlug: "sunnyvale" },
  { city: "Santa Clarita", state: "California", stateAbbr: "CA", slug: "santa-clarita-ca", shortSlug: "santa-clarita" },
  { city: "Pompano Beach", state: "Florida", stateAbbr: "FL", slug: "pompano-beach-fl", shortSlug: "pompano-beach" },
  { city: "West Jordan", state: "Utah", stateAbbr: "UT", slug: "west-jordan-ut", shortSlug: "west-jordan" },
  { city: "Centennial", state: "Colorado", stateAbbr: "CO", slug: "centennial-co", shortSlug: "centennial" },
  { city: "Pearland", state: "Texas", stateAbbr: "TX", slug: "pearland-tx", shortSlug: "pearland" },
  { city: "Westminster", state: "Colorado", stateAbbr: "CO", slug: "westminster-co", shortSlug: "westminster-co" },
  { city: "Murrieta", state: "California", stateAbbr: "CA", slug: "murrieta-ca", shortSlug: "murrieta" },
  { city: "Palm Bay", state: "Florida", stateAbbr: "FL", slug: "palm-bay-fl", shortSlug: "palm-bay" },
  { city: "Round Rock", state: "Texas", stateAbbr: "TX", slug: "round-rock-tx", shortSlug: "round-rock" },
  { city: "Lewisville", state: "Texas", stateAbbr: "TX", slug: "lewisville-tx", shortSlug: "lewisville" },
  { city: "Miami Gardens", state: "Florida", stateAbbr: "FL", slug: "miami-gardens-fl", shortSlug: "miami-gardens" },
  { city: "West Palm Beach", state: "Florida", stateAbbr: "FL", slug: "west-palm-beach-fl", shortSlug: "west-palm-beach" },
  { city: "Odessa", state: "Texas", stateAbbr: "TX", slug: "odessa-tx", shortSlug: "odessa" },
  { city: "League City", state: "Texas", stateAbbr: "TX", slug: "league-city-tx", shortSlug: "league-city" },
  { city: "Allen", state: "Texas", stateAbbr: "TX", slug: "allen-tx", shortSlug: "allen" },
  { city: "Davie", state: "Florida", stateAbbr: "FL", slug: "davie-fl", shortSlug: "davie" },
  { city: "San Marcos", state: "Texas", stateAbbr: "TX", slug: "san-marcos-tx", shortSlug: "san-marcos" },
  { city: "Edinburg", state: "Texas", stateAbbr: "TX", slug: "edinburg-tx", shortSlug: "edinburg" },
  { city: "Meridian", state: "Idaho", stateAbbr: "ID", slug: "meridian-id", shortSlug: "meridian" },
  { city: "Tuscaloosa", state: "Alabama", stateAbbr: "AL", slug: "tuscaloosa-al", shortSlug: "tuscaloosa" },
  { city: "Longmont", state: "Colorado", stateAbbr: "CO", slug: "longmont-co", shortSlug: "longmont" },
  { city: "South Bend", state: "Indiana", stateAbbr: "IN", slug: "south-bend-in", shortSlug: "south-bend" },
  { city: "Broken Arrow", state: "Oklahoma", stateAbbr: "OK", slug: "broken-arrow-ok", shortSlug: "broken-arrow" },
  { city: "Tyler", state: "Texas", stateAbbr: "TX", slug: "tyler-tx", shortSlug: "tyler" },
  { city: "College Station", state: "Texas", stateAbbr: "TX", slug: "college-station-tx", shortSlug: "college-station" },
  { city: "Lakeland", state: "Florida", stateAbbr: "FL", slug: "lakeland-fl", shortSlug: "lakeland" },
  { city: "Clearwater", state: "Florida", stateAbbr: "FL", slug: "clearwater-fl", shortSlug: "clearwater" },
  { city: "Pueblo", state: "Colorado", stateAbbr: "CO", slug: "pueblo-co", shortSlug: "pueblo" },
  { city: "West Valley City", state: "Utah", stateAbbr: "UT", slug: "west-valley-city-ut", shortSlug: "west-valley-city" },
  { city: "Westminster", state: "California", stateAbbr: "CA", slug: "westminster-ca", shortSlug: "westminster-ca" },
  { city: "Arvada", state: "Colorado", stateAbbr: "CO", slug: "arvada-co", shortSlug: "arvada" },
  { city: "Thornton", state: "Colorado", stateAbbr: "CO", slug: "thornton-co", shortSlug: "thornton" },
  { city: "Clovis", state: "California", stateAbbr: "CA", slug: "clovis-ca", shortSlug: "clovis" },
  { city: "Palm Coast", state: "Florida", stateAbbr: "FL", slug: "palm-coast-fl", shortSlug: "palm-coast" },
  { city: "New Braunfels", state: "Texas", stateAbbr: "TX", slug: "new-braunfels-tx", shortSlug: "new-braunfels" },
  { city: "Goodyear", state: "Arizona", stateAbbr: "AZ", slug: "goodyear-az", shortSlug: "goodyear" },
  { city: "Buckeye", state: "Arizona", stateAbbr: "AZ", slug: "buckeye-az", shortSlug: "buckeye" },
  { city: "Daly City", state: "California", stateAbbr: "CA", slug: "daly-city-ca", shortSlug: "daly-city" },
  { city: "Greenville", state: "South Carolina", stateAbbr: "SC", slug: "greenville-sc", shortSlug: "greenville-sc" },
  { city: "Columbia", state: "South Carolina", stateAbbr: "SC", slug: "columbia-sc", shortSlug: "columbia" },
  { city: "Charleston", state: "South Carolina", stateAbbr: "SC", slug: "charleston-sc", shortSlug: "charleston" },
  { city: "Chattanooga", state: "Tennessee", stateAbbr: "TN", slug: "chattanooga-tn", shortSlug: "chattanooga" },
  { city: "Jackson", state: "Mississippi", stateAbbr: "MS", slug: "jackson-ms", shortSlug: "jackson" },
  { city: "Pensacola", state: "Florida", stateAbbr: "FL", slug: "pensacola-fl", shortSlug: "pensacola" },
  { city: "Daytona Beach", state: "Florida", stateAbbr: "FL", slug: "daytona-beach-fl", shortSlug: "daytona-beach" },
  { city: "Ocala", state: "Florida", stateAbbr: "FL", slug: "ocala-fl", shortSlug: "ocala" },
  { city: "Gainesville", state: "Florida", stateAbbr: "FL", slug: "gainesville-fl", shortSlug: "gainesville" },
  { city: "Port St Lucie", state: "Florida", stateAbbr: "FL", slug: "port-st-lucie-fl", shortSlug: "port-st-lucie" },
  { city: "Deltona", state: "Florida", stateAbbr: "FL", slug: "deltona-fl", shortSlug: "deltona" },
  { city: "Kissimmee", state: "Florida", stateAbbr: "FL", slug: "kissimmee-fl", shortSlug: "kissimmee" },
  { city: "Sanford", state: "Florida", stateAbbr: "FL", slug: "sanford-fl", shortSlug: "sanford-fl" },
  { city: "Bradenton", state: "Florida", stateAbbr: "FL", slug: "bradenton-fl", shortSlug: "bradenton" },
  { city: "Sarasota", state: "Florida", stateAbbr: "FL", slug: "sarasota-fl", shortSlug: "sarasota" },
  { city: "Fort Myers", state: "Florida", stateAbbr: "FL", slug: "fort-myers-fl", shortSlug: "fort-myers" },
  { city: "Naples", state: "Florida", stateAbbr: "FL", slug: "naples-fl", shortSlug: "naples" },
  { city: "Bonita Springs", state: "Florida", stateAbbr: "FL", slug: "bonita-springs-fl", shortSlug: "bonita-springs" },
  { city: "Lehigh Acres", state: "Florida", stateAbbr: "FL", slug: "lehigh-acres-fl", shortSlug: "lehigh-acres" },
  { city: "Spring Hill", state: "Florida", stateAbbr: "FL", slug: "spring-hill-fl", shortSlug: "spring-hill" },
  { city: "Palm Harbor", state: "Florida", stateAbbr: "FL", slug: "palm-harbor-fl", shortSlug: "palm-harbor" },
  { city: "Largo", state: "Florida", stateAbbr: "FL", slug: "largo-fl", shortSlug: "largo" },
  { city: "Dunedin", state: "Florida", stateAbbr: "FL", slug: "dunedin-fl", shortSlug: "dunedin" },
  { city: "Tarpon Springs", state: "Florida", stateAbbr: "FL", slug: "tarpon-springs-fl", shortSlug: "tarpon-springs" },
  { city: "New Haven", state: "Connecticut", stateAbbr: "CT", slug: "new-haven-ct", shortSlug: "new-haven" },
  { city: "Hartford", state: "Connecticut", stateAbbr: "CT", slug: "hartford-ct", shortSlug: "hartford" },
  { city: "Bridgeport", state: "Connecticut", stateAbbr: "CT", slug: "bridgeport-ct", shortSlug: "bridgeport" },
  { city: "Stamford", state: "Connecticut", stateAbbr: "CT", slug: "stamford-ct", shortSlug: "stamford" },
  { city: "Waterbury", state: "Connecticut", stateAbbr: "CT", slug: "waterbury-ct", shortSlug: "waterbury" },
  { city: "Norwalk", state: "Connecticut", stateAbbr: "CT", slug: "norwalk-ct", shortSlug: "norwalk" },
  { city: "Danbury", state: "Connecticut", stateAbbr: "CT", slug: "danbury-ct", shortSlug: "danbury" },
  { city: "Worcester", state: "Massachusetts", stateAbbr: "MA", slug: "worcester-ma", shortSlug: "worcester" },
  { city: "Springfield", state: "Massachusetts", stateAbbr: "MA", slug: "springfield-ma", shortSlug: "springfield-ma" },
  { city: "Lowell", state: "Massachusetts", stateAbbr: "MA", slug: "lowell-ma", shortSlug: "lowell" },
  { city: "Cambridge", state: "Massachusetts", stateAbbr: "MA", slug: "cambridge-ma", shortSlug: "cambridge" },
  { city: "New Bedford", state: "Massachusetts", stateAbbr: "MA", slug: "new-bedford-ma", shortSlug: "new-bedford" },
  { city: "Brockton", state: "Massachusetts", stateAbbr: "MA", slug: "brockton-ma", shortSlug: "brockton" },
  { city: "Quincy", state: "Massachusetts", stateAbbr: "MA", slug: "quincy-ma", shortSlug: "quincy" },
  { city: "Lynn", state: "Massachusetts", stateAbbr: "MA", slug: "lynn-ma", shortSlug: "lynn" },
  { city: "Fall River", state: "Massachusetts", stateAbbr: "MA", slug: "fall-river-ma", shortSlug: "fall-river" },
  { city: "Newton", state: "Massachusetts", stateAbbr: "MA", slug: "newton-ma", shortSlug: "newton" },
  { city: "Somerville", state: "Massachusetts", stateAbbr: "MA", slug: "somerville-ma", shortSlug: "somerville" },
  { city: "Lawrence", state: "Massachusetts", stateAbbr: "MA", slug: "lawrence-ma", shortSlug: "lawrence" },
  { city: "Haverhill", state: "Massachusetts", stateAbbr: "MA", slug: "haverhill-ma", shortSlug: "haverhill" },
  { city: "Trenton", state: "New Jersey", stateAbbr: "NJ", slug: "trenton-nj", shortSlug: "trenton" },
  { city: "Camden", state: "New Jersey", stateAbbr: "NJ", slug: "camden-nj", shortSlug: "camden" },
  { city: "Passaic", state: "New Jersey", stateAbbr: "NJ", slug: "passaic-nj", shortSlug: "passaic" },
  { city: "Elizabeth", state: "New Jersey", stateAbbr: "NJ", slug: "elizabeth-nj", shortSlug: "elizabeth" },
  { city: "Clifton", state: "New Jersey", stateAbbr: "NJ", slug: "clifton-nj", shortSlug: "clifton" },
  { city: "Bayonne", state: "New Jersey", stateAbbr: "NJ", slug: "bayonne-nj", shortSlug: "bayonne" },
  { city: "East Orange", state: "New Jersey", stateAbbr: "NJ", slug: "east-orange-nj", shortSlug: "east-orange" },
  { city: "Vineland", state: "New Jersey", stateAbbr: "NJ", slug: "vineland-nj", shortSlug: "vineland" },
  { city: "Union City", state: "New Jersey", stateAbbr: "NJ", slug: "union-city-nj", shortSlug: "union-city" },
  { city: "Hoboken", state: "New Jersey", stateAbbr: "NJ", slug: "hoboken-nj", shortSlug: "hoboken" },
  { city: "Hackensack", state: "New Jersey", stateAbbr: "NJ", slug: "hackensack-nj", shortSlug: "hackensack" },
  { city: "Paramus", state: "New Jersey", stateAbbr: "NJ", slug: "paramus-nj", shortSlug: "paramus" },
  { city: "Wayne", state: "New Jersey", stateAbbr: "NJ", slug: "wayne-nj", shortSlug: "wayne" },
  { city: "Cherry Hill", state: "New Jersey", stateAbbr: "NJ", slug: "cherry-hill-nj", shortSlug: "cherry-hill" },
  { city: "Princeton", state: "New Jersey", stateAbbr: "NJ", slug: "princeton-nj", shortSlug: "princeton" },
  { city: "Buffalo", state: "New York", stateAbbr: "NY", slug: "buffalo-ny", shortSlug: "buffalo" },
  { city: "Syracuse", state: "New York", stateAbbr: "NY", slug: "syracuse-ny", shortSlug: "syracuse" },
  { city: "Albany", state: "New York", stateAbbr: "NY", slug: "albany-ny", shortSlug: "albany" },
  { city: "Schenectady", state: "New York", stateAbbr: "NY", slug: "schenectady-ny", shortSlug: "schenectady" },
  { city: "Utica", state: "New York", stateAbbr: "NY", slug: "utica-ny", shortSlug: "utica" },
  { city: "White Plains", state: "New York", stateAbbr: "NY", slug: "white-plains-ny", shortSlug: "white-plains" },
  { city: "New Rochelle", state: "New York", stateAbbr: "NY", slug: "new-rochelle-ny", shortSlug: "new-rochelle" },
  { city: "Mount Vernon", state: "New York", stateAbbr: "NY", slug: "mount-vernon-ny", shortSlug: "mount-vernon" },
  { city: "Hempstead", state: "New York", stateAbbr: "NY", slug: "hempstead-ny", shortSlug: "hempstead" },
  { city: "Freeport", state: "New York", stateAbbr: "NY", slug: "freeport-ny", shortSlug: "freeport" },
  { city: "Valley Stream", state: "New York", stateAbbr: "NY", slug: "valley-stream-ny", shortSlug: "valley-stream" },
  { city: "Levittown", state: "New York", stateAbbr: "NY", slug: "levittown-ny", shortSlug: "levittown" },
  { city: "Brentwood", state: "New York", stateAbbr: "NY", slug: "brentwood-ny", shortSlug: "brentwood" },
  { city: "Bay Shore", state: "New York", stateAbbr: "NY", slug: "bay-shore-ny", shortSlug: "bay-shore" },
  { city: "Huntington", state: "New York", stateAbbr: "NY", slug: "huntington-ny", shortSlug: "huntington" },
  { city: "Smithtown", state: "New York", stateAbbr: "NY", slug: "smithtown-ny", shortSlug: "smithtown" },
  { city: "Commack", state: "New York", stateAbbr: "NY", slug: "commack-ny", shortSlug: "commack" },
  { city: "Islip", state: "New York", stateAbbr: "NY", slug: "islip-ny", shortSlug: "islip" },
  { city: "Babylon", state: "New York", stateAbbr: "NY", slug: "babylon-ny", shortSlug: "babylon" },
  { city: "Poughkeepsie", state: "New York", stateAbbr: "NY", slug: "poughkeepsie-ny", shortSlug: "poughkeepsie" },
  { city: "Newburgh", state: "New York", stateAbbr: "NY", slug: "newburgh-ny", shortSlug: "newburgh" },
  { city: "Middletown", state: "New York", stateAbbr: "NY", slug: "middletown-ny", shortSlug: "middletown" },
  { city: "Kingston", state: "New York", stateAbbr: "NY", slug: "kingston-ny", shortSlug: "kingston" },
  { city: "Ithaca", state: "New York", stateAbbr: "NY", slug: "ithaca-ny", shortSlug: "ithaca" },
  { city: "Binghamton", state: "New York", stateAbbr: "NY", slug: "binghamton-ny", shortSlug: "binghamton" },
  { city: "Elmira", state: "New York", stateAbbr: "NY", slug: "elmira-ny", shortSlug: "elmira" },
  { city: "Jamestown", state: "New York", stateAbbr: "NY", slug: "jamestown-ny", shortSlug: "jamestown" },
  { city: "Niagara Falls", state: "New York", stateAbbr: "NY", slug: "niagara-falls-ny", shortSlug: "niagara-falls" },
  { city: "Saratoga Springs", state: "New York", stateAbbr: "NY", slug: "saratoga-springs-ny", shortSlug: "saratoga-springs" },
  { city: "Plattsburgh", state: "New York", stateAbbr: "NY", slug: "plattsburgh-ny", shortSlug: "plattsburgh" },
  { city: "Watertown", state: "New York", stateAbbr: "NY", slug: "watertown-ny", shortSlug: "watertown" },
  { city: "Ogdensburg", state: "New York", stateAbbr: "NY", slug: "ogdensburg-ny", shortSlug: "ogdensburg" },
  { city: "Glens Falls", state: "New York", stateAbbr: "NY", slug: "glens-falls-ny", shortSlug: "glens-falls" },
  { city: "Asheville", state: "North Carolina", stateAbbr: "NC", slug: "asheville-nc", shortSlug: "asheville" },
  { city: "Wilmington", state: "North Carolina", stateAbbr: "NC", slug: "wilmington-nc", shortSlug: "wilmington" },
  { city: "High Point", state: "North Carolina", stateAbbr: "NC", slug: "high-point-nc", shortSlug: "high-point" },
  { city: "Gastonia", state: "North Carolina", stateAbbr: "NC", slug: "gastonia-nc", shortSlug: "gastonia" },
  { city: "Concord", state: "North Carolina", stateAbbr: "NC", slug: "concord-nc", shortSlug: "concord-nc" },
  { city: "Huntersville", state: "North Carolina", stateAbbr: "NC", slug: "huntersville-nc", shortSlug: "huntersville" },
  { city: "Mooresville", state: "North Carolina", stateAbbr: "NC", slug: "mooresville-nc", shortSlug: "mooresville" },
  { city: "Apex", state: "North Carolina", stateAbbr: "NC", slug: "apex-nc", shortSlug: "apex" },
  { city: "Cary", state: "North Carolina", stateAbbr: "NC", slug: "cary-nc", shortSlug: "cary" },
  { city: "Holly Springs", state: "North Carolina", stateAbbr: "NC", slug: "holly-springs-nc", shortSlug: "holly-springs" },
  { city: "Wake Forest", state: "North Carolina", stateAbbr: "NC", slug: "wake-forest-nc", shortSlug: "wake-forest" },
  { city: "Greenville", state: "North Carolina", stateAbbr: "NC", slug: "greenville-nc", shortSlug: "greenville-nc" },
  { city: "Jacksonville", state: "North Carolina", stateAbbr: "NC", slug: "jacksonville-nc", shortSlug: "jacksonville-nc" },
  { city: "Burlington", state: "North Carolina", stateAbbr: "NC", slug: "burlington-nc", shortSlug: "burlington-nc" },
  { city: "Hickory", state: "North Carolina", stateAbbr: "NC", slug: "hickory-nc", shortSlug: "hickory" },
  { city: "Kannapolis", state: "North Carolina", stateAbbr: "NC", slug: "kannapolis-nc", shortSlug: "kannapolis" },
  { city: "Statesville", state: "North Carolina", stateAbbr: "NC", slug: "statesville-nc", shortSlug: "statesville" },
  { city: "Salisbury", state: "North Carolina", stateAbbr: "NC", slug: "salisbury-nc", shortSlug: "salisbury" },
  { city: "Sanford", state: "North Carolina", stateAbbr: "NC", slug: "sanford-nc", shortSlug: "sanford-nc" },
  { city: "Lumberton", state: "North Carolina", stateAbbr: "NC", slug: "lumberton-nc", shortSlug: "lumberton" },
  { city: "Goldsboro", state: "North Carolina", stateAbbr: "NC", slug: "goldsboro-nc", shortSlug: "goldsboro" },
  { city: "Rocky Mount", state: "North Carolina", stateAbbr: "NC", slug: "rocky-mount-nc", shortSlug: "rocky-mount" },
  { city: "Wilson", state: "North Carolina", stateAbbr: "NC", slug: "wilson-nc", shortSlug: "wilson" },
  { city: "New Bern", state: "North Carolina", stateAbbr: "NC", slug: "new-bern-nc", shortSlug: "new-bern" },
  { city: "Elizabeth City", state: "North Carolina", stateAbbr: "NC", slug: "elizabeth-city-nc", shortSlug: "elizabeth-city" },
  { city: "Outer Banks", state: "North Carolina", stateAbbr: "NC", slug: "outer-banks-nc", shortSlug: "outer-banks" },
  { city: "Boone", state: "North Carolina", stateAbbr: "NC", slug: "boone-nc", shortSlug: "boone" },
  { city: "Hendersonville", state: "North Carolina", stateAbbr: "NC", slug: "hendersonville-nc", shortSlug: "hendersonville" },
  { city: "Brevard", state: "North Carolina", stateAbbr: "NC", slug: "brevard-nc", shortSlug: "brevard" },
  { city: "Morganton", state: "North Carolina", stateAbbr: "NC", slug: "morganton-nc", shortSlug: "morganton" },
  // Additional cities to reach 400
  { city: "Beaumont", state: "Texas", stateAbbr: "TX", slug: "beaumont-tx", shortSlug: "beaumont" },
  { city: "Abilene", state: "Texas", stateAbbr: "TX", slug: "abilene-tx", shortSlug: "abilene" },
  { city: "Pasadena", state: "Texas", stateAbbr: "TX", slug: "pasadena-tx", shortSlug: "pasadena" },
  { city: "Carrollton", state: "Texas", stateAbbr: "TX", slug: "carrollton-tx", shortSlug: "carrollton" },
  { city: "Sugar Land", state: "Texas", stateAbbr: "TX", slug: "sugar-land-tx", shortSlug: "sugar-land" },
  { city: "Visalia", state: "California", stateAbbr: "CA", slug: "visalia-ca", shortSlug: "visalia" },
  { city: "Santa Rosa", state: "California", stateAbbr: "CA", slug: "santa-rosa-ca", shortSlug: "santa-rosa" },
  { city: "Concord", state: "California", stateAbbr: "CA", slug: "concord-ca", shortSlug: "concord-ca" },
  { city: "Thousand Oaks", state: "California", stateAbbr: "CA", slug: "thousand-oaks-ca", shortSlug: "thousand-oaks" },
  { city: "Simi Valley", state: "California", stateAbbr: "CA", slug: "simi-valley-ca", shortSlug: "simi-valley" },
  { city: "Victorville", state: "California", stateAbbr: "CA", slug: "victorville-ca", shortSlug: "victorville" },
  { city: "Vallejo", state: "California", stateAbbr: "CA", slug: "vallejo-ca", shortSlug: "vallejo" },
  { city: "Berkeley", state: "California", stateAbbr: "CA", slug: "berkeley-ca", shortSlug: "berkeley" },
  { city: "El Monte", state: "California", stateAbbr: "CA", slug: "el-monte-ca", shortSlug: "el-monte" },
  { city: "Downey", state: "California", stateAbbr: "CA", slug: "downey-ca", shortSlug: "downey" },
  { city: "Costa Mesa", state: "California", stateAbbr: "CA", slug: "costa-mesa-ca", shortSlug: "costa-mesa" },
  { city: "Inglewood", state: "California", stateAbbr: "CA", slug: "inglewood-ca", shortSlug: "inglewood" },
  { city: "Carlsbad", state: "California", stateAbbr: "CA", slug: "carlsbad-ca", shortSlug: "carlsbad" },
  { city: "Antioch", state: "California", stateAbbr: "CA", slug: "antioch-ca", shortSlug: "antioch" },
  { city: "Temecula", state: "California", stateAbbr: "CA", slug: "temecula-ca", shortSlug: "temecula" },
  { city: "Coral Springs", state: "Florida", stateAbbr: "FL", slug: "coral-springs-fl", shortSlug: "coral-springs" },
  { city: "Hollywood", state: "Florida", stateAbbr: "FL", slug: "hollywood-fl", shortSlug: "hollywood" },
  { city: "Sunrise", state: "Florida", stateAbbr: "FL", slug: "sunrise-fl", shortSlug: "sunrise" },
  { city: "Plantation", state: "Florida", stateAbbr: "FL", slug: "plantation-fl", shortSlug: "plantation" },
  { city: "Boca Raton", state: "Florida", stateAbbr: "FL", slug: "boca-raton-fl", shortSlug: "boca-raton" },
  { city: "Deerfield Beach", state: "Florida", stateAbbr: "FL", slug: "deerfield-beach-fl", shortSlug: "deerfield-beach" },
  { city: "Homestead", state: "Florida", stateAbbr: "FL", slug: "homestead-fl", shortSlug: "homestead" },
  { city: "Boynton Beach", state: "Florida", stateAbbr: "FL", slug: "boynton-beach-fl", shortSlug: "boynton-beach" },
  { city: "Lauderhill", state: "Florida", stateAbbr: "FL", slug: "lauderhill-fl", shortSlug: "lauderhill" },
  { city: "Fort Lauderdale", state: "Florida", stateAbbr: "FL", slug: "fort-lauderdale-fl", shortSlug: "fort-lauderdale" },
  { city: "Youngstown", state: "Ohio", stateAbbr: "OH", slug: "youngstown-oh", shortSlug: "youngstown" },
  { city: "Canton", state: "Ohio", stateAbbr: "OH", slug: "canton-oh", shortSlug: "canton" },
  { city: "Parma", state: "Ohio", stateAbbr: "OH", slug: "parma-oh", shortSlug: "parma" },
  { city: "Lorain", state: "Ohio", stateAbbr: "OH", slug: "lorain-oh", shortSlug: "lorain" },
  { city: "Hamilton", state: "Ohio", stateAbbr: "OH", slug: "hamilton-oh", shortSlug: "hamilton" },
  { city: "Springfield", state: "Ohio", stateAbbr: "OH", slug: "springfield-oh", shortSlug: "springfield-oh" },
  { city: "Allentown", state: "Pennsylvania", stateAbbr: "PA", slug: "allentown-pa", shortSlug: "allentown" },
  { city: "Erie", state: "Pennsylvania", stateAbbr: "PA", slug: "erie-pa", shortSlug: "erie" },
  { city: "Reading", state: "Pennsylvania", stateAbbr: "PA", slug: "reading-pa", shortSlug: "reading" },
  { city: "Scranton", state: "Pennsylvania", stateAbbr: "PA", slug: "scranton-pa", shortSlug: "scranton" },
  { city: "Bethlehem", state: "Pennsylvania", stateAbbr: "PA", slug: "bethlehem-pa", shortSlug: "bethlehem" },
  { city: "Lancaster", state: "Pennsylvania", stateAbbr: "PA", slug: "lancaster-pa", shortSlug: "lancaster-pa" },
  { city: "Harrisburg", state: "Pennsylvania", stateAbbr: "PA", slug: "harrisburg-pa", shortSlug: "harrisburg" },
  { city: "York", state: "Pennsylvania", stateAbbr: "PA", slug: "york-pa", shortSlug: "york" },
  { city: "Ann Arbor", state: "Michigan", stateAbbr: "MI", slug: "ann-arbor-mi", shortSlug: "ann-arbor" },
  { city: "Lansing", state: "Michigan", stateAbbr: "MI", slug: "lansing-mi", shortSlug: "lansing" },
  { city: "Flint", state: "Michigan", stateAbbr: "MI", slug: "flint-mi", shortSlug: "flint" },
  { city: "Dearborn", state: "Michigan", stateAbbr: "MI", slug: "dearborn-mi", shortSlug: "dearborn" },
  { city: "Kalamazoo", state: "Michigan", stateAbbr: "MI", slug: "kalamazoo-mi", shortSlug: "kalamazoo" },
  { city: "Sterling Heights", state: "Michigan", stateAbbr: "MI", slug: "sterling-heights-mi", shortSlug: "sterling-heights" },
  { city: "Detroit", state: "Michigan", stateAbbr: "MI", slug: "detroit-mi", shortSlug: "detroit" },
  { city: "Warren", state: "Michigan", stateAbbr: "MI", slug: "warren-mi", shortSlug: "warren" },
  { city: "Athens", state: "Georgia", stateAbbr: "GA", slug: "athens-ga", shortSlug: "athens" },
  { city: "Sandy Springs", state: "Georgia", stateAbbr: "GA", slug: "sandy-springs-ga", shortSlug: "sandy-springs" },
  { city: "Roswell", state: "Georgia", stateAbbr: "GA", slug: "roswell-ga", shortSlug: "roswell" },
  { city: "Johns Creek", state: "Georgia", stateAbbr: "GA", slug: "johns-creek-ga", shortSlug: "johns-creek" },
  { city: "Alpharetta", state: "Georgia", stateAbbr: "GA", slug: "alpharetta-ga", shortSlug: "alpharetta" },
  { city: "Marietta", state: "Georgia", stateAbbr: "GA", slug: "marietta-ga", shortSlug: "marietta" },
  { city: "Valdosta", state: "Georgia", stateAbbr: "GA", slug: "valdosta-ga", shortSlug: "valdosta" },
  { city: "Smyrna", state: "Georgia", stateAbbr: "GA", slug: "smyrna-ga", shortSlug: "smyrna" },
  { city: "Warner Robins", state: "Georgia", stateAbbr: "GA", slug: "warner-robins-ga", shortSlug: "warner-robins" },
  { city: "Provo", state: "Utah", stateAbbr: "UT", slug: "provo-ut", shortSlug: "provo" },
  { city: "Orem", state: "Utah", stateAbbr: "UT", slug: "orem-ut", shortSlug: "orem" },
  { city: "Sandy", state: "Utah", stateAbbr: "UT", slug: "sandy-ut", shortSlug: "sandy" },
  { city: "Ogden", state: "Utah", stateAbbr: "UT", slug: "ogden-ut", shortSlug: "ogden" },
  { city: "St George", state: "Utah", stateAbbr: "UT", slug: "st-george-ut", shortSlug: "st-george" },
  { city: "Layton", state: "Utah", stateAbbr: "UT", slug: "layton-ut", shortSlug: "layton" },
  { city: "Nampa", state: "Idaho", stateAbbr: "ID", slug: "nampa-id", shortSlug: "nampa" },
  { city: "Idaho Falls", state: "Idaho", stateAbbr: "ID", slug: "idaho-falls-id", shortSlug: "idaho-falls" },
  { city: "Pocatello", state: "Idaho", stateAbbr: "ID", slug: "pocatello-id", shortSlug: "pocatello" },
  { city: "Cedar Rapids", state: "Iowa", stateAbbr: "IA", slug: "cedar-rapids-ia", shortSlug: "cedar-rapids" },
  { city: "Davenport", state: "Iowa", stateAbbr: "IA", slug: "davenport-ia", shortSlug: "davenport" },
  { city: "Sioux City", state: "Iowa", stateAbbr: "IA", slug: "sioux-city-ia", shortSlug: "sioux-city" },
  { city: "Topeka", state: "Kansas", stateAbbr: "KS", slug: "topeka-ks", shortSlug: "topeka" },
  { city: "Olathe", state: "Kansas", stateAbbr: "KS", slug: "olathe-ks", shortSlug: "olathe" },
  { city: "Fargo", state: "North Dakota", stateAbbr: "ND", slug: "fargo-nd", shortSlug: "fargo" },
  { city: "Bismarck", state: "North Dakota", stateAbbr: "ND", slug: "bismarck-nd", shortSlug: "bismarck" },
  { city: "Billings", state: "Montana", stateAbbr: "MT", slug: "billings-mt", shortSlug: "billings" },
  { city: "Missoula", state: "Montana", stateAbbr: "MT", slug: "missoula-mt", shortSlug: "missoula" },
  { city: "Cheyenne", state: "Wyoming", stateAbbr: "WY", slug: "cheyenne-wy", shortSlug: "cheyenne" },
  { city: "Casper", state: "Wyoming", stateAbbr: "WY", slug: "casper-wy", shortSlug: "casper" },
  { city: "Burlington", state: "Vermont", stateAbbr: "VT", slug: "burlington-vt", shortSlug: "burlington-vt" },
  { city: "Manchester", state: "New Hampshire", stateAbbr: "NH", slug: "manchester-nh", shortSlug: "manchester" },
];

// --- Slug generators ---

// Industry page: /industry/crm-for-cleaning-service-businesses
export function generateIndustrySlug(industry: ComboIndustry): string {
  return `crm-for-${industry.slug.replace(/-services$/, "-service").replace(/-s$/, "")}-businesses`;
}

// Location page: /location/home-service-crm-in-dallas-tx
export function generateLocationSlug(metro: ComboMetro): string {
  return `home-service-crm-in-${metro.shortSlug}`;
}

// Combo page: /crm-for-cleaning-businesses-in-dallas-tx
export function generateComboSlug(industry: ComboIndustry, metro: ComboMetro): string {
  return `crm-for-${industry.slug.replace(/-services$/, "").replace(/-service$/, "")}-businesses-in-${metro.shortSlug}`;
}

export function getAllCombos(): Combo[] {
  const combos: Combo[] = [];
  for (const industry of industries) {
    for (const metro of metros) {
      combos.push({
        industry,
        metro,
        slug: generateComboSlug(industry, metro),
      });
    }
  }
  return combos;
}

export function findCombo(slug: string): { industry: ComboIndustry; metro: ComboMetro } | null {
  // Format: crm-for-{industry}-businesses-in-{metro-slug}
  const prefix = "crm-for-";
  const businessesIn = "-businesses-in-";

  if (!slug.startsWith(prefix)) return null;
  const bizIdx = slug.indexOf(businessesIn);
  if (bizIdx === -1) return null;

  const industryPart = slug.substring(prefix.length, bizIdx);
  const metroSlug = slug.substring(bizIdx + businessesIn.length);

  // Match industry: try exact, then with -services, then with -service suffix
  const industry = industries.find(
    (i) =>
      i.slug === industryPart ||
      i.slug === `${industryPart}-services` ||
      i.slug === `${industryPart}-service` ||
      i.slug.replace(/-services$/, "").replace(/-service$/, "") === industryPart
  );
  const metro = metros.find((m) => m.shortSlug === metroSlug);

  if (!industry || !metro) return null;

  return { industry, metro };
}

// Find industry from industry page slug
export function findIndustryByPageSlug(slug: string): ComboIndustry | null {
  // Format: crm-for-{industry}-businesses
  const prefix = "crm-for-";
  const suffix = "-businesses";
  if (!slug.startsWith(prefix) || !slug.endsWith(suffix)) return null;
  const industryPart = slug.slice(prefix.length, -suffix.length);
  return industries.find(
    (i) =>
      i.slug === industryPart ||
      i.slug === `${industryPart}s` ||
      i.slug === `${industryPart}-services` ||
      i.slug === `${industryPart}-service` ||
      i.slug.replace(/-services$/, "-service").replace(/-s$/, "") === industryPart
  ) ?? null;
}

// Find metro from location page slug
export function findMetroByPageSlug(slug: string): ComboMetro | null {
  // Format: home-service-crm-in-{metro-slug}
  const prefix = "home-service-crm-in-";
  if (!slug.startsWith(prefix)) return null;
  const metroSlug = slug.slice(prefix.length);
  return metros.find((m) => m.shortSlug === metroSlug) ?? null;
}
