export interface CityData {
  name: string
  slug: string
  state: string
  stateAbbr: string
  population: string
  description: string
}

export const cities: CityData[] = [
  // Northeast
  { name: 'New York', slug: 'new-york', state: 'New York', stateAbbr: 'NY', population: '8.3M', description: 'The largest US metro with massive demand across all home service trades.' },
  { name: 'Boston', slug: 'boston', state: 'Massachusetts', stateAbbr: 'MA', population: '4.9M', description: 'Dense metro with high-income homeowners and strong demand for premium services.' },
  { name: 'Philadelphia', slug: 'philadelphia', state: 'Pennsylvania', stateAbbr: 'PA', population: '6.2M', description: 'Large metro area spanning PA, NJ, and DE with diverse service needs.' },
  { name: 'Pittsburgh', slug: 'pittsburgh', state: 'Pennsylvania', stateAbbr: 'PA', population: '2.4M', description: 'Growing metro with older housing stock driving renovation and maintenance demand.' },
  { name: 'Hartford', slug: 'hartford', state: 'Connecticut', stateAbbr: 'CT', population: '1.2M', description: 'Affluent suburbs with strong demand for landscaping and home maintenance.' },
  { name: 'Providence', slug: 'providence', state: 'Rhode Island', stateAbbr: 'RI', population: '1.6M', description: 'Compact metro spanning RI and MA with growing home service demand.' },
  { name: 'Newark', slug: 'newark', state: 'New Jersey', stateAbbr: 'NJ', population: '2.3M', description: 'Dense suburban metro adjacent to NYC with strong residential demand.' },
  { name: 'Buffalo', slug: 'buffalo', state: 'New York', stateAbbr: 'NY', population: '1.2M', description: 'Western NY metro with seasonal service demand and growing renovation market.' },
  { name: 'Albany', slug: 'albany', state: 'New York', stateAbbr: 'NY', population: '900K', description: 'Capital district metro with steady demand for residential and commercial services.' },
  { name: 'Rochester', slug: 'rochester', state: 'New York', stateAbbr: 'NY', population: '1.1M', description: 'Upstate NY metro with older homes and strong demand for maintenance services.' },
  { name: 'Syracuse', slug: 'syracuse', state: 'New York', stateAbbr: 'NY', population: '660K', description: 'Central NY metro with seasonal service demands and university-area housing.' },
  { name: 'Bridgeport', slug: 'bridgeport', state: 'Connecticut', stateAbbr: 'CT', population: '950K', description: 'Coastal CT metro with affluent communities and strong cleaning demand.' },
  { name: 'New Haven', slug: 'new-haven', state: 'Connecticut', stateAbbr: 'CT', population: '860K', description: 'University city with mix of residential and commercial service needs.' },
  { name: 'Stamford', slug: 'stamford', state: 'Connecticut', stateAbbr: 'CT', population: '135K', description: 'Affluent Fairfield County city with premium home service demand.' },
  { name: 'Worcester', slug: 'worcester', state: 'Massachusetts', stateAbbr: 'MA', population: '950K', description: 'Central MA metro with growing population and diverse housing stock.' },
  { name: 'Springfield MA', slug: 'springfield-ma', state: 'Massachusetts', stateAbbr: 'MA', population: '700K', description: 'Western MA metro with steady residential service demand.' },
  { name: 'Manchester', slug: 'manchester-nh', state: 'New Hampshire', stateAbbr: 'NH', population: '415K', description: 'Southern NH metro with growing suburbs and strong home maintenance demand.' },
  { name: 'Portland ME', slug: 'portland-me', state: 'Maine', stateAbbr: 'ME', population: '550K', description: 'Coastal Maine metro with seasonal tourism driving cleaning and maintenance demand.' },
  { name: 'Burlington', slug: 'burlington', state: 'Vermont', stateAbbr: 'VT', population: '225K', description: 'Vermont metro with eco-conscious homeowners and seasonal service needs.' },
  { name: 'Allentown', slug: 'allentown', state: 'Pennsylvania', stateAbbr: 'PA', population: '850K', description: 'Lehigh Valley metro with growing residential areas and diverse service needs.' },
  { name: 'Scranton', slug: 'scranton', state: 'Pennsylvania', stateAbbr: 'PA', population: '570K', description: 'Northeastern PA metro with older housing stock driving renovation demand.' },
  { name: 'Harrisburg', slug: 'harrisburg', state: 'Pennsylvania', stateAbbr: 'PA', population: '580K', description: 'PA capital metro with steady residential and commercial service demand.' },
  { name: 'Trenton', slug: 'trenton', state: 'New Jersey', stateAbbr: 'NJ', population: '380K', description: 'Central NJ metro connecting NYC and Philadelphia service corridors.' },
  { name: 'Jersey City', slug: 'jersey-city', state: 'New Jersey', stateAbbr: 'NJ', population: '290K', description: 'Dense urban market across from Manhattan with high-rise and brownstone demand.' },

  // Southeast
  { name: 'Miami', slug: 'miami', state: 'Florida', stateAbbr: 'FL', population: '6.1M', description: 'Year-round demand for cleaning, pest control, pool service, and landscaping.' },
  { name: 'Tampa', slug: 'tampa', state: 'Florida', stateAbbr: 'FL', population: '3.2M', description: 'Fast-growing Gulf Coast metro with strong demand for outdoor and cleaning services.' },
  { name: 'Orlando', slug: 'orlando', state: 'Florida', stateAbbr: 'FL', population: '2.7M', description: 'Rapidly expanding metro with booming residential construction and maintenance needs.' },
  { name: 'Jacksonville', slug: 'jacksonville', state: 'Florida', stateAbbr: 'FL', population: '1.6M', description: 'Sprawling metro with growing suburbs creating new demand for home services.' },
  { name: 'Fort Lauderdale', slug: 'fort-lauderdale', state: 'Florida', stateAbbr: 'FL', population: '1.9M', description: 'South Florida metro with year-round pool, pest, and cleaning demand.' },
  { name: 'West Palm Beach', slug: 'west-palm-beach', state: 'Florida', stateAbbr: 'FL', population: '1.5M', description: 'Affluent South Florida market with premium home service demand.' },
  { name: 'St. Petersburg', slug: 'st-petersburg', state: 'Florida', stateAbbr: 'FL', population: '265K', description: 'Tampa Bay city with growing demand for cleaning and outdoor services.' },
  { name: 'Cape Coral', slug: 'cape-coral', state: 'Florida', stateAbbr: 'FL', population: '220K', description: 'Southwest Florida city with strong pool service and landscaping demand.' },
  { name: 'Sarasota', slug: 'sarasota', state: 'Florida', stateAbbr: 'FL', population: '840K', description: 'Gulf Coast metro with retiree population driving premium service demand.' },
  { name: 'Tallahassee', slug: 'tallahassee', state: 'Florida', stateAbbr: 'FL', population: '390K', description: 'FL capital with university and government-driven service demand.' },
  { name: 'Pensacola', slug: 'pensacola', state: 'Florida', stateAbbr: 'FL', population: '510K', description: 'Florida panhandle metro with coastal maintenance and military base demand.' },
  { name: 'Gainesville FL', slug: 'gainesville-fl', state: 'Florida', stateAbbr: 'FL', population: '340K', description: 'University of Florida metro with strong move-in/out cleaning demand.' },
  { name: 'Atlanta', slug: 'atlanta', state: 'Georgia', stateAbbr: 'GA', population: '6.1M', description: 'One of the fastest-growing metros with exploding demand for all trades.' },
  { name: 'Charlotte', slug: 'charlotte', state: 'North Carolina', stateAbbr: 'NC', population: '2.7M', description: 'Booming metro with new construction and high demand for cleaning and landscaping.' },
  { name: 'Raleigh', slug: 'raleigh', state: 'North Carolina', stateAbbr: 'NC', population: '1.5M', description: 'Research Triangle area with tech-savvy homeowners and growing populations.' },
  { name: 'Nashville', slug: 'nashville', state: 'Tennessee', stateAbbr: 'TN', population: '2M', description: 'Explosive growth creating demand for every category of home service.' },
  { name: 'Memphis', slug: 'memphis', state: 'Tennessee', stateAbbr: 'TN', population: '1.3M', description: 'Established metro with steady demand for residential and commercial services.' },
  { name: 'Richmond', slug: 'richmond', state: 'Virginia', stateAbbr: 'VA', population: '1.3M', description: 'Historic metro with older homes driving strong renovation and maintenance demand.' },
  { name: 'Washington DC', slug: 'washington-dc', state: 'District of Columbia', stateAbbr: 'DC', population: '6.3M', description: 'High-income metro spanning DC, MD, and VA with premium service demand.' },
  { name: 'New Orleans', slug: 'new-orleans', state: 'Louisiana', stateAbbr: 'LA', population: '1.3M', description: 'Unique market with year-round pest control, humidity-related cleaning, and restoration demand.' },
  { name: 'Charleston', slug: 'charleston', state: 'South Carolina', stateAbbr: 'SC', population: '800K', description: 'Growing coastal metro with strong demand for cleaning and outdoor services.' },
  { name: 'Savannah', slug: 'savannah', state: 'Georgia', stateAbbr: 'GA', population: '400K', description: 'Historic coastal city with unique maintenance needs and growing population.' },
  { name: 'Durham', slug: 'durham', state: 'North Carolina', stateAbbr: 'NC', population: '330K', description: 'Research Triangle city with strong tech-sector driven home service demand.' },
  { name: 'Greensboro', slug: 'greensboro', state: 'North Carolina', stateAbbr: 'NC', population: '930K', description: 'Piedmont Triad metro with steady residential service demand.' },
  { name: 'Winston-Salem', slug: 'winston-salem', state: 'North Carolina', stateAbbr: 'NC', population: '680K', description: 'Growing NC metro with expanding suburbs and renovation demand.' },
  { name: 'Wilmington NC', slug: 'wilmington-nc', state: 'North Carolina', stateAbbr: 'NC', population: '300K', description: 'Coastal NC city with tourism and humidity-driven cleaning demand.' },
  { name: 'Asheville', slug: 'asheville', state: 'North Carolina', stateAbbr: 'NC', population: '470K', description: 'Mountain metro with vacation rental and premium home service demand.' },
  { name: 'Columbia SC', slug: 'columbia-sc', state: 'South Carolina', stateAbbr: 'SC', population: '850K', description: 'SC capital metro with university and government service demand.' },
  { name: 'Greenville SC', slug: 'greenville-sc', state: 'South Carolina', stateAbbr: 'SC', population: '950K', description: 'Fast-growing Upstate SC metro with expanding residential areas.' },
  { name: 'Myrtle Beach', slug: 'myrtle-beach', state: 'South Carolina', stateAbbr: 'SC', population: '500K', description: 'Coastal resort area with vacation rental cleaning and maintenance demand.' },
  { name: 'Augusta', slug: 'augusta', state: 'Georgia', stateAbbr: 'GA', population: '620K', description: 'Georgia-South Carolina border metro with military base and residential demand.' },
  { name: 'Chattanooga', slug: 'chattanooga', state: 'Tennessee', stateAbbr: 'TN', population: '580K', description: 'Growing TN metro with revitalized downtown and expanding suburbs.' },
  { name: 'Knoxville', slug: 'knoxville', state: 'Tennessee', stateAbbr: 'TN', population: '900K', description: 'East Tennessee metro with growing population and strong service demand.' },
  { name: 'Virginia Beach', slug: 'virginia-beach', state: 'Virginia', stateAbbr: 'VA', population: '1.8M', description: 'Hampton Roads metro with military bases and growing residential demand.' },
  { name: 'Norfolk', slug: 'norfolk', state: 'Virginia', stateAbbr: 'VA', population: '245K', description: 'Major Navy base city with strong residential and commercial service needs.' },
  { name: 'Lexington', slug: 'lexington', state: 'Kentucky', stateAbbr: 'KY', population: '520K', description: 'Central KY metro with university-driven demand and horse country estates.' },
  { name: 'Louisville', slug: 'louisville', state: 'Kentucky', stateAbbr: 'KY', population: '1.3M', description: 'Kentucky\'s largest metro with steady residential and commercial demand.' },
  { name: 'Birmingham', slug: 'birmingham', state: 'Alabama', stateAbbr: 'AL', population: '1.1M', description: 'Alabama\'s largest metro with year-round demand for cleaning and outdoor services.' },
  { name: 'Huntsville', slug: 'huntsville', state: 'Alabama', stateAbbr: 'AL', population: '500K', description: 'Fastest-growing AL metro with tech sector driving premium service demand.' },
  { name: 'Montgomery', slug: 'montgomery', state: 'Alabama', stateAbbr: 'AL', population: '390K', description: 'AL capital with military base and steady residential demand.' },
  { name: 'Mobile', slug: 'mobile', state: 'Alabama', stateAbbr: 'AL', population: '430K', description: 'Gulf Coast AL metro with humidity-driven cleaning and pest control demand.' },
  { name: 'Jackson MS', slug: 'jackson-ms', state: 'Mississippi', stateAbbr: 'MS', population: '590K', description: 'MS capital metro with growing suburbs and residential service demand.' },
  { name: 'Baton Rouge', slug: 'baton-rouge', state: 'Louisiana', stateAbbr: 'LA', population: '870K', description: 'LA capital with university-driven demand and year-round outdoor service needs.' },
  { name: 'Shreveport', slug: 'shreveport', state: 'Louisiana', stateAbbr: 'LA', population: '440K', description: 'Northwest LA metro with steady residential service demand.' },
  { name: 'Little Rock', slug: 'little-rock', state: 'Arkansas', stateAbbr: 'AR', population: '750K', description: 'AR capital metro with growing suburbs and diverse home service needs.' },
  { name: 'Fayetteville AR', slug: 'fayetteville-ar', state: 'Arkansas', stateAbbr: 'AR', population: '580K', description: 'Northwest AR boom town with rapid residential growth.' },

  // Midwest
  { name: 'Chicago', slug: 'chicago', state: 'Illinois', stateAbbr: 'IL', population: '9.5M', description: 'Third-largest metro with massive demand across all home service categories.' },
  { name: 'Detroit', slug: 'detroit', state: 'Michigan', stateAbbr: 'MI', population: '4.3M', description: 'Large metro with strong seasonal demand and growing renovation market.' },
  { name: 'Minneapolis', slug: 'minneapolis', state: 'Minnesota', stateAbbr: 'MN', population: '3.7M', description: 'Twin Cities metro with strong demand for seasonal services and home maintenance.' },
  { name: 'St. Louis', slug: 'st-louis', state: 'Missouri', stateAbbr: 'MO', population: '2.8M', description: 'Bi-state metro with diverse housing stock and steady service demand.' },
  { name: 'Kansas City', slug: 'kansas-city', state: 'Missouri', stateAbbr: 'MO', population: '2.2M', description: 'Growing metro spanning MO and KS with expanding suburbs and service demand.' },
  { name: 'Columbus', slug: 'columbus', state: 'Ohio', stateAbbr: 'OH', population: '2.1M', description: 'Fast-growing Ohio metro with strong residential cleaning and landscaping demand.' },
  { name: 'Cleveland', slug: 'cleveland', state: 'Ohio', stateAbbr: 'OH', population: '2M', description: 'Established metro with older housing stock driving maintenance and repair demand.' },
  { name: 'Cincinnati', slug: 'cincinnati', state: 'Ohio', stateAbbr: 'OH', population: '2.3M', description: 'Tri-state metro spanning OH, KY, and IN with diverse service needs.' },
  { name: 'Indianapolis', slug: 'indianapolis', state: 'Indiana', stateAbbr: 'IN', population: '2.1M', description: 'Central Indiana metro with growing suburbs and steady home service demand.' },
  { name: 'Milwaukee', slug: 'milwaukee', state: 'Wisconsin', stateAbbr: 'WI', population: '1.6M', description: 'Lake Michigan metro with strong seasonal demand and older housing stock.' },
  { name: 'Omaha', slug: 'omaha', state: 'Nebraska', stateAbbr: 'NE', population: '970K', description: 'Growing Midwest metro with expanding residential areas and service demand.' },
  { name: 'Des Moines', slug: 'des-moines', state: 'Iowa', stateAbbr: 'IA', population: '700K', description: 'Central Iowa metro with steady growth and strong home maintenance demand.' },
  { name: 'Madison', slug: 'madison', state: 'Wisconsin', stateAbbr: 'WI', population: '680K', description: 'WI capital with university-driven demand and growing tech sector.' },
  { name: 'Grand Rapids', slug: 'grand-rapids', state: 'Michigan', stateAbbr: 'MI', population: '1.1M', description: 'West Michigan metro with growing population and strong renovation demand.' },
  { name: 'Ann Arbor', slug: 'ann-arbor', state: 'Michigan', stateAbbr: 'MI', population: '380K', description: 'University of Michigan city with high-income households and strong service demand.' },
  { name: 'Lansing', slug: 'lansing', state: 'Michigan', stateAbbr: 'MI', population: '480K', description: 'MI capital metro with university and government-driven demand.' },
  { name: 'Dayton', slug: 'dayton', state: 'Ohio', stateAbbr: 'OH', population: '810K', description: 'Southwest Ohio metro with affordable housing driving maintenance demand.' },
  { name: 'Akron', slug: 'akron', state: 'Ohio', stateAbbr: 'OH', population: '700K', description: 'Northeast Ohio metro with older housing and steady service needs.' },
  { name: 'Toledo', slug: 'toledo', state: 'Ohio', stateAbbr: 'OH', population: '640K', description: 'Northwest Ohio metro with seasonal service demand and renovation opportunities.' },
  { name: 'Fort Wayne', slug: 'fort-wayne', state: 'Indiana', stateAbbr: 'IN', population: '430K', description: 'Northeast Indiana metro with growing suburbs and affordable housing market.' },
  { name: 'South Bend', slug: 'south-bend', state: 'Indiana', stateAbbr: 'IN', population: '325K', description: 'Notre Dame area with university-driven cleaning and maintenance demand.' },
  { name: 'Evansville', slug: 'evansville', state: 'Indiana', stateAbbr: 'IN', population: '315K', description: 'Southern Indiana tri-state metro with steady residential service demand.' },
  { name: 'Springfield IL', slug: 'springfield-il', state: 'Illinois', stateAbbr: 'IL', population: '210K', description: 'IL capital with government and residential service demand.' },
  { name: 'Peoria', slug: 'peoria', state: 'Illinois', stateAbbr: 'IL', population: '405K', description: 'Central Illinois metro with diverse housing and service needs.' },
  { name: 'Rockford', slug: 'rockford', state: 'Illinois', stateAbbr: 'IL', population: '340K', description: 'Northern Illinois metro with affordable housing and renovation demand.' },
  { name: 'Cedar Rapids', slug: 'cedar-rapids', state: 'Iowa', stateAbbr: 'IA', population: '275K', description: 'Eastern Iowa metro with strong residential service demand.' },
  { name: 'Davenport', slug: 'davenport', state: 'Iowa', stateAbbr: 'IA', population: '385K', description: 'Quad Cities metro spanning Iowa and Illinois with steady demand.' },
  { name: 'Wichita', slug: 'wichita', state: 'Kansas', stateAbbr: 'KS', population: '650K', description: 'Kansas\'s largest metro with growing suburbs and diverse service needs.' },
  { name: 'Lincoln', slug: 'lincoln', state: 'Nebraska', stateAbbr: 'NE', population: '340K', description: 'NE capital with university-driven demand and growing residential areas.' },
  { name: 'Sioux Falls', slug: 'sioux-falls', state: 'South Dakota', stateAbbr: 'SD', population: '290K', description: 'Fastest-growing SD metro with booming residential construction.' },
  { name: 'Fargo', slug: 'fargo', state: 'North Dakota', stateAbbr: 'ND', population: '260K', description: 'Growing ND-MN metro with strong seasonal service demand.' },
  { name: 'Duluth', slug: 'duluth', state: 'Minnesota', stateAbbr: 'MN', population: '290K', description: 'Northern MN port city with seasonal demand and tourism-driven services.' },
  { name: 'Rochester MN', slug: 'rochester-mn', state: 'Minnesota', stateAbbr: 'MN', population: '225K', description: 'Mayo Clinic city with high-income households and premium service demand.' },
  { name: 'Green Bay', slug: 'green-bay', state: 'Wisconsin', stateAbbr: 'WI', population: '325K', description: 'Northeast WI metro with strong seasonal service and maintenance demand.' },

  // Southwest
  { name: 'Dallas', slug: 'dallas', state: 'Texas', stateAbbr: 'TX', population: '7.6M', description: 'Massive metro with year-round demand and explosive population growth.' },
  { name: 'Houston', slug: 'houston', state: 'Texas', stateAbbr: 'TX', population: '7.1M', description: 'Fourth-largest US metro with year-round demand for every home service trade.' },
  { name: 'San Antonio', slug: 'san-antonio', state: 'Texas', stateAbbr: 'TX', population: '2.6M', description: 'Fast-growing South Texas metro with strong demand for cleaning and outdoor services.' },
  { name: 'Austin', slug: 'austin', state: 'Texas', stateAbbr: 'TX', population: '2.3M', description: 'One of America\'s fastest-growing metros with booming new construction and service needs.' },
  { name: 'Fort Worth', slug: 'fort-worth', state: 'Texas', stateAbbr: 'TX', population: '2.5M', description: 'Western DFW metro with rapid suburban growth and family-oriented service demand.' },
  { name: 'El Paso', slug: 'el-paso', state: 'Texas', stateAbbr: 'TX', population: '870K', description: 'Border metro with bilingual demand for home services.' },
  { name: 'McAllen', slug: 'mcallen', state: 'Texas', stateAbbr: 'TX', population: '950K', description: 'Rio Grande Valley metro with bilingual market and growing residential demand.' },
  { name: 'Corpus Christi', slug: 'corpus-christi', state: 'Texas', stateAbbr: 'TX', population: '480K', description: 'Coastal Texas metro with humidity-driven cleaning and pest control demand.' },
  { name: 'Lubbock', slug: 'lubbock', state: 'Texas', stateAbbr: 'TX', population: '320K', description: 'West Texas university city with growing residential service market.' },
  { name: 'Amarillo', slug: 'amarillo', state: 'Texas', stateAbbr: 'TX', population: '270K', description: 'Texas Panhandle metro with seasonal HVAC and maintenance demand.' },
  { name: 'Midland-Odessa', slug: 'midland-odessa', state: 'Texas', stateAbbr: 'TX', population: '340K', description: 'Permian Basin metro with energy sector driving premium service demand.' },
  { name: 'Waco', slug: 'waco', state: 'Texas', stateAbbr: 'TX', population: '280K', description: 'Central Texas metro with renovation boom and growing residential market.' },
  { name: 'Killeen', slug: 'killeen', state: 'Texas', stateAbbr: 'TX', population: '470K', description: 'Central Texas military metro with Fort Cavazos driving service demand.' },
  { name: 'Tyler', slug: 'tyler', state: 'Texas', stateAbbr: 'TX', population: '235K', description: 'East Texas metro with growing residential areas and service needs.' },
  { name: 'Beaumont', slug: 'beaumont', state: 'Texas', stateAbbr: 'TX', population: '400K', description: 'Southeast Texas metro with humidity-driven cleaning and maintenance demand.' },
  { name: 'Phoenix', slug: 'phoenix', state: 'Arizona', stateAbbr: 'AZ', population: '4.9M', description: 'Year-round warm weather drives constant demand for pool, pest, and outdoor services.' },
  { name: 'Scottsdale', slug: 'scottsdale', state: 'Arizona', stateAbbr: 'AZ', population: '260K', description: 'Luxury market with premium service demand for cleaning, landscaping, and pool care.' },
  { name: 'Tucson', slug: 'tucson', state: 'Arizona', stateAbbr: 'AZ', population: '1M', description: 'Southern Arizona metro with strong demand for HVAC, pest control, and landscaping.' },
  { name: 'Mesa', slug: 'mesa', state: 'Arizona', stateAbbr: 'AZ', population: '520K', description: 'East Valley Phoenix suburb with strong residential service demand.' },
  { name: 'Chandler', slug: 'chandler', state: 'Arizona', stateAbbr: 'AZ', population: '280K', description: 'Fast-growing Phoenix suburb with tech sector and family-oriented demand.' },
  { name: 'Gilbert', slug: 'gilbert', state: 'Arizona', stateAbbr: 'AZ', population: '275K', description: 'Rapidly growing East Valley suburb with new construction demand.' },
  { name: 'Flagstaff', slug: 'flagstaff', state: 'Arizona', stateAbbr: 'AZ', population: '75K', description: 'Northern AZ mountain city with seasonal demand and university market.' },
  { name: 'Las Vegas', slug: 'las-vegas', state: 'Nevada', stateAbbr: 'NV', population: '2.3M', description: 'Fast-growing desert metro with strong demand for cleaning, pool, and HVAC services.' },
  { name: 'Reno', slug: 'reno', state: 'Nevada', stateAbbr: 'NV', population: '490K', description: 'Northern Nevada metro with growing tech sector and residential service demand.' },
  { name: 'Albuquerque', slug: 'albuquerque', state: 'New Mexico', stateAbbr: 'NM', population: '900K', description: 'New Mexico\'s largest metro with growing residential service demand.' },
  { name: 'Santa Fe', slug: 'santa-fe', state: 'New Mexico', stateAbbr: 'NM', population: '150K', description: 'High-end market with premium home maintenance and cleaning demand.' },
  { name: 'Las Cruces', slug: 'las-cruces', state: 'New Mexico', stateAbbr: 'NM', population: '220K', description: 'Southern NM metro with university and military-driven service demand.' },
  { name: 'Oklahoma City', slug: 'oklahoma-city', state: 'Oklahoma', stateAbbr: 'OK', population: '1.4M', description: 'Central Oklahoma metro with expanding suburbs and growing home service market.' },
  { name: 'Tulsa', slug: 'tulsa', state: 'Oklahoma', stateAbbr: 'OK', population: '1M', description: 'Eastern Oklahoma metro with steady residential service demand.' },

  // West Coast
  { name: 'Los Angeles', slug: 'los-angeles', state: 'California', stateAbbr: 'CA', population: '13.2M', description: 'Largest West Coast metro with massive demand across all home service trades.' },
  { name: 'San Francisco', slug: 'san-francisco', state: 'California', stateAbbr: 'CA', population: '4.7M', description: 'High-income Bay Area metro with premium demand for cleaning and home services.' },
  { name: 'San Diego', slug: 'san-diego', state: 'California', stateAbbr: 'CA', population: '3.3M', description: 'Year-round temperate climate drives consistent demand for outdoor and cleaning services.' },
  { name: 'San Jose', slug: 'san-jose', state: 'California', stateAbbr: 'CA', population: '2M', description: 'Silicon Valley metro with tech-savvy homeowners and premium service expectations.' },
  { name: 'Sacramento', slug: 'sacramento', state: 'California', stateAbbr: 'CA', population: '2.4M', description: 'California\'s capital with growing suburbs and strong residential service demand.' },
  { name: 'Riverside', slug: 'riverside', state: 'California', stateAbbr: 'CA', population: '4.6M', description: 'Inland Empire metro with massive suburban sprawl and growing service demand.' },
  { name: 'Fresno', slug: 'fresno', state: 'California', stateAbbr: 'CA', population: '1.1M', description: 'Central Valley metro with growing residential areas and strong service needs.' },
  { name: 'Bakersfield', slug: 'bakersfield', state: 'California', stateAbbr: 'CA', population: '910K', description: 'Southern Central Valley metro with hot climate driving HVAC and pool demand.' },
  { name: 'Stockton', slug: 'stockton', state: 'California', stateAbbr: 'CA', population: '780K', description: 'Central Valley metro with growing population and affordable housing market.' },
  { name: 'Modesto', slug: 'modesto', state: 'California', stateAbbr: 'CA', population: '560K', description: 'Northern Central Valley metro with agricultural community and residential growth.' },
  { name: 'Oxnard', slug: 'oxnard', state: 'California', stateAbbr: 'CA', population: '850K', description: 'Ventura County metro with coastal homes and year-round service demand.' },
  { name: 'Santa Barbara', slug: 'santa-barbara', state: 'California', stateAbbr: 'CA', population: '450K', description: 'Premium coastal market with affluent homeowners and high service expectations.' },
  { name: 'Santa Rosa', slug: 'santa-rosa', state: 'California', stateAbbr: 'CA', population: '500K', description: 'Sonoma County metro with wine country estates and premium service demand.' },
  { name: 'Salinas', slug: 'salinas', state: 'California', stateAbbr: 'CA', population: '440K', description: 'Monterey Bay area metro with agricultural and residential service needs.' },
  { name: 'Visalia', slug: 'visalia', state: 'California', stateAbbr: 'CA', population: '470K', description: 'Southern Central Valley metro with growing residential market.' },
  { name: 'Palm Springs', slug: 'palm-springs', state: 'California', stateAbbr: 'CA', population: '490K', description: 'Desert resort market with pool service, HVAC, and premium cleaning demand.' },
  { name: 'Long Beach', slug: 'long-beach', state: 'California', stateAbbr: 'CA', population: '470K', description: 'Coastal LA County city with diverse residential service needs.' },
  { name: 'Oakland', slug: 'oakland', state: 'California', stateAbbr: 'CA', population: '440K', description: 'East Bay city with diverse housing stock and strong cleaning demand.' },
  { name: 'Irvine', slug: 'irvine', state: 'California', stateAbbr: 'CA', population: '310K', description: 'Orange County planned community with premium home service expectations.' },
  { name: 'Anaheim', slug: 'anaheim', state: 'California', stateAbbr: 'CA', population: '350K', description: 'Orange County city with tourism-adjacent residential demand.' },
  { name: 'Seattle', slug: 'seattle', state: 'Washington', stateAbbr: 'WA', population: '4M', description: 'Tech hub with high-income residents and strong demand for cleaning and home services.' },
  { name: 'Portland', slug: 'portland', state: 'Oregon', stateAbbr: 'OR', population: '2.5M', description: 'Eco-conscious metro with demand for green cleaning and sustainable home services.' },
  { name: 'Tacoma', slug: 'tacoma', state: 'Washington', stateAbbr: 'WA', population: '920K', description: 'South Puget Sound metro with growing residential demand.' },
  { name: 'Spokane', slug: 'spokane', state: 'Washington', stateAbbr: 'WA', population: '590K', description: 'Eastern WA metro with seasonal demand and growing residential areas.' },
  { name: 'Vancouver WA', slug: 'vancouver-wa', state: 'Washington', stateAbbr: 'WA', population: '510K', description: 'Portland-adjacent metro with growing population and no state income tax.' },
  { name: 'Olympia', slug: 'olympia', state: 'Washington', stateAbbr: 'WA', population: '300K', description: 'WA capital metro with government and residential service demand.' },
  { name: 'Bellingham', slug: 'bellingham', state: 'Washington', stateAbbr: 'WA', population: '230K', description: 'Northwest WA university city with eco-conscious service demand.' },
  { name: 'Eugene', slug: 'eugene', state: 'Oregon', stateAbbr: 'OR', population: '380K', description: 'University of Oregon city with eco-friendly service preferences.' },
  { name: 'Salem', slug: 'salem', state: 'Oregon', stateAbbr: 'OR', population: '430K', description: 'OR capital metro with steady residential service demand.' },
  { name: 'Bend', slug: 'bend', state: 'Oregon', stateAbbr: 'OR', population: '210K', description: 'Fast-growing Central Oregon metro with outdoor lifestyle and premium services.' },
  { name: 'Medford', slug: 'medford', state: 'Oregon', stateAbbr: 'OR', population: '225K', description: 'Southern Oregon metro with growing residential and retiree demand.' },

  // Mountain West
  { name: 'Denver', slug: 'denver', state: 'Colorado', stateAbbr: 'CO', population: '2.9M', description: 'Fast-growing Front Range metro with strong demand across all service categories.' },
  { name: 'Colorado Springs', slug: 'colorado-springs', state: 'Colorado', stateAbbr: 'CO', population: '750K', description: 'Military and tech-driven metro with growing residential demand.' },
  { name: 'Fort Collins', slug: 'fort-collins', state: 'Colorado', stateAbbr: 'CO', population: '370K', description: 'Northern Colorado university city with growing suburbs and eco-conscious demand.' },
  { name: 'Boulder', slug: 'boulder', state: 'Colorado', stateAbbr: 'CO', population: '330K', description: 'Affluent university metro with premium and eco-friendly service demand.' },
  { name: 'Pueblo', slug: 'pueblo', state: 'Colorado', stateAbbr: 'CO', population: '170K', description: 'Southern Colorado city with affordable housing and steady service demand.' },
  { name: 'Salt Lake City', slug: 'salt-lake-city', state: 'Utah', stateAbbr: 'UT', population: '1.3M', description: 'Growing Wasatch Front metro with expanding suburbs and strong family-oriented demand.' },
  { name: 'Provo', slug: 'provo', state: 'Utah', stateAbbr: 'UT', population: '680K', description: 'Utah Valley metro with young families and fast-growing residential areas.' },
  { name: 'Ogden', slug: 'ogden', state: 'Utah', stateAbbr: 'UT', population: '700K', description: 'Northern Wasatch Front metro with growing suburbs and outdoor service demand.' },
  { name: 'St. George', slug: 'st-george', state: 'Utah', stateAbbr: 'UT', population: '190K', description: 'Fastest-growing UT metro with retiree and vacation home demand.' },
  { name: 'Boise', slug: 'boise', state: 'Idaho', stateAbbr: 'ID', population: '770K', description: 'One of America\'s fastest-growing metros with exploding residential service needs.' },
  { name: 'Idaho Falls', slug: 'idaho-falls', state: 'Idaho', stateAbbr: 'ID', population: '175K', description: 'Eastern Idaho metro with growing population and seasonal service demand.' },
  { name: 'Coeur d\'Alene', slug: 'coeur-d-alene', state: 'Idaho', stateAbbr: 'ID', population: '180K', description: 'Northern Idaho resort area with premium vacation home service demand.' },
  { name: 'Missoula', slug: 'missoula', state: 'Montana', stateAbbr: 'MT', population: '125K', description: 'Western Montana university city with growing population and service demand.' },
  { name: 'Billings', slug: 'billings', state: 'Montana', stateAbbr: 'MT', population: '185K', description: 'Montana\'s largest city with steady residential and commercial service needs.' },
  { name: 'Great Falls', slug: 'great-falls', state: 'Montana', stateAbbr: 'MT', population: '85K', description: 'Central Montana city with military base and seasonal service demand.' },
  { name: 'Cheyenne', slug: 'cheyenne', state: 'Wyoming', stateAbbr: 'WY', population: '100K', description: 'WY capital with military base and growing residential demand.' },
  { name: 'Casper', slug: 'casper', state: 'Wyoming', stateAbbr: 'WY', population: '80K', description: 'Central Wyoming city with energy sector and residential service needs.' },

  // Pacific
  { name: 'Honolulu', slug: 'honolulu', state: 'Hawaii', stateAbbr: 'HI', population: '1M', description: 'Island metro with year-round demand for cleaning, pest control, and maintenance.' },
  { name: 'Maui', slug: 'maui', state: 'Hawaii', stateAbbr: 'HI', population: '165K', description: 'Resort island with vacation rental cleaning and premium maintenance demand.' },
  { name: 'Anchorage', slug: 'anchorage', state: 'Alaska', stateAbbr: 'AK', population: '400K', description: 'Alaska\'s largest metro with unique seasonal service demand.' },
  { name: 'Fairbanks', slug: 'fairbanks', state: 'Alaska', stateAbbr: 'AK', population: '100K', description: 'Interior Alaska with extreme seasonal demand for HVAC and maintenance.' },

  // Additional major metros
  { name: 'Baltimore', slug: 'baltimore', state: 'Maryland', stateAbbr: 'MD', population: '2.8M', description: 'Major Mid-Atlantic metro with diverse housing stock and strong service demand.' },
  { name: 'Annapolis', slug: 'annapolis', state: 'Maryland', stateAbbr: 'MD', population: '590K', description: 'MD capital with affluent waterfront communities and premium service demand.' },
  { name: 'Frederick', slug: 'frederick', state: 'Maryland', stateAbbr: 'MD', population: '280K', description: 'Growing Western MD metro with expanding residential areas.' },
  { name: 'Wilmington DE', slug: 'wilmington-de', state: 'Delaware', stateAbbr: 'DE', population: '730K', description: 'Northern Delaware metro with corporate and residential service demand.' },
  { name: 'Dover', slug: 'dover', state: 'Delaware', stateAbbr: 'DE', population: '185K', description: 'DE capital with military base and growing residential demand.' },

  // Additional Southeast
  { name: 'Fort Myers', slug: 'fort-myers', state: 'Florida', stateAbbr: 'FL', population: '800K', description: 'Southwest Florida metro with strong pool, pest, and cleaning demand.' },
  { name: 'Ocala', slug: 'ocala', state: 'Florida', stateAbbr: 'FL', population: '390K', description: 'Central Florida metro with horse country estates and growing suburbs.' },
  { name: 'Lakeland', slug: 'lakeland', state: 'Florida', stateAbbr: 'FL', population: '740K', description: 'Central Florida metro between Tampa and Orlando with rapid residential growth.' },
  { name: 'Daytona Beach', slug: 'daytona-beach', state: 'Florida', stateAbbr: 'FL', population: '680K', description: 'Central Florida coast metro with tourism and residential demand.' },
  { name: 'Melbourne FL', slug: 'melbourne-fl', state: 'Florida', stateAbbr: 'FL', population: '620K', description: 'Space Coast metro with tech sector and year-round outdoor service demand.' },
  { name: 'Naples', slug: 'naples', state: 'Florida', stateAbbr: 'FL', population: '410K', description: 'Premium Southwest Florida market with luxury home service demand.' },
  { name: 'Athens', slug: 'athens', state: 'Georgia', stateAbbr: 'GA', population: '215K', description: 'University of Georgia city with student and residential service demand.' },
  { name: 'Macon', slug: 'macon', state: 'Georgia', stateAbbr: 'GA', population: '240K', description: 'Central Georgia metro with steady residential service needs.' },
  { name: 'Columbus GA', slug: 'columbus-ga', state: 'Georgia', stateAbbr: 'GA', population: '330K', description: 'Western Georgia metro with Fort Moore military base demand.' },

  // Additional Southwest/Texas
  { name: 'Brownsville', slug: 'brownsville', state: 'Texas', stateAbbr: 'TX', population: '430K', description: 'Rio Grande Valley border metro with bilingual service demand.' },
  { name: 'Laredo', slug: 'laredo', state: 'Texas', stateAbbr: 'TX', population: '275K', description: 'South Texas border city with growing residential service market.' },
  { name: 'College Station', slug: 'college-station', state: 'Texas', stateAbbr: 'TX', population: '270K', description: 'Texas A&M university metro with student and residential demand.' },
  { name: 'Abilene', slug: 'abilene', state: 'Texas', stateAbbr: 'TX', population: '175K', description: 'West Central Texas city with military base and residential service needs.' },
  { name: 'San Angelo', slug: 'san-angelo', state: 'Texas', stateAbbr: 'TX', population: '120K', description: 'West Texas city with steady residential and commercial service demand.' },

  // Additional Midwest
  { name: 'Topeka', slug: 'topeka', state: 'Kansas', stateAbbr: 'KS', population: '235K', description: 'KS capital with government and residential service demand.' },
  { name: 'Lawrence', slug: 'lawrence', state: 'Kansas', stateAbbr: 'KS', population: '125K', description: 'University of Kansas city with student housing and residential demand.' },
  { name: 'Springfield MO', slug: 'springfield-mo', state: 'Missouri', stateAbbr: 'MO', population: '470K', description: 'Southwest MO metro with growing suburbs and affordable housing market.' },
  { name: 'Columbia MO', slug: 'columbia-mo', state: 'Missouri', stateAbbr: 'MO', population: '210K', description: 'University of Missouri city with steady residential service demand.' },
  { name: 'Champaign', slug: 'champaign', state: 'Illinois', stateAbbr: 'IL', population: '240K', description: 'University of Illinois metro with student and residential service demand.' },
  { name: 'Bloomington IL', slug: 'bloomington-il', state: 'Illinois', stateAbbr: 'IL', population: '175K', description: 'Central Illinois metro with insurance industry and residential demand.' },
  { name: 'Appleton', slug: 'appleton', state: 'Wisconsin', stateAbbr: 'WI', population: '250K', description: 'Fox Valley WI metro with growing residential areas and service needs.' },
  { name: 'Eau Claire', slug: 'eau-claire', state: 'Wisconsin', stateAbbr: 'WI', population: '170K', description: 'Western WI university city with growing residential demand.' },
  { name: 'La Crosse', slug: 'la-crosse', state: 'Wisconsin', stateAbbr: 'WI', population: '140K', description: 'Western WI-MN border metro with steady service demand.' },
  { name: 'Kalamazoo', slug: 'kalamazoo', state: 'Michigan', stateAbbr: 'MI', population: '340K', description: 'Southwest Michigan metro with university and manufacturing sector demand.' },
  { name: 'Traverse City', slug: 'traverse-city', state: 'Michigan', stateAbbr: 'MI', population: '160K', description: 'Northern Michigan resort area with vacation home and seasonal demand.' },
  { name: 'Saginaw', slug: 'saginaw', state: 'Michigan', stateAbbr: 'MI', population: '375K', description: 'Mid-Michigan metro with affordable housing and renovation demand.' },
  { name: 'Flint', slug: 'flint', state: 'Michigan', stateAbbr: 'MI', population: '410K', description: 'Mid-Michigan metro with renovation and maintenance demand.' },
  { name: 'Youngstown', slug: 'youngstown', state: 'Ohio', stateAbbr: 'OH', population: '540K', description: 'Northeast Ohio-Western PA metro with affordable housing and service needs.' },
  { name: 'Canton', slug: 'canton', state: 'Ohio', stateAbbr: 'OH', population: '400K', description: 'Northeast Ohio metro with steady residential and commercial service demand.' },
  { name: 'Terre Haute', slug: 'terre-haute', state: 'Indiana', stateAbbr: 'IN', population: '170K', description: 'Western Indiana university city with residential service demand.' },
  { name: 'Bloomington IN', slug: 'bloomington-in', state: 'Indiana', stateAbbr: 'IN', population: '175K', description: 'Indiana University city with student housing and residential demand.' },
  { name: 'Rapid City', slug: 'rapid-city', state: 'South Dakota', stateAbbr: 'SD', population: '150K', description: 'Western SD metro with tourism and growing residential demand.' },
  { name: 'Bismarck', slug: 'bismarck', state: 'North Dakota', stateAbbr: 'ND', population: '135K', description: 'ND capital with energy sector and growing residential demand.' },
  { name: 'Grand Forks', slug: 'grand-forks', state: 'North Dakota', stateAbbr: 'ND', population: '105K', description: 'Northern ND university city with military base and residential demand.' },

  // Additional Mountain West
  { name: 'Grand Junction', slug: 'grand-junction', state: 'Colorado', stateAbbr: 'CO', population: '155K', description: 'Western Colorado metro with growing population and outdoor lifestyle.' },
  { name: 'Greeley', slug: 'greeley', state: 'Colorado', stateAbbr: 'CO', population: '330K', description: 'Northern Colorado metro with rapid residential growth and agricultural base.' },
  { name: 'Logan', slug: 'logan', state: 'Utah', stateAbbr: 'UT', population: '145K', description: 'Northern Utah university city with family-oriented service demand.' },
  { name: 'Twin Falls', slug: 'twin-falls', state: 'Idaho', stateAbbr: 'ID', population: '115K', description: 'Southern Idaho metro with growing agricultural and residential demand.' },
  { name: 'Pocatello', slug: 'pocatello', state: 'Idaho', stateAbbr: 'ID', population: '95K', description: 'Southeast Idaho university city with steady residential service demand.' },
  { name: 'Helena', slug: 'helena', state: 'Montana', stateAbbr: 'MT', population: '85K', description: 'MT capital with government workers and growing residential market.' },
  { name: 'Bozeman', slug: 'bozeman', state: 'Montana', stateAbbr: 'MT', population: '120K', description: 'Fastest-growing MT metro with outdoor lifestyle and premium service demand.' },

  // Additional West Coast
  { name: 'Redding', slug: 'redding', state: 'California', stateAbbr: 'CA', population: '180K', description: 'Northern California metro with hot summers driving HVAC and pool demand.' },
  { name: 'Chico', slug: 'chico', state: 'California', stateAbbr: 'CA', population: '225K', description: 'Northern California university metro with growing residential demand.' },
  { name: 'Eureka', slug: 'eureka', state: 'California', stateAbbr: 'CA', population: '135K', description: 'Coastal Northern California metro with unique climate and service needs.' },
  { name: 'San Luis Obispo', slug: 'san-luis-obispo', state: 'California', stateAbbr: 'CA', population: '285K', description: 'Central Coast metro with university and premium residential demand.' },
  { name: 'Santa Cruz', slug: 'santa-cruz', state: 'California', stateAbbr: 'CA', population: '270K', description: 'Coastal university metro with eco-conscious service preferences.' },
  { name: 'Merced', slug: 'merced', state: 'California', stateAbbr: 'CA', population: '285K', description: 'UC Merced metro with growing residential areas in the Central Valley.' },
  { name: 'El Centro', slug: 'el-centro', state: 'California', stateAbbr: 'CA', population: '180K', description: 'Imperial Valley metro with extreme heat driving HVAC demand.' },
  { name: 'Kennewick', slug: 'kennewick', state: 'Washington', stateAbbr: 'WA', population: '310K', description: 'Tri-Cities WA metro with growing tech and agricultural economy.' },
  { name: 'Yakima', slug: 'yakima', state: 'Washington', stateAbbr: 'WA', population: '255K', description: 'Central WA agricultural metro with bilingual service demand.' },
  { name: 'Wenatchee', slug: 'wenatchee', state: 'Washington', stateAbbr: 'WA', population: '120K', description: 'Central WA apple country with growing residential demand.' },
  { name: 'Corvallis', slug: 'corvallis', state: 'Oregon', stateAbbr: 'OR', population: '100K', description: 'Oregon State University city with eco-conscious residential demand.' },
  { name: 'Grants Pass', slug: 'grants-pass', state: 'Oregon', stateAbbr: 'OR', population: '90K', description: 'Southern Oregon metro with retiree and outdoor lifestyle demand.' },

  // Additional Southeast fill
  { name: 'Hilton Head', slug: 'hilton-head', state: 'South Carolina', stateAbbr: 'SC', population: '220K', description: 'Luxury resort island with vacation rental and premium service demand.' },
  { name: 'Florence SC', slug: 'florence-sc', state: 'South Carolina', stateAbbr: 'SC', population: '210K', description: 'Eastern SC metro with growing residential and commercial demand.' },
  { name: 'Tuscaloosa', slug: 'tuscaloosa', state: 'Alabama', stateAbbr: 'AL', population: '250K', description: 'University of Alabama city with student housing and residential demand.' },
  { name: 'Dothan', slug: 'dothan', state: 'Alabama', stateAbbr: 'AL', population: '150K', description: 'Southeast Alabama tri-state metro with steady residential demand.' },
  { name: 'Hattiesburg', slug: 'hattiesburg', state: 'Mississippi', stateAbbr: 'MS', population: '170K', description: 'Southern MS university city with growing residential areas.' },
  { name: 'Biloxi', slug: 'biloxi', state: 'Mississippi', stateAbbr: 'MS', population: '400K', description: 'Gulf Coast MS metro with tourism, military, and residential demand.' },
  { name: 'Lafayette', slug: 'lafayette', state: 'Louisiana', stateAbbr: 'LA', population: '500K', description: 'Acadiana metro with energy sector and unique cultural service demand.' },
  { name: 'Lake Charles', slug: 'lake-charles', state: 'Louisiana', stateAbbr: 'LA', population: '210K', description: 'Southwest LA metro with energy sector and hurricane recovery demand.' },
  { name: 'Monroe LA', slug: 'monroe-la', state: 'Louisiana', stateAbbr: 'LA', population: '180K', description: 'Northeast LA metro with steady residential and commercial demand.' },
  { name: 'Hot Springs', slug: 'hot-springs', state: 'Arkansas', stateAbbr: 'AR', population: '100K', description: 'AR resort city with tourism and retiree-driven service demand.' },
  { name: 'Jonesboro', slug: 'jonesboro', state: 'Arkansas', stateAbbr: 'AR', population: '135K', description: 'Northeast AR university city with growing residential demand.' },
  { name: 'Fort Smith', slug: 'fort-smith', state: 'Arkansas', stateAbbr: 'AR', population: '280K', description: 'Western AR metro on the OK border with steady service demand.' },

  // Additional Virginia/WV/Kentucky
  { name: 'Roanoke', slug: 'roanoke', state: 'Virginia', stateAbbr: 'VA', population: '315K', description: 'Blue Ridge metro with growing population and diverse housing stock.' },
  { name: 'Charlottesville', slug: 'charlottesville', state: 'Virginia', stateAbbr: 'VA', population: '255K', description: 'UVA university metro with affluent residents and premium service demand.' },
  { name: 'Lynchburg', slug: 'lynchburg', state: 'Virginia', stateAbbr: 'VA', population: '265K', description: 'Central Virginia metro with university and manufacturing sector demand.' },
  { name: 'Fredericksburg', slug: 'fredericksburg', state: 'Virginia', stateAbbr: 'VA', population: '400K', description: 'Northern Virginia metro between DC and Richmond with rapid residential growth.' },
  { name: 'Charleston WV', slug: 'charleston-wv', state: 'West Virginia', stateAbbr: 'WV', population: '260K', description: 'WV capital metro with government and steady residential demand.' },
  { name: 'Huntington', slug: 'huntington', state: 'West Virginia', stateAbbr: 'WV', population: '360K', description: 'WV-OH-KY tri-state metro with older housing and maintenance demand.' },
  { name: 'Morgantown', slug: 'morgantown', state: 'West Virginia', stateAbbr: 'WV', population: '140K', description: 'WVU university city with student housing and residential demand.' },
  { name: 'Bowling Green', slug: 'bowling-green', state: 'Kentucky', stateAbbr: 'KY', population: '185K', description: 'Southern KY metro with university and growing residential market.' },
  { name: 'Owensboro', slug: 'owensboro', state: 'Kentucky', stateAbbr: 'KY', population: '120K', description: 'Western KY metro with steady residential and commercial demand.' },

  // Additional Minnesota/Iowa/Dakotas
  { name: 'St. Cloud', slug: 'st-cloud', state: 'Minnesota', stateAbbr: 'MN', population: '200K', description: 'Central MN metro with university and growing residential areas.' },
  { name: 'Mankato', slug: 'mankato', state: 'Minnesota', stateAbbr: 'MN', population: '105K', description: 'Southern MN metro with university and manufacturing sector demand.' },
  { name: 'Iowa City', slug: 'iowa-city', state: 'Iowa', stateAbbr: 'IA', population: '175K', description: 'University of Iowa city with strong student housing and residential demand.' },
  { name: 'Waterloo', slug: 'waterloo', state: 'Iowa', stateAbbr: 'IA', population: '170K', description: 'Eastern Iowa metro with manufacturing and residential service needs.' },
  { name: 'Dubuque', slug: 'dubuque', state: 'Iowa', stateAbbr: 'IA', population: '100K', description: 'Eastern Iowa tri-state metro with historic housing and renovation demand.' },
  { name: 'Sioux City', slug: 'sioux-city', state: 'Iowa', stateAbbr: 'IA', population: '185K', description: 'Tri-state IA-NE-SD metro with steady residential demand.' },

  // Additional West
  { name: 'Prescott', slug: 'prescott', state: 'Arizona', stateAbbr: 'AZ', population: '240K', description: 'Central AZ mountain metro with retiree and vacation home demand.' },
  { name: 'Yuma', slug: 'yuma', state: 'Arizona', stateAbbr: 'AZ', population: '210K', description: 'Southwest AZ border metro with extreme heat driving HVAC demand.' },
  { name: 'Lake Havasu City', slug: 'lake-havasu-city', state: 'Arizona', stateAbbr: 'AZ', population: '115K', description: 'Western AZ resort city with seasonal and retiree service demand.' },
  { name: 'Sierra Vista', slug: 'sierra-vista', state: 'Arizona', stateAbbr: 'AZ', population: '85K', description: 'Southeast AZ military metro with Fort Huachuca-driven demand.' },

  // Fill remaining to reach 300
  { name: 'Clarksville', slug: 'clarksville', state: 'Tennessee', stateAbbr: 'TN', population: '320K', description: 'TN-KY border metro with Fort Campbell military base demand.' },
  { name: 'Murfreesboro', slug: 'murfreesboro', state: 'Tennessee', stateAbbr: 'TN', population: '170K', description: 'Fast-growing Nashville suburb with university and residential demand.' },
  { name: 'Johnson City', slug: 'johnson-city', state: 'Tennessee', stateAbbr: 'TN', population: '210K', description: 'Tri-Cities TN metro with growing residential areas and service needs.' },
  { name: 'Cookeville', slug: 'cookeville', state: 'Tennessee', stateAbbr: 'TN', population: '115K', description: 'Upper Cumberland TN metro with university and residential demand.' },
  { name: 'Texarkana', slug: 'texarkana', state: 'Texas', stateAbbr: 'TX', population: '150K', description: 'TX-AR border metro with steady residential service demand.' },
  { name: 'Hickory', slug: 'hickory', state: 'North Carolina', stateAbbr: 'NC', population: '370K', description: 'Western NC metro with manufacturing base and residential demand.' },
  { name: 'Greenville NC', slug: 'greenville-nc', state: 'North Carolina', stateAbbr: 'NC', population: '195K', description: 'Eastern NC university metro with growing residential demand.' },
  { name: 'New Bern', slug: 'new-bern', state: 'North Carolina', stateAbbr: 'NC', population: '130K', description: 'Coastal NC city with military base and retiree demand.' },
  { name: 'Fayetteville NC', slug: 'fayetteville-nc', state: 'North Carolina', stateAbbr: 'NC', population: '530K', description: 'Fort Liberty military metro with strong residential service demand.' },
  { name: 'Rocky Mount', slug: 'rocky-mount', state: 'North Carolina', stateAbbr: 'NC', population: '150K', description: 'Eastern NC metro with steady residential and commercial demand.' },
  { name: 'Valdosta', slug: 'valdosta', state: 'Georgia', stateAbbr: 'GA', population: '150K', description: 'South Georgia metro with military base and university demand.' },
  { name: 'Warner Robins', slug: 'warner-robins', state: 'Georgia', stateAbbr: 'GA', population: '200K', description: 'Central Georgia metro with Robins Air Force Base demand.' },
  { name: 'Gainesville GA', slug: 'gainesville-ga', state: 'Georgia', stateAbbr: 'GA', population: '210K', description: 'Northeast Georgia metro with Lake Lanier and growing residential demand.' },
  { name: 'Panama City', slug: 'panama-city', state: 'Florida', stateAbbr: 'FL', population: '210K', description: 'Florida panhandle beach metro with tourism and military demand.' },
  { name: 'Punta Gorda', slug: 'punta-gorda', state: 'Florida', stateAbbr: 'FL', population: '200K', description: 'Southwest Florida retiree metro with pool and maintenance demand.' },
  { name: 'The Villages', slug: 'the-villages', state: 'Florida', stateAbbr: 'FL', population: '130K', description: 'Largest retirement community in the US with massive home service demand.' },
  { name: 'Daphne', slug: 'daphne', state: 'Alabama', stateAbbr: 'AL', population: '230K', description: 'Eastern Shore Baldwin County metro with growing residential demand.' },
  { name: 'Gulfport', slug: 'gulfport', state: 'Mississippi', stateAbbr: 'MS', population: '285K', description: 'Gulf Coast MS metro with military and tourism-driven service demand.' },
  { name: 'Oxford MS', slug: 'oxford-ms', state: 'Mississippi', stateAbbr: 'MS', population: '60K', description: 'Ole Miss university town with student housing and premium residential demand.' },
  { name: 'Alexandria LA', slug: 'alexandria-la', state: 'Louisiana', stateAbbr: 'LA', population: '155K', description: 'Central LA metro with military base and residential service demand.' },
  { name: 'Elizabethtown', slug: 'elizabethtown', state: 'Kentucky', stateAbbr: 'KY', population: '155K', description: 'Central KY metro with Fort Knox military base and residential demand.' },
  { name: 'Joplin', slug: 'joplin', state: 'Missouri', stateAbbr: 'MO', population: '180K', description: 'Southwest MO four-state metro with steady residential service demand.' },
  { name: 'Longview', slug: 'longview', state: 'Texas', stateAbbr: 'TX', population: '215K', description: 'East Texas metro with growing residential and commercial service needs.' },
  { name: 'Lufkin', slug: 'lufkin', state: 'Texas', stateAbbr: 'TX', population: '90K', description: 'Deep East Texas city with residential and forestry sector demand.' },
]

export function getCityBySlug(slug: string): CityData | undefined {
  return cities.find((c) => c.slug === slug)
}

export function getAllCitySlugs(): string[] {
  return cities.map((c) => c.slug)
}

export function getCitiesByState(): Record<string, CityData[]> {
  const grouped: Record<string, CityData[]> = {}
  for (const city of cities) {
    if (!grouped[city.state]) grouped[city.state] = []
    grouped[city.state].push(city)
  }
  return grouped
}
