export interface ServiceData {
  name: string
  slug: string
  category: string
  description: string
  longDescription: string
  challenges: string[]
  howFullLoopHelps: string[]
  keywords: string[]
}

export const services: ServiceData[] = [
  {
    name: 'House Cleaning',
    slug: 'house-cleaning',
    category: 'Cleaning',
    description: 'Full Loop CRM for house cleaning businesses — organic lead gen, AI sales, scheduling, GPS operations, payments, reviews, and retargeting in one platform.',
    longDescription: 'House cleaning is one of the most competitive home service trades. Clients expect reliability, consistency, and easy scheduling. Full Loop CRM gives house cleaning businesses the tools to dominate their local market with organic lead generation, convert leads 24/7 with AI-powered SMS sales, manage recurring schedules, track field teams with GPS, and automate payments and reviews — all in one platform.',
    challenges: ['High competition from national franchises and solo operators', 'Client churn from inconsistent service quality', 'Difficulty tracking recurring schedules across multiple team members', 'No visibility into which marketing channels generate paying clients', 'Manual payroll calculations eating into profit margins'],
    howFullLoopHelps: ['Multi-domain SEO network targets every neighborhood you serve', 'Selenas AI books clients 24/7 — no missed leads at 11pm or weekends', 'Recurring booking engine handles weekly, biweekly, monthly, and custom schedules', 'GPS check-in/out verifies team arrival and auto-calculates pay', 'Revenue attribution shows exactly which domains drive your best clients'],
    keywords: ['house cleaning CRM', 'cleaning business software', 'maid service management', 'cleaning scheduling software', 'house cleaning lead generation'],
  },
  {
    name: 'Maid Service',
    slug: 'maid-service',
    category: 'Cleaning',
    description: 'Full Loop CRM for maid services — manage teams, generate leads organically, automate booking, and track every dollar.',
    longDescription: 'Maid services depend on recurring clients and reliable teams. Full Loop CRM was originally built from inside a maid service operation — every feature reflects the real challenges of managing cleaning teams, scheduling repeat clients, handling last-minute cancellations, and generating new business without paying for ads.',
    challenges: ['Recruiting and retaining reliable cleaning teams', 'Managing complex recurring schedules with frequent changes', 'Tracking team hours and calculating payroll manually', 'Competing with low-cost solo operators on price', 'Building a consistent pipeline of new clients'],
    howFullLoopHelps: ['Bilingual team portal (EN/ES) that cleaners actually use', 'Emergency job broadcasting fills last-minute cancellations', 'Automated 4-stage reminder cascade reduces no-shows', 'Organic lead generation eliminates dependency on paid ads', 'Client lifecycle analytics identify at-risk clients before they churn'],
    keywords: ['maid service CRM', 'maid service software', 'cleaning company management', 'maid service scheduling', 'maid service lead generation'],
  },
  {
    name: 'Deep Cleaning',
    slug: 'deep-cleaning',
    category: 'Cleaning',
    description: 'Full Loop CRM for deep cleaning businesses — convert one-time jobs into recurring clients with AI sales and automated follow-ups.',
    longDescription: 'Deep cleaning services face a unique challenge: most jobs are one-time. Full Loop CRM helps deep cleaning businesses convert those one-time clients into recurring customers through automated post-service follow-ups, discount offers, and lifecycle tracking that identifies when a client is due for another deep clean.',
    challenges: ['Majority of deep cleaning jobs are one-time with no repeat business', 'Higher price point requires strong sales and objection handling', 'Seasonal demand fluctuations make revenue unpredictable', 'Difficulty communicating the value difference vs regular cleaning', 'No automated way to re-engage past clients'],
    howFullLoopHelps: ['Selenas AI handles pricing objections and communicates the value of deep cleaning', 'Automated thank-you emails with rebooking discounts 3 days after service', 'Client lifecycle tracking alerts you when past clients are due for another deep clean', 'Referral program turns satisfied one-time clients into lead generators', 'Revenue forecasting helps plan for seasonal fluctuations'],
    keywords: ['deep cleaning CRM', 'deep cleaning business software', 'deep cleaning scheduling', 'deep cleaning lead generation', 'deep cleaning business management'],
  },
  {
    name: 'Move In/Out Cleaning',
    slug: 'move-in-out-cleaning',
    category: 'Cleaning',
    description: 'Full Loop CRM for move in/out cleaning — capture time-sensitive leads with AI and dominate local search.',
    longDescription: 'Move in/out cleaning is the most time-sensitive trade in the cleaning industry. Clients need service within days, often searching at the last minute. Full Loop CRM captures these urgent leads through neighborhood-specific websites and converts them instantly via Selenas AI — before they call your competitor.',
    challenges: ['Extremely time-sensitive leads — clients need service within 48-72 hours', 'High search volume but fierce competition for local keywords', 'Seasonal peaks around lease cycles (summer, end of month)', 'Clients rarely become recurring — pure one-time transactions', 'Real estate agent relationships are hard to scale'],
    howFullLoopHelps: ['AI responds to leads within seconds — critical for time-sensitive bookings', 'Multi-domain SEO captures hyper-local move-out cleaning searches', 'Referral program helps scale real estate agent relationships', 'Automated booking with real-time availability prevents double-booking during peaks', 'Revenue attribution tracks which neighborhoods generate the most move-out requests'],
    keywords: ['move in out cleaning CRM', 'move out cleaning software', 'move in cleaning lead generation', 'move out cleaning scheduling', 'end of lease cleaning CRM'],
  },
  {
    name: 'Carpet Cleaning',
    slug: 'carpet-cleaning',
    category: 'Cleaning',
    description: 'Full Loop CRM for carpet cleaning — generate organic leads, automate quoting, and manage field technicians.',
    longDescription: 'Carpet cleaning businesses need a steady flow of local leads and efficient scheduling for equipment-heavy jobs. Full Loop CRM generates organic traffic through neighborhood websites, uses AI to qualify leads and provide instant estimates, and manages field technicians with GPS-verified check-in/out.',
    challenges: ['Equipment logistics add complexity to scheduling', 'Clients often comparison-shop on price alone', 'Difficulty building recurring revenue from one-time carpet cleaning jobs', 'No attribution for which marketing channels drive bookings', 'Manual quoting based on room count and square footage'],
    howFullLoopHelps: ['Selenas AI qualifies leads by room count and provides instant estimates', 'Multi-domain SEO targets neighborhood-specific carpet cleaning keywords', 'Automated follow-ups convert one-time clients into annual deep-clean schedules', 'GPS tracking ensures technicians arrive on time with equipment', 'Full P&L reporting shows profit per job after labor and supply costs'],
    keywords: ['carpet cleaning CRM', 'carpet cleaning software', 'carpet cleaning lead generation', 'carpet cleaning scheduling', 'carpet cleaning business management'],
  },
  {
    name: 'Window Cleaning',
    slug: 'window-cleaning',
    category: 'Cleaning',
    description: 'Full Loop CRM for window cleaning businesses — schedule recurring appointments and generate organic local leads.',
    longDescription: 'Window cleaning businesses thrive on recurring schedules and geographic density. Full Loop CRM helps window cleaners build dense route-based schedules, generate organic leads in every neighborhood they serve, and manage seasonal demand shifts with smart booking tools.',
    challenges: ['Weather-dependent scheduling requires flexible rescheduling', 'Geographic density is critical for route efficiency and profitability', 'Seasonal demand spikes in spring and fall', 'Residential vs commercial scheduling complexity', 'Building recurring revenue with quarterly or biannual schedules'],
    howFullLoopHelps: ['Recurring booking engine supports custom intervals for quarterly window cleaning', 'Multi-domain SEO targets neighborhood-level window cleaning searches', 'Real-time availability calendar handles weather-related rescheduling', 'GPS-verified check-in/out ensures route efficiency', 'Client lifecycle analytics track when clients are due for their next cleaning'],
    keywords: ['window cleaning CRM', 'window cleaning software', 'window cleaning scheduling', 'window cleaning lead generation', 'window cleaning business management'],
  },
  {
    name: 'Pressure Washing',
    slug: 'pressure-washing',
    category: 'Exterior',
    description: 'Full Loop CRM for pressure washing — dominate local search and convert leads with AI-powered sales.',
    longDescription: 'Pressure washing is a high-demand, seasonal trade with strong local search volume. Full Loop CRM helps pressure washing businesses capture organic leads through neighborhood websites, convert them instantly with AI sales, and manage teams in the field with GPS tracking.',
    challenges: ['Highly seasonal demand with weather dependency', 'Clients often need one-time service with no recurring revenue', 'Price-sensitive market with many solo operators', 'Equipment and travel logistics affect scheduling', 'Difficulty standing out in crowded local search results'],
    howFullLoopHelps: ['Multi-domain SEO dominates neighborhood-level pressure washing searches', 'Selenas AI qualifies leads by property type, surface area, and service needs', 'Automated post-service follow-ups convert one-time into annual clients', 'GPS check-in/out tracks team efficiency across multiple job sites', 'Revenue attribution identifies which neighborhoods are most profitable'],
    keywords: ['pressure washing CRM', 'pressure washing software', 'pressure washing lead generation', 'pressure washing scheduling', 'power washing business management'],
  },
  {
    name: 'Landscaping',
    slug: 'landscaping',
    category: 'Outdoor',
    description: 'Full Loop CRM for landscaping businesses — manage crews, generate leads, and automate recurring maintenance schedules.',
    longDescription: 'Landscaping businesses manage complex schedules across multiple crews, properties, and service types. Full Loop CRM provides the complete operational backbone — from organic lead generation through scheduling, GPS-verified crew management, payment collection, and client retention.',
    challenges: ['Multiple crews serving different zones require complex scheduling', 'Seasonal revenue fluctuations from spring peaks to winter slowdowns', 'Mix of one-time projects and recurring maintenance contracts', 'Difficulty tracking profitability per client and per crew', 'Crew management across multiple job sites in a single day'],
    howFullLoopHelps: ['Visual calendar with crew-based color coding and drag-drop scheduling', 'Recurring booking engine handles weekly mowing through seasonal cleanup', 'GPS check-in/out across multiple daily job sites per crew', 'Full P&L with per-crew labor costs and per-client profitability', 'Multi-domain SEO targets landscaping searches in every neighborhood you serve'],
    keywords: ['landscaping CRM', 'landscaping business software', 'lawn care scheduling', 'landscaping lead generation', 'landscape company management'],
  },
  {
    name: 'Lawn Care',
    slug: 'lawn-care',
    category: 'Outdoor',
    description: 'Full Loop CRM for lawn care — automate weekly mowing schedules and generate organic leads in your territory.',
    longDescription: 'Lawn care is the quintessential recurring home service — weekly mowing contracts form the revenue backbone. Full Loop CRM automates every aspect of running a lawn care business, from generating organic leads to managing weekly schedules, tracking crew locations, and collecting payments.',
    challenges: ['High volume of weekly recurring schedules to manage', 'Route optimization is critical for profitability', 'Weather delays require mass rescheduling capabilities', 'Low margins demand tight cost control', 'Client acquisition cost must stay low to maintain profitability'],
    howFullLoopHelps: ['Weekly recurring booking automation generates all future dates automatically', 'GPS tracking enables route-based crew management', 'Zero ad spend organic lead generation keeps acquisition costs near zero', 'Automated reminders reduce no-access situations', 'Margin analysis shows true profitability per client after labor and fuel'],
    keywords: ['lawn care CRM', 'lawn care software', 'lawn mowing scheduling', 'lawn care lead generation', 'lawn service business management'],
  },
  {
    name: 'HVAC Repair',
    slug: 'hvac-repair',
    category: 'Trades',
    description: 'Full Loop CRM for HVAC repair — capture emergency leads 24/7 and manage technician dispatch with GPS.',
    longDescription: 'HVAC repair is one of the highest-value home service trades with strong emergency demand. Full Loop CRM captures emergency HVAC leads around the clock with AI-powered sales, dispatches technicians with GPS tracking, and builds long-term maintenance contracts through automated follow-ups.',
    challenges: ['Emergency calls come at all hours — nights, weekends, holidays', 'High-value leads require fast response to prevent losing to competitors', 'Technician dispatch and routing across wide service areas', 'Building recurring maintenance contracts from one-time repair calls', 'Seasonal peaks in summer (AC) and winter (heating) strain capacity'],
    howFullLoopHelps: ['Selenas AI engages emergency HVAC leads within seconds, 24/7/365', 'GPS-verified technician dispatch with real-time location tracking', 'Automated post-repair follow-ups convert one-time into annual maintenance contracts', 'Emergency job broadcasting dispatches nearest available technician', 'Multi-domain SEO captures "HVAC repair near me" searches in every neighborhood'],
    keywords: ['HVAC CRM', 'HVAC business software', 'HVAC scheduling', 'HVAC lead generation', 'HVAC repair business management'],
  },
  {
    name: 'Plumbing',
    slug: 'plumbing',
    category: 'Trades',
    description: 'Full Loop CRM for plumbing businesses — capture emergency leads, manage dispatching, and track job profitability.',
    longDescription: 'Plumbing businesses handle a mix of emergency calls and scheduled maintenance. Full Loop CRM captures both types of leads through organic search, qualifies them with AI, and manages the full lifecycle from dispatch through payment and follow-up.',
    challenges: ['Emergency calls require immediate response and flexible scheduling', 'Wide range of job types from small repairs to major installations', 'Tracking parts and labor costs per job for accurate profitability', 'Building trust with homeowners who are wary of plumbing estimates', 'Managing apprentice and journeyman scheduling and pay rates'],
    howFullLoopHelps: ['24/7 AI lead engagement captures emergency plumbing searches instantly', 'Per-team-member pay rates with automatic calculation from GPS check-in/out', 'Full financial suite tracks revenue, labor, and parts costs per job', 'Multi-domain SEO targets neighborhood plumbing searches', 'Client profiles with full service history build trust for repeat business'],
    keywords: ['plumbing CRM', 'plumbing business software', 'plumber scheduling', 'plumbing lead generation', 'plumbing company management'],
  },
  {
    name: 'Electrical',
    slug: 'electrical',
    category: 'Trades',
    description: 'Full Loop CRM for electricians — generate local leads, automate scheduling, and manage technician dispatch.',
    longDescription: 'Electrical businesses need efficient scheduling, reliable lead generation, and clear communication with clients about complex work. Full Loop CRM provides the complete business platform — from capturing organic leads to scheduling, dispatch, payment, and review generation.',
    challenges: ['Complex job types require detailed quoting and communication', 'Licensing and permit requirements add scheduling complexity', 'Mix of residential and commercial work with different pricing', 'Emergency service calls disrupt planned schedules', 'Building ongoing relationships beyond one-time repairs'],
    howFullLoopHelps: ['Selenas AI qualifies leads by job type and urgency level', 'Smart scheduling with buffer times for jobs that run long', 'GPS tracking verifies technician arrival and calculates hours worked', 'Automated post-service follow-ups drive Google reviews', 'Revenue attribution shows which services and neighborhoods are most profitable'],
    keywords: ['electrician CRM', 'electrical business software', 'electrician scheduling', 'electrical lead generation', 'electrical contractor management'],
  },
  {
    name: 'Handyman Services',
    slug: 'handyman-services',
    category: 'Trades',
    description: 'Full Loop CRM for handyman services — manage diverse job types, generate leads, and build recurring client relationships.',
    longDescription: 'Handyman services cover the widest range of job types in home services. Full Loop CRM handles this diversity with flexible scheduling, AI-powered lead qualification that routes different job types appropriately, and client relationship management that builds repeat business.',
    challenges: ['Extremely diverse job types from minor fixes to full-day projects', 'Difficulty pricing accurately across such a wide range of services', 'Clients often need one-time help with no natural recurring schedule', 'Competition from both specialists and DIY homeowners', 'Building a reputation across multiple service categories'],
    howFullLoopHelps: ['AI sales qualifies leads by job type and provides appropriate pricing guidance', 'Flexible scheduling handles 30-minute fixes and full-day projects', 'Automated follow-ups convert one-time clients into regulars', 'Multi-domain SEO targets specific handyman services in each neighborhood', 'Referral program turns satisfied clients into your best marketing channel'],
    keywords: ['handyman CRM', 'handyman business software', 'handyman scheduling', 'handyman lead generation', 'handyman service management'],
  },
  {
    name: 'Pest Control',
    slug: 'pest-control',
    category: 'Specialty',
    description: 'Full Loop CRM for pest control — capture emergency leads, build recurring treatment plans, and manage technician routes.',
    longDescription: 'Pest control businesses thrive on recurring treatment contracts and emergency calls. Full Loop CRM captures both through organic search, converts them with 24/7 AI sales, and manages the entire operational cycle from scheduling through treatment documentation and re-engagement.',
    challenges: ['Emergency pest calls require immediate response', 'Building recurring quarterly or monthly treatment contracts', 'Seasonal pest activity creates demand spikes', 'Tracking treatment history per property for regulatory compliance', 'Wide service areas requiring efficient route management'],
    howFullLoopHelps: ['24/7 AI captures emergency pest control leads — spiders at midnight, rodents on weekends', 'Recurring booking engine manages monthly and quarterly treatment schedules', 'Client profiles store full treatment history per property', 'GPS routing tracks technician efficiency across wide service areas', 'Automated reminders ensure clients never miss a scheduled treatment'],
    keywords: ['pest control CRM', 'pest control software', 'pest control scheduling', 'pest control lead generation', 'exterminator business management'],
  },
  {
    name: 'Painting',
    slug: 'painting',
    category: 'Trades',
    description: 'Full Loop CRM for painting businesses — generate leads, manage project scheduling, and track crew profitability.',
    longDescription: 'Painting businesses handle multi-day projects with complex scheduling needs. Full Loop CRM provides the project management backbone — from lead generation through estimation, scheduling, crew dispatch, and payment collection — with full profitability tracking per job.',
    challenges: ['Multi-day projects require careful scheduling and crew coordination', 'Estimating accuracy directly impacts profitability', 'Seasonal demand peaks in spring and summer', 'Competition from both professional crews and DIY homeowners', 'Managing multiple concurrent projects across different locations'],
    howFullLoopHelps: ['Multi-domain SEO captures local painting searches by neighborhood', 'Selenas AI qualifies leads by project type, room count, and timeline', 'Scheduling with multi-day job support and crew assignment', 'GPS check-in/out tracks daily crew hours on multi-day projects', 'P&L reporting shows true profitability per project after labor and materials'],
    keywords: ['painting CRM', 'painting business software', 'painter scheduling', 'painting lead generation', 'painting contractor management'],
  },
  {
    name: 'Junk Removal',
    slug: 'junk-removal',
    category: 'Specialty',
    description: 'Full Loop CRM for junk removal — capture urgent leads with AI, manage crew dispatch, and optimize routes.',
    longDescription: 'Junk removal is a high-volume, time-sensitive trade where speed of response determines who gets the job. Full Loop CRM captures junk removal leads through organic search, responds within seconds via AI, and manages crew dispatch with GPS tracking for maximum route efficiency.',
    challenges: ['Extremely time-sensitive — clients want same-day or next-day service', 'Volume-based pricing requires on-site estimates for many jobs', 'Truck routing and capacity management across multiple pickups', 'Environmental disposal regulations vary by municipality', 'Building recurring relationships from typically one-time service'],
    howFullLoopHelps: ['AI engages junk removal leads within seconds — critical for same-day bookings', 'Smart scheduling handles same-day requests with real-time crew availability', 'GPS tracking optimizes truck routes across multiple daily pickups', 'Automated follow-ups for future cleanout needs and referral generation', 'Revenue attribution tracks which neighborhoods generate the most junk removal requests'],
    keywords: ['junk removal CRM', 'junk removal software', 'junk removal scheduling', 'junk removal lead generation', 'junk hauling business management'],
  },
  {
    name: 'Pool Cleaning',
    slug: 'pool-cleaning',
    category: 'Outdoor',
    description: 'Full Loop CRM for pool cleaning — manage weekly route schedules, generate organic leads, and track chemical treatment history.',
    longDescription: 'Pool cleaning businesses run on tight weekly routes and recurring maintenance contracts. Full Loop CRM manages the entire operation — from generating organic leads in pool-heavy neighborhoods to scheduling weekly service routes, tracking treatment history, and managing seasonal open/close schedules.',
    challenges: ['Weekly routes must be geographically optimized for efficiency', 'Seasonal business model with open/close periods', 'Chemical treatment tracking for client safety and compliance', 'Mix of weekly maintenance and one-time cleanups', 'Geographic concentration in specific neighborhoods with pools'],
    howFullLoopHelps: ['Weekly recurring schedules auto-generate for the entire season', 'Multi-domain SEO targets pool-heavy neighborhoods specifically', 'Client profiles store treatment history and pool specifications', 'GPS tracking verifies weekly service visits', 'Revenue forecasting accounts for seasonal on/off cycles'],
    keywords: ['pool cleaning CRM', 'pool service software', 'pool cleaning scheduling', 'pool cleaning lead generation', 'pool maintenance business management'],
  },
  {
    name: 'Roofing',
    slug: 'roofing',
    category: 'Trades',
    description: 'Full Loop CRM for roofing — capture storm-damage leads, manage project scheduling, and track crew operations.',
    longDescription: 'Roofing businesses handle high-value projects with complex timelines and crew coordination. Full Loop CRM captures roofing leads — including time-sensitive storm damage inquiries — qualifies them with AI, and manages the full project lifecycle from estimate through completion and payment.',
    challenges: ['Storm damage creates sudden demand spikes requiring rapid response', 'High-value projects require thorough lead qualification', 'Multi-day installations need careful crew and material coordination', 'Insurance claim processes add complexity to client communication', 'Seasonal weather windows limit available working days'],
    howFullLoopHelps: ['24/7 AI captures emergency storm damage leads before competitors', 'Lead qualification identifies job type, urgency, and budget', 'Multi-day scheduling with crew assignment and GPS tracking', 'Client profiles store project documentation and communication history', 'P&L tracking shows true profitability per roofing project'],
    keywords: ['roofing CRM', 'roofing business software', 'roofing scheduling', 'roofing lead generation', 'roofing contractor management'],
  },
  {
    name: 'Gutter Cleaning',
    slug: 'gutter-cleaning',
    category: 'Exterior',
    description: 'Full Loop CRM for gutter cleaning — build seasonal recurring schedules and generate local organic leads.',
    longDescription: 'Gutter cleaning businesses rely on seasonal recurring schedules, typically spring and fall. Full Loop CRM generates organic leads through local search, manages biannual recurring schedules, and automates client re-engagement when it is time for their next cleaning.',
    challenges: ['Highly seasonal with demand concentrated in spring and fall', 'Building reliable biannual recurring schedules', 'Weather dependency affects scheduling flexibility', 'Low individual job value requires high volume', 'Competing with pressure washing companies offering gutter add-ons'],
    howFullLoopHelps: ['Recurring booking engine manages biannual and seasonal schedules', 'Multi-domain SEO captures seasonal gutter cleaning searches', 'Automated lifecycle reminders re-engage clients when next cleaning is due', 'Route-based GPS scheduling maximizes jobs per day', 'Referral program incentivizes neighborhood-level word of mouth'],
    keywords: ['gutter cleaning CRM', 'gutter cleaning software', 'gutter cleaning scheduling', 'gutter cleaning lead generation', 'gutter service business management'],
  },
  {
    name: 'Air Duct Cleaning',
    slug: 'air-duct-cleaning',
    category: 'Specialty',
    description: 'Full Loop CRM for air duct cleaning — generate leads, schedule technicians, and build recurring maintenance contracts.',
    longDescription: 'Air duct cleaning businesses benefit from health-conscious homeowners searching for indoor air quality solutions. Full Loop CRM captures these searches through targeted local SEO, qualifies leads with AI that explains the health benefits, and builds recurring annual maintenance schedules.',
    challenges: ['Educating homeowners on the health benefits drives conversion', 'Seasonal demand tied to HVAC usage patterns', 'Equipment-heavy service requires careful scheduling', 'Building annual or biannual maintenance contracts', 'Competing with HVAC companies offering duct cleaning as add-on'],
    howFullLoopHelps: ['Selenas AI educates leads on air quality benefits during qualification', 'Multi-domain SEO targets health-conscious homeowner searches', 'Recurring scheduling for annual duct cleaning maintenance', 'GPS-verified technician dispatch with equipment tracking', 'Automated follow-ups remind clients when annual cleaning is due'],
    keywords: ['air duct cleaning CRM', 'duct cleaning software', 'air duct cleaning scheduling', 'duct cleaning lead generation', 'HVAC duct cleaning management'],
  },
]

export function getServiceBySlug(slug: string): ServiceData | undefined {
  return services.find((s) => s.slug === slug)
}

export function getAllServiceSlugs(): string[] {
  return services.map((s) => s.slug)
}
