// State-level metadata used to enrich combo + metro pages with real
// jurisdiction-specific content, so each page isn't a pure template swap.

export interface StateMetadata {
  licensingAuthority: string;
  licensingUrl: string;
  climateZone: "hot-humid" | "hot-dry" | "mixed-humid" | "cold" | "very-cold" | "marine";
  populationRank: number;
  tradeAssociation: string;
  seasonalNote: string;
  permitNote: string;
  taxNote: string;
}

export const stateMetadata: Record<string, StateMetadata> = {
  AL: {
    licensingAuthority: "Alabama Home Builders Licensure Board",
    licensingUrl: "https://hblb.alabama.gov",
    climateZone: "hot-humid",
    populationRank: 24,
    tradeAssociation: "Home Builders Association of Alabama",
    seasonalNote: "Peak demand runs April through September, with storm-driven spikes for roofing and restoration.",
    permitNote: "Most cities require permits for HVAC, electrical, and plumbing work exceeding minor repairs.",
    taxNote: "Alabama does not charge sales tax on most labor, but parts and materials are taxable.",
  },
  AK: {
    licensingAuthority: "Alaska Department of Commerce — Division of Corporations, Business and Professional Licensing",
    licensingUrl: "https://www.commerce.alaska.gov/web/cbpl",
    climateZone: "very-cold",
    populationRank: 48,
    tradeAssociation: "Associated Builders & Contractors of Alaska",
    seasonalNote: "Season compresses into May-September; winter demand flips to heating, plow, and emergency work.",
    permitNote: "Mechanical and electrical work requires registration with the Department of Labor.",
    taxNote: "No state sales tax; local sales taxes vary by borough.",
  },
  AZ: {
    licensingAuthority: "Arizona Registrar of Contractors (ROC)",
    licensingUrl: "https://roc.az.gov",
    climateZone: "hot-dry",
    populationRank: 14,
    tradeAssociation: "Arizona Builders Alliance",
    seasonalNote: "HVAC demand peaks May through September; landscaping and pool services run year-round.",
    permitNote: "Arizona requires a ROC license for any single job over $1,000 including labor and materials.",
    taxNote: "Transaction privilege tax (TPT) applies to prime contractors; subcontractor rules differ.",
  },
  AR: {
    licensingAuthority: "Arkansas Contractors Licensing Board",
    licensingUrl: "https://www.aclb.arkansas.gov",
    climateZone: "mixed-humid",
    populationRank: 33,
    tradeAssociation: "Arkansas Home Builders Association",
    seasonalNote: "Storm season from March through June drives roofing and restoration spikes.",
    permitNote: "Commercial jobs over $50,000 and residential over $2,000 require a state contractor license.",
    taxNote: "Sales tax applies to both labor and materials on most improvement work.",
  },
  CA: {
    licensingAuthority: "California Contractors State License Board (CSLB)",
    licensingUrl: "https://www.cslb.ca.gov",
    climateZone: "marine",
    populationRank: 1,
    tradeAssociation: "California Building Industry Association",
    seasonalNote: "Year-round demand; wildfire season drives restoration, roofing, and defensible-space landscaping.",
    permitNote: "CSLB license required for any job over $500 labor and materials; Title 24 energy code adds HVAC/electrical scope.",
    taxNote: "Labor is generally not taxable, but fabrication labor and materials are.",
  },
  CO: {
    licensingAuthority: "Colorado Department of Regulatory Agencies (DORA)",
    licensingUrl: "https://dpo.colorado.gov",
    climateZone: "cold",
    populationRank: 21,
    tradeAssociation: "Colorado Association of Home Builders",
    seasonalNote: "Hail season May-August drives roofing insurance work; snow removal contracts lock in by October.",
    permitNote: "Licensing is city-level — Denver, Colorado Springs, and Boulder each have separate contractor boards.",
    taxNote: "State plus local sales tax on materials; home-rule cities can charge their own rates.",
  },
  CT: {
    licensingAuthority: "Connecticut Department of Consumer Protection",
    licensingUrl: "https://portal.ct.gov/dcp",
    climateZone: "cold",
    populationRank: 29,
    tradeAssociation: "Home Builders & Remodelers Association of Connecticut",
    seasonalNote: "Winter heating demand and spring storm cleanup drive two clear busy seasons.",
    permitNote: "Home Improvement Contractor registration required for any residential job over $200.",
    taxNote: "6.35% sales tax applies to most services, including certain repair work.",
  },
  DE: {
    licensingAuthority: "Delaware Division of Revenue — Contractor Licensing",
    licensingUrl: "https://revenue.delaware.gov",
    climateZone: "mixed-humid",
    populationRank: 45,
    tradeAssociation: "Home Builders Association of Delaware",
    seasonalNote: "Beach rental season drives turnover cleaning and landscaping peaks from May through September.",
    permitNote: "Every contractor must hold a state business license; county/city permits required for most work.",
    taxNote: "No sales tax, but gross receipts tax applies to contractor revenue.",
  },
  DC: {
    licensingAuthority: "DC Department of Licensing and Consumer Protection",
    licensingUrl: "https://dlcp.dc.gov",
    climateZone: "mixed-humid",
    populationRank: 49,
    tradeAssociation: "Maryland Building Industry Association (DC chapter)",
    seasonalNote: "Row-house density drives steady year-round demand for HVAC, plumbing, and restoration.",
    permitNote: "Basic Business License plus trade-specific endorsement required for all contractors.",
    taxNote: "Sales tax applies to most service work at 6%.",
  },
  FL: {
    licensingAuthority: "Florida Department of Business and Professional Regulation (DBPR)",
    licensingUrl: "https://www.myfloridalicense.com",
    climateZone: "hot-humid",
    populationRank: 3,
    tradeAssociation: "Florida Home Builders Association",
    seasonalNote: "Hurricane season June-November drives roofing, tree, and water damage spikes; snowbird cleaning peaks October-April.",
    permitNote: "Certified (statewide) or Registered (county) contractor license required for most trades.",
    taxNote: "Sales tax on materials; labor generally exempt unless bundled with taxable goods.",
  },
  GA: {
    licensingAuthority: "Georgia State Licensing Board for Residential and General Contractors",
    licensingUrl: "https://sos.ga.gov/georgia-state-licensing-board-residential-and-general-contractors",
    climateZone: "hot-humid",
    populationRank: 8,
    tradeAssociation: "Home Builders Association of Georgia",
    seasonalNote: "Atlanta hail season peaks March-May; pest and HVAC demand runs April-October.",
    permitNote: "Residential contractor license required for jobs over $2,500; separate electrical, plumbing, HVAC trade licenses.",
    taxNote: "Sales tax on materials; labor on repair work generally exempt.",
  },
  HI: {
    licensingAuthority: "Hawaii Department of Commerce and Consumer Affairs — Contractors License Board",
    licensingUrl: "https://cca.hawaii.gov/pvl/boards/contractor",
    climateZone: "hot-humid",
    populationRank: 40,
    tradeAssociation: "Building Industry Association of Hawaii",
    seasonalNote: "Year-round demand; wet-season mold and pest work November-April.",
    permitNote: "Any contracting job $1,000+ including labor and materials requires a state license.",
    taxNote: "General excise tax (GET) of 4-4.5% applies to all contracting revenue.",
  },
  ID: {
    licensingAuthority: "Idaho Division of Building Safety",
    licensingUrl: "https://dbs.idaho.gov",
    climateZone: "cold",
    populationRank: 38,
    tradeAssociation: "Idaho Building Contractors Association",
    seasonalNote: "Boise-area growth drives steady construction demand; winter heating and snow removal peak December-February.",
    permitNote: "Contractor registration required statewide; additional trade licenses for HVAC, electrical, plumbing.",
    taxNote: "Sales tax on materials at point of purchase; labor generally exempt.",
  },
  IL: {
    licensingAuthority: "Illinois Department of Financial and Professional Regulation (IDFPR)",
    licensingUrl: "https://idfpr.illinois.gov",
    climateZone: "cold",
    populationRank: 6,
    tradeAssociation: "Home Builders Association of Illinois",
    seasonalNote: "Chicago winters drive heating emergency demand December-March; pest and HVAC peak June-September.",
    permitNote: "Plumbers and roofers licensed at state level; HVAC, electrical licensed city-by-city (Chicago is its own regime).",
    taxNote: "Sales tax on materials; labor rules vary by service type.",
  },
  IN: {
    licensingAuthority: "Indiana Professional Licensing Agency",
    licensingUrl: "https://www.in.gov/pla",
    climateZone: "cold",
    populationRank: 17,
    tradeAssociation: "Indiana Builders Association",
    seasonalNote: "Severe weather May-July drives roofing and restoration; winter heating service peaks January-February.",
    permitNote: "Plumbing licensed at state level; most other trades licensed by city or county.",
    taxNote: "Sales tax on materials; labor generally exempt.",
  },
  IA: {
    licensingAuthority: "Iowa Division of Labor — Contractor Registration",
    licensingUrl: "https://www.iowadivisionoflabor.gov",
    climateZone: "cold",
    populationRank: 31,
    tradeAssociation: "Home Builders Association of Iowa",
    seasonalNote: "Derecho and severe weather May-August drive roofing and tree work spikes.",
    permitNote: "Any contractor earning $2,000+ per year must register with Iowa Division of Labor.",
    taxNote: "Sales tax on both materials and most labor on new construction; repair work partially exempt.",
  },
  KS: {
    licensingAuthority: "Kansas City and county building departments",
    licensingUrl: "https://www.kansas.gov",
    climateZone: "mixed-humid",
    populationRank: 36,
    tradeAssociation: "Kansas Building Industry Association",
    seasonalNote: "Tornado season April-June drives roofing and restoration demand.",
    permitNote: "No statewide licensing for most trades; Johnson, Wyandotte, and Sedgwick counties run their own programs.",
    taxNote: "Sales tax on both materials and labor for most improvement work.",
  },
  KY: {
    licensingAuthority: "Kentucky Department of Housing, Buildings and Construction",
    licensingUrl: "https://dhbc.ky.gov",
    climateZone: "mixed-humid",
    populationRank: 26,
    tradeAssociation: "Home Builders Association of Kentucky",
    seasonalNote: "HVAC and pest demand peaks April-October; storm season March-May drives roofing.",
    permitNote: "HVAC, plumbing, and electrical require state licensing; general contracting licensed locally.",
    taxNote: "Sales tax on materials; most labor exempt on residential repair.",
  },
  LA: {
    licensingAuthority: "Louisiana State Licensing Board for Contractors",
    licensingUrl: "https://www.lslbc.louisiana.gov",
    climateZone: "hot-humid",
    populationRank: 25,
    tradeAssociation: "Louisiana Home Builders Association",
    seasonalNote: "Hurricane season June-November drives major restoration, roofing, and tree work spikes.",
    permitNote: "Residential license required for jobs over $75,000; commercial over $50,000.",
    taxNote: "Sales tax on both labor and materials for most contracting work.",
  },
  ME: {
    licensingAuthority: "Maine Department of Professional and Financial Regulation",
    licensingUrl: "https://www.maine.gov/pfr",
    climateZone: "very-cold",
    populationRank: 42,
    tradeAssociation: "Home Builders & Remodelers Association of Maine",
    seasonalNote: "Winter heating demand November-March; seasonal rental cleaning peaks May-September.",
    permitNote: "Electricians and plumbers require state licensing; general contractors licensed locally.",
    taxNote: "Sales tax on materials; most service labor exempt.",
  },
  MD: {
    licensingAuthority: "Maryland Home Improvement Commission",
    licensingUrl: "https://www.dllr.state.md.us/license/mhic",
    climateZone: "mixed-humid",
    populationRank: 19,
    tradeAssociation: "Maryland Building Industry Association",
    seasonalNote: "Severe storm spikes April-August; DC suburb density drives steady year-round work.",
    permitNote: "Home Improvement Contractor license required for any residential work over $500.",
    taxNote: "Sales tax applies to materials; fabrication and taxable services per state schedule.",
  },
  MA: {
    licensingAuthority: "Massachusetts Division of Occupational Licensure",
    licensingUrl: "https://www.mass.gov/orgs/division-of-occupational-licensure",
    climateZone: "cold",
    populationRank: 16,
    tradeAssociation: "Home Builders & Remodelers Association of Massachusetts",
    seasonalNote: "Winter heating emergencies and ice-dam roofing peak December-February; landscaping April-October.",
    permitNote: "Construction Supervisor License (CSL) plus Home Improvement Contractor (HIC) registration for most residential work.",
    taxNote: "Sales tax on materials; most labor on repair work exempt.",
  },
  MI: {
    licensingAuthority: "Michigan Department of Licensing and Regulatory Affairs (LARA)",
    licensingUrl: "https://www.michigan.gov/lara",
    climateZone: "cold",
    populationRank: 10,
    tradeAssociation: "Home Builders Association of Michigan",
    seasonalNote: "Cold-climate HVAC spikes November-March; spring storm season drives roofing April-June.",
    permitNote: "Residential Builder License required for jobs over $600; separate licenses for mechanical, electrical, plumbing.",
    taxNote: "Sales tax on materials; most contracting labor exempt on repair.",
  },
  MN: {
    licensingAuthority: "Minnesota Department of Labor and Industry",
    licensingUrl: "https://www.dli.mn.gov",
    climateZone: "very-cold",
    populationRank: 22,
    tradeAssociation: "Housing First Minnesota",
    seasonalNote: "Deep-cold HVAC emergencies December-February; severe storm and hail spikes May-August.",
    permitNote: "Residential Building Contractor license required for most home improvement work.",
    taxNote: "Sales tax on materials; labor generally exempt on residential repair.",
  },
  MS: {
    licensingAuthority: "Mississippi State Board of Contractors",
    licensingUrl: "https://www.msboc.us",
    climateZone: "hot-humid",
    populationRank: 34,
    tradeAssociation: "Home Builders Association of Mississippi",
    seasonalNote: "Hurricane season drives Gulf Coast restoration spikes June-November.",
    permitNote: "State contractor license required for residential jobs over $50,000 and commercial over $50,000.",
    taxNote: "7% sales tax applies to both labor and materials on most improvement work.",
  },
  MO: {
    licensingAuthority: "Missouri state has no statewide contractor license — city-level",
    licensingUrl: "https://mo.gov",
    climateZone: "mixed-humid",
    populationRank: 19,
    tradeAssociation: "Home Builders Association of Missouri",
    seasonalNote: "Tornado season March-June drives restoration and roofing; HVAC peaks summer and winter.",
    permitNote: "Licensing handled by each city — Kansas City and St. Louis have their own contractor boards.",
    taxNote: "Sales tax on materials; labor rules vary by municipality.",
  },
  MT: {
    licensingAuthority: "Montana Department of Labor and Industry",
    licensingUrl: "https://dli.mt.gov",
    climateZone: "very-cold",
    populationRank: 44,
    tradeAssociation: "Montana Building Industry Association",
    seasonalNote: "Long winter season drives heating and snow work October-April.",
    permitNote: "Independent Contractor Exemption Certificate plus trade licensure for electrical and plumbing.",
    taxNote: "No state sales tax.",
  },
  NE: {
    licensingAuthority: "Nebraska Department of Labor — Contractor Registration",
    licensingUrl: "https://dol.nebraska.gov",
    climateZone: "cold",
    populationRank: 37,
    tradeAssociation: "Nebraska State Home Builders Association",
    seasonalNote: "Severe storm and hail spikes May-July; winter heating November-February.",
    permitNote: "Contractor registration required for any contractor earning $5,000+ per year.",
    taxNote: "Sales tax on both materials and most labor for improvement work.",
  },
  NV: {
    licensingAuthority: "Nevada State Contractors Board",
    licensingUrl: "https://nscb.nv.gov",
    climateZone: "hot-dry",
    populationRank: 32,
    tradeAssociation: "Southern Nevada Home Builders Association",
    seasonalNote: "HVAC and pool demand May-September; year-round tourism drives hospitality cleaning.",
    permitNote: "Contractor license required for any job $1,000+ including labor and materials.",
    taxNote: "Sales tax on materials; labor generally exempt on repair.",
  },
  NH: {
    licensingAuthority: "New Hampshire Office of Professional Licensure and Certification",
    licensingUrl: "https://www.oplc.nh.gov",
    climateZone: "cold",
    populationRank: 41,
    tradeAssociation: "Home Builders & Remodelers Association of New Hampshire",
    seasonalNote: "Winter heating emergencies November-March; lake-country cleaning peaks June-September.",
    permitNote: "Electricians, plumbers, and gas fitters require state licensing; general contractors regulated locally.",
    taxNote: "No state sales tax; meals and rooms tax does not apply to contracting.",
  },
  NJ: {
    licensingAuthority: "New Jersey Division of Consumer Affairs",
    licensingUrl: "https://www.njconsumeraffairs.gov",
    climateZone: "mixed-humid",
    populationRank: 11,
    tradeAssociation: "New Jersey Builders Association",
    seasonalNote: "Nor'easter and hurricane damage drives roofing and restoration spikes August-March.",
    permitNote: "Home Improvement Contractor registration required for any residential work over $500.",
    taxNote: "Sales tax on most contracting labor and materials at 6.625%.",
  },
  NM: {
    licensingAuthority: "New Mexico Regulation and Licensing Department — Construction Industries Division",
    licensingUrl: "https://www.rld.nm.gov/construction-industries",
    climateZone: "hot-dry",
    populationRank: 36,
    tradeAssociation: "Home Builders Association of New Mexico",
    seasonalNote: "Monsoon season July-September drives roof and water damage work; dust-driven HVAC service year-round.",
    permitNote: "Any job over $200 including labor requires a state contractor license.",
    taxNote: "Gross receipts tax applies to all contractor revenue.",
  },
  NY: {
    licensingAuthority: "New York Department of State — Division of Licensing Services",
    licensingUrl: "https://www.dos.ny.gov/licensing",
    climateZone: "cold",
    populationRank: 4,
    tradeAssociation: "New York State Builders Association",
    seasonalNote: "NYC year-round density drives constant demand; upstate heating November-March.",
    permitNote: "NYC has its own DOB and DCWP licensing for nearly every trade; upstate varies by county.",
    taxNote: "Sales tax on both labor and materials for most residential improvement work.",
  },
  NC: {
    licensingAuthority: "North Carolina Licensing Board for General Contractors",
    licensingUrl: "https://nclbgc.org",
    climateZone: "mixed-humid",
    populationRank: 9,
    tradeAssociation: "North Carolina Home Builders Association",
    seasonalNote: "Coastal hurricane season June-November; HVAC and pest demand April-October.",
    permitNote: "General contractor license required for jobs over $30,000; separate trade licenses for HVAC, plumbing, electrical.",
    taxNote: "Sales tax on materials; repair, maintenance, and installation services also taxable.",
  },
  ND: {
    licensingAuthority: "North Dakota Secretary of State — Contractor Licensing",
    licensingUrl: "https://sos.nd.gov",
    climateZone: "very-cold",
    populationRank: 47,
    tradeAssociation: "North Dakota Association of Builders",
    seasonalNote: "Winter season extends October-April; construction compresses May-September.",
    permitNote: "Contractor license required for any project $4,000+.",
    taxNote: "Sales tax on materials; labor rules vary.",
  },
  OH: {
    licensingAuthority: "Ohio Construction Industry Licensing Board",
    licensingUrl: "https://com.ohio.gov/divisions-and-programs/industrial-compliance/licensing",
    climateZone: "cold",
    populationRank: 7,
    tradeAssociation: "Ohio Home Builders Association",
    seasonalNote: "Lake-effect winter drives HVAC November-March; summer severe storms drive roofing June-August.",
    permitNote: "HVAC, electrical, plumbing, hydronics, refrigeration require state licensing; general trades local.",
    taxNote: "Sales tax on most contracting services and materials.",
  },
  OK: {
    licensingAuthority: "Oklahoma Construction Industries Board",
    licensingUrl: "https://www.ok.gov/cib",
    climateZone: "mixed-humid",
    populationRank: 28,
    tradeAssociation: "Oklahoma State Home Builders Association",
    seasonalNote: "Tornado Alley — April-June severe weather drives the biggest annual roofing and restoration spikes.",
    permitNote: "HVAC, electrical, plumbing, roofing require state licensing.",
    taxNote: "Sales tax on materials; most repair labor exempt.",
  },
  OR: {
    licensingAuthority: "Oregon Construction Contractors Board (CCB)",
    licensingUrl: "https://www.oregon.gov/ccb",
    climateZone: "marine",
    populationRank: 27,
    tradeAssociation: "Oregon Home Builders Association",
    seasonalNote: "Wet-season moisture work October-April; wildfire-driven restoration July-October.",
    permitNote: "CCB license required for any contractor; additional trade licenses for electrical, plumbing.",
    taxNote: "No state sales tax.",
  },
  PA: {
    licensingAuthority: "Pennsylvania Attorney General — Home Improvement Contractor Registration",
    licensingUrl: "https://www.attorneygeneral.gov/submit-a-complaint/hicpa",
    climateZone: "cold",
    populationRank: 5,
    tradeAssociation: "Pennsylvania Builders Association",
    seasonalNote: "Winter heating demand November-March; Philly row-house density drives steady plumbing and HVAC.",
    permitNote: "Home Improvement Contractor registration required for any residential work over $5,000 per year.",
    taxNote: "Sales tax on materials; labor on repair generally exempt.",
  },
  RI: {
    licensingAuthority: "Rhode Island Contractors' Registration and Licensing Board",
    licensingUrl: "https://crb.ri.gov",
    climateZone: "cold",
    populationRank: 43,
    tradeAssociation: "Rhode Island Builders Association",
    seasonalNote: "Coastal winter storms drive roofing and restoration; summer drives landscaping and exterior cleaning.",
    permitNote: "Contractor registration required for any residential work; trade licenses for electrical, plumbing, mechanical.",
    taxNote: "Sales tax on both labor and materials for most improvement work.",
  },
  SC: {
    licensingAuthority: "South Carolina Labor, Licensing and Regulation — Contractor's Licensing Board",
    licensingUrl: "https://llr.sc.gov",
    climateZone: "hot-humid",
    populationRank: 23,
    tradeAssociation: "Home Builders Association of South Carolina",
    seasonalNote: "Hurricane and coastal storm spikes June-November; HVAC and pest year-round.",
    permitNote: "Residential Builders license required for jobs $5,000-$200,000; General Contractor for larger.",
    taxNote: "Sales tax on materials; most repair labor exempt.",
  },
  SD: {
    licensingAuthority: "South Dakota Department of Labor and Regulation",
    licensingUrl: "https://dlr.sd.gov",
    climateZone: "very-cold",
    populationRank: 46,
    tradeAssociation: "South Dakota Home Builders Association",
    seasonalNote: "Severe storm and hail May-August; long heating season October-April.",
    permitNote: "No statewide general contractor license; plumbing and electrical state-regulated.",
    taxNote: "Sales tax and contractor's excise tax apply to contracting work.",
  },
  TN: {
    licensingAuthority: "Tennessee Board for Licensing Contractors",
    licensingUrl: "https://www.tn.gov/commerce/regboards/contractors.html",
    climateZone: "mixed-humid",
    populationRank: 15,
    tradeAssociation: "Home Builders Association of Tennessee",
    seasonalNote: "Nashville and Memphis severe storm spikes March-May; HVAC peaks June-September.",
    permitNote: "Contractor license required for any job over $25,000 — separate Home Improvement license for smaller residential.",
    taxNote: "Sales tax on materials; labor on installation taxable.",
  },
  TX: {
    licensingAuthority: "Texas Department of Licensing and Regulation (TDLR)",
    licensingUrl: "https://www.tdlr.texas.gov",
    climateZone: "hot-humid",
    populationRank: 2,
    tradeAssociation: "Texas Association of Builders",
    seasonalNote: "Summer HVAC demand May-October; hurricane season Gulf Coast June-November; severe storm Dallas-Fort Worth March-May.",
    permitNote: "Texas has no state general contractor license — HVAC, electrical, plumbing licensed by state; most others by city.",
    taxNote: "Sales tax on residential remodeling materials; labor rules differ by contract type (separated vs. lump-sum).",
  },
  UT: {
    licensingAuthority: "Utah Division of Occupational and Professional Licensing (DOPL)",
    licensingUrl: "https://dopl.utah.gov",
    climateZone: "cold",
    populationRank: 30,
    tradeAssociation: "Utah Home Builders Association",
    seasonalNote: "Heavy winter snow drives plow and heating December-March; Wasatch Front growth sustains year-round construction.",
    permitNote: "Contractor license required for any job over $3,000 including labor and materials.",
    taxNote: "Sales tax on materials; labor generally exempt.",
  },
  VT: {
    licensingAuthority: "Vermont Secretary of State — Office of Professional Regulation",
    licensingUrl: "https://sos.vermont.gov/opr",
    climateZone: "very-cold",
    populationRank: 49,
    tradeAssociation: "Home Builders & Remodelers Association of Northern Vermont",
    seasonalNote: "Long heating season October-April; ski-country rental cleaning December-March.",
    permitNote: "Electrical and plumbing state-licensed; residential contractor registration required for jobs over $3,500.",
    taxNote: "Sales tax on materials; most service labor exempt.",
  },
  VA: {
    licensingAuthority: "Virginia Department of Professional and Occupational Regulation (DPOR)",
    licensingUrl: "https://www.dpor.virginia.gov",
    climateZone: "mixed-humid",
    populationRank: 12,
    tradeAssociation: "Home Builders Association of Virginia",
    seasonalNote: "Hurricane-driven Tidewater restoration August-November; DC-metro density drives year-round demand.",
    permitNote: "Class A, B, or C contractor license based on project size; Class A required over $120,000.",
    taxNote: "Sales tax on materials; labor rules vary by contract type.",
  },
  WA: {
    licensingAuthority: "Washington State Department of Labor & Industries",
    licensingUrl: "https://lni.wa.gov",
    climateZone: "marine",
    populationRank: 13,
    tradeAssociation: "Building Industry Association of Washington",
    seasonalNote: "Wet-season moisture and moss work October-April; wildfire restoration East-side July-October.",
    permitNote: "Contractor registration required for all contractors; separate electrical and plumbing licensing.",
    taxNote: "Retail sales tax on both labor and materials for most construction.",
  },
  WV: {
    licensingAuthority: "West Virginia Division of Labor — Contractor Licensing Board",
    licensingUrl: "https://labor.wv.gov",
    climateZone: "mixed-humid",
    populationRank: 39,
    tradeAssociation: "Home Builders Association of West Virginia",
    seasonalNote: "Winter heating November-March; flood-season restoration April-June.",
    permitNote: "Contractor license required for any job over $2,500.",
    taxNote: "Sales tax on both labor and materials for most contracting.",
  },
  WI: {
    licensingAuthority: "Wisconsin Department of Safety and Professional Services",
    licensingUrl: "https://dsps.wi.gov",
    climateZone: "very-cold",
    populationRank: 20,
    tradeAssociation: "Wisconsin Builders Association",
    seasonalNote: "Long winter drives heating and snow work November-March; summer storms drive roofing May-August.",
    permitNote: "Dwelling Contractor certification required for most residential work; separate trade licenses.",
    taxNote: "Sales tax on materials; most construction labor exempt.",
  },
  WY: {
    licensingAuthority: "Wyoming Department of Workforce Services",
    licensingUrl: "https://dws.wyo.gov",
    climateZone: "very-cold",
    populationRank: 50,
    tradeAssociation: "Wyoming Contractors Association",
    seasonalNote: "Long heating season October-April; summer construction compressed into May-September.",
    permitNote: "No statewide general contractor licensing; electrical state-licensed, others city-level.",
    taxNote: "Sales tax on materials; labor generally exempt.",
  },
};

export function getStateMeta(stateAbbr: string): StateMetadata | null {
  return stateMetadata[stateAbbr.toUpperCase()] ?? null;
}
