// @ts-nocheck
import type { Park } from "./siteData";

export const beaches: Park[] = [
  /* ═══════════════════════════════════════════════════════════
     CALIFORNIA (40)
     ═══════════════════════════════════════════════════════════ */
  {
    name: "Santa Monica Beach",
    slug: "santa-monica-beach",
    city: "Santa Monica",
    citySlug: "santa-monica",
    state: "California",
    stateSlug: "california",
    description: "Santa Monica Beach offers miles of wide, flat sand perfect for laying out a mat and stretching with the Pacific breeze. The iconic pier and boardwalk atmosphere make every session feel like a California dream.",
    bestSpot: "The wide sandy area just south of the pier, away from the volleyball courts",
    touristRating: 5,
    nearbyAttractions: ["Santa Monica Pier", "Third Street Promenade", "Palisades Park"],
  },
  {
    name: "Venice Beach",
    slug: "venice-beach",
    city: "Los Angeles",
    citySlug: "los-angeles",
    state: "California",
    stateSlug: "california",
    description: "Venice Beach is the birthplace of outdoor fitness culture in California. Stretch alongside bodybuilders at Muscle Beach or find a quiet patch of sand for a focused mobility session.",
    bestSpot: "The grassy area near the recreation center, just north of Muscle Beach",
    touristRating: 5,
    nearbyAttractions: ["Venice Boardwalk", "Muscle Beach", "Abbot Kinney Boulevard"],
  },
  {
    name: "Manhattan Beach",
    slug: "manhattan-beach",
    city: "Manhattan Beach",
    citySlug: "manhattan-beach",
    state: "California",
    stateSlug: "california",
    description: "Manhattan Beach provides a cleaner, quieter alternative to Venice for beachside stretching. The firm sand near the waterline is ideal for dynamic warm-ups and deep flexibility work.",
    bestSpot: "The flat sand area near the Manhattan Beach pier, early morning for space",
    touristRating: 4,
    nearbyAttractions: ["Manhattan Beach Pier", "The Strand walkway", "Metlox Plaza"],
  },
  {
    name: "Hermosa Beach",
    slug: "hermosa-beach",
    city: "Hermosa Beach",
    citySlug: "hermosa-beach",
    state: "California",
    stateSlug: "california",
    description: "Hermosa Beach has a laid-back surf town vibe that makes stretching feel effortless. The wide beach and gentle slope give you plenty of room to set up a mat and flow through your routine.",
    bestSpot: "South of the pier where the sand is wide and the crowd thins out",
    touristRating: 4,
    nearbyAttractions: ["Hermosa Beach Pier", "The Strand", "Pier Avenue shops"],
  },
  {
    name: "Laguna Beach",
    slug: "laguna-beach",
    city: "Laguna Beach",
    citySlug: "laguna-beach",
    state: "California",
    stateSlug: "california",
    description: "Laguna Beach combines stunning cove scenery with excellent stretching conditions. The sheltered coves block wind while the sound of waves crashing against rocks creates a meditative stretching environment.",
    bestSpot: "Main Beach near the lifeguard tower where the sand is flat and wide",
    touristRating: 5,
    nearbyAttractions: ["Laguna Art Museum", "Thousand Steps Beach", "Heisler Park"],
  },
  {
    name: "Huntington Beach",
    slug: "huntington-beach",
    city: "Huntington Beach",
    citySlug: "huntington-beach",
    state: "California",
    stateSlug: "california",
    description: "Surf City USA has some of the widest beaches in Southern California, giving you endless space for a full stretching session. The consistent sunshine and ocean breeze keep you comfortable year-round.",
    bestSpot: "The wide sand north of the pier, near the fire pits",
    touristRating: 5,
    nearbyAttractions: ["Huntington Beach Pier", "International Surfing Museum", "Bolsa Chica Wetlands"],
  },
  {
    name: "Newport Beach",
    slug: "newport-beach-ca",
    city: "Newport Beach",
    citySlug: "newport-beach",
    state: "California",
    stateSlug: "california",
    description: "Newport Beach offers wide stretches of pristine sand ideal for a morning stretch routine. The upscale beachfront and calm atmosphere make it one of the best spots in Orange County for outdoor flexibility work.",
    bestSpot: "The Balboa Peninsula beach near 20th Street where the sand is widest",
    touristRating: 4,
    nearbyAttractions: ["Balboa Island", "Newport Harbor", "Fashion Island"],
  },
  {
    name: "Coronado Beach",
    slug: "coronado-beach",
    city: "Coronado",
    citySlug: "coronado",
    state: "California",
    stateSlug: "california",
    description: "Coronado Beach consistently ranks among America's best beaches, and the fine silver sand is perfect for laying out a stretch mat. The wide, flat shoreline gives you room to move freely.",
    bestSpot: "In front of the Hotel del Coronado where the sand is flat and spacious",
    touristRating: 5,
    nearbyAttractions: ["Hotel del Coronado", "Coronado Ferry Landing", "Centennial Park"],
  },
  {
    name: "La Jolla Cove",
    slug: "la-jolla-cove",
    city: "San Diego",
    citySlug: "san-diego",
    state: "California",
    stateSlug: "california",
    description: "La Jolla Cove is a stunning backdrop for stretching above the turquoise waters. The grassy park above the cove provides a flat area perfect for a mat while you take in the coastal views.",
    bestSpot: "Ellen Browning Scripps Park on the bluff above the cove",
    touristRating: 5,
    nearbyAttractions: ["La Jolla Sea Caves", "Birch Aquarium", "Torrey Pines State Reserve"],
  },
  {
    name: "Mission Beach",
    slug: "mission-beach",
    city: "San Diego",
    citySlug: "san-diego",
    state: "California",
    stateSlug: "california",
    description: "Mission Beach has a classic Southern California boardwalk feel with wide sandy shores perfect for stretching. The flat terrain and year-round sunshine make it a reliable outdoor session spot.",
    bestSpot: "The wide sand area between the jetty and Belmont Park",
    touristRating: 4,
    nearbyAttractions: ["Belmont Park", "Mission Bay", "SeaWorld San Diego"],
  },
  {
    name: "Pacific Beach",
    slug: "pacific-beach",
    city: "San Diego",
    citySlug: "san-diego",
    state: "California",
    stateSlug: "california",
    description: "Pacific Beach draws a young, active crowd that makes outdoor stretching feel right at home. The wide beach and boardwalk offer plenty of space for a full-body flexibility routine.",
    bestSpot: "Near Crystal Pier where the sand is wide and relatively uncrowded in the morning",
    touristRating: 4,
    nearbyAttractions: ["Crystal Pier", "Pacific Beach boardwalk", "Tourmaline Surfing Park"],
  },
  {
    name: "Ocean Beach San Francisco",
    slug: "ocean-beach-sf",
    city: "San Francisco",
    citySlug: "san-francisco",
    state: "California",
    stateSlug: "california",
    description: "Ocean Beach in San Francisco stretches for miles along the western edge of the city. The firm, packed sand is excellent for stretching, though you will want to dress in layers for the coastal fog.",
    bestSpot: "The flat sand near Balboa Street entrance where it is less windy",
    touristRating: 3,
    nearbyAttractions: ["Golden Gate Park", "Cliff House ruins", "Sutro Baths"],
  },
  {
    name: "Baker Beach",
    slug: "baker-beach",
    city: "San Francisco",
    citySlug: "san-francisco",
    state: "California",
    stateSlug: "california",
    description: "Baker Beach delivers Golden Gate Bridge views while you stretch. The sheltered sandy cove is a dramatic setting for outdoor flexibility sessions, with the bridge towering in the background.",
    bestSpot: "The main beach area near the parking lot with direct Golden Gate Bridge views",
    touristRating: 4,
    nearbyAttractions: ["Golden Gate Bridge", "Presidio of San Francisco", "Battery Chamberlin"],
  },
  {
    name: "Stinson Beach",
    slug: "stinson-beach",
    city: "Stinson Beach",
    citySlug: "stinson-beach",
    state: "California",
    stateSlug: "california",
    description: "Stinson Beach is a quiet Marin County escape where you can stretch with nothing but the sound of waves and seabirds. The wide sandy beach rarely gets crowded on weekday mornings.",
    bestSpot: "The main public beach area near the community center",
    touristRating: 3,
    nearbyAttractions: ["Muir Woods", "Mount Tamalpais", "Bolinas Lagoon"],
  },
  {
    name: "Santa Cruz Beach",
    slug: "santa-cruz-beach",
    city: "Santa Cruz",
    citySlug: "santa-cruz",
    state: "California",
    stateSlug: "california",
    description: "Santa Cruz Beach Boardwalk provides an energetic backdrop for beachside stretching. The wide main beach has ample space for a mat, and the surf culture crowd keeps the vibe active and welcoming.",
    bestSpot: "The wide sand area east of the boardwalk near the wharf",
    touristRating: 4,
    nearbyAttractions: ["Santa Cruz Beach Boardwalk", "Santa Cruz Wharf", "Natural Bridges State Beach"],
  },
  {
    name: "Malibu Beach",
    slug: "malibu-beach",
    city: "Malibu",
    citySlug: "malibu",
    state: "California",
    stateSlug: "california",
    description: "Malibu Beach offers a celebrity-adjacent stretching experience on some of the most famous sand in the world. Surfrider Beach at Malibu Pier is a wide, accessible spot for your mat.",
    bestSpot: "Surfrider Beach near Malibu Pier where the sand is wide and flat",
    touristRating: 5,
    nearbyAttractions: ["Malibu Pier", "Getty Villa", "Malibu Country Mart"],
  },
  {
    name: "Zuma Beach",
    slug: "zuma-beach",
    city: "Malibu",
    citySlug: "malibu",
    state: "California",
    stateSlug: "california",
    description: "Zuma Beach is one of the largest and most pristine beaches in LA County. The wide, flat sand provides an ideal surface for stretching with mountain-meets-ocean scenery.",
    bestSpot: "The wide central section of the beach near parking lot 7",
    touristRating: 4,
    nearbyAttractions: ["Point Dume", "El Matador State Beach", "Trancas Country Market"],
  },
  {
    name: "El Matador Beach",
    slug: "el-matador-beach",
    city: "Malibu",
    citySlug: "malibu",
    state: "California",
    stateSlug: "california",
    description: "El Matador Beach is a hidden gem with dramatic sea stacks and cliffs that create a magical stretching environment. The small sandy coves feel private and serene for a focused mobility session.",
    bestSpot: "The main sandy cove at the base of the staircase between the rock formations",
    touristRating: 4,
    nearbyAttractions: ["Zuma Beach", "Leo Carrillo State Park", "Point Dume"],
  },
  {
    name: "Pismo Beach",
    slug: "pismo-beach",
    city: "Pismo Beach",
    citySlug: "pismo-beach",
    state: "California",
    stateSlug: "california",
    description: "Pismo Beach on the Central Coast is a laid-back beach town with wide sand perfect for stretching. The calm atmosphere and moderate weather make it comfortable for outdoor sessions most of the year.",
    bestSpot: "The wide flat sand near the Pismo Beach pier",
    touristRating: 3,
    nearbyAttractions: ["Pismo Beach Pier", "Monarch Butterfly Grove", "Dinosaur Caves Park"],
  },
  {
    name: "Monterey Bay Beach",
    slug: "monterey-bay-beach",
    city: "Monterey",
    citySlug: "monterey",
    state: "California",
    stateSlug: "california",
    description: "Monterey Bay Beach stretches along the scenic Monterey coastline where sea otters play in the kelp beds. The sandy beach near Cannery Row provides a unique backdrop for morning stretching.",
    bestSpot: "San Carlos Beach near the Coast Guard pier where the sand is accessible",
    touristRating: 4,
    nearbyAttractions: ["Monterey Bay Aquarium", "Cannery Row", "Old Fisherman's Wharf"],
  },
  {
    name: "Carmel Beach",
    slug: "carmel-beach",
    city: "Carmel-by-the-Sea",
    citySlug: "carmel-by-the-sea",
    state: "California",
    stateSlug: "california",
    description: "Carmel Beach is a stunning white sand crescent with cypress trees framing the coastline. The wide beach and artistic community make for an inspiring stretching session with Point Lobos views.",
    bestSpot: "The wide central beach area at the foot of Ocean Avenue",
    touristRating: 5,
    nearbyAttractions: ["Point Lobos", "17-Mile Drive", "Carmel Mission"],
  },
  {
    name: "Half Moon Bay Beach",
    slug: "half-moon-bay-beach",
    city: "Half Moon Bay",
    citySlug: "half-moon-bay",
    state: "California",
    stateSlug: "california",
    description: "Half Moon Bay offers a rugged Northern California beach experience for stretching. The wide sandy beach at Half Moon Bay State Beach is sheltered enough for a comfortable mat session.",
    bestSpot: "Francis Beach area of Half Moon Bay State Beach",
    touristRating: 3,
    nearbyAttractions: ["Mavericks surf break", "Half Moon Bay downtown", "Pillar Point Harbor"],
  },
  {
    name: "Redondo Beach",
    slug: "redondo-beach",
    city: "Redondo Beach",
    citySlug: "redondo-beach",
    state: "California",
    stateSlug: "california",
    description: "Redondo Beach offers a mellow South Bay atmosphere for beachside stretching. The wide sandy shore near the pier gives you ample room for a full flexibility routine with harbor views.",
    bestSpot: "The wide sand south of the Redondo Beach Pier near Veterans Park",
    touristRating: 3,
    nearbyAttractions: ["Redondo Beach Pier", "Riviera Village", "Hopkins Wilderness Park"],
  },
  {
    name: "Dockweiler Beach",
    slug: "dockweiler-beach",
    city: "Los Angeles",
    citySlug: "los-angeles",
    state: "California",
    stateSlug: "california",
    description: "Dockweiler Beach is one of LA's most spacious beaches, stretching for miles with plenty of room for stretching. Watch planes take off from LAX overhead while you work through your flexibility routine.",
    bestSpot: "The wide sand area near the fire pits, south of the main entrance",
    touristRating: 2,
    nearbyAttractions: ["LAX Observation Deck", "Playa Vista", "Ballona Creek Bike Path"],
  },
  {
    name: "Long Beach City Beach",
    slug: "long-beach-city-beach",
    city: "Long Beach",
    citySlug: "long-beach",
    state: "California",
    stateSlug: "california",
    description: "Long Beach City Beach stretches along the calm harbor front, making it one of the most sheltered beach stretching spots in SoCal. The calm water and wide sand create a relaxed session environment.",
    bestSpot: "The wide sand near Junipero Avenue beach entrance",
    touristRating: 3,
    nearbyAttractions: ["Queen Mary", "Aquarium of the Pacific", "Shoreline Village"],
  },
  {
    name: "Seal Beach",
    slug: "seal-beach",
    city: "Seal Beach",
    citySlug: "seal-beach",
    state: "California",
    stateSlug: "california",
    description: "Seal Beach is a charming small-town beach that feels worlds away from the LA hustle. The wide, clean sand and quiet atmosphere make it a hidden gem for focused stretching sessions.",
    bestSpot: "Near the Seal Beach pier on the wide sandy main beach",
    touristRating: 3,
    nearbyAttractions: ["Seal Beach Pier", "Main Street Seal Beach", "National Wildlife Refuge"],
  },
  {
    name: "Dana Point Beach",
    slug: "dana-point-beach",
    city: "Dana Point",
    citySlug: "dana-point",
    state: "California",
    stateSlug: "california",
    description: "Dana Point offers dramatic bluff-top views and a protected beach for stretching below. Doheny State Beach at Dana Point has wide flat sand that is perfect for rolling out your mat.",
    bestSpot: "Doheny State Beach near the day-use picnic area",
    touristRating: 3,
    nearbyAttractions: ["Dana Point Harbor", "Dana Point Headlands", "Doheny State Beach"],
  },
  {
    name: "San Clemente Beach",
    slug: "san-clemente-beach",
    city: "San Clemente",
    citySlug: "san-clemente",
    state: "California",
    stateSlug: "california",
    description: "San Clemente Beach has a classic California surf town feel with a long stretch of clean sand. The pier area provides a wide, flat surface ideal for outdoor stretching with ocean views.",
    bestSpot: "The wide sand near San Clemente Pier with views of the coastline",
    touristRating: 3,
    nearbyAttractions: ["San Clemente Pier", "Avenida del Mar", "Trestles surf break"],
  },
  {
    name: "Oceanside Beach",
    slug: "oceanside-beach",
    city: "Oceanside",
    citySlug: "oceanside",
    state: "California",
    stateSlug: "california",
    description: "Oceanside Beach stretches for miles along the north San Diego County coast. The wide sand near the pier and harbor area gives you ample space for a full stretching session.",
    bestSpot: "The flat sandy area south of the Oceanside Pier",
    touristRating: 3,
    nearbyAttractions: ["Oceanside Pier", "Oceanside Harbor", "Mission San Luis Rey"],
  },
  {
    name: "Encinitas Beach",
    slug: "encinitas-beach",
    city: "Encinitas",
    citySlug: "encinitas",
    state: "California",
    stateSlug: "california",
    description: "Encinitas is a yoga and wellness hub, making it the ideal community for beachside stretching. Moonlight State Beach offers wide sand and a health-conscious crowd that embraces outdoor flexibility work.",
    bestSpot: "Moonlight State Beach where the grassy park meets the sand",
    touristRating: 3,
    nearbyAttractions: ["Self Realization Fellowship", "Swami's surf break", "San Diego Botanic Garden"],
  },
  {
    name: "Del Mar Beach",
    slug: "del-mar-beach",
    city: "Del Mar",
    citySlug: "del-mar",
    state: "California",
    stateSlug: "california",
    description: "Del Mar Beach is an upscale coastal retreat with wide, clean sand and gorgeous sunset views. The flat beach terrain and low-key crowd make it perfect for an undisturbed stretching session.",
    bestSpot: "The wide beach area at Powerhouse Park near the lifeguard station",
    touristRating: 4,
    nearbyAttractions: ["Del Mar Racetrack", "Torrey Pines State Beach", "Seagrove Park"],
  },
  {
    name: "Imperial Beach",
    slug: "imperial-beach",
    city: "Imperial Beach",
    citySlug: "imperial-beach",
    state: "California",
    stateSlug: "california",
    description: "Imperial Beach is California's most southwesterly beach with wide sand and smaller crowds than nearby San Diego spots. The open, uncrowded stretches make it great for a peaceful flexibility session.",
    bestSpot: "The wide flat sand near the Imperial Beach pier",
    touristRating: 2,
    nearbyAttractions: ["Imperial Beach Pier", "Border Field State Park", "Tijuana Estuary"],
  },
  {
    name: "Avila Beach",
    slug: "avila-beach",
    city: "Avila Beach",
    citySlug: "avila-beach",
    state: "California",
    stateSlug: "california",
    description: "Avila Beach is a sheltered Central Coast gem with warm, calm waters and wide sand. The south-facing beach stays sunny and wind-protected, creating ideal conditions for outdoor stretching.",
    bestSpot: "The main beach near the promenade where the sand is widest",
    touristRating: 3,
    nearbyAttractions: ["Avila Beach Promenade", "Port San Luis", "Sycamore Mineral Springs"],
  },
  {
    name: "Cayucos Beach",
    slug: "cayucos-beach",
    city: "Cayucos",
    citySlug: "cayucos",
    state: "California",
    stateSlug: "california",
    description: "Cayucos Beach is a quiet, old-fashioned California beach town with wide sand and a vintage pier. The uncrowded beach provides a tranquil setting for stretching with Morro Rock visible in the distance.",
    bestSpot: "The flat sand near the Cayucos pier in the morning before crowds arrive",
    touristRating: 2,
    nearbyAttractions: ["Cayucos Pier", "Estero Bluffs State Park", "Morro Rock"],
  },
  {
    name: "Morro Bay Beach",
    slug: "morro-bay-beach",
    city: "Morro Bay",
    citySlug: "morro-bay",
    state: "California",
    stateSlug: "california",
    description: "Morro Bay Beach stretches along the base of the iconic Morro Rock. The wide sand and dramatic volcanic rock backdrop create a memorable stretching environment on the Central Coast.",
    bestSpot: "The beach north of Morro Rock near the sandspit",
    touristRating: 3,
    nearbyAttractions: ["Morro Rock", "Morro Bay State Park", "Embarcadero waterfront"],
  },
  {
    name: "Bodega Bay Beach",
    slug: "bodega-bay-beach",
    city: "Bodega Bay",
    citySlug: "bodega-bay",
    state: "California",
    stateSlug: "california",
    description: "Bodega Bay offers rugged Sonoma Coast beaches where stretching meets wild natural beauty. Doran Regional Park beach has wide flat sand protected from the wind by the jetty.",
    bestSpot: "Doran Beach Regional Park where the sand is wide and wind-sheltered",
    touristRating: 3,
    nearbyAttractions: ["Bodega Head Trail", "Sonoma Coast State Park", "Bodega Bay Lodge"],
  },
  {
    name: "Fort Bragg Glass Beach",
    slug: "fort-bragg-glass-beach",
    city: "Fort Bragg",
    citySlug: "fort-bragg",
    state: "California",
    stateSlug: "california",
    description: "Glass Beach in Fort Bragg is a unique Mendocino Coast destination where sea glass pebbles line the shore. The flat areas above the beach in the park provide a stable surface for stretching with ocean views.",
    bestSpot: "The flat grassy area in MacKerricher State Park overlooking Glass Beach",
    touristRating: 3,
    nearbyAttractions: ["MacKerricher State Park", "Noyo Harbor", "Mendocino village"],
  },
  {
    name: "Crystal Cove Beach",
    slug: "crystal-cove-beach",
    city: "Laguna Beach",
    citySlug: "laguna-beach",
    state: "California",
    stateSlug: "california",
    description: "Crystal Cove State Park features pristine beaches backed by coastal bluffs and tide pools. The wide sandy coves provide a stunning natural setting for stretching with virtually no development in sight.",
    bestSpot: "The main beach cove near the historic cottages where the sand is flat",
    touristRating: 4,
    nearbyAttractions: ["Crystal Cove Historic District", "Crystal Cove tide pools", "El Moro Canyon trails"],
  },

  /* ═══════════════════════════════════════════════════════════
     FLORIDA (35)
     ═══════════════════════════════════════════════════════════ */
  {
    name: "South Beach Miami",
    slug: "south-beach-miami",
    city: "Miami Beach",
    citySlug: "miami-beach",
    state: "Florida",
    stateSlug: "florida",
    description: "South Beach is the most iconic beach in Florida, with wide white sand and art deco architecture lining the shore. The flat, spacious beach is perfect for stretching, especially at sunrise before the crowds.",
    bestSpot: "The wide sand near Lummus Park between 5th and 15th Streets",
    touristRating: 5,
    nearbyAttractions: ["Art Deco Historic District", "Ocean Drive", "Lincoln Road Mall"],
  },
  {
    name: "Fort Lauderdale Beach",
    slug: "fort-lauderdale-beach",
    city: "Fort Lauderdale",
    citySlug: "fort-lauderdale",
    state: "Florida",
    stateSlug: "florida",
    description: "Fort Lauderdale Beach offers a wide, well-maintained shoreline with a scenic wave wall promenade. The broad sandy beach gives you plenty of room for a morning stretching session in the warm Florida sun.",
    bestSpot: "The wide sand near Las Olas Boulevard beach entrance",
    touristRating: 4,
    nearbyAttractions: ["Las Olas Boulevard", "Bonnet House Museum", "Hugh Taylor Birch State Park"],
  },
  {
    name: "Clearwater Beach",
    slug: "clearwater-beach",
    city: "Clearwater",
    citySlug: "clearwater",
    state: "Florida",
    stateSlug: "florida",
    description: "Clearwater Beach consistently ranks as one of America's top beaches with fine white sand and calm Gulf waters. The wide, flat shoreline is an excellent setting for beachside stretching.",
    bestSpot: "The wide sand south of Pier 60 where the beach is broadest",
    touristRating: 5,
    nearbyAttractions: ["Pier 60", "Clearwater Marine Aquarium", "Sand Key Park"],
  },
  {
    name: "Siesta Key Beach",
    slug: "siesta-key-beach",
    city: "Sarasota",
    citySlug: "sarasota",
    state: "Florida",
    stateSlug: "florida",
    description: "Siesta Key Beach has the finest, whitest quartz sand in the world — it stays cool even in midday sun, making it comfortable for stretching anytime. The wide crescent beach offers endless space.",
    bestSpot: "The main public beach area near the pavilion where the sand is widest",
    touristRating: 5,
    nearbyAttractions: ["Siesta Key Village", "Point of Rocks", "Mote Marine Laboratory"],
  },
  {
    name: "Panama City Beach",
    slug: "panama-city-beach",
    city: "Panama City Beach",
    citySlug: "panama-city-beach",
    state: "Florida",
    stateSlug: "florida",
    description: "Panama City Beach stretches for 27 miles along the Emerald Coast with sugar-white sand. The expansive beach gives you more than enough space for stretching, and the warm Gulf waters are steps away for recovery.",
    bestSpot: "The quieter western end of the beach near St. Andrews State Park",
    touristRating: 4,
    nearbyAttractions: ["St. Andrews State Park", "Pier Park", "Shell Island"],
  },
  {
    name: "Cocoa Beach",
    slug: "cocoa-beach",
    city: "Cocoa Beach",
    citySlug: "cocoa-beach",
    state: "Florida",
    stateSlug: "florida",
    description: "Cocoa Beach is the Space Coast's premier beach with wide sand and the chance to watch rocket launches while stretching. The long, flat beach is ideal for a full flexibility routine.",
    bestSpot: "Near the Cocoa Beach Pier where the sand is wide and accessible",
    touristRating: 4,
    nearbyAttractions: ["Kennedy Space Center", "Cocoa Beach Pier", "Ron Jon Surf Shop"],
  },
  {
    name: "Daytona Beach",
    slug: "daytona-beach",
    city: "Daytona Beach",
    citySlug: "daytona-beach",
    state: "Florida",
    stateSlug: "florida",
    description: "Daytona Beach is famous for its hard-packed sand that extends far from the waterline. The firm surface is actually great for stretching — it provides stable support while keeping you close to the ocean.",
    bestSpot: "The non-driving section of beach near the boardwalk and pier",
    touristRating: 4,
    nearbyAttractions: ["Daytona Beach Boardwalk", "Daytona International Speedway", "Ponce de Leon Inlet Lighthouse"],
  },
  {
    name: "St. Pete Beach",
    slug: "st-pete-beach",
    city: "St. Petersburg",
    citySlug: "st-petersburg",
    state: "Florida",
    stateSlug: "florida",
    description: "St. Pete Beach offers some of the best Gulf Coast sand in Florida with gentle waves and warm water. The wide, white beach provides a luxurious setting for stretching with stunning sunset views.",
    bestSpot: "The wide beach area near the Don CeSar hotel where the sand is flat",
    touristRating: 5,
    nearbyAttractions: ["The Don CeSar", "Pass-a-Grille Beach", "Fort De Soto Park"],
  },
  {
    name: "Destin Beach",
    slug: "destin-beach",
    city: "Destin",
    citySlug: "destin",
    state: "Florida",
    stateSlug: "florida",
    description: "Destin's emerald waters and white sand make it one of the most beautiful stretching spots on the Gulf Coast. Henderson Beach State Park offers wide, pristine sand perfect for your mat.",
    bestSpot: "Henderson Beach State Park where the sand is wide and uncrowded",
    touristRating: 4,
    nearbyAttractions: ["Henderson Beach State Park", "Destin Harbor Boardwalk", "HarborWalk Village"],
  },
  {
    name: "Key West Beach",
    slug: "key-west-beach",
    city: "Key West",
    citySlug: "key-west",
    state: "Florida",
    stateSlug: "florida",
    description: "Key West beaches offer a tropical island vibe for stretching at the southernmost point of the continental US. Smathers Beach has the widest sand in Key West with calm turquoise water.",
    bestSpot: "Smathers Beach along the wide sandy stretch near the airport end",
    touristRating: 4,
    nearbyAttractions: ["Mallory Square", "Duval Street", "Ernest Hemingway Home"],
  },
  {
    name: "Hollywood Beach",
    slug: "hollywood-beach-fl",
    city: "Hollywood",
    citySlug: "hollywood",
    state: "Florida",
    stateSlug: "florida",
    description: "Hollywood Beach features a wide broadwalk perfect for a pre-stretch warm-up walk before you settle onto the sand. The wide beach and gentle waves create a relaxed environment for flexibility work.",
    bestSpot: "The wide sand along the Hollywood Beach Broadwalk near Johnson Street",
    touristRating: 4,
    nearbyAttractions: ["Hollywood Beach Broadwalk", "Anne Kolb Nature Center", "ArtsPark at Young Circle"],
  },
  {
    name: "Deerfield Beach",
    slug: "deerfield-beach",
    city: "Deerfield Beach",
    citySlug: "deerfield-beach",
    state: "Florida",
    stateSlug: "florida",
    description: "Deerfield Beach offers a quieter alternative to Fort Lauderdale with the same gorgeous sand and warm water. The Blue Wave-certified beach provides clean, wide sand for stretching.",
    bestSpot: "Near the Deerfield Beach International Fishing Pier on the wide sand",
    touristRating: 3,
    nearbyAttractions: ["Deerfield Beach Pier", "Quiet Waters Park", "Deerfield Island Park"],
  },
  {
    name: "Delray Beach",
    slug: "delray-beach",
    city: "Delray Beach",
    citySlug: "delray-beach",
    state: "Florida",
    stateSlug: "florida",
    description: "Delray Beach combines a vibrant downtown scene with a beautiful public beach. The wide sand near Atlantic Avenue is ideal for stretching before exploring the shops and restaurants.",
    bestSpot: "The public beach at the east end of Atlantic Avenue",
    touristRating: 4,
    nearbyAttractions: ["Atlantic Avenue", "Morikami Museum", "Wakodahatchee Wetlands"],
  },
  {
    name: "Jupiter Beach",
    slug: "jupiter-beach",
    city: "Jupiter",
    citySlug: "jupiter",
    state: "Florida",
    stateSlug: "florida",
    description: "Jupiter Beach is a dog-friendly, laid-back stretch of sand with the historic Jupiter Inlet Lighthouse nearby. The wide beach and natural dunes create a scenic stretching environment.",
    bestSpot: "The wide sand near the Jupiter Beach Park pavilion",
    touristRating: 3,
    nearbyAttractions: ["Jupiter Inlet Lighthouse", "Dubois Park", "Blowing Rocks Preserve"],
  },
  {
    name: "Palm Beach",
    slug: "palm-beach-fl",
    city: "Palm Beach",
    citySlug: "palm-beach",
    state: "Florida",
    stateSlug: "florida",
    description: "Palm Beach offers an upscale beachside stretching experience along the Gold Coast. The well-maintained public beach sections have wide sand and a sophisticated atmosphere.",
    bestSpot: "Midtown Beach on the wide sand with views of the mansions",
    touristRating: 4,
    nearbyAttractions: ["Worth Avenue", "The Breakers", "Henry Morrison Flagler Museum"],
  },
  {
    name: "Vero Beach",
    slug: "vero-beach",
    city: "Vero Beach",
    citySlug: "vero-beach",
    state: "Florida",
    stateSlug: "florida",
    description: "Vero Beach on the Treasure Coast offers uncrowded beaches with natural beauty. The quiet, wide sand is perfect for a focused stretching session without the tourist crowds.",
    bestSpot: "South Beach Park where the sand is wide and well-maintained",
    touristRating: 3,
    nearbyAttractions: ["Vero Beach Museum of Art", "McKee Botanical Garden", "Indian River Lagoon"],
  },
  {
    name: "St. Augustine Beach",
    slug: "st-augustine-beach",
    city: "St. Augustine",
    citySlug: "st-augustine",
    state: "Florida",
    stateSlug: "florida",
    description: "St. Augustine Beach combines America's oldest city charm with wide, drivable sand beaches. The flat, firm sand near the pier provides a stable surface for stretching with historic vibes.",
    bestSpot: "The wide sand near the St. Augustine Beach pier",
    touristRating: 4,
    nearbyAttractions: ["St. Augustine Historic District", "Castillo de San Marcos", "St. Augustine Lighthouse"],
  },
  {
    name: "Amelia Island Beach",
    slug: "amelia-island-beach",
    city: "Fernandina Beach",
    citySlug: "fernandina-beach",
    state: "Florida",
    stateSlug: "florida",
    description: "Amelia Island has 13 miles of uncrowded beaches on Florida's northeast tip. The wide, quiet shores are ideal for stretching in a natural setting with wild horses occasionally spotted in the dunes.",
    bestSpot: "Main Beach Park near the playground where the sand is wide and accessible",
    touristRating: 4,
    nearbyAttractions: ["Fort Clinch State Park", "Fernandina Beach downtown", "Amelia Island State Park"],
  },
  {
    name: "Anna Maria Island Beach",
    slug: "anna-maria-island-beach",
    city: "Anna Maria",
    citySlug: "anna-maria",
    state: "Florida",
    stateSlug: "florida",
    description: "Anna Maria Island is Old Florida at its best — no high-rises, just white sand and turquoise Gulf water. The relaxed island pace makes for peaceful stretching sessions on wide, uncrowded beaches.",
    bestSpot: "Manatee Beach Park where the sand is wide and facilities are nearby",
    touristRating: 4,
    nearbyAttractions: ["Bean Point", "Pine Avenue shops", "Robinson Preserve"],
  },
  {
    name: "Sanibel Island Beach",
    slug: "sanibel-island-beach",
    city: "Sanibel",
    citySlug: "sanibel",
    state: "Florida",
    stateSlug: "florida",
    description: "Sanibel Island is famous for shelling but also offers wide, natural beaches for stretching. The barrier island setting and wildlife refuge backdrop create a serene outdoor fitness environment.",
    bestSpot: "Bowman's Beach where the sand is wide and the setting is natural",
    touristRating: 4,
    nearbyAttractions: ["J.N. Ding Darling Wildlife Refuge", "Bailey-Matthews Shell Museum", "Sanibel Lighthouse"],
  },
  {
    name: "Marco Island Beach",
    slug: "marco-island-beach",
    city: "Marco Island",
    citySlug: "marco-island",
    state: "Florida",
    stateSlug: "florida",
    description: "Marco Island offers wide crescent-shaped beaches with powdery sand on the Gulf Coast. Tigertail Beach has a mix of sand and tidal flats that provide interesting terrain for outdoor stretching.",
    bestSpot: "South Marco Beach near the Marriott where the sand is widest",
    touristRating: 3,
    nearbyAttractions: ["Tigertail Beach", "Marco Island Historical Museum", "Everglades National Park"],
  },
  {
    name: "Naples Beach",
    slug: "naples-beach",
    city: "Naples",
    citySlug: "naples",
    state: "Florida",
    stateSlug: "florida",
    description: "Naples Beach is one of Florida's most pristine Gulf Coast beaches with fine white sand. The upscale but uncrowded atmosphere and spectacular sunsets make every stretching session special.",
    bestSpot: "The wide beach near the Naples Pier for the best sunset stretching",
    touristRating: 4,
    nearbyAttractions: ["Naples Pier", "Fifth Avenue South", "Naples Botanical Garden"],
  },
  {
    name: "Fort Myers Beach",
    slug: "fort-myers-beach",
    city: "Fort Myers Beach",
    citySlug: "fort-myers-beach",
    state: "Florida",
    stateSlug: "florida",
    description: "Fort Myers Beach on Estero Island has wide, gentle-sloping sand ideal for stretching. The warm Gulf water and casual beach town vibe create a welcoming environment for outdoor flexibility work.",
    bestSpot: "The wide beach near Lynn Hall Memorial Park near the pier",
    touristRating: 3,
    nearbyAttractions: ["Fort Myers Beach Pier", "Lovers Key State Park", "Times Square shops"],
  },
  {
    name: "Pensacola Beach",
    slug: "pensacola-beach",
    city: "Pensacola",
    citySlug: "pensacola",
    state: "Florida",
    stateSlug: "florida",
    description: "Pensacola Beach has sugar-white sand and emerald waters on Santa Rosa Island. The wide, uncrowded beach stretches for miles and provides excellent conditions for outdoor stretching year-round.",
    bestSpot: "The wide beach east of the Pensacola Beach pier near the quieter sections",
    touristRating: 4,
    nearbyAttractions: ["Fort Pickens", "Pensacola Beach Pier", "Gulf Islands National Seashore"],
  },
  {
    name: "Navarre Beach",
    slug: "navarre-beach",
    city: "Navarre",
    citySlug: "navarre",
    state: "Florida",
    stateSlug: "florida",
    description: "Navarre Beach is one of Florida's best-kept secrets with miles of undeveloped white sand. The uncrowded conditions and natural setting make it a premium spot for uninterrupted stretching sessions.",
    bestSpot: "The wide sand near the Navarre Beach Fishing Pier",
    touristRating: 3,
    nearbyAttractions: ["Navarre Beach Pier", "Gulf Islands National Seashore", "Navarre Beach Marine Park"],
  },
  {
    name: "Grayton Beach",
    slug: "grayton-beach",
    city: "Santa Rosa Beach",
    citySlug: "santa-rosa-beach",
    state: "Florida",
    stateSlug: "florida",
    description: "Grayton Beach State Park is consistently ranked among America's top beaches. The pristine white sand and rare coastal dune lakes create an extraordinary backdrop for stretching in nature.",
    bestSpot: "The main beach area at Grayton Beach State Park",
    touristRating: 4,
    nearbyAttractions: ["Grayton Beach State Park", "Western Lake", "30A scenic route"],
  },
  {
    name: "Seaside Beach",
    slug: "seaside-beach-fl",
    city: "Seaside",
    citySlug: "seaside",
    state: "Florida",
    stateSlug: "florida",
    description: "Seaside is the famous planned community that inspired the movie The Truman Show. The beautiful beach with white sand and calm emerald water provides a picture-perfect stretching location.",
    bestSpot: "The wide beach access near the Seaside amphitheater",
    touristRating: 4,
    nearbyAttractions: ["Seaside town center", "30A Bike Trail", "Ruskin Place Artist Colony"],
  },
  {
    name: "New Smyrna Beach",
    slug: "new-smyrna-beach",
    city: "New Smyrna Beach",
    citySlug: "new-smyrna-beach",
    state: "Florida",
    stateSlug: "florida",
    description: "New Smyrna Beach is a surf town with wide, hard-packed sand and a relaxed East Coast vibe. The long stretch of accessible beach provides ample room for stretching near the inlet.",
    bestSpot: "The wide beach near Flagler Avenue beach access",
    touristRating: 3,
    nearbyAttractions: ["Flagler Avenue shops", "Smyrna Dunes Park", "Marine Discovery Center"],
  },
  {
    name: "Melbourne Beach",
    slug: "melbourne-beach",
    city: "Melbourne",
    citySlug: "melbourne",
    state: "Florida",
    stateSlug: "florida",
    description: "Melbourne Beach on the Space Coast offers quiet, uncrowded sand for a peaceful stretching session. The natural dune-backed beach and sea turtle nesting areas add to the serene atmosphere.",
    bestSpot: "The public beach at Ocean Avenue where the sand is wide",
    touristRating: 2,
    nearbyAttractions: ["Sebastian Inlet State Park", "Archie Carr National Wildlife Refuge", "Eau Gallie Arts District"],
  },
  {
    name: "Jacksonville Beach",
    slug: "jacksonville-beach",
    city: "Jacksonville",
    citySlug: "jacksonville",
    state: "Florida",
    stateSlug: "florida",
    description: "Jacksonville Beach is a lively northeast Florida beach with a wide shoreline and active fitness culture. The long stretch of sand is popular with runners and ideal for outdoor stretching.",
    bestSpot: "The wide sand near the Jacksonville Beach pier in the morning",
    touristRating: 3,
    nearbyAttractions: ["Jacksonville Beach Pier", "Adventure Landing", "Beaches Town Center"],
  },
  {
    name: "Atlantic Beach FL",
    slug: "atlantic-beach-fl",
    city: "Jacksonville",
    citySlug: "jacksonville",
    state: "Florida",
    stateSlug: "florida",
    description: "Atlantic Beach is a quieter alternative to Jacksonville Beach with a more residential feel. The wide, clean sand and neighborhood vibe make it great for regular stretching sessions.",
    bestSpot: "The beach at the end of Atlantic Boulevard where the sand is widest",
    touristRating: 2,
    nearbyAttractions: ["Dutton Island Preserve", "Hanna Park", "Atlantic Beach Town Center"],
  },
  {
    name: "Captiva Island Beach",
    slug: "captiva-island-beach",
    city: "Captiva",
    citySlug: "captiva",
    state: "Florida",
    stateSlug: "florida",
    description: "Captiva Island is a serene barrier island just north of Sanibel with stunning Gulf sunsets. The quiet, shell-strewn beach provides a peaceful setting for stretching in a tropical paradise.",
    bestSpot: "Turner Beach at the south end of Captiva with wide sand and sunset views",
    touristRating: 4,
    nearbyAttractions: ["South Seas Island Resort", "Chapel by the Sea", "Captiva Cruises"],
  },

  /* ═══════════════════════════════════════════════════════════
     HAWAII (23)
     ═══════════════════════════════════════════════════════════ */
  {
    name: "Waikiki Beach",
    slug: "waikiki-beach",
    city: "Honolulu",
    citySlug: "honolulu",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Waikiki Beach is the world's most famous beach and an iconic spot for stretching with Diamond Head as your backdrop. Early morning sessions before the crowds arrive are unforgettable.",
    bestSpot: "The wide sand near the Duke Kahanamoku statue at sunrise",
    touristRating: 5,
    nearbyAttractions: ["Diamond Head", "Honolulu Zoo", "Kalakaua Avenue"],
  },
  {
    name: "Sunset Beach",
    slug: "sunset-beach-oahu",
    city: "Haleiwa",
    citySlug: "haleiwa",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Sunset Beach on Oahu's North Shore is legendary for big waves and wide sand. During calm summer months, the expansive beach provides a world-class stretching spot with mountain and ocean views.",
    bestSpot: "The wide sand near the main Sunset Beach parking area",
    touristRating: 4,
    nearbyAttractions: ["Pipeline surf break", "Waimea Bay", "Haleiwa Town"],
  },
  {
    name: "Kailua Beach",
    slug: "kailua-beach",
    city: "Kailua",
    citySlug: "kailua",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Kailua Beach is consistently ranked Hawaii's best beach with powdery white sand and turquoise water. The wide, flat beach is ideal for stretching with the Mokulua Islands visible offshore.",
    bestSpot: "The wide sand near the main Kailua Beach Park entrance",
    touristRating: 5,
    nearbyAttractions: ["Lanikai Beach", "Mokulua Islands", "Kailua town"],
  },
  {
    name: "Lanikai Beach",
    slug: "lanikai-beach",
    city: "Kailua",
    citySlug: "kailua",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Lanikai Beach is a postcard-perfect stretch of fine sand with crystal clear water. The intimate beach setting with twin offshore islands creates an unreal stretching environment.",
    bestSpot: "The sandy area near the mid-beach public access points",
    touristRating: 5,
    nearbyAttractions: ["Lanikai Pillbox Hike", "Mokulua Islands", "Kailua Beach Park"],
  },
  {
    name: "Ala Moana Beach",
    slug: "ala-moana-beach",
    city: "Honolulu",
    citySlug: "honolulu",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Ala Moana Beach Park is the locals' favorite beach in Honolulu with a long sandy shoreline and calm lagoon. The flat park and beach areas are popular for outdoor fitness including stretching.",
    bestSpot: "The grassy area near Magic Island peninsula for flat, stable ground",
    touristRating: 4,
    nearbyAttractions: ["Ala Moana Center", "Magic Island", "Kewalo Basin Harbor"],
  },
  {
    name: "Waimanalo Beach",
    slug: "waimanalo-beach",
    city: "Waimanalo",
    citySlug: "waimanalo",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Waimanalo Beach has the longest stretch of sand on Oahu — over three miles of pristine white beach backed by ironwood trees. The wide, uncrowded sand is a local secret for outdoor stretching.",
    bestSpot: "Waimanalo Beach Park where the sand is widest and backed by shade trees",
    touristRating: 3,
    nearbyAttractions: ["Makapuu Lighthouse Trail", "Sea Life Park", "Bellows Beach"],
  },
  {
    name: "Ka'anapali Beach",
    slug: "kaanapali-beach",
    city: "Lahaina",
    citySlug: "lahaina",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Ka'anapali Beach on Maui is a stunning three-mile stretch of golden sand with Black Rock as its landmark. The wide resort beach is perfect for stretching with views of Lanai and Molokai.",
    bestSpot: "The wide sand near Black Rock (Pu'u Keka'a) in the early morning",
    touristRating: 5,
    nearbyAttractions: ["Black Rock", "Whaler's Village", "Lahaina Historic District"],
  },
  {
    name: "Wailea Beach",
    slug: "wailea-beach",
    city: "Wailea",
    citySlug: "wailea",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Wailea Beach on Maui's south shore offers luxury resort sand with calm, clear water. The well-maintained beach and coastal walking path make it an excellent spot for a premium stretching session.",
    bestSpot: "The wide sand between the Four Seasons and Grand Wailea resorts",
    touristRating: 5,
    nearbyAttractions: ["Wailea Beach Path", "The Shops at Wailea", "Molokini Crater"],
  },
  {
    name: "Ho'okipa Beach",
    slug: "hookipa-beach",
    city: "Paia",
    citySlug: "paia",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Ho'okipa Beach is Maui's premier windsurfing spot with a wide sandy area and grassy park above. The flat park area overlooking the beach is perfect for stretching while watching world-class surf.",
    bestSpot: "The grassy overlook area above the beach with flat ground and ocean views",
    touristRating: 3,
    nearbyAttractions: ["Paia Town", "Road to Hana", "Twin Falls"],
  },
  {
    name: "Big Beach Makena",
    slug: "big-beach-makena",
    city: "Wailea",
    citySlug: "wailea",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Big Beach (Makena) is one of Maui's largest undeveloped beaches with a wide expanse of golden sand. The natural setting and dramatic cinder cone backdrop create a powerful stretching environment.",
    bestSpot: "The wide sand at the north end of the beach where it is less steep",
    touristRating: 4,
    nearbyAttractions: ["Little Beach", "Makena State Park", "Ahihi-Kinau Natural Area Reserve"],
  },
  {
    name: "Napili Bay Beach",
    slug: "napili-bay-beach",
    city: "Lahaina",
    citySlug: "lahaina",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Napili Bay is a crescent-shaped beach on Maui's west side with calm, clear water and golden sand. The sheltered bay and gentle slope make it a relaxing spot for a morning stretching routine.",
    bestSpot: "The flat sand in the center of the crescent bay",
    touristRating: 4,
    nearbyAttractions: ["Kapalua Bay", "Dragon's Teeth", "Nakalele Blowhole"],
  },
  {
    name: "Kapalua Bay Beach",
    slug: "kapalua-bay-beach",
    city: "Lahaina",
    citySlug: "lahaina",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Kapalua Bay is a sheltered, crescent-shaped beach consistently rated among Hawaii's best. The calm water and soft sand create an ideal environment for stretching in a tropical paradise.",
    bestSpot: "The wide sandy area near the south end of the bay",
    touristRating: 5,
    nearbyAttractions: ["Kapalua Coastal Trail", "Dragon's Teeth", "DT Fleming Beach"],
  },
  {
    name: "Hanalei Bay Beach",
    slug: "hanalei-bay-beach",
    city: "Hanalei",
    citySlug: "hanalei",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Hanalei Bay on Kauai is a dramatic crescent beach backed by emerald mountains. The wide sand and jaw-dropping scenery make every stretching session feel like you are in a movie.",
    bestSpot: "The wide sand near the Hanalei Pier with mountain views",
    touristRating: 5,
    nearbyAttractions: ["Hanalei Pier", "Hanalei Town", "Na Pali Coast"],
  },
  {
    name: "Poipu Beach",
    slug: "poipu-beach",
    city: "Koloa",
    citySlug: "koloa",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Poipu Beach on Kauai's sunny south shore offers warm sand and calm water perfect for beachside stretching. The crescent beach and tide pools add variety to your outdoor session.",
    bestSpot: "The wide sandy area near the main lifeguard station",
    touristRating: 4,
    nearbyAttractions: ["Spouting Horn", "Allerton Garden", "Koloa Town"],
  },
  {
    name: "Ke'e Beach",
    slug: "kee-beach",
    city: "Hanalei",
    citySlug: "hanalei",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Ke'e Beach sits at the end of the road on Kauai's north shore where the Na Pali Coast begins. The reef-protected lagoon and dramatic cliff backdrop create an otherworldly stretching environment.",
    bestSpot: "The sandy beach area near the reef-protected swimming area",
    touristRating: 4,
    nearbyAttractions: ["Kalalau Trail", "Na Pali Coast", "Limahuli Garden"],
  },
  {
    name: "Lydgate Beach",
    slug: "lydgate-beach",
    city: "Kapaa",
    citySlug: "kapaa",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Lydgate Beach Park on Kauai's east side has protected swimming pools and a wide sandy area. The family-friendly park and calm conditions make it a reliable stretching spot in any weather.",
    bestSpot: "The flat grassy area in Lydgate Beach Park near the playground",
    touristRating: 3,
    nearbyAttractions: ["Wailua Falls", "Kapaa Town", "Coconut Marketplace"],
  },
  {
    name: "Anini Beach",
    slug: "anini-beach",
    city: "Kilauea",
    citySlug: "kilauea",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Anini Beach on Kauai's north shore is protected by the longest reef in Hawaii, creating calm water and a peaceful atmosphere. The narrow but long sandy beach is a quiet escape for focused stretching.",
    bestSpot: "The sandy area near the pavilion at Anini Beach Park",
    touristRating: 3,
    nearbyAttractions: ["Kilauea Lighthouse", "Princeville", "Na Aina Kai Botanical Gardens"],
  },
  {
    name: "Hapuna Beach",
    slug: "hapuna-beach",
    city: "Waimea",
    citySlug: "waimea",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Hapuna Beach on the Big Island's Kohala Coast is one of Hawaii's largest white sand beaches. The wide, gently sloping sand and consistent sunshine make it a premier stretching destination.",
    bestSpot: "The wide sand in the center of the beach where the slope is gentle",
    touristRating: 5,
    nearbyAttractions: ["Mauna Kea Beach", "Puako Petroglyph Park", "Mauna Lani Resort"],
  },
  {
    name: "Mauna Kea Beach",
    slug: "mauna-kea-beach",
    city: "Waimea",
    citySlug: "waimea",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Mauna Kea Beach is a crescent of white sand on the Big Island's Kohala Coast. The resort-adjacent beach has calm water and wide sand ideal for a luxury stretching experience.",
    bestSpot: "The wide sandy crescent near the public beach access path",
    touristRating: 4,
    nearbyAttractions: ["Hapuna Beach", "Spencer Beach Park", "Puukohola Heiau"],
  },
  {
    name: "Punaluu Black Sand Beach",
    slug: "punaluu-black-sand-beach",
    city: "Pahala",
    citySlug: "pahala",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Punaluu Black Sand Beach is one of the most unique stretching spots in America. The jet-black volcanic sand and green sea turtles basking on shore create an unforgettable outdoor session.",
    bestSpot: "The flat black sand area near the pavilion away from the turtle resting spots",
    touristRating: 4,
    nearbyAttractions: ["Hawaii Volcanoes National Park", "Punaluu Bake Shop", "Ka Lae South Point"],
  },
  {
    name: "Kua Bay Beach",
    slug: "kua-bay-beach",
    city: "Kailua-Kona",
    citySlug: "kailua-kona",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Kua Bay (Maniniowali) is a turquoise jewel on the Big Island's Kohala Coast. The white sand beach backed by lava rock fields provides a striking contrast and beautiful stretching backdrop.",
    bestSpot: "The main sandy area of Kua Bay where the sand is flat and wide",
    touristRating: 4,
    nearbyAttractions: ["Kekaha Kai State Park", "Kaloko-Honokohau National Historical Park", "Kailua-Kona town"],
  },
  {
    name: "Hulopoe Bay Beach",
    slug: "hulopoe-bay-beach",
    city: "Lanai City",
    citySlug: "lanai-city",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Hulopoe Bay on the island of Lanai is a pristine marine preserve with golden sand and spinner dolphins. The secluded beach provides an exclusive stretching experience on a quiet Hawaiian island.",
    bestSpot: "The wide sandy area near the tide pools at the east end of the bay",
    touristRating: 4,
    nearbyAttractions: ["Sweetheart Rock", "Lanai Cat Sanctuary", "Four Seasons Lanai"],
  },
  {
    name: "Papohaku Beach",
    slug: "papohaku-beach",
    city: "Kaunakakai",
    citySlug: "kaunakakai",
    state: "Hawaii",
    stateSlug: "hawaii",
    description: "Papohaku Beach on Molokai stretches for nearly three miles and is often completely empty. The wide, golden sand and total solitude make it one of Hawaii's most peaceful stretching locations.",
    bestSpot: "Anywhere along the three-mile stretch — you will likely have it to yourself",
    touristRating: 2,
    nearbyAttractions: ["Kalaupapa National Historical Park", "Halawa Valley", "Molokai Fish & Dive"],
  },

  /* ═══════════════════════════════════════════════════════════
     EAST COAST — NEW YORK (6)
     ═══════════════════════════════════════════════════════════ */
  {
    name: "Coney Island Beach",
    slug: "coney-island-beach",
    city: "New York",
    citySlug: "new-york",
    state: "New York",
    stateSlug: "new-york",
    description: "Coney Island Beach is New York City's most famous beach with a wide sandy shore and iconic boardwalk. The expansive beach provides plenty of room for stretching alongside the city's diverse fitness crowd.",
    bestSpot: "The wide sand near the Parachute Jump away from the amusement area",
    touristRating: 4,
    nearbyAttractions: ["Luna Park", "New York Aquarium", "Nathan's Famous"],
  },
  {
    name: "Rockaway Beach",
    slug: "rockaway-beach",
    city: "New York",
    citySlug: "new-york",
    state: "New York",
    stateSlug: "new-york",
    description: "Rockaway Beach is NYC's surfing beach with miles of wide sand accessible by subway. The active outdoor culture and beachside fitness scene make stretching feel like a natural part of the landscape.",
    bestSpot: "The wide sand near Beach 90th Street where the surf and fitness crowd gathers",
    touristRating: 3,
    nearbyAttractions: ["Rockaway Beach Boardwalk", "Riis Park", "Fort Tilden"],
  },
  {
    name: "Jones Beach",
    slug: "jones-beach",
    city: "Wantagh",
    citySlug: "wantagh",
    state: "New York",
    stateSlug: "new-york",
    description: "Jones Beach is Long Island's premier public beach with miles of wide sand and excellent facilities. The expansive beach stretches over six miles, giving you plenty of space for a full stretching routine.",
    bestSpot: "The wide sand near Field 6 where it is quieter and more spacious",
    touristRating: 4,
    nearbyAttractions: ["Jones Beach Theater", "Jones Beach Nature Center", "Tobay Beach"],
  },
  {
    name: "Long Beach NY",
    slug: "long-beach-ny",
    city: "Long Beach",
    citySlug: "long-beach-ny",
    state: "New York",
    stateSlug: "new-york",
    description: "Long Beach on Long Island offers a wide sandy beach with a lively boardwalk. The accessible beach and fitness-friendly atmosphere make it a great spot for regular outdoor stretching sessions.",
    bestSpot: "The wide sand near the center of the boardwalk",
    touristRating: 3,
    nearbyAttractions: ["Long Beach Boardwalk", "Point Lookout", "Lido Beach"],
  },
  {
    name: "Fire Island Beach",
    slug: "fire-island-beach",
    city: "Bay Shore",
    citySlug: "bay-shore",
    state: "New York",
    stateSlug: "new-york",
    description: "Fire Island is a car-free barrier island with pristine beaches and a unique community. The wide, uncrowded oceanside beach is an incredible escape for stretching just a ferry ride from Long Island.",
    bestSpot: "The ocean beach near the Kismet or Ocean Beach ferry terminals",
    touristRating: 4,
    nearbyAttractions: ["Fire Island Lighthouse", "Sunken Forest", "Watch Hill"],
  },
  {
    name: "Montauk Beach",
    slug: "montauk-beach",
    city: "Montauk",
    citySlug: "montauk",
    state: "New York",
    stateSlug: "new-york",
    description: "Montauk Beach at the eastern tip of Long Island offers dramatic Atlantic coastline and wide sand. The surf town vibe and stunning ocean views create a memorable stretching destination.",
    bestSpot: "Ditch Plains Beach where the wide sand meets the surf culture",
    touristRating: 4,
    nearbyAttractions: ["Montauk Point Lighthouse", "Camp Hero State Park", "Ditch Plains"],
  },

  /* ═══════════════════════════════════════════════════════════
     EAST COAST — NEW JERSEY (9)
     ═══════════════════════════════════════════════════════════ */
  {
    name: "Atlantic City Beach",
    slug: "atlantic-city-beach",
    city: "Atlantic City",
    citySlug: "atlantic-city",
    state: "New Jersey",
    stateSlug: "new-jersey",
    description: "Atlantic City Beach stretches wide and free along the famous boardwalk. The broad, sandy beach is surprisingly spacious and provides an energetic setting for stretching with the casino skyline behind you.",
    bestSpot: "The wide sand near the Steel Pier area where the beach is broadest",
    touristRating: 4,
    nearbyAttractions: ["Atlantic City Boardwalk", "Steel Pier", "Absecon Lighthouse"],
  },
  {
    name: "Cape May Beach",
    slug: "cape-may-beach",
    city: "Cape May",
    citySlug: "cape-may",
    state: "New Jersey",
    stateSlug: "new-jersey",
    description: "Cape May Beach is a Victorian-era shore town with wide, clean beaches and a charming promenade. The well-maintained sand and historic B&B backdrop make stretching feel like a coastal retreat.",
    bestSpot: "The beach near the promenade at Beach Avenue with views of Victorian homes",
    touristRating: 4,
    nearbyAttractions: ["Cape May Lighthouse", "Washington Street Mall", "Emlen Physick Estate"],
  },
  {
    name: "Asbury Park Beach",
    slug: "asbury-park-beach",
    city: "Asbury Park",
    citySlug: "asbury-park",
    state: "New Jersey",
    stateSlug: "new-jersey",
    description: "Asbury Park Beach has been reborn as a hip, artsy shore destination with a revitalized boardwalk. The wide beach and creative energy make it a fun, unique setting for outdoor stretching.",
    bestSpot: "The wide sand near Convention Hall where the beach is spacious",
    touristRating: 4,
    nearbyAttractions: ["Asbury Park Boardwalk", "Stone Pony", "Convention Hall"],
  },
  {
    name: "Long Branch Beach",
    slug: "long-branch-beach",
    city: "Long Branch",
    citySlug: "long-branch",
    state: "New Jersey",
    stateSlug: "new-jersey",
    description: "Long Branch Beach offers a wide shore with an upscale boardwalk and ocean views. The Pier Village area provides a modern coastal setting for stretching with dining and shopping nearby.",
    bestSpot: "The wide sand near Pier Village where the beach is well-maintained",
    touristRating: 3,
    nearbyAttractions: ["Pier Village", "Seven Presidents Oceanfront Park", "Great Lawn"],
  },
  {
    name: "Wildwood Beach",
    slug: "wildwood-beach",
    city: "Wildwood",
    citySlug: "wildwood",
    state: "New Jersey",
    stateSlug: "new-jersey",
    description: "Wildwood Beach is one of the widest free beaches on the East Coast — over 1,000 feet of sand in some spots. The massive beach means you will always find room for a stretching mat.",
    bestSpot: "The wide sand away from the boardwalk where you have maximum space",
    touristRating: 4,
    nearbyAttractions: ["Wildwood Boardwalk", "Morey's Piers", "Doo Wop Experience Museum"],
  },
  {
    name: "Ocean City NJ Beach",
    slug: "ocean-city-nj-beach",
    city: "Ocean City",
    citySlug: "ocean-city-nj",
    state: "New Jersey",
    stateSlug: "new-jersey",
    description: "Ocean City NJ is America's Greatest Family Resort with clean, wide beaches and a classic boardwalk. The family-friendly atmosphere and spacious sand make stretching enjoyable for all ages.",
    bestSpot: "The wide beach near the Music Pier for a spacious, clean stretch area",
    touristRating: 4,
    nearbyAttractions: ["Ocean City Boardwalk", "Music Pier", "Gillian's Wonderland Pier"],
  },
  {
    name: "Point Pleasant Beach",
    slug: "point-pleasant-beach",
    city: "Point Pleasant Beach",
    citySlug: "point-pleasant-beach",
    state: "New Jersey",
    stateSlug: "new-jersey",
    description: "Point Pleasant Beach has a wide sandy shore and a classic Jersey Shore boardwalk. The spacious beach provides a nice setting for stretching with a lively boardwalk atmosphere nearby.",
    bestSpot: "The wide sand south of Jenkinson's Boardwalk",
    touristRating: 3,
    nearbyAttractions: ["Jenkinson's Boardwalk", "Jenkinson's Aquarium", "Manasquan Inlet"],
  },
  {
    name: "Seaside Heights Beach",
    slug: "seaside-heights-beach",
    city: "Seaside Heights",
    citySlug: "seaside-heights",
    state: "New Jersey",
    stateSlug: "new-jersey",
    description: "Seaside Heights Beach is a classic Jersey Shore destination with wide sand and a bustling boardwalk. The spacious beach offers plenty of room for stretching, especially in the morning hours.",
    bestSpot: "The wide sand near the Casino Pier area in the early morning",
    touristRating: 3,
    nearbyAttractions: ["Casino Pier", "Seaside Heights Boardwalk", "Island Beach State Park"],
  },
  {
    name: "Sandy Hook Beach",
    slug: "sandy-hook-beach",
    city: "Highlands",
    citySlug: "highlands",
    state: "New Jersey",
    stateSlug: "new-jersey",
    description: "Sandy Hook is a national recreation area with pristine beaches and views of the Manhattan skyline. The wide, uncrowded beaches and natural setting offer a unique stretching experience near NYC.",
    bestSpot: "North Beach area with wide sand and views of the NYC skyline",
    touristRating: 4,
    nearbyAttractions: ["Sandy Hook Lighthouse", "Fort Hancock", "Gateway National Recreation Area"],
  },

  /* ═══════════════════════════════════════════════════════════
     EAST COAST — MASSACHUSETTS (5)
     ═══════════════════════════════════════════════════════════ */
  {
    name: "Cape Cod National Seashore",
    slug: "cape-cod-national-seashore",
    city: "Provincetown",
    citySlug: "provincetown",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    description: "Cape Cod National Seashore has some of the most dramatic beaches in New England with towering dunes and wild Atlantic surf. The wide sandy beaches provide a stunning backdrop for stretching.",
    bestSpot: "Race Point Beach where the wide sand stretches toward the lighthouse",
    touristRating: 5,
    nearbyAttractions: ["Pilgrim Monument", "Race Point Lighthouse", "Provincetown Art Galleries"],
  },
  {
    name: "Nantucket Beach",
    slug: "nantucket-beach",
    city: "Nantucket",
    citySlug: "nantucket",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    description: "Nantucket Island beaches offer pristine sand and a quintessential New England atmosphere. The wide south shore beaches provide excellent stretching conditions with gentle waves and warm summer sand.",
    bestSpot: "Surfside Beach where the sand is wide and the surf is gentle",
    touristRating: 5,
    nearbyAttractions: ["Nantucket Whaling Museum", "Cisco Brewers", "Great Point Lighthouse"],
  },
  {
    name: "Martha's Vineyard Beach",
    slug: "marthas-vineyard-beach",
    city: "Edgartown",
    citySlug: "edgartown",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    description: "Martha's Vineyard offers diverse beaches from dramatic Aquinnah Cliffs to gentle Edgartown shores. South Beach in Edgartown has wide sand ideal for a summer stretching session.",
    bestSpot: "South Beach Edgartown where the wide Atlantic-facing sand provides ample room",
    touristRating: 5,
    nearbyAttractions: ["Aquinnah Cliffs", "Edgartown Harbor", "Flying Horses Carousel"],
  },
  {
    name: "Revere Beach",
    slug: "revere-beach",
    city: "Revere",
    citySlug: "revere",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    description: "Revere Beach is America's first public beach, established in 1896, and accessible by subway from Boston. The wide crescent of sand provides a convenient stretching spot for city dwellers.",
    bestSpot: "The wide sand near the central pavilion on the Revere Beach Boulevard side",
    touristRating: 3,
    nearbyAttractions: ["Revere Beach Boulevard", "Kelly's Roast Beef", "Wonderland MBTA station"],
  },
  {
    name: "Crane Beach",
    slug: "crane-beach",
    city: "Ipswich",
    citySlug: "ipswich",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    description: "Crane Beach is a pristine barrier beach on the North Shore with over four miles of sand backed by dunes and the Crane Estate. The natural beauty and wide sand make it a top stretching destination.",
    bestSpot: "The wide main beach area near the bathhouse where the sand is flat",
    touristRating: 4,
    nearbyAttractions: ["Crane Estate", "Castle Hill", "Ipswich River Wildlife Sanctuary"],
  },

  /* ═══════════════════════════════════════════════════════════
     EAST COAST — CAROLINAS & GEORGIA (9)
     ═══════════════════════════════════════════════════════════ */
  {
    name: "Myrtle Beach",
    slug: "myrtle-beach",
    city: "Myrtle Beach",
    citySlug: "myrtle-beach",
    state: "South Carolina",
    stateSlug: "south-carolina",
    description: "Myrtle Beach stretches for 60 miles along the Grand Strand with wide, flat sand perfect for stretching. The warm weather and long beach season give you months of outdoor flexibility time.",
    bestSpot: "The wide sand near the Second Avenue Pier in the early morning",
    touristRating: 4,
    nearbyAttractions: ["Broadway at the Beach", "Myrtle Beach Boardwalk", "SkyWheel"],
  },
  {
    name: "Wrightsville Beach",
    slug: "wrightsville-beach",
    city: "Wilmington",
    citySlug: "wilmington",
    state: "North Carolina",
    stateSlug: "north-carolina",
    description: "Wrightsville Beach near Wilmington is a family-friendly barrier island with wide, clean sand. The active community embraces outdoor fitness, making beachside stretching a natural fit.",
    bestSpot: "The wide beach near Johnnie Mercer's Pier",
    touristRating: 3,
    nearbyAttractions: ["Johnnie Mercer's Pier", "Wrightsville Beach Loop", "Airlie Gardens"],
  },
  {
    name: "Outer Banks Beach",
    slug: "outer-banks-beach",
    city: "Kill Devil Hills",
    citySlug: "kill-devil-hills",
    state: "North Carolina",
    stateSlug: "north-carolina",
    description: "The Outer Banks offer wild, windswept beaches stretching for over 100 miles. The wide sand near Kill Devil Hills provides ample space for stretching where the Wright Brothers first flew.",
    bestSpot: "The wide beach near the Avalon Pier in Kill Devil Hills",
    touristRating: 4,
    nearbyAttractions: ["Wright Brothers Memorial", "Jockey's Ridge State Park", "Bodie Island Lighthouse"],
  },
  {
    name: "Hilton Head Beach",
    slug: "hilton-head-beach",
    city: "Hilton Head Island",
    citySlug: "hilton-head-island",
    state: "South Carolina",
    stateSlug: "south-carolina",
    description: "Hilton Head Island has 12 miles of wide, flat beaches perfect for biking and stretching. The hard-packed sand at low tide provides a firm surface ideal for a full stretching routine.",
    bestSpot: "Coligny Beach Park where the sand is wide and facilities are excellent",
    touristRating: 4,
    nearbyAttractions: ["Harbour Town Lighthouse", "Sea Pines Forest Preserve", "Coastal Discovery Museum"],
  },
  {
    name: "Folly Beach",
    slug: "folly-beach",
    city: "Charleston",
    citySlug: "charleston",
    state: "South Carolina",
    stateSlug: "south-carolina",
    description: "Folly Beach is Charleston's beach town with a laid-back surf vibe and wide sandy shores. The accessible beach and quirky local culture make stretching feel effortless and fun.",
    bestSpot: "The wide sand near the Folly Beach Pier at the center of the island",
    touristRating: 3,
    nearbyAttractions: ["Folly Beach Pier", "Morris Island Lighthouse", "Charleston downtown"],
  },
  {
    name: "Isle of Palms Beach",
    slug: "isle-of-palms-beach",
    city: "Charleston",
    citySlug: "charleston",
    state: "South Carolina",
    stateSlug: "south-carolina",
    description: "Isle of Palms is a residential beach community near Charleston with wide, clean sand and a quieter atmosphere. The spacious beach provides a relaxed setting for stretching near the Lowcountry.",
    bestSpot: "The wide beach near the Isle of Palms County Park",
    touristRating: 3,
    nearbyAttractions: ["Isle of Palms County Park", "Wild Dunes Resort", "Sullivan's Island"],
  },
  {
    name: "Kiawah Island Beach",
    slug: "kiawah-island-beach",
    city: "Charleston",
    citySlug: "charleston",
    state: "South Carolina",
    stateSlug: "south-carolina",
    description: "Kiawah Island has 10 miles of pristine, uncrowded beach backed by maritime forest. The wide, natural beach and wildlife sightings create a serene environment for premium outdoor stretching.",
    bestSpot: "Beachwalker Park at the west end of the island with wide public sand",
    touristRating: 4,
    nearbyAttractions: ["Beachwalker Park", "Kiawah River", "Angel Oak Tree"],
  },
  {
    name: "Pawleys Island Beach",
    slug: "pawleys-island-beach",
    city: "Pawleys Island",
    citySlug: "pawleys-island",
    state: "South Carolina",
    stateSlug: "south-carolina",
    description: "Pawleys Island is one of the oldest beach resorts on the East Coast with wide, natural beaches. The arrogantly shabby charm and quiet sand make it an ideal retreat for focused stretching.",
    bestSpot: "The wide public beach near the south end of the island",
    touristRating: 3,
    nearbyAttractions: ["Huntington Beach State Park", "Brookgreen Gardens", "Atalaya Castle"],
  },
  {
    name: "Tybee Island Beach",
    slug: "tybee-island-beach",
    city: "Savannah",
    citySlug: "savannah",
    state: "Georgia",
    stateSlug: "georgia",
    description: "Tybee Island is Savannah's beach with wide sand and a classic pier. The laid-back coastal Georgia atmosphere and warm water make it a welcoming spot for stretching near the historic city.",
    bestSpot: "The wide sand near the Tybee Island Pier and Pavilion",
    touristRating: 3,
    nearbyAttractions: ["Tybee Island Lighthouse", "Fort Screven", "Savannah Historic District"],
  },

  /* ═══════════════════════════════════════════════════════════
     EAST COAST — VIRGINIA, MARYLAND, CT, RI (6)
     ═══════════════════════════════════════════════════════════ */
  {
    name: "Virginia Beach Oceanfront",
    slug: "virginia-beach-oceanfront",
    city: "Virginia Beach",
    citySlug: "virginia-beach",
    state: "Virginia",
    stateSlug: "virginia",
    description: "Virginia Beach has a three-mile boardwalk and wide sandy beach perfect for stretching. The active fitness scene along the oceanfront makes outdoor flexibility work a natural part of the culture.",
    bestSpot: "The wide sand near 24th Street where the beach is spacious",
    touristRating: 4,
    nearbyAttractions: ["Virginia Beach Boardwalk", "Virginia Aquarium", "First Landing State Park"],
  },
  {
    name: "Ocean City MD Beach",
    slug: "ocean-city-md-beach",
    city: "Ocean City",
    citySlug: "ocean-city-md",
    state: "Maryland",
    stateSlug: "maryland",
    description: "Ocean City Maryland has 10 miles of wide, free public beach with a classic boardwalk. The expansive sand and lively summer atmosphere provide an energetic setting for beachside stretching.",
    bestSpot: "The wide sand near the inlet area where the beach is broadest",
    touristRating: 4,
    nearbyAttractions: ["Ocean City Boardwalk", "Assateague Island", "Trimper's Rides"],
  },
  {
    name: "Narragansett Beach",
    slug: "narragansett-beach",
    city: "Narragansett",
    citySlug: "narragansett",
    state: "Rhode Island",
    stateSlug: "rhode-island",
    description: "Narragansett Town Beach is one of Rhode Island's finest with wide sand and the historic Towers landmark. The New England charm and wide beach make it a lovely stretching spot.",
    bestSpot: "The wide sand near The Towers at the north end of the beach",
    touristRating: 3,
    nearbyAttractions: ["The Towers", "Point Judith Lighthouse", "Narragansett Seawall"],
  },
  {
    name: "Misquamicut Beach",
    slug: "misquamicut-beach",
    city: "Westerly",
    citySlug: "westerly",
    state: "Rhode Island",
    stateSlug: "rhode-island",
    description: "Misquamicut State Beach is a long barrier beach in Westerly with wide sand and Atlantic waves. The expansive beach and family atmosphere provide a pleasant setting for stretching sessions.",
    bestSpot: "The wide sand near the state beach pavilion where the beach is broadest",
    touristRating: 3,
    nearbyAttractions: ["Watch Hill", "Atlantic Beach Park", "Westerly downtown"],
  },
  {
    name: "Hammonasset Beach",
    slug: "hammonasset-beach",
    city: "Madison",
    citySlug: "madison",
    state: "Connecticut",
    stateSlug: "connecticut",
    description: "Hammonasset Beach State Park is Connecticut's largest shoreline park with two miles of beach. The wide, flat sand and natural setting make it the best stretching beach in the state.",
    bestSpot: "The wide beach near the Meigs Point nature center",
    touristRating: 3,
    nearbyAttractions: ["Meigs Point Nature Center", "Hammonasset trails", "Madison downtown"],
  },
  {
    name: "Westerly Beach",
    slug: "westerly-beach",
    city: "Westerly",
    citySlug: "westerly",
    state: "Rhode Island",
    stateSlug: "rhode-island",
    description: "Westerly's Watch Hill area offers pristine beaches with a classic New England seaside feel. The wide sand and elegant coastal setting provide an upscale environment for outdoor stretching.",
    bestSpot: "East Beach in Watch Hill where the sand is wide and less crowded",
    touristRating: 4,
    nearbyAttractions: ["Watch Hill Lighthouse", "Flying Horse Carousel", "Napatree Point"],
  },

  /* ═══════════════════════════════════════════════════════════
     GULF COAST — TEXAS (5)
     ═══════════════════════════════════════════════════════════ */
  {
    name: "Galveston Beach",
    slug: "galveston-beach",
    city: "Galveston",
    citySlug: "galveston",
    state: "Texas",
    stateSlug: "texas",
    description: "Galveston Beach is Houston's closest beach with miles of sand along the seawall. The wide beach and historic Pleasure Pier create a lively Gulf Coast setting for stretching.",
    bestSpot: "Stewart Beach where the sand is wide and well-maintained",
    touristRating: 3,
    nearbyAttractions: ["Galveston Island Historic Pleasure Pier", "The Strand", "Moody Gardens"],
  },
  {
    name: "South Padre Island Beach",
    slug: "south-padre-island-beach",
    city: "South Padre Island",
    citySlug: "south-padre-island",
    state: "Texas",
    stateSlug: "texas",
    description: "South Padre Island is Texas's tropical beach with wide, warm sand and Gulf water. The miles of undeveloped beach north of town provide a peaceful setting for stretching.",
    bestSpot: "The wide sand near Andy Bowie Park for a quieter experience",
    touristRating: 4,
    nearbyAttractions: ["South Padre Island Birding Center", "Schlitterbahn Waterpark", "Sea Turtle Inc."],
  },
  {
    name: "Port Aransas Beach",
    slug: "port-aransas-beach",
    city: "Port Aransas",
    citySlug: "port-aransas",
    state: "Texas",
    stateSlug: "texas",
    description: "Port Aransas is a charming Texas beach town on Mustang Island with wide, drivable sand. The laid-back fishing village atmosphere and gentle Gulf waves make it relaxing for stretching.",
    bestSpot: "The wide beach near Horace Caldwell Pier",
    touristRating: 3,
    nearbyAttractions: ["Port Aransas Jetty", "San Jose Island", "University of Texas Marine Science Institute"],
  },
  {
    name: "Mustang Island Beach",
    slug: "mustang-island-beach",
    city: "Corpus Christi",
    citySlug: "corpus-christi",
    state: "Texas",
    stateSlug: "texas",
    description: "Mustang Island State Park offers five miles of pristine Gulf Coast beach backed by dunes. The wide sand and natural setting provide an excellent location for stretching near Corpus Christi.",
    bestSpot: "The main beach area of Mustang Island State Park",
    touristRating: 3,
    nearbyAttractions: ["Mustang Island State Park", "Padre Island National Seashore", "Corpus Christi Bay"],
  },
  {
    name: "Corpus Christi Beach",
    slug: "corpus-christi-beach",
    city: "Corpus Christi",
    citySlug: "corpus-christi",
    state: "Texas",
    stateSlug: "texas",
    description: "Corpus Christi's North Beach offers wide sand with views of the harbor bridge and the Texas State Aquarium. The accessible beach is a convenient stretching spot in the Sparkling City by the Sea.",
    bestSpot: "North Beach near the USS Lexington where the sand is wide",
    touristRating: 3,
    nearbyAttractions: ["USS Lexington", "Texas State Aquarium", "Corpus Christi Marina"],
  },

  /* ═══════════════════════════════════════════════════════════
     GULF COAST — LOUISIANA, ALABAMA, MISSISSIPPI (5)
     ═══════════════════════════════════════════════════════════ */
  {
    name: "Grand Isle Beach",
    slug: "grand-isle-beach",
    city: "Grand Isle",
    citySlug: "grand-isle",
    state: "Louisiana",
    stateSlug: "louisiana",
    description: "Grand Isle is Louisiana's only inhabited barrier island with a long stretch of Gulf beach. The wide sand and fishing village atmosphere provide a unique Louisiana stretching experience.",
    bestSpot: "Grand Isle State Park beach where the sand is maintained and wide",
    touristRating: 2,
    nearbyAttractions: ["Grand Isle State Park", "Grand Isle fishing charters", "Fort Livingston"],
  },
  {
    name: "Gulf Shores Beach",
    slug: "gulf-shores-beach",
    city: "Gulf Shores",
    citySlug: "gulf-shores",
    state: "Alabama",
    stateSlug: "alabama",
    description: "Gulf Shores has white sand and turquoise water that rivals Florida's best beaches. The wide, clean beach provides excellent conditions for stretching on Alabama's stunning Gulf Coast.",
    bestSpot: "The wide sand at Gulf State Park Pier beach area",
    touristRating: 4,
    nearbyAttractions: ["Gulf State Park", "The Wharf", "Hugh S. Branyon Backcountry Trail"],
  },
  {
    name: "Orange Beach",
    slug: "orange-beach-al",
    city: "Orange Beach",
    citySlug: "orange-beach",
    state: "Alabama",
    stateSlug: "alabama",
    description: "Orange Beach adjoins Gulf Shores with equally beautiful white sand and clear water. The slightly less crowded beach and excellent facilities make it a great spot for focused stretching.",
    bestSpot: "The wide beach at the public access near Cotton Bayou",
    touristRating: 3,
    nearbyAttractions: ["Alabama Gulf Coast Zoo", "The Wharf", "Perdido Pass"],
  },
  {
    name: "Biloxi Beach",
    slug: "biloxi-beach",
    city: "Biloxi",
    citySlug: "biloxi",
    state: "Mississippi",
    stateSlug: "mississippi",
    description: "Biloxi Beach stretches along the Mississippi Gulf Coast with wide, man-made sand and calm water. The beachfront casino skyline and gentle waves create a unique stretching atmosphere.",
    bestSpot: "The wide sand along Beach Boulevard near the Biloxi Lighthouse",
    touristRating: 3,
    nearbyAttractions: ["Biloxi Lighthouse", "Beauvoir Jefferson Davis Home", "Biloxi casinos"],
  },
  {
    name: "Long Beach MS",
    slug: "long-beach-ms",
    city: "Long Beach",
    citySlug: "long-beach-ms",
    state: "Mississippi",
    stateSlug: "mississippi",
    description: "Long Beach, Mississippi offers a quiet Gulf Coast beach with wide sand and a small-town charm. The peaceful atmosphere and gentle water make it a relaxed stretching spot away from casino crowds.",
    bestSpot: "The wide beach along the harbor near the Long Beach town center",
    touristRating: 2,
    nearbyAttractions: ["Long Beach Harbor", "Friendship Oak", "Gulf Islands Waterpark"],
  },

  /* ═══════════════════════════════════════════════════════════
     PACIFIC NORTHWEST — OREGON (6)
     ═══════════════════════════════════════════════════════════ */
  {
    name: "Cannon Beach",
    slug: "cannon-beach",
    city: "Cannon Beach",
    citySlug: "cannon-beach",
    state: "Oregon",
    stateSlug: "oregon",
    description: "Cannon Beach is one of America's most scenic beaches with the iconic Haystack Rock rising from the sand. The wide, flat beach provides a dramatic stretching backdrop unlike anywhere else.",
    bestSpot: "The wide sand near Haystack Rock at low tide when the beach is expansive",
    touristRating: 5,
    nearbyAttractions: ["Haystack Rock", "Ecola State Park", "Cannon Beach downtown"],
  },
  {
    name: "Pacific City Beach",
    slug: "pacific-city-beach",
    city: "Pacific City",
    citySlug: "pacific-city",
    state: "Oregon",
    stateSlug: "oregon",
    description: "Pacific City Beach is dominated by the massive Cape Kiwanda sandstone cape. The wide sand and dramatic dune landscape create an adventurous setting for stretching on the Oregon Coast.",
    bestSpot: "The wide flat sand near Cape Kiwanda with dune views",
    touristRating: 3,
    nearbyAttractions: ["Cape Kiwanda", "Pelican Brewing Company", "Pacific City Dory Fleet"],
  },
  {
    name: "Seaside Beach Oregon",
    slug: "seaside-beach-oregon",
    city: "Seaside",
    citySlug: "seaside",
    state: "Oregon",
    stateSlug: "oregon",
    description: "Seaside Beach is Oregon's classic resort beach town with a wide sandy shore and promenade. The Turnaround and wide beach provide accessible stretching spots near shops and restaurants.",
    bestSpot: "The wide sand near the Seaside Promenade and Turnaround",
    touristRating: 4,
    nearbyAttractions: ["Seaside Promenade", "Seaside Aquarium", "Tillamook Head Trail"],
  },
  {
    name: "Lincoln City Beach",
    slug: "lincoln-city-beach",
    city: "Lincoln City",
    citySlug: "lincoln-city",
    state: "Oregon",
    stateSlug: "oregon",
    description: "Lincoln City stretches for seven miles along the Oregon Coast with wide sandy beaches. The kite-flying capital of the world has steady breezes and wide sand perfect for an invigorating stretch session.",
    bestSpot: "The wide sand at D River Wayside in the center of town",
    touristRating: 3,
    nearbyAttractions: ["D River Wayside", "Devils Lake", "Chinook Winds Casino"],
  },
  {
    name: "Newport Beach Oregon",
    slug: "newport-beach-oregon",
    city: "Newport",
    citySlug: "newport",
    state: "Oregon",
    stateSlug: "oregon",
    description: "Newport Beach on the central Oregon Coast offers wide sand with views of the Yaquina Bay Bridge. The vibrant fishing port and aquarium nearby make it a full-day coastal stretching destination.",
    bestSpot: "Nye Beach where the sand is wide and the neighborhood is charming",
    touristRating: 3,
    nearbyAttractions: ["Oregon Coast Aquarium", "Yaquina Head Lighthouse", "Bayfront District"],
  },
  {
    name: "Bandon Beach",
    slug: "bandon-beach",
    city: "Bandon",
    citySlug: "bandon",
    state: "Oregon",
    stateSlug: "oregon",
    description: "Bandon Beach is dotted with dramatic sea stacks and offers some of the most photogenic sand on the Oregon Coast. The wide beach and rock formations create a magical setting for stretching.",
    bestSpot: "Face Rock Viewpoint area where the beach is wide and the sea stacks frame the view",
    touristRating: 4,
    nearbyAttractions: ["Face Rock", "Bandon Marsh Wildlife Refuge", "Coquille River Lighthouse"],
  },

  /* ═══════════════════════════════════════════════════════════
     PACIFIC NORTHWEST — WASHINGTON (5)
     ═══════════════════════════════════════════════════════════ */
  {
    name: "Ruby Beach",
    slug: "ruby-beach",
    city: "Forks",
    citySlug: "forks",
    state: "Washington",
    stateSlug: "washington",
    description: "Ruby Beach in Olympic National Park is a wild, driftwood-strewn beach with sea stacks and tide pools. The dramatic Pacific Northwest scenery makes it one of the most unique stretching spots in America.",
    bestSpot: "The flat sandy area among the driftwood near the main beach access",
    touristRating: 4,
    nearbyAttractions: ["Olympic National Park", "Hoh Rain Forest", "Kalaloch Lodge"],
  },
  {
    name: "Rialto Beach",
    slug: "rialto-beach",
    city: "Forks",
    citySlug: "forks",
    state: "Washington",
    stateSlug: "washington",
    description: "Rialto Beach is a rugged Olympic Coast beach known for dramatic sea stacks and driftwood. The wide, pebbly beach near the parking area provides a wild outdoor stretching experience.",
    bestSpot: "The wider sandy section near the trailhead before the rocks begin",
    touristRating: 3,
    nearbyAttractions: ["Hole-in-the-Wall", "La Push", "Olympic National Park"],
  },
  {
    name: "Long Beach Washington",
    slug: "long-beach-wa",
    city: "Long Beach",
    citySlug: "long-beach-wa",
    state: "Washington",
    stateSlug: "washington",
    description: "Long Beach claims to be the longest beach in the world at 28 miles. The wide, flat sand stretches endlessly, giving you all the space you could want for an outdoor stretching session.",
    bestSpot: "The wide flat sand near the Long Beach boardwalk access",
    touristRating: 3,
    nearbyAttractions: ["Long Beach Boardwalk", "Cape Disappointment State Park", "World Kite Museum"],
  },
  {
    name: "Alki Beach Seattle",
    slug: "alki-beach-seattle",
    city: "Seattle",
    citySlug: "seattle",
    state: "Washington",
    stateSlug: "washington",
    description: "Alki Beach is Seattle's urban beach with stunning views of the downtown skyline across Elliott Bay. The sandy shore and paved path provide excellent options for stretching with a city backdrop.",
    bestSpot: "The sandy beach area near the Alki Beach bathhouse with skyline views",
    touristRating: 4,
    nearbyAttractions: ["Alki Point Lighthouse", "Seattle skyline views", "West Seattle Junction"],
  },
  {
    name: "Golden Gardens Beach",
    slug: "golden-gardens-beach",
    city: "Seattle",
    citySlug: "seattle",
    state: "Washington",
    stateSlug: "washington",
    description: "Golden Gardens is a beloved Seattle beach park with sandy shores and Olympic Mountain views. The flat beach and grassy areas above provide multiple options for stretching with sunset views.",
    bestSpot: "The flat sandy area near the fire pits with views of the Olympic Mountains",
    touristRating: 3,
    nearbyAttractions: ["Golden Gardens Park", "Ballard Locks", "Ballard neighborhood"],
  },

  /* ═══════════════════════════════════════════════════════════
     GREAT LAKES (11)
     ═══════════════════════════════════════════════════════════ */
  {
    name: "Sleeping Bear Dunes Beach",
    slug: "sleeping-bear-dunes-beach",
    city: "Traverse City",
    citySlug: "traverse-city",
    state: "Michigan",
    stateSlug: "michigan",
    description: "Sleeping Bear Dunes National Lakeshore has towering dunes and crystal-clear Lake Michigan water. The wide sandy beaches below the dunes provide a breathtaking setting for stretching in nature.",
    bestSpot: "Glen Haven Beach where the sand is wide and the dunes tower above",
    touristRating: 5,
    nearbyAttractions: ["Sleeping Bear Dunes", "Glen Arbor", "Empire Bluffs Trail"],
  },
  {
    name: "Holland Beach",
    slug: "holland-beach",
    city: "Holland",
    citySlug: "holland",
    state: "Michigan",
    stateSlug: "michigan",
    description: "Holland State Park Beach has wide sand and the iconic Big Red Lighthouse. The clean Lake Michigan water and wide beach provide a scenic Michigan setting for stretching.",
    bestSpot: "The wide sand at Holland State Park with Big Red Lighthouse views",
    touristRating: 4,
    nearbyAttractions: ["Big Red Lighthouse", "Windmill Island Gardens", "Holland downtown"],
  },
  {
    name: "Grand Haven Beach",
    slug: "grand-haven-beach",
    city: "Grand Haven",
    citySlug: "grand-haven",
    state: "Michigan",
    stateSlug: "michigan",
    description: "Grand Haven State Park Beach offers wide sand along Lake Michigan with a musical fountain and lighthouses. The spacious beach and vibrant waterfront create an excellent stretching destination.",
    bestSpot: "The wide beach at Grand Haven State Park near the pier",
    touristRating: 4,
    nearbyAttractions: ["Grand Haven Lighthouse", "Musical Fountain", "Grand Haven boardwalk"],
  },
  {
    name: "South Haven Beach",
    slug: "south-haven-beach",
    city: "South Haven",
    citySlug: "south-haven",
    state: "Michigan",
    stateSlug: "michigan",
    description: "South Haven Beach is a charming Lake Michigan beach town with wide sand and a red lighthouse. The gentle shoreline and small-town atmosphere make stretching here feel like a summer vacation.",
    bestSpot: "South Beach near the South Haven Lighthouse where the sand is wide",
    touristRating: 3,
    nearbyAttractions: ["South Haven Lighthouse", "Kal-Haven Trail", "Michigan Maritime Museum"],
  },
  {
    name: "St. Joseph Beach",
    slug: "st-joseph-beach",
    city: "St. Joseph",
    citySlug: "st-joseph",
    state: "Michigan",
    stateSlug: "michigan",
    description: "St. Joseph's Silver Beach offers wide sand along Lake Michigan with twin lighthouses and a bluff-top park. The well-maintained beach and stunning sunsets create a premium stretching spot.",
    bestSpot: "Silver Beach near the inner and outer lighthouses where the sand is wide",
    touristRating: 4,
    nearbyAttractions: ["Silver Beach Carousel", "Curious Kids' Museum", "Bluff Park"],
  },
  {
    name: "North Avenue Beach Chicago",
    slug: "north-avenue-beach-chicago",
    city: "Chicago",
    citySlug: "chicago",
    state: "Illinois",
    stateSlug: "illinois",
    description: "North Avenue Beach is Chicago's premier urban beach with wide sand and a dramatic skyline backdrop. The fitness-friendly atmosphere with the beach house gym makes it a natural spot for stretching.",
    bestSpot: "The wide sand south of the steamship-shaped beach house",
    touristRating: 5,
    nearbyAttractions: ["Lincoln Park Zoo", "Lakefront Trail", "Lincoln Park"],
  },
  {
    name: "Oak Street Beach Chicago",
    slug: "oak-street-beach-chicago",
    city: "Chicago",
    citySlug: "chicago",
    state: "Illinois",
    stateSlug: "illinois",
    description: "Oak Street Beach is Chicago's Gold Coast beach with stunning views of the Magnificent Mile skyline. The intimate urban beach setting and active crowd make it perfect for a downtown stretching session.",
    bestSpot: "The sandy area near the Oak Street Beach entrance off Lake Shore Drive",
    touristRating: 4,
    nearbyAttractions: ["Magnificent Mile", "Navy Pier", "John Hancock Center"],
  },
  {
    name: "Bradford Beach Milwaukee",
    slug: "bradford-beach-milwaukee",
    city: "Milwaukee",
    citySlug: "milwaukee",
    state: "Wisconsin",
    stateSlug: "wisconsin",
    description: "Bradford Beach is Milwaukee's main urban beach on Lake Michigan with wide sand and volleyball courts. The active summer scene and city backdrop make it a great spot for outdoor stretching.",
    bestSpot: "The wide sand near the tiki bar area where the beach is spacious",
    touristRating: 3,
    nearbyAttractions: ["Milwaukee Art Museum", "North Point Lighthouse", "East Side neighborhood"],
  },
  {
    name: "Headlands Beach",
    slug: "headlands-beach",
    city: "Mentor",
    citySlug: "mentor",
    state: "Ohio",
    stateSlug: "ohio",
    description: "Headlands Beach State Park is Ohio's longest natural beach on Lake Erie. The wide, sandy shore and natural dunes provide a surprisingly beautiful stretching spot on the Great Lakes.",
    bestSpot: "The wide main beach area near the parking lot where the sand is broadest",
    touristRating: 3,
    nearbyAttractions: ["Headlands Dunes State Nature Preserve", "Fairport Harbor Lighthouse", "Mentor Lagoons"],
  },
  {
    name: "Edgewater Beach Cleveland",
    slug: "edgewater-beach-cleveland",
    city: "Cleveland",
    citySlug: "cleveland",
    state: "Ohio",
    stateSlug: "ohio",
    description: "Edgewater Beach in Cleveland offers wide sand and skyline views along Lake Erie. The recently renovated park and beach provide an excellent urban stretching location with sunset lake views.",
    bestSpot: "The wide sand at the main beach area with Cleveland skyline views",
    touristRating: 3,
    nearbyAttractions: ["Edgewater Park", "Cleveland skyline", "West Side Market"],
  },
  {
    name: "Indiana Dunes Beach",
    slug: "indiana-dunes-beach",
    city: "Michigan City",
    citySlug: "michigan-city",
    state: "Indiana",
    stateSlug: "indiana",
    description: "Indiana Dunes National Park has 15 miles of Lake Michigan shoreline with sandy beaches and towering dunes. The diverse landscape and wide beaches create a unique stretching environment near Chicago.",
    bestSpot: "West Beach where the sand is wide and the dunes provide wind shelter",
    touristRating: 4,
    nearbyAttractions: ["Indiana Dunes National Park", "Mount Baldy", "Portage Lakefront"],
  },
];
