import type { City } from "./siteData";

export const citiesBatch3: City[] = [
  // ─── Michigan ───
  {
    name: "Detroit",
    slug: "detroit",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 639111,
    description: "Detroit is a city defined by resilience and reinvention, where a storied automotive legacy meets a thriving creative renaissance along the riverfront and revitalized downtown corridors.",
    landmarks: ["Detroit Institute of Arts", "Ford Field", "Belle Isle Park"],
    vibe: "Gritty revival energy with world-class culture and deep neighborhood pride",
  },
  {
    name: "Grand Rapids",
    slug: "grand-rapids",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 198917,
    description: "Grand Rapids blends Midwestern warmth with a booming craft beer scene and internationally recognized art installations, making it one of Michigan's most livable cities.",
    landmarks: ["Frederik Meijer Gardens", "Grand Rapids Art Museum", "John Ball Zoo"],
    vibe: "Creative and community-driven with a craft beer culture that rivals any coast",
  },
  {
    name: "Warren",
    slug: "warren",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 139387,
    description: "Warren is metro Detroit's largest suburb, home to General Motors' Technical Center and a sprawling network of parks that keep residents active year-round.",
    landmarks: ["General Motors Technical Center", "Warren Community Center", "Halmich Park"],
    vibe: "Working-class suburban stability with strong auto-industry roots",
  },
  {
    name: "Sterling Heights",
    slug: "sterling-heights",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 134346,
    description: "Sterling Heights is a diverse Macomb County suburb known for its thriving Middle Eastern and Chaldean communities, excellent parks system, and family-friendly atmosphere.",
    landmarks: ["Dodge Park", "Lakeside Mall", "Sterling Heights Nature Center"],
    vibe: "Culturally diverse suburban community with strong family values and green spaces",
  },
  {
    name: "Lansing",
    slug: "lansing",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 112644,
    description: "Michigan's capital city sits at the confluence of the Grand and Red Cedar rivers, blending state government energy with a lively college-town atmosphere thanks to nearby Michigan State.",
    landmarks: ["Michigan State Capitol", "Impression 5 Science Center", "Potter Park Zoo"],
    vibe: "Capital city hustle softened by river trails and a tight-knit local culture",
  },
  {
    name: "Ann Arbor",
    slug: "ann-arbor",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 123851,
    description: "Ann Arbor is a progressive university city centered around the University of Michigan, renowned for its vibrant arts scene, independent bookstores, and farm-to-table dining culture.",
    landmarks: ["University of Michigan", "Michigan Stadium", "Nichols Arboretum"],
    vibe: "Intellectually charged and walkable with a fiercely independent local spirit",
  },
  {
    name: "Flint",
    slug: "flint",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 95943,
    description: "Flint carries the legacy of the American auto industry and a community that has shown extraordinary resilience through decades of economic and infrastructure challenges.",
    landmarks: ["Flint Institute of Arts", "Sloan Museum", "Crossroads Village"],
    vibe: "Resilient and community-focused with deep blue-collar pride",
  },
  {
    name: "Dearborn",
    slug: "dearborn",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 109976,
    description: "Dearborn is the hometown of Ford Motor Company and home to one of the largest Arab American communities in the nation, creating a uniquely rich cultural tapestry.",
    landmarks: ["The Henry Ford Museum", "Greenfield Village", "Arab American National Museum"],
    vibe: "Culturally rich auto-heritage city with outstanding Middle Eastern dining",
  },
  {
    name: "Livonia",
    slug: "livonia",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 94520,
    description: "Livonia is a well-maintained western suburb of Detroit prized for its top-rated schools, safe neighborhoods, and convenient access to major freeways.",
    landmarks: ["Eddie Edgar Ice Arena", "Livonia Recreation Center", "Greenmead Historical Park"],
    vibe: "Classic Midwestern suburb with excellent schools and manicured parks",
  },
  {
    name: "Troy",
    slug: "troy",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 87294,
    description: "Troy is Oakland County's corporate hub, home to numerous Fortune 500 offices and upscale shopping at Somerset Collection, paired with highly ranked public schools.",
    landmarks: ["Somerset Collection", "Troy Historic Village", "Boulan Park"],
    vibe: "Affluent corporate suburb with top schools and upscale retail",
  },
  {
    name: "Westland",
    slug: "westland",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 82578,
    description: "Westland is a Wayne County suburb offering affordable housing, an expansive parks system, and easy commuter access to Detroit's job centers.",
    landmarks: ["Westland Shopping Center", "Tattan Park", "Mike Modano Ice Arena"],
    vibe: "Affordable and family-friendly with solid parks and suburban convenience",
  },
  {
    name: "Farmington Hills",
    slug: "farmington-hills",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 83986,
    description: "Farmington Hills is a prosperous Oakland County community consistently ranked among the safest cities in Michigan, with rolling terrain, nature preserves, and excellent schools.",
    landmarks: ["Heritage Park", "Marvin's Marvelous Mechanical Museum", "Founders Sports Park"],
    vibe: "Safe, leafy suburb with a quiet sophistication and strong community events",
  },
  {
    name: "Kalamazoo",
    slug: "kalamazoo",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 72990,
    description: "Kalamazoo is a vibrant college city anchored by Western Michigan University, famous for its Kalamazoo Promise scholarship program and a walkable downtown brewery district.",
    landmarks: ["Kalamazoo Institute of Arts", "Bell's Brewery", "Bronson Park"],
    vibe: "College-town energy with craft brewing culture and progressive community programs",
  },
  {
    name: "Wyoming",
    slug: "wyoming-mi",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 76810,
    description: "Wyoming is Grand Rapids' largest suburb, offering diverse neighborhoods, a strong public school system, and affordable living in West Michigan's booming metro area.",
    landmarks: ["Lamar Park", "Wyoming Public Library", "Gezon Park"],
    vibe: "Diverse and affordable suburb riding Grand Rapids' growth wave",
  },
  {
    name: "Southfield",
    slug: "southfield",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 76188,
    description: "Southfield is a major office and cultural hub in Oakland County with a significant African American population and one of metro Detroit's largest concentrations of corporate headquarters.",
    landmarks: ["Southfield Civic Center", "Lawrence Technological University", "Burgh Historical Park"],
    vibe: "Corporate-suburban blend with diverse culture and professional energy",
  },
  {
    name: "Rochester Hills",
    slug: "rochester-hills",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 76572,
    description: "Rochester Hills is an upscale Oakland County community set among rolling hills and the Clinton River, home to Oakland University and scenic trail systems.",
    landmarks: ["Meadow Brook Hall", "Paint Creek Trail", "Borden Park"],
    vibe: "Affluent and nature-rich with university culture and historic estates",
  },
  {
    name: "Taylor",
    slug: "taylor",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 62114,
    description: "Taylor is a Downriver community south of Detroit known for its Heritage Park festival grounds, affordable housing, and strong blue-collar community identity.",
    landmarks: ["Heritage Park", "Taylor Sportsplex", "Sheridan Park"],
    vibe: "Hardworking Downriver community with affordable living and local pride",
  },
  {
    name: "Pontiac",
    slug: "pontiac",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 62431,
    description: "Pontiac is an Oakland County city undergoing revitalization, with a growing arts district and entrepreneurial spirit breathing new life into its historic downtown.",
    landmarks: ["Phoenix Center", "Pontiac Silverdome site", "Great Lakes Crossing Outlets"],
    vibe: "Urban revitalization energy with entrepreneurial spirit and arts momentum",
  },
  {
    name: "St. Clair Shores",
    slug: "st-clair-shores",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 60070,
    description: "St. Clair Shores is a lakeside Macomb County community on Lake St. Clair, cherished for its marinas, waterfront dining, and relaxed suburban pace.",
    landmarks: ["Lake St. Clair Metropark", "Blossom Heath Park", "St. Clair Shores Civic Arena"],
    vibe: "Waterfront suburban charm with boating culture and lakeside relaxation",
  },
  {
    name: "Royal Oak",
    slug: "royal-oak",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 59112,
    description: "Royal Oak is metro Detroit's go-to destination for nightlife, dining, and arts, with a walkable downtown packed with independent restaurants, galleries, and the renowned Detroit Zoo.",
    landmarks: ["Detroit Zoo", "Royal Oak Music Theatre", "Normandy Oaks Park"],
    vibe: "Trendy and walkable with buzzing nightlife and a creative downtown scene",
  },
  {
    name: "Novi",
    slug: "novi",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 61984,
    description: "Novi is a fast-growing Oakland County suburb with top-rated schools, the massive Twelve Oaks Mall, and a diverse population fueled by technology and automotive professionals.",
    landmarks: ["Twelve Oaks Mall", "Novi Town Center", "Lakeshore Park"],
    vibe: "Modern and multicultural suburb with upscale retail and rapid growth",
  },
  {
    name: "Dearborn Heights",
    slug: "dearborn-heights",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 55630,
    description: "Dearborn Heights is a residential Wayne County suburb offering affordable homes, community parks, and convenient proximity to both Detroit and Ann Arbor corridors.",
    landmarks: ["Canfield Community Center", "Eton Senior Center", "Berwyn Park"],
    vibe: "Quiet residential suburb with affordable family living and easy commuter access",
  },
  {
    name: "Battle Creek",
    slug: "battle-creek",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 51534,
    description: "Battle Creek is the Cereal City, headquarters of Kellogg's and a community shaped by food manufacturing heritage, Fort Custer, and a revitalizing downtown district.",
    landmarks: ["Kellogg's Cereal City", "Binder Park Zoo", "Leila Arboretum"],
    vibe: "Small-city charm with cereal capital heritage and military community ties",
  },
  {
    name: "Saginaw",
    slug: "saginaw",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 44202,
    description: "Saginaw sits along the Saginaw River in Michigan's Great Lakes Bay Region, working to revitalize its downtown while preserving its rich lumber and automotive history.",
    landmarks: ["Japanese Cultural Center & Tea House", "Castle Museum of Saginaw County", "Ojibway Island"],
    vibe: "River city with industrial roots and a community focused on renewal",
  },
  {
    name: "Kentwood",
    slug: "kentwood",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 54175,
    description: "Kentwood is a diverse and growing suburb south of Grand Rapids, known for its excellent parks, strong school system, and welcoming immigrant communities.",
    landmarks: ["Kentwood Activities Center", "Pinewood Park", "East Paris Nature Park"],
    vibe: "Welcoming and diverse suburb with community parks and Grand Rapids proximity",
  },
  {
    name: "East Lansing",
    slug: "east-lansing",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 48437,
    description: "East Lansing is the home of Michigan State University, a spirited college town with Big Ten athletics, a lively Grand River Avenue strip, and abundant green space.",
    landmarks: ["Michigan State University", "Spartan Stadium", "MSU Broad Art Museum"],
    vibe: "Quintessential Big Ten college town with Spartan pride and youthful energy",
  },
  {
    name: "Roseville",
    slug: "roseville-mi",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 49036,
    description: "Roseville is a Macomb County suburb along Gratiot Avenue, offering affordable homes, a strong recreation department, and convenient access to metro Detroit amenities.",
    landmarks: ["Roseville Recreation Center", "Huron Park", "Macomb Place Mall"],
    vibe: "Affordable and accessible Macomb County suburb with neighborhood warmth",
  },
  {
    name: "Portage",
    slug: "portage",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 49730,
    description: "Portage is Kalamazoo's southern neighbor, a well-planned city with an award-winning trail system, corporate employers like Stryker, and a strong sense of community.",
    landmarks: ["Celery Flats Interpretive Center", "Milham Park", "Portage Creek Bicentennial Park"],
    vibe: "Well-planned suburban community with corporate presence and excellent trails",
  },
  {
    name: "Midland",
    slug: "midland",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 42029,
    description: "Midland is the global headquarters of Dow Chemical, a company town that has invested deeply in arts, sciences, and public gardens for its residents.",
    landmarks: ["Dow Gardens", "Midland Center for the Arts", "Whiting Forest Canopy Walk"],
    vibe: "Corporate-cultured small city with world-class gardens and science education",
  },
  {
    name: "Lincoln Park",
    slug: "lincoln-park",
    state: "Michigan",
    stateSlug: "michigan",
    stateAbbr: "MI",
    population: 36714,
    description: "Lincoln Park is a close-knit Downriver community with affordable housing, a revitalized downtown strip, and strong civic pride among its working-class residents.",
    landmarks: ["Lincoln Park Civic Center", "Kennedy Memorial Park", "Fort Street corridor"],
    vibe: "Tight-knit Downriver community with working-class grit and neighborhood loyalty",
  },

  // ─── Minnesota ───
  {
    name: "Minneapolis",
    slug: "minneapolis",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 429954,
    description: "Minneapolis is a cultural powerhouse on the Mississippi River, home to a thriving theater scene second only to New York, world-class museums, and an extensive urban bike trail network.",
    landmarks: ["Mill City Museum", "Walker Art Center", "Chain of Lakes"],
    vibe: "Progressive and active with year-round outdoor culture despite brutal winters",
  },
  {
    name: "Saint Paul",
    slug: "saint-paul",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 311527,
    description: "Minnesota's capital city charms with its Victorian architecture, Summit Avenue mansions, and a quieter, more historic counterpart to its Twin City across the river.",
    landmarks: ["Minnesota State Capitol", "Cathedral of Saint Paul", "Como Park Zoo"],
    vibe: "Historic and stately with a quieter elegance than its twin across the river",
  },
  {
    name: "Rochester",
    slug: "rochester-mn",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 121395,
    description: "Rochester is dominated by the Mayo Clinic, one of the world's leading medical centers, giving this southern Minnesota city an international, health-focused character.",
    landmarks: ["Mayo Clinic", "Soldiers Field", "Silver Lake Park"],
    vibe: "World-class medical hub with international residents and Midwestern hospitality",
  },
  {
    name: "Bloomington",
    slug: "bloomington-mn",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 89987,
    description: "Bloomington is home to the Mall of America, the nation's largest shopping and entertainment complex, along with the Minnesota Valley National Wildlife Refuge.",
    landmarks: ["Mall of America", "Minnesota Valley National Wildlife Refuge", "Hyland Lake Park Reserve"],
    vibe: "Retail destination city with surprising natural beauty along the Minnesota River",
  },
  {
    name: "Duluth",
    slug: "duluth",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 90936,
    description: "Duluth is a stunning port city perched on the hillsides above Lake Superior, beloved for its craft brewery scene, outdoor recreation, and the iconic Aerial Lift Bridge.",
    landmarks: ["Aerial Lift Bridge", "Glensheen Mansion", "Park Point Beach"],
    vibe: "Rugged lakeside beauty with craft beer culture and four-season outdoor adventure",
  },
  {
    name: "Brooklyn Park",
    slug: "brooklyn-park",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 86478,
    description: "Brooklyn Park is one of Minnesota's most diverse suburbs, a northwest metro community with extensive parks, community programs, and growing cultural amenities.",
    landmarks: ["Edinburgh USA Golf Course", "Brooklyn Park Sports Dome", "Palmer Lake Park"],
    vibe: "Diverse and family-oriented suburb with strong parks and recreation programs",
  },
  {
    name: "Plymouth",
    slug: "plymouth-mn",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 81026,
    description: "Plymouth is an affluent western suburb dotted with lakes and corporate campuses, offering top-rated schools and a high quality of life in the Twin Cities metro.",
    landmarks: ["French Regional Park", "Plymouth Ice Center", "Medicine Lake"],
    vibe: "Affluent lake-studded suburb with corporate polish and outdoor amenities",
  },
  {
    name: "Maple Grove",
    slug: "maple-grove",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 80489,
    description: "Maple Grove is a fast-growing northwest suburb with a vibrant town center, excellent healthcare facilities, and family-friendly neighborhoods among preserved wetlands.",
    landmarks: ["Maple Grove Town Center", "Central Park", "Elm Creek Park Reserve"],
    vibe: "Modern suburban growth with smart planning and abundant nature preserves",
  },
  {
    name: "Woodbury",
    slug: "woodbury",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 75102,
    description: "Woodbury is the Twin Cities' premier eastern suburb, consistently ranked among the best places to live in Minnesota for its schools, safety, and extensive trail system.",
    landmarks: ["Carver Lake Park", "HealthEast Sports Center", "Ojibway Park"],
    vibe: "Top-rated suburban living with trails, safety, and family-first amenities",
  },
  {
    name: "St. Cloud",
    slug: "st-cloud",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 68881,
    description: "St. Cloud is central Minnesota's regional hub along the Mississippi River, home to St. Cloud State University and the famous granite quarries that built much of the state.",
    landmarks: ["Munsinger Gardens", "St. Cloud State University", "Quarry Park"],
    vibe: "College-town river city with granite heritage and central Minnesota charm",
  },
  {
    name: "Eagan",
    slug: "eagan",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 68262,
    description: "Eagan is a south metro suburb anchored by the Twin Cities Premium Outlets and a nationally recognized parks system with over 60 miles of trails.",
    landmarks: ["Lebanon Hills Regional Park", "Cascade Bay Waterpark", "Caponi Art Park"],
    vibe: "Active suburban community with outstanding parks and convenient metro access",
  },
  {
    name: "Eden Prairie",
    slug: "eden-prairie",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 64198,
    description: "Eden Prairie is a southwestern suburb that has been named Money Magazine's best place to live in America, offering corporate headquarters, top schools, and abundant green space.",
    landmarks: ["Staring Lake Park", "Eden Prairie Center", "Bryant Lake Regional Park"],
    vibe: "Best-place-to-live accolades with corporate campuses and pristine parks",
  },
  {
    name: "Coon Rapids",
    slug: "coon-rapids",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 64855,
    description: "Coon Rapids is a large north metro suburb along the Mississippi River, known for the Coon Rapids Dam Regional Park and a strong network of community athletic facilities.",
    landmarks: ["Coon Rapids Dam Regional Park", "Bunker Hills Regional Park", "Bunker Hills Wave Pool"],
    vibe: "River-adjacent suburb with outdoor recreation focus and family neighborhoods",
  },
  {
    name: "Burnsville",
    slug: "burnsville",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 64317,
    description: "Burnsville is a south metro community at the junction of major highways, offering diverse dining, the Burnsville Performing Arts Center, and proximity to the Minnesota River bluffs.",
    landmarks: ["Alimagnet Park", "Burnsville Performing Arts Center", "Crystal Lake"],
    vibe: "Diverse crossroads suburb with accessible dining and performing arts culture",
  },
  {
    name: "Blaine",
    slug: "blaine",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 70222,
    description: "Blaine is a rapidly growing north metro suburb known for the National Sports Center, one of the largest amateur sports complexes in the world.",
    landmarks: ["National Sports Center", "Blaine Wetland Sanctuary", "Aquatore Park"],
    vibe: "Sports-focused suburb with rapid residential growth and family appeal",
  },
  {
    name: "Lakeville",
    slug: "lakeville",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 69490,
    description: "Lakeville is a booming southern suburb where Dakota County's rolling farmland meets suburban development, prized for its lakes, trails, and highly rated school district.",
    landmarks: ["Antlers Park", "Lake Marion", "Lakeville Area Arts Center"],
    vibe: "Fast-growing lakeside suburb with top schools and small-town charm at its edges",
  },
  {
    name: "Minnetonka",
    slug: "minnetonka",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 53781,
    description: "Minnetonka wraps around the western shores of Lake Minnetonka, offering lakeside luxury, corporate campuses including UnitedHealth Group, and scenic Hennepin County parks.",
    landmarks: ["Lake Minnetonka", "Minnehaha Creek", "Purgatory Creek Park"],
    vibe: "Lakeside affluence with corporate headquarters and scenic waterfront living",
  },
  {
    name: "Apple Valley",
    slug: "apple-valley",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 55135,
    description: "Apple Valley is a south metro suburb best known as home of the Minnesota Zoo, with a community-centered atmosphere, strong schools, and diverse neighborhoods.",
    landmarks: ["Minnesota Zoo", "Lebanon Hills Regional Park", "Apple Valley Aquatic Center"],
    vibe: "Zoo-town pride with community spirit and accessible south-metro living",
  },
  {
    name: "Edina",
    slug: "edina",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 54824,
    description: "Edina is one of the Twin Cities' most affluent communities, centered around the upscale Galleria shopping district and known for elite public schools and manicured neighborhoods.",
    landmarks: ["Centennial Lakes Park", "Galleria Edina", "Braemar Golf Course"],
    vibe: "Polished and affluent with top-tier schools and upscale retail destinations",
  },
  {
    name: "St. Louis Park",
    slug: "st-louis-park",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 50010,
    description: "St. Louis Park is a first-ring suburb just west of Minneapolis, offering urban convenience with suburban space, a connected trail system, and diverse housing options.",
    landmarks: ["The Shops at West End", "Aquila Park", "Wolfe Park"],
    vibe: "Urban-suburban hybrid with walkable districts and easy Minneapolis access",
  },
  {
    name: "Mankato",
    slug: "mankato",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 44488,
    description: "Mankato is southern Minnesota's regional center along the Minnesota River bend, home to Minnesota State University and a lively downtown with local shops and restaurants.",
    landmarks: ["Minneopa State Park", "Riverfront Park", "Minnesota State University Mankato"],
    vibe: "College-town river community serving as southern Minnesota's cultural anchor",
  },
  {
    name: "Moorhead",
    slug: "moorhead",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 44505,
    description: "Moorhead sits on the Minnesota side of the Fargo-Moorhead metro, home to Minnesota State University Moorhead and Concordia College along the Red River.",
    landmarks: ["Hjemkomst Center", "Regional Science Center", "Moorhead River Walk"],
    vibe: "College-town twin across the Red River with Scandinavian heritage and prairie grit",
  },
  {
    name: "Shakopee",
    slug: "shakopee",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 43107,
    description: "Shakopee is a booming southwest metro suburb that hosts Valleyfair amusement park and Canterbury Park racetrack, blending entertainment venues with rapid residential growth.",
    landmarks: ["Valleyfair", "Canterbury Park", "Memorial Park"],
    vibe: "Entertainment-destination suburb with explosive growth and family attractions",
  },
  {
    name: "Maplewood",
    slug: "maplewood",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 42090,
    description: "Maplewood is an east metro suburb adjacent to Saint Paul, offering a blend of affordable housing, the Maplewood Mall retail hub, and easy access to Twin Cities employment centers.",
    landmarks: ["Maplewood Mall", "Phalen-Keller Regional Park", "Wakefield Park"],
    vibe: "Practical east-metro suburb with retail convenience and Saint Paul proximity",
  },
  {
    name: "Cottage Grove",
    slug: "cottage-grove",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 37428,
    description: "Cottage Grove is a growing Washington County community along the Mississippi River bluffs, attracting families with its trails, parks, and small-town feel within metro reach.",
    landmarks: ["Grey Cloud Dunes SNA", "Kingston Park", "Mississippi River bluffs"],
    vibe: "River-bluff community with small-town feel and growing suburban energy",
  },
  {
    name: "Richfield",
    slug: "richfield",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 36407,
    description: "Richfield is a diverse first-ring suburb between Minneapolis and Bloomington, home to Best Buy headquarters and a walkable community with strong neighborhood identity.",
    landmarks: ["Wood Lake Nature Center", "Veterans Memorial Park", "Richfield Ice Arena"],
    vibe: "Diverse first-ring suburb with corporate presence and strong neighborhood bonds",
  },
  {
    name: "Inver Grove Heights",
    slug: "inver-grove-heights",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 38267,
    description: "Inver Grove Heights is a south metro community along the Mississippi River with a mix of established neighborhoods and new development, plus scenic river valley views.",
    landmarks: ["Heritage Village Park", "Inver Wood Golf Course", "Pine Bend Bluffs SNA"],
    vibe: "River-valley suburb balancing established neighborhoods with steady growth",
  },
  {
    name: "Andover",
    slug: "andover",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 38530,
    description: "Andover is a growing north metro community where suburban neighborhoods give way to preserved wetlands and open spaces, offering a semi-rural feel close to Twin Cities jobs.",
    landmarks: ["Kelsey Round Lake Park", "Andover Community Center", "Rum River Central Regional Park"],
    vibe: "Semi-rural north metro living with wetland preserves and growing subdivisions",
  },
  {
    name: "Rosemount",
    slug: "rosemount",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 28009,
    description: "Rosemount is a southern Dakota County community known for its annual Irish festival, strong schools, and a hometown atmosphere surrounded by protected green corridors.",
    landmarks: ["Steeple Center", "Schwarz Pond Park", "Robert Trail Library"],
    vibe: "Small-town suburban charm with Irish heritage and strong community events",
  },
  {
    name: "Savage",
    slug: "savage",
    state: "Minnesota",
    stateSlug: "minnesota",
    stateAbbr: "MN",
    population: 34044,
    description: "Savage is a scenic Scott County community along the Minnesota River, offering wooded neighborhoods, the popular McColl Pond trail system, and proximity to the Twin Cities.",
    landmarks: ["McColl Pond Environmental Learning Center", "Hidden Valley Park", "Minnesota River bluffs"],
    vibe: "Wooded river community with nature trails and a quiet family-centric lifestyle",
  },

  // ─── Mississippi ───
  {
    name: "Jackson",
    slug: "jackson-ms",
    state: "Mississippi",
    stateSlug: "mississippi",
    stateAbbr: "MS",
    population: 153701,
    description: "Jackson is Mississippi's capital and cultural heart, home to a rich civil rights history, a thriving blues and soul music scene, and the state's premier museums and universities.",
    landmarks: ["Mississippi Civil Rights Museum", "Old Capitol Museum", "Fondren District"],
    vibe: "Deep-rooted Southern capital with civil rights legacy and soulful cultural energy",
  },
  {
    name: "Gulfport",
    slug: "gulfport",
    state: "Mississippi",
    stateSlug: "mississippi",
    stateAbbr: "MS",
    population: 72926,
    description: "Gulfport is the second-largest city in Mississippi, a Gulf Coast community that rebuilt with resilience after Hurricane Katrina and now thrives on tourism, seafood, and beach culture.",
    landmarks: ["Mississippi Aquarium", "Jones Park", "Gulfport Harbor"],
    vibe: "Resilient Gulf Coast city with beach culture, seafood, and rebuilding pride",
  },
  {
    name: "Southaven",
    slug: "southaven",
    state: "Mississippi",
    stateSlug: "mississippi",
    stateAbbr: "MS",
    population: 55026,
    description: "Southaven is the largest suburb in the Memphis metro area on the Mississippi side, a rapidly growing DeSoto County city with family amenities and Southern hospitality.",
    landmarks: ["Snowden Grove Park", "BankPlus Amphitheater", "Southaven Town Center"],
    vibe: "Fast-growing Memphis suburb with Southern charm and modern family amenities",
  },
  {
    name: "Hattiesburg",
    slug: "hattiesburg",
    state: "Mississippi",
    stateSlug: "mississippi",
    stateAbbr: "MS",
    population: 48985,
    description: "Hattiesburg is a vibrant college city in the Piney Woods region, anchored by the University of Southern Mississippi and a downtown district that punches above its weight in arts and dining.",
    landmarks: ["University of Southern Mississippi", "African American Military History Museum", "Chain Park"],
    vibe: "College-town energy in the Piney Woods with an outsized arts and dining scene",
  },
  {
    name: "Biloxi",
    slug: "biloxi",
    state: "Mississippi",
    stateSlug: "mississippi",
    stateAbbr: "MS",
    population: 46212,
    description: "Biloxi is a Gulf Coast casino and resort city with a rich French colonial history, miles of white sand beaches, and a thriving seafood industry.",
    landmarks: ["Biloxi Lighthouse", "Beau Rivage Resort & Casino", "Biloxi Town Green"],
    vibe: "Casino resort energy meets Gulf Coast fishing heritage and beachfront living",
  },
  {
    name: "Meridian",
    slug: "meridian",
    state: "Mississippi",
    stateSlug: "mississippi",
    stateAbbr: "MS",
    population: 33258,
    description: "Meridian is an east-central Mississippi city with deep railroad heritage and the distinction of being the hometown of Jimmie Rodgers, the Father of Country Music.",
    landmarks: ["Jimmie Rodgers Museum", "Meridian Museum of Art", "Highland Park Dentzel Carousel"],
    vibe: "Railroad heritage city with country music roots and small-town Southern warmth",
  },
  {
    name: "Tupelo",
    slug: "tupelo",
    state: "Mississippi",
    stateSlug: "mississippi",
    stateAbbr: "MS",
    population: 38300,
    description: "Tupelo is the birthplace of Elvis Presley and northeast Mississippi's commercial hub, offering a charming downtown, strong healthcare systems, and growing cultural attractions.",
    landmarks: ["Elvis Presley Birthplace", "Tupelo Automobile Museum", "Natchez Trace Parkway"],
    vibe: "Elvis birthplace pride with small-city commerce and genuine Southern hospitality",
  },
  {
    name: "Olive Branch",
    slug: "olive-branch",
    state: "Mississippi",
    stateSlug: "mississippi",
    stateAbbr: "MS",
    population: 44054,
    description: "Olive Branch is one of the fastest-growing cities in Mississippi, a DeSoto County community in the Memphis metro that attracts families with affordable housing and new development.",
    landmarks: ["Olive Branch City Park", "Old Towne Olive Branch", "Cherokee Valley Golf Club"],
    vibe: "Boom-town suburban growth with affordable living and Memphis metro access",
  },
  {
    name: "Horn Lake",
    slug: "horn-lake",
    state: "Mississippi",
    stateSlug: "mississippi",
    stateAbbr: "MS",
    population: 27521,
    description: "Horn Lake is a DeSoto County community in the Memphis suburbs, a small city with affordable living, community parks, and a growing commercial corridor along Goodman Road.",
    landmarks: ["Horn Lake Community Park", "Latimer Lakes Park", "Goodman Road corridor"],
    vibe: "Affordable Memphis-metro suburb with small-town community and steady growth",
  },

  // ─── Missouri ───
  {
    name: "Kansas City",
    slug: "kansas-city-mo",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 508090,
    description: "Kansas City is a sprawling metro known for its legendary barbecue, jazz heritage, spectacular fountains, and the championship-winning Chiefs, straddling the Missouri-Kansas border.",
    landmarks: ["Nelson-Atkins Museum of Art", "Country Club Plaza", "Union Station"],
    vibe: "Barbecue and jazz capital with Midwestern hospitality and championship sports energy",
  },
  {
    name: "St. Louis",
    slug: "st-louis",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 293310,
    description: "St. Louis is the Gateway to the West, anchored by its iconic Arch on the Mississippi riverfront, with world-class free museums, a passionate sports culture, and diverse neighborhoods.",
    landmarks: ["Gateway Arch", "Forest Park", "Busch Stadium"],
    vibe: "Gateway City pride with free world-class attractions and fierce neighborhood loyalty",
  },
  {
    name: "Springfield",
    slug: "springfield-mo",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 169176,
    description: "Springfield is the Ozarks' largest city, birthplace of Route 66 and home to Bass Pro Shops' flagship store, blending outdoor recreation with a growing university-town culture.",
    landmarks: ["Bass Pro Shops Outdoor World", "Fantastic Caverns", "Dickerson Park Zoo"],
    vibe: "Ozarks gateway with Route 66 nostalgia and outdoor adventure around every corner",
  },
  {
    name: "Columbia",
    slug: "columbia-mo",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 126254,
    description: "Columbia is a vibrant college city in the heart of Missouri, home to the University of Missouri and a thriving downtown with independent shops, restaurants, and a progressive spirit.",
    landmarks: ["University of Missouri", "Stephens Lake Park", "The Blue Note"],
    vibe: "Progressive college town with Mizzou spirit and a walkable creative downtown",
  },
  {
    name: "Independence",
    slug: "independence",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 123011,
    description: "Independence is the hometown of Harry Truman and the historic starting point of the Oregon, California, and Santa Fe trails, now a suburban community east of Kansas City.",
    landmarks: ["Harry S. Truman Library & Museum", "National Frontier Trails Museum", "Independence Square"],
    vibe: "Truman-era Americana with trail history and Kansas City suburban convenience",
  },
  {
    name: "Lee's Summit",
    slug: "lees-summit",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 101108,
    description: "Lee's Summit is a thriving Kansas City suburb with a charming historic downtown, top-rated schools, and a community that balances growth with small-town character.",
    landmarks: ["Downtown Lee's Summit", "Longview Lake", "Unity Village"],
    vibe: "Charming KC suburb with downtown character, great schools, and steady growth",
  },
  {
    name: "O'Fallon",
    slug: "ofallon-mo",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 91316,
    description: "O'Fallon is St. Charles County's largest city and one of Missouri's fastest-growing communities, offering new construction, family amenities, and easy access to the St. Louis metro.",
    landmarks: ["Fort Zumwalt Park", "Ozzie Smith Sports Complex", "Dardenne Prairie corridor"],
    vibe: "Fast-growing family suburb with new development and strong community programming",
  },
  {
    name: "St. Joseph",
    slug: "st-joseph",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 72473,
    description: "St. Joseph is a Missouri River city steeped in frontier history as the starting point of the Pony Express and the place where Jesse James met his end.",
    landmarks: ["Pony Express Museum", "Patee House Museum", "Krug Park"],
    vibe: "Frontier history city along the Missouri River with preserved Wild West heritage",
  },
  {
    name: "St. Charles",
    slug: "st-charles",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 72540,
    description: "St. Charles is Missouri's first state capital, a historic river city with a charming brick-lined Main Street, Lewis and Clark heritage, and a growing suburban population.",
    landmarks: ["Historic Main Street", "Lewis & Clark Boat House", "Katy Trail State Park"],
    vibe: "Historic river-town charm with brick Main Street shops and Lewis & Clark heritage",
  },
  {
    name: "Blue Springs",
    slug: "blue-springs",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 57543,
    description: "Blue Springs is an eastern Kansas City suburb with a strong school district, extensive parks system, and a community identity rooted in family-friendly living.",
    landmarks: ["Burr Oak Woods Conservation Area", "Fleming Park", "Blue Springs Lake"],
    vibe: "Family-focused KC suburb with excellent parks and tight-knit community feel",
  },
  {
    name: "St. Peters",
    slug: "st-peters",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 57517,
    description: "St. Peters is a St. Charles County suburb known for its award-winning Rec-Plex athletic complex and a strong commitment to recreation and family programming.",
    landmarks: ["Rec-Plex", "Lakeside Park", "Mid Rivers Mall"],
    vibe: "Recreation-focused suburb with award-winning athletic facilities and family amenities",
  },
  {
    name: "Florissant",
    slug: "florissant",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 51573,
    description: "Florissant is one of St. Louis County's oldest communities, a north county suburb with historic churches, a preserved Old Town district, and affordable family housing.",
    landmarks: ["Old St. Ferdinand Shrine", "Florissant Civic Center", "Koch Park"],
    vibe: "Historic north-county suburb with old-world charm and affordable community living",
  },
  {
    name: "Joplin",
    slug: "joplin",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 51762,
    description: "Joplin is a resilient southwestern Missouri city that rebuilt after a devastating 2011 tornado, sitting at the crossroads of Route 66 and the Four States region.",
    landmarks: ["Cunningham Park", "Bonnie and Clyde Hideout", "Route 66 Mural Park"],
    vibe: "Tornado-resilient community with Route 66 heritage and Four States crossroads energy",
  },
  {
    name: "Chesterfield",
    slug: "chesterfield",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 49999,
    description: "Chesterfield is an affluent west St. Louis County suburb known for its premium shopping at Chesterfield Mall and the massive Faust Park historical grounds.",
    landmarks: ["Faust Park", "Chesterfield Valley", "Butterfly House"],
    vibe: "Affluent suburban enclave with premium retail and scenic Missouri River valley views",
  },
  {
    name: "Jefferson City",
    slug: "jefferson-city",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 43228,
    description: "Jefferson City is Missouri's capital, perched on bluffs above the Missouri River with a striking state capitol building, penitentiary history, and a growing downtown scene.",
    landmarks: ["Missouri State Capitol", "Missouri State Penitentiary", "Capitol City Trail"],
    vibe: "Capital city on the bluffs with government culture and Missouri River beauty",
  },
  {
    name: "Cape Girardeau",
    slug: "cape-girardeau",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 40100,
    description: "Cape Girardeau is a Mississippi River city in southeast Missouri, home to Southeast Missouri State University and a revitalized downtown with a historic flood wall mural.",
    landmarks: ["Cape Girardeau Flood Wall Murals", "Trail of Tears State Park", "Southeast Missouri State University"],
    vibe: "River-town university city with flood wall art and Southeast Missouri regional pride",
  },
  {
    name: "Wentzville",
    slug: "wentzville",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 44372,
    description: "Wentzville is one of Missouri's fastest-growing cities at the western edge of the St. Louis metro, home to a GM assembly plant and rapidly expanding residential communities.",
    landmarks: ["Peruque Valley Park", "Progress Park", "Wentzville Community Club"],
    vibe: "Boom-town energy at the metro's western edge with auto manufacturing backbone",
  },
  {
    name: "Wildwood",
    slug: "wildwood",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 37373,
    description: "Wildwood is a sprawling, wooded west St. Louis County city that prioritizes green space preservation, equestrian trails, and a rural character within the metropolitan area.",
    landmarks: ["Al Foster Trail", "Wildwood Town Center", "LaSalle Springs"],
    vibe: "Wooded exurban retreat with preserved green spaces and equestrian culture",
  },
  {
    name: "Ballwin",
    slug: "ballwin",
    state: "Missouri",
    stateSlug: "missouri",
    stateAbbr: "MO",
    population: 31195,
    description: "Ballwin is a popular west St. Louis County suburb with the North Pointe aquatic center, strong community programming, and consistently high livability rankings.",
    landmarks: ["The Pointe at Ballwin Commons", "Vlasis Park", "New Ballwin Park"],
    vibe: "Livable and well-programmed suburb with strong community recreation facilities",
  },

  // ─── Montana ───
  {
    name: "Billings",
    slug: "billings",
    state: "Montana",
    stateSlug: "montana",
    stateAbbr: "MT",
    population: 119157,
    description: "Billings is Montana's largest city, a Yellowstone River community surrounded by rimrocks and serving as the economic and medical hub for the northern Great Plains and Rocky Mountain region.",
    landmarks: ["Pictograph Cave State Park", "Yellowstone Art Museum", "Rimrocks"],
    vibe: "Montana's big city with rimrock scenery and gateway-to-Yellowstone energy",
  },
  {
    name: "Missoula",
    slug: "missoula",
    state: "Montana",
    stateSlug: "montana",
    stateAbbr: "MT",
    population: 75516,
    description: "Missoula is a mountain-valley college town home to the University of Montana, beloved for its literary culture, craft beer scene, and unmatched access to wilderness.",
    landmarks: ["University of Montana", "Caras Park", "Mount Sentinel"],
    vibe: "Literary mountain town with university culture and world-class trout rivers nearby",
  },
  {
    name: "Great Falls",
    slug: "great-falls",
    state: "Montana",
    stateSlug: "montana",
    stateAbbr: "MT",
    population: 60442,
    description: "Great Falls is the Electric City on the Missouri River, named for the series of waterfalls Lewis and Clark documented, with a thriving Western art scene and Malmstrom Air Force Base.",
    landmarks: ["Giant Springs State Park", "C.M. Russell Museum", "Lewis and Clark Interpretive Center"],
    vibe: "Western art city on the Missouri River with military presence and Big Sky beauty",
  },

  // ─── Nebraska ───
  {
    name: "Omaha",
    slug: "omaha",
    state: "Nebraska",
    stateSlug: "nebraska",
    stateAbbr: "NE",
    population: 486051,
    description: "Omaha is a Missouri River metropolis that punches far above its weight with Warren Buffett's Berkshire Hathaway, the world-class Henry Doorly Zoo, and a thriving Old Market district.",
    landmarks: ["Henry Doorly Zoo", "Old Market District", "Bob Kerrey Pedestrian Bridge"],
    vibe: "Understated Midwest powerhouse with world-class zoo and billionaire-next-door culture",
  },
  {
    name: "Lincoln",
    slug: "lincoln",
    state: "Nebraska",
    stateSlug: "nebraska",
    stateAbbr: "NE",
    population: 291082,
    description: "Lincoln is Nebraska's capital and home of the University of Nebraska, where Big Red football is a religion and the Haymarket District anchors a growing food and arts scene.",
    landmarks: ["Memorial Stadium", "Nebraska State Capitol", "Haymarket District"],
    vibe: "Big Red football passion with state capital gravitas and college-town creativity",
  },
  {
    name: "Bellevue",
    slug: "bellevue-ne",
    state: "Nebraska",
    stateSlug: "nebraska",
    stateAbbr: "NE",
    population: 64176,
    description: "Bellevue is Nebraska's oldest city and home to Offutt Air Force Base and US Strategic Command, blending military community with suburban Omaha living along the Missouri River bluffs.",
    landmarks: ["Fontenelle Forest", "Offutt Air Force Base", "Haworth Park"],
    vibe: "Military community pride with Missouri River bluff beauty and Omaha proximity",
  },
  {
    name: "Grand Island",
    slug: "grand-island",
    state: "Nebraska",
    stateSlug: "nebraska",
    stateAbbr: "NE",
    population: 53131,
    description: "Grand Island is central Nebraska's hub along the Platte River, famous for the spectacular annual sandhill crane migration and the Nebraska State Fair.",
    landmarks: ["Stuhr Museum of the Prairie Pioneer", "Fonner Park", "Stolley Park"],
    vibe: "Prairie crossroads city with crane migration spectacle and state fair traditions",
  },

  // ─── Nevada ───
  {
    name: "Las Vegas",
    slug: "las-vegas",
    state: "Nevada",
    stateSlug: "nevada",
    stateAbbr: "NV",
    population: 641903,
    description: "Las Vegas is the Entertainment Capital of the World, where the neon-lit Strip draws millions of visitors while a sprawling residential city of desert neighborhoods extends in every direction.",
    landmarks: ["Las Vegas Strip", "Fremont Street Experience", "Red Rock Canyon"],
    vibe: "Nonstop entertainment energy with desert suburbia stretching to red rock mountains",
  },
  {
    name: "Henderson",
    slug: "henderson",
    state: "Nevada",
    stateSlug: "nevada",
    stateAbbr: "NV",
    population: 320189,
    description: "Henderson is Nevada's second-largest city, a master-planned community southeast of the Strip that consistently ranks among America's safest large cities with stunning desert mountain views.",
    landmarks: ["Lake Las Vegas", "Water Street District", "Clark County Museum"],
    vibe: "Safe and master-planned desert living with mountain views and Strip proximity",
  },
  {
    name: "Reno",
    slug: "reno",
    state: "Nevada",
    stateSlug: "nevada",
    stateAbbr: "NV",
    population: 264165,
    description: "Reno is the Biggest Little City in the World, a high-desert city at the base of the Sierra Nevada that has reinvented itself from casino town to tech hub and outdoor recreation gateway.",
    landmarks: ["Reno Arch", "National Automobile Museum", "Riverwalk District"],
    vibe: "Reinvented casino city turned tech hub with Sierra Nevada adventure at the doorstep",
  },
  {
    name: "North Las Vegas",
    slug: "north-las-vegas",
    state: "Nevada",
    stateSlug: "nevada",
    stateAbbr: "NV",
    population: 262527,
    description: "North Las Vegas is a rapidly growing city north of the Strip, home to Nellis Air Force Base and the Las Vegas Motor Speedway, with diverse neighborhoods and affordable housing.",
    landmarks: ["Las Vegas Motor Speedway", "Nellis Air Force Base", "Craig Ranch Regional Park"],
    vibe: "Fast-growing and diverse with motorsports energy and military community roots",
  },
  {
    name: "Sparks",
    slug: "sparks",
    state: "Nevada",
    stateSlug: "nevada",
    stateAbbr: "NV",
    population: 108445,
    description: "Sparks is Reno's eastern twin, a city built on railroad heritage that now thrives on logistics, Tesla's Gigafactory proximity, and a bustling Victorian Square entertainment district.",
    landmarks: ["Victorian Square", "Sparks Marina", "Nugget Casino Resort"],
    vibe: "Railroad heritage meets Tesla-era growth with community festivals and marina parks",
  },
  {
    name: "Carson City",
    slug: "carson-city",
    state: "Nevada",
    stateSlug: "nevada",
    stateAbbr: "NV",
    population: 58639,
    description: "Carson City is Nevada's capital, an independent city nestled against the Sierra Nevada foothills with Old West heritage, the historic Carson City Mint, and easy access to Lake Tahoe.",
    landmarks: ["Nevada State Capitol", "Nevada State Museum", "Carson Hot Springs"],
    vibe: "Old West capital city in the Sierra foothills with Lake Tahoe just over the mountain",
  },

  // ─── New Hampshire ───
  {
    name: "Manchester",
    slug: "manchester-nh",
    state: "New Hampshire",
    stateSlug: "new-hampshire",
    stateAbbr: "NH",
    population: 115644,
    description: "Manchester is New Hampshire's largest city, a former mill town along the Merrimack River that has reinvented itself into a tech and startup hub while preserving its red-brick industrial heritage.",
    landmarks: ["Currier Museum of Art", "SEE Science Center", "Arms Park"],
    vibe: "Mill-city-turned-tech-hub with brick-lined riverfronts and startup energy",
  },
  {
    name: "Nashua",
    slug: "nashua",
    state: "New Hampshire",
    stateSlug: "new-hampshire",
    stateAbbr: "NH",
    population: 91322,
    description: "Nashua has been repeatedly named one of the best places to live in America, a southern New Hampshire city with no sales or income tax, a vibrant downtown, and easy Boston access.",
    landmarks: ["Mine Falls Park", "Nashua River Walk", "Pheasant Lane Mall"],
    vibe: "Tax-free living with best-place-to-live accolades and New England charm",
  },
  {
    name: "Concord",
    slug: "concord-nh",
    state: "New Hampshire",
    stateSlug: "new-hampshire",
    stateAbbr: "NH",
    population: 43976,
    description: "Concord is New Hampshire's capital, a small city on the Merrimack River known for its granite State House, McAuliffe-Shepard Discovery Center, and a walkable Main Street district.",
    landmarks: ["New Hampshire State House", "McAuliffe-Shepard Discovery Center", "White Park"],
    vibe: "Compact granite capital with New England walkability and civic pride",
  },

  // ─── New Jersey ───
  {
    name: "Newark",
    slug: "newark",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 311549,
    description: "Newark is New Jersey's largest city and a major transportation hub, experiencing a cultural and economic renaissance with world-class performing arts, Portuguese Ironbound cuisine, and new development.",
    landmarks: ["Newark Museum of Art", "Prudential Center", "Branch Brook Park"],
    vibe: "Renaissance energy in NJ's largest city with Ironbound dining and arts revival",
  },
  {
    name: "Jersey City",
    slug: "jersey-city",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 292449,
    description: "Jersey City is Manhattan's vibrant neighbor across the Hudson, a booming waterfront city with stunning skyline views, diverse neighborhoods, and a thriving restaurant and bar scene.",
    landmarks: ["Liberty State Park", "Liberty Science Center", "Exchange Place waterfront"],
    vibe: "Manhattan-adjacent boom town with waterfront skyline views and global dining",
  },
  {
    name: "Paterson",
    slug: "paterson",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 159732,
    description: "Paterson is the Silk City, built around the Great Falls of the Passaic River, America's first planned industrial city now home to one of the most diverse populations in the nation.",
    landmarks: ["Great Falls National Historical Park", "Lambert Castle", "Paterson Museum"],
    vibe: "Industrial heritage city with Great Falls grandeur and extraordinary cultural diversity",
  },
  {
    name: "Elizabeth",
    slug: "elizabeth",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 137298,
    description: "Elizabeth is one of New Jersey's oldest cities, a Union County hub with the massive Jersey Gardens outlet mall, a thriving Latino community, and proximity to Newark Airport.",
    landmarks: ["The Mills at Jersey Gardens", "Warinanco Park", "Elizabeth Waterfront"],
    vibe: "Historic port city with vibrant Latino culture and major retail destination energy",
  },
  {
    name: "Lakewood",
    slug: "lakewood-nj",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 135158,
    description: "Lakewood is Ocean County's largest municipality, a rapidly growing community with a large Orthodox Jewish population, pine barrens surroundings, and Georgian Court University.",
    landmarks: ["Georgian Court University", "Lake Carasaljo", "Pine Park"],
    vibe: "Rapidly growing community with strong cultural identity and Pine Barrens setting",
  },
  {
    name: "Edison",
    slug: "edison",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 107588,
    description: "Edison is named after Thomas Edison and is one of the most diverse townships in America, with a large South Asian community, excellent schools, and a central New Jersey location.",
    landmarks: ["Thomas Edison Center at Menlo Park", "Roosevelt Park", "Middlesex Greenway"],
    vibe: "Inventor's namesake city with extraordinary South Asian culture and suburban diversity",
  },
  {
    name: "Woodbridge",
    slug: "woodbridge",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 103353,
    description: "Woodbridge is a sprawling Middlesex County township with waterfront access on the Raritan Bay, diverse communities, and a central location between New York and Philadelphia.",
    landmarks: ["Woodbridge Community Center", "Parker Press Park", "Sewaren waterfront"],
    vibe: "Centrally located township with waterfront access and diverse suburban neighborhoods",
  },
  {
    name: "Toms River",
    slug: "toms-river",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 95438,
    description: "Toms River is the Ocean County seat, a Jersey Shore community along Barnegat Bay known for its Little League World Series victories, boating culture, and barrier island beaches.",
    landmarks: ["Cattus Island County Park", "Toms River Seaport Society", "Barnegat Bay"],
    vibe: "Jersey Shore bay community with Little League pride and year-round coastal living",
  },
  {
    name: "Hamilton",
    slug: "hamilton-nj",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 92297,
    description: "Hamilton is a large Mercer County township adjacent to Trenton, offering suburban living, the Grounds for Sculpture art park, and a mix of residential and commercial development.",
    landmarks: ["Grounds for Sculpture", "Veterans Park", "Sayen House and Gardens"],
    vibe: "Art-park suburb with spacious neighborhoods and New Jersey capital-area convenience",
  },
  {
    name: "Trenton",
    slug: "trenton",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 90871,
    description: "Trenton is New Jersey's capital, a Delaware River city where Washington crossed to change the course of the Revolution, now working to revitalize its historic downtown and waterfront.",
    landmarks: ["New Jersey State House", "Old Barracks Museum", "Trenton Battle Monument"],
    vibe: "Revolutionary War capital city on the Delaware with revitalization momentum",
  },
  {
    name: "Clifton",
    slug: "clifton",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 90296,
    description: "Clifton is a Passaic County city with a remarkably diverse population, stretching from the Passaic River to the Garret Mountain Reservation with strong neighborhood identities.",
    landmarks: ["Garret Mountain Reservation", "Clifton Arts Center", "Weasel Brook Park"],
    vibe: "Diverse multi-neighborhood city with mountain reservation views and NYC proximity",
  },
  {
    name: "Camden",
    slug: "camden",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 73562,
    description: "Camden is a Delaware River city across from Philadelphia, undergoing significant revitalization with the waterfront adventure aquarium, Rutgers campus expansion, and corporate relocations.",
    landmarks: ["Adventure Aquarium", "Battleship New Jersey", "Camden Waterfront"],
    vibe: "Waterfront revival city with Philadelphia skyline views and growing investment",
  },
  {
    name: "Brick",
    slug: "brick",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 76882,
    description: "Brick is a large Ocean County township along the Barnegat Bay, a Jersey Shore community with Point Pleasant Beach nearby, family neighborhoods, and year-round coastal living.",
    landmarks: ["Brick Beach", "Windward Beach Park", "Trader Cove Marina"],
    vibe: "Jersey Shore residential township with bay access and family beach culture",
  },
  {
    name: "Cherry Hill",
    slug: "cherry-hill",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 74553,
    description: "Cherry Hill is a premier Camden County suburb with excellent schools, the Cherry Hill Mall, and a large, active Jewish community that shapes its cultural and culinary landscape.",
    landmarks: ["Cherry Hill Mall", "Croft Farm", "Barclay Farmstead"],
    vibe: "Upscale South Jersey suburb with top schools and vibrant cultural community",
  },
  {
    name: "Passaic",
    slug: "passaic",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 72722,
    description: "Passaic is a densely populated city along the Passaic River with a vibrant Latino community, affordable urban living, and easy NJ Transit access to New York City.",
    landmarks: ["Third Ward Park", "Passaic Falls", "Pulaski Park"],
    vibe: "Dense urban energy with Latino vibrancy and affordable NYC-accessible living",
  },
  {
    name: "Middletown",
    slug: "middletown-nj",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 66522,
    description: "Middletown is a large Monmouth County township along the Sandy Hook Bay, offering waterfront living, strong schools, and fast ferry service to Manhattan from its bayshore communities.",
    landmarks: ["Sandy Hook Bay waterfront", "Deep Cut Gardens", "Poricy Park"],
    vibe: "Bayshore suburb with Manhattan ferry access and coastal Monmouth County charm",
  },
  {
    name: "Union City",
    slug: "union-city-nj",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 73970,
    description: "Union City is the most densely populated city in New Jersey, a Hudson County community on the Palisades with stunning Manhattan views, Cuban culture, and affordable urban living.",
    landmarks: ["Palisades cliffs viewpoints", "Union City Civic Center", "Bergenline Avenue"],
    vibe: "Ultra-dense Hudson County living with Palisades views and rich Cuban heritage",
  },
  {
    name: "Old Bridge",
    slug: "old-bridge",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 68356,
    description: "Old Bridge is a sprawling Middlesex County township with diverse neighborhoods, extensive parkland, and a central location that makes it accessible to both New York and the Jersey Shore.",
    landmarks: ["Old Bridge Waterfront Park", "Cheesequake State Park", "Laurence Harbor Beach"],
    vibe: "Central Jersey crossroads with state park access and diverse suburban communities",
  },
  {
    name: "Gloucester",
    slug: "gloucester-nj",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 64634,
    description: "Gloucester Township is a Camden County community offering affordable South Jersey living, the Gloucester Premium Outlets, and proximity to both Philadelphia and the Pine Barrens.",
    landmarks: ["Gloucester Premium Outlets", "Scotland Run Park", "Timber Creek Park"],
    vibe: "Affordable South Jersey suburb with outlet shopping and Pine Barrens proximity",
  },
  {
    name: "North Bergen",
    slug: "north-bergen",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 65827,
    description: "North Bergen is a Hudson County township on the Palisades offering dramatic Manhattan skyline views, diverse dining along Bergenline Avenue, and NJ Transit access to Midtown.",
    landmarks: ["James J. Braddock North Hudson County Park", "Palisades panoramic views", "Bergenline Avenue"],
    vibe: "Palisades-top living with dramatic skyline panoramas and diverse boulevard dining",
  },
  {
    name: "Vineland",
    slug: "vineland",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 61391,
    description: "Vineland is a sprawling Cumberland County city in southern New Jersey, founded as a planned community for agriculture and still defined by its farming heritage and Italian American culture.",
    landmarks: ["Landis Avenue", "Palace of Depression site", "Vineland Historical and Antiquarian Society"],
    vibe: "Agricultural South Jersey city with Italian American roots and small-town character",
  },
  {
    name: "Bayonne",
    slug: "bayonne",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 71852,
    description: "Bayonne is a Hudson County peninsula city surrounded by waterways, known for its military ocean terminal heritage, growing waterfront development, and close-knit neighborhood culture.",
    landmarks: ["Bayonne Bridge", "Stephen R. Gregg Park", "Cape Liberty Cruise Port"],
    vibe: "Peninsula city with waterfront development, cruise port, and neighborhood loyalty",
  },
  {
    name: "East Orange",
    slug: "east-orange",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 64270,
    description: "East Orange is an Essex County city with a strong African American community, historic architecture, and proximity to both Newark and the South Mountain Reservation.",
    landmarks: ["Oval Park", "East Orange Public Library", "South Mountain Reservation nearby"],
    vibe: "Proud African American community with historic architecture and urban resilience",
  },
  {
    name: "Franklin",
    slug: "franklin-nj",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 67698,
    description: "Franklin Township is a Somerset County community offering diverse suburban living, Rutgers Preparatory School, and proximity to both New Brunswick and the scenic Millstone River valley.",
    landmarks: ["Colonial Park", "Delaware and Raritan Canal", "Bunker Hill Environmental Center"],
    vibe: "Diverse Somerset County suburb with canal trails and quality suburban schools",
  },
  {
    name: "New Brunswick",
    slug: "new-brunswick",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 56100,
    description: "New Brunswick is the Hub City, home to Rutgers University and Johnson & Johnson headquarters, with a vibrant downtown theater district and one of New Jersey's best restaurant scenes.",
    landmarks: ["Rutgers University", "State Theatre New Jersey", "George Street Playhouse"],
    vibe: "University city with pharma headquarters, theater culture, and diverse dining",
  },
  {
    name: "Piscataway",
    slug: "piscataway",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 60700,
    description: "Piscataway is a Middlesex County township home to Rutgers' Busch Campus and a diverse suburban community with strong South Asian and East Asian populations.",
    landmarks: ["Rutgers Busch Campus", "Johnson Park", "East Jersey Old Town Village"],
    vibe: "University-adjacent diverse suburb with multicultural neighborhoods and green space",
  },
  {
    name: "Perth Amboy",
    slug: "perth-amboy",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 55049,
    description: "Perth Amboy is a historic waterfront city at the confluence of the Raritan River and Arthur Kill, with a proud Latino community and a revitalizing downtown centered on its harbor.",
    landmarks: ["Raritan Bay Waterfront Park", "Perth Amboy Ferry Slip", "Kearny Cottage"],
    vibe: "Historic waterfront city with Latino vibrancy and harbor revitalization energy",
  },
  {
    name: "West New York",
    slug: "west-new-york",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 54015,
    description: "West New York is a densely packed Hudson County town on the Palisades, offering some of the most spectacular Manhattan skyline views in New Jersey and a thriving Latino dining scene.",
    landmarks: ["Boulevard East promenade", "Old Glory Park", "Bergenline Avenue shops"],
    vibe: "Dense Palisades-top living with million-dollar skyline views and Latino culture",
  },
  {
    name: "Hoboken",
    slug: "hoboken",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 60419,
    description: "Hoboken is the Mile Square City, a walkable Hudson River waterfront community famous as Frank Sinatra's birthplace, the birthplace of baseball, and a premier young-professional destination.",
    landmarks: ["Hoboken Waterfront Walkway", "Stevens Institute of Technology", "Carlo's Bakery"],
    vibe: "Walkable mile-square city with waterfront bars, Sinatra legacy, and young pro energy",
  },
  {
    name: "Plainfield",
    slug: "plainfield",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 54586,
    description: "Plainfield is a Union County city with a rich architectural heritage, diverse neighborhoods, and a downtown district working toward revitalization with new transit-oriented development.",
    landmarks: ["Cedar Brook Park", "Drake House Museum", "Plainfield Historic District"],
    vibe: "Architecturally rich city with diverse community and transit-oriented revitalization",
  },
  {
    name: "Hackensack",
    slug: "hackensack",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 46030,
    description: "Hackensack is the Bergen County seat, a northern New Jersey hub dominated by the Hackensack University Medical Center and a downtown that has seen significant redevelopment and new housing.",
    landmarks: ["Hackensack University Medical Center", "USS Ling Submarine Museum", "Main Street corridor"],
    vibe: "Bergen County hub with medical center prominence and downtown redevelopment momentum",
  },
  {
    name: "Sayreville",
    slug: "sayreville",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 44243,
    description: "Sayreville is a Middlesex County borough along the Raritan River, known as the hometown of Jon Bon Jovi and a community balancing industrial heritage with waterfront redevelopment.",
    landmarks: ["Kennedy Park", "Raritan River waterfront", "Starland Ballroom"],
    vibe: "Bon Jovi's hometown with Raritan River waterfront and blue-collar community pride",
  },
  {
    name: "Kearny",
    slug: "kearny",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 44425,
    description: "Kearny is a Hudson County town with deep Scottish and Irish roots, known locally as Soccer Town USA for producing multiple US national team players from its tight-knit community.",
    landmarks: ["Kearny High School", "Gunnel Oval", "Passaic River waterfront"],
    vibe: "Soccer Town USA with Scottish-Irish heritage and close-knit working-class bonds",
  },
  {
    name: "Linden",
    slug: "linden",
    state: "New Jersey",
    stateSlug: "new-jersey",
    stateAbbr: "NJ",
    population: 44951,
    description: "Linden is a Union County city with a mix of residential neighborhoods and industrial areas, home to a diverse population and convenient NJ Transit rail service to New York Penn Station.",
    landmarks: ["Raymond Wood Bauer Promenade", "Wheeler Park", "Linden Aviation Plaza"],
    vibe: "Industrial-residential city with diverse community and direct NYC rail access",
  },
];
