// @ts-nocheck
import type { City } from "./siteData";

export const citiesBatch2: City[] = [
  /* ─── Hawaii ─── */
  {
    name: "Honolulu",
    slug: "honolulu",
    state: "Hawaii",
    stateSlug: "hawaii",
    stateAbbr: "HI",
    population: 350964,
    description: "Hawaii's capital and largest city, Honolulu stretches along the southern shore of Oahu with world-famous beaches, a vibrant Polynesian culture, and year-round tropical weather that draws millions of visitors annually.",
    landmarks: ["Waikiki Beach", "Diamond Head State Monument", "Pearl Harbor National Memorial"],
    vibe: "Tropical island capital blending surf culture, Polynesian heritage, and cosmopolitan city life",
  },
  {
    name: "East Honolulu",
    slug: "east-honolulu",
    state: "Hawaii",
    stateSlug: "hawaii",
    stateAbbr: "HI",
    population: 51062,
    description: "A residential community east of downtown Honolulu, East Honolulu features scenic ridgelines, quiet neighborhoods tucked into lush valleys, and easy access to Hanauma Bay and the island's windward coast.",
    landmarks: ["Hanauma Bay Nature Preserve", "Koko Head Crater Trail", "Sandy Beach Park"],
    vibe: "Laid-back suburban paradise with volcanic ridgelines and turquoise snorkeling coves",
  },
  {
    name: "Pearl City",
    slug: "pearl-city",
    state: "Hawaii",
    stateSlug: "hawaii",
    stateAbbr: "HI",
    population: 52064,
    description: "Situated along the northern shore of Pearl Harbor, Pearl City is a diverse residential community with deep historical roots, local shopping centers, and quick access to both Honolulu and the North Shore.",
    landmarks: ["Pearl Harbor National Memorial", "Pearlridge Center", "Waimano Ridge Trail"],
    vibe: "Family-oriented harbor town with strong military ties and multicultural local flavor",
  },

  /* ─── Idaho ─── */
  {
    name: "Boise",
    slug: "boise",
    state: "Idaho",
    stateSlug: "idaho",
    stateAbbr: "ID",
    population: 235684,
    description: "Idaho's capital and largest city, Boise sits at the foot of the Rocky Mountain foothills along the Boise River. A fast-growing tech hub surrounded by outdoor recreation, it blends urban energy with easy access to world-class skiing and hiking.",
    landmarks: ["Boise River Greenbelt", "Idaho State Capitol", "Table Rock"],
    vibe: "Mountain-meets-metro tech hub with craft breweries, river trails, and four-season outdoor living",
  },
  {
    name: "Meridian",
    slug: "meridian",
    state: "Idaho",
    stateSlug: "idaho",
    stateAbbr: "ID",
    population: 131507,
    description: "One of the fastest-growing cities in America, Meridian sits just west of Boise in the Treasure Valley. New master-planned communities, family-friendly parks, and a revitalized downtown make it a magnet for young professionals and families.",
    landmarks: ["The Village at Meridian", "Julius M. Kleiner Memorial Park", "Roaring Springs Waterpark"],
    vibe: "Booming Treasure Valley suburb with new development, community parks, and small-town friendliness",
  },
  {
    name: "Nampa",
    slug: "nampa",
    state: "Idaho",
    stateSlug: "idaho",
    stateAbbr: "ID",
    population: 108757,
    description: "The second-largest city in the Boise metro, Nampa combines a historic downtown core with rapid suburban growth. Agriculture, wineries, and the Snake River Birds of Prey area give it a distinct character within the Treasure Valley.",
    landmarks: ["Warhawk Air Museum", "Lakeview Park", "Snake River Birds of Prey National Conservation Area"],
    vibe: "Agricultural roots meeting rapid growth with wineries, air museums, and canyon country nearby",
  },
  {
    name: "Idaho Falls",
    slug: "idaho-falls",
    state: "Idaho",
    stateSlug: "idaho",
    stateAbbr: "ID",
    population: 66541,
    description: "Eastern Idaho's largest city straddles the Snake River with a picturesque downtown waterfall. As the gateway to Yellowstone and Grand Teton national parks, Idaho Falls serves as a basecamp for outdoor adventure and nuclear energy research.",
    landmarks: ["Idaho Falls River Walk", "Museum of Idaho", "Idaho Falls Temple"],
    vibe: "Yellowstone gateway city with a stunning river walk, nuclear-age history, and mountain access",
  },
  {
    name: "Pocatello",
    slug: "pocatello",
    state: "Idaho",
    stateSlug: "idaho",
    stateAbbr: "ID",
    population: 57773,
    description: "Home to Idaho State University, Pocatello sits in a high-desert valley surrounded by mountains. The city blends college-town energy with railroad heritage and serves as a hub for outdoor recreation in southeastern Idaho.",
    landmarks: ["Idaho State University", "Museum of Clean", "Pocatello Zoo"],
    vibe: "College town in a mountain valley with railroad heritage and high-desert adventure",
  },
  {
    name: "Caldwell",
    slug: "caldwell",
    state: "Idaho",
    stateSlug: "idaho",
    stateAbbr: "ID",
    population: 62604,
    description: "A rapidly growing city in Canyon County, Caldwell anchors the western end of the Treasure Valley. Its revitalized Indian Creek Plaza, thriving wine scene along the Sunnyslope Wine Trail, and agricultural heritage define its character.",
    landmarks: ["Indian Creek Plaza", "Sunnyslope Wine Trail", "College of Idaho"],
    vibe: "Wine country meets farming community with a revitalized plaza and Treasure Valley growth",
  },
  {
    name: "Twin Falls",
    slug: "twin-falls",
    state: "Idaho",
    stateSlug: "idaho",
    stateAbbr: "ID",
    population: 54710,
    description: "Perched on the rim of the Snake River Canyon, Twin Falls offers dramatic landscapes including the Perrine Bridge and Shoshone Falls. The city is the commercial hub of south-central Idaho's Magic Valley agricultural region.",
    landmarks: ["Shoshone Falls", "Perrine Bridge", "Snake River Canyon"],
    vibe: "Canyon-rim city with dramatic waterfalls, BASE jumping culture, and Magic Valley agriculture",
  },

  /* ─── Illinois ─── */
  {
    name: "Chicago",
    slug: "chicago",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 2665039,
    description: "The third-largest city in America, Chicago dominates the southwestern shore of Lake Michigan with iconic architecture, deep-dish pizza, world-class museums, and a mosaic of 77 distinct neighborhoods each with its own character.",
    landmarks: ["Millennium Park & Cloud Gate", "Willis Tower Skydeck", "Art Institute of Chicago"],
    vibe: "Bold, blue-collar metropolis with towering architecture, legendary food, and lakefront energy",
  },
  {
    name: "Aurora",
    slug: "aurora",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 180542,
    description: "Illinois' second-largest city straddles the Fox River west of Chicago. Aurora blends historic architecture along its riverfront with diverse neighborhoods, a casino, and growing arts and dining scenes.",
    landmarks: ["Paramount Theatre", "Phillips Park Zoo", "RiverEdge Park"],
    vibe: "Diverse Fox River city with historic theaters, growing arts scene, and suburban accessibility",
  },
  {
    name: "Naperville",
    slug: "naperville",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 149540,
    description: "Consistently ranked among the best places to live in America, Naperville features a charming downtown riverwalk, top-rated schools, and an engaged community with a vibrant restaurant and shopping scene along the DuPage River.",
    landmarks: ["Naperville Riverwalk", "Centennial Beach", "Naper Settlement"],
    vibe: "Upscale western suburb with a picture-perfect riverwalk, top schools, and boutique shopping",
  },
  {
    name: "Joliet",
    slug: "joliet",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 150362,
    description: "Located along the Des Plaines River and the historic Route 66 corridor, Joliet is a blue-collar city with deep industrial roots, a NASCAR speedway, and a revitalizing downtown anchored by the Rialto Square Theatre.",
    landmarks: ["Rialto Square Theatre", "Chicagoland Speedway", "Route 66 Trailhead"],
    vibe: "Route 66 heritage city with racing culture, limestone architecture, and working-class pride",
  },
  {
    name: "Rockford",
    slug: "rockford",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 148655,
    description: "The largest city in northern Illinois outside Chicago, Rockford straddles the Rock River with beautiful Japanese and botanical gardens, a strong manufacturing legacy, and an increasingly diverse cultural scene.",
    landmarks: ["Anderson Japanese Gardens", "Nicholas Conservatory & Gardens", "Rock Cut State Park"],
    vibe: "Rock River manufacturing city reinventing itself with world-class gardens and cultural renewal",
  },
  {
    name: "Springfield",
    slug: "springfield",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 114394,
    description: "Illinois' state capital and the home of Abraham Lincoln, Springfield is steeped in presidential history and Route 66 lore. Government, healthcare, and tourism drive an economy rooted in the heart of the Prairie State.",
    landmarks: ["Abraham Lincoln Presidential Library & Museum", "Illinois State Capitol", "Lincoln Home National Historic Site"],
    vibe: "Prairie capital city where Lincoln's legacy, Route 66 nostalgia, and state government converge",
  },
  {
    name: "Elgin",
    slug: "elgin",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 114797,
    description: "Straddling the Fox River northwest of Chicago, Elgin is a diverse city known for its historic watch-making heritage, a thriving arts scene at the Hemmens Cultural Center, and the Grand Victoria Casino riverboat.",
    landmarks: ["Elgin National Watch Company Observatory", "Grand Victoria Casino", "Lords Park & Zoo"],
    vibe: "Historic Fox River city with watchmaking heritage, diverse neighborhoods, and riverside entertainment",
  },
  {
    name: "Peoria",
    slug: "peoria",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 113150,
    description: "Sitting on the bluffs above the Illinois River, Peoria is central Illinois' largest metro and the global headquarters of Caterpillar. The phrase 'Will it play in Peoria?' reflects its reputation as a bellwether of mainstream American tastes.",
    landmarks: ["Caterpillar Visitors Center", "Peoria Riverfront Museum", "Wildlife Prairie Park"],
    vibe: "Heartland riverfront city with Caterpillar muscle, medical innovation, and all-American identity",
  },
  {
    name: "Champaign",
    slug: "champaign",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 88302,
    description: "Half of the Champaign-Urbana twin cities, Champaign is home to the University of Illinois flagship campus. A Big Ten college town with a strong tech startup scene, craft beer culture, and cornfield horizons in every direction.",
    landmarks: ["University of Illinois at Urbana-Champaign", "Memorial Stadium", "Krannert Center for the Performing Arts"],
    vibe: "Big Ten college town with tech startups, craft beer, and prairie-flat horizons",
  },
  {
    name: "Waukegan",
    slug: "waukegan",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 89321,
    description: "The Lake County seat on Lake Michigan's western shore, Waukegan is a diverse working-class city with a revitalizing lakefront, deep ties to author Ray Bradbury, and one of the most culturally varied communities in the Chicago suburbs.",
    landmarks: ["Waukegan Harbor & Beach", "Genesee Theatre", "Bowen Park"],
    vibe: "Lake Michigan harbor city with blue-collar grit, cultural diversity, and lakefront renewal",
  },
  {
    name: "Cicero",
    slug: "cicero",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 81597,
    description: "A densely populated town immediately west of Chicago, Cicero is one of the largest majority-Hispanic communities in the Midwest. Its Western Electric factory legacy and Al Capone history give way to a vibrant, hardworking present.",
    landmarks: ["Cicero Community Park", "Western Electric Hawthorne Works site", "Sportsman's Park"],
    vibe: "Dense, proudly Hispanic inner suburb with deep industrial roots and tireless community spirit",
  },
  {
    name: "Bloomington",
    slug: "bloomington",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 78902,
    description: "Home to State Farm's headquarters and Illinois Wesleyan University, Bloomington pairs with twin city Normal to form a prosperous metro in the heart of central Illinois corn country with a surprisingly vibrant downtown scene.",
    landmarks: ["State Farm Corporate Headquarters", "Constitution Trail", "David Davis Mansion"],
    vibe: "Insurance-industry anchor with college energy, Constitution Trail cycling, and prairie charm",
  },
  {
    name: "Arlington Heights",
    slug: "arlington-heights",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 77676,
    description: "A well-established northwest suburb of Chicago, Arlington Heights features a walkable downtown with diverse dining, the former Arlington Park racetrack site slated for major redevelopment, and top-rated schools.",
    landmarks: ["Arlington Heights Memorial Library", "Downtown Arlington Heights", "Metropolis Performing Arts Centre"],
    vibe: "Walkable northwest suburb with destination dining, commuter rail convenience, and family stability",
  },
  {
    name: "Evanston",
    slug: "evanston",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 78110,
    description: "Home to Northwestern University on Chicago's northern border, Evanston is an intellectually vibrant lakefront city with beautiful beaches, independent bookstores, and a progressive community that punches well above its weight culturally.",
    landmarks: ["Northwestern University", "Grosse Point Lighthouse", "Evanston Art Center"],
    vibe: "Progressive university city with Lake Michigan beaches, indie shops, and intellectual energy",
  },
  {
    name: "Schaumburg",
    slug: "schaumburg",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 78723,
    description: "A major employment and retail center in Chicago's northwest suburbs, Schaumburg is anchored by the massive Woodfield Mall and a concentration of corporate offices, hotels, and convention facilities along the I-90 corridor.",
    landmarks: ["Woodfield Mall", "Legoland Discovery Center", "Medieval Times"],
    vibe: "Corporate-suburban powerhouse with mega-mall retail, entertainment venues, and office campuses",
  },
  {
    name: "Bolingbrook",
    slug: "bolingbrook",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 75999,
    description: "A diverse southwest suburb of Chicago along I-55 and Route 53, Bolingbrook grew from farmland to one of the most ethnically diverse communities in Illinois with excellent parks, golf courses, and family amenities.",
    landmarks: ["The Promenade Bolingbrook", "Bolingbrook Golf Club", "Hidden Oaks Nature Center"],
    vibe: "Diverse, family-centered suburb with excellent parks, retail corridors, and multicultural community",
  },
  {
    name: "Decatur",
    slug: "decatur",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 70522,
    description: "Known as the Soybean Capital of the World, Decatur is an agricultural processing hub in central Illinois anchored by ADM and Caterpillar. Lake Decatur provides recreation while the city works to diversify its economy.",
    landmarks: ["Scovill Zoo", "Millikin University", "Rock Springs Conservation Area"],
    vibe: "Soybean capital with ag-industry grit, lakeside recreation, and small-city perseverance",
  },
  {
    name: "Palatine",
    slug: "palatine",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 69350,
    description: "A northwest Chicago suburb with a walkable downtown centered on its Metra station, Palatine offers a mix of dining, parks, and community events. Deer Grove Forest Preserve provides hiking and nature within minutes of town.",
    landmarks: ["Deer Grove Forest Preserve", "Palatine Hills Golf Course", "Downtown Palatine"],
    vibe: "Commuter-friendly northwest suburb with forest preserves, downtown dining, and community roots",
  },
  {
    name: "Skokie",
    slug: "skokie",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 67174,
    description: "Bordering Chicago's north side, Skokie is one of the most diverse suburbs in America with over 80 languages spoken. The Illinois Holocaust Museum, vibrant Asian dining corridors, and excellent library system define this welcoming community.",
    landmarks: ["Illinois Holocaust Museum & Education Center", "Westfield Old Orchard", "Emily Oaks Nature Center"],
    vibe: "Hyper-diverse inner suburb with world-class museum, multicultural dining, and inclusive community",
  },
  {
    name: "Des Plaines",
    slug: "des-plaines",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 60675,
    description: "Home to the first McDonald's restaurant and nestled along the Des Plaines River near O'Hare Airport, Des Plaines is a working-class suburb with strong community identity, diverse neighborhoods, and easy access to downtown Chicago.",
    landmarks: ["First McDonald's Museum", "Rivers Casino Des Plaines", "Lake Opeka"],
    vibe: "O'Hare-adjacent suburb with fast-food history, casino entertainment, and blue-collar community pride",
  },
  {
    name: "Orland Park",
    slug: "orland-park",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 60521,
    description: "An affluent southwest suburb of Chicago, Orland Park features upscale shopping at Orland Square Mall, a state-of-the-art recreation complex, and a growing downtown district with restaurants and entertainment.",
    landmarks: ["Orland Square Mall", "Centennial Park", "Orland Park Civic Center"],
    vibe: "Upscale southwest suburb with premium shopping, recreation facilities, and family comfort",
  },
  {
    name: "Tinley Park",
    slug: "tinley-park",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 57040,
    description: "A south suburb known for its outdoor concert venue and charming Oak Park Avenue downtown, Tinley Park balances small-town character with suburban convenience and hosts major events at the Hollywood Casino Amphitheatre.",
    landmarks: ["Hollywood Casino Amphitheatre", "Oak Park Avenue Downtown", "Vogt Visual Arts Center"],
    vibe: "Concert-venue suburb with charming main street, strong Irish heritage, and community pride",
  },
  {
    name: "Oak Lawn",
    slug: "oak-lawn",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 59294,
    description: "A south-side Chicago suburb with deep Irish-American roots, Oak Lawn centers on a busy 95th Street commercial corridor and Advocate Christ Medical Center, one of the largest hospitals in the Chicago metro.",
    landmarks: ["Advocate Christ Medical Center", "Oak Lawn Public Library", "Stony Creek Golf Course"],
    vibe: "South-side suburb with Irish heritage, medical-center anchor, and tight-knit neighborhood bonds",
  },
  {
    name: "Berwyn",
    slug: "berwyn",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 56657,
    description: "A quirky, densely populated inner-west suburb of Chicago, Berwyn is known for its bungalow-belt architecture, thriving arts scene, eclectic shops on Cermak Road, and a growing reputation as one of Chicago's most affordable creative communities.",
    landmarks: ["Cermak Road commercial district", "Berwyn Route 66 Museum", "Proksa Park"],
    vibe: "Quirky bungalow-belt suburb with arts energy, Route 66 nostalgia, and creative affordability",
  },
  {
    name: "Normal",
    slug: "normal",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 54469,
    description: "Twin city to Bloomington and home to Illinois State University, Normal pulses with college energy. Uptown Normal's modern transit center, Children's Discovery Museum, and thriving restaurant scene make it a cultural anchor for central Illinois.",
    landmarks: ["Illinois State University", "Uptown Normal", "Children's Discovery Museum"],
    vibe: "Lively college town with modern transit hub, university energy, and twin-city synergy",
  },
  {
    name: "Wheaton",
    slug: "wheaton",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 54911,
    description: "The DuPage County seat west of Chicago, Wheaton is home to Wheaton College and Cantigny Park. Its tree-lined downtown, excellent schools, and strong community organizations make it one of the most desirable western suburbs.",
    landmarks: ["Cantigny Park & Museums", "Wheaton College", "Cosley Zoo"],
    vibe: "Tree-lined county seat with Christian college heritage, historic estate parks, and suburban charm",
  },
  {
    name: "Downers Grove",
    slug: "downers-grove",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 50089,
    description: "A western Chicago suburb with a vibrant downtown centered on its Metra station, Downers Grove blends tree-shaded residential streets with a walkable Main Street dining and shopping scene and excellent forest preserve access.",
    landmarks: ["Downtown Downers Grove", "Morton Arboretum (nearby)", "Lyman Woods Nature Center"],
    vibe: "Walkable western suburb with Metra-commuter downtown, mature tree canopy, and community events",
  },
  {
    name: "Mount Prospect",
    slug: "mount-prospect",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 57014,
    description: "A northwest suburb with a diverse and welcoming community, Mount Prospect features a charming downtown along Northwest Highway, excellent library, and proximity to both O'Hare Airport and Arlington Heights entertainment.",
    landmarks: ["Downtown Mount Prospect", "Lions Park & Recreation Center", "Melas Park"],
    vibe: "Diverse northwest suburb with welcoming downtown, strong parks, and O'Hare convenience",
  },
  {
    name: "Hoffman Estates",
    slug: "hoffman-estates",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 52530,
    description: "A sprawling northwest Chicago suburb, Hoffman Estates is home to the NOW Arena and the Sears/Discover headquarters campus. Poplar Creek Prairie and Paul Douglas Forest Preserve offer nature escapes within a corporate-suburban setting.",
    landmarks: ["NOW Arena", "Poplar Creek Prairie", "Paul Douglas Forest Preserve"],
    vibe: "Corporate northwest suburb with arena entertainment, prairie preserves, and family subdivisions",
  },
  {
    name: "Glenview",
    slug: "glenview",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 50507,
    description: "An affluent north-shore suburb, Glenview features The Glen Town Center built on a former naval air station, excellent schools, and a mix of established neighborhoods with upscale shopping and dining options.",
    landmarks: ["The Glen Town Center", "Kohl Children's Museum", "Gallery Park"],
    vibe: "Affluent north-shore suburb with former air-station redevelopment, top schools, and refined living",
  },
  {
    name: "Buffalo Grove",
    slug: "buffalo-grove",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 54542,
    description: "A northwest suburb straddling Lake and Cook counties, Buffalo Grove is a family-oriented community with excellent schools, expansive parks, and a significant technology and business corridor along Lake-Cook Road.",
    landmarks: ["Buffalo Grove Town Center", "Mike Rylko Community Park", "Willow Stream Park"],
    vibe: "Family-focused northwest suburb with top schools, tech-corridor employment, and park-rich neighborhoods",
  },
  {
    name: "Bartlett",
    slug: "bartlett",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 50706,
    description: "A far-west suburb of Chicago in DuPage and Cook counties, Bartlett is defined by its extensive park system, annual heritage festival, and a growing community that maintains a small-town feel despite suburban expansion.",
    landmarks: ["James 'Pate' Philip State Park", "Bartlett Park District Community Center", "Apple Orchard Golf Course"],
    vibe: "Far-west suburb with abundant green space, heritage festivals, and small-town community spirit",
  },
  {
    name: "Oak Park",
    slug: "oak-park",
    state: "Illinois",
    stateSlug: "illinois",
    stateAbbr: "IL",
    population: 52233,
    description: "Immediately west of Chicago, Oak Park is world-famous for its Frank Lloyd Wright architecture and as Ernest Hemingway's birthplace. A progressive, diverse inner suburb with excellent dining, arts, and a walkable village center.",
    landmarks: ["Frank Lloyd Wright Home and Studio", "Unity Temple", "Ernest Hemingway Birthplace Museum"],
    vibe: "Architecturally iconic inner suburb with Wright heritage, progressive values, and walkable village life",
  },

  /* ─── Indiana ─── */
  {
    name: "Indianapolis",
    slug: "indianapolis",
    state: "Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    population: 887642,
    description: "Indiana's capital and the crossroads of America, Indianapolis is best known for the Indy 500 and a revitalized downtown anchored by Monument Circle, a world-class children's museum, and a thriving sports and convention scene.",
    landmarks: ["Indianapolis Motor Speedway", "Monument Circle", "Children's Museum of Indianapolis"],
    vibe: "Racing capital with Midwest hospitality, revitalized downtown, and all-American sports culture",
  },
  {
    name: "Fort Wayne",
    slug: "fort-wayne",
    state: "Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    population: 263886,
    description: "Indiana's second-largest city sits at the confluence of three rivers in the northeast. Fort Wayne has invested heavily in riverfront development, with Promenade Park, a growing downtown, and a strong manufacturing and defense sector.",
    landmarks: ["Promenade Park", "Fort Wayne Children's Zoo", "Parkview Field"],
    vibe: "Three-rivers city with riverfront renewal, zoo excellence, and friendly Midwest affordability",
  },
  {
    name: "Evansville",
    slug: "evansville",
    state: "Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    population: 119477,
    description: "Southwestern Indiana's largest city curves along the Ohio River with a revitalized riverfront, strong healthcare sector, and deep German heritage visible in its architecture, festivals, and cuisine.",
    landmarks: ["LST-325 Ship Memorial", "Mesker Park Zoo", "Evansville Riverfront"],
    vibe: "Ohio River bend city with German heritage, riverfront revival, and southern Indiana warmth",
  },
  {
    name: "South Bend",
    slug: "south-bend",
    state: "Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    population: 103453,
    description: "Home to the University of Notre Dame, South Bend has undergone significant downtown revitalization. Once a Studebaker manufacturing hub, the city now blends Notre Dame's academic prestige with a growing tech and startup ecosystem.",
    landmarks: ["University of Notre Dame", "Studebaker National Museum", "East Race Waterway"],
    vibe: "Fighting Irish college city with manufacturing heritage, downtown renewal, and startup energy",
  },
  {
    name: "Carmel",
    slug: "carmel",
    state: "Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    population: 101068,
    description: "Consistently ranked among America's best places to live, Carmel is an affluent Indianapolis suburb famous for its roundabouts, Arts & Design District, world-class performing arts center, and exceptional quality of life.",
    landmarks: ["The Palladium at Center for the Performing Arts", "Carmel Arts & Design District", "Midtown Plaza"],
    vibe: "Top-ranked affluent suburb with roundabout urbanism, performing arts, and design-district charm",
  },
  {
    name: "Fishers",
    slug: "fishers",
    state: "Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    population: 101171,
    description: "One of the fastest-growing cities in Indiana, Fishers has transformed from a Hamilton County bedroom community into a vibrant city with its own identity centered on the Nickel Plate District, tech hub, and family amenities.",
    landmarks: ["Nickel Plate District", "Conner Prairie Interactive History Park", "Fishers District"],
    vibe: "Fast-growing Indianapolis suburb with tech-hub energy, interactive history, and family-first design",
  },
  {
    name: "Bloomington",
    slug: "bloomington",
    state: "Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    population: 79168,
    description: "Home to Indiana University, Bloomington is a progressive college town in the rolling hills of southern Indiana. The limestone quarries, cycling culture immortalized in 'Breaking Away,' and a thriving arts scene give it a unique character.",
    landmarks: ["Indiana University Bloomington", "Kirkwood Avenue", "Monroe Lake"],
    vibe: "Progressive limestone-country college town with cycling culture, live music, and arts energy",
  },
  {
    name: "Hammond",
    slug: "hammond",
    state: "Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    population: 77879,
    description: "On Indiana's border with Chicago, Hammond is the largest city in the Calumet Region. Its Lake Michigan frontage, diverse communities, and proximity to the Chicago job market make it a gateway between the two states.",
    landmarks: ["Wolf Lake Memorial Park", "Hammond Marina", "Horseshoe Casino"],
    vibe: "Illinois-border industrial city with lakefront access, casino entertainment, and Chicago proximity",
  },
  {
    name: "Gary",
    slug: "gary",
    state: "Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    population: 69093,
    description: "Founded by U.S. Steel in 1906, Gary is the birthplace of Michael Jackson and a symbol of American industrial rise and transformation. Indiana Dunes National Park on its doorstep and ongoing reinvestment signal a city looking forward.",
    landmarks: ["Indiana Dunes National Park", "Michael Jackson Family Home", "Gary Aquatorium"],
    vibe: "Steel-city birthplace of the King of Pop with dunes on the doorstep and industrial resilience",
  },
  {
    name: "Lafayette",
    slug: "lafayette",
    state: "Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    population: 70783,
    description: "Paired with West Lafayette and Purdue University across the Wabash River, Lafayette is a growing city blending Boilermaker innovation with a vibrant downtown, diverse dining scene, and strong Subaru manufacturing presence.",
    landmarks: ["Purdue University (West Lafayette)", "Columbian Park Zoo", "Wabash Riverwalk"],
    vibe: "Wabash River city with Purdue spillover energy, Subaru manufacturing, and growing downtown",
  },
  {
    name: "Muncie",
    slug: "muncie",
    state: "Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    population: 65194,
    description: "Home to Ball State University in east-central Indiana, Muncie gained fame as the subject of the landmark 'Middletown' sociology studies. The university, Minnetrista cultural campus, and Cardinal Greenway trail anchor the community.",
    landmarks: ["Ball State University", "Minnetrista", "Cardinal Greenway Trail"],
    vibe: "Middletown USA college city with Ball State energy, cultural campus, and trail connectivity",
  },
  {
    name: "Terre Haute",
    slug: "terre-haute",
    state: "Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    population: 58389,
    description: "On the Wabash River near the Illinois border, Terre Haute is home to Indiana State University, Rose-Hulman Institute of Technology, and the birthplace of labor leader Eugene V. Debs. Downtown revitalization continues to reshape this west-Indiana city.",
    landmarks: ["Indiana State University", "Terre Haute Children's Museum", "Debs Home"],
    vibe: "Wabash River college town with labor history, engineering prestige, and downtown renaissance",
  },
  {
    name: "Noblesville",
    slug: "noblesville",
    state: "Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    population: 69604,
    description: "The Hamilton County seat north of Indianapolis, Noblesville features a charming historic courthouse square, the Ruoff Music Center amphitheater, and White River access. Rapid growth makes it one of Indiana's most dynamic cities.",
    landmarks: ["Ruoff Music Center", "Hamilton County Courthouse Square", "Morse Reservoir"],
    vibe: "Fast-growing county seat with courthouse charm, amphitheater concerts, and reservoir recreation",
  },
  {
    name: "Greenwood",
    slug: "greenwood",
    state: "Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    population: 63850,
    description: "A southern Indianapolis suburb in Johnson County, Greenwood anchors around the Greenwood Park Mall and a revitalizing Old Town district. Strong retail, healthcare, and suburban growth continue to fuel the city's expansion.",
    landmarks: ["Greenwood Park Mall", "Old City Park", "Freedom Springs Aquatic Center"],
    vibe: "Southern Indy suburb with mall-anchored retail, Old Town renewal, and family-suburban growth",
  },
  {
    name: "Anderson",
    slug: "anderson",
    state: "Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    population: 54788,
    description: "A former General Motors manufacturing center northeast of Indianapolis, Anderson is home to Anderson University and Mounds State Park. The city's industrial legacy gives way to trail development and community reinvention.",
    landmarks: ["Mounds State Park", "Anderson University", "Paramount Theatre Centre"],
    vibe: "Post-industrial city with ancient mounds, university presence, and reinvention spirit",
  },
  {
    name: "Westfield",
    slug: "westfield",
    state: "Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    population: 60768,
    description: "One of Indiana's fastest-growing cities in Hamilton County, Westfield is anchored by Grand Park Sports Campus, one of the largest youth sports complexes in the nation. New development, trails, and dining continue to reshape this former farming town.",
    landmarks: ["Grand Park Sports Campus", "Westfield Washington Public Library", "Asa Bales Park"],
    vibe: "Youth-sports destination booming with growth, Grand Park energy, and Hamilton County prosperity",
  },
  {
    name: "Kokomo",
    slug: "kokomo",
    state: "Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    population: 59053,
    description: "Known as the City of Firsts for its automotive inventions, Kokomo in north-central Indiana has deep Chrysler/Stellantis manufacturing roots. The Kokomo Automotive Heritage Museum and nearby reservoir provide recreation and history.",
    landmarks: ["Kokomo Automotive Heritage Museum", "Highland Park", "Kokomo Reservoir"],
    vibe: "Automotive-invention city with Chrysler roots, reservoir recreation, and inventive heritage",
  },
  {
    name: "Lawrence",
    slug: "lawrence",
    state: "Indiana",
    stateSlug: "indiana",
    stateAbbr: "IN",
    population: 52338,
    description: "An Indianapolis suburb on the city's northeast side, Lawrence is home to Fort Benjamin Harrison State Park and a growing community of young families. The former military base's conversion into park and residential space defines the city's modern identity.",
    landmarks: ["Fort Benjamin Harrison State Park", "Lawrence Community Park", "Post Road commercial corridor"],
    vibe: "Northeast Indy suburb with state-park centerpiece, military heritage, and family growth",
  },

  /* ─── Iowa ─── */
  {
    name: "Des Moines",
    slug: "des-moines",
    state: "Iowa",
    stateSlug: "iowa",
    stateAbbr: "IA",
    population: 214133,
    description: "Iowa's capital and largest city, Des Moines is the insurance capital of the world and host to the Iowa State Fair and first-in-the-nation presidential caucuses. A revitalized downtown, sculpture park, and growing food scene make it far more than flyover country.",
    landmarks: ["Iowa State Capitol", "Pappajohn Sculpture Park", "Iowa State Fairgrounds"],
    vibe: "Insurance capital with presidential-caucus prestige, sculpture gardens, and surprising culinary scene",
  },
  {
    name: "Cedar Rapids",
    slug: "cedar-rapids",
    state: "Iowa",
    stateSlug: "iowa",
    stateAbbr: "IA",
    population: 137710,
    description: "Iowa's second-largest city on the Cedar River, Cedar Rapids is the cereal capital of the world thanks to Quaker Oats and General Mills. Rebuilt stronger after devastating 2008 floods, the city features Czech Village and a growing arts district.",
    landmarks: ["NewBo City Market", "Czech Village", "National Czech & Slovak Museum"],
    vibe: "Cereal-capital river city rebuilt from floods with Czech heritage and creative-district energy",
  },
  {
    name: "Davenport",
    slug: "davenport",
    state: "Iowa",
    stateSlug: "iowa",
    stateAbbr: "IA",
    population: 101724,
    description: "The largest of the Quad Cities on the Mississippi River, Davenport is unique among river cities for having no floodwall, keeping its downtown directly connected to the waterfront. Jazz heritage, the Figge Art Museum, and river festivals define the city.",
    landmarks: ["Figge Art Museum", "Modern Woodmen Park", "Village of East Davenport"],
    vibe: "Mississippi riverfront city with jazz heritage, no-floodwall access, and Quad Cities energy",
  },
  {
    name: "Sioux City",
    slug: "sioux-city",
    state: "Iowa",
    stateSlug: "iowa",
    stateAbbr: "IA",
    population: 85797,
    description: "At the junction of Iowa, Nebraska, and South Dakota where the Big Sioux River meets the Missouri, Sioux City is a tri-state hub with a revitalized Historic Fourth Street district, meatpacking heritage, and Lewis and Clark connections.",
    landmarks: ["Lewis and Clark Interpretive Center", "Historic Fourth Street", "Sergeant Floyd Monument"],
    vibe: "Tri-state Missouri River hub with Lewis and Clark history, meatpacking roots, and downtown revival",
  },
  {
    name: "Iowa City",
    slug: "iowa-city",
    state: "Iowa",
    stateSlug: "iowa",
    stateAbbr: "IA",
    population: 74828,
    description: "Home to the University of Iowa and designated a UNESCO City of Literature, Iowa City is one of America's great college towns. The Iowa Writers' Workshop, Hawkeye athletics, and a walkable pedestrian mall create a vibrant cultural hub.",
    landmarks: ["University of Iowa", "Iowa City Pedestrian Mall", "Old Capitol Museum"],
    vibe: "UNESCO literary city with Hawkeye pride, the Writers' Workshop, and pedestrian-mall culture",
  },
  {
    name: "Waterloo",
    slug: "waterloo",
    state: "Iowa",
    stateSlug: "iowa",
    stateAbbr: "IA",
    population: 67314,
    description: "Paired with Cedar Falls in northeast Iowa, Waterloo is a working-class city on the Cedar River with deep John Deere manufacturing roots, a growing tech presence, and the Sullivan Brothers Iowa Veterans Museum honoring five brothers lost at sea in WWII.",
    landmarks: ["John Deere Tractor & Engine Museum", "Sullivan Brothers Iowa Veterans Museum", "Lost Island Waterpark"],
    vibe: "John Deere manufacturing city with WWII memorial heritage and Cedar Valley community",
  },
  {
    name: "Council Bluffs",
    slug: "council-bluffs",
    state: "Iowa",
    stateSlug: "iowa",
    stateAbbr: "IA",
    population: 62877,
    description: "Directly across the Missouri River from Omaha, Nebraska, Council Bluffs is a historic city where Lewis and Clark held council with native tribes. Casino resorts, railroad history, and the Union Pacific Railroad Museum anchor the community.",
    landmarks: ["Union Pacific Railroad Museum", "Historic 100 Block", "Tom Hanafan River's Edge Park"],
    vibe: "Omaha's Iowa twin with Lewis and Clark history, casino entertainment, and railroad heritage",
  },
  {
    name: "Ames",
    slug: "ames",
    state: "Iowa",
    stateSlug: "iowa",
    stateAbbr: "IA",
    population: 66427,
    description: "Home to Iowa State University and its beautiful central campus, Ames is a thriving college town in central Iowa known for Cyclone athletics, agricultural research, and the Reiman Gardens butterfly conservatory.",
    landmarks: ["Iowa State University", "Reiman Gardens", "Jack Trice Stadium"],
    vibe: "Cyclone college town with ag-research prestige, butterfly gardens, and Big 12 athletics",
  },
  {
    name: "West Des Moines",
    slug: "west-des-moines",
    state: "Iowa",
    stateSlug: "iowa",
    stateAbbr: "IA",
    population: 68723,
    description: "An affluent western suburb of Des Moines, West Des Moines is a major employment center with corporate campuses for Wells Fargo, Hy-Vee, and other firms. Jordan Creek Town Center and the Valley Junction historic district offer distinct shopping experiences.",
    landmarks: ["Jordan Creek Town Center", "Valley Junction Historic District", "Raccoon River Park"],
    vibe: "Corporate-suburban powerhouse with upscale mall, historic Valley Junction, and trail-rich parks",
  },
  {
    name: "Ankeny",
    slug: "ankeny",
    state: "Iowa",
    stateSlug: "iowa",
    stateAbbr: "IA",
    population: 72540,
    description: "One of Iowa's fastest-growing cities north of Des Moines, Ankeny is home to DMACC, John Deere's financial division, and the Prairie Trail mixed-use development. A young, growing community with excellent schools and trail systems.",
    landmarks: ["Prairie Trail", "Ankeny Market Pavilion", "Hawkeye Park"],
    vibe: "Booming Des Moines suburb with Prairie Trail development, young families, and rapid growth",
  },
  {
    name: "Dubuque",
    slug: "dubuque",
    state: "Iowa",
    stateSlug: "iowa",
    stateAbbr: "IA",
    population: 59667,
    description: "Iowa's oldest city perches on dramatic Mississippi River bluffs at the Iowa-Illinois-Wisconsin tri-state corner. Victorian architecture, the Fenelon Place Elevator funicular, and the National Mississippi River Museum define this picturesque river city.",
    landmarks: ["National Mississippi River Museum & Aquarium", "Fenelon Place Elevator", "Port of Dubuque"],
    vibe: "Bluff-top Mississippi River city with Victorian charm, funicular rides, and tri-state character",
  },

  /* ─── Kansas ─── */
  {
    name: "Wichita",
    slug: "wichita",
    state: "Kansas",
    stateSlug: "kansas",
    stateAbbr: "KS",
    population: 397532,
    description: "The Air Capital of the World, Wichita is Kansas' largest city and a global center for aircraft manufacturing. Cessna, Beechcraft, and Spirit AeroSystems anchor the economy while the revitalized Old Town district and Keeper of the Plains statue define the city's identity.",
    landmarks: ["Keeper of the Plains", "Old Town Wichita", "Sedgwick County Zoo"],
    vibe: "Air Capital with aircraft-manufacturing muscle, Old Town nightlife, and prairie-city friendliness",
  },
  {
    name: "Overland Park",
    slug: "overland-park",
    state: "Kansas",
    stateSlug: "kansas",
    stateAbbr: "KS",
    population: 197238,
    description: "The second-largest city in Kansas and a premier Johnson County suburb of Kansas City, Overland Park consistently ranks among the best places to live with excellent schools, corporate campuses for Sprint/T-Mobile, and the sprawling Arboretum & Botanical Gardens.",
    landmarks: ["Overland Park Arboretum & Botanical Gardens", "Prairiefire Museum", "Deanna Rose Children's Farmstead"],
    vibe: "Top-ranked KC suburb with corporate prestige, botanical gardens, and family-oriented excellence",
  },
  {
    name: "Kansas City",
    slug: "kansas-city",
    state: "Kansas",
    stateSlug: "kansas",
    stateAbbr: "KS",
    population: 156607,
    description: "The Kansas side of the KC metro, Kansas City KS (known as KCK) features the Kansas Speedway, Legends shopping district, and diverse ethnic neighborhoods. The Argentine and Strawberry Hill neighborhoods showcase the city's rich immigrant heritage.",
    landmarks: ["Kansas Speedway", "The Legends Outlets", "Strawberry Hill Museum"],
    vibe: "KC's Kansas twin with speedway thrills, Legends shopping, and proud immigrant-neighborhood heritage",
  },
  {
    name: "Olathe",
    slug: "olathe",
    state: "Kansas",
    stateSlug: "kansas",
    stateAbbr: "KS",
    population: 146290,
    description: "The Johnson County seat southwest of Kansas City, Olathe is one of the fastest-growing cities in Kansas with top-rated schools, major employers in aerospace and healthcare, and a growing downtown revitalization along Kansas Avenue.",
    landmarks: ["Mahaffie Stagecoach Stop & Farm", "Ernie Miller Nature Center", "Black Bob Bay Aquatic Center"],
    vibe: "Fast-growing county seat with stagecoach heritage, top schools, and suburban KC prosperity",
  },
  {
    name: "Topeka",
    slug: "topeka",
    state: "Kansas",
    stateSlug: "kansas",
    stateAbbr: "KS",
    population: 127191,
    description: "Kansas' state capital where Brown v. Board of Education was born, Topeka sits on the Kansas River with a revitalized downtown NOTO Arts District, the Gage Park zoo, and deep roots in the civil rights movement.",
    landmarks: ["Brown v. Board of Education National Historic Site", "Kansas State Capitol", "NOTO Arts District"],
    vibe: "Civil-rights landmark capital with NOTO arts revival, Kansas River setting, and government roots",
  },
  {
    name: "Lawrence",
    slug: "lawrence",
    state: "Kansas",
    stateSlug: "kansas",
    stateAbbr: "KS",
    population: 95358,
    description: "Home to the University of Kansas on Mount Oread, Lawrence is a vibrant college town with a beloved Massachusetts Street downtown, Jayhawk basketball fervor, and a Free State heritage dating to the Bleeding Kansas era.",
    landmarks: ["University of Kansas", "Massachusetts Street", "Haskell Indian Nations University"],
    vibe: "Jayhawk college town with Mass Street charm, Free State history, and Big 12 basketball passion",
  },
  {
    name: "Shawnee",
    slug: "shawnee",
    state: "Kansas",
    stateSlug: "kansas",
    stateAbbr: "KS",
    population: 67311,
    description: "A Johnson County suburb northwest of Overland Park, Shawnee blends suburban family living with the Shawnee Town 1929 living-history museum, Wonderful World of Oz park, and proximity to major KC metro employment centers.",
    landmarks: ["Shawnee Town 1929", "Wonderful World of Oz Park", "Shawnee Mission Park"],
    vibe: "KC suburb with living-history museum, Oz-themed park, and Johnson County family comfort",
  },
  {
    name: "Manhattan",
    slug: "manhattan",
    state: "Kansas",
    stateSlug: "kansas",
    stateAbbr: "KS",
    population: 55045,
    description: "The Little Apple and home to Kansas State University in the Flint Hills, Manhattan combines Wildcat athletics with a charming Aggieville entertainment district and stunning tall-grass prairie scenery along the Kansas River.",
    landmarks: ["Kansas State University", "Aggieville", "Flint Hills Discovery Center"],
    vibe: "Little Apple college town with Wildcat pride, Flint Hills backdrop, and Aggieville nightlife",
  },
  {
    name: "Lenexa",
    slug: "lenexa",
    state: "Kansas",
    stateSlug: "kansas",
    stateAbbr: "KS",
    population: 57434,
    description: "A Johnson County city between Overland Park and Olathe, Lenexa is known as the Spinach Capital of the World and features the massive Lenexa City Center development, extensive trail system, and strong corporate presence.",
    landmarks: ["Lenexa City Center", "Sar-Ko-Par Trails Park", "Black Hoof Park"],
    vibe: "Spinach Capital suburb with modern city center, trail networks, and Johnson County convenience",
  },
  {
    name: "Salina",
    slug: "salina",
    state: "Kansas",
    stateSlug: "kansas",
    stateAbbr: "KS",
    population: 50869,
    description: "At the crossroads of I-70 and I-135 in central Kansas, Salina is a regional hub with a charming downtown, the Smoky Hill Museum, Rolling Hills Zoo, and an economy anchored by agriculture, manufacturing, and the former Schilling Air Force Base.",
    landmarks: ["Rolling Hills Zoo", "Smoky Hill Museum", "Salina Art Center"],
    vibe: "Central Kansas crossroads city with zoo excellence, Smoky Hill heritage, and prairie hospitality",
  },

  /* ─── Kentucky ─── */
  {
    name: "Louisville",
    slug: "louisville",
    state: "Kentucky",
    stateSlug: "kentucky",
    stateAbbr: "KY",
    population: 633045,
    description: "Kentucky's largest city on the Ohio River, Louisville is home to the Kentucky Derby, Louisville Slugger bats, and a bourbon trail that starts right downtown. The NuLu and Bardstown Road neighborhoods pulse with restaurant and gallery culture.",
    landmarks: ["Churchill Downs", "Louisville Slugger Museum & Factory", "Muhammad Ali Center"],
    vibe: "Derby City with bourbon culture, Ohio River charm, and neighborhood-driven food and arts scenes",
  },
  {
    name: "Lexington",
    slug: "lexington",
    state: "Kentucky",
    stateSlug: "kentucky",
    stateAbbr: "KY",
    population: 322570,
    description: "The Horse Capital of the World, Lexington is surrounded by rolling Bluegrass horse farms and is home to the University of Kentucky. Downtown's vibrant dining and distillery scene, Keeneland racing, and equine heritage make it uniquely Kentucky.",
    landmarks: ["Keeneland Race Course", "Kentucky Horse Park", "University of Kentucky"],
    vibe: "Bluegrass horse country with bourbon distilleries, UK Wildcat passion, and rolling-farm beauty",
  },
  {
    name: "Bowling Green",
    slug: "bowling-green",
    state: "Kentucky",
    stateSlug: "kentucky",
    stateAbbr: "KY",
    population: 80575,
    description: "Home to Western Kentucky University and the only Corvette assembly plant in the world, Bowling Green blends college-town energy with automotive heritage. The National Corvette Museum and Lost River Cave attract visitors from across the country.",
    landmarks: ["National Corvette Museum", "Lost River Cave", "Western Kentucky University"],
    vibe: "Corvette-country college town with cave adventures, Hilltoppers spirit, and manufacturing pride",
  },
  {
    name: "Owensboro",
    slug: "owensboro",
    state: "Kentucky",
    stateSlug: "kentucky",
    stateAbbr: "KY",
    population: 60972,
    description: "The BBQ Capital of Kentucky on the Ohio River, Owensboro is famous for its mutton barbecue, the International Bluegrass Music Museum, and a beautifully redeveloped riverfront with walking trails, splash pads, and performance venues.",
    landmarks: ["International Bluegrass Music Museum", "Smothers Park Riverfront", "Owensboro Museum of Science & History"],
    vibe: "Mutton-BBQ river city with bluegrass music heritage, riverfront renewal, and western Kentucky warmth",
  },
  {
    name: "Covington",
    slug: "covington",
    state: "Kentucky",
    stateSlug: "kentucky",
    stateAbbr: "KY",
    population: 53282,
    description: "Directly across the Ohio River from Cincinnati, Covington is northern Kentucky's urban core connected by the iconic Roebling Suspension Bridge. MainStrasse Village's German heritage, craft breweries, and river views make it a regional destination.",
    landmarks: ["Roebling Suspension Bridge", "MainStrasse Village", "Devou Park"],
    vibe: "Cincinnati's Kentucky neighbor with Roebling Bridge views, German village charm, and craft-beer culture",
  },
  {
    name: "Richmond",
    slug: "richmond",
    state: "Kentucky",
    stateSlug: "kentucky",
    stateAbbr: "KY",
    population: 58406,
    description: "Home to Eastern Kentucky University south of Lexington, Richmond is a growing college town with Civil War battlefield history at the Battle of Richmond site, access to the Daniel Boone National Forest, and a revitalizing downtown.",
    landmarks: ["Eastern Kentucky University", "Battle of Richmond Civil War Site", "Fort Boonesborough State Park"],
    vibe: "EKU college town with Civil War history, Daniel Boone country access, and Bluegrass setting",
  },

  /* ─── Louisiana ─── */
  {
    name: "New Orleans",
    slug: "new-orleans",
    state: "Louisiana",
    stateSlug: "louisiana",
    stateAbbr: "LA",
    population: 383997,
    description: "The Big Easy is unlike any other American city — a sultry, music-soaked crescent along the Mississippi where jazz, Creole cuisine, Mardi Gras, and centuries of French, Spanish, and African heritage create a culture that exists nowhere else on Earth.",
    landmarks: ["French Quarter & Bourbon Street", "Jackson Square & St. Louis Cathedral", "Garden District"],
    vibe: "Jazz-infused, Creole-soul city with Mardi Gras spirit, Mississippi magic, and one-of-a-kind culture",
  },
  {
    name: "Baton Rouge",
    slug: "baton-rouge",
    state: "Louisiana",
    stateSlug: "louisiana",
    stateAbbr: "LA",
    population: 227470,
    description: "Louisiana's capital and home to LSU, Baton Rouge sits on the Mississippi River bluffs with the tallest state capitol building in America. Tiger tailgating, Southern cuisine, and petrochemical industry wealth drive this Gulf South city.",
    landmarks: ["Louisiana State Capitol", "LSU Tiger Stadium", "Old State Capitol"],
    vibe: "Geaux Tigers capital city with Mississippi River bluffs, Southern food, and state-government power",
  },
  {
    name: "Shreveport",
    slug: "shreveport",
    state: "Louisiana",
    stateSlug: "louisiana",
    stateAbbr: "LA",
    population: 188987,
    description: "Northwest Louisiana's largest city on the Red River, Shreveport pairs with Bossier City to form a metro known for riverboat casinos, Barksdale Air Force Base, and a growing arts and music scene in the Highland neighborhood.",
    landmarks: ["Shreveport Aquarium", "Sci-Port Discovery Center", "Highland Historic District"],
    vibe: "Red River casino city with air-force presence, Highland arts scene, and Ark-La-Tex culture",
  },
  {
    name: "Metairie",
    slug: "metairie",
    state: "Louisiana",
    stateSlug: "louisiana",
    stateAbbr: "LA",
    population: 145880,
    description: "Jefferson Parish's largest community directly west of New Orleans, Metairie is a densely populated suburb that shares New Orleans' food culture while offering suburban convenience. Veterans Memorial Boulevard is the commercial spine lined with restaurants.",
    landmarks: ["Lakeside Shopping Center", "Lafreniere Park", "Veterans Memorial Boulevard corridor"],
    vibe: "New Orleans' go-to suburb with the same food culture, lakefront proximity, and suburban ease",
  },
  {
    name: "Lafayette",
    slug: "lafayette",
    state: "Louisiana",
    stateSlug: "louisiana",
    stateAbbr: "LA",
    population: 121374,
    description: "The heart of Cajun Country, Lafayette is the cultural capital of Acadiana where Cajun and Creole music, food, and French language heritage thrive. Boudin, crawfish boils, and dance halls define daily life in this south-central Louisiana city.",
    landmarks: ["Vermilionville Living History Museum", "Acadian Cultural Center", "Downtown Lafayette"],
    vibe: "Cajun Country capital with zydeco dance halls, crawfish culture, and joie de vivre",
  },
  {
    name: "Lake Charles",
    slug: "lake-charles",
    state: "Louisiana",
    stateSlug: "louisiana",
    stateAbbr: "LA",
    population: 83137,
    description: "On the shores of Lake Charles in southwest Louisiana, this petrochemical hub is also known for its casino resorts, Creole heritage, and annual Mardi Gras celebration that rivals New Orleans. The Contraband Days pirate festival adds local flavor.",
    landmarks: ["L'Auberge Casino Resort", "Crying Eagle Brewing Company", "1911 Historic City Hall Arts & Cultural Center"],
    vibe: "Petrochemical-powered lake city with casino glitz, Creole spice, and its own Mardi Gras",
  },
  {
    name: "Kenner",
    slug: "kenner",
    state: "Louisiana",
    stateSlug: "louisiana",
    stateAbbr: "LA",
    population: 66759,
    description: "Home to Louis Armstrong New Orleans International Airport in Jefferson Parish, Kenner is a suburban gateway to New Orleans with Rivertown museums, Treasure Chest Casino, and the Pontchartrain Convention & Civic Center.",
    landmarks: ["Louis Armstrong New Orleans International Airport", "Rivertown Museums", "Treasure Chest Casino"],
    vibe: "New Orleans airport city with Rivertown charm, casino entertainment, and suburban Jefferson Parish living",
  },
  {
    name: "Bossier City",
    slug: "bossier-city",
    state: "Louisiana",
    stateSlug: "louisiana",
    stateAbbr: "LA",
    population: 68159,
    description: "Shreveport's twin city across the Red River, Bossier City is anchored by Barksdale Air Force Base, the Louisiana Boardwalk casino and shopping district, and a concentration of entertainment venues that make it northwest Louisiana's fun zone.",
    landmarks: ["Louisiana Boardwalk", "Barksdale Air Force Base", "CenturyLink Center"],
    vibe: "Red River entertainment twin with air-force base, boardwalk casinos, and Shreveport synergy",
  },
  {
    name: "Monroe",
    slug: "monroe",
    state: "Louisiana",
    stateSlug: "louisiana",
    stateAbbr: "LA",
    population: 52035,
    description: "The largest city in northeast Louisiana on the Ouachita River, Monroe is home to the University of Louisiana at Monroe, the Biedenharn Museum where Coca-Cola was first bottled, and the Black Bayou Lake National Wildlife Refuge.",
    landmarks: ["Biedenharn Museum & Gardens", "Black Bayou Lake NWR", "University of Louisiana at Monroe"],
    vibe: "Ouachita River city where Coke was first bottled, with bayou wildlife and university energy",
  },

  /* ─── Maine ─── */
  {
    name: "Portland",
    slug: "portland",
    state: "Maine",
    stateSlug: "maine",
    stateAbbr: "ME",
    population: 68408,
    description: "Maine's largest city on Casco Bay, Portland is one of America's top food destinations with more restaurants per capita than almost any city. The Old Port's cobblestone streets, working waterfront, craft breweries, and island ferry access define this coastal gem.",
    landmarks: ["Old Port District", "Portland Head Light", "Eastern Promenade Trail"],
    vibe: "Foodie harbor city with cobblestone Old Port, craft breweries, and Casco Bay island access",
  },

  /* ─── Maryland ─── */
  {
    name: "Baltimore",
    slug: "baltimore",
    state: "Maryland",
    stateSlug: "maryland",
    stateAbbr: "MD",
    population: 585708,
    description: "Charm City on the Chesapeake Bay, Baltimore is a port city with a revitalized Inner Harbor, world-class Johns Hopkins institutions, iconic row houses, and a fierce local identity built on crab cakes, Natty Boh, and Orioles baseball.",
    landmarks: ["Inner Harbor", "Fort McHenry National Monument", "National Aquarium"],
    vibe: "Charm City with crab-cake pride, Inner Harbor energy, and blue-collar Baltimore grit",
  },
  {
    name: "Frederick",
    slug: "frederick",
    state: "Maryland",
    stateSlug: "maryland",
    stateAbbr: "MD",
    population: 78171,
    description: "A historic city at the crossroads of western Maryland, Frederick features a beautifully preserved downtown along Carroll Creek, Civil War heritage, and a thriving arts and farm-to-table dining scene backed by Catoctin Mountain views.",
    landmarks: ["Carroll Creek Linear Park", "National Museum of Civil War Medicine", "Schifferstadt Architectural Museum"],
    vibe: "Historic crossroads city with creek-side dining, Civil War heritage, and Catoctin Mountain charm",
  },
  {
    name: "Rockville",
    slug: "rockville",
    state: "Maryland",
    stateSlug: "maryland",
    stateAbbr: "MD",
    population: 68401,
    description: "The Montgomery County seat just north of Washington DC, Rockville is a diverse edge city with the Rockville Town Square development, abundant Asian dining, biotech research corridors, and excellent Metro access to the nation's capital.",
    landmarks: ["Rockville Town Square", "Glenview Mansion at Civic Center Park", "F. Scott Fitzgerald grave at St. Mary's Church"],
    vibe: "DC-adjacent edge city with biotech corridors, diverse Asian dining, and Metro-connected convenience",
  },
  {
    name: "Gaithersburg",
    slug: "gaithersburg",
    state: "Maryland",
    stateSlug: "maryland",
    stateAbbr: "MD",
    population: 69657,
    description: "A diverse city in upper Montgomery County, Gaithersburg is home to the National Institute of Standards and Technology (NIST), the Lakeforest Mall area, and Kentlands — one of the first new-urbanist communities in America.",
    landmarks: ["NIST (National Institute of Standards and Technology)", "Kentlands Town Center", "Seneca Creek State Park"],
    vibe: "NIST-anchored diverse suburb with new-urbanist Kentlands, state park access, and DC-corridor growth",
  },
  {
    name: "Bowie",
    slug: "bowie",
    state: "Maryland",
    stateSlug: "maryland",
    stateAbbr: "MD",
    population: 58025,
    description: "A planned community in Prince George's County between DC and Annapolis, Bowie features Bowie State University, extensive trail systems, and a diverse, affluent suburban community with one of the largest Black middle-class populations in America.",
    landmarks: ["Bowie State University", "Allen Pond Park", "Bowie Town Center"],
    vibe: "Diverse planned community with Black middle-class prosperity, trails, and DC-Annapolis access",
  },
  {
    name: "Hagerstown",
    slug: "hagerstown",
    state: "Maryland",
    stateSlug: "maryland",
    stateAbbr: "MD",
    population: 53590,
    description: "The Hub City of western Maryland at the crossroads of I-70 and I-81, Hagerstown is surrounded by Civil War battlefields, Appalachian Trail access, and a revitalizing downtown arts and cultural district anchored by the Maryland Theatre.",
    landmarks: ["Maryland Theatre", "Hagerstown City Park", "Antietam National Battlefield (nearby)"],
    vibe: "Western Maryland crossroads with Civil War surroundings, Appalachian access, and arts-district renewal",
  },
  {
    name: "Annapolis",
    slug: "annapolis",
    state: "Maryland",
    stateSlug: "maryland",
    stateAbbr: "MD",
    population: 40812,
    description: "Maryland's capital and home to the U.S. Naval Academy, Annapolis is a sailing capital with a beautifully preserved colonial downtown, Chesapeake Bay waterfront dining, and centuries of maritime heritage on the Severn River.",
    landmarks: ["U.S. Naval Academy", "Maryland State House", "City Dock & Ego Alley"],
    vibe: "Sailing capital with Naval Academy prestige, colonial architecture, and Chesapeake Bay lifestyle",
  },
  {
    name: "College Park",
    slug: "college-park",
    state: "Maryland",
    stateSlug: "maryland",
    stateAbbr: "MD",
    population: 52507,
    description: "Home to the University of Maryland flagship campus, College Park is a college town adjacent to Washington DC with Terrapin athletics, the College Park Aviation Museum at the world's oldest continuously operating airport, and growing Purple Line transit development.",
    landmarks: ["University of Maryland", "College Park Aviation Museum", "Xfinity Center"],
    vibe: "Terrapin college town with DC adjacency, aviation history, and Big Ten energy",
  },
  {
    name: "Salisbury",
    slug: "salisbury",
    state: "Maryland",
    stateSlug: "maryland",
    stateAbbr: "MD",
    population: 33640,
    description: "The largest city on Maryland's Eastern Shore, Salisbury is the commercial hub of the Delmarva Peninsula with Salisbury University, Perdue Farms headquarters, and the Wicomico River providing access to the Chesapeake Bay.",
    landmarks: ["Salisbury University", "Ward Museum of Wildfowl Art", "Salisbury City Park & Zoo"],
    vibe: "Eastern Shore hub with poultry-industry roots, university presence, and Delmarva Peninsula charm",
  },
  {
    name: "Laurel",
    slug: "laurel",
    state: "Maryland",
    stateSlug: "maryland",
    stateAbbr: "MD",
    population: 32381,
    description: "Straddling Prince George's and Howard counties between DC and Baltimore, Laurel is a diverse city with historic Main Street, proximity to NSA at Fort Meade, and the Patuxent Wildlife Research Center providing green space and nature.",
    landmarks: ["Historic Main Street Laurel", "Patuxent Wildlife Research Center", "Laurel Park (horse racing)"],
    vibe: "DC-Baltimore corridor city with historic Main Street, intelligence-community proximity, and wildlife preserve",
  },

  /* ─── Massachusetts ─── */
  {
    name: "Boston",
    slug: "boston",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 675647,
    description: "The Cradle of the American Revolution, Boston is a world-class city where colonial history meets cutting-edge innovation. Harvard, MIT, and dozens of universities fuel a knowledge economy while Fenway Park, the Freedom Trail, and the waterfront define its soul.",
    landmarks: ["Freedom Trail", "Fenway Park", "Boston Common & Public Garden"],
    vibe: "Revolutionary history meets world-class universities, Red Sox passion, and waterfront innovation",
  },
  {
    name: "Worcester",
    slug: "worcester",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 206518,
    description: "The Heart of the Commonwealth and second-largest city in New England, Worcester is a diverse college city with a dozen institutions of higher learning, a revitalized Canal District, and the world-class Worcester Art Museum.",
    landmarks: ["Worcester Art Museum", "Polar Park (WooSox)", "Hanover Theatre"],
    vibe: "College-city renaissance with WooSox baseball, Canal District nightlife, and industrial grit",
  },
  {
    name: "Springfield",
    slug: "springfield",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 155929,
    description: "The birthplace of basketball and the City of Firsts, Springfield anchors western Massachusetts on the Connecticut River. The Naismith Memorial Basketball Hall of Fame, the Springfield Armory, and MGM Springfield casino define this historically inventive city.",
    landmarks: ["Naismith Memorial Basketball Hall of Fame", "Springfield Armory National Historic Site", "MGM Springfield"],
    vibe: "Basketball birthplace with casino revival, Connecticut River setting, and inventive heritage",
  },
  {
    name: "Cambridge",
    slug: "cambridge",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 118977,
    description: "Home to Harvard University and MIT across the Charles River from Boston, Cambridge is one of the most intellectually dense square miles on Earth. Biotech labs, indie bookstores, Harvard Square, and Kendall Square's innovation hub define this city of ideas.",
    landmarks: ["Harvard University", "Massachusetts Institute of Technology (MIT)", "Harvard Square"],
    vibe: "Intellectual epicenter with Harvard and MIT prestige, biotech innovation, and bookstore-cafe culture",
  },
  {
    name: "Lowell",
    slug: "lowell",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 115554,
    description: "The birthplace of the American Industrial Revolution, Lowell's historic mill buildings along the Merrimack River canal system now house a national park, UMass Lowell, and a diverse immigrant community with one of America's largest Cambodian populations.",
    landmarks: ["Lowell National Historical Park", "UMass Lowell", "Lowell Folk Festival"],
    vibe: "Mill-city birthplace of American industry with canal heritage, Cambodian culture, and university energy",
  },
  {
    name: "Brockton",
    slug: "brockton",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 105643,
    description: "The City of Champions south of Boston, Brockton produced boxing legends Rocky Marciano and Marvin Hagler. A diverse working-class city with Cape Verdean and Haitian communities, it serves as a regional hub between Boston and Cape Cod.",
    landmarks: ["Fuller Craft Museum", "D.W. Field Park", "Rocky Marciano statue"],
    vibe: "City of Champions with boxing legacy, Cape Verdean culture, and working-class resilience",
  },
  {
    name: "New Bedford",
    slug: "new-bedford",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 101079,
    description: "Once the whaling capital of the world immortalized in Moby-Dick, New Bedford remains America's top commercial fishing port. The Whaling National Historical Park, Portuguese community, and working waterfront define this South Coast city.",
    landmarks: ["New Bedford Whaling Museum", "New Bedford Whaling National Historical Park", "Buttonwood Park Zoo"],
    vibe: "America's fishing capital with Moby-Dick whaling history, Portuguese heritage, and working-waterfront grit",
  },
  {
    name: "Quincy",
    slug: "quincy",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 101636,
    description: "The City of Presidents — birthplace of John Adams and John Quincy Adams — Quincy sits south of Boston on the coast with a thriving Asian-American community, historic shipyards, and granite quarrying heritage.",
    landmarks: ["Adams National Historical Park", "United First Parish Church (Church of the Presidents)", "Wollaston Beach"],
    vibe: "Presidential birthplace with thriving Asian community, coastal access, and granite-quarry heritage",
  },
  {
    name: "Lynn",
    slug: "lynn",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 101253,
    description: "A diverse working-class city north of Boston on the coast, Lynn was once the shoe-making capital of the world. Today its waterfront, diverse immigrant communities, and proximity to Nahant Beach make it one of the most affordable coastal cities near Boston.",
    landmarks: ["Lynn Shore & Nahant Beach Reservation", "High Rock Tower", "Lynn Museum & Historical Society"],
    vibe: "Shoe-city heritage meets coastal affordability with diverse immigrant energy and beach access",
  },
  {
    name: "Fall River",
    slug: "fall-river",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 93885,
    description: "A former textile-mill city on Mount Hope Bay where the Taunton River meets Narragansett Bay, Fall River is known for its Portuguese-American community, Battleship Cove naval museum, and dramatic granite mill buildings lining the waterfront.",
    landmarks: ["Battleship Cove", "Fall River Heritage State Park", "Lizzie Borden House"],
    vibe: "Granite-mill waterfront city with Portuguese soul, battleship museum, and Narragansett Bay access",
  },
  {
    name: "Newton",
    slug: "newton",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 88923,
    description: "The Garden City west of Boston, Newton is an affluent community of 13 distinct villages with top-rated schools, beautiful parks, and a location along the Boston Marathon route. Newton Centre and Newtonville offer charming village shopping districts.",
    landmarks: ["Heartbreak Hill (Boston Marathon)", "Crystal Lake", "Newton Free Library"],
    vibe: "Garden City of 13 villages with Marathon-route fame, top schools, and affluent suburban charm",
  },
  {
    name: "Lawrence",
    slug: "lawrence",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 89143,
    description: "A historic mill city on the Merrimack River, Lawrence was the site of the famous 1912 Bread and Roses strike. Today it is one of the most Dominican cities in America with vibrant Latino culture, affordable housing, and industrial-chic mill conversions.",
    landmarks: ["Lawrence Heritage State Park", "Bread and Roses Strike memorial", "Great Stone Dam"],
    vibe: "Bread and Roses mill city with Dominican vibrancy, Merrimack River setting, and working-class pride",
  },
  {
    name: "Somerville",
    slug: "somerville",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 81045,
    description: "One of the most densely populated cities in New England just north of Cambridge, Somerville has transformed from working-class Slummerville to one of Boston's hippest communities with Davis Square, Assembly Row, and the new Green Line Extension.",
    landmarks: ["Davis Square", "Assembly Row", "Prospect Hill Tower"],
    vibe: "Hip, dense inner suburb with Davis Square indie culture, Assembly Row shopping, and transit renewal",
  },
  {
    name: "Framingham",
    slug: "framingham",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 72362,
    description: "A MetroWest city famous for the Framingham Heart Study that shaped modern cardiology, Framingham is a diverse community with a growing Brazilian population, the Shoppers World retail area, and a revitalizing downtown anchored by the commuter rail.",
    landmarks: ["Framingham Centre Common", "Shoppers World", "Garden in the Woods"],
    vibe: "Heart Study city with Brazilian cultural energy, MetroWest convenience, and diverse community",
  },
  {
    name: "Haverhill",
    slug: "haverhill",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 67707,
    description: "A Merrimack Valley city on the New Hampshire border, Haverhill has revitalized its downtown with brewery culture, arts spaces in repurposed shoe factories, and waterfront development along the Merrimack River. One of the best-value cities north of Boston.",
    landmarks: ["Bradford College (former campus)", "Winnekenni Castle", "Merrimack River waterfront"],
    vibe: "Merrimack Valley city with brewery renaissance, shoe-factory arts, and NH-border affordability",
  },
  {
    name: "Waltham",
    slug: "waltham",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 64015,
    description: "The Watch City west of Boston along the Charles River, Waltham is home to Brandeis University and Bentley University. Moody Street's international restaurant row and the Charles River Museum of Industry anchor this diverse, livable city.",
    landmarks: ["Brandeis University", "Moody Street restaurant row", "Charles River Museum of Industry"],
    vibe: "Watch City with two universities, Moody Street dining diversity, and Charles River charm",
  },
  {
    name: "Malden",
    slug: "malden",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 66263,
    description: "A diverse city just north of Boston on the Orange Line, Malden has become a food destination thanks to its Chinese, Korean, and pan-Asian restaurants. Pleasant Street's global dining scene rivals any neighborhood in the Boston metro for variety.",
    landmarks: ["Malden Center MBTA Station", "Waitts Mount", "Pleasant Street dining corridor"],
    vibe: "Orange Line city with pan-Asian food scene, dense diversity, and affordable urban convenience",
  },
  {
    name: "Brookline",
    slug: "brookline",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 63191,
    description: "An affluent town entirely surrounded by Boston, Brookline is the birthplace of JFK and home to Coolidge Corner's independent cinema and shops. Tree-lined streets, excellent schools, and Green Line access make it one of the most desirable communities in Greater Boston.",
    landmarks: ["JFK National Historic Site", "Coolidge Corner Theatre", "Larz Anderson Auto Museum"],
    vibe: "Boston-surrounded enclave with JFK heritage, Coolidge Corner charm, and leafy affluence",
  },
  {
    name: "Medford",
    slug: "medford",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 63489,
    description: "Home to Tufts University on the Mystic River north of Boston, Medford combines academic energy with a diverse residential community. The Mystic River Reservation, historic Royall House, and Green Line Extension have revitalized this inner suburb.",
    landmarks: ["Tufts University", "Mystic River Reservation", "Isaac Royall House"],
    vibe: "Tufts University city with Mystic River trails, Green Line expansion, and diverse neighborhoods",
  },
  {
    name: "Taunton",
    slug: "taunton",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 59365,
    description: "The Silver City and seat of Bristol County, Taunton is one of the oldest cities in America with deep colonial history, a revitalizing downtown, and the Christmas-lights tradition on Taunton Green that draws visitors from across southern New England.",
    landmarks: ["Taunton Green", "Old Colony History Museum", "Massasoit State Park"],
    vibe: "Silver City with colonial roots, famous Christmas lights, and southern New England small-city charm",
  },
  {
    name: "Chicopee",
    slug: "chicopee",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 55126,
    description: "A city at the confluence of the Chicopee and Connecticut rivers in western Massachusetts, Chicopee has deep Polish-American heritage, Westover Air Reserve Base, and a working-class community proud of its kielbasa, pierogies, and neighborhood identity.",
    landmarks: ["Westover Air Reserve Base", "Chicopee State Park", "Chicopee Falls Dam"],
    vibe: "Polish-heritage river city with air-reserve base, Connecticut River setting, and neighborhood pride",
  },
  {
    name: "Weymouth",
    slug: "weymouth",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 57746,
    description: "A South Shore town with deep colonial history — Abigail Adams was born here — Weymouth features miles of coastline, the former South Weymouth Naval Air Station redevelopment (now Southfield), and easy access to both Boston and Cape Cod.",
    landmarks: ["Abigail Adams Birthplace", "Webb Memorial State Park", "George Lane Beach"],
    vibe: "South Shore coastal town with Abigail Adams heritage, beach access, and naval-station redevelopment",
  },
  {
    name: "Revere",
    slug: "revere",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 62186,
    description: "Home to America's first public beach, Revere Beach, this dense city north of Boston has experienced a renaissance with luxury beachfront development, diverse immigrant communities, and Blue Line transit access to downtown Boston.",
    landmarks: ["Revere Beach", "Wonderland MBTA Station", "Revere Beach Reservation"],
    vibe: "America's first public beach with luxury redevelopment, dense diversity, and Blue Line access",
  },
  {
    name: "Peabody",
    slug: "peabody",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 54251,
    description: "The Leather City on the North Shore, Peabody was once the tanning capital of America. Today it is known for the Northshore Mall, proximity to Salem, and a strong community with Irish, Greek, and Portuguese heritage neighborhoods.",
    landmarks: ["Northshore Mall", "Brooksby Farm", "George Peabody House Museum"],
    vibe: "Leather City with North Shore mall shopping, diverse heritage, and Salem-adjacent character",
  },
  {
    name: "Plymouth",
    slug: "plymouth",
    state: "Massachusetts",
    stateSlug: "massachusetts",
    stateAbbr: "MA",
    population: 61217,
    description: "America's Hometown where the Pilgrims landed in 1620, Plymouth is a sprawling coastal town with Plymouth Rock, the Mayflower II replica, cranberry bogs, and miles of South Shore beaches along Cape Cod Bay.",
    landmarks: ["Plymouth Rock", "Mayflower II", "Plimoth Patuxet Museums"],
    vibe: "America's Hometown with Pilgrim history, cranberry bogs, and Cape Cod Bay waterfront",
  },
];
