import type { Service, Neighborhood } from "./data";

interface MoneyPageContent {
  heroDescription: string;
  sections: { heading: string; content: string }[];
}

const serviceContent: Record<string, { projectDescription: string; sizingGuide: string; weightTips: string; bestPractices: string; whyUs: string }> = {
  "construction-dumpster-rental": {
    projectDescription: "Construction projects are among the most waste-intensive jobs in the industry. From foundation work through framing, roofing, drywall installation, and finishing, every phase generates debris that needs to go somewhere. Lumber cutoffs, drywall scraps, concrete waste, metal flashing, packaging materials, and general job site debris accumulate fast. Without a properly sized dumpster on site, crews waste hours hauling debris to a distant container or making dump runs. A roll-off dumpster positioned right at the work area keeps your crew focused on building, not on waste management. We work with general contractors, subcontractors, and owner-builders across Florida to provide reliable dumpster service that matches the pace of construction.",
    sizingGuide: "Most residential construction jobs need a 20 yard dumpster as a baseline. For framing-only phases with mostly lumber cutoffs, a 20 yard handles a typical single-family home. Once you add drywall, roofing, and mixed debris, a 30 yard becomes the better choice. Commercial construction almost always starts at 30 yards. For long-duration builds, we set up rotation schedules — when one fills up, we swap it for an empty within hours. Multi-building projects often run 2-3 dumpsters simultaneously. The key is matching container size to the current phase of work, not trying to cover the entire project with one container.",
    weightTips: "Construction debris varies wildly in weight. Lumber scraps run about 300-500 lbs per cubic yard. Drywall comes in around 500-700 lbs per cubic yard. Concrete and masonry shoot up to 2,000-2,500 lbs per cubic yard. Roofing shingles fall in the 700-1,000 lbs per cubic yard range. If your project involves heavy materials like concrete or brick, separate them from lighter debris. Two properly loaded dumpsters cost less than one overweight dumpster with overage charges. We help you plan the weight strategy before the first shovel hits dirt.",
    bestPractices: "Position your dumpster where the most waste is generated — near the lumber staging area during framing, close to the building entrance during interior work. Keep a clear path from the work area to the dumpster. Break down oversized materials before tossing them in — flat-packing drywall scraps and cutting long lumber pieces maximizes space. Load heavy items first (concrete, tile, masonry) and lighter items on top. Close the rear swing door before throwing anything over the sides. Daily end-of-day cleanup into the dumpster keeps your site OSHA-compliant and impresses inspectors.",
    whyUs: "We built our business around contractors. That means priority scheduling when residential customers face wait times, volume pricing that saves you 15-25% on every rental, dedicated account management so you have one person who knows your projects, and NET-30 billing so you are not paying upfront for every container. Our drivers know construction sites — they can place a 30 yard dumpster with precision in tight spots, navigate around equipment, and time deliveries to avoid disrupting crane operations or concrete pours.",
  },
  "residential-dumpster-rental": {
    projectDescription: "Residential dumpster rental covers every type of home project that generates more waste than your weekly trash pickup can handle. Garage cleanouts where you finally confront years of accumulated stuff. Attic purges that unearth boxes you have not opened since you moved in. Shed demolitions that turn a rotting eyesore into usable yard space. Pre-move decluttering that saves you hundreds on moving costs by reducing your load. Basement cleanouts, yard overhauls, fence replacements, small deck removals, and the catch-all category of stuff-that-has-been-sitting-there-too-long. A dumpster in your driveway changes the psychology of cleaning — when disposing of something is as easy as walking it outside and tossing it in, you suddenly find the motivation to let go of things you have been holding onto for no reason.",
    sizingGuide: "For most residential projects, a 10 yard dumpster is all you need. It holds about 4 pickup truck loads — enough for a garage cleanout, a single room renovation, or a moderate yard cleanup. When the project scope expands to multiple rooms, a full estate cleanout, or a renovation involving drywall and flooring removal, the 20 yard becomes the right call at roughly 8 pickup truck loads. The 30 yard is rarely needed for residential unless you are doing a whole-house gut or major addition. Our recommendation: describe your project to us and we will tell you the right size. We would rather put you in a 10 yard and save you money than upsell you a 20 yard you do not need.",
    weightTips: "Residential debris is usually light relative to its volume. Furniture, clothing, cardboard boxes, old electronics, toys, kitchenware — these items fill space but do not weigh much. The exceptions are old appliances (a refrigerator weighs 200-300 lbs), mattresses (80-150 lbs but bulky), and any concrete, tile, or dirt from landscaping. Most residential cleanouts come in well under the 2-ton weight limit on a 10 yard dumpster. You would have to work hard to exceed it with household items alone.",
    bestPractices: "Start with the easiest wins — obviously broken items, empty boxes, things you forgot you owned. Build momentum before tackling sentimental items. Use the four-category method: keep, donate, sell, trash. Everything in the trash category goes straight to the dumpster. Break down furniture when possible to maximize space — remove legs from tables, disassemble bed frames, flatten cardboard boxes. Load the dumpster from back to front, distributing weight evenly. The rear swing door opens for walk-in loading of heavy items — use it instead of trying to lift heavy things over the sides.",
    whyUs: "We make residential dumpster rental simple because we know it is probably your first time. You call or text, tell us about your project, and we recommend the right size at a flat rate with no hidden fees. We deliver on your schedule, you load at your own pace, and we pick up when you are done. No pressure, no upselling, no surprise charges. If you finish early, we pick up early. If you need more time, we extend by the day. We have served thousands of homeowners across Florida and we know how to make this process painless.",
  },
  "commercial-dumpster-rental": {
    projectDescription: "Commercial dumpster rental serves businesses, property managers, retail operations, restaurants, offices, and industrial facilities that generate waste beyond what standard trash service handles. Tenant improvement buildouts that gut and rebuild commercial spaces. Shopping center renovations that update aging retail environments. Office relocations that produce mountains of old furniture, equipment, and files. Restaurant closures or remodels that strip out commercial kitchen equipment, booths, flooring, and decor. Warehouse cleanouts during business closures or relocations. Hotel renovations room by room or floor by floor. The commercial world generates waste at scale, and managing it requires a waste removal partner who understands business timelines and constraints.",
    sizingGuide: "Commercial projects typically start at 20 yards and scale up. A single office suite TI buildout might fill one 20 yard container. A full floor renovation in a commercial building needs 30 yards with rotation. Warehouse cleanouts often require multiple 30 yard containers running simultaneously. Retail renovations vary widely — a small boutique remodel fits in a 20 yard while a department store gut-and-rebuild might need continuous 30 yard rotation for weeks. We assess every commercial project individually because cookie-cutter sizing wastes your money and your time.",
    weightTips: "Commercial debris weight depends heavily on what is being removed. Office furniture and carpet are relatively light. Commercial kitchen equipment is dense stainless steel — heavy. Concrete block interior walls are extremely heavy. Commercial tile floors with thick mortar beds generate serious weight. Strip mall renovations involving multiple material types create unpredictable loads. We recommend weighing on a load-by-load basis for large commercial projects rather than guessing at a blanket weight allocation.",
    bestPractices: "Coordinate dumpster placement with building management or your landlord. Place containers at loading docks or service entrances — never at main customer-facing entrances. Schedule deliveries and pickups during off-hours if the business or neighboring tenants are still operating. Separate recyclable materials like cardboard, metal, and clean wood from general waste to reduce disposal costs. Keep fire lanes and emergency exits clear. Document placement with photos in case of any disputes with property management.",
    whyUs: "We handle commercial accounts with the professionalism your business expects. Consolidated monthly invoicing organized by location or project. Dedicated account management with a single point of contact. Priority scheduling that respects your construction timeline and business operations. Insurance certificates provided on request. We understand that commercial projects have stakeholders, deadlines, and budgets that residential projects do not — and we manage our service accordingly.",
  },
  "roofing-dumpster-rental": {
    projectDescription: "Roofing projects are the single most common dumpster rental job in Florida. The state's heat, humidity, UV exposure, and hurricane seasons destroy roofs faster than anywhere else in the country. A typical roof tear-off generates thousands of pounds of old shingles, felt paper, flashing, nails, and sometimes rotted plywood decking. Shingles are deceptively heavy — a single square (100 sq ft) of architectural shingles weighs 350-500 lbs. A standard Florida home with 25 squares of roofing produces 8,000-12,500 lbs of shingles alone before you count the underlayment and accessories. Having the right dumpster positioned directly below the roof line lets crews throw shingles straight off the roof into the container, dramatically increasing tear-off speed.",
    sizingGuide: "Most residential roof tear-offs need a 20 yard dumpster. A 20 yard holds approximately 20-25 squares of single-layer asphalt shingles within the weight limit. For larger homes (over 2,500 sq ft), multi-layer tear-offs, or homes with tile roofing, step up to a 30 yard or order two 20 yards. For small repair jobs, garage roofs, or shed tear-offs, a 10 yard works. The critical factor for roofing is weight, not volume — shingles are dense and heavy. Tell us your roof square footage and number of layers and we will recommend the exact right setup.",
    weightTips: "Roofing shingles are one of the heaviest common materials that go in dumpsters. Standard 3-tab shingles weigh 200-250 lbs per square. Architectural (dimensional) shingles weigh 350-500 lbs per square. Tile roofing is even heavier at 900-1,200 lbs per square. Our standard weight limits are 2 tons (10 yard), 3 tons (20 yard), and 4 tons (30 yard). For a 25-square architectural shingle roof, you are looking at 8,750-12,500 lbs of shingles — a 20 yard at 3 tons (6,000 lbs) might not be enough. This is why we size roofing dumpsters by weight first, volume second.",
    bestPractices: "Position the dumpster directly adjacent to the house, under the section of roof being torn off. Roofers will toss shingles directly off the roof into the container — this is the fastest and safest method. Make sure the dumpster is not under overhead power lines. Place plywood or boards under the dumpster to protect the driveway from the concentrated weight. If the tear-off is multi-day, cover the dumpster overnight with a tarp to prevent rain from adding water weight. For shingle-only loads, let us know — some recycling facilities accept shingles at lower tipping fees.",
    whyUs: "We have handled thousands of roofing dumpster jobs across Florida. Our drivers know exactly how to position a dumpster for optimal roof-to-container tossing distance. We stock heavier-duty containers for roofing projects and set appropriate weight limits upfront. For roofing contractors, our contractor accounts include volume pricing, priority scheduling during peak season, and same-day swap service when a container fills up mid-job.",
  },
  "demolition-dumpster-rental": {
    projectDescription: "Demolition projects produce the widest variety and largest volume of debris of any project type. Interior demolition generates drywall, framing lumber, flooring, cabinetry, fixtures, insulation, and sometimes hazardous materials like asbestos or lead paint. Exterior demolition adds siding, stucco, roofing, concrete foundations, and structural elements. Full structure demolition creates an enormous volume of mixed materials that requires heavy equipment and multiple dumpster loads. Partial demolition — gutting specific rooms, removing additions, or stripping a building to the shell — is more common in residential settings and still generates significant waste. Every demo project needs a dumpster on site before the first swing of the sledgehammer.",
    sizingGuide: "Demolition almost always requires a 20 or 30 yard dumpster. Interior demo of a single room fits in a 20 yard. A full interior gut of a house — walls, floors, ceilings, everything — needs a 30 yard and often requires multiple loads. Exterior demo (siding, stucco, decks, fences) varies widely by material and square footage but generally starts at 20 yards. For full structure demolition, plan on multiple 30 yard rotations. We work with your demo crew to schedule swaps so full containers get replaced with empties without stopping work.",
    weightTips: "Demolition debris varies enormously in weight. Drywall runs 500-700 lbs per cubic yard. Concrete and masonry hit 2,000-2,500 lbs per cubic yard. Lumber is 300-500 lbs per cubic yard. Stucco with wire lath comes in at 800-1,000 lbs per cubic yard. A mixed demo load can be unpredictable — concrete footings hidden in a wall, heavy tile under carpet, steel beams behind drywall. For demo projects, we recommend telling us exactly what the structure is made of so we can set the right weight expectations.",
    bestPractices: "Demo in order: soft strip first (fixtures, cabinets, trim, appliances), then walls, then floors, then ceilings. This sequence maximizes efficiency and makes loading the dumpster logical — heavy floor materials go in first, lighter wall materials on top. Separate hazardous materials before demo begins. Test for asbestos and lead paint in any Florida building constructed before 1980. Keep a clear debris path from the demo zone to the dumpster. Break large pieces into manageable sizes before loading.",
    whyUs: "We understand demolition pace and can match dumpster service to it. When your demo crew fills a 30 yard in a day, we have an empty one there within hours. Our rotation scheduling for multi-day demo projects is seamless — your crew never waits for a container. We also provide weight tracking across multiple loads so you can manage your demolition budget accurately.",
  },
  "renovation-dumpster-rental": {
    projectDescription: "Renovation projects span the entire spectrum from cosmetic updates to full gut-and-rebuild transformations. Kitchen remodels that strip cabinets, countertops, flooring, and backsplash. Bathroom renovations tearing out tile, tubs, vanities, and fixtures. Whole-house renovations that touch every room over weeks or months. Basement finishing that removes old materials before new construction. Florida's housing stock — much of it built in the 1970s through 1990s — is in constant renovation cycle as homes age and styles change. Every renovation generates a mix of demolition debris from what is being removed and construction waste from what is being installed. A dumpster handles both phases seamlessly.",
    sizingGuide: "Renovation sizing depends entirely on scope. A single bathroom remodel fits in a 10 yard. A kitchen renovation typically needs a 20 yard. Multiple rooms or a full house renovation calls for a 20-30 yard with potential rotation. The key question is: how much are you tearing out? A cosmetic refresh (paint, fixtures, hardware) generates almost no dumpster-worthy waste. A full gut to the studs generates cubic yards of drywall, flooring, cabinetry, and fixtures. Describe your renovation scope and we will size it accurately.",
    weightTips: "Renovation debris includes a mix of materials at different weights. Ceramic tile with mortar is heavy — about 8-12 lbs per square foot. Granite countertops run 20-25 lbs per square foot. Drywall is moderate at 1.6 lbs per square foot. Lumber and cabinetry are relatively light. A kitchen renovation with stone countertops and tile flooring produces more weight per cubic yard than a bedroom renovation with drywall and carpet. Account for the heavy items when choosing your dumpster size.",
    bestPractices: "Coordinate your dumpster delivery with the start of demolition, not before. You do not want an empty dumpster sitting in your driveway burning rental days while you wait for your contractor to start. Create a debris path from the renovation area to the dumpster using plastic sheeting to protect floors and walls. Seal off the renovation zone with plastic to contain dust. Schedule the dumpster to stay through the build phase — new construction generates packaging waste, cutoff materials, and protective coverings that need disposal.",
    whyUs: "Renovation projects run on tight timelines and even tighter budgets. Our flat-rate pricing lets you include waste removal as a fixed line item in your renovation budget. Our 7-day standard rental period covers most renovation demo phases with room to spare. For larger renovations that span weeks, our extended rental rates keep costs predictable. We coordinate with your contractor so the dumpster arrives when demo starts and leaves when the project wraps.",
  },
  "junk-removal-dumpster-rental": {
    projectDescription: "Junk removal dumpster rental is for when you have too much stuff and need it gone. Years of accumulated clutter in the garage, attic, basement, or spare bedroom. Inherited property full of someone else's belongings. Hoarding situations that require systematic cleanout. Office or business closures with furniture, equipment, and inventory to dispose of. The common thread: large volumes of mixed items that are not worth keeping, donating, or selling. A dumpster gives you the time and space to sort through everything at your own pace — keep what matters, toss what does not. No rush, no pressure, no scheduling junk removal crews around your availability.",
    sizingGuide: "A 10 yard dumpster handles a single room or garage cleanout. A 20 yard handles a whole-house declutter or estate cleanout. A 30 yard is for extreme accumulation — heavily packed houses, multi-room hoarding situations, or commercial cleanouts with large furniture and equipment. The 20 yard is our most popular junk removal size because it holds enough to make a real difference without being overkill for most residential situations. When in doubt, the 20 yard is the safe bet.",
    weightTips: "Household junk is usually light relative to its volume. Clothing, cardboard, small appliances, toys, books, and general clutter do not weigh much. The items that add weight are large appliances (refrigerators at 200-300 lbs, washing machines at 150-200 lbs), old CRT televisions (100-150 lbs), and exercise equipment (treadmills at 200-350 lbs). Most junk removal loads come in well under the weight limit. You would need an extraordinary amount of heavy items to exceed a 10 yard's 2-ton limit with household junk.",
    bestPractices: "Sort before you toss. Walk through the space and create three zones: keep, donate, and trash. Everything in the trash zone goes in the dumpster. Items in good condition can go to Habitat for Humanity ReStore, Goodwill, or local charities — donating is free disposal and helps your community. For the dumpster: break down furniture when possible, flatten boxes, remove fabric and padding from furniture frames. Load the dumpster strategically — heavy items on the bottom, bulky light items on top.",
    whyUs: "We make junk removal simple for people who have never rented a dumpster. Text us what you need to clean out and we will tell you the right size. We deliver to your driveway, you load on your schedule, and we pick up when you are ready. No strangers in your house, no scheduling headaches, no per-item pricing games. One flat rate, one container, one simple process.",
  },
  "estate-cleanout-dumpster-rental": {
    projectDescription: "Estate cleanouts are one of the most emotionally difficult projects we serve. After a loved one passes, the family faces the overwhelming task of clearing an entire household — decades of accumulated belongings, furniture, clothing, kitchenware, paperwork, and personal items. The physical volume is staggering: the average American home contains over 300,000 items. Sorting through everything while processing grief is exhausting. A dumpster in the driveway makes the physical part manageable. You work room by room, at your own pace, keeping what matters and letting the rest go. No rushed decisions, no pressure to finish in a day, no making dozens of dump runs in your car.",
    sizingGuide: "Most estate cleanouts for a 2-3 bedroom home need a 20 yard dumpster. Smaller homes or apartments typically fit in a 10 yard. Larger homes — especially those where the deceased had accumulated many years of belongings — may need a 30 yard or two 20 yards. The amount of furniture is usually the determining factor. A heavily furnished 3-bedroom home with a full garage and attic can push the limits of a 20 yard. If the home has been lived in for 20+ years without significant decluttering, size up.",
    weightTips: "Estate cleanout debris is mostly household items — furniture, mattresses, clothing, kitchenware, books, and general possessions. This is typically light-to-moderate density material. Old appliances (washer, dryer, refrigerator, stove) add significant individual weight but are only a few items. The main weight concern in estate cleanouts is old magazines, newspapers, and books in large quantities — paper is surprisingly heavy at about 58 lbs per cubic foot. A closet full of National Geographics can weigh over 500 lbs.",
    bestPractices: "Start with the easiest room to build momentum — usually the garage or a spare bedroom. Save the most sentimental rooms for last when you have established a sorting rhythm. Use the four-category method: keep, donate, sell, and trash. Have the dumpster close to the most-used exit door. If multiple family members are participating, assign rooms to avoid duplication and disagreements. Take breaks. This is physically and emotionally demanding work. The dumpster is there for your timeline, not the other way around.",
    whyUs: "We treat estate cleanout customers with extra care because we understand the circumstances. We offer flexible scheduling — if you need to pause for a few days and come back, we extend your rental at a minimal daily rate. We will not rush you. Our pricing is transparent and fixed so you are not worrying about costs while dealing with loss. Many families have told us that having the dumpster there was the single most helpful thing during the cleanout process.",
  },
  "storm-debris-dumpster-rental": {
    projectDescription: "When a hurricane, tropical storm, or severe weather event hits Florida, the aftermath creates urgent demand for dumpster service. Fallen trees and branches, damaged fencing, destroyed screen enclosures, roofing materials torn loose by wind, water-damaged drywall and insulation, ruined flooring and furniture, and general storm debris can fill yards and block driveways. The damage is often extensive and the cleanup is time-sensitive — water intrusion gets worse by the hour, insurance adjusters need access, and the property needs to be secured. Storm debris dumpster rental is about speed: getting a container to your property fast so you can start cleaning up and protecting what is left.",
    sizingGuide: "Storm damage severity determines dumpster size. Minor storm damage (fallen branches, damaged fence sections, a few screen panels) fits in a 10-20 yard. Moderate damage (partial roof damage, flooding in one area, significant tree debris) typically needs a 20-30 yard. Major damage (roof failure, extensive flooding, structural damage) often requires multiple 30 yard containers over several days or weeks as restoration progresses. For hurricane aftermath, demand spikes enormously — booking early or having a pre-existing account gives you priority.",
    weightTips: "Storm debris weight is unpredictable because it is a mix of everything: wet drywall (much heavier than dry), waterlogged furniture, tree trunks and branches, concrete block from damaged walls, roofing materials, and mud-covered everything. Water-saturated materials can weigh 2-3 times their dry weight. A wet mattress can weigh 200+ lbs. Waterlogged drywall and insulation are extremely heavy. Factor in the moisture content when planning your dumpster size — you may need a larger container or accept a weight overage as the cost of fast cleanup.",
    bestPractices: "Document everything before you dispose of it. Photograph all damage and damaged items for your insurance claim. Keep receipts for your dumpster rental — it is typically reimbursable under your homeowner's policy. Prioritize removing items that are actively causing further damage — wet materials that are spreading mold, debris blocking drainage, damaged structural elements exposing the interior. Wear protective equipment: gloves, boots, eye protection. Storm debris often contains nails, broken glass, and contaminated water.",
    whyUs: "After major storms, dumpster inventory sells out fast. We maintain emergency reserves and prioritize existing customers and contractor accounts. Our post-storm protocol is simple: text us your address and damage description, and we get you in the queue immediately. We understand that storm cleanup cannot wait for normal business scheduling. We offer extended hours during major weather events and coordinate with restoration contractors to keep dumpsters moving efficiently through affected areas.",
  },
  "yard-waste-dumpster-rental": {
    projectDescription: "Florida landscaping grows aggressively year-round, and managing yard waste is a never-ending battle. Palm trees drop fronds constantly. Hedges grow inches per week during summer. Hurricane season brings down branches, strips leaves, and scatters debris across entire neighborhoods. Major landscaping overhauls — removing old plantings, clearing overgrown lots, prepping for new sod or hardscaping — generate far more green waste than your weekly yard waste pickup can handle. A yard waste dumpster gives you the capacity to tackle major landscaping projects without making dozens of trips to the green waste facility.",
    sizingGuide: "For routine heavy cleanup — accumulated palm fronds, hedge trimmings, dead plantings — a 10 yard usually works. For major landscape overhauls, tree trimming projects, or post-storm cleanup, a 20 yard handles the volume. For lot clearing or removing extensive mature landscaping, a 30 yard may be needed. Palm fronds are bulky but light — they fill space fast without adding much weight. Dense hedge trimmings and tree branches pack more tightly and add more weight. The volume of yard waste almost always surprises people — plan for more than you think.",
    weightTips: "Green yard waste is relatively light: tree branches at 200-400 lbs per cubic yard, palm fronds even lighter. The weight concern with yard waste is when dirt and sod get involved. Dirt weighs about 2,200 lbs per cubic yard and sod is nearly as heavy. A thin layer of sod removal from a moderate yard can produce tons of material that quickly exceeds weight limits. If your landscaping project involves significant dirt or sod removal, tell us upfront — we will set appropriate weight expectations and may recommend a separate heavy-debris container.",
    bestPractices: "Cut branches into manageable lengths (4-6 feet max) so they lay flat in the dumpster rather than sticking up at angles and wasting space. Break down palm frond boots (the thick base where the frond connects to the trunk) — they take up less space when split. Separate dirt and sod from green waste if possible. Do not put landscape fabric, plastic sheeting, or PVC irrigation pipe in a yard waste dumpster — these are not green waste and change the disposal category. Compact as you load — walking on top of yard waste periodically helps settle it down.",
    whyUs: "We route yard waste loads to green waste recycling facilities when possible, which often have lower tipping fees than standard landfills. This can save you money compared to companies that send everything to the same place regardless of content. We know which Florida disposal facilities accept clean yard waste separately and we optimize routing accordingly.",
  },
  "garage-cleanout-dumpster-rental": {
    projectDescription: "The garage cleanout is America's most popular weekend dumpster project — and in Florida, where garages also serve as storage for hurricane supplies, pool equipment, outdoor furniture, and everything else that does not fit in the house, the accumulation is even worse. Most Florida garages have not seen a car in years. They are packed with broken power tools, deflated sports equipment, holiday decorations from a decade ago, boxes that were never unpacked after the last move, and an impressive collection of things that seemed too good to throw away at the time but have been untouched ever since. A 10 yard dumpster and one motivated weekend is all it takes to reclaim your garage.",
    sizingGuide: "A standard two-car garage cleanout fits in a 10 yard dumpster about 90% of the time. That is 4 pickup truck loads of space, which handles the typical accumulation of a garage that has been collecting stuff for 5-10 years. If your garage is packed floor to ceiling with no visible floor space, or if you are also cleaning out the shed, attic, or additional storage areas, step up to a 20 yard. The 10 yard is our most affordable option and fits perfectly in any driveway without blocking the entire thing.",
    weightTips: "Garage cleanout debris is typically light. Cardboard boxes, plastic storage bins, old clothing, sports equipment, small tools, and general household items do not weigh much individually or collectively. The items that add weight: old riding mowers (300-500 lbs), weight sets and exercise equipment (200-500 lbs), bags of concrete or sand that have been sitting in the corner for years (60-80 lbs each), and old CRT televisions or monitors (100-150 lbs each). Even with these heavy items included, most garage cleanouts come in well under the 10 yard's 2-ton weight limit.",
    bestPractices: "The two-pass method works best. First pass: walk through and pull out everything that is obviously trash — broken items, damaged boxes, things you forgot existed. Toss it all in the dumpster without overthinking it. Second pass: sort what remains into keep, donate, and sell categories. You will be amazed how much floor space appears after pass one. The Friday-to-Monday rental is perfect for garage cleanouts: dumpster arrives Friday, you clean Saturday, organize Sunday, we pick up Monday.",
    whyUs: "Garage cleanouts are our bread and butter residential project. We have helped thousands of Florida homeowners reclaim their garages. Our 10 yard dumpster is sized perfectly for this project and priced to make the decision easy. We deliver Friday, you have the entire weekend to work at your own pace, and we pick up Monday. The total investment is one flat-rate rental and a weekend of effort. The return is a garage you can actually park in.",
  },
  "foreclosure-cleanout-dumpster-rental": {
    projectDescription: "Foreclosed and abandoned properties in Florida present unique cleanout challenges. Former occupants leave behind furniture, clothing, trash, and sometimes deliberate damage. Squatters add their own debris. Water damage from neglected leaks creates mold and structural deterioration. Yards become overgrown jungles. Pools turn into mosquito breeding grounds. Banks, asset managers, and investors need these properties cleaned out fast to protect their investment, satisfy code enforcement, and prepare for resale or renovation. A dumpster on site is step one of every foreclosure rehab — you cannot assess or repair a property until you clear out what is inside.",
    sizingGuide: "Foreclosure cleanout sizing depends on the property condition. A well-maintained home where the previous owner simply left furniture and personal items might fit in a 10-15 yard. A neglected property with heavy accumulation, squatter debris, and damage-related removal (moldy drywall, damaged flooring) typically needs a 20 yard. Severely neglected properties — hoarding situations, extensive vandalism, or properties vacant for years — often require a 30 yard or multiple loads. When possible, walk the property before ordering to gauge the volume.",
    weightTips: "Foreclosure cleanout weight varies enormously by property condition. A clean-out of furniture and personal items is relatively light. Add in waterlogged materials from roof leaks or flooding and the weight increases significantly. Damaged drywall, tile flooring, and appliances add serious weight. The wildcard in foreclosure cleanouts is hidden weight — closets packed with heavy items, water-saturated subfloors, concrete block walls that need removal. We recommend describing the property condition in detail so we can set realistic weight expectations.",
    bestPractices: "Before tossing anything, know Florida's abandoned property laws. After a lease termination or foreclosure, the property owner must provide the required notice period before disposing of personal property left behind. Document everything with photos before disposal for legal protection. Wear protective equipment — foreclosed properties often contain mold, animal waste, needles, and other hazards. Start with obviously trash items first, then assess what remains. Have the dumpster positioned at the most accessible door to minimize carry distance.",
    whyUs: "We work with banks, asset management companies, REO specialists, and real estate investors across Florida. We provide the documentation these clients need: itemized invoices, before-and-after photos, disposal certificates, and scale tickets. Our turnaround time meets the aggressive timelines that bank-owned property dispositions require. For investors doing multiple cleanouts per month, our volume pricing and dedicated account management streamline the entire process.",
  },
  "moving-dumpster-rental": {
    projectDescription: "Moving is the perfect trigger for a dumpster rental because it forces the question you have been avoiding: do you really want to pack, load, transport, and unload all of this stuff? The answer, for most families, is no. Moving companies charge by weight and volume — every box you pack costs money to move. A pre-move dumpster rental lets you aggressively declutter before packing begins, reducing your moving costs, your packing time, and the chaos of moving day. Rent a dumpster 1-2 weeks before your move date, go room by room, and purge everything you do not need at your new home. The investment in a dumpster rental pays for itself in reduced moving costs.",
    sizingGuide: "For a 2-3 bedroom home pre-move declutter, a 10 yard dumpster handles the purge for most families. If you have been in your home for 10+ years without a major declutter, or if you are downsizing to a smaller home and need to let go of more, a 20 yard gives breathing room. The items that take up the most space in a pre-move dumpster: old furniture you are replacing, broken or outdated appliances you are not bringing, boxes of stuff from the garage or attic that you have not opened in years, and outgrown kids' items.",
    weightTips: "Pre-move declutter debris is similar to junk removal — mostly household items that are light relative to volume. Furniture frames, clothing, linens, books, toys, kitchen items, and general household clutter. The heavier items are old appliances and exercise equipment. Most pre-move dumpster loads come in well under the weight limit. Your bigger concern is volume — fitting everything in — rather than weight.",
    bestPractices: "Start the declutter at least 2 weeks before your move date. Go room by room starting with the least-used spaces (guest room, basement, attic, garage). For every item, ask: would I buy this again at my new home? If the answer is no, it goes in the dumpster or donation pile. Schedule the dumpster to overlap with your packing timeline — as you pack each room, you will find more items to toss. Have the dumpster picked up 1-2 days before the movers arrive so the driveway is clear for the moving truck.",
    whyUs: "We know the moving timeline is stressful, so we make the dumpster part effortless. Book with one text, get instant confirmation, and we deliver on your schedule. Our 7-day rental period aligns perfectly with a 1-2 week pre-move declutter. If your move date shifts (as they often do), we adjust the dumpster schedule at no extra charge. Many of our customers tell us the pre-move dumpster was the best money they spent on the entire move.",
  },
  "concrete-dumpster-rental": {
    projectDescription: "Concrete disposal is one of the most specialized dumpster rental categories because concrete is extraordinarily heavy. A single cubic yard of concrete weighs approximately 4,000 lbs — two tons. A standard 10 yard dumpster filled with concrete would weigh 20 tons, far exceeding its 2-ton weight limit. This means concrete disposal requires different sizing strategies than other materials. Whether you are removing a concrete patio, demolishing a driveway, tearing out a pool deck, breaking up a foundation, or disposing of concrete block walls, the weight-first approach to sizing is essential. We handle concrete disposal projects throughout Florida with containers and weight limits specifically configured for this dense material.",
    sizingGuide: "For concrete disposal, ignore the volume and focus on weight. A 10 yard dumpster with a 2-ton weight limit holds about half a cubic yard of solid concrete — that is roughly a 4x4 foot section of a 6-inch slab. A 20 yard with 3 tons holds about three-quarters of a cubic yard. A 30 yard with 4 tons holds about one cubic yard. For large concrete removal projects (driveways, pool decks, foundations), you will need multiple loads regardless of container size. We can set up rotation schedules so full containers get swapped for empties as your project progresses.",
    weightTips: "Concrete weighs approximately 150 lbs per cubic foot or 4,050 lbs per cubic yard. Concrete block weighs slightly less at about 3,000-3,500 lbs per cubic yard. Rebar-reinforced concrete adds to the weight and complicates disposal. Asphalt weighs about 3,600 lbs per cubic yard. When calculating your project's weight, measure the area and depth of concrete being removed, then multiply by the weight per cubic foot. A 20x20 foot patio that is 4 inches thick contains about 5 cubic yards of concrete weighing approximately 20,000 lbs — that is 10 tons requiring multiple dumpster loads.",
    bestPractices: "Break concrete into manageable pieces before loading — chunks under 100 lbs are ideal. Do not mix concrete with other debris types. Clean concrete (no rebar, no other materials mixed in) can often go to concrete recycling facilities at lower tipping fees than landfills. Concrete with rebar is accepted but costs more to process. Do not stack concrete above the fill line — even if the dumpster looks half empty, it may already be at the weight limit. Load concrete evenly across the floor of the container rather than piling it in one spot.",
    whyUs: "We handle concrete disposal differently because it requires different logistics. We configure weight limits specifically for concrete loads. We route clean concrete to recycling facilities when possible to save you money. We provide accurate weight estimates based on your project dimensions so you know exactly how many loads to expect. No surprises, no guesswork, just honest heavy-material disposal expertise.",
  },
  "appliance-removal-dumpster-rental": {
    projectDescription: "Appliance disposal in Florida is complicated by one factor: refrigerants. Refrigerators, freezers, air conditioners, dehumidifiers, and heat pumps contain refrigerant gases that must be professionally recovered before the appliance can be disposed of in a dumpster or landfill. Simply tossing a refrigerator in a dumpster without refrigerant removal is a federal violation of the Clean Air Act. Beyond the refrigerant issue, old appliances are simply heavy and awkward — a standard refrigerator weighs 200-350 lbs, a washer 150-200 lbs, a dryer 100-150 lbs, a stove 130-200 lbs, and a dishwasher 75-125 lbs. When you are replacing multiple appliances during a renovation, the combined weight and bulk makes dumpster rental the smart choice.",
    sizingGuide: "For appliance-only disposal (no other debris), a 10 yard dumpster holds 8-12 major appliances depending on size and type. For appliance disposal combined with a renovation or cleanout project, size the dumpster for the overall project and add the appliance weight to your calculations. Most appliance removal is part of a larger project — kitchen or laundry room renovations, estate cleanouts, or property management unit turns — where the dumpster is already on site for other debris.",
    weightTips: "Appliances are heavy individually but manageable in the context of a normal dumpster load. A full set of kitchen appliances (refrigerator, stove, dishwasher, microwave) weighs about 600-800 lbs total. A washer-dryer set adds another 250-350 lbs. Even with a full set of appliances, you are well under the 2-ton limit on a 10 yard dumpster. The weight concern is when appliance disposal is combined with heavy renovation debris like tile or countertops.",
    bestPractices: "Remove refrigerant from any appliance that contains it before placing in the dumpster — this includes refrigerators, freezers, window AC units, and dehumidifiers. Most HVAC companies and appliance stores can perform refrigerant recovery. Remove doors from refrigerators and freezers as a safety precaution. Disconnect and cap any gas lines before moving gas appliances. Use a hand truck or appliance dolly to move heavy items — do not try to lift a refrigerator into a dumpster manually. Use the rear swing door for walk-in loading of heavy appliances.",
    whyUs: "We can coordinate refrigerant recovery for appliances that need it, saving you the hassle of finding a certified technician. For renovation projects where appliance removal is part of a larger job, we include the appliances in our overall sizing recommendation so nothing gets overlooked. For property managers replacing appliances across multiple units, we handle the logistics at scale.",
  },
  "pool-demolition-dumpster-rental": {
    projectDescription: "Pool demolition is one of the largest residential dumpster projects in Florida. Removing an inground pool means breaking up thousands of pounds of concrete, gunite, or fiberglass shell, plus tile, coping, decking, plumbing, and equipment. A standard residential pool (15x30 feet) contains 25-40 cubic yards of shell material weighing 50-100 tons. This is not a DIY project — pool demolition requires heavy equipment (excavators, concrete crushers) and experienced operators. But it absolutely requires dumpster service, and lots of it. Full pool removal generates more debris than almost any other residential project.",
    sizingGuide: "Pool demolition is a multi-dumpster project by definition. A standard residential pool requires 4-8 full 30 yard dumpster loads for a complete removal, or 2-4 loads for a partial fill-in (where the top portion of the shell is broken and the rest is filled with rubble). We set up rotation schedules with your demolition contractor: while one container is being hauled and dumped, your crew loads the next one. Continuous rotation prevents downtime on the demo.",
    weightTips: "Pool shell material is extremely heavy. Concrete and gunite weigh about 4,000 lbs per cubic yard. A standard pool shell contains 25-40 cubic yards of material weighing 50-80 tons total. Each 30 yard dumpster load is limited to 4 tons (8,000 lbs), meaning you fill far less than the full volume before hitting the weight limit. For pool demo, containers are typically loaded to about one-quarter volume before reaching the weight ceiling. This is normal for heavy material disposal.",
    bestPractices: "Coordinate closely with your pool demolition contractor on dumpster timing. The dumpster should arrive before the excavator — not the other way around. Position containers where the excavator can load directly without moving material twice. Separate pool equipment (pumps, filters, heaters) from concrete debris — equipment is lighter and may have scrap value. Tile and coping can go in with the concrete. Keep the work area organized: material flows from the pool excavation to the container to the truck.",
    whyUs: "We have worked with pool demolition contractors across Florida and understand the pace and logistics of these projects. Our rotation scheduling ensures your excavator crew never waits for a container. We provide weight tracking across all loads so you can manage your demolition budget. For pool demo, we typically recommend discussing the project scope upfront so we can provide a per-load rate that covers the full removal rather than pricing each container individually.",
  },
  "landscaping-dumpster-rental": {
    projectDescription: "Landscaping projects in Florida generate an enormous amount of green waste and mixed debris. The state's aggressive growing season means landscaping never stops — hedges that grow a foot per month, palm trees that drop fronds year-round, and ground cover that spreads faster than you can contain it. Major landscaping overhauls involve removing existing plantings, clearing overgrown areas, pulling up old sod, removing landscape timbers and edging, demolishing old hardscaping (patios, walkways, retaining walls), and hauling away all of it before new installations begin. A dumpster on site during a landscaping project means crews can work continuously without stopping for dump runs.",
    sizingGuide: "For routine heavy landscaping cleanup (accumulated fronds, hedge trimmings, dead plants), a 10-20 yard handles the volume. For major landscape overhauls with plant removal, a 20 yard is standard. For lot clearing with extensive vegetation, tree removal, and hardscape demolition, a 30 yard may be necessary. The biggest variable is whether dirt and sod are involved — these are extremely heavy materials that can fill weight limits fast with minimal volume. If your project involves significant dirt or sod removal, tell us upfront.",
    weightTips: "Green waste (branches, fronds, trimmings) is relatively light at 200-400 lbs per cubic yard. But the moment dirt enters the picture, weight becomes critical. Topsoil weighs about 2,200 lbs per cubic yard. Sod weighs similarly. Sand weighs about 2,700 lbs per cubic yard. A thin layer of sod removal from a quarter-acre lot can produce 5+ tons of material. Landscape rock and pavers are also heavy. Separate heavy materials from green waste when possible — different disposal routing can save significant money.",
    bestPractices: "Have the dumpster delivered before landscaping crews arrive. Position it near the work area to minimize wheelbarrow distance. Separate green waste from hardscape materials when possible — many disposal facilities offer lower rates for clean green waste. Cut branches to 4-6 foot lengths for efficient packing. Break down palm frond boots. Do not put landscape plastic, irrigation PVC, or other non-organic materials in a yard waste load — these contaminate the green waste stream.",
    whyUs: "We understand the difference between green waste, clean fill, mixed debris, and heavy materials — and we route each to the most cost-effective disposal facility. Many landscaping companies overpay for disposal because their dumpster provider treats everything the same. We do not. Tell us what you are disposing of and we will find the cheapest legitimate disposal option available.",
  },
  "hoa-community-dumpster-rental": {
    projectDescription: "HOA and community association dumpster rental serves a unique client: the governing board that manages shared property on behalf of hundreds or thousands of residents. Community-wide cleanups, bulk trash collection events, common area renovations, pool facility remodeling, clubhouse updates, parking lot resurfacing, landscape overhauls, and storm debris cleanup all require dumpster service at a scale that serves the entire community. HOA dumpster rental also includes individual unit owners within the community who need dumpsters for personal renovations — and who must navigate HOA rules about dumpster placement, duration, and screening requirements.",
    sizingGuide: "Community-wide cleanup events typically need multiple 30 yard dumpsters placed in accessible locations (near mailbox clusters, at the community entrance, or in common parking areas). Common area renovation projects are sized like any commercial renovation based on scope. Individual homeowner projects within HOA communities usually need a 10-20 yard dumpster on the homeowner's driveway. For recurring community needs (quarterly bulk cleanups, ongoing renovation support), we set up scheduled service agreements.",
    weightTips: "Community cleanup events produce mixed household items that are generally light. Renovation projects follow standard weight guidelines based on materials. The unique weight consideration for HOA communities is pool facility renovation — pool deck concrete, tile, and equipment are heavy materials that need appropriate weight planning. Common area landscape renovation with large tree removal or soil grading can also produce heavy loads.",
    bestPractices: "Coordinate dumpster placement with HOA management and get written approval before scheduling delivery. Most HOAs restrict dumpsters to driveways only, limit rental periods to 7-14 days, and require advance notice to the association. Some communities require screening or fencing around dumpsters. For community-wide cleanup events, communicate the dumpster locations and rules to residents in advance. Have a monitor on site during community cleanup days to ensure prohibited items do not get dumped.",
    whyUs: "We work with HOA management companies and community associations across Florida. We understand the politics and logistics of serving communities: we bill the association directly, provide itemized invoicing by project or event, coordinate multiple container placements within the community, and work within the specific rules each association has about dumpster placement and duration. Our dedicated account management means one phone call handles everything.",
  },
  "diy-project-dumpster-rental": {
    projectDescription: "DIY projects are surging in popularity as homeowners take on renovations, upgrades, and repairs themselves. YouTube tutorials, home improvement shows, and the satisfaction of doing it yourself drive millions of homeowners to tackle projects that used to be contractor-only territory. But every DIY project generates waste — from the small (paint cans, packaging, old hardware) to the significant (demolished walls, ripped-out flooring, old fixtures, and removed cabinetry). A dumpster rental gives DIY homeowners the same waste management capability that professional contractors have, turning your home into a proper job site where debris goes in a container instead of piling up in the yard.",
    sizingGuide: "DIY project sizing is highly variable because DIY covers everything from weekend shelf installation to multi-room renovation. Small projects (one room, cosmetic changes): no dumpster needed. Medium projects (bathroom remodel, flooring replacement, deck removal): 10 yard dumpster. Large projects (kitchen gut, multiple rooms, garage conversion): 20 yard dumpster. Major projects (whole-house renovation, addition, extensive demolition): 20-30 yard dumpster. The 10 yard is the sweet spot for most DIY projects — it is affordable, fits in any driveway, and holds enough for the typical weekend warrior project.",
    weightTips: "DIY project weight depends entirely on what you are tearing out. Light materials: drywall, carpet, vinyl flooring, wood paneling, drop ceiling tiles. Medium materials: hardwood flooring, plywood subflooring, lumber framing. Heavy materials: ceramic tile, concrete backer board, stone or brick, concrete. Most DIY projects involve a mix. A single-bathroom renovation produces about 500-1,000 lbs of debris. A kitchen demo can produce 1,500-3,000 lbs. These are well within the weight limits for a 10-20 yard dumpster.",
    bestPractices: "Plan your waste disposal before you start demo. Having the dumpster on site from day one means debris goes directly from the demo area to the container instead of piling up in your garage or yard. Watch YouTube for demo technique — proper demolition order saves time and effort. Wear safety gear (dust mask, safety glasses, gloves, boots). Turn off utilities to the work area before starting. Keep the dumpster covered during rain. And remember: it always takes longer than the YouTube video suggests. Rent the dumpster for the full 7 days even if you think you will finish in a weekend.",
    whyUs: "We love serving DIY homeowners because we were probably in your shoes once. We know you might not know exactly what size you need or what questions to ask — and that is perfectly fine. Text us what you are planning and we will walk you through it. No contractor jargon, no condescending attitudes, just straightforward advice from people who handle waste removal every day. Our flat-rate pricing means no budget surprises, and our 7-day rental gives you the flexibility that DIY timelines actually require.",
  },
  "office-cleanout-dumpster-rental": {
    projectDescription: "Office cleanouts happen during relocations, closures, renovations, and the periodic purge of accumulated equipment, furniture, and files. Modern offices generate surprising amounts of waste: cubicle systems, modular desks, filing cabinets full of paper, outdated electronics, office chairs, conference tables, break room appliances, and the miscellaneous accumulation of years of business operations. Commercial leases often require spaces to be returned in broom-clean condition, meaning everything must be removed — not just moved to another corner. A dumpster at the loading dock or service entrance gives your cleanout crew immediate disposal capacity.",
    sizingGuide: "Small office (under 2,000 sq ft) cleanouts typically fit in a 10-20 yard dumpster. Medium offices (2,000-5,000 sq ft) usually need a 20-30 yard. Large offices or full-floor cleanouts in commercial buildings need 30 yard containers with rotation scheduling. The density of furnishing matters — a fully furnished office with cubicle systems, filing cabinets, and break room equipment produces far more debris than a sparsely furnished space. If the cleanout includes demolition of partition walls or flooring removal, size up accordingly.",
    weightTips: "Office furniture is moderately heavy: cubicle panels (50-100 lbs each), metal filing cabinets (100-200 lbs each), solid wood desks (100-250 lbs each), office chairs (25-50 lbs each). Paper is surprisingly heavy at about 58 lbs per cubic foot — a full 4-drawer filing cabinet of paper weighs about 200 lbs. Metal components (filing cabinets, desk frames, shelving) have scrap value — consider separating them. Electronics are generally light except for older CRT monitors and large copiers/printers.",
    bestPractices: "Coordinate with building management on dumpster placement and loading dock access. Schedule deliveries and pickups during off-hours if the building is still occupied by other tenants. Separate recyclable materials: paper and cardboard go to recycling, metal furniture has scrap value, and electronics should go to e-waste recyclers. Shred or destroy confidential documents before disposal — never put readable business documents in an open dumpster. Remove batteries from any electronic devices. Check if your commercial lease has specific move-out or disposal requirements.",
    whyUs: "We handle commercial cleanouts with the professionalism and documentation that business clients expect. We coordinate with building management on scheduling and access. We provide itemized invoicing for your records. We can handle after-hours delivery and pickup to avoid disrupting building operations. For companies closing or relocating, we offer rapid turnaround — full cleanout capacity when your timeline demands it.",
  },
  "disaster-restoration-dumpster-rental": {
    projectDescription: "Disaster restoration is the professional process of repairing and rebuilding after catastrophic events — hurricanes, floods, fires, tornadoes, and other disasters that cause structural damage to buildings. Restoration is distinct from cleanup: it involves systematic demolition of damaged materials, environmental remediation (mold, smoke, water damage), structural repair, and full rebuilding. Restoration contractors work under strict insurance company protocols and need waste management that matches their pace and documentation requirements. A restoration job might generate water-damaged drywall, contaminated insulation, burned structural members, smoke-damaged finishes, mold-infested materials, and flood-ruined contents — all of which require proper disposal.",
    sizingGuide: "Disaster restoration dumpster sizing depends on the extent of damage and the building size. Minor water damage (one room, partial drywall removal) fits in a 10 yard. Moderate damage (multiple rooms, flooring removal, extensive drywall gutting) needs a 20 yard. Major damage (structural repair, full-floor demolition, fire restoration) typically requires 30 yard containers with rotation. Large commercial restoration projects may run multiple containers simultaneously for weeks or months.",
    weightTips: "Disaster-damaged materials are often waterlogged and significantly heavier than their dry weight. Wet drywall weighs 2-3 times its normal weight. Waterlogged carpet and padding can be extremely heavy. Burned materials are generally lighter (fire consumes mass) but structurally compromised and difficult to handle. Flood debris mixed with mud and sediment adds unpredictable weight. For restoration projects, we recommend load-by-load weight tracking rather than upfront weight estimates because the actual weight depends on moisture content that changes daily.",
    bestPractices: "Follow your restoration contractor's demolition plan — they have specific protocols for removing contaminated materials safely. Contain potentially contaminated debris (mold, asbestos, lead, smoke residue) according to environmental regulations. Document all disposed materials with photos for insurance claims. Keep dumpster rental receipts — they are reimbursable restoration expenses under most insurance policies. Separate materials when required by environmental regulations — some contaminated materials may need special disposal facilities.",
    whyUs: "We work with restoration contractors daily and understand the insurance and documentation requirements. We provide load tickets, weight receipts, and disposal facility documentation for every load — everything your insurance adjuster needs. Our priority scheduling ensures restoration crews are never waiting for a container. We maintain communication with your project manager so dumpster swaps happen without disrupting the restoration timeline.",
  },
  "warehouse-cleanout-dumpster-rental": {
    projectDescription: "Warehouse cleanouts are industrial-scale waste removal projects that dwarf residential and most commercial jobs. When businesses close, relocate, or restructure, they leave behind thousands of square feet of inventory, racking, pallets, packaging materials, office equipment, and accumulated debris. A 10,000 sq ft warehouse stacked with items to head height can require 100+ cubic yards of dumpster capacity — that is 4-5 full 30 yard containers. The logistics of warehouse cleanouts are different from residential: loading dock access, forklift coordination, multiple simultaneous containers, and the physical demands of clearing massive volumes of material in compressed timelines.",
    sizingGuide: "Warehouse cleanouts almost always require 30 yard dumpsters and often require multiple containers simultaneously. The standard approach is two 30 yard dumpsters on site at all times: while your crew fills one, we haul and dump the other. This eliminates downtime — your crew is never waiting for an empty container. For very large warehouses (20,000+ sq ft) or heavily packed spaces, three containers on rotation may be necessary. Most warehouse cleanouts run 3-10 business days depending on volume and crew size.",
    weightTips: "Warehouse contents vary enormously in density. Cardboard boxes and packaging materials are very light. Racking systems (steel) are very heavy — a standard pallet rack section weighs 200-400 lbs. Industrial equipment, machinery, and metal fabrication materials can be extremely dense. Pallets in large quantities add up (a standard wood pallet weighs 30-70 lbs). For mixed warehouse contents, weight is generally moderate — the volume fills up before the weight limit. For metal-heavy warehouses, weight management becomes critical.",
    bestPractices: "Walk the warehouse before ordering to estimate volume. Separate valuable recyclables: cardboard (baled cardboard has value), pallets (pallet recyclers will pick up and pay), metal racking (significant scrap value), and clean plastics. The scrap and recycling value from a large warehouse cleanout can offset a meaningful portion of your dumpster costs. Use forklifts to stage material near the loading dock before loading the dumpster. Load dumpsters at the dock level for ergonomic efficiency.",
    whyUs: "We handle warehouse-scale operations with the logistics management they require. Multi-container rotation scheduling, loading dock delivery coordination, and rapid turnaround on full containers. For large cleanouts, we assign a dedicated logistics coordinator to manage the dumpster flow. We also have relationships with recycling facilities, scrap yards, and specialty disposal sites that can handle the variety of materials found in warehouse cleanouts.",
  },
  "rental-property-dumpster-rental": {
    projectDescription: "Rental property dumpster service covers the ongoing waste management needs of landlords, property managers, and real estate investors who manage single-family homes, duplexes, small multifamily buildings, and vacation rentals. Tenant turnovers generate cleanout debris. Between-tenant renovations update worn kitchenware, flooring, paint, and fixtures. Problem tenants leave behind damage that requires demolition and repair. Eviction cleanouts need to happen fast to minimize vacancy loss. Seasonal vacation rental refreshes keep properties competitive. The common need: reliable, affordable dumpster service on a recurring basis for an operator managing multiple properties.",
    sizingGuide: "Tenant turnover cleanout (furniture and trash left behind): 10 yard for a 1-2 bedroom, 20 yard for a 3+ bedroom or heavily accumulated unit. Between-tenant renovation (flooring, paint, fixture updates): 10 yard for cosmetic refresh, 20 yard for full renovation. Eviction cleanout with damage: 20 yard to cover both cleanout debris and damaged materials. For property managers doing multiple turnovers per month, our recurring service agreements provide the most cost-effective solution.",
    weightTips: "Rental property debris is typically household items and light renovation materials — furniture, carpet, appliances, drywall patches, flooring. Weight is rarely a concern for turnover cleanouts. Renovation projects follow standard weight guidelines. The main cost consideration for rental property operators is efficiency: minimizing vacancy days by having the dumpster arrive immediately after the old tenant leaves and getting it picked up before the new tenant moves in.",
    bestPractices: "Schedule the dumpster for the day after tenant move-out. Have your maintenance crew start the cleanout immediately. Sort salvageable items (working appliances, undamaged furniture) for use in other properties or donation. Document the condition of the unit with photos before and after cleanout for security deposit accounting. For eviction cleanouts, follow Florida's abandoned property notice requirements before disposing of personal belongings.",
    whyUs: "We offer property manager accounts with the features landlords need: volume pricing across multiple properties, priority scheduling for fast turnover, NET-30 billing with invoices organized by property address, and one-text ordering. Our property manager clients average 5-20 dumpster rentals per year, and the consistency of working with one reliable provider saves them hours of coordination time compared to shopping each rental individually.",
  },
  "flooring-removal-dumpster-rental": {
    projectDescription: "Flooring removal generates more weight per square foot than most homeowners expect. Ceramic tile with its mortar bed weighs 8-12 lbs per square foot. Hardwood flooring with plywood subfloor weighs 3-5 lbs per square foot. Even carpet with padding weighs about 1-2 lbs per square foot. A 1,500 sq ft home with ceramic tile throughout produces 12,000-18,000 lbs of flooring debris — that is 6-9 tons. The removal process is labor-intensive: prying up tile, chipping mortar, pulling up tack strips, removing underlayment, and hauling everything out. Having a dumpster in the driveway means removed flooring goes directly from the room to the container without staging, storing, or making dump runs.",
    sizingGuide: "Flooring removal sizing depends on the material and square footage. Carpet removal from a whole house (1,500 sq ft) fits in a 10 yard dumpster easily — carpet is bulky but light. Vinyl and laminate flooring removal is similar. Ceramic tile removal from a whole house needs a 20-30 yard due to weight. Hardwood flooring removal falls in between. For a single room (kitchen or bathroom), a 10 yard handles any flooring type. For whole-house tile removal, the 30 yard with its 4-ton weight limit is often necessary just for the weight capacity.",
    weightTips: "Tile is the heavy one. Ceramic tile with thin-set mortar weighs about 8 lbs per square foot. With a thick mortar bed (common in older Florida homes), it can reach 12 lbs per square foot. A 200 sq ft kitchen floor in tile produces 1,600-2,400 lbs. A whole house at 1,500 sq ft produces 12,000-18,000 lbs. Contrast this with carpet at 1-2 lbs per square foot — the same 1,500 sq ft house produces only 1,500-3,000 lbs of carpet. Know your flooring material before sizing your dumpster.",
    bestPractices: "Remove furniture and clear the room completely before starting removal. For tile, start at a doorway or edge where you can get under the first tile. Use a floor scraper for large areas and a hammer and chisel for stubborn spots. For carpet, cut it into manageable strips (4-6 feet wide) for easier handling and loading. Roll carpet strips for compact loading. Remove tack strips with a pry bar after carpet is out. For all flooring types: wear knee pads, dust mask, and safety glasses. Load heavy tile debris from the bottom of the dumpster up.",
    whyUs: "We size flooring removal dumpsters by weight, not just volume, because tile and stone flooring can exceed weight limits long before filling the container. When you tell us your flooring type and square footage, we calculate the actual weight and recommend a container that handles both the volume and the tonnage. This prevents the surprise overage charge that catches homeowners who rent based on volume alone.",
  },
  "fence-removal-dumpster-rental": {
    projectDescription: "Florida's climate and termites destroy fences faster than in most other states. Wood fences in particular have a lifespan of 10-15 years in Florida's humidity before rot, termite damage, and UV degradation make replacement necessary. Hurricane season can take out entire fence lines in a single night. Whether you are replacing a rotted privacy fence, removing a damaged chain link perimeter, clearing a vinyl fence that has become brittle and broken, or tearing down an old fence before installing a new one, the debris needs a container. Fence panels are long and awkward, posts have concrete bases that are heavy, and hardware (nails, screws, brackets) is scattered throughout. A dumpster makes fence disposal simple.",
    sizingGuide: "Most residential fence removal projects fit in a 10 yard dumpster. A standard 6-foot privacy fence around a quarter-acre lot generates about 3-4 cubic yards of debris when panels are broken down to manageable lengths. If you are also removing the concrete post bases (which you should, especially if installing a new fence), add weight but not much volume. For larger properties (half acre or more) or when combining fence removal with other landscaping work, a 20 yard is the safer choice.",
    weightTips: "Wood fence panels are relatively light — the lumber from a full perimeter fence weighs 500-1,000 lbs. The real weight is in the concrete fence post bases. A standard 4x4 post with a 2-foot deep, 12-inch diameter concrete footing weighs about 75 lbs per post. A yard with 30-40 posts adds 2,250-3,000 lbs of concrete alone. Chain link fencing is light (the fabric and rails from a full yard weigh a few hundred pounds) but the posts and concrete bases add the same weight as wood fencing. Account for the post bases in your weight planning.",
    bestPractices: "Break fence panels into 4-6 foot sections for easy loading. Remove fence boards from rails when possible to flatten the material and maximize dumpster space. Pull posts with their concrete bases intact if possible — trying to separate the post from the concrete is usually not worth the effort. Stack concrete bases flat on the bottom of the dumpster. For chain link, roll the fabric into manageable bundles. Separate metal components (chain link fabric, metal posts, hardware) if you want to take them to a scrap yard for value.",
    whyUs: "Fence removal is a straightforward project that most homeowners can do themselves with a dumpster in the driveway. We make the disposal part easy: order with a text, get same-day or next-day delivery, load at your own pace, and we pick up when you are done. For fence contractors doing multiple jobs per week, our volume pricing and priority scheduling keep your crew moving between projects without waiting for containers.",
  },
};

const defaultServiceContent = {
  projectDescription: "This type of project generates significant waste that needs professional disposal. Whether you are a homeowner tackling a DIY project, a contractor managing a job site, or a property manager overseeing maintenance, having the right dumpster on site makes the difference between an efficient project and a logistical nightmare. Roll-off dumpsters eliminate the need for multiple dump runs, keep your workspace clean and safe, and let you focus on the actual work instead of waste management. We deliver the right size container to your location, you load it at your own pace, and we haul it away when you are done.",
  sizingGuide: "Choosing the right dumpster size depends on the scope of your project and the type of materials you are disposing of. A 10 yard dumpster holds approximately 4 pickup truck loads and works well for small cleanouts, single-room renovations, and minor demolition projects. A 20 yard dumpster holds about 8 pickup truck loads and is our most popular size — it handles kitchen and bathroom renovations, roofing tear-offs, estate cleanouts, and medium-sized construction projects. A 30 yard dumpster holds roughly 12 pickup truck loads and is built for large construction, whole-house renovations, and commercial cleanouts. When in doubt, size up — the price difference between sizes is typically $50-100, while ordering a second dumpster costs $300+ extra.",
  weightTips: "Every dumpster has an included weight limit: 2 tons for 10 yard, 3 tons for 20 yard, and 4 tons for 30 yard containers. Most household and general construction debris comes in well under these limits. The materials that push you over are dense items like concrete, brick, tile, stone, dirt, and roofing shingles. If your project involves these heavy materials, let us know when you book so we can recommend the right size and set appropriate weight expectations. Separating heavy materials from lighter debris into different loads often saves money compared to one overloaded mixed container.",
  bestPractices: "Load the dumpster from back to front, placing heavy items on the bottom and lighter items on top. Break down large items to maximize space — disassemble furniture, flatten boxes, cut long boards into manageable lengths. Use the rear swing door for walk-in loading of heavy items rather than lifting them over the sides. Keep the load level and below the fill line — nothing can extend above the top of the dumpster walls. Distribute weight evenly across the container rather than piling everything on one side. Cover the dumpster with a tarp during rain to prevent water weight accumulation.",
  whyUs: "We provide flat-rate pricing with no hidden fees — the number we quote includes delivery, pickup, the rental period, and disposal up to the weight limit. Same-day delivery is available when you order before noon. Our 7-day standard rental period gives you plenty of time for most projects, and extensions are available at a reasonable daily rate. We answer our phone, we show up on time, and we do exactly what we say we will do. Our reputation across Florida is built on reliability and honesty, not on clever marketing.",
};

export function getMoneyPageContent(service: Service, neighborhood: Neighborhood): MoneyPageContent {
  const { name: sName } = service;
  const { name: nName, region } = neighborhood;
  const sLower = sName.toLowerCase();
  const sc = serviceContent[service.slug] || defaultServiceContent;

  const heroDescription = `Need ${sLower} in ${nName}? We deliver 10, 20, and 30 yard roll-off dumpsters throughout ${nName} and the ${region} area with same-day or next-day delivery. Flat-rate pricing, no hidden fees, and a 7-day rental period included with every container. Whether your project is residential, commercial, or contractor-managed, we have the right dumpster at the right price. Text or call for an instant quote.`;

  const sections: { heading: string; content: string }[] = [
    {
      heading: `About ${sName} in ${nName}`,
      content: `${sc.projectDescription} In ${nName} and throughout ${region}, we see these projects year-round. Florida's climate, growth rate, and housing stock create constant demand for dumpster service — and we are positioned to deliver fast, reliable service every time. Whether your project is on a quiet residential street in ${nName} or at a busy commercial site, we handle the waste removal so you can focus on the work.`,
    },
    {
      heading: `Choosing the Right Dumpster Size for Your ${nName} Project`,
      content: `${sc.sizingGuide} For projects in ${nName} specifically, we keep inventory staged across ${region} to ensure fast delivery of all three sizes. If you are unsure which size fits your project, text us a description or photos and we will recommend the right container. Getting the size right the first time saves you money and avoids project delays.`,
    },
    {
      heading: `Weight Limits and Heavy Materials`,
      content: sc.weightTips,
    },
    {
      heading: `How ${sName} Works in ${nName}`,
      content: `The process is straightforward. Contact us with your ${nName} delivery address, the dumpster size you need (or describe your project and we will recommend one), and your preferred delivery date. We confirm availability and give you a flat-rate quote. On delivery day, our driver places the dumpster exactly where you want it — typically on your driveway, but we can also place on streets (with permit if required), parking lots, construction pads, and other hard surfaces. You load at your own pace over the 7-day rental period. When you are done, text or call us and we schedule pickup within 24 hours. The entire process is designed to be simple, transparent, and hassle-free.`,
    },
    {
      heading: "Best Practices for Loading Your Dumpster",
      content: sc.bestPractices,
    },
    {
      heading: `Delivery and Logistics in ${nName}`,
      content: `Our delivery fleet covers all of ${region} with same-day service available for orders placed before noon. For ${nName} deliveries, our drivers are familiar with the local roads, traffic patterns, and common placement challenges. We need approximately 60 feet of straight-line approach for the roll-off truck and about 23 feet of vertical clearance for overhead wires and trees. If your driveway is narrow, curved, has a steep grade, or has low-hanging branches, let us know when you book so we can plan the best approach. We send a photo confirmation after delivery so you can verify placement even if you are not on site.`,
    },
    {
      heading: `Permits and Local Regulations in ${nName}`,
      content: `Placing a dumpster on your own private property in ${nName} generally requires no permit. If the dumpster needs to go on a public street, sidewalk, or right-of-way, you will likely need a permit from your local municipality or county. Permit requirements vary across ${region} — some areas require them for any street placement, while others are more relaxed. Costs typically range from $25 to $150 with 1-3 business day processing. When you give us your delivery address, we will tell you exactly what is required and can guide you through the process. We have placed dumpsters in every part of ${region} and know the local rules.`,
    },
    {
      heading: `Flat-Rate Pricing in ${nName}`,
      content: `Every dumpster rental in ${nName} includes flat-rate pricing: delivery, a 7-day rental period, pickup, and disposal up to the included weight limit — all in one price. There is no separate delivery fee, fuel surcharge, environmental fee, or pickup charge. Our 10 yard dumpsters start at $275, 20 yard at $350, and 30 yard at $450. Exact pricing depends on your specific location within ${region} and the type of debris you are disposing of. The quote we give you is the price on your invoice, guaranteed. The only potential additional charge is a per-ton overage fee if your load exceeds the included weight limit — and we help you avoid that by recommending the right size for your project.`,
    },
    {
      heading: `Why ${nName} Customers Choose Us`,
      content: sc.whyUs,
    },
    {
      heading: `What Can Go in Your Dumpster in ${nName}`,
      content: `Accepted materials include household furniture, appliances (refrigerant must be removed from fridges and AC units), drywall, lumber, roofing shingles, concrete, brick, tile, carpet, vinyl flooring, yard waste, cardboard, general junk, and most construction and demolition debris. Prohibited materials include hazardous waste, asbestos, liquid paint, chemicals, pesticides, propane tanks, batteries, medical waste, and tires in quantities over four. These restrictions are set by Florida state law and landfill regulations — they apply everywhere in ${region}, not just in ${nName}. If you are unsure about a specific item, text us a photo and we will confirm immediately.`,
    },
  ];

  return { heroDescription, sections };
}
