-- Adopted from legacy hand-run migration: 2026_07_23_tenant_sms_from_number.sql
-- Original commit date (git first-add): 2026-07-22T20:32:23-04:00
-- STATUS: part of the baseline. Assumed already live in prod as of
-- the 2026-07-28 cutover -- marked applied without re-running, per
-- docs/adr/0008-migration-tool-cutover.md. Do NOT re-run against prod.
-- Optional override for the "from" address used by admin/owner notification
-- SMS (smsAdmins/lib/sms.ts), for tenants whose voice DID
-- (tenants.telnyx_phone) isn't SMS-messaging-enabled — e.g. a dedicated
-- toll-free voice-only line with no Telnyx messaging profile attached.
-- NULL (falls back to telnyx_phone) for every tenant that doesn't need the
-- split.
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS sms_from_number text;
