import type { Neighborhood } from "./siteData";

export const statenIslandNeighborhoods: Neighborhood[] = [
  {
    name: "Annadale",
    slug: "annadale",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A quiet, family-oriented South Shore neighborhood with tree-lined streets, single-family homes, and easy access to beaches and parkland.",
    landmarks: ["Annadale Green", "Blue Heron Park", "Wolfe's Pond Park"],
    vibe: "Suburban family-friendly",
  },
  {
    name: "Arden Heights",
    slug: "arden-heights",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A sprawling residential community on the South Shore known for its newer housing developments, shopping centers, and peaceful suburban character.",
    landmarks: ["Arden Heights Woods", "Woodrow United Methodist Church", "Arden Heights Boulevard shops"],
    vibe: "Modern suburban",
  },
  {
    name: "Arlington",
    slug: "arlington",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A small North Shore neighborhood near the Bayonne Bridge with industrial roots and waterfront views of the Kill Van Kull.",
    landmarks: ["Bayonne Bridge", "Arlington Marsh", "Mariners Marsh Park"],
    vibe: "Industrial waterfront",
  },
  {
    name: "Arrochar",
    slug: "arrochar",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A compact East Shore neighborhood nestled between Fort Wadsworth and the Verrazano-Narrows Bridge, offering stunning views of New York Harbor.",
    landmarks: ["Verrazano-Narrows Bridge", "Fort Wadsworth", "Von Briesen Park"],
    vibe: "Scenic and residential",
  },
  {
    name: "Bay Terrace",
    slug: "bay-terrace",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A small, quiet neighborhood on the southeastern shore known for its waterfront homes, bay views, and proximity to Great Kills Harbor.",
    landmarks: ["Great Kills Harbor", "Bay Terrace waterfront", "Hylan Boulevard"],
    vibe: "Waterfront residential",
  },
  {
    name: "Bloomfield",
    slug: "bloomfield",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A small West Shore neighborhood transitioning from its industrial past, located near the former Fresh Kills Landfill site now being transformed into a massive park.",
    landmarks: ["Freshkills Park", "Main Creek", "Richmond Avenue corridor"],
    vibe: "Transitional and evolving",
  },
  {
    name: "Brighton Heights",
    slug: "brighton-heights",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A hilly North Shore neighborhood with panoramic views, Victorian-era homes, and a strong sense of community identity.",
    landmarks: ["Clove Lakes Park", "Brighton Heights Reformed Church", "Henderson Avenue shops"],
    vibe: "Historic hilltop community",
  },
  {
    name: "Bulls Head",
    slug: "bulls-head",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A central Staten Island neighborhood anchored by the busy Richmond Avenue commercial corridor, offering diverse dining and shopping options.",
    landmarks: ["Richmond Avenue shopping district", "Bulls Head Historical Society", "Willowbrook Park nearby"],
    vibe: "Commercial and diverse",
  },
  {
    name: "Castleton Corners",
    slug: "castleton-corners",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A centrally located neighborhood at the crossroads of Victory Boulevard and Manor Road, known for its Italian-American heritage and local eateries.",
    landmarks: ["Victory Boulevard corridor", "Castleton Corners shopping area", "Reed Basket Willow Swamp Park"],
    vibe: "Central hub with character",
  },
  {
    name: "Charleston",
    slug: "charleston",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A rapidly growing South Shore neighborhood with new retail developments, residential communities, and access to the Outerbridge Crossing.",
    landmarks: ["Charleston Shopping Center", "Outerbridge Crossing", "Clay Pit Ponds State Park Preserve"],
    vibe: "Growing suburban",
  },
  {
    name: "Chelsea",
    slug: "chelsea-staten-island",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A small, quiet neighborhood on the West Shore with waterfront access and a mix of residential properties near the Travis community.",
    landmarks: ["Chelsea waterfront", "Victory Boulevard", "Travis Avenue"],
    vibe: "Quiet and secluded",
  },
  {
    name: "Clifton",
    slug: "clifton",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A diverse Northeast Shore neighborhood known for its Sri Lankan community, vibrant dining scene along Bay Street, and proximity to the waterfront.",
    landmarks: ["Bay Street corridor", "Clifton train station", "Edgewater Park"],
    vibe: "Diverse and multicultural",
  },
  {
    name: "Concord",
    slug: "concord",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A residential neighborhood in the eastern part of the island with a mix of housing styles and convenient access to the Staten Island Expressway.",
    landmarks: ["Staten Island Expressway", "Concord village green", "Targee Street shops"],
    vibe: "Accessible residential",
  },
  {
    name: "Dongan Hills",
    slug: "dongan-hills",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A leafy, upscale East Shore neighborhood with colonial-era roots, featuring stately homes on tree-lined streets and excellent views from its hillside properties.",
    landmarks: ["Dongan Hills station", "Richmond Road", "Old Town Road historic area"],
    vibe: "Upscale and historic",
  },
  {
    name: "Egbertville",
    slug: "egbertville",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A small, tucked-away neighborhood between Todt Hill and the Greenbelt, prized for its natural surroundings and quiet residential streets.",
    landmarks: ["Staten Island Greenbelt", "Egbertville Ravine", "Rockland Avenue"],
    vibe: "Nature-surrounded and peaceful",
  },
  {
    name: "Elm Park",
    slug: "elm-park",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A compact North Shore neighborhood with a diverse population, local shops along Morningstar Road, and easy access to the Kill Van Kull waterfront.",
    landmarks: ["Morningstar Road shops", "Elm Park station", "Kill Van Kull waterfront"],
    vibe: "Walkable and diverse",
  },
  {
    name: "Eltingville",
    slug: "eltingville",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A large, family-friendly South Shore neighborhood with strong community ties, local sports leagues, and access to beaches along the waterfront.",
    landmarks: ["Eltingville Transit Center", "Great Kills Park nearby", "Hylan Boulevard shopping"],
    vibe: "Active family community",
  },
  {
    name: "Emerson Hill",
    slug: "emerson-hill",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "An affluent hillside neighborhood named after Ralph Waldo Emerson, offering stunning harbor views and large homes on winding, wooded roads.",
    landmarks: ["Emerson Hill viewpoints", "Douglas Road estates", "Staten Island Academy"],
    vibe: "Exclusive and scenic",
  },
  {
    name: "Fort Wadsworth",
    slug: "fort-wadsworth",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A historic military site at the foot of the Verrazano-Narrows Bridge, now a National Recreation Area with sweeping views of New York Harbor.",
    landmarks: ["Fort Wadsworth", "Battery Weed", "Verrazano-Narrows Bridge overlook"],
    vibe: "Historic and scenic",
  },
  {
    name: "Graniteville",
    slug: "graniteville",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A centrally located neighborhood with a mix of residential and commercial areas, known for its proximity to the College of Staten Island and shopping.",
    landmarks: ["College of Staten Island nearby", "South Avenue", "Graniteville quarry site"],
    vibe: "Central and convenient",
  },
  {
    name: "Grant City",
    slug: "grant-city",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A cozy midland neighborhood with a village feel, centered around its train station and a walkable strip of shops and restaurants on Lincoln Avenue.",
    landmarks: ["Grant City train station", "Lincoln Avenue shops", "Midland Field"],
    vibe: "Small-town village feel",
  },
  {
    name: "Grasmere",
    slug: "grasmere",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A residential neighborhood on the East Shore known for its well-kept homes, hilly terrain, and proximity to both Hylan Boulevard and the waterfront.",
    landmarks: ["Hylan Boulevard", "Grasmere station", "Miller Field nearby"],
    vibe: "Quiet and well-established",
  },
  {
    name: "Great Kills",
    slug: "great-kills",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A vibrant South Shore neighborhood with a thriving main street, marina, and beach park — a year-round community with strong Italian-American roots.",
    landmarks: ["Great Kills Park", "Great Kills Harbor & Marina", "Nelson Avenue shopping district"],
    vibe: "Lively shore community",
  },
  {
    name: "Greenridge",
    slug: "greenridge",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A residential area between Eltingville and Heartland Village, featuring single-family homes and a suburban atmosphere with easy highway access.",
    landmarks: ["Greenridge Plaza", "Staten Island Railway nearby", "Arthur Kill Road"],
    vibe: "Quiet suburban",
  },
  {
    name: "Grymes Hill",
    slug: "grymes-hill",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "One of Staten Island's most prestigious neighborhoods, perched atop a glacial ridge with spectacular Manhattan skyline views and home to Wagner College.",
    landmarks: ["Wagner College", "Grymes Hill viewpoints", "Howard Avenue estates"],
    vibe: "Prestigious and panoramic",
  },
  {
    name: "Hamilton Park",
    slug: "hamilton-park",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A small, historic enclave on the North Shore featuring Victorian-era cottages, winding lanes, and a village-like atmosphere rare in New York City.",
    landmarks: ["Hamilton Park Cottage Colony", "St. John's Episcopal Church", "Franklin Avenue"],
    vibe: "Historic cottage enclave",
  },
  {
    name: "Heartland Village",
    slug: "heartland-village",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A busy commercial and residential hub centered around the Staten Island Mall, offering extensive shopping, dining, and entertainment options.",
    landmarks: ["Staten Island Mall", "Platinum Boulevard", "Heartland Village shopping area"],
    vibe: "Commercial and bustling",
  },
  {
    name: "Huguenot",
    slug: "huguenot",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A spacious South Shore neighborhood named after French Protestant settlers, featuring large-lot homes, wooded areas, and a strong family community.",
    landmarks: ["Huguenot Avenue", "Blue Heron Park Preserve", "Huguenot train station"],
    vibe: "Spacious and family-oriented",
  },
  {
    name: "Lighthouse Hill",
    slug: "lighthouse-hill",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A secluded hilltop neighborhood home to the only inland lighthouse in New York, offering wooded lots, architectural gems, and a rural feel within the city.",
    landmarks: ["Staten Island Range Light", "Jacques Marchais Museum of Tibetan Art", "Lighthouse Hill Park"],
    vibe: "Secluded and artistic",
  },
  {
    name: "Livingston",
    slug: "livingston",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A central North Shore neighborhood with a diverse residential community, local shopping along Bard Avenue, and proximity to Snug Harbor Cultural Center.",
    landmarks: ["Bard Avenue historic homes", "Livingston station", "Snug Harbor Cultural Center nearby"],
    vibe: "Diverse and central",
  },
  {
    name: "Manor Heights",
    slug: "manor-heights",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A hilly residential neighborhood in central Staten Island known for its elevated terrain, split-level homes, and convenient access to the expressway.",
    landmarks: ["Manor Road", "Willowbrook Park nearby", "Manor Heights overlooks"],
    vibe: "Elevated suburban",
  },
  {
    name: "Mariners Harbor",
    slug: "mariners-harbor",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A North Shore waterfront neighborhood with deep maritime history, diverse communities, and ongoing revitalization along the Kill Van Kull.",
    landmarks: ["Mariners Harbor Houses", "South Avenue waterfront", "Prall's Island bird sanctuary"],
    vibe: "Maritime heritage community",
  },
  {
    name: "Meiers Corners",
    slug: "meiers-corners",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A central residential neighborhood at the junction of several major roads, offering a convenient location with local shopping and community parks.",
    landmarks: ["Victory Boulevard", "Meiers Corners shopping", "Clove Lakes Park nearby"],
    vibe: "Convenient crossroads",
  },
  {
    name: "Midland Beach",
    slug: "midland-beach",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "An East Shore beachfront neighborhood with a boardwalk, community playgrounds, and a resilient spirit rebuilt after Hurricane Sandy.",
    landmarks: ["Midland Beach boardwalk", "Franklin D. Roosevelt Boardwalk", "Miller Field"],
    vibe: "Resilient beach community",
  },
  {
    name: "New Brighton",
    slug: "new-brighton",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A historic North Shore neighborhood that was once Staten Island's premier resort area, now home to Snug Harbor Cultural Center and diverse communities.",
    landmarks: ["Snug Harbor Cultural Center & Botanical Garden", "New Brighton Village Hall", "Sailors' Snug Harbor"],
    vibe: "Cultural and historic",
  },
  {
    name: "New Dorp",
    slug: "new-dorp",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A bustling mid-island neighborhood with a lively shopping lane, beach access, and deep Dutch colonial roots dating back to the 1600s.",
    landmarks: ["New Dorp Lane shopping district", "New Dorp Beach", "New Dorp Moravian Church and Cemetery"],
    vibe: "Bustling and historic",
  },
  {
    name: "New Springville",
    slug: "new-springville",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A central neighborhood anchored by the Staten Island Mall and major retail corridors, serving as the island's primary commercial hub.",
    landmarks: ["Staten Island Mall", "Korean War Veterans Parkway", "Richmond Hill Road"],
    vibe: "Retail and residential hub",
  },
  {
    name: "Oakwood",
    slug: "oakwood",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A South Shore neighborhood blending suburban living with beach access, featuring the scenic Oakwood Beach area and connections to Great Kills Park.",
    landmarks: ["Oakwood Beach", "Great Kills Park trailhead", "Oakwood station"],
    vibe: "Beachside suburban",
  },
  {
    name: "Ocean Breeze",
    slug: "ocean-breeze",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A small East Shore neighborhood that was heavily impacted by Hurricane Sandy and is now partly transformed into wetland parkland for flood protection.",
    landmarks: ["Ocean Breeze Park", "Ocean Breeze Fishing Pier", "Father Capodanno Boulevard"],
    vibe: "Resilient and transforming",
  },
  {
    name: "Old Place",
    slug: "old-place",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "One of Staten Island's smallest and most isolated neighborhoods, a quiet enclave on the West Shore surrounded by wetlands and industrial areas.",
    landmarks: ["Old Place Creek", "Arthur Kill waterfront", "Western Avenue"],
    vibe: "Isolated and quiet",
  },
  {
    name: "Old Town",
    slug: "old-town",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "One of the oldest settled areas on Staten Island, a small neighborhood preserving early colonial history near the crossroads of major island roads.",
    landmarks: ["Old Town Road", "Historic Richmond Road", "Dongan Hills colonial sites nearby"],
    vibe: "Historic and quaint",
  },
  {
    name: "Park Hill",
    slug: "park-hill",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A hillside neighborhood on the North Shore known for its apartment complexes, diverse community, and views toward the Verrazano-Narrows Bridge.",
    landmarks: ["Park Hill Apartments", "Sobel Court Park", "Vanderbilt Avenue"],
    vibe: "Diverse hilltop community",
  },
  {
    name: "Pleasant Plains",
    slug: "pleasant-plains",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A southern neighborhood with a suburban feel, quiet streets, and proximity to Conference House Park at the island's southernmost tip.",
    landmarks: ["Pleasant Plains station", "Conference House Park nearby", "Amboy Road corridor"],
    vibe: "Peaceful southern suburb",
  },
  {
    name: "Port Ivory",
    slug: "port-ivory",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A remote West Shore industrial area named after the Procter & Gamble Ivory soap factory that once operated here, now largely warehouses and wetlands.",
    landmarks: ["Former Ivory soap factory site", "Western Avenue industrial area", "Arthur Kill shoreline"],
    vibe: "Industrial and remote",
  },
  {
    name: "Port Richmond",
    slug: "port-richmond",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A vibrant, diverse North Shore neighborhood with a bustling commercial avenue, strong Mexican-American community, and rich 19th-century architecture.",
    landmarks: ["Port Richmond Avenue shopping district", "Veterans Park", "Reformed Church on Staten Island"],
    vibe: "Vibrant and multicultural",
  },
  {
    name: "Prince's Bay",
    slug: "princes-bay",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A scenic South Shore neighborhood with waterfront access on Raritan Bay, a historic lighthouse, and a relaxed coastal atmosphere.",
    landmarks: ["Prince's Bay Lighthouse", "Lemon Creek Park", "Prince's Bay train station"],
    vibe: "Coastal and laid-back",
  },
  {
    name: "Randall Manor",
    slug: "randall-manor",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A small, leafy North Shore neighborhood with handsome older homes, quiet streets, and proximity to Snug Harbor Cultural Center.",
    landmarks: ["Randall Manor homes", "Snug Harbor nearby", "Bard Avenue"],
    vibe: "Leafy and genteel",
  },
  {
    name: "Richmond Valley",
    slug: "richmond-valley",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A far South Shore neighborhood near the Outerbridge Crossing, offering a suburban feel with easy access to New Jersey and the island's southern parks.",
    landmarks: ["Outerbridge Crossing", "Richmond Valley train station", "Arthur Kill Road"],
    vibe: "Southern gateway",
  },
  {
    name: "Richmondtown",
    slug: "richmondtown",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "The historic heart of Staten Island, home to a restored colonial village museum and the county courthouse, preserving centuries of island history.",
    landmarks: ["Historic Richmond Town", "Richmond County Courthouse", "St. Andrew's Church"],
    vibe: "Historic and civic",
  },
  {
    name: "Rosebank",
    slug: "rosebank",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A diverse East Shore neighborhood with strong Italian-American roots, home to the Garibaldi-Meucci Museum and vibrant local culture.",
    landmarks: ["Garibaldi-Meucci Museum", "Our Lady of Mount Carmel Grotto", "Alice Austen House nearby"],
    vibe: "Cultural and spirited",
  },
  {
    name: "Rossville",
    slug: "rossville",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A quiet South Shore neighborhood with an industrial waterfront on the Arthur Kill, known for its historic ship graveyard and Sandy Ground heritage.",
    landmarks: ["Arthur Kill Ship Graveyard (Rossville Boatyard)", "Rossville AME Zion Church", "Blazing Star Burial Ground"],
    vibe: "Historic and off-the-beaten-path",
  },
  {
    name: "St. George",
    slug: "st-george",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "The civic and cultural capital of Staten Island, home to the ferry terminal, borough hall, and a growing arts and dining scene along the waterfront.",
    landmarks: ["St. George Ferry Terminal", "National Lighthouse Museum", "Staten Island Museum at Snug Harbor"],
    vibe: "Civic center and cultural hub",
  },
  {
    name: "Sandy Ground",
    slug: "sandy-ground",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A historically significant community founded by free Black oystermen in the 1800s, one of the oldest continuously inhabited free Black settlements in the U.S.",
    landmarks: ["Sandy Ground Historical Society Museum", "Rossville AME Zion Church", "Bloomingdale Road"],
    vibe: "Historic and culturally significant",
  },
  {
    name: "Shore Acres",
    slug: "shore-acres",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A quiet East Shore residential neighborhood with waterfront homes, harbor views, and a close-knit community atmosphere.",
    landmarks: ["Shore Acres waterfront", "Von Briesen Park nearby", "Hylan Boulevard"],
    vibe: "Waterfront and close-knit",
  },
  {
    name: "Silver Lake",
    slug: "silver-lake",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A North Shore neighborhood centered around the scenic Silver Lake Park reservoir, offering green space, a golf course, and wooded walking paths.",
    landmarks: ["Silver Lake Park", "Silver Lake Golf Course", "Victory Boulevard"],
    vibe: "Green and recreational",
  },
  {
    name: "South Beach",
    slug: "south-beach",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A lively East Shore beach community with a long boardwalk, ocean views, and a family-friendly atmosphere that comes alive in summer months.",
    landmarks: ["South Beach Boardwalk", "Fountain of Dolphins", "Ocean Breeze Athletic Complex"],
    vibe: "Beachfront and active",
  },
  {
    name: "Stapleton",
    slug: "stapleton",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A diverse, revitalizing North Shore neighborhood with a growing waterfront development, historic rowhouses, and an emerging arts scene.",
    landmarks: ["Stapleton Waterfront", "Tappen Park", "Stapleton Houses"],
    vibe: "Revitalizing and diverse",
  },
  {
    name: "Sunnyside",
    slug: "sunnyside-staten-island",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A small residential neighborhood on the North Shore with modest homes, local character, and proximity to Clove Lakes Park.",
    landmarks: ["Clove Lakes Park nearby", "Clove Road", "Sunnyside campus area"],
    vibe: "Modest and residential",
  },
  {
    name: "Todt Hill",
    slug: "todt-hill",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "The highest point on the Atlantic coastal plain and Staten Island's most exclusive neighborhood, featuring grand estates, manicured grounds, and celebrity residents.",
    landmarks: ["Todt Hill summit (highest point on the eastern seaboard south of Maine)", "Staten Island Greenbelt", "Ocean Terrace"],
    vibe: "Elite and exclusive",
  },
  {
    name: "Tompkinsville",
    slug: "tompkinsville",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A walkable North Shore neighborhood adjacent to the ferry terminal, with a diverse food scene, local shops on Victory Boulevard, and growing energy.",
    landmarks: ["Tompkinsville Park", "Victory Boulevard shops", "Bay Street Landing"],
    vibe: "Walkable and energetic",
  },
  {
    name: "Tottenville",
    slug: "tottenville",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "The southernmost neighborhood in New York City, a charming waterfront community with Victorian homes, the historic Conference House, and small-town appeal.",
    landmarks: ["Conference House", "Tottenville Beach", "Main Street Tottenville"],
    vibe: "Small-town waterfront charm",
  },
  {
    name: "Travis",
    slug: "travis",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A tight-knit West Shore community known for its annual Fourth of July parade — the oldest continuously running Independence Day celebration in the country.",
    landmarks: ["Travis Fourth of July Parade route", "Wild Avenue", "Long Neck Creek"],
    vibe: "Patriotic and tight-knit",
  },
  {
    name: "Ward Hill",
    slug: "ward-hill",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A small, elevated neighborhood between Stapleton and Grymes Hill with harbor views, mature trees, and a secluded residential atmosphere.",
    landmarks: ["Ward Hill overlooks", "Stapleton Heights", "Van Duzer Street"],
    vibe: "Elevated and secluded",
  },
  {
    name: "West Brighton",
    slug: "west-brighton",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A central North Shore neighborhood with a diverse community, Forest Avenue shopping, and direct access to the green oasis of Clove Lakes Park.",
    landmarks: ["Clove Lakes Park", "Forest Avenue commercial district", "Corporal Thompson Park"],
    vibe: "Diverse and community-driven",
  },
  {
    name: "Westerleigh",
    slug: "westerleigh",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A charming, historically dry neighborhood founded as a temperance community in the 1880s, featuring Queen Anne homes and a tight-knit community spirit.",
    landmarks: ["Westerleigh Park", "Watchogue Road", "Westerleigh Improvement Society"],
    vibe: "Charming and community-minded",
  },
  {
    name: "Willowbrook",
    slug: "willowbrook",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A central neighborhood home to the College of Staten Island campus and Willowbrook Park, with a history tied to the former Willowbrook State School.",
    landmarks: ["College of Staten Island", "Willowbrook Park", "Carousel for All Children"],
    vibe: "Academic and parkside",
  },
  {
    name: "Woodrow",
    slug: "woodrow",
    borough: "Staten Island",
    boroughSlug: "staten-island",
    description: "A quiet, semi-rural neighborhood on the South Shore with wooded lots, newer developments, and proximity to Clay Pit Ponds State Park Preserve.",
    landmarks: ["Clay Pit Ponds State Park Preserve", "Woodrow Road", "Sandy Ground Historic Area nearby"],
    vibe: "Semi-rural and natural",
  },
];
